### ISSUE TITLE
[v1.0.0b] - Mealplan sorts by added time instead of breakfast,lunch,dinner

### ISSUE THREAD

**Issue by coffee-mage** [mealie-recipes/mealie#1000]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

This may fall under 'working as intended'.  I noticed meal planner sorts meals based on added time instead of breakfast/lunch/dinner.

<img width="242" alt="mealplan" src="https://user-images.githubusercontent.com/14890934/155297911-7a44ed88-5c32-40ea-8ac2-794c370ff08e.png">

### Deployment

Other

### Deployment Details

beta.mealie.io

**Comment by namelivia** [comment]
:wave: Hello, sorry if this is not the best place to post this but... How can you add several items per day to the meal planner like shown in the screencap? I've been trying to figure out how to add breakfast lunch and dinner to the planner but I have not been able and couldn't find any info on the documentation or the Github issues.

Is it only on v1.0?

**Comment by hay-kot** [comment]
@namelivia, this is only in v1.0. The meal-planner has been completely rewritten.

**Comment by tmllull** [comment]
Hi! Is there any update about this? I notice that you can move the recipes between days, but not reorder in the same day to rearrange it.

For now, the only way to keep the "logical" order (breakfast-lunch-dinner) is adding the recipes in reverse order (dinner-lunch-breakfast), but the if You want to swap some recipes between days, this order can be broken again.

**Comment by hay-kot** [comment]
I'm planning on changing this so you can adjust the order, but it's a lower priority right now.

**Comment by Grygon** [comment]
Just to document while poking at meal-plan issues: It looks like this is resolved in nightly. Added these randomly:
![image](https://github.com/hay-kot/mealie/assets/647846/c5dca818-3623-4603-858f-8e16e21338c4)
