### ISSUE TITLE
[v1.0.0b] - Ingredient Parser -- can't delete ingredient

### ISSUE THREAD

**Issue by coffee-mage** [mealie-recipes/mealie#1009]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When using the ingredient parser, if you decide you don't want an ingredient.  The red delete button doesn't seem to work.

### Deployment

Other

### Deployment Details

beta.mealie.io

**Comment by hay-kot** [comment]
I've removed the button from the parser page, thanks!

-  #1015
