### ISSUE TITLE
[v1.0.0b] - Ingredient Parser -- If you try to parse recipe that already has been parsed.

### ISSUE THREAD

**Issue by coffee-mage** [mealie-recipes/mealie#1010]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

If I build a recipe,  parse it, save it.  Then later edit, and try to parse again.  The parser seems to ignore the existing amount,unit, food items and only tries to parse the note.   Because most of the ingredients have no note,  or only an actual note item (e.g. minced).  This will mangle the recipe.

Also if I try to parse and decide it's a bad idea.  Should there be a cancel button?  The only way I could find to get out of parser was back button on web browser.

### Deployment

Other

### Deployment Details

beta.mealie.io

**Comment by hay-kot** [comment]
> If I build a recipe, parse it, save it. Then later edit, and try to parse again. The parser seems to ignore the existing amount,unit, food items and only tries to parse the note. Because most of the ingredients have no note, or only an actual note item (e.g. minced). This will mangle the recipe.

Parsing ingredients multiple times isn't really something I'm planning on supporting. I don't really think there's much that needs to be done here. I suppose there could be some kind of warning? 

>Also if I try to parse and decide it's a bad idea. Should there be a cancel button? The only way I could find to get out of parser was back button on web browser.

There is a cancel button on the left hand side on the action bar.

**Comment by coffee-mage** [comment]
Apparently i'm blind,  there is a cancel button.  ;)  

On the parsing.  It makes sense that you don't support parsing multiple times.  I would suggest either a warning message, or if people have food/unit/amounts in the recipe already, the parsing button is disabled.

**Comment by wrobelda** [comment]
@hay-kot I just run into an issue where I duplicated a recipe, since the steps are the same, but needed to edit the ingredients. I bulk added them and realized Parsing is greyed out. This definitely is a valid use case for letting recipe be parased again, isn't it?
