### ISSUE TITLE
[v1.0.0b] - Attaching ingredients to steps doesn't display in cook mode, and cook mode nukes the ingredient/step link.

### ISSUE THREAD

**Issue by coffee-mage** [mealie-recipes/mealie#1011]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

https://beta.mealie.io/recipe/mini-cheesecake
When I try to attach ingredients (step3, butter, sugar, graham cracker) to steps in the recipe, it appears to attach properly (see screenshot).
![image](https://user-images.githubusercontent.com/14890934/155862229-2b26e3ef-d571-477f-a325-b02a0005f933.png)

When I go into 'cook mode', it doesn't display the ingredients to the step I attached it to.
![image](https://user-images.githubusercontent.com/14890934/155862246-a881858d-6d08-435c-8e12-e399121a0ed6.png)

After I go back to recipe (after cook mode), and edit recipe.  Attached ingredients are gone.
![image](https://user-images.githubusercontent.com/14890934/155862260-3495990a-b8a2-478e-81d0-a0d90b9e5694.png)

### Deployment

Other

### Deployment Details

beta.mealie.io

**Comment by hay-kot** [comment]
These don't appear to be saving at all. will look into it.

**Comment by hay-kot** [comment]
fixed in 🎉 

-  #1015
