### ISSUE TITLE
[v1.0.0b] - Instructions section not displaying 'Section' titles

### ISSUE THREAD

**Issue by jrcatoe** [mealie-recipes/mealie#1012]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When adding section titles to the instructions, they show immediately after saving the changes, but once you refresh the page, they only show when in 'edit' mode.

Adding section title:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/22477725/155867514-bdcb2022-8867-4f41-98d6-c28f3d78a4f6.png">

Immediately after saving the changes:
<img width="773" alt="image" src="https://user-images.githubusercontent.com/22477725/155867538-e93310e7-2053-4253-90ea-57c1b24f5603.png">

After refreshing the page:
<img width="772" alt="image" src="https://user-images.githubusercontent.com/22477725/155867547-e0db1e44-2c4c-44c9-8f72-be45e81d7729.png">

Back in edit mode:
<img width="770" alt="image" src="https://user-images.githubusercontent.com/22477725/155867562-aee5bdbf-116f-467a-bb29-7afb95809df8.png">

And the cycle repeats.

### Deployment

Other

### Deployment Details

Using beta site: https://beta.mealie.io/recipe/mini-cheesecake

**Comment by hay-kot** [comment]
Thanks for this (and other) the bugs reports! fixed in

-  #1015
