### ISSUE TITLE
[v1.0.0b] - Can't delete unit

### ISSUE THREAD

**Issue by jrcatoe** [mealie-recipes/mealie#1013]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I created a bad unit on the beta site and cannot delete it:
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/22477725/155868100-a99776f0-eba1-4bee-a953-5d137404d05d.png">

If you click 'Delete', you get a popup as expected:
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/22477725/155868142-c36efe18-a258-4e65-ae72-39b3e38a4bd9.png">

But then nothing happens.

### Deployment

Other

### Deployment Details

Using beta site: https://beta.mealie.io/admin/toolbox/units

**Comment by hay-kot** [comment]
This has been fixed. Admin Toolbox has been removed, and not Foods/Units are managed by each group - See Here https://beta.mealie.io/group/data/units
