### ISSUE TITLE
Nextcloud Cookbook import error (UNIQUE constraint failed)

### ISSUE THREAD

**Issue by carnager** [mealie-recipes/mealie#1016]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

On a fresh install Mealie gives me errors when importing my Nextcloud cookbook database. Half of my recipes could not be imported.

Error message:

```
(sqlite3.IntegrityError) UNIQUE constraint failed: recipes.slug [SQL: INSERT INTO recipes (name, description, image, total_time, prep_time, perform_time, cook_time, recipe_yield, "recipeCuisine", slug, rating, org_url, date_added, date_updated, favorited_by_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)] [parameters: ('Gnocchi - Thunfisch - Auflauf', 'Gnocchi - Thunfisch - Auflauf. Über 279 Bewertungen und für mega befunden. Mit ► Portionsrechner ► Kochbuch ► Video-Tipps! Jetzt entdecken und ausprobieren!', 'https://img.chefkoch-cdn.de/rezepte/1219561227436669/bilder/922654/crop-960x540/gnocchi-thunfisch-auflauf.jpg', '30 Minutes', '30 Minutes', None, None, '4', None, 'gnocchi-thunfisch-auflauf', None, 'https://www.chefkoch.de/rezepte/1219561227436669/Gnocchi-Thunfisch-Auflauf.html', '2022-02-28', '2022-02-28 08:58:39.237452', None)] (Background on this error at: https://sqlalche.me/e/14/gkpj) 
```

### Deployment

Docker (Linux)

### Mealie Version

0.5.6

**Comment by carnager** [comment]
ok... i indeed overlooked a similar issue and the import is actually working. Sorry.

**Comment by vdbrink** [comment]
I have this same issue with manual adding a new recipe.
Is there a way to manual fix this because it's not in a new version yet.

UPDATE: The name of the recipe was already existing.
