### ISSUE TITLE
[v1.0.0b] - All built-in ingredients have "-" instead of white spaces

### ISSUE THREAD

**Issue by achurak** [mealie-recipes/mealie#1025]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Brand new install of mealie v1.0.0b. For some reason all built-in ingredients have dashes instead of white spaces (olive-oil, baking-soda, acorn-squash, etc.) which prevents the food parser from correctly recognizing them and thus requires to either select the "dashed" ingredient manually or to create a "white space" version of it as offered by the parser.

![image](https://user-images.githubusercontent.com/12438813/157497439-2fe6885c-8eba-4665-8d70-df0fd613f30d.png)

### Deployment

Other

### Deployment Details

Standard sqlite deployment on k8s if it makes any difference.

**Comment by hay-kot** [comment]
This has been fixed with 

- #1026 

Once the build is complete (about an hour) you'll be able to pull the new container down and restart your application. During startup the foods with '-' will be renamed to their appropriate value.

Thanks for reporting this!
