### ISSUE TITLE
Manually editing recipe JSON and saving does not work

### ISSUE THREAD

**Issue by hilmarp** [mealie-recipes/mealie#1044]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Manually editing the JSON for a recipe and saving does not work.

The `ref` it's trying to use is `undefined`.

![Screenshot from 2022-03-13 10-55-49](https://user-images.githubusercontent.com/2643080/158056830-84d0b043-6841-4674-93ed-d65360b826c8.png)

### Deployment

Docker (Linux)

### Mealie Version

v0.5.6

**Comment by redshiva** [comment]
I am having the same issue.
