### ISSUE TITLE
[v1.0.0b] - When parsing ingredients you can create multiple units with the same name

### ISSUE THREAD

**Issue by Sennevds** [mealie-recipes/mealie#1050]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When I was looking at the list of units I saw there where a lot of units with the name 'gram' but all have a different Id:
![image](https://user-images.githubusercontent.com/3531609/158127650-de2de4b8-2b81-469a-9beb-1eae8a54c3ef.png)
I also noticed the parser never prepopulates the unit when the ingredient is in grams so there's something wrong there.

Maybe (but that should be a different issue I think) there should be a wat to merge units (and ingredients).

### Deployment

Docker (Linux)

**Comment by Lycolus** [comment]
I noticed a similar behavior while using the abbreviation 'g'. Hope that helps in any way.

**Comment by hay-kot** [comment]
Closing in favor of https://github.com/mealie-recipes/mealie/issues/2510 where more discussion has occurred
