### ISSUE TITLE
[v1.0.0b] - ALLOW_SIGNUP doesn't work

### ISSUE THREAD

**Issue by Tukks** [mealie-recipes/mealie#1054]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I'm currently switching from mealie 0.x to 1.x beta.
I disabled with my docker compose the environement variable ALLOW_SIGNUP
- ALLOW_SIGNUP=false

And I can create account from the login page.

expeted : can't create new account without a invitation link

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
Thanks for letting me know! There was actually a lot wrong with the registration flow. Should be fixed up once the most recent PR's are built. You can track the build here:

- https://github.com/hay-kot/mealie/actions/runs/1990201480 

additionally `ALLOW_SIGNUP ` has moved from the frontend ENV to the backend ENV so be sure to update your docker-compose.

**Comment by Tukks** [comment]
@hay-kot Tested and work great
![image](https://user-images.githubusercontent.com/5930169/158805903-7cd56cc5-22f9-4a20-bcc4-7e8312266c81.png)

Thank for you work
