### ISSUE TITLE
[v1.0.0b] - Can't upload/import images

### ISSUE THREAD

**Issue by Nelinski** [mealie-recipes/mealie#1057]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I can't upload any images, either for the user profile picture or for recipes. When a recipe is created, it doesn't import the image either. I also can't import an image via a URL. Happy to provide any additional details, just let me know what you need.

### Deployment

Unraid

### Deployment Details

Running on Unraid, behind a reverse proxy as a subdomain (using NGINX).

**Comment by hay-kot** [comment]
Can you first verify that the data directory is mounted on the frontend container? This is a relatively recent change that has caught a few people up. See the docker-compose for an example

https://nightly.mealie.io/documentation/getting-started/installation/sqlite/

If that's setup correctly, can you provide the logs for the API container?

**Comment by Nelinski** [comment]
Bingo, that was it thanks. I did have the data directory mounted on the frontend container, but it was pointing to a separate location to the api container. Pointing the frontend container to the same one as the api container fixed it. Thanks.
