### ISSUE TITLE
[v1.0.0b] - No indication of successful/failed password or username profile changes

### ISSUE THREAD

**Issue by jcookin** [mealie-recipes/mealie#1074]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When changing anything in the "Personal Information" section or the password (only tested as an admin), there is no notification if the changes succeeded or failed. I had typo'd the original password when changing passwords, and when logging back in found the new password had not been applied.

### Proposed Solution

A Toast indicating success states or any other simple indicator would easily resolve this issue.

### Deployment

Docker (Linux)

### Deployment Details

Hosted on a Ubuntu 20.04.3 machine, docker-compose with SQLite DB, and accessed via Brave Browser 98.1.35.101

**Comment by hay-kot** [comment]
Thanks for the feedback! Should be fixed in the next build 🎉
