### ISSUE TITLE
[v1.0.0b] [Task] - Create Page Should Use Nested Routes Instead of Tabs

### ISSUE THREAD

**Issue by hay-kot** [mealie-recipes/mealie#1083]
### What is the problem this task addresses?

https://beta.mealie.io/recipe/create?tab=url is managed by a tab view instead of nested routes which reduces performance and increases load times. The code is also fairly complicated because of the multi-purpose usage of the route.

### Proposed/Possible Solution(s)?

Use Nuxt nested routes to reduce code complexity and split code.

See This Route for Example Implementation:

- https://beta.mealie.io/group/data/foods

**Comment by PFischbeck** [comment]
I started to tackle this, but ran into an issue. Some of these tabs, e.g., the bulk URL importer, have two parts to them: the smaller element on top, and more wide content at the bottom. Using `NuxtChild` doesn't seem feasible here, as this would only capture one of the two elements. If it would cover both, most of the abstraction and shared structure would be lost.
This actually seems like a place where Vue 3's `Teleport` would come in handy, which we can't use yet... We could also use `portal-vue`, but that would be an additional dependency. What do you think?

**Comment by hay-kot** [comment]
I think my initial plan was to take each Nested Page and split it into it's own file and render that content inside of the Parent Page. I think all that would be required would be to move the bottom nav buttons around? Here's a basic layout of what I was thinking - let me know if that makes sense or not. 

**Before**
```html
<MainPage> 
  <PageTitle/>
  <PageNav/>

   <DynamicChild/>
     
   <PageNavBottom/>
   
   <DynamicChildExtended/>
<MainPage>
```

 **After**

```html
<MainPage> 
  <PageTitle/>
  <PageNav/>

   <NestedRoute>
        <DynamicChild>
        <DynamicChildExtended/>
    </NestedRoute>    

   <PageNavBottom/>
<MainPage>
```
