### ISSUE TITLE
[v1.0.0b] - decimal numbers for ingredient quantity stored as integer

### ISSUE THREAD

**Issue by tbleiker** [mealie-recipes/mealie#1091]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

The corresponding column for the ingredient quantity (_quantity_ in able _recipes_ingredients_) is defined as _integer_.

In the ingredients list, the quantity can be specified as decimal number, but when you (re)load the recipe, the decimal places are not shown.

### Deployment

Docker (Linux)

### Deployment Details

most current frontend-nigthly (013e0ae0d902) and api-nightly (da7c7613bfcc) with **PostgreSQL**

**Comment by hay-kot** [comment]
Huh, apparently this isn't an issue with SQLite because it doesn't restrain types assigned to columns which is why I never noticed this. 

The annoying part is that alembic migrations doesn't appear to work very well in translating this change so it's going to require some work to get this to work seamlessly.

**Comment by hay-kot** [comment]
I believe I've got the basic migration necessary in #1093 - will probably take a bit to get this tested and merged so if you're in a hurry I'd suggest move to SQLite. The Backup/Restore should allow you to move back and forth between databases.

**Comment by tbleiker** [comment]
I am not in a hurry. I have just started to test your app (which btw, looks awesome! 😄 thx a lot for the effort you are putting into this project!). 

I quickly glanced over your commits. They look reasonable. If I find some time in the next days, I will test them out.

**Comment by hay-kot** [comment]
Change has been merged and built into the latest image. Let me know how the upgrade process goes 👍

**Comment by tbleiker** [comment]
I pulled the new containers and it seems to work!

However, I will stick to sqlite for now. I keep the postgresql database as playground and will report anything suspicious :smile:
