### ISSUE TITLE
[v1.0.0b] [Task] - Keep Original Text on Ingredient Parse

### ISSUE THREAD

**Issue by hay-kot** [mealie-recipes/mealie#1094]
### What is the problem this task addresses?

Currently scraping the recipe ingredients is destructive and might result in bad data being saved. 

### Proposed/Possible Solution(s)?

Add a 'original_text' field in the database and save this field on parse so we can reference it later if necessary.

- [x] Backend Text Capture
- [x] Frontend View

**Comment by Miroito** [comment]
I'm currently working on this.
