### ISSUE TITLE
[v1.0.0b] - Food filter not working

### ISSUE THREAD

**Issue by tbleiker** [mealie-recipes/mealie#1103]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

The "Food Filter" on the search page does not seem to work. Selecting food gives me an empty page.

### Deployment

Docker (Linux), Docker (Windows)

### Deployment Details

most current frontend-nigthly (da57184c5690) and api-nightly (4ed3545a8de7) with sqlite

**Comment by hay-kot** [comment]
Should be fixed in the latest build

**Comment by tbleiker** [comment]
yep, working now!

btw: thx a lot for the effort you put into this awesome project! :smile:
