### ISSUE TITLE
[v1.0.0b] [Task] - Optional Import Keywords as Tags

### ISSUE THREAD

**Issue by hay-kot** [mealie-recipes/mealie#1105]
### What is the problem this task addresses?

Currently recipes that are scraped from the web do not include any of the tags/keywords

### Proposed/Possible Solution(s)?

Based on a user selection (checkbox on scraper page) create and assign the keywords associated with a recipe

**Comment by Miroito** [comment]
I'm interested to take that one if no one else is already on it.

**Comment by Miroito** [comment]
This is not possible atm. 
The first recipe scraper that is tried is using a package called [recipe-scraper](https://github.com/hhursev/recipe-scrapers) and it does not scrape the whole standard [schema](https://schema.org/Recipe) for the most known websites.
see that in [their scraper template file](https://github.com/hhursev/recipe-scrapers/blob/main/templates/scraper.py), the keyword property is missing which means it is not returned (if available at all on this website).

This package is not great to be honest, it seems to rely on maintenance to support more websites wħen there is a standard defined [here](https://developers.google.com/search/docs/advanced/structured-data/intro-structured-data) by Google on where websites that want to be referenced by Google Search have to put their recipe data.

The second scraper is irrelevant as long as the first scraper sends back a recipe object. I have not yet checked whether this one was retrieving said keywords.

**Comment by hay-kot** [comment]
> This package is not great to be honest, it seems to rely on maintenance to support more websites wħen t[here](https://developers.google.com/search/docs/advanced/structured-data/intro-structured-data) is a standard defined here by Google on where websites that want to be referenced by Google Search have to put their recipe data.

This library does support the standard schema in addition to their custom scrapers. The custom scrapers exists because a wide variety of websites don't support the Schema.org standard. It's a good package and the best optional available. 

If you look at how we're implementing this you can see that we first try to use their internal scrapers which does a lookup to see if a custom scraper has been implemented, if it hasn't we fallback to "wild_mode" which will use the schema you're describing. 

As far as implementing it, it should be possible by accessing the `scraped_schema.schema.data` dictionary which looks like it captures the Schema.org and some other properties.

**Comment by Miroito** [comment]
Seems I assumed some things that aren't true about this library. 
I'll take a look if I can get the whole schema out and if you're right then it should easy to continue.
