### ISSUE TITLE
[v1.0.0b] [Task] - Add Fuzzy Search to Categories, Tags, and Tools Pages

### ISSUE THREAD

**Issue by hay-kot** [mealie-recipes/mealie#1108]
### What is the problem this task addresses?

It's difficult to find Categories, Tags, or Tools when there are many

### Proposed/Possible Solution(s)?

Use the Fuse library to implement fuzzy search for those pages.

**Comment by ritikBhandari** [comment]
So these `Categories`, `Tags` and `Tools` pages exist but difficult to find and that is why we need to implement fuzzy search.
Is that correct?

**Comment by hay-kot** [comment]
> So these `Categories`, `Tags` and `Tools` pages exist but difficult to find and that is why we need to implement fuzzy search.
> Is that correct?

Yes, it would be these pages

- https://beta.mealie.io/recipes/categories
- https://beta.mealie.io/recipes/tags
- https://beta.mealie.io/recipes/tools

**Comment by ritikBhandari** [comment]
Sure.
Can I work on this?

**Comment by hay-kot** [comment]
> Sure.
> Can I work on this?

Absolutely!

**Comment by ritikBhandari** [comment]
Thank you :)

**Comment by zierbeek** [comment]
so a new search box should be added to these pages as well?
