### ISSUE TITLE
[v1.0.0b] [Task] - Add Page For Users Favorite Recipes

### ISSUE THREAD

**Issue by hay-kot** [mealie-recipes/mealie#1109]
### What is the problem this task addresses?

There is no way to see all of your favorite recipes

### Proposed/Possible Solution(s)?

Implement a page that shows all your favorite recipes

**Comment by ritikBhandari** [comment]
So there are two things to be done:

1. Add a 'favourite' button to add the items to the favourites list.
2. Make a favourite page to show the items.

Am I going right?

**Comment by hay-kot** [comment]
> So there are two things to be done:
> 
> 1. Add a 'favourite' button to add the items to the favourites list.
> 2. Make a favourite page to show the items.
> 
> Am I going right?

Actually the hearts on the recipes toggle favorites and all the API's exists

https://beta.mealie.io/docs#/Users%3A%20Favorites

Should just need to implement the page.

**Comment by ritikBhandari** [comment]
But dont you think if the hearts were created to toggle favourites, the page for the same should have been created simultaneously?

**Comment by ritikBhandari** [comment]
Would u mind if I work on this?

**Comment by hay-kot** [comment]
Go for it!

**Comment by ritikBhandari** [comment]
Thanks!

**Comment by mostlyvirtual** [comment]
How is this task different from this page? /user/1/favorites
