### ISSUE TITLE
[v1.0.0b] - Import Receipe Bookmarklets does not work

### ISSUE THREAD

**Issue by TheDarthFather** [mealie-recipes/mealie#1115]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I am trying to create a Bookmarklets as per the documentation.
The link opens in a new browser window, but the recipe is not imported.

```
var url = document.URL ;
var mealie = "http://mealie.mydomain.com/"
var dest = mealie + "/?recipe_import_url=" + url
window.open(dest, '_blank') 
```

**Result:**
https://mealie.mydomain.com/?recipe_import_url=https%3A%2F%2Fwww.acouplecooks.com%2Fbreakfast-vegetable-scramble%2F

### Deployment

Docker (Linux)

**Comment by zierbeek** [comment]
Thought it would be as easy as this. But getting a 404 unfortunately.

```
var url = document.URL ;
var mealie = "http://mealie.mydomain.com/"
var dest = mealie + "/create?tab=url&recipe_import_url=" + url
window.open(dest, '_blank') 
```

I guess you would first need to authenticate with a long live token?

**Comment by hay-kot** [comment]
```
window.open("https://mealie.yourdomain.com/recipe/create" + "/?recipe_import_url=" + document.URL + "&tab=url", '_blank') 
```

This one will work as far as inputting the text, but there isn't a listener on the page to check for a URL when the page is rendered. That still needs to be added.

**Comment by hay-kot** [comment]
Fixed with the latest build 🎉

**Comment by TheDarthFather** [comment]
I updated the docker, I have the same issue.
This is my bookmark .. created with the editor suggeted on wiki ... what do I miss ?
`javascript:(function()%7Bvar url %3D document.URL %3B%0Avar mealie %3D "https%3A%2F%2FMYSUBDOMAIN.COM"%0Avar dest %3D mealie %2B "%2F%3Frecipe_import_url%3D" %2B url%0Awindow.open(dest%2C '_blank')%7D)()%3B`

**Comment by hay-kot** [comment]
@TheDarthFather - You need to update your bookmarklet to with the snippet I posted above. 

![CleanShot 2022-04-02 at 11 23 29](https://user-images.githubusercontent.com/64056131/161398150-517750d7-f495-4230-9a54-79a8b076b12c.png)

**Comment by TheDarthFather** [comment]
Works! Thank you!

**Comment by ghuser238490** [comment]
Maybe something changed in 
Version v1.0.0beta-5, Build 9e77a9f367d9f2cf704054842613b6ba399841a2

It only works for me when adding `/url` to the URL:

`window.open("https://mealie.yourdomain.com/recipe/create/url" + "/?recipe_import_url=" + document.URL + "&tab=url", '_blank') `

**Comment by BatteryPower** [comment]
need to update documentation with this change :)

**Comment by snickers2k** [comment]
why not having a simple drag-and-drop button?
this is one of the biggest issues i have with mealie .. of the most important things is to easily import recipes from other sites while browsing - this needs to work out of the box without fiddling
