### ISSUE TITLE
[v1.0.0b] - Error message on the screen when saving a recipe that has a comment

### ISSUE THREAD

**Issue by blueline13** [mealie-recipes/mealie#1123]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When a comment is added to a recipe and then the recipe is changed, an error window appears. Changes are not saved. If the comment is deleted, the recipe can be changed without errors.

### Deployment

Other

### Deployment Details

See recipe:
https://beta.mealie.io/recipe/forloren-hare

**Comment by hay-kot** [comment]
Should be fixed in the latest build - you may need to delete comments before being able to re-save them. Had to do with a validation error on the backend so it was storing UUIDs as numbers - hard to come back from that one :(

**Comment by blueline13** [comment]
Thank you very much for this extrem quick fix.
