### ISSUE TITLE
[v1.0.0b] - Cookbooks Should Provide an And/Or Filter Option for Categories/Tags/Tools

### ISSUE THREAD

**Issue by blueline13** [mealie-recipes/mealie#1128]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

In the new cookbook Dialog, the elements within 
Categories or Tags or Tools are now Logical AND Linked. 
Category1 **AND** Category2 **AND** Category3

In older versions they were logical OR Linked.
Category1 **OR** Category2 **OR** Category3

Please re-enable the old config or add a selection for each item (Category, Tags and Tools) "AND" or "OR" for the type of link.

### Deployment

Other

### Deployment Details

See at  https://beta.mealie.io/group/cookbooks

**Comment by hay-kot** [comment]
Do you mind providing a little more detail on how you're using cookbooks so I can get a better idea of how they're being used?

**Comment by blueline13** [comment]
I will gladly try to describe my approach.

When I scan and create my cookbooks, each paper cookbook gets its own category. Now these individual cookbooks are to be summarized in a cookbook of Mealie. As an example, several cookbooks from India are summarized under the Mealie cookbook "India". This is now my idea for what I want to use the cookbooks in Mealie.

Yes I could also create an additional category India and then show only the one category. In my opinion this is not so flexible and I have to select an additional category every time.

If my idea is not completely discarded then it would be good to do this via an "AND" / "OR" field on the line, if the effort is not too great. 

Better to understand now?

**Comment by hay-kot** [comment]
Thanks! 

I'm not super sure how folks are using cookbooks so it's hard to make good decisions to improve them. That was helpful. I think that implementing an And/Or switch should be fairly straight forward and would be really beneficial in improving the flexibility of them. I'll take a look at that in the next couple of days.

**Comment by blueline13** [comment]
That sounds good. Thank you for your quick support.

**Comment by hay-kot** [comment]
> That sounds good. Thank you for your quick support.

Sure thing! Here's the quick implementation I worked up. 

In this case each filter (Tags, Categories, and Tools) can be made to filter by AND/OR by using the require toggle. This DOES NOT work across fields so each criteria set by Tags, Categories and Tools have to be met for the recipe to be included... I think that meets your use case? 

![CleanShot 2022-04-03 at 11 37 23](https://user-images.githubusercontent.com/64056131/161445089-a210e682-6dc9-4411-9454-dcdebedbc630.png)

**Comment by blueline13** [comment]
This looks really SUPER. That makes it easier for me again and gives more flexibility for all! 👍

**Comment by hay-kot** [comment]
Fixed! feature is live in the latest build and on the demo site 🎉
