### ISSUE TITLE
Search function not finding recipe

### ISSUE THREAD

**Issue by tjjunior** [mealie-recipes/mealie#1139]
Program works great, thank you so much.  I'm running vers 0.5.6 via Unraid, so this may already be fixed in the v1.0.  I'm searching for the term "chili."  Here are the results that come up in order:

1. Chili hot cocoa
2. Ground turkey chili
3. Of the next 8 results, none have chili in the title (e.g. Salsa Chicken, Spinach Pinwheels, etc)

But what does not show up is a recipe called Laura's Quick Slow Cooker Turkey Chili.  When I search for the term Laura, it shows up, but not when I search for chili.  Let me know if you need something to see what's going on.  Or since the focus is on 1.0, no worries if the functionality has changed and so won't be an issue once I upgrade.  But just wanted to call out there is some sort of an error in the logic in case it's helpfu.

**Comment by doctorjames** [comment]
I've observed this behaviour too in beta3

**Comment by hay-kot** [comment]
For context, this has to do with how Fuzzy search works in general. It grades each token match in a string, in this case the title, by the position it is in the title. So if the matched token is later in the title, it will score lower than those that are earlier. 

The unfortunate nature of fuzzy search is that it can be super intuitive and helpful, but it can also yield odd results, as you've found. Not sure there's much we can do here - although I would like to move search to the server side using built in SQL functions instead, so that may resolve this issue.

**Comment by doctorjames** [comment]
The thing that people will find frustrating (and assume is a bug) is not finding the exact word entered (because it's later in the title, as you explained). Does this position weighting need to be there? 

If you could eventually add a server side search, maybe using an ILIKE %term% style SQL query, you could merge that (assigning a high score for sorting) with the weighted fuzzy search results you have at the moment. This would eliminate the unexpected failure to find the exact word entered, while also offering all the existing fuzzy search benefits.

**Comment by michael-genson** [comment]
One thing we could try is to do a literal search first, then a fuzzy search. i.e. if the word is literally in the title, return that result, then return the fuzzy results afterwards. Not sure how much that would improve things (or if it's worth the extra computation time).

**Comment by hay-kot** [comment]
We use the [Fuse Library](https://fusejs.io/api/options.html) on the frontend which has many different options, but from what I understand, it always uses position to determine score. 

> If you could eventually add a server side search, maybe using an ILIKE %term% style SQL query, you could merge that (assigning a high score for sorting) with the weighted fuzzy search results you have at the moment. This would eliminate the unexpected failure to find the exact word entered, while also offering all the existing fuzzy search benefits.

This is the approach I'm likely to take. The entire search API needs to be rewritten for server-side other-wise we need to load ALL the recipes on the frontend to perform an iterative search which can be slow. Some users have thousands of recipes (much to my surprise) and find it impossible to use the search functionality. This a probably a week or two of work so I haven't had time to really dig into it with some of the other things we're working on, but it's on my list. I'll write up a task this evening so we can put it on the schedule and I can lay out the scope.

**Comment by doctorjames** [comment]
My missing search results were all where the word was significant to the recipe (i.e. what kind of thing it was) but appeared near the end of a longish title. I just had a skim of the documentation to Fuse and this could be a stopgap until the server side search becomes a more significant priority:

---
## Fuzzy Matching Options

### `ignoreLocation`

- Type: `boolean`
- Default: `false`

When `true`, search will ignore `location` and `distance`, so it won't matter where in the string the pattern appears.

* [Documentation](https://fusejs.io/concepts/scoring-theory.html#distance-threshold-and-location)

---

I like this extended search syntax, though had better not get too used to it if we're moving away from this library:

---
## Extended Search

This form of advanced searching allows you to fine-tune results.

White space acts as an **AND** operator, while a single pipe (`|`) character acts as an **OR** operator. To escape white space, use double quote ex. `="scheme language"` for exact match.

| Token       | Match type                 | Description                            |
| ----------- | -------------------------- | -------------------------------------- |
| `jscript`   | fuzzy-match                | Items that fuzzy match `jscript`       |
| `=scheme`   | exact-match                | Items that are `scheme`                |
| `'python`   | include-match              | Items that include `python`            |
| `!ruby`     | inverse-exact-match        | Items that do not include `ruby`       |
| `^java`     | prefix-exact-match         | Items that start with `java`           |
| `!^earlang` | inverse-prefix-exact-match | Items that do not start with `earlang` |
| `.js$`      | suffix-exact-match         | Items that end with `.js`              |
| `!.go$`     | inverse-suffix-exact-match | Items that do not end with `.go`       |

White space acts as an **AND** operator, while a single pipe (`|`) character acts as an **OR** operator.

* [Documentation](https://fusejs.io/examples.html#extended-search)
