### ISSUE TITLE
[v1.0.0b] - Error in processing the quantity of ingredients

### ISSUE THREAD

**Issue by Seehundkuschler** [mealie-recipes/mealie#1140]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

If the quantity specification "2-3" is used in the list of ingredients, all subsequent ingredients are no longer displayed after saving and calling up again. If only "1" or "2" etc. is used, the error does not occur. Sorry, i hope this helps. I'm new to Docker.

### Deployment

Other

### Deployment Details

docker linux on qnap nas TS-230, sql, hkotel/mealie:api-nightly, hkotel/mealie:frontend-nightly from April 4. 2022

**Comment by hay-kot** [comment]
If you're using the Quantity column on the recipe then this is expected. The database only supports integer of floating point numbers so "2-3" isn't a supported type. To use a range you'd either have to disable the quantity and use the notes field for the recipe or add a note that the quantity can be 2-3 of an item. I don't think it's feasible to add the ability to add ranges like that.

It's probably worth looking the UI element and limiting inputs to only valid integers / characters.

**Comment by Seehundkuschler** [comment]
Thank you very much for the explanation. Yes, that makes sense to me. It would be good then if already when entering, or at the latest when saving, the cell input would be checked for validity. Otherwise it happens that one has entered a lot, saves and then the entire recipe including the steps is deleted. Then only the ingredients up to the wrong "1-2" entry remain with me. The rest is deleted after a new call. Maybe someone else makes the same mistake as me, because that is often given with such recipes and is simply entered without thinking about it.
