### ISSUE TITLE
Docker Container Security Vulnerabilities

### ISSUE THREAD

**Issue by samcro1967** [mealie-recipes/mealie#1141]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Amazing project and appreciate all of your work!  The latest docker container has 35 fixable critical and high security vulnerabilities.  Hoping you can push a new image with updates.  Project seems very active so hoping this can be added the next time a code update happens.

### Deployment

Docker (Linux)

### Mealie Version

0.5.6

**Comment by hay-kot** [comment]
Can you provide some more context here? 

> The latest docker container has 35 fixable critical and high security vulnerabilities. 

This doesn't really give me any information to go on. 

1. How did the scan the docker image?
2. What are the issues in the container?
3. How are you determining "fixable" 
4. Are you willing to submit a PR to address any of these issues? 

---

Right now I'm focused on getting v1 ready for release, so this isn't something I'm going to be actively working on in the 0.5.x branches. Happy to accept any PR's that do address these issue though.

**Comment by samcro1967** [comment]
Scan using the following:
```
curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b .
docker save hkotel/mealie:latest --output meailie.tar
grype --only-fixed docker-archive:./meailie.tar | grep -i -E '(High|Critical)'
```
It will generate output showing security vulnerabilities that have fixes available.  Normally "docker build -t mealie ." will build a new image with the latest versions and address all of them provided old versions of packages are not specified in the Dockerfile.

I did not share the list here as it is not generally considered good practice to publicly share security vulnerabilities of an application.

Not sure a PR here makes sense, but happy to help if I can.  The Docker image needs recreated with updates to the installed packages and pushed to the public repo.

Understandable to focus on the latest branches.  Might be a step to add as you move forward with newer branches.  I can automate cloning the repo locally and updating for short term security needs.

THANK YOU AGAIN FOR THIS PRODCT!  Wife loves it.
