### ISSUE TITLE
[v1.0.0b] [Task] - Allow Users to Use Seed Data (Units, Foods, Labels)

### ISSUE THREAD

**Issue by hay-kot** [mealie-recipes/mealie#1148]
### What is the problem this task addresses?

Currently Mealie provides seed data to bootstrap your installation with English only translations of common Units, Foods, and Labels. Soon or already (depending on when you see this) These will be available to translate on Crowdin. Since multiple translations are now available users should be able to select which seed data they would like to use instead of populating the default selection.

### Proposed/Possible Solution(s)?

See Comments and provide a 👍  for your preferred solution

**Comment by hay-kot** [comment]
### Solution 1 - Default to English

In this solution we would still default and auto seed the database with the English translations, however we would add a "Seed" and "Delete All" action to the frontend to allow users to easily remove and replace with their translations.

**Comment by hay-kot** [comment]
### Solution 2 - No Defaults

In this solution we would no longer seed the database by default. Every group would have to perform a seed action on their own via the UI. This would allow every group to use their own language from the start. The downside here is that it would be an extra step for every user.

**Comment by Tukks** [comment]
The solution 2 seems better, when you create your group, ask what the use want to be seeded.

**Comment by simgunz** [comment]
> The solution 2 seems better, when you create your group, ask what the use want to be seeded.

This is a great idea. Though I would keep an option to seed manually later and in multiple languages.

My use case: I need both Italian ingredients and English ingredients.

**Comment by hay-kot** [comment]
Solution #2 should be in the next build. Thanks for the feedback!

**Comment by terrapinlogo** [comment]
Could we also get seed data for tools, tags, and categories.
Extending on from that could we get an option to seed with a user provided csv file. This would be useful for bulk adding extra data/community sourced data
