### ISSUE TITLE
[v1.0.0b] - Ingredients do not get parsed correctly, Is there a way to use brute force by default?

### ISSUE THREAD

**Issue by AIndoria** [mealie-recipes/mealie#1154]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I think this image would be self-explanatory. As you can see, instead of adding the ingredient units based on the parser, it just adds 1 and then adds the rest to "Notes" instead:

![image](https://user-images.githubusercontent.com/8932732/163268822-1b6006cb-7cec-4cc5-9c7a-8df710218f3a.png)

![image](https://user-images.githubusercontent.com/8932732/163268927-00b7fe0c-5e66-4044-a7da-300e335b2f96.png)

Further, when I put something through the NLP parser, it doesn't actually do anything, but the Brute force one works. How do I change from NLP to Brute by default?

![image](https://user-images.githubusercontent.com/8932732/163269104-9fd950bb-ba22-49c1-931e-148422e0fb3a.png)

![image](https://user-images.githubusercontent.com/8932732/163269122-a92ef05e-784a-4e0f-9bc3-01a9bffeea4a.png)

Did I miss a compilation or some file when I built and compiled it from scratch?

### Deployment

Other

### Deployment Details

I compiled my own from the mealie-next branch and built my own docker images. Running on Ubuntu 20.04.

**Comment by hay-kot** [comment]
Pretty sure this is a setup issue. Your example works fine on the beta site. Also, when you import a recipe it won't automatically parse the ingredients since it's likely there will be some mistakes. Instead you need to click the Parse button and manually go through and double check. That may change in the future - but that's where it is at now. 

<img width="1241" alt="CleanShot 2022-04-13 at 13 08 36@2x" src="https://user-images.githubusercontent.com/64056131/163270730-407e8cd1-2bb6-465f-ab9e-4e7b426b897e.png">


> I compiled my own from the mealie-next branch and built my own docker images. Running on Ubuntu 20.04.

Going to take a guess that this is causing all of your problems. You're likely missing the CRF++ and the NLP model that are included in the pre-built docker image. 

- Did you review the DockerFile in the repository? 
- Why are you compiling your own docker image? 

> Brute force one works. How do I change from NLP to Brute by default?

You can't at this time. Probably is reasonable to let this be set via an ENV variable  - though if you're an english speaker your results will almost always be better using the NLP model.

**Comment by AIndoria** [comment]
You might be correct (checking this as we speak). I hadn't downloaded the CRF++ model with make setup-model. this is the only thing I need to do when it comes to NLP setup, correct?

**Comment by AIndoria** [comment]
Hi,

thanks for responding so quickly.

I think I'm not explaining the "building my own docker image" appropriately. So,

>You're likely missing the CRF++ and the NLP model that are included in the pre-built docker image.

The only option I saw for this during the setup process was `make setup-model`. That is all I'd have to do, correct? (I might have missed this step tbf). This downloads the model right, but do I have to separately install CRF++ somewhere and include its location too?

Generally speaking I was making changes, doing `make frontend-build`, `make docker-prod` and going from there. Not necessarily creating my own dockerfile etc.


>Did you review the DockerFile in the repository?

I do see a few references to the CRF there but I assumed that by using `make docker-prod` they'd be included. Is it not the case?





>Why are you compiling your own docker image?

I wanted to make some potential UI customizations and thought it'd be best to do so pre-compilation rather than having to fiddle with `docker exec` mode post launch. I'm just using `make docker-prod`

**Comment by AIndoria** [comment]
Ok @hay-kot  so I did some additional stuff. I did the `make setup-model` and then `make frontend-build` followed by `make-docker-prod`, which is essentially what I am using now.

You said

>also, when you import a recipe it won't automatically parse the ingredients since it's likely there will be some mistakes. Instead you need to click the Parse button and manually go through and double check.

I don't see this. When I click Import Recipe and paste URL, it just processes it and takes me to the newly created recipe page.

Anyhow, when I parse an ingredient with NLP in the `Settings->Parser` section, it works fine now. **However**,

When I go to "Import recipes by URL" it still has the same issue of appending 1 in front of each ingredient as a unit. Do you have any idea why it might be happening or what else I might be missing?

It "parses" it properly, but for some reason still adds "1" in front in UI:

![image](https://user-images.githubusercontent.com/8932732/163283469-357be05d-395a-4ab6-9b90-4a0da91843d8.png)

**Comment by AIndoria** [comment]
So, you're partially correct. It is however, I feel, still a bug. Let me explain (I deleted my earlier haphazard research comments):


**What I did:**

Following your suggestion thinking I might have missed the CRF model download, Run `make setup-model` followed by `make frontend-build` and `make docker-prod` which *while* fixes the `Settings->Parser` NPL not showing issue, doesn't fix the addition of 1 before the recipe issue. So 1/2 done.

**What I tested further:**

1.   Take a fresh server that had never had mealie installed before.
2.  Use this URL on your documentation site to download docker-compose.yml https://nightly.mealie.io/documentation/getting-started/installation/sqlite/
3. run `docker-compose up -d`
4. Browse to Settings -> Parser, works as expected, **BUT** the ingredient list still does not. And this is with the docker images pulled from your official dockerhub repo, and *not* my customized instance.
5. When I do a debug scrape, it shows accurate information

See:

![image](https://user-images.githubusercontent.com/8932732/163289983-7c38349c-77fa-42aa-a42e-b51c76159519.png)

![image](https://user-images.githubusercontent.com/8932732/163290021-3b9f0d0d-15a4-4694-8c28-d69ea3615d51.png)

![image](https://user-images.githubusercontent.com/8932732/163290191-cc3e5169-be93-43da-a294-90677ea12878.png)

Can you confirm this is a bug on your side please?

**Comment by AIndoria** [comment]
So, you're partially correct. It is however, I feel, still a bug. Let me explain (I deleted my earlier haphazard research comments):


>stead you need to click the Parse button and manually go through and double check. 

Mmm, why does it work as expected in the demo instance at https://beta.mealie.io . I don't need to click anything there, right? I just input a recipe URL, and it parses it correctly, including the ingredient counts.

**What I did:**

Following your suggestion thinking I might have missed the CRF model download, Run `make setup-model` followed by `make frontend-build` and `make docker-prod` which *while* fixes the `Settings->Parser` NPL not showing issue, doesn't fix the addition of 1 before the recipe issue. So 1/2 done.

**What I tested further:**

1.   Take a fresh server that had never had mealie installed before.
2.  Use this URL on your documentation site to download docker-compose.yml https://nightly.mealie.io/documentation/getting-started/installation/sqlite/
3. run `docker-compose up -d`
4. Browse to Settings -> Parser, works as expected, **BUT** the ingredient list still does not. And this is with the docker images pulled from your official dockerhub repo, and *not* my customized instance.
5. When I do a debug scrape, it shows accurate information.

See:

![image](https://user-images.githubusercontent.com/8932732/163289983-7c38349c-77fa-42aa-a42e-b51c76159519.png)

![image](https://user-images.githubusercontent.com/8932732/163290291-80e9abb9-9fc8-4544-adf9-7d67fac325d2.png)


![image](https://user-images.githubusercontent.com/8932732/163290021-3b9f0d0d-15a4-4694-8c28-d69ea3615d51.png)

![image](https://user-images.githubusercontent.com/8932732/163290191-cc3e5169-be93-43da-a294-90677ea12878.png)

Can you confirm this is a bug on your side please?

**Comment by AIndoria** [comment]
So, @hay-kot , thank you, you're partially correct. It is however, I feel, still a bug. Let me explain (I deleted my earlier haphazard research comments):


>stead you need to click the Parse button and manually go through and double check. 

Mmm, why does it work as expected in the demo instance at https://beta.mealie.io . I don't need to click anything there, right? I just input a recipe URL, and it parses it correctly, including the ingredient counts.

**What I did:**

Following your suggestion thinking I might have missed the CRF model download, Run `make setup-model` followed by `make frontend-build` and `make docker-prod` which *while* fixes the `Settings->Parser` NPL not showing issue, doesn't fix the addition of 1 before the recipe issue. So 1/2 done. So, I thought "Why not just test it in a fresh, stock, mealie instance."


**What I tested further:**


1.   Take a fresh server that had never had mealie installed before.
2.  Use this URL on your documentation site to download docker-compose.yml https://nightly.mealie.io/documentation/getting-started/installation/sqlite/
3. run `docker-compose up -d`
4. Browse to Settings -> Parser, works as expected.
5. Import a new recipe from url ( https://www.allrecipes.com/recipe/263728/vegan-mug-cake-with-pineapple-and-mint/ ) **BUT** the ingredient list still does not populate accurately. And this is with the docker images pulled from your official dockerhub repo, and *not* my customized instance.
6. When I do a debug scrape, it shows accurate information.

See:

![image](https://user-images.githubusercontent.com/8932732/163289983-7c38349c-77fa-42aa-a42e-b51c76159519.png)

![image](https://user-images.githubusercontent.com/8932732/163290191-cc3e5169-be93-43da-a294-90677ea12878.png)

![image](https://user-images.githubusercontent.com/8932732/163290021-3b9f0d0d-15a4-4694-8c28-d69ea3615d51.png)

So after that, when I click on Edit on Recipe, I get this. I'm assuming 'this' is the Parse button you referenced earlier? I feel like unless you're manually entering/bulk-entering ingredients (and not importing from the URL), you should never have to click the Edit button and manually Parse the ingredients (As expected in your beta.mealie.io instance, where it just works)

![image](https://user-images.githubusercontent.com/8932732/163290291-80e9abb9-9fc8-4544-adf9-7d67fac325d2.png)


Just to reiterate, these images I'm testing are from : https://hub.docker.com/r/hkotel/mealie and not my own compilation.

Can you confirm this is a bug on your side please?

**Comment by hay-kot** [comment]
This is not an issue with the application. If you want to disable foods and units by default on all new recipes go into your group settings and disable it. Then you'll get to behavior on the beta site. You can also set this in a per instance basis in the recipe settings. 

The application does not parse out foods and units automatically when imported because it's not reliable enough to be the default behavior. Like I said in my first comment, if you want to parse the units and foods from the ingredient you can use the parse button in the recipe editor. 

I suggest you look through the site and take stock of all of the settings available to you.

**Comment by AIndoria** [comment]
>If you want to **disable foods and units by default** on all new recipes go into your group settings and disable it. Then you'll get to behavior on the beta site

Aaaah, this might be why this 'works' on beta site but it doens't on my instance. My bad, I had thought you had this enabled there as well. TYVM. 

I apologize.

**Comment by AIndoria** [comment]
> If you want to disable foods and units by default on all new recipes go into your group settings and disable it.

Ah, I see. This makes more sense. Thank you. I must have missed the fact that that particular option does that and was confused as to why the behavior wasn't working as it was in the beta site. I appreciate your help.
