### ISSUE TITLE
test_default_settings test function does not test default settings defined in AppSettings class

### ISSUE THREAD

**Issue by Miroito** [mealie-recipes/mealie#1156]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

The test_default_settings function does not do the test it is intended to do.

`monkeypatch.delenv` does not prevent the app_settings function from loading the `DEFAULT_PASSWORD` defined in the local .env file.

```
def test_default_settings(monkeypatch):
    monkeypatch.delenv("DEFAULT_GROUP", raising=False)
    monkeypatch.delenv("DEFAULT_PASSWORD", raising=False)
    monkeypatch.delenv("POSTGRES_USER", raising=False)
    monkeypatch.delenv("POSTGRES_PASSWORD", raising=False)
    monkeypatch.delenv("DEFAULT_PASSWORD", raising=False)
    monkeypatch.delenv("API_PORT", raising=False)
    monkeypatch.delenv("API_DOCS", raising=False)
    monkeypatch.delenv("IS_DEMO", raising=False)

    get_app_settings.cache_clear()
    app_settings = get_app_settings()

    assert app_settings.DEFAULT_GROUP == "Home"
    assert app_settings.DEFAULT_PASSWORD == "MyPassword"
    assert app_settings.API_PORT == 9000
    assert app_settings.API_DOCS is True
    assert app_settings.IS_DEMO is False

    assert app_settings.REDOC_URL == "/redoc"
    assert app_settings.DOCS_URL == "/docs"
```

### Deployment

Other

### Deployment Details

Dev environment. Unlikely it depends on installation.

### Mealie Version

1.0.0b

**Comment by hay-kot** [comment]
I see what you're saying. Kind of wondering if this test is even really doing anything? I feel like I'm just testing the default behavior of Pydantic which is probably not super useful.

**Comment by Miroito** [comment]
For me it is supposed to test the default hardcoded settings in the AppSettings class. The current issue is that it is not...

**Comment by Miroito** [comment]
@hay-kot What do you think? Is it worth trying to write it again so it fits its original purpose or should it disappear?

**Comment by hay-kot** [comment]
I think we can just remove it.
