### ISSUE TITLE
[v1.0.0b] [Task] - Sanitize HTML on user inputs 

### ISSUE THREAD

**Issue by hay-kot** [mealie-recipes/mealie#1159]
### What is the problem this task addresses?

User provided input is passed directly to v-html which is a security risk

### Proposed/Possible Solution(s)?

Pre-process html to remove scripts tags and possible other problematic text.

**Comment by Drumstickx** [comment]
I come from an IT security background and in my experience the best approach is to never put user-controlled content in tags that execute HTML such as `v-html`. This eliminates the risk of code execution, sanitization may miss certain edge cases.

I found only 4 occurrences of `v-html` in the code, all for executing a function in a for loop. I only have basic Vue knowledge, but maybe you know a way to achieve the same without `v-html`?

If there is no way around including user-generated input, you should use an established framework, such as https://github.com/cure53/DOMPurify that is recommended by OWASP (see https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html#html-sanitization)

**Comment by hay-kot** [comment]
Thanks for the insight, there's no other way to supper the breaking of fractions that I'm aware of without using the v-html. I was able to utilize the DOMPurify as you described with very strict settings to implement a hopefully secure way to use user input.

- #1173
