### ISSUE TITLE
[v1.0.0b] [Task] - Initial Setup "Wizard"

### ISSUE THREAD

**Issue by hay-kot** [mealie-recipes/mealie#1164]
### What is the problem this task addresses?

Mealie currently uses default credentials and default initialization methods to setup the database. This can be confusing and lead to excess issues or users looking for help in discord. 

### Proposed/Possible Solution(s)?

Mealie should provide a "Wizard" like setup that, on first run, will require the user to do the setup requirements.

- [ ] Create new  superuser user (or update default)
- [ ] Create new group (or update default)
- [ ] Choose / set group settings. 
- [ ] Initialize / seed data items taking into account the users language
- [ ] ???

Open to feedback or ideas, leave a comment below with ideas.

**Comment by stroodle96** [comment]
Would be nice to be able to configure email setup in the wizard so you don't have to use environment variables. And for setting timezones as well. 

And maybe setting language. So you could remove that from the sidebar menu.

**Comment by fluaten** [comment]
> And maybe setting language. So you could remove that from the sidebar menu.

A **setting language** per user could be practical when the browser is set to another language than the one you want mealie translate in.

I have to set the language each time I log in.. Mainly because I clean my cookie and cache each time I close the browser.

**Comment by hay-kot** [comment]
Closing, I think the current setup is sufficient and the work here is pretty significant.
