### ISSUE TITLE
Import recipes from www.bettybossi.ch

### ISSUE THREAD

**Issue by SwissOS** [mealie-recipes/mealie#1165]
hi,

I am trying to import a recipe (in french) from the Betty Bossi website. For example, this recipe:
https://www.bettybossi.ch/fr/Rezept/ShowRezept/BB_BLUB160501_0070A-40-fr

I have no idea why nothing is imported; is the website not compliant with schema.org/Recipe ? Sorry, I'm totally new to this (and not a developer).

Thanks for any pointers!

**Comment by SwissOS** [comment]
OK, after a couple of hours of looking around, I think I should ask this on https://github.com/hhursev/recipe-scrapers which is the source code being used to scrape recipes in mealie, correct?

**Comment by hay-kot** [comment]
Correct, I checked the recipe site and it doesn't provide any meta-data so nothing we can do here. That'll need to happen up stream. Thanks!
