### ISSUE TITLE
[v1.0.0b] - Parsing plural ingredients doesn't find singular ingredients in database

### ISSUE THREAD

**Issue by s-croot** [mealie-recipes/mealie#1166]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

If an ingredient is parsed which contains a plural of the food type then the parser does not find the matching food in the database if the database entry is stored as singular

For example
'3 spring onions, thinly sliced' returns:
![image](https://user-images.githubusercontent.com/64306380/164686108-d3548df6-31a3-450f-8be3-a03f5d145d6c.png)
even though 'spring onion' exists in my database:
![image](https://user-images.githubusercontent.com/64306380/164686316-0c8c07d1-4110-496a-825e-1f0c64989d54.png)

Perhaps the parser could ignore pluralisation when searching the database

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
This should be fixed in nightly: https://github.com/mealie-recipes/mealie/pull/2535

I'm going to close this for now, but if you upgrade to nightly and still experience this feel free to re-open
