### ISSUE TITLE
[v1.0.0b] - Mealie Alpha Import fails/times out when a folder is missing a .json file

### ISSUE THREAD

**Issue by nkringle** [mealie-recipes/mealie#1183]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I am in the process of switching from Mealie Alpha to Mealie Beta and am importing 750 recipes. I noticed it essentially stalled out when importing those recipes. I went through and noticed that there were more folders in my Mealie Alpha backup than actual recipes. It looks like, at some point I renamed some of my recipes in Mealie Alpha, which caused the recipe.json files to be removed but the images and assets were never removed from the folder. When I deleted all of these from the backup.zip and then re-uploaded it into Mealie Beta the migration immediately was successful. I don't know if it makes more sense to fix it in Mealie Alpha or to just handle the error case of a recipe folder missing a *.json folder (and thus skipping it)? 

Here is an example of the original recipe folder (it still has the images but not json file):
<img width="387" alt="Screen Shot 2022-04-30 at 10 37 02 PM" src="https://user-images.githubusercontent.com/11429076/166131223-7dbaa473-0b30-495b-90e0-6f4da9ded7b9.png">

Here is an example of that recipe that was renamed (the images are the same and it has all the json file):
<img width="345" alt="Screen Shot 2022-04-30 at 10 38 15 PM" src="https://user-images.githubusercontent.com/11429076/166131227-a7ae481a-3890-4fff-9503-a0a06254448e.png">

I am marking this as a V1/Beta bug although technically I think there is a bug in both. Alpha should not leave old assets around for renamed recipes and Beta should probably not freak out if it has an import with bad/missing data.

### Deployment

Other

### Deployment Details

Docker Mac with Trafiek container proxy

**Comment by hay-kot** [comment]
Just merged a fix for this, thanks for reporting!

I discovered the data bug during the v1 development and resolved it as apart of the rewrite so purging of directories should be handled. Additionally, there are some cleanup functions that can be run in the Maintenance Page on the admin section of the site to clean up some of those directories if they do happen to cary over. 

Since it's mostly resolved I'm going to leave the bug in 0.5.4 since it's already addressed in V1 and the migration _should_ take care of the error as well.
