### ISSUE TITLE
[v1.0.0b] - [solved] Problem with the Combine function in the data management of food and units

### ISSUE THREAD

**Issue by blueline13** [mealie-recipes/mealie#1190]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Found a problem with combining function of Units and Foods.

https://beta.mealie.io/recipe/test-3

I have created two ingredients and two units (Ingredients: zutat1, zutat2 // Unit: unit1, unit2). Now press the combine key in the Data Managmenet and enter the following for Food as well as for Unit and execute (Source: zutat1 Target: zutat2 // likewise for unit). From now on you will find only zutat2 and unit2 in the data mangement. Also in the recipe itself it is now displayed correctly and zutat2 and unit2 is shown. So far so good.

But if you edit the recipe or create a new one, you can still select either zutat1 or unit1. But zutat1 or unit1 can no longer be edited or deleted in Data Management. So that it can no longer be selected in the recipe. 

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
I think this is just a caching issues. It looks like the issue doesn't persist if you reload the page.

**Comment by blueline13** [comment]
I tried this again and after Combine den reloaded the web page, after that it displayed correctly. I tested this with Windows10 and Firefox, Brave and Edge. 

If you can't implement a workaround via software, then a hint window would certainly help everyone. 

Thanks for the help!
