### ISSUE TITLE
[v1.0.0b] - Missing dictionary paths

### ISSUE THREAD

**Issue by Miroito** [mealie-recipes/mealie#1208]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

The path categoy.catergories is not reachable for all dictionaries.
It is called for example in `frontend/components/Domain/Recipe/RecipeCategoryTagToolPage.vue` but it is not in `fr-FR.json` nor in the German file.

I have not checked more dictionary files.
The path `tool.tools` seems to suffer the same fate.

### Deployment

Other

### Deployment Details

Does not depend on deployment

**Comment by hay-kot** [comment]
Finally got it working, thanks for pointing this out 🎉
