### ISSUE TITLE
[v1.0.0b] - Mealy_Alpha Migration error

### ISSUE THREAD

**Issue by josemariaaraujo** [mealie-recipes/mealie#1211]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When migrating a backup from v0.5.6 I get a "Failed to import" error for every recipe, with "Expected 'id' to be provided for unit" in the description.
Both new installations in Docker with latest versions, found when reviewing both versions to see if fits my needs.

### Deployment

Docker (Linux)

**Comment by zierbeek** [comment]
Hi there! 

have you followed the migration guide? 
https://nightly.mealie.io/documentation/getting-started/migrating-to-mealie-v1/

**Comment by josemariaaraujo** [comment]
My bad!
Just did a clean install of both and tried again with a new (web imported) recipe and works fine.
Have been working last days with importing a large collection of recipes in custom generated json, looking for compatibility, and somehow ended up with recipes with wrongly formated ingredients that are valid in V0.5.6, but that can't be migrated to V1.0.0b, totally my fault.

Really sorry for wasting your time.
