### ISSUE TITLE
Can't set input values VIA Javascript

### ISSUE THREAD

**Issue by 97WaterPolo** [mealie-recipes/mealie#1215]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When trying to set the values of inputs using JavaScript it fails to bind inside the text box. Upon inspecting the element the inputs on the page should have the ability to be manipulated by JavaScript, running the code below fails to properly save the input value to the input and fails to post the data when executing the login.

```
var inputs = document.getElementsByTagName("input");
for (let inputElement of inputs) {
    if (inputElement.type == 'email'){
        console.log("Email input. Setting value to: example@test.com");
        inputElement.value = "example@test.com";
    }else if (inputElement.type == 'password'){
        console.log("Password input. Setting value to: ExamplePassword");
        inputElement.value = "ExamplePassword";
    }
}
```
Before: 
![image](https://user-images.githubusercontent.com/6467276/167915196-6775edf3-0ecc-415f-bd32-46acd8571366.png)
After:
![image](https://user-images.githubusercontent.com/6467276/167915315-f5f8eb99-0238-4041-9fed-4ccb0382abc3.png)
Expected:
![image](https://user-images.githubusercontent.com/6467276/167915412-86611c4a-0ec0-449d-b6b2-503235ac521a.png)

### Deployment

Docker (Linux), Unraid

### Mealie Version

v0.5.6

**Comment by hay-kot** [comment]
Hey, This is something that's a supported use case, you can update the TOKEN_TIME variable to extend login sessions to avoid potentially having to login again, otherwise you can use the API to instead of running an automated browser instance.
