### ISSUE TITLE
[v1.0.0b] - Ingredient Parsing screen does not allow 0 quantity

### ISSUE THREAD

**Issue by Miroito** [mealie-recipes/mealie#1231]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

The parsing for ingredient does not allow to save ingredients with a quantity of 0.

This screen also lacks a message feedback in case of error in the backend, making it difficult to know what's wrong for the untrained end user. 

### Deployment

Docker (Linux), Other

### Deployment Details

Reproduced in a development environment and my deployed version of mealie on a linux server.

**Comment by hay-kot** [comment]
I wasn't able to replicate this using the parser, what error were you getting on the backend?

**Comment by hay-kot** [comment]
Pretty sure this has been fixed, if it isn't, feel free to reopen.

**Comment by Miroito** [comment]
I just tried on one recipe on a relatively recent image of Mealie and I did not experience the issue I described.
If it ever was an issue (I'm starting to doubt somehow) we can consider it fixed.
