### ISSUE TITLE
[META] Language Support

### ISSUE THREAD

**Issue by hay-kot** [mealie-recipes/mealie#124]
Language Support is now done through a 3rd party site that will automagically create and submit a PR for you! Checkout [Mealie at Crowdin](https://crowdin.com/project/mealie) for how you can support your language or others.

[![Crowdin](https://badges.crowdin.net/mealie/localized.svg)](https://crowdin.com/project/mealie)

<s>
See the [documentation](https://hay-kot.github.io/mealie/contributors/translating/) for how to contribute additional languages for the web UI. PR Request should be made on the `dev` branch to keep up with rapid development changes. If you'd like to contribute/support additional languages comment on this issue. 

# Current Translation Status
## Currently Supported
Current Languages in `frontend/src/store/modules/language.js`:
* Danish (da) - @dekvall #72
* English (en) - general
* French (fr) - @Raghnarok05, @Batgame  #93 
* Swedish (sv) - @dekvall #128
* 简体中文 (zh-CN) - @wengtad #133
* 繁體中文 (zh-TW) - @wengtad #133

## Prepared Pull Requests
Pull Requests with `language.js` and locale file:

## Currently Supported Needing Attention
* Danish (da) 
* Swedish (sv) 
* French (fr) [Updated with #146]
</s>

**Comment by dpieski** [comment]
I can do a Spanish translation if no one else is already working on that

**Comment by beefsaus** [comment]
I can do a Dutch translation if you need help

**Comment by ilco3** [comment]
ive added a dutch translation  i translated myself 
mealie/frontend/src/locales/ could sombody check if  if it works -if my usage of words is correct

> I can do a Dutch translation if you need help

**Comment by ilco3** [comment]
> ive added a dutch translation i translated myself
> mealie/frontend/src/locales/ could sombody check if if it works -if my usage of words is correct
> 
> > I can do a Dutch translation if you need help

uploaded it trough the create a new file function on mealie/frontend/src/locales/

**Comment by mindesbunister** [comment]
#160

**Comment by dpieski** [comment]
# Current Translation Status
## Currently Supported
Current Languages in `frontend/src/store/modules/language.js`:
* Danish (da) - @dekvall #72
* English (en) - general
* French (fr) - @hay-kot, @Raghnarok05, @Batgame  #93 
* Swedish (sv) - @dekvall #128
* 简体中文 (zh-CN) - @wengtad #133
* 繁體中文 (zh-TW) - @wengtad #133

## Prepared Pull Requests
Pull Requests with `language.js` and locale file:
* Polish (pl) - @retmas-gh #154
* Spanish (es-MX) - @dpieski #163

## Pull Requests Needing Attention
With `<lang-code>.json` file but no `langauge.js` update:
* German (de) - @mindesbunister #160

## Currently Supported Needing Attention
* Danish (da) 
* Swedish (sv) 
* French (fr) [Updated with #146]

**Comment by retmas-gh** [comment]
commenting for the sake of commenting i guess; translated to polish in pr #154

**Comment by fenevol** [comment]
Translated Mealie into Catalan and updated Spanish translation.
Thanks for this great software.

**Comment by bartfailt** [comment]
Is there any plan to release translations created in the past few months? Specifically I'd like to start using my Hungarian translation #639 merged a month ago

**Comment by hay-kot** [comment]
> Is there any plan to release translations created in the past few months? Specifically, I'd like to start using my Hungarian translation #639 merged a month ago

Yes. There are 2 PR's outstanding that I'd like to see in the next release as well as the language bug in 0.5.2 that needs to be fixed as well. I'm hoping to tackle those this weekend as time allows. You can always use the `dev` tag to pull down the latest development image and get those features/languages.
