### ISSUE TITLE
[v1.0.0b] - Cannot delete meal in meal planner on Android device

### ISSUE THREAD

**Issue by MichlF** [mealie-recipes/mealie#1269]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When attempting to delete a meal in the meal planner (using the red bin icon) on an android device using the Brave browser, the meal cannot be deleted (i.e. nothing happens after the highlighting animation). However, it works fine using the same browser on a Windows computer.
Since the meal card every now and then wobbles slightly when pressing the bin icon, this may be related to the drag & drop feature?
There is no error message in the container log.
Might also be related to #1177.

### Deployment

Docker (Synology)

**Comment by hay-kot** [comment]
Potential fix for this in #1295 - need to confirm after the nightly build.

Edit:

Still not working very well, will have to take another stab at it.

**Comment by hay-kot** [comment]
Okay #1302 will _actually_ fix this issue. I've disabled the drag and drop by entire card on mobile and added a handle to drag and drop to different days. This also makes it easier to scroll through a mealplan

![CleanShot 2022-05-27 at 16 12 25](https://user-images.githubusercontent.com/64056131/170802009-c2edca42-9f8f-4962-9372-b0af80000597.png)
