### ISSUE TITLE
[v1.0.0b] - Bulk Importer Fails Silently

### ISSUE THREAD

**Issue by stroodle96** [mealie-recipes/mealie#1273]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When trying to use the bulk importer, I see the message that it started but the recipes never show up.  When I look at the logs I see the errors below.  If I import the recipe one at a time using the normal importer, they import fine.  So there are 2 problems here.  The big problem here is that there is no notification to the end user that the imports failed at all without looking in the logs.  I think there should be notice sent to notifiers or email the user/admin about the failed import.  I do have Discord notifier setup with all the notify option selected.  The second problem is the bulk importer is throwing errors when the normal URL importer is not. 

 ERROR: 24-May-22 18:35:12 	Failed to create recipe from url: https://www.homechef.com/meals/chile-cumin-carne-asada-with-cilantro-butter 
ERROR: 24-May-22 18:35:12 	(400, {'details': 'BAD_RECIPE_DATA'})
ERROR: 24-May-22 18:35:14 	Failed to create recipe from url: https://www.homechef.com/meals/prosciutto-and-mushroom-carbonara-standard 
ERROR: 24-May-22 18:35:14 	(400, {'details': 'BAD_RECIPE_DATA'})

**Details**
Version: v1.0.0b
Build: 1092e0ce7c070bbf204ee9ec20b852e690197aef
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 13.33.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: Yes
Docker Volumes: success

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
Thanks for the feedback this was half baked for sure! 

I've got a working implementation in 

- #1294 

That will add a few new features and address your concerns. 

1. It will add a report component below which will show previously done bulk imports and display status You'll be able to click into it and see which recipes failed and review what exception was thrown and a general message. 
2. New toast notifications for successfully starting and import.
3. There's now a toggle for showing/hiding the category/tag entry section
4. There's now a bulk add URL dialog so you can past in a list of urls separated by a line and they'll be added to the list. 

![CleanShot 2022-05-25 at 19 15 14](https://user-images.githubusercontent.com/64056131/170408988-5d7958c7-1ee2-458e-bf86-f4b579af08a7.png)

**Comment by stroodle96** [comment]
Awesome, this looks very sleek. Will bulk import status and notifications be sent to notifiers that are setup? Like a discord message that it failed or complete successfully?

**Comment by hay-kot** [comment]
Not on this go around, but will consider it for a future update.
