### ISSUE TITLE
[v1.0.0b] - Backup File is Too Large For My Data

### ISSUE THREAD

**Issue by kushfest** [mealie-recipes/mealie#1301]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I'm having an issue when backing up my data on the current beta: my backup file is 3GB. This is weird because my recipe data totals to less than 100MB. 

Also strange...when I extract the 3GB backup zip, the folder it generates is only 100MB. Is something broken in the process to create the backup zip file? 

### Deployment

Docker (Linux)

### Deployment Details

<img width="802" alt="image" src="https://user-images.githubusercontent.com/13265036/170777580-b4328157-9b1b-4918-944f-17f9f60c332e.png">

**Comment by hay-kot** [comment]
Thanks!

Can you ...

1. Verify that there aren't any hidden files in the backup / zip file? 
2. Also, can you provide the results from the storage details dialog on the admin panel? 

<img width="940" alt="CleanShot 2022-05-27 at 11 51 09@2x" src="https://user-images.githubusercontent.com/64056131/170780723-199a4364-6d2f-4298-8a37-07a821da425a.png">
