### ISSUE TITLE
[v1.0.0b] - Opening recipe directly instead of navigation on the same browser leads to a server error

### ISSUE THREAD

**Issue by Meuschke23** [mealie-recipes/mealie#1311]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

**Details**
Version: v1.0.0beta-2
Build: b981cf62bfd7d22fe35c0fa563713b39b10ab3e6
Anwendungsmodus: Produktivumgebung
Demostatus: Keine Demo
API-Port: 9000
API Dokumentation: Aktiviert
Datenbanktyp: sqlite
Recipe Scraper Version: 14.1.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: Yes
Docker Volumes: success
---
Hello Mealie-Team,
first of all I would like to note that Mealie is a great tool, thank you very much for that.
if i open a recipe directly (https://mealie.DOMAIN/recipe/RECIPE instead of navigation on the same browser leads to a server error:

**server error**

![2022-05-29_14-24-16](https://user-images.githubusercontent.com/65863113/170868164-08f18947-56be-4f48-8fc6-be695cf8e17f.png)

[_mealie-frontend_logs.txt](https://github.com/hay-kot/mealie/files/8793343/_mealie-frontend_logs.txt)

Can you help?

Best Regards
Meuschke

### Deployment

Docker (Linux)

### Deployment Details

version: "3.7"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-nightly
    container_name: mealie-frontend
    environment:
    # Set Frontend ENV Variables Here
      - API_URL=http://mealie-api:9000 # 
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.app-CENSORED.entrypoints=websecure
      - traefik.http.routers.app-CENSORED.rule=Host(`CENSORED`)
      - traefik.http.services.app-CENSORED.loadbalancer.server.port=3000
      - diun.enable=true
    networks:
      - proxy
      - intern
    restart: always
    volumes:
      - /var/AppData/Mealie/data:/app/data/

  mealie-api:
    image: hkotel/mealie:api-nightly
    container_name: mealie-api
    volumes:
      - /var/AppData/Mealie/data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=false
      - LDAP_AUTH_ENABLED=false
      - SMTP_HOST=CENSORED
      - SMTP_PORT=465
      - SMTP_FROM_NAME=Mealie
      - SMTP_AUTH_STRATEGY=SSL
      - SMTP_FROM_EMAIL=CENSORED
      - SMTP_USER=CENSORED
      - SMTP_PASSWORD=CENSORED
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - WORKERS_PER_CORE=0.5
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=CENSORED
    labels:
      - diun.enable=true
    restart: always
    networks:
      - intern

volumes:
  mealie-data:
    driver: local

networks:
  intern:
  proxy:
    external: true

**Comment by hay-kot** [comment]
Fixed with #1313, there's now a linter rule to catch errors like that, thanks for reporting! 

You can move to the nightly tag to pickup the change after the build is done, or wait for the next tag/release
