### ISSUE TITLE
[v1.0.0b] - You can delete your own admin account while logged in

### ISSUE THREAD

**Issue by mprajescu** [mealie-recipes/mealie#1317]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

You can delete your own account if you are admin, thus locking yourself out of the system. 
I did this on the demo site and it worked perfectly without any issues. 

You should implement a prompt to confirm this request. 
You should disallow the account to be deleted unless there is at least another admin account. 

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
> You should implement a prompt to confirm this request.

There is a confirmation for deleting a user

> You should disallow the account to be deleted unless there is at least another admin account.

I'm not going to implement this. This page isn't user facing and the implication of administering your own application would be that you can manage users and not delete yourself. 

I'll leave this issue open for a while to see if anyone else wants to implement this.

**Comment by mynamewastaken** [comment]
That's a fair point but the code does check for demoting one's own admin account (https://github.com/hay-kot/mealie/blob/mealie-next/mealie/routes/admin/admin_management_users.py#L52), seems like a guardrail against deleting it wouldn't be a stretch.

**Comment by hay-kot** [comment]
> That's a fair point but the code does check for demoting one's own admin account (https://github.com/hay-kot/mealie/blob/mealie-next/mealie/routes/admin/admin_management_users.py#L52), seems like a guardrail against deleting it wouldn't be a stretch.

As I said. 

> I'll leave this issue open for a while to see if anyone else wants to implement this.

There is already a confirmation screen when deleting a user. Anyone here is welcome to submit a PR to add more safety around this, but I won't be doing it.

**Comment by tehniemer** [comment]
Is there a way to re-create an admin account? I migrated from the previous version and don't seem to have admin access now.
