### ISSUE TITLE
How to get in touch regarding a security concern

### ISSUE THREAD

**Issue by JamieSlome** [mealie-recipes/mealie#1318]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@gaurav-g2) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by hay-kot** [comment]
Thanks for reaching out, I've added a SECURITY.md with an email address you can reach me at.

**Comment by JamieSlome** [comment]
@hay-kot - it looks like we sent the e-mails over but never got a response?

To make your life easier, you can find all of the reports here:
https://huntr.dev/bounties/e5a8e90d-0425-4379-b5c6-ca8ff4db509f/
https://huntr.dev/bounties/901ea690-50dd-4bf0-b3a8-55b6c12a029b/
https://huntr.dev/bounties/caf75bd7-387a-4a6a-a8f5-3744b784966b/

They are all private and only accessible to you 👍
