### ISSUE TITLE
[v0.5.x] - Homechef Recipes importing incorrectly

### ISSUE THREAD

**Issue by Mavarice** [mealie-recipes/mealie#1330]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

While importing Recipes from HomeChef (one of those weekly box meals services) it seems to pull the steps incorrectly.
For example this Recipe: https://www.homechef.com/meals/florentine-shrimp-alfredo is found, however it only adds a single step with a (admittedly malformed) JSON of all the steps in one step.

```json
{'@type': 'ItemList', 'numberOfItems': '3', 'itemListElement': [{'@type': 'ListItem', 'image': 'https://homechef.imgix.net/https%3A%2F%2Fasset.homechef.com%2Fuploads%2Frecipe%2Fimage%2F66900%2F879779LemonFlorentineShrimpAlfredoStepShotsFinal_copy.jpg?ixlib=rails-1.1.0&w=75&auto=format&blur=100&q=0&s=226ce855ab781b15292624cb1596db10', 'name': 'Prepare the Ingredients', 'description': 'Turn oven on to 425 degrees. Let preheat, at least 10 minutes. Thoroughly rinse any fresh produce and pat dry.\n\nCombine cream base, mirepoix base, cream cheese, 2 Tbsp. water, and garlic salt in provided tray. Cream cheese will melt as meal bakes.\n\nStir in pasta until combined and coated.'}, {'@type': 'ListItem', 'image': 'https://homechef.imgix.net/https%3A%2F%2Fasset.homechef.com%2Fuploads%2Frecipe%2Fimage%2F66901%2F879779LemonFlorentineShrimpAlfredoStepShotsFinal-2_copy.jpg?ixlib=rails-1.1.0&w=75&auto=format&blur=100&q=0&s=c51c93f3788fa168a198ce9550fc3b84', 'name': 'Add the Shrimp', 'description': 'Pat shrimp dry.\n\nTop pasta and sauce with spinach, then shrimp. Season with a pinch of pepper.'}, {'@type': 'ListItem', 'image': 'https://homechef.imgix.net/https%3A%2F%2Fasset.homechef.com%2Fuploads%2Frecipe%2Fimage%2F66902%2F879779LemonFlorentineeShrimpAlfredoStep3Final_copy.jpg?ixlib=rails-1.1.0&w=75&auto=format&blur=100&q=0&s=106e0e36820500383d3bc04bd077e679', 'name': 'Bake the Meal', 'description': 'Bake uncovered in hot oven until shrimp reach a minimum internal temperature of 145 degrees, 20-22 minutes.\n\nWhile meal bakes, halve lemon.\n\nCarefully remove tray from oven. Squeeze one lemon half over meal (to taste; remaining is yours to do with as you please!) and add half the Parmesan (reserve remaining for garnish). Stir until creamy. Garnish with remaining Parmesan. Bon appétit!'}]}
```

It appears as though their website uses single quotes instead of double quotes per JSON specifications.

### Deployment

Docker (Linux), Docker (Synology)

### Deployment Details

No special changes of any kind were made. 
I've tried this on the latest, dev and frontend-nightly and the implementation is the same.

**Comment by Mavarice** [comment]
Attaching image as an example of above.

![image](https://user-images.githubusercontent.com/28742681/171309357-41610d71-1298-44aa-9a97-ac2257dbf7f8.png)

**Comment by Mavarice** [comment]
Note: Image, Description, Ingredients, and nutrition all import correctly and without issue.

**Comment by stroodle96** [comment]
I just tested your recipe and it works fine on my instance. I recently imported almost 70 recipes from home chef and only 1 had major problems. Are you on the latest v1 update? 

Also I would like to add to the issue and see if there is a way to remove the "Info" word that gets added in front of some ingredients like in the screenshot. It's easy enough to remove, but tedious when you import so many recipes

**Comment by hay-kot** [comment]
This does work in the v1 releases. 

https://demo.mealie.io/recipe/florentine-shrimp-alfredo-with-lemon?edit=false

**Comment by stroodle96** [comment]
The extra word "Info" being added to the ingredients does still happen on V1 though. Should I create a separate issue for that? Or is there no easy fix for that?

**Comment by hay-kot** [comment]
> The extra word "Info" being added to the ingredients does still happen on V1 though. Should I create a separate issue for that? Or is there no easy fix for that?

That'd need to be handled in the upstream library, provided Mealie isn't inserting the text. That way everyone can even fit from the changes. I don't agree with making parser changes without up streaming them to the original library.

I think you could implement a custom parser in the recipe-scrapers project and just strip that Info from the beginning g if all ingredients. _should_ be fairly simple.
