### ISSUE TITLE
[v1.0.0b] [Task] - Integrate "Cook" Page into Recipe Page

### ISSUE THREAD

**Issue by hay-kot** [mealie-recipes/mealie#1337]
### What is the problem this task addresses?

The "Cook" page is half baked and not super well developed. I think a better approach would be to roll that functionality into the main Recipe page and just add an additional toggle.

### Proposed/Possible Solution(s)?

One approach I considered was to use the "Cook" button to toggle CookMode on the Recipe Page which would do the following

- Hide everything but the Recipe Steps and ingredients, and Title Section.
- Put the Ingredients at the bottom of the page (maybe collapsed).
- Display all linked ingredients on Recipe Steps.

**Comment by Miroito** [comment]
This is feasible though it might be non intuitive to have the Cook button as it is now trigger a toggle action. 
There are no on/off slider type buttons in Mealie (at least not that I remember) at the moment which would probably make such a button out of place. I'm lacking ideas as to how it should look like. Any idea is welcome.

Other than that I can already start working on this using the existing PR.

**Comment by Bentipa** [comment]
I am wondering if it makes sense to put much more code into the index file.
I would rather try to perform a cleanup of that file and split it a little so the LOC are reduced.

We would then have an Edit, View and Cook Configuration for the same page.
If I want to cook, a separate page that is optimized for cooking would make sense.
If I want to edit a recipe, a page that is optimized for editing makes sense.
And if I want to view a recipe, a page that is optimized for viewing/getting a overview makes sense.

Either this or we combine view&cook as they have most in common (would lead to 2 different pages).

**Comment by hay-kot** [comment]
> I am wondering if it makes sense to put much more code into the index file.
I would rather try to perform a cleanup of that file and split it a little so the LOC are reduced.

Yes, that file is a dumpster fire. I've wanted to do this for a long time but haven't found an effective way to split things up without ALOT of duplicate code. Right now each component inside the page has an Edit and View toggle and that switches the internal state to show/hide the appropriate items. Since they layouts for Edit and View are pretty much identical, if we split the pages it will cause a lot of duplication, unless we use a bunch of slots and a layout component, but I'm not sure that's worth the trouble. 

Additionally, the Recipe View need to be moved to it's own component eventually to support Shareable and Public recipes on different routes. For example the Recipe Page and the `shared/recipes/_id.vue` pages are nearly identical with a few state things changes for SEO.

I'd really like to get that in a more organized state, but I haven't had any good ideas on how to get it done. I'm definitely open to suggestions on that one.

**Comment by Bentipa** [comment]
Yeah, as I said, my suggestion would be to have one for edit and one for view/cook.
Sure, the edit page will share similar things with the view page, but it should be kind of different.
But maybe someone else has a better idea.

**Comment by Miroito** [comment]
> Put the Ingredients at the bottom of the page (maybe collapsed).

Moving ingredients to the bottom of the page is maybe not the best of ideas, what if the user did not link the ingredients to the recipe steps? Or if that linkage is incomplete?

Most recipes will have the ingredients on the left and the instructions on the right to be able to see both at every given moment (at least in western cultures). I think it should stay that way.

I'm open to your feedback

**Comment by hay-kot** [comment]
> Moving ingredients to the bottom of the page is maybe not the best of ideas, what if the user did not link the ingredients to the recipe steps? Or if that linkage is incomplete?
> Most recipes will have the ingredients on the left and the instructions on the right to be able to see both at every given moment (at least in western cultures). I think it should stay that way.

The idea with the linking of ingredients and cook mode was that if the user linked their ingredients we could enable a simple view to see the ingredients in the relevant steps and remove duplicate UI elements so you get a clean step by step view.

If the user _didn't_ link their ingredients I'm not sure what purpose a Cook Mode would serve? Wouldn't it be effectively the same view as the default recipe view?

**Comment by Miroito** [comment]
That's a good point.. If ingredients aren't linked, the target cook mode will look the same with only less information because categories and other things will have disappeared.

In that case, the show linked ingredients button that I designed in the first place to appear only when the recipe had at least one linked ingredient was not that bad imo.

**Comment by Miroito** [comment]
@hay-kot What do you think? I still feel like hiding the list of ingredients at the end of the page might lead to confusion. 
I can also just hide the cook mode button when no ingredients are linked since we have concluded that it is useless in that case.

**Comment by hay-kot** [comment]
My view is that the whole point of "Cook Mode" is to clear out clutter and focus on the steps, which is only really valid if the steps are properly linked to ingredients. I agree that in order to show the cook button, the user should have to have at least one ingredient linked to a step. I still think it makes sense to hide the ingredients, otherwise what's the point? Having them at the bottom was an optional stop-gap to make sure if you accidentally didn't link something you could still find it, but maybe we just hide them all together as force users to setup their steps with ingredients? 

I just don't see this being useful unless we make it a hard requirement to link ingredients.

**Comment by Miroito** [comment]
Sure, here's then a summary to what I would implement to finish the PR:
- The cook mode button will appear only when at least one ingredient has been linked to a step for this recipe.
- The list of ingredients is moved to the bottom in cook mode in case it is needed for consultation.

Let me know if that is fine for you and I'll get to it.

**Comment by hay-kot** [comment]
This was closed thanks to the work of @Miroito 🎉
