### ISSUE TITLE
[v1.0.0b] - Backup creation error with language setting "german"

### ISSUE THREAD

**Issue by Seehundkuschler** [mealie-recipes/mealie#1353]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

In the current nightly, when creating a backup, the created file is not displayed if the language setting is set to "german". The list is empty. If the language is set to "american english", the backup files are visible.

### Deployment

Other

### Deployment Details

docker QNAP TS-230. api/frontend-nightly, 07.07.2022 , v1.0.0beta-2 , Build eca8a965096e24dfec012297198d430353a1547b

**Comment by hay-kot** [comment]
Fixed in nightly thanks to @michael-genson
