### ISSUE TITLE
[v1.0.0b] - Shopping list for food items not displaying labels properly

### ISSUE THREAD

**Issue by coffee-mage** [mealie-recipes/mealie#1357]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When building a shopping list with food items, it does not display the food labels properly.   This happens both when adding to shopping list from recipe, and adding single food item manually.

If you manually set the label in the create shopping item window, it works properly.  If you try to rely on the food database table, it doesn't display.

Also the api call to ./foods?start=0&limit=999  seems to return the proper label information, the shopping list just doesn't use it.
![image](https://user-images.githubusercontent.com/14890934/172590671-4f74aaa6-5625-453d-8256-ae9c78287aed.png)

Salt doesn't have proper label information,  but when I manually set black pepper to 'meat'.  It shows properly.
![image](https://user-images.githubusercontent.com/14890934/172590793-7d4cfa82-6eba-42af-acad-8910be692577.png)

### Deployment

Docker (Linux)

**Comment by PFischbeck** [comment]
Can you check whether this still happens with the latest nightly? I can't reproduce it, for me the labels are properly added based on food items.

**Comment by coffee-mage** [comment]
Hi PF,
Just pulled the latest nightly.  If I add to shopping list from recipe,  it works as expected.
If I add single food item (without setting the label), it doesn't pull the food label from the food database.

**Steps**
1) On shopping list, hit [+ Create] green button.
2) Toggle food mode
3) Find food item that has label from the dropdown  (e.g. Salt)
4) Fill in Units
5) Leave label drowndown untouched  (assuming it will be populated based on food).
6) Hit Save (disk icon)
7) New food item (salt) doesn't have label.


Let me know what I can provide to be more helpful.
