### ISSUE TITLE
[v1.0.0b] - Parser doesn't handle 1/8th properly

### ISSUE THREAD

**Issue by coffee-mage** [mealie-recipes/mealie#1358]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When parsing a recipe that has 1/8 teaspoon in it.  Parser converts that to 0.1 instead of 0.125.   Then after recipe saves, it displays as 1/10th instead of original 1/8th.   If I override the 0.1 with 0.125, it will show properly as 1/8th.

![image](https://user-images.githubusercontent.com/14890934/172605038-32faf796-1591-4d28-8406-04fdddb8175c.png)

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
This should be fixed in PR #1369
