### ISSUE TITLE
[v1.0.0b] - After create recipe, image doesn't show up

### ISSUE THREAD

**Issue by coffee-mage** [mealie-recipes/mealie#1359]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

After I create a recipe, the image doesn't show up on the recipe detail page.  The thumbnail  image shows fine on the recipe list page.

For some reason I get a 404 (from disk cache) error.
![image](https://user-images.githubusercontent.com/14890934/172606234-cdec88f7-4fb1-4721-8044-bbb9e771a861.png)

If I 'clear browser cache' in chrome, the problem fixes itself.   I'm not sure if this is an issue with my setup, or a broader issue.  Creating an issue, just so you are aware.

### Deployment

Docker (Linux)

**Comment by madindehead** [comment]
I'm also seeing this error, but when trying to add the image after a recipe has been imported.

![image](https://user-images.githubusercontent.com/52778103/174614597-c0e396f5-2756-4344-b1f4-e88bfa454819.png)

Using the latest beta. Firefox as browser.

**Comment by hay-kot** [comment]
I believe this error has been resolved, could you try to replicate it on the latest version (nightly) or on the demo site and let me know if it's still present?

**Comment by madindehead** [comment]
> I believe this error has been resolved, could you try to replicate it on the latest version (nightly) or on the demo site and let me know if it's still present?

I checked. It was an error in my compose file. Ooops. I had remapped the volume for the backend, but not the frontend. All good now.

**Comment by coffee-mage** [comment]
I just did a git pull on the source code, and rebuilt my docker images.   I still seem to get the same problem.
Image loads when creating the recipe,  image loads in the all recipes thumbnail.  When I click on the recipe, the image doesn't show at the top.

Let me know if you think i'm doing something incorrectly.

Here are more technical details:

**Console Log**
b24b09f.js:2 [Vuetify] Failed to decode image, trying to render anyway

src: /api/media/recipes/6c77bed8-e44e-421a-a3d6-d1db38d879cc/images/min-original.webp?rnd=1&version=null
Original error: The source image cannot be decoded.

found in

```
---> <VImg>
       <RecipeCardImage>
         <RouterLink>
           <VCard>
             <VHover>
               <VLazy>
                 <RecipeCard>
                   <VLazy>
                     <RecipeCardSection>
                       <Anonymous>
                         <Nuxt>
                           <VMain>
                             <VApp>
                               <Anonymous>
                                 <Root>
```


**Console Network Window**
Request URL: https://mealie.codesoldier.net/api/media/recipes/4f330b68-14f8-47cb-9219-4ebefd371f18/images/original.webp?rnd=1&version=null
Request Method: GET
Status Code: 404  (from disk cache)
Remote Address: 192.168.1.5:8118
Referrer Policy: strict-origin-when-cross-origin
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
cache-control: max-age=14400
cf-cache-status: MISS
cf-ray: 724a5d6f6c7c3fcd-YYZ
content-length: 0
date: Sat, 02 Jul 2022 21:09:53 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=BsDA4ftJlbX6vrsGNsD3UXZPCpWKv03AcCo6t8bG80rnnqODOfCaeYr65m5WmtaIutojFzM1Izc185veBqbWw9xWvfoP3nmjPyuYOlYjlGp%2F3a1hGsSTdEaXBOHOh7rtetCuciYE0nNs"}],"group":"cf-nel","max_age":604800}
server: cloudflare
vary: Accept-Encoding
