### ISSUE TITLE
[v1.0.0b] - ingredient parser -- create new ingredient usability

### ISSUE THREAD

**Issue by coffee-mage** [mealie-recipes/mealie#1360]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When the ingredient parser cannot find a new ingredient, and you try to type the ingredient you want into the combo box:
![image](https://user-images.githubusercontent.com/14890934/172608499-02f19032-d818-4ee6-a8d0-5f9d9adebf4e.png)

It says you can hit enter to create.  Enter button only works to create for me about 50% of the time.  It feels random when it works and when it doesn't.   The green create button works 100% of the time.

If the enter button does work  (or the create button that always works).  It leaves the combo box open.  So you need to click outside of the combo box to get it to collapse.  Would be nice onEnter/onCreateButton if it selects the item automatically and closes the combo box.
![image](https://user-images.githubusercontent.com/14890934/172608926-b952a1d5-217e-48a6-81c2-1ad852d131bd.png)

### Deployment

Docker (Linux)

**Comment by CodingKoopa** [comment]
This still seems to be a pain point when working with a fresh instance.
