### ISSUE TITLE
[v1.0.0b] - Server error when select Mealplan & Language German

### ISSUE THREAD

**Issue by blueline13** [mealie-recipes/mealie#1361]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

1) Open the Meal Planner. Select the German translation. Then a server error appears.

2) Select the German translation. Only then open the Meal Planner. Then the window remains empty.

I have the problem in my Nightly(June 7) installation. But the problem can also be reproduced on demo.mealie.io.

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
There's an issue with the config for a few languages, including German. I [submitted a PR](https://github.com/hay-kot/mealie/pull/1362) for this.

**Comment by hay-kot** [comment]
Fixed in nightly thanks to @michael-genson
