### ISSUE TITLE
[v1.0.0b] - Custom scaling not being applied

### ISSUE THREAD

**Issue by Dunrar** [mealie-recipes/mealie#1367]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I'm on the docker nightly version and just tried out the custom scaling option ( #1345), but could not get it to actually apply the scaling. Tried with multiply recepies in multiple languages, no dice. Images below:

![custom_scaling](https://user-images.githubusercontent.com/23218622/173050095-50f3f761-3541-40b1-8abd-5f51e3edc2dd.png)

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Did you enable ingredient amounts on that recipe (did you parse it)? The scaling won't work if the amounts are disabled (which is the default behavior)

**Comment by Dunrar** [comment]
I didn't, thank you... It works, though the model understandably struggles a lot with languages other than englisch.
