### ISSUE TITLE
[v1.0.0b] - SQLAlchemy queries are built using is_ instead of __equals__ for filtering on single values and this breaks with Postgres

### ISSUE THREAD

**Issue by doctorjames** [mealie-recipes/mealie#1378]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Having been using Mealie 0.5.x for some time, this weekend I built and installed 1.0.0beta-3 using a Postgres backend.

Attempting to use the Meal Planner causes errors in the docker logs in both the Postgres and Mielie API containers. The SQL errors show `IS` being used to query against strings.

Here's one example from Postgres:

```log
db_1               | 2022-06-13 02:19:21.107 BST [42] STATEMENT:  SELECT recipes.created_at AS recipes_created_at, recipes.update_at AS recipes_update_at, recipes.id AS recipes_id, recipes.slug AS recipes_slug, recipes.group_id AS recipes_group_id, recipes.user_id AS recipes_user_id, recipes.name AS recipes_name, recipes.description AS recipes_description, recipes.image AS recipes_image, recipes.total_time AS recipes_total_time, recipes.prep_time AS recipes_prep_time, recipes.perform_time AS recipes_perform_time, recipes.cook_time AS recipes_cook_time, recipes.recipe_yield AS recipes_recipe_yield, recipes."recipeCuisine" AS "recipes_recipeCuisine", recipes.rating AS recipes_rating, recipes.org_url AS recipes_org_url, recipes.date_added AS recipes_date_added, recipes.date_updated AS recipes_date_updated
db_1               |    FROM recipes
db_1               |    WHERE recipes.group_id = '16d2a5e3-9b5d-438f-a87b-3f9d22e09e1b'::uuid AND (EXISTS (SELECT 1
db_1               |    FROM recipes_to_tags, tags
db_1               |    WHERE recipes.id = recipes_to_tags.recipe_id AND tags.id = recipes_to_tags.tag_id AND tags.id IS '897d37c9-e98f-46ca-8888-0c400b0e81dd'::uuid))
db_1               | 2022-06-13 02:19:29.936 BST [36] ERROR:  syntax error at or near "'897d37c9-e98f-46ca-8888-0c400b0e81dd'" at character 982
```

The following modifications were enough to make the Meal Planner work

```patch
diff --git a/mealie/repos/repository_meal_plan_rules.py b/mealie/repos/repository_meal_plan_rules.py
index 4c9e2a77..dc735533 100644
--- a/mealie/repos/repository_meal_plan_rules.py
+++ b/mealie/repos/repository_meal_plan_rules.py
@@ -15,14 +15,14 @@ class RepositoryMealPlanRules(RepositoryGeneric[PlanRulesOut, GroupMealPlanRules
     def get_rules(self, day: PlanRulesDay, entry_type: PlanRulesType) -> list[PlanRulesOut]:
         qry = self.session.query(GroupMealPlanRules).filter(
             or_(
-                GroupMealPlanRules.day.is_(day),
+                GroupMealPlanRules.day==day,
                 GroupMealPlanRules.day.is_(None),
-                GroupMealPlanRules.day.is_(PlanRulesDay.unset.value),
+                GroupMealPlanRules.day==PlanRulesDay.unset.value,
             ),
             or_(
-                GroupMealPlanRules.entry_type.is_(entry_type),
+                GroupMealPlanRules.entry_type==entry_type,
                 GroupMealPlanRules.entry_type.is_(None),
-                GroupMealPlanRules.entry_type.is_(PlanRulesType.unset.value),
+                GroupMealPlanRules.entry_type==PlanRulesType.unset.value,
             ),
         )
```

```patch
diff --git a/mealie/repos/repository_recipes.py b/mealie/repos/repository_recipes.py
index ee1c0c37..990eab82 100644
--- a/mealie/repos/repository_recipes.py
+++ b/mealie/repos/repository_recipes.py
@@ -141,14 +141,14 @@ class RepositoryRecipes(RepositoryGeneric[Recipe, RecipeModel]):
         if categories:
             cat_ids = [x.id for x in categories]
             if require_all_categories:
-                fltr.extend(RecipeModel.recipe_category.any(Category.id.is_(cat_id)) for cat_id in cat_ids)
+                fltr.extend(RecipeModel.recipe_category.any(Category.id==cat_id) for cat_id in cat_ids)
             else:
                 fltr.append(RecipeModel.recipe_category.any(Category.id.in_(cat_ids)))

         if tags:
             tag_ids = [x.id for x in tags]
             if require_all_tags:
-                fltr.extend(RecipeModel.tags.any(Tag.id.is_(tag_id)) for tag_id in tag_ids)
+                fltr.extend(RecipeModel.tags.any(Tag.id==tag_id) for tag_id in tag_ids)
             else:
                 fltr.append(RecipeModel.tags.any(Tag.id.in_(tag_ids)))
```

It's possible there are more issues in areas I've not yet explored. I've no experience with either SQLAlchemy or Mealie's data model, but if you want, I can submit that as a pull request.

### Deployment

Docker (Linux)

### Deployment Details

Docker on armv7l 

If you want I can also submit a separate pull request for the additions required to the Dockerfile to build properly on 32 bit Arm, which might be useful to other people even if you can't build them automatically. crfpp also needed a one line change.

**Comment by hay-kot** [comment]
Straight from the docs

> The [ColumnOperators.is_()](https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.ColumnOperators.is_) operator is automatically invoked when using the [ColumnOperators.__eq__()](https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.ColumnOperators.__eq__) overloaded operator, i.e. ==, in conjunction with the None or [null()](https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.null) value. In this way, there’s typically not a need to use [ColumnOperators.is_()](https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.ColumnOperators.is_) explicitly, paricularly when used with a dynamic value:

TIL. Makes total sense though, I should read more. If you want to submit a PR with the changes you've made here, that would be great. 

---

For the Armv7, I'm not sure how involved the process is, but would it make more sense to include a guide in the Docs instead of adding it to the build process? I know when we were using CI builds it would randomly crash all the time so I'm hesitant to add it back in. Nothing is a time suck quite like CI builds can be.
