### ISSUE TITLE
[v1.0.0b] - Kitchen Stories Import: Servings always 0

### ISSUE THREAD

**Issue by mhellmeier** [mealie-recipes/mealie#1380]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

The servings are always set to zero when importing recipes from [kitchen stories](https://www.kitchenstories.com/). 

Example URL to import:
https://www.kitchenstories.com/en/recipes/carrot-miso-soup

Expected servings: 2
Servings displayed in Mealie: 0

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
This appears to be an issue upstream, so not something I can do anything about, in fact the scraper seems to be broken entirely in the latest version. I've created an issue in the recipe-scraper repository and will have to defer there for now

- https://github.com/hhursev/recipe-scrapers/issues/562

**Comment by hay-kot** [comment]
Looks like this is fixed in nightly, verified on the demo site.
