### ISSUE TITLE
[v1.0.0b] - Meal Planner not working in German language

### ISSUE THREAD

**Issue by gitrys** [mealie-recipes/mealie#1382]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

If the language is in german, the meal planner won't work.

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
This should be fixed in nightly:
https://github.com/hay-kot/mealie/issues/1353

**Comment by hay-kot** [comment]
@michael-genson is correct, this should be fixed in Nightly. Please provide for deployment details if you're still experiencing the issues after updating the the latest nightly version.

**Comment by gitrys** [comment]
You are right, it's fixed. Thank you for your awesome work!
