### ISSUE TITLE
[v1.0.0b] - Some sites import all instructions as one step

### ISSUE THREAD

**Issue by epheterson** [mealie-recipes/mealie#1399]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I'll try to add more links as I come across them, but at least this site seems to consistently have the issue.

All of the instructions are discovered, though import as a single "Step 1". Perhaps the site isn't properly formatting them, though if we can somehow detect a numbered list (even hard-coded numbers that aren't ol tags) then it'd be great to separate them automatically.

Example –
https://www.halfbakedharvest.com/honey-garlic-cashew-chicken/

### Deployment

Docker (Synology)

### Deployment Details

```
**Details**
Version: v1.0.0beta-3
Build: 56eb0bca7142715984c8028c4c881f086e979564
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.3.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: No
Docker Volumes: success
```

**Comment by epheterson** [comment]
I just noticed there's an option when using "Bulk Add" for instructions that handles this, would be nice if that were applied automatically since the logic already exists.

**Comment by hay-kot** [comment]
There's too many edge cases to consider for something like this and would just create a bunch of issues for us to handle. That's why it's a manual process now. 

For example, how would you adequitly determine how to treat these different? 

```
Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, blanditiis.

1. Lorem ipsum dolor sit amet.
2. Lorem ipsum dolor sit amet.
3. Lorem ipsum dolor sit amet.
```

```
1. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ea, eligendi.
2. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ea, eligendi.
3. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ea, eligendi.
```

```
1. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ea, eligendi. 2. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ea, eligendi. 3. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ea, eligendi.
```

Unfortunately recipe websites have all kinds of ways they provide mangled instructions and I don't really want to get into the weeds of parsing that. In most cases, it's a small manual task to split it up - and you get to validate it to make sure it right.
