### ISSUE TITLE
[v1.0.0b] - Images drag and drop doesn't work in Firefox

### ISSUE THREAD

**Issue by Nabukodonosor** [mealie-recipes/mealie#1441]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

This feature doesn't work in Firefox. I've tried in Chrome and it works great, but in the latest Firefox in Windows 7 it doesn't work. I'm talking about the option to attach images to the Instructions steps.

### Deployment

Docker (Linux)

**Comment by dorj222** [comment]
@hay-kot  may I take this issue?

**Comment by hay-kot** [comment]
> @hay-kot  may I take this issue? 

Absolutely!
