### ISSUE TITLE
[v1.0.0b] [Task] - Add Slovenian language (100% translated on Crowdin)

### ISSUE THREAD

**Issue by thehijacker** [mealie-recipes/mealie#1462]
### What is the problem this task addresses?

Slovenian translation is 100% finished and double checked. I kindly ask to add it into repository/docker. Currently on version 
v1.0.0beta-3 deployed with docker-compose. Was asked on Discord to open a task here. So please do not close it :).

![image](https://user-images.githubusercontent.com/13857043/176019617-2a1a1fc4-0e67-4a4b-900b-9cddf5e20403.png)

Thank you very much.

### Proposed/Possible Solution(s)?

Well. I guess you need to export from Crowdin and import it here somewere. Probably a rebuild will be needed :). You know best.

**Comment by hay-kot** [comment]
Fixed in 

- https://github.com/hay-kot/mealie/pull/1520
