### ISSUE TITLE
[v1.0.0b] - Meal Planner Range Error

### ISSUE THREAD

**Issue by m10x** [mealie-recipes/mealie#1492]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When clicking on Meal Planner, nothing is shown.
![image](https://user-images.githubusercontent.com/4344935/179496161-148b7f5f-6b9f-426d-bccd-5ac9cec7e660.png)
Console log shows 2 range errors.
![image](https://user-images.githubusercontent.com/4344935/179496253-c51e09d0-aa31-4373-bb40-1b1c947a1c3f.png)
When refreshing I receive a "GET http://192.168.178.101:9925/group/mealplan/planner 500 (Internal Server Error)"  
I used the default docker-compose litesql file as shown [here](https://nightly.mealie.io/documentation/getting-started/installation/sqlite/) and changed TZ to Europe/Berlin. Ohterwise I only changed BASE_URL.

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
This is fixed in nightly: https://github.com/hay-kot/mealie/pull/1362

I'd recommend upgrading to nightly (which has been consistently stable). You can also wait until the next main release, but that probably won't be until August.

**Comment by m10x** [comment]
> This is fixed in nightly: https://github.com/hay-kot/mealie/pull/1362
> 
> I'd recommend upgrading to nightly (which has been consistently stable). You can also wait until the next main release, but that probably won't be until August.

Ah thank you. I just noticed that I had the filter active to only search for open issues... sorry for that!

**Comment by michael-genson** [comment]
All good :)
