### ISSUE TITLE
[v1.0.0b] - Postgres version not working on my ARM device (psycopg2 error)

### ISSUE THREAD

**Issue by aberlaas** [mealie-recipes/mealie#1495]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When starting docker from the postgres docker version, I get the following error from mealie-api container : 'Error connecting to database: (psycopg2.OperationalError) SCRAM authentication requires libpq version 10 or above'

I use Odroid ARM device on recent armbian distribution (see deployment info).

Thanks,

### Deployment

Docker (Linux)

### Deployment Details

Device: Odroid-C2
Plateform: aarch64
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy

**Comment by Cobbert** [comment]
Have you tried the latest version for 1.0.0? I do not have an odroid, but I have maybe 20 pis laying around that are also arm processors that I can load armbian onto and test out if you still have issues on the latest beta release. Running via docker should just work out regardless of what the base system is in my mind though.

Let me know and Ill dig out some Pis to play with.

**Comment by aberlaas** [comment]
Hi,

I just tested again with latest nightly images ( v1.0.0beta-4) and I'm still having the issue.
Thank you for helping !

**Comment by Cobbert** [comment]
OK, I will get a pi out and see if I can recreate the issue.

**Comment by CodingKoopa** [comment]
`mealie:latest` is broken on my Ampere Altra (ARM-based) Oracle Cloud VPS for this reason, but `mealie:frontend-nightly` (image `a262267e8d67`) and `mealie:api-nightly` (image `64e828a3fcd3`) work .

**Comment by aberlaas** [comment]
I tried again today on latest docker images, the error is still happening on my Arm device (Armbian).
