### ISSUE TITLE
[v1.0.0b] - Multiple LDAP issues

### ISSUE THREAD

**Issue by rafaelmathieu** [mealie-recipes/mealie#1499]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

` - LDAP_BIND_TEMPLATE=cn={},ou=users,dc=home,dc=com `
` - LDAP_ADMIN_FILTER=memberOf=cn=app_admin,ou=groups,dc=home,dc=com`

Using the LDAP integration above works in v0.5.6. Users are able to login with their username but not email. And users part of the app_admin group are correctly assigned as admin.

The LDAP settings are the same in both v1 and v0.5 version I am running.

1. in v1 users are able to login using username and email (this is new), but the system creates two users instead of having only one.
2. using the same Admin filter in V1 doesn't result in the user having admin rights. not sure how to get it to work.

### Deployment

Docker (Linux), Unraid

### Deployment Details

Running on unraid via portainer's stacks.

**Comment by Elegant996** [comment]
This was normal behavior. If it is the client's first time logging in, the email address isn't recognized (it's not used to authenticate LDAP, the username is). Once the user was created, it assigned the username to the email field and did not pull it from LDAP.

#1487 addresses this issue, once the user logs in with their account, the email will be pulled and can be used on future logins. I tried to find other ways but it would have required a bind account.

**Comment by hay-kot** [comment]
I think with #1487 this has been implemented, if not feel free to reopen!
