### ISSUE TITLE
[v1.0.0b] - Postgresql backup restore fails when not user postgres superuser

### ISSUE THREAD

**Issue by wipash** [mealie-recipes/mealie#1500]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Postgresql version: 14.4
Mealie version: 1.0.0beta-3

When restoring a backup using the builtin backup restore functionality, the backup fails if Mealie is configured to use a user other than the postgres superuser.

The cause seems to be in the `drop_all()` function of `alchemy_exporter.py`. Postgres doesn't allow `SET session_replication_role = 'replica'` if you are not a superuser.

Log from postgres server:
```
2022-07-22 04:42:24.951 GMT [424] ERROR:  permission denied to set parameter "session_replication_role"
2022-07-22 04:42:24.951 GMT [424] STATEMENT:  SET session_replication_role = 'replica'
2022-07-22 04:42:24.952 GMT [424] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2022-07-22 04:42:24.952 GMT [424] STATEMENT:  SET session_replication_role = 'origin'
```

Mealie is deployed with these environment variables:
```
        TZ: Pacific/Auckland
        TOKEN_TIME: 43830
        DB_ENGINE: postgres
        POSTGRES_USER: mealie
        POSTGRES_PASSWORD: longandcomplexpassword
        POSTGRES_SERVER: my.postgres.server
        POSTGRES_PORT: 5432
        POSTGRES_DB: mealie
        BASE_URL: https://mealie.myhouse.com
```

If I set mealie to use the postgres superuser account, the restore works as expected.

### Deployment

Docker (Linux)

**Comment by wipash** [comment]
Easy enough to work around

```sql
ALTER USER mealie WITH SUPERUSER;

# Run restore from Mealie

ALTER USER mealie WITH NOSUPERUSER;
```

**Comment by Taylor-Tyson** [comment]
Newbie question, how do I connect to the postgres database to alter the user?

**Comment by yottabit42** [comment]
I am logged into the mealie database with pgadmin, but the mealie user doesn't have the permissions to grant superuser to the mealie user. 😄 There is also a postgres user, but I don't know what the password would be...

**Comment by yottabit42** [comment]
I am using Mealie from the Truecharts repo in TrueNAS. I was able to grant superuser access to the mealie user in postgres by obtaining the postgres user password from the postgres container shell with the `env` command. I then installed pgadmin, connected to the mealie database, authenticated as the postgres user, and was able to grant superuser rights to the mealie user. I was then able to successfully restore the backup from the Mealie UI. Hope this helps anyone else that runs into the same problem.

**Comment by 0skater0** [comment]
> I am using Mealie from the Truecharts repo in TrueNAS. I was able to grant superuser access to the mealie user in postgres by obtaining the postgres user password from the postgres container shell with the `env` command. I then installed pgadmin, connected to the mealie database, authenticated as the postgres user, and was able to grant superuser rights to the mealie user. I was then able to successfully restore the backup from the Mealie UI. Hope this helps anyone else that runs into the same problem.

Thanks for the explanation!
How did you connect to the mealie database with pgadmin?
I installed pgadmin as an application within TrueNAS but i don't know what hostname/address i should use. 
The hostnames i tried do not seem to work.
Do you have any advice?

**Comment by yottabit42** [comment]
> Thanks for the explanation! How did you connect to the mealie database with pgadmin? I installed pgadmin as an application within TrueNAS but i don't know what hostname/address i should use. The hostnames i tried do not seem to work. Do you have any advice?

Run `sudo bash heavyscript.sh dns`. You can get heavyscript.sh from [Github](https://github.com/Heavybullets8/heavy_script). 

If you need more help, you might want to check out the TrueCharts Discord, and ask in the #unsupported channel. I finally figured out the missing pieces (the `env` command in the container shell) with help from folks there.

**Comment by regularguy01** [comment]
I moved from SQLite to Postgres.  I ran the commands above 
`ALTER USER mealie WITH SUPERUSER;`

`# Run restore from Mealie`

`ALTER USER mealie WITH NOSUPERUSER;`

You don't have to do this on the New Version.  The mealie user is a SUPERUSER now.  However you DO need to make another superuser before you run the NOSUPERUSER one as there is only one User mealie as default.  If you don't you will lock the restore out since you cannot re-promote mealie if you take SUPERUSER from it.

**Comment by Obioban** [comment]
With the current version of Mealie, we no longer need to set the mealie Postgres user to superuser, correct? 

Really need help restoring the backup file-- my wife has many, MANY hours into entering recipes into Mealie, and threw out her originals. 

Right now when I click the upload button, it just does its progress bar thing... indefinitely. 

https://youtu.be/TLuP0dYqvDI

**Comment by michael-genson** [comment]
Can you share your Mealie version as well as your backup file?

**Comment by Obioban** [comment]
Mealie version 1.7.0 currently. 

Backup file attached.
[mealie_2024.zip](https://github.com/user-attachments/files/15518524/mealie_2024.zip)

**Comment by michael-genson** [comment]
Do you use Safari? Safari mangles zip files for some silly reason.
Try this one where I've fixed the file structure: [mealie_2024_fixed.zip](https://github.com/user-attachments/files/15518590/mealie_2024_fixed.zip)

**Comment by Obioban** [comment]
Well, I don't know if it was your file or dusting off Firefox (as I was, indeed, using safari), but that did the trick! Thank you, thank you, THANK YOU!

**Comment by mgrecar** [comment]
If the `ALTER USER` step for a Postgres database restore is not necessary any longer, perhaps the documentation around Backup and Restoring could be updated to indicate for which Mealie versions that applied to? https://docs.mealie.io/documentation/getting-started/usage/backups-and-restoring/ seems to indicate it's the thing to do currently.

**Comment by Borgotto** [comment]
I use a shared Postgres server for multiple services, one of which is Mealie, it'd be nice to not have the need to set mealie as the superuser every time I need to restore a backup, chances are that I'll forget about this fix for next time I'll need to migrate my data.
