### ISSUE TITLE
[v1.0.0beta-3 ] - Additional Critical Severity Issues

### ISSUE THREAD

**Issue by 0xBruno** [mealie-recipes/mealie#1516]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Additional critical severity issues identified. Details were emailed to ob92oy0sl@mozmail.com. Just wanted to put this on your radar. 

### Deployment

Docker (Linux)

### Deployment Details

docker-compose on kali linux

**Comment by hay-kot** [comment]
This issue was fixed with 

- https://github.com/hay-kot/mealie/pull/1522

Correct?

**Comment by 0xBruno** [comment]
Looks good to me 😸
