### ISSUE TITLE
[v1.0.0b4] - issue when URL importing right after deploy

### ISSUE THREAD

**Issue by hmorandell** [mealie-recipes/mealie#1570]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Hi,
I deployed mealie using the  docker-compose template from https://nightly.mealie.io/documentation/getting-started/installation/sqlite/
Everything is working fine after the installation, even the data import from version 0.5 where I'm coming from. The problem is that it seems that there is no network connection for importing a recipe via a URL, which was working fine in version 0.5

When I look at the console I see these entries:
```
......
    resp = requests.get(url, timeout=SCRAPER_TIMEOUT, stream=True)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/requests/adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='www.chefkoch.de', port=443): Max retries exceeded with url: /rezepte/2363941375415207/Schnelle-Falafel-aus-Kichererbsenmehl.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f79b987e5c0>, 'Connection to www.chefkoch.de timed out. (connect timeout=15)'))
127.0.0.1:60270 - "GET /docs HTTP/1.1" 200
.....
```

the weird thing is that the network where thez are on seem to have connection to the outside, and there is no firewalll in between blocking connections. Anyone has an idea where and what's going wrong? Or what else can i Check?

### Deployment

Docker (Linux)

**Comment by tbornon** [comment]
Hi,

I just did a fresh install of Mealie and had no issue importing a recipe. Could you give the URL you tried to import ?

**Comment by hmorandell** [comment]
Hi
sorry at the end it came out that it was a networking issue inside Docker. I did a mistake in the general network configuration, I fixed that right now and everything is working as expected. It was never a issue related to Mealie.

sorry for opening this thread and thanks for your great work
