### ISSUE TITLE
[v1.0.0b] - Unable to change password - field not clickable

### ISSUE THREAD

**Issue by chrisw554** [mealie-recipes/mealie#1594]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When attempting to change the password for the default admin account, the password field is not clickable - unable to be typed in. Same thing happens with a new admin user I have created.

I've tested using Chrome & Safari on Mac OS and iOS.

It would be nice if when creating or updating a user, you are directed back to the user list afterwards or at least have a message appear to say the creation/update was successful. Maybe this is another bug I'm experiencing.

### Deployment

Docker (Linux)

### Deployment Details

Installed via SQLite docker-compose, fresh install just moments ago.

**Comment by chrisw554** [comment]
This can probably be closed. I've since found where to change the password. My Profile > Manage User Profile

What purpose does the password field serve when updating a user here? /admin/manage/users

**Comment by hay-kot** [comment]
> What purpose does the password field serve when updating a user here? /admin/manage/users

None, we're generating that form with some templates so I think it was easier to disable instead of remove the field remove. It also gives a visual indicator that admins can't change user passwords.
