### ISSUE TITLE
[v1.0.0b] - Dark theme environment variables incorrect in documentation

### ISSUE THREAD

**Issue by chrisw554** [mealie-recipes/mealie#1599]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Sorry if this doesn't belong here.

On the following page, the dark theme variables are incorrect
https://nightly.mealie.io/documentation/getting-started/installation/frontend-config/

It states DARK_LIGHT instead of THEME_DARK

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Oh hey you're right, thanks for flagging! I'll submit a PR to get that fixed
