### ISSUE TITLE
[v1.0.0b] - Sort no longer working on Recents and Cookbooks pages

### ISSUE THREAD

**Issue by epheterson** [mealie-recipes/mealie#1605]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Sort functionality is no longer working on Recents or Cookbooks pages. It's still working fine in All Recipes, Categories, Tags and Tools pages.

### Deployment

Docker (Synology)

### Deployment Details

```
**Details**
Version: v1.0.0beta-4 (nightly)
Build: 56eb0bca7142715984c8028c4c881f086e979564
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.13.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: Yes
Docker Volumes: success
```

**Comment by michael-genson** [comment]
I submitted PR #1606 to hide the sort menu from these pages for now, but I'll work on actually fixing the problem.
