### ISSUE TITLE
[v1.0.0b] - Public share links should include image

### ISSUE THREAD

**Issue by epheterson** [mealie-recipes/mealie#1620]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When sharing public links (added in recently nightly release) the name of the recipe shows up on platforms that show link previews, but not the recipe image. 

It’d be great if the recipe image appeared as well. I’m using iMessage mostly, others to try are Facebook messenger, Discord, Slack, etc…

### Deployment

Docker (Synology)

**Comment by michael-genson** [comment]
I can confirm on Discord, Windows 10, same behavior. I get just the title. I feel like the description would be nice too, when there's one available.
![image](https://user-images.githubusercontent.com/71845777/187342979-2c67753f-d95c-47d1-ae93-bb68ea9aeb74.png)

**Comment by epheterson** [comment]
Description is a nice idea too. If the description is included, it should be limited to a certain number of characters since some get pretty long.
