### ISSUE TITLE
Unable to import from another Mealie instance

### ISSUE THREAD

**Issue by SteveM363** [mealie-recipes/mealie#1625]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I have checked for existing issues that have been resolved in v1-beta

### What is the issue you are experiencing?

I have access to 2 instances of Mealie, running on 2 different servers. I am unable to import a recipe from one to the other.
The scraped data reads "recipe_scrapers was unable to scrape this URL" when directed to either the public instance or the local IP:port of the alternate instance.

### Deployment

Docker (Linux)

### Deployment Details

Both instances are linux docker instances, on 2 seperate systems. Normally accessed through cloudflare from outside the home network but have tried to import from within as well.

### Mealie Version

0.5.6

**Comment by hay-kot** [comment]
This is a known limitation. Your version 0.5.6 doesn't even support SSR so it is actually impossible to implement. We're working on SSR in the v1 tree, but we don't have this specific feature on our road map currently. You can submit a feature request on the discussions page using the template. Thanks!
