### ISSUE TITLE
Paprika import

### ISSUE THREAD

**Issue by alephtaph** [mealie-recipes/mealie#1627]
Hi everyone

I just learned from a developer, that paprika import is activated. But I can't find any options or manuals on how to do it.
Version: 0.5.6
Installed with simple docker-compose

Thanks for your suggestions.

**Comment by Kuchenpirat** [comment]
Hi, 
version 0.5x does as far as i know not support migration from paprika. 
For that you have to use the newer releases.
Installation instructions can be found here: https://nightly.mealie.io/documentation/getting-started/installation/installation-checklist/ 

Then you will find in you admin panel the point data migration where you can import from paprika. 

Hope this helps
