### ISSUE TITLE
[v1.0.0b] - Advanced Search toggle behavior seems to misbehave

### ISSUE THREAD

**Issue by GCTWorks** [mealie-recipes/mealie#1632]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When toggling the "Advanced" search on then off, the Categories, Tags, and Foods controls do not disappear.  Also, the toggle control itself does not taggle back to the left position.  The color does change to the inactive color though.  Further clicks of the Advanced toggle control appear to do nothing.  A refresh of the page will always reset the search with Advanced turned off.

I think the intended behavior would be for a toggle off action to clear the Categories, Tags, and Foods controls then hide them and for the toggle control to indicate properly.  It would be a nice to have for the toggle control status to persist thru a page refresh.

Before toggling on Advanced Search
![image](https://user-images.githubusercontent.com/13966442/189172329-457bbb64-2b30-4839-9bc9-30692554c642.png)

After toggling on Advanced Search
![image](https://user-images.githubusercontent.com/13966442/189172451-6b2a6390-826d-4147-99d6-0600d1b092ec.png)

After toggling OFF Advanced Search
![image](https://user-images.githubusercontent.com/13966442/189172576-ec4da356-cd0e-4f83-a9a7-6c01bc5ff804.png)

### Deployment

Docker (Linux)

### Deployment Details

Device:  Raspberry Pi 4B
OS:  Ubuntu 22.04.1
Mealie Deployment Method:  docker compose

Other details:  this was a fresh deployment to start testing the v1.x.x series

**General About**
Version
: v1.0.0beta-4
Build
: 13850cda1f9cb02a8c788030ba6cfa96bba33571
Application Mode
: Production
Demo Status
: Not Demo
API Port
: 9000
API Docs
: Enabled
Database Type
: sqlite
Database URL
: sqlite:////app/data/mealie.db
Default Group
: Home
Recipe Scraper Version
: [14.11.0](https://github.com/hhursev/recipe-scrapers/releases/tag/14.11.0)

**Comment by jxtrt** [comment]
Can replicate on a new install.

**Comment by michael-genson** [comment]
I haven't had time to test this on a new install, but mine works fine. Try adding a single recipe and see if the behavior persists? Could be an issue with having 0 recipes

**Comment by GCTWorks** [comment]
> I haven't had time to test this on a new install, but mine works fine. Try adding a single recipe and see if the behavior persists? Could be an issue with having 0 recipes

I just tried adding a recipe.  The behavior is the same.
