### ISSUE TITLE
[v1.0.0b] - Excessive amount of downloaded data and diskspace needed

### ISSUE THREAD

**Issue by manuelkamp** [mealie-recipes/mealie#1644]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I configured the docker-compose file and started the container. Then I recognized, that it downloads an incredible amount of data (several gigabytes!!!) and uses the whole disk space I have allocated this VM (5 GB) - I then cancelled the command. I am not using a builtin database server, I use my running Postgres node, which i configured in the docker file. I am wondering, what that much data is needed for just a simple app???

### Deployment

Docker (Linux)

### Deployment Details

---
version: "3.7"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-4
    container_name: mealie-frontend
    depends_on:
      - mealie-api
    environment:
    # Set Frontend ENV Variables Here
      - API_URL=http://mealie-api:9000 # 
    restart: always
    ports:
      - "9925:3000" # 
    volumes:
      - mealie-data:/app/data/ # 
  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-4
    container_name: mealie-api
#    depends_on:
#      - postgres
    volumes:
      - mealie-data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://rezepte.somedomain
      - DEFAULT_EMAIL=rezepte@somedomain
      - TOKEN_TIME=1800
      - API_DOCS=false
      - DEFAULT_GROUP=Home

    # Database Settings
      - DB_ENGINE=postgres
      - POSTGRES_USER=mealie
      - POSTGRES_PASSWORD=somepwd
      - POSTGRES_SERVER=someserver
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mealie

   # E-Mail Einstellungen
      - SMTP_HOST=somemx
      - SMTP_PORT=465
      - SMTP_FROM_NAME=somename
      - SMTP_AUTH_STRATEGY=TLS
      - SMTP_FROM_EMAIL=rezepte@somedomain
      - SMTP_USER=rezepte@somedomain
      - SMTP_PASSWORD=somepassword

    restart: always
#  postgres:
#    container_name: postgres
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: mealie
#      POSTGRES_USER: mealie

volumes:
  mealie-data:
    driver: local

**Comment by hay-kot** [comment]
What was downloaded?

**Comment by manuelkamp** [comment]
I don't know, because I cancelled the command. I just used 'docker-compose up -d' and then it just filled the disk with data (monitoring alerted me about that). I let it run for about 3 Minutes before I cancelled it, just can remember it was around task 13/30 and for each task it just showed 10-30 lines of numbers and letters what it was downloading and extracting.

**Comment by hay-kot** [comment]
Compressed sizes are listed on dockerhub. I can't say for sure what your issue is here, but I'm guessing it's docker related and not related to Mealie. If you come back with more information that points to an issue with mealie you can reopen the issue. 

![CleanShot 2022-09-15 at 19 35 20](https://user-images.githubusercontent.com/64056131/190551292-3dbbaa02-98e7-4ce8-8c90-d6168a769fb1.png)
