### ISSUE TITLE
[v1.0.0b] - Categories and Tags are no longer sorted in drop down menu

### ISSUE THREAD

**Issue by MichlF** [mealie-recipes/mealie#1649]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Title says it all:
When adding or editing a recipe the drop down menu for Categories or Tags are no longer sorted as they have been in previous releases. 
I assume this to be a bug because it gets really difficult to find any element when it is unsorted so I don't see any functional advantage from this change.

### Deployment

Docker (Synology)

**Comment by michael-genson** [comment]
Good catch, I'm so used to using the search feature that my brain doesn't even register that there's a pre-populated list before I start typing, so I never noticed.
Do you know how it was sorted previously? Did it used to be alphabetical order?

**Comment by MichlF** [comment]
Yes, it was alphabetically sorted.

**Comment by michael-genson** [comment]
Thanks! I'll take a look at this, I'm guessing it's related to our new pagination API
