### ISSUE TITLE
Web Demo Account Locked

### ISSUE THREAD

**Issue by kemalmeler** [mealie-recipes/mealie#1656]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I have checked for existing issues that have been resolved in v1-beta

### What is the issue you are experiencing?

The demo account locked.

Username: changeme@email.com
Password: demo
![image](https://user-images.githubusercontent.com/17831255/191006299-a7c95c45-f960-436a-801b-9b7f8cc07a4d.png)

### Deployment

Other

### Mealie Version

v1.0.0beta-4

**Comment by kemalmeler** [comment]
It's solved. I think it's has limit of login attempt. Idk?

**Comment by ambroisie** [comment]
This is still an issue.

**Comment by kemalmeler** [comment]
@ambroisie Hi Ambroisie, 

Reopen.

**Comment by hay-kot** [comment]
It's clear that a locking mechanism for accounts on the demo isn't working... People still seem to mistyped the password or purposely lock the account. 

I'll look into a more permanent solution to this. Thanks!

**Comment by hay-kot** [comment]
Just pushed a fix should be good now, thanks!

**Comment by Radiergummi** [comment]
@hay-kot the demo credentials don't seem to work -- could it be that a signed-in demo user can change the password (seems like a troll thing to do)
