### ISSUE TITLE
Can we pull Notes from Recipes into Notes Field in Mealie

### ISSUE THREAD

**Issue by jayakumark** [mealie-recipes/mealie#1660]
example URL:
https://rakskitchen.net/coriander-lemon-rice-recipe-cilantro-lime-rice/

RecipeSage pulls the notes data automatically and adds it , thats the only thing mealie seems missing.

**Comment by hay-kot** [comment]
Please use the feature request process 

https://github.com/hay-kot/mealie/issues/317
