### ISSUE TITLE
[v1.0.0b] - API_PORT env var does not work as expected

### ISSUE THREAD

**Issue by stavros-k** [mealie-recipes/mealie#1666]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

API_PORT should set the port that api is listening.

But as I can tell it always run on 9000. 
I think it's because it's hardcoded in the `run.sh`
Here: https://github.com/hay-kot/mealie/blob/a8f392290786a339c53b476dcd9b4ff601ef7777/mealie/run.sh#L65

### Deployment

Docker (Linux)

### Deployment Details

Helm Chart / TrueNAS Scale App

**Comment by spectrum705** [comment]
I want to take on this issue. can anyone help me?

**Comment by hay-kot** [comment]
Thanks for the issue! I'm not sure this warrants a fix, I'm more included to remove the API_PORT from the documentation since in a containerized environment, you're likely better off not touching it. It usually just leads to confusion from folks.

Is there a compelling reason to fix this and make it configurable over removing it from the docs?

**Comment by stavros-k** [comment]
In Kubernetes, you can deploy as a sidecar in the **same** pod an extra app/whatever (eg a vpn).
images in the same POD, bind ports on the same "localhost" context.

So if a sidecar app wants to bind port 9000, it will conflict.

9000 is not a very common port and I can't think of a "potential" side car that would need port 9000 as well.
Makes it a very low priority to make it configurable.

As a helm/app creator, I aim to give the end user the ease of altering the internal ports(if possible) for the above reason.

While I was creating the chart, I noticed it didn't work, and that's why I reported it.
It's not a blocker for me, or anyone except niche cases (where a sidecar wants to bind port 9000).

My suggestion: 
If it's something easy to do, make it configurable.
If not, don't

**Comment by hay-kot** [comment]
Thanks for all the info! I didn't know Kubernetes had that kind of fine grained control, pretty cool. PR #1754 should fix this behavior and allow the API_PORT to be changed.

**Comment by stavros-k** [comment]
Thanks!
