### ISSUE TITLE
[v1.0.0b] - Infinite scroll fails on large windows

### ISSUE THREAD

**Issue by kryten87** [mealie-recipes/mealie#1668]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

1. Go to "All Recipes"
2. Toggle the view to the smaller recipe cards and refresh the page

At this point, Mealie will load 30 recipes and display them on the screen.
However, if you have a large monitor and the browser window is large enough that all recipes are displayed (and the scroll bar is disabled), there is no way to scroll to the bottom of the page and trigger the event to load the next page of results.

![2022-09-23_14-38](https://user-images.githubusercontent.com/2042984/192060198-207d1b70-f3ac-4686-9762-d3c71cb71968.png)

Notice that the scrollbar on the right in the image above is disabled -- scrolling is not possible, so the infinite scroll is not available.

One solution might be to check when the page is initially rendered -- if the page is not filled with recipe cards, then load another page of data.

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Hey there! I fixed this in #1547. I'd recommend upgrading to nightly if you want it fixed ASAP, otherwise it'll be a part of the next release.

If you choose to wait for the next release, one way to get around this bug is to shrink your screen (either zoom in or make the window smaller), which is a bit of a pain, but it works.

**Comment by kryten87** [comment]
Thanks @michael-genson , I'll go ahead & close this then.
