### ISSUE TITLE
[v1.0.0b] - Docker compose install is failing - ERROR: Encountered errors while bringing up the project.

### ISSUE THREAD

**Issue by Kickbut101** [mealie-recipes/mealie#1682]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I am simply trying to install mealie with the recommended docker-compose way via the documentation on this page https://hay-kot.github.io/mealie/documentation/getting-started/install/

`sudo docker-compose up -d
Starting mealie ... error

ERROR: for mealie  Cannot start service mealie: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: process_linux.go:458: setting cgroup config for procHooks process caused: can't load program: operation not permitted: unknown

ERROR: for mealie  Cannot start service mealie: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: process_linux.go:458: setting cgroup config for procHooks process caused: can't load program: operation not permitted: unknown
ERROR: Encountered errors while bringing up the project.`

My system:
   Static hostname: docker
         Icon name: computer-container
           Chassis: container
        Machine ID: 195960f05385474a951a6b82e08e1dba
           Boot ID: bdab02f41e77431b9d8bb86cc1f80b63
    Virtualization: lxc
  Operating System: Debian GNU/Linux 11 (bullseye)
            Kernel: Linux 5.15.39-4-pve
      Architecture: x86-64

I have tried both the "@latest" and "hkotel/mealie:frontend-v1.0.0beta-4" just as a troubleshooting measure.

### Deployment

Docker (Linux)

### Deployment Details

I made docker-compose.yml file in /tmp/

Looks like this:

`version: "3.1"
services:
  mealie:
    container_name: mealie
    image: hkotel/mealie:frontend-v1.0.0beta-4
    restart: always
    ports:
      - 9925:80
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago

      # Default Recipe Settings
      RECIPE_PUBLIC: 'true'
      RECIPE_SHOW_NUTRITION: 'true'
      RECIPE_SHOW_ASSETS: 'true'
      RECIPE_LANDSCAPE_VIEW: 'true'
      RECIPE_DISABLE_COMMENTS: 'false'
      RECIPE_DISABLE_AMOUNT: 'false'

      # Gunicorn
      # WEB_CONCURRENCY: 2
      # WORKERS_PER_CORE: 0.5
      # MAX_WORKERS: 8
    volumes:
      - ./mealie/data/:/app/data`

tried running with docker-compose up -d and with sudo docker-compose up -d

**Comment by leshicodes** [comment]
@Kickbut101 Have you tried updating the Host System's OS/Kernel?

[See this post from a user having a similar issue.](https://github.com/opencontainers/runc/issues/3412) in which they reference the solution as the following...

> The problem came from the kernel that has not been updated.
> Fixed with:
> `sudo apt install linux-image-amd64`

So maybe try doing the same?

It also may be worth attempting to do a version update for docker as well, as you may just be hitting a bug with the version you have installed.
