### ISSUE TITLE
[v1.0.0b] - Food.com recipes will not import

### ISSUE THREAD

**Issue by thewolfman56** [mealie-recipes/mealie#1688]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When trying to import recipes from food.com [,](https://www.food.com/recipe/mashed-red-potatoes-with-garlic-and-parmesan-34382) I receive the error "Looks like we couldn't find anything".  When I debug the scraper, I receive the message ""recipe_scrapers was unable to scrape this URL"

It looks like my installation is using Recipe Scraper v 14.11.0 and according to the issues page for Recipe Scraper, this looks to be a bug corrected in 14.13.0

### Deployment

Unraid

### Deployment Details

Not using the built-in template for unRAID

**Comment by michael-genson** [comment]
Not sure what version you were on at the time, but it's working on the newest version:
https://www.food.com/recipe/ground-beef-stuffed-green-bell-peppers-with-cheese-1356
![image](https://user-images.githubusercontent.com/71845777/198689804-80beffc7-5636-4122-9066-291da94af20a.png)

**Comment by thewolfman56** [comment]
> Not sure what version you were on at the time, but it's working on the newest version: https://www.food.com/recipe/ground-beef-stuffed-green-bell-peppers-with-cheese-1356 ![image](https://user-images.githubusercontent.com/71845777/198689804-80beffc7-5636-4122-9066-291da94af20a.png)

I was using v1.0.0beta-4, but I just upgraded to v1.0.0beta-5 after reading the response and the Food.com recipe import works for me now.
