### ISSUE TITLE
live (or close to live) sync for shopping list

### ISSUE THREAD

**Issue by g-vdn** [mealie-recipes/mealie#1714]
Would be great to have a live update or a sync each 5 secs or something on the shopping list. Like OurGrocery app.
You go to the market with somebody else - both of you can "work" on same shopping list, checking items and stuff. Check item on phone A (account A), after x amount of seconds, that same item is checked also on phone B (account B).

Thanks!

P.S. Amazing looking app so far, now I'm checking how to switch from Cookbook/Nextcloud to this one.

**Comment by michael-genson** [comment]
Interesting. So, for example, two people have the same shopping list open on two different devices, and if one person checks off an item, the other person sees that change?
