### ISSUE TITLE
Recipe names shouldn't be unique

### ISSUE THREAD

**Issue by Roebie** [mealie-recipes/mealie#1726]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I have checked for existing issues that have been resolved in v1-beta

### What is the issue you are experiencing?

The recipe name apparently needs to be unique. 
This shouldn't imho be the case as it is extremely limiting.

I collect soup recipes. I have for example like 35 leek soup recipes (that have enough differences to be considered different recipes). Some of those 35 have a unique name, but most don't. They are just called 'leek soup', because that's what they are.
However, I can only create one recipy called 'leek soup' in Mealie, which is quite ridiculous as the other 34 recipes are also just 'leek soup'. 
Now I end up adding a number to the recipes name, just to make it unique, but anyone can see that this is cumbersome and doesn't look good.

Can something be done about this? Imho, the uniqueness of a recipe should be on some internal database record id, not the name of a recipe.

Thank you.

### Deployment

Docker (Synology)

### Mealie Version

0.5.6

**Comment by hay-kot** [comment]
Recipes have unique names because that's how the URL schema is defined for recipe routes. If we were to change to an ID or UUID there would be an outpouring of complaints about the new URL schema and non-pretty urls. 

This is just the way that it is going to be.
