### ISSUE TITLE
Wrong unit for calories

### ISSUE THREAD

**Issue by Roebie** [mealie-recipes/mealie#1727]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I have checked for existing issues that have been resolved in v1-beta

### What is the issue you are experiencing?

Under the heading Nutrition sometimes the calories are provided (when the website I'm importing a recipe from provides this information).

I have noticed that Mealie displays this information with an incorrect unit: calories (cal) instead of kilocalories (kcal). I noticed it first while my Mealie website was set to Nederlands (Dutch), but I have also tried this in French, German, American English and British English. In all five languages the caloric unit is cal instead of kcal, so it's probably not a simple translation issue.

Example: https://15gram.be/recepten/kabeljauw-met-prei-in-roomsaus
On this website the calories are clearly shown as 627.31 kcal

However on import in Mealie the calories are shown as 627,31 calories. So the value is suddenly 1000 times lower and incorrect.

I also noticed that it's possible to change the value but not the unit by hand. I wonder what would happen if the source website would have it's caloric value expressed in (the official SI) kJ unit instead of (the obsolete, but still often used) kcal unit.

Thanks for fixing this bug.

### Deployment

Docker (Synology)

### Mealie Version

0.5.6

**Comment by hay-kot** [comment]
We adhere to the schema.org definitions for units whenever possible. In this case, the sites are not confirming to the correct standard set-out by them, we'd effectively have to guess what the unit is since not everyone adhere's the standard. The bottom line is that the parser will never be perfect because not everyone on the internet will adhere to the schema defined.

https://schema.org/calories
