### ISSUE TITLE
[v1.0.0b] - Mealie API excessive memory consumption

### ISSUE THREAD

**Issue by tommyalatalo** [mealie-recipes/mealie#1728]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

The Mealie API container has a very high memory consumption, even at idle.
I have my container set to a limit of 1300mb and Mealie API hovers around 1000mb+ constantly, and seems to periodically crash and restart due to hitting the memory limit.

Why is an idle api spending more than a gigabyte of memory? I would have expected less than 100mb ram usage for a service that's just sitting there doing nothing.

I'm running the `hkotel/mealie:api-nightly` image, so perhaps this is still work in progress, but I didn't see any related issues.

### Deployment

Docker (Linux)

### Deployment Details

Deployed with docker using Nomad.

**Comment by michael-genson** [comment]
I can't reproduce this, I've been running nightly on Docker for weeks and it's idling around 200-230mb. Is there anything else you might be doing with Nomad? Do you have any logs?

**Comment by hay-kot** [comment]
I have 3 instances running and haven't experienced this, they all idle around 200-300mb. FastAPI does run with higher memory than I'd expect, but I haven't found a way around this. 

Can you provide more information about your deployment and configuration?

**Comment by tommyalatalo** [comment]
My deployment is quite basic, only difference being I'm using Nomad to deploy the containers since I use it to manage a homelab cluster.

```hcl
job "mealie" {
  datacenters = ["main"]
  type        = "service"

  vault {
    policies    = ["mealie", "smtp"]
    change_mode = "restart"
  }

  group "mealie" {
    network {
      mode = "bridge"
      port "api" {
        to = 9000
      }
      port "frontend" {
        to = 3000
      }
    }

    task "api" {
      driver = "docker"

      config {
        image      = "hkotel/mealie:api-nightly"
        volumes    = ["/zpool/services/mealie:/app/data"]
        force_pull = true
      }

      service {
        name = NOMAD_JOB_NAME
        port = "api"

        check {
          port     = "api"
          name     = "${NOMAD_JOB_NAME} ${NOMAD_TASK_NAME} http"
          type     = "http"
          path     = "/api/app/about"
          interval = "30s"
          timeout  = "2s"
        }
      }

      resources {
        memory = 1000
      }

      template {
        destination = "secrets/env"
        change_mode = "restart"
        env         = true
        data        = <<-EOH
        DB_ENGINE=sqlite
        BASE_URL=https://mealie.mydomain.com
        {{ with secret "kv/smtp" -}}
        SMTP_HOST={{ .Data.data.smtp_host }}
        SMTP_PORT={{ .Data.data.smtp_port }}
        SMTP_AUTH_STRATEGY={{ .Data.data.smtp_auth | toUpper }}
        SMTP_FROM_EMAIL={{ .Data.data.smtp_email | replaceAll "@" "+mealie@" }}
        SMTP_USER={{ .Data.data.smtp_email }}
        {{- end }}
        {{ with secret "kv/mealie" -}}
        SMTP_FROM_NAME=Mealie
        SMTP_PASSWORD={{ .Data.data.smtp_password }}
        {{- end -}}
        EOH
      }
    }

    task "frontend" {
      driver = "docker"

      config {
        image      = "hkotel/mealie:frontend-nightly"
        volumes    = ["/zpool/services/mealie:/app/data"]
        force_pull = true
      }

      service {
        name = NOMAD_JOB_NAME
        port = "frontend"

        check {
          port     = "frontend"
          name     = "${NOMAD_JOB_NAME} ${NOMAD_TASK_NAME} http"
          type     = "http"
          path     = "/login"
          interval = "30s"
          timeout  = "2s"
        }
      }

      template {
        destination = "local/env"
        change_mode = "restart"
        env         = true
        data        = <<-EOH
          API_URL=http://127.0.0.1:{{ env "NOMAD_PORT_api" }}
        EOH
      }
    }
  }
}
```

I just verified again that the memory use is excessive, both the Nomad UI memory graph and `docker stats` (output below) shows very high memory usage for the api container. It went up as high as 994mb while I was watching it for a minute. I redeployed the containers yesterday with `force_pull` enabled so the images are up to date.

```
CONTAINER ID   NAME                                       CPU %     MEM USAGE / LIMIT    MEM %     NET I/O   BLOCK I/O         PIDS
22ccb61d6f03   api-a9055876-b5bf-ee2c-d746-e1417ed8898d   0.80%     914.6MiB / 1000MiB   91.46%    0B / 0B   4.23TB / 15.5MB   27
```

The logs do seem to have something a bit unusual, this keeps repeating:

```
[2022-10-16 09:42:14 +0200] [34] [WARNING] Worker with pid 44042 was terminated due to signal 9
[2022-10-16 09:42:14 +0200] [44562] [INFO] Booting worker with pid: 44562
[2022-10-16 09:42:14 +0200] [44562] [INFO] Started server process [44562]
[2022-10-16 09:42:14 +0200] [44562] [INFO] Waiting for application startup.
[2022-10-16 09:42:14 +0200] [44562] [INFO] Application startup complete.
[2022-10-16 09:43:14 +0200] [34] [WARNING] Worker with pid 44060 was terminated due to signal 9
[2022-10-16 09:43:14 +0200] [44580] [INFO] Booting worker with pid: 44580
[2022-10-16 09:43:15 +0200] [44580] [INFO] Started server process [44580]
[2022-10-16 09:43:15 +0200] [44580] [INFO] Waiting for application startup.
[2022-10-16 09:43:15 +0200] [44580] [INFO] Application startup complete.
[2022-10-16 09:47:16 +0200] [34] [WARNING] Worker with pid 44132 was terminated due to signal 9
[2022-10-16 09:47:16 +0200] [44645] [INFO] Booting worker with pid: 44645
[2022-10-16 09:47:16 +0200] [44645] [INFO] Started server process [44645]
[2022-10-16 09:47:16 +0200] [44645] [INFO] Waiting for application startup.
[2022-10-16 09:47:16 +0200] [44645] [INFO] Application startup complete.
[2022-10-16 09:48:17 +0200] [34] [WARNING] Worker with pid 44144 was terminated due to signal 9
[2022-10-16 09:48:17 +0200] [44663] [INFO] Booting worker with pid: 44663
[2022-10-16 09:48:17 +0200] [44663] [INFO] Started server process [44663]
[2022-10-16 09:48:17 +0200] [44663] [INFO] Waiting for application startup.
[2022-10-16 09:48:17 +0200] [44663] [INFO] Application startup complete.
```

**Comment by hay-kot** [comment]
Can you try killing the server and setting all your [Web Worker](https://nightly.mealie.io/documentation/getting-started/installation/backend-config/#webworker) ENV Settings explicitly to 1 and let us know if it improves?

**Comment by tommyalatalo** [comment]
I set the three worker env vars to 1, and it seems to have improved the situation.
After starting up the service again the API container starts up to about 150mb ram usage, after accessing the web page it jumps up to about 250mb, so we're down to a quarter of what I had before.

**Comment by GeeteshMehto** [comment]
Hello sir, please assign this issue to me as i already worked on this kind of problem in past and has a great experience.

**Comment by hay-kot** [comment]
@GeeteshMehto You're welcome to work on this issue. We don't really assign issues. If you want to work I this, I suggest submitting a draft PR and linking the Issue, that way folks can see what you're working on.

---

For the overall issue, I've been playing around with the deployment locally trying to make some improvements. I think part of the issue is with how Python allocates memory for the process vs the actual used memory. If your machine has 16gb of memory Python will allocate a larger portion of that to it's process to avoid having to go back to the OS to get more memory space. 

I was able to pretty drastically improve idle memory by setting the containers limits in the docker-compose. 

```yaml
  mealie:
    container_name: mealie-api
    deploy:
      resources:
        limits:
          memory: 500M
    build:
      context: ./
      target: production
      dockerfile: Dockerfile
```

Setting the containers limit to 500M and 1000M dropped my idle memory usage to 157M down from 250M. I'll be including this recommendation in the docs in a PR shortly. I still think it idles pretty high, but I haven't been able to pin down the overall issue.

**Comment by hay-kot** [comment]
Changes deployed in #1758 have dropped my memory consumption on idle to around 60-70mb. Can anyone else report their results from the latest beta? Thinking this can be closed, but would like to get some more confirmation that things have improved.

**Comment by tommyalatalo** [comment]
> Changes deployed in #1758 have dropped my memory consumption on idle to around 60-70mb. Can anyone else report their results from the latest beta? Thinking this can be closed, but would like to get some more confirmation that things have improved.

It goes up to 130-140mb on idle right after startup for me.
