### ISSUE TITLE
Lol... deleting default account deletes all accounts

### ISSUE THREAD

**Issue by bcsteeve** [mealie-recipes/mealie#1729]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I have checked for existing issues that have been resolved in v1-beta

### What is the issue you are experiencing?

I really don't know if I'm on V0.5.x or the 1 beta or whatever... I'm not going to use this software so I leave this as a courtesy.

Installing this very bloated software was insane.  When it finally finished, I logged in with the default account and the first thing I did was create a new account with my chosen credentials.  I logged out, logged in with the new account and went and deleted the default account.  Instantly both accounts were deleted and I was kicked out with no way to get back in.

You'll want to fix that.  Good luck.

### Deployment

Docker (Linux)

### Mealie Version

no idea, since you didn't make it obvious anywhere.

**Comment by hay-kot** [comment]
Hey, this isn't how you talk to people or interact with open source. 

I've confirmed that this isn't what happens when you do what you described. Closing and locking the issue.
