### ISSUE TITLE
[spelling] scrapper -> scraper in home page

### ISSUE THREAD

**Issue by hauntingEcho** [mealie-recipes/mealie#1737]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I have checked for existing issues that have been resolved in v1-beta

### What is the issue you are experiencing?

spelling error in the homepage

### Deployment

Other

### Deployment Details

none

### Mealie Version

https://hay-kot.github.io/mealie/

**Comment by GeeteshMehto** [comment]
Hello sir, please assign this issue to me as i already worked on this kind of problem in past and has a great experience.\
