### ISSUE TITLE
[v1.0.0b] - Beta 5 has not yet appeared on DockerHub

### ISSUE THREAD

**Issue by SteveDinn** [mealie-recipes/mealie#1770]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Got the notification email from GitHub stating that beta 5 was not available. I went to look for it on DockerHub, but it's still not there nearly a day later.

### Deployment

Docker (Linux)

### Deployment Details

n/a

**Comment by hay-kot** [comment]
I'm having a multitude of build issues that I can't reproduce locally, so I have to keep trying to build in CI.

All I can say is to have patience while I get the build errors resolved.

**Comment by hay-kot** [comment]
Images are now published, thanks for your patience!

**Comment by SteveDinn** [comment]
Impatience just means we want it :)

Thanks!
