### ISSUE TITLE
[META] Mealie Demo page using an expired SSL certificate

### ISSUE THREAD

**Issue by gPoupon** [mealie-recipes/mealie#1776]
https://mealie-demo.hay-kot.dev/

Expired October 25th; also using HSTS so the demo is effectively inaccessible until the cert gets renewed.

**Comment by hay-kot** [comment]
That url is no longer valid.

https://demo.mealie.io

Is the new demo link.


Where did you find this link?

**Comment by geogn4t** [comment]
I've actually seen this before when I first encountered Mealie on the Unraid Community Apps Store.

The user that manages the app has that URL listed here: https://forums.unraid.net/topic/129137-support-kakersuk-mealie/ 
Additionally, in the Unraid UI, there's a link the project page, which directs users to this url: https://hay-kot.github.io/mealie/

![image](https://user-images.githubusercontent.com/36601147/198112486-6901e2f5-e793-4cc0-8e53-ad179e3b60a2.png)

I did ask about v1 in the unraid forum and did get a response that this app is only for the pre v1 version.. Can't recall if it was .5 or something else.

**Comment by gPoupon** [comment]
@hay-kot I got it from here: https://hay-kot.github.io/mealie/

Someone on reddit linked to this project using that, but I guess it's not the main URL being used anymore then?
