### ISSUE TITLE
Recipe rating is displayed in title on recipe pages

### ISSUE THREAD

**Issue by shiruken** [mealie-recipes/mealie#1778]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I have checked for existing issues that have been resolved in v1-beta

### What is the issue you are experiencing?

When viewing recipe pages, the numeric rating assigned to the recipe is showing up in the title

![Recipe with 5-star Rating](https://user-images.githubusercontent.com/867617/198159933-ebe61439-facd-475d-a593-abaf8951ef31.png)

![Recipe with 3-star Rating](https://user-images.githubusercontent.com/867617/198160017-177e57ef-48e3-4e0c-bfac-dd8e052a15d0.png)

### Deployment

Unraid

### Mealie Version

v1.0.0beta-5

**Comment by michael-genson** [comment]
I did some playing around and it has two requirements to reproduce:
1. The recipe has to be rated (i.e. if you never give it a rating it won't have a number)
2. The recipe can't be in landscape mode

It doesn't actually change the title in the data, it's just displaying `title + rating`

**Comment by michael-genson** [comment]
I have a PR coming, thank you for the report!
