### ISSUE TITLE
[v1.0.0b] - SMTP authentication in B5 no longer works

### ISSUE THREAD

**Issue by digi303** [mealie-recipes/mealie#1781]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Since beta 5, SMTP authentication no longer works.
With the same settings beta 4 runs without problems.
It seems to be due to the SMTP_FROM_EMAIL entry, as the log file speaks of an invalid sender or unkown aliases.

2022-10-26T21:53:35.518290108Z,stdout,"ERROR: 26-Oct-22 23:53:35 	(554, b'5.7.1 Database error. / Der angegebene Absender ist keiner Ihrer erlaubten Aliase.')

While troubleshooting, I also noticed an error in the log. Could this be the problem?

2022-10-26T21:51:31.911225878Z, stdout, /app/mealie/run.sh: line 62: [: ==: unary operator expected

### Deployment

Docker (Synology)

**Comment by proffalken** [comment]
I've just had to troubleshoot this myself.

Not sure about the bash error as I've not looked into it, but if you set `SMTP_FROM_NAME` to an email address instead of a string then the email will be received by the remote SMTP server.

Obviously that's not a fix, but it might help someone track down the issue.

**Comment by digi303** [comment]
Thanks for the quick reply.
I have just tested it - it works perfectly.

A good workaround for the moment.

Thank you.

**Comment by michael-genson** [comment]
> I've just had to troubleshoot this myself.
> 
> Not sure about the bash error as I've not looked into it, but if you set `SMTP_FROM_NAME` to an email address instead of a string then the email will be received by the remote SMTP server.
> 
> Obviously that's not a fix, but it might help someone track down the issue.

Yep this helped, thanks! I'm working on a PR
