### ISSUE TITLE
[v1.0.0b] - Rating is appended to recipe name

### ISSUE THREAD

**Issue by digi303** [mealie-recipes/mealie#1784]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

The star rating is appended to the recipe name. I am not sure if this is how it should be.

Example with 1 star:
![1](https://user-images.githubusercontent.com/94383598/198544043-ccfdccd1-a394-48fa-8564-d9ab7a29733e.jpg)

Example with 5 stars:
![5](https://user-images.githubusercontent.com/94383598/198544125-9199ade5-578e-442a-bfd9-a3b13059f57e.jpg)

### Deployment

Docker (Synology)

**Comment by michael-genson** [comment]
This is fixed in nightly: #1778

**Comment by digi303** [comment]
Sorry haven' t seen this issue and the fix.

**Comment by michael-genson** [comment]
> Sorry haven' t seen this issue and the fix.

No worries!
