### ISSUE TITLE
[v1.0.0b] - public share link broken

### ISSUE THREAD

**Issue by digi303** [mealie-recipes/mealie#1788]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

The public share link no longer works.
You are only redirected to the registration page.

### Deployment

Docker (Synology)

**Comment by michael-genson** [comment]
I can't reproduce this in the newest version. Which version are you on? Can you post any server logs, or client logs from your browser?

**Comment by hay-kot** [comment]
Is your recipe set to public?

**Comment by digi303** [comment]
I use the "official" Beta 5 as a Docker container. I have attached the build data.
The recipe is set to public. Pictures & link attached.

https://rezeptserver.my-router.de/explore/recipes/be1e30d4-9c5d-4ebb-9fb8-6ba83a028150/rollo-pollo

![Mealie_Build](https://user-images.githubusercontent.com/94383598/198971646-5a5bf929-b62c-434b-b419-562e85e45856.jpg)

![Rollo](https://user-images.githubusercontent.com/94383598/198972126-f47c2c35-0e45-4a7b-9c53-2b356225841b.jpg)



I'll install the nightly right away - let's see if anything changes.

**Comment by digi303** [comment]
Unfortunately, nightly doesn't work for me at all. The frontend somehow does not find the API.
All settings from the B5 have been adopted and checked several times. I can't get it to work.
![front-night](https://user-images.githubusercontent.com/94383598/198980583-8623300d-68ce-4663-ac68-6541158a511f.jpg)

Mealie API-nightly / frontend b5 works, but nothing changes with the public link.
![error](https://user-images.githubusercontent.com/94383598/198982771-142556d0-7834-4252-934e-fd97a8e1d09e.jpg)
a shared link works. Therefore, I assume that the basic configuration is correct.

**Comment by hay-kot** [comment]
One last thing to check, is your group set to private? 

![CleanShot 2022-10-31 at 23 24 30@2x](https://user-images.githubusercontent.com/64056131/199180790-8ad3ee7c-95c8-4f21-8e19-b1b780e45055.png)

**Comment by digi303** [comment]
Yes, the group is set "private".
And the first checkmark "allow users outside of your group to see your recipes" is also unchecked.

I will uncheck the private group setting and set the first point and verify the public link...

OK - with the group setting private, the public link remains "locked" no matter what else you set.
I assumed that the "public recipe" setting would release it.

As soon as you uncheck the "private" box, it works as desired.
Whether it's a bug or a feature, it's now working again.

Many thanks for the tip.

**Comment by hay-kot** [comment]
@digi303 

I agree it's somewhat confusing. The general Idea is that `Private Group` setting overrides all recipe sharing preferences.  The `allow users outside of your group to see your recipes` is just the default settings when a new recipe is created, so it's not really applicable in this case. 

Basically. 

```mermaid
stateDiagram-v2
  r1: Request Access
  p1 : Is Group Private?
  p2: Is Recipe Private?
  s1: Deny Access
  n1: Allow Access
  
  r1 --> p1
  p1 --> p2: No
  p1 --> s1: Yes

  p2 --> s1: Yes
  p2 --> n1: No
```

I think that's the right approach to this? 🤷 Open to suggestions on either clarifying the current behavior or changing the behavior to something more intuitive.

**Comment by digi303** [comment]
@hay-kot 
If you follow the "group is above recipe" approach, this is completely correct and also makes sense. Clear line. 
Nice Graphics  btw. Helps to understand.
In my logic, however, I would want to leave the final decision to the "owner" of the individual recipe. I.e. if the group is private, then in principle all recipes are also private - but the creator of a recipe can make his own - and only his own - public. The others in the group, of course, cannot.

But that is of course my personal view. I also understand your approach and think it makes sense.

If, for example, members of a cooking group develop recipes together, your approach is definitely the better one.

**Comment by yottabit42** [comment]
I am also unable to share recipes. In my case the group is not private, the recipes are not private. I can use the share icon in the recipe index, then the "+ New" button. Next I click on the copy URL button, and I receive a toast: "Recipe link copied to clipboard." But the clipboard is always empty.

Mealie: v1.0.0beta-5
Browser: Chrome 107.0.5304.92

**Comment by hay-kot** [comment]
@yottabit42, the issue here is really just an issue of clarity in how the sharing works. Yours sound like a actual bug. Could you submit your own issue so we can track it?

**Comment by yottabit42** [comment]
@hay-kot, done! #1800.
