### ISSUE TITLE
Localisation using Fluent

### ISSUE THREAD

**Issue by m00nwtchr** [mealie-recipes/mealie#1789]
Currently, the names of ingredients, units, etc. when combined together with the numerical value sound weird in many languages, (for me, Polish). It would be nice if the localisation was done using Project Fluent (https://projectfluent.org/) which aims to allow applications to accommodate the grammar of languages that don't fit with how English does it (without e.g. having to create a new unit object in mealie).

**Comment by hay-kot** [comment]
This looks like it would require a significant rewrite of all our translation infrastructure. That's just not something I can take on with this project. Sorry.
