### ISSUE TITLE
[v1.0.0b] - Recipe Link Sharing Clipboard Left Empty

### ISSUE THREAD

**Issue by yottabit42** [mealie-recipes/mealie#1800]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

The group is not private, the recipes are not private. I can use the share icon in the recipe index, then the "+ New" button. Next I click on the copy URL button, and I receive a toast: "Recipe link copied to clipboard." But the clipboard is always empty.

Mealie: v1.0.0beta-5
Browser: Chrome 107.0.5304.92

[Here](https://youtu.be/_0ts3QEFHs0) is a screen recording of the actions I took. The window recording didn't capture my right-click and attempt to choose Paste from the menu in the URL field, but the Paste options were grayed out, as well as the normal Ctrl+V also not pasting anything. The clipboard remains empty.

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
Looking at your video, you don't have a valid SSL cert for the site. The browsers Copy API has restrictions on when you can access it. I believe the conditions are

- Site is localhost or 127.0.0.1
- Site is HTTPS and has a valid certificate

Can you check your browser console for an error to confirm? If that is the error then we (Mealie) should at least show an error message.

**Comment by yottabit42** [comment]
Yep, that is the problem then. I am not using HTTPS. I need to install ingress or another reverse proxy to get that working at some point. Thanks!

**Comment by yottabit42** [comment]
Confirmed after setting up SSL that the share copy function works now! I had been meaning to do this for years, so thanks for giving me justification! lol

**Comment by hay-kot** [comment]
Thanks for reporting back!
