### ISSUE TITLE
[v1.0.0b] - CSS loads in a different order in prod vs dev, causing several visual issues

### ISSUE THREAD

**Issue by michael-genson** [mealie-recipes/mealie#1802]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Some of the frontend components have the wrong background color in my prod instance. Here's a simple example:

In dev (what it _should_ look like):
![image](https://user-images.githubusercontent.com/71845777/200041356-c0f144cb-2d48-4126-a638-04d47909c356.png)

In prod:
![image](https://user-images.githubusercontent.com/71845777/200041420-0f1afca3-fd53-4e42-a55f-94cc77427bea.png)

It seems to stem from the order of CSS being different between dev and prod. Using Chrome dev tools for this element under `Computed` I get different results (in the dev tools the top result "wins")

In dev:
![image](https://user-images.githubusercontent.com/71845777/200041921-fd24d332-c9d8-437b-a19d-2a6d80fa1346.png)

In prod:
![image](https://user-images.githubusercontent.com/71845777/200041965-0ea30e1b-c08c-4dec-bd77-70462f51881f.png)

There are other examples that are more egregious:

dev:
![image](https://user-images.githubusercontent.com/71845777/200042510-28acb20f-61b7-42ba-8a25-bb92a924ff79.png)

prod:
![image](https://user-images.githubusercontent.com/71845777/200042443-07d9b98e-8a19-45b4-893c-6e9855e5758e.png)

Has anyone else experienced this in prod, or is it just me? If it's just me I'll look at my deployment and such, but I'm doing everything pretty stock so I'm not sure what I could do differently.

I use Chrome, but I checked on incognito and Firefox with the same results so it doesn't seem browser-specific.

### Deployment

Docker (Synology)

**Comment by hay-kot** [comment]
Can confirm I've experienced this. I've also seen it mentioned by other folks, thanks for the detailed report!

**Comment by michael-genson** [comment]
Small, weird update on this. I was playing around with light and dark mode and noticed if you toggle from dark mode -> light mode -> back to dark mode, the CSS renders correctly (until a refresh)

![image](https://user-images.githubusercontent.com/71845777/205324605-0e07a52f-4e2c-472b-83d7-d803fd536e89.png)

¯\\_(ツ)_/¯
