### ISSUE TITLE
[v1.0.0b] - Automatic "Link Ingredients" does not work when special characters are next to the word

### ISSUE THREAD

**Issue by RealFoxie** [mealie-recipes/mealie#1803]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When using the "link ingredients" automatic feature, it only works for an exact match, which is to be expected. However, any special character like `,` en `**` (used to make ingredients bold in the instructions) will also break the feature.
Example:
`Add **sugar**, Mascarpone, cheese`
Only cheese will automatically get selected as a food. `sugar` has `**` next to it, `Mascarpone` has `,` next to it.

Note that with ```Add **sugar**, Mascarpone, cheese.```, `cheese` will not be linked, because of `.`

It could be that a food item has some special characters included, that should also be matched. But most typical sentence characters (, . and *) should probably be ignored, improving the workings of this feature.

### Deployment

Docker (Linux)

**Comment by jenscalaerts** [comment]
I am looking into creating a fix for this issue but I feel like I have found some more issues with this. 

1. A partial match for example an ingredient called "Celery" will match "ce" in the step. (this might be intended)
2. A word after a newline will not match for example in the following multiline "celery" will not match because it is after a newline.
"This is a line with no trailing space
celery will never match"

Are these intended?

**Comment by RealFoxie** [comment]
Partial match can be nice so "add the eggs" would also match for the ingredient "egg".
In some way this could be limited. It's hard to know how exactly, as it can be language dependent (some languages might have eggsies as plural of egg). It should match the most equal ingredient word first though (So first "Celery" before "Ce" for the world Celery in a recipe text). 
If a recipe has "Ce" as an ingredient and in the instructions there is "Celery", I think a match can be expected. I don't think this problem would happen often?

**Comment by hay-kot** [comment]
> Are these intended?

No. This was a pretty half-baked implementation that I could figure out a good rule of thumb for, so I never went back to fix it.
