### ISSUE TITLE
[v1.0.0b] - Cannot create food or unit in Ingredients Amount UI

### ISSUE THREAD

**Issue by brettinternet** [mealie-recipes/mealie#1805]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When I select "Create" for "food" or "unit" in the "Ingredients Amount" section, there's a 422 HTTP error in the client console.

![Screen Shot 2022-11-07 at 1 18 39 PM](https://user-images.githubusercontent.com/20871604/200406788-b180c4a5-d825-4164-9fdc-91aa46925035.png)

```
Error: Request failed with status code 422
    at t.exports (b9f1f2e.js:2:230763)
    at t.exports (b9f1f2e.js:2:290930)
    at XMLHttpRequest.O (b9f1f2e.js:2:229357)
```

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
Can you provide your logs from your server and what browser you're using?

**Comment by brettinternet** [comment]
The server logs aren't much help here. Prior to these messages are just a bunch of HTTP 200 messages from loading the recipe.

```
INFO: "POST /api/units HTTP/1.1" 422 Unprocessable Entity
INFO: "GET /api/units?page=1&perPage=-1 HTTP/1.1" 200 OK
INFO: "POST /api/units HTTP/1.1" 422 Unprocessable Entity
INFO: "GET /api/units?page=1&perPage=-1 HTTP/1.1" 200 OK
INFO: "GET /api/users/self HTTP/1.1" 200 OK
INFO: "POST /api/units HTTP/1.1" 422 Unprocessable Entity
INFO: "GET /api/units?page=1&perPage=-1 HTTP/1.1" 200 OK
```

I've tried this on both lastest Chrome and Firefox versions on an arm64 MacOS. I've also disabled uBlock/extensions, etc.

**Comment by ismakc** [comment]
Same error here, with similar logs. Should I try to provide some new info to resolve the issue?

**Comment by ismakc** [comment]
My bad! It seems that the name of the food must be typed before clicking on create.
