### ISSUE TITLE
[v1.0.0b] - Recipe can't be added to list

### ISSUE THREAD

**Issue by uwtgomi** [mealie-recipes/mealie#1813]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When trying to add a recipe to a shopping list (both from the overview and the detail view), a popup appears with all my shoppinglists. Clicking on the list however does not do anything. Ingredients are not added to the list, and the popup stays open.

### Deployment

Docker (Synology)

### Deployment Details

**Details**
Version: v1.0.0beta-5
Build: ee121a12f8db33ecb4db5f8582f7ea9788d019e4
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.20.0

**Checks**
Secure Site: No
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: No
Docker Volumes: success

Browser: Firefox

**Comment by mreimbold** [comment]
I am having the same issue when trying to add a recipe to the shopping list that does not have a quantity specified for an ingredient. The api logs the following error

```
pydantic.error_wrappers.ValidationError: 1 validation error for ShoppingListItemCreate
quantity
  none is not an allowed value (type=type_error.none.not_allowed)
```

Maybe this is the case for you as well?

EDIT: Setting the quantity to 0 seems to work

**Comment by uwtgomi** [comment]
My recipe does have quantites, still it does not work. I checked the log - the error is the same as the one you posted.
there seems to be something popping up in the UI, but it is hidden by the header-bar.
