### ISSUE TITLE
[v1.0.0b] - /api/recipes/create mislabeled in API spec

### ISSUE THREAD

**Issue by Mustachipleb** [mealie-recipes/mealie#1819]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

The OpenAPI docs indicate /api/recipes/create is to be used to create a new recipe, while this is actually /api/recipes in practice.

### Deployment

Docker (Linux)

### Deployment Details

image: hkotel/mealie:api-v1.0.0beta-5

**Comment by michael-genson** [comment]
Can you send a screenshot of what you're seeing? On my instance I don't have a `/create` route. I'm on nightly though, so it's possible someone fixed it.

**Comment by Mustachipleb** [comment]
![image](https://user-images.githubusercontent.com/37940247/208780877-118e871c-c608-4d56-86c6-ccac8ccf00c3.png)
The mistake (at least I think so) is present in the redocly documentation.
