### ISSUE TITLE
[v1.0.0b] - Misleading quantities on default recipes with a 1 as the unit

### ISSUE THREAD

**Issue by nkringle** [mealie-recipes/mealie#1821]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I'm considering this feedback/a bug of the 1.x release but it may be a feature request in someone else's eyes. 

In mealie, by default when you create or import a recipe and do not use the quantities functionality (for example, if you are using the apis to import a recipe using the ios / siri shortcut (which I am doing), the import process defaults the ingredients to all have a unit of '1', and then puts the actual imported text in the comment/notes section. 

[An example recipe](https://www.crazyforcrust.com/crockpot-apple-dump-cake/)

![Screenshot 2022-11-14 at 9 29 21 AM](https://user-images.githubusercontent.com/11429076/201700512-9c4ae8bf-0077-43da-a7c2-80fb2e7f34f3.png)

When this recipe is viewed, the unit of '1' and the notes are displayed next to each other and make it look like the actual unit is something different:

![Screenshot 2022-11-14 at 9 24 44 AM](https://user-images.githubusercontent.com/11429076/201700705-4a1ed739-a43e-4a1c-8158-e61e6e74cee8.png)

This has caused me a bunch of pain where I am following a recipe and end up not realizing that the 1 on the ingredient list should be ignored - at times causing me to need to start over what I am cooking. (For example - above it looks like it is 1.25 cups of sugar, but it is actually 0.25 cups). 

I realize I could go through and fix the units of my recipes, but I currently have hundreds (probably nearing a thousand) recipes in mealie so that's a long process. 😄 

I think there are a couple of different approaches that would work for this:
- Do not show the meaningless 1 if the parser hasn't run on that recipe.
- Find some way to visually separate the quantity from the description, using some separator that won't be confused for something else (i.e. a '-', '.', etc)
- Auto-run the parser on ingredients as a recipe is being created
- Show a little flag or notice on the recipe that the ingredients haven't been parsed 

At the end of the day, if I can be able to pull up one of these recipes and not accidentally quadruple the salt that is supposed to be in it, I will be happy! 😂 

### Deployment

Other

### Deployment Details

Docker on mac

**Details**
Version: v1.0.0beta-5
Build: ee121a12f8db33ecb4db5f8582f7ea9788d019e4
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.20.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: Yes
Docker Volumes: success

**Comment by michael-genson** [comment]
You can set the default behavior of recipes to disable ingredient amounts in group settings (https://MEALIE-URL/group):
![image](https://user-images.githubusercontent.com/71845777/201704767-ba31179c-2e49-496f-97e4-25cf2b01ec2d.png)

This will match the behavior you're expecting, I think. You can then toggle it on for individual recipes.

**Comment by nkringle** [comment]
Thanks - I changed that. I think it may make sense to add context to what that toggle does to the documentation/side effects of potentially having it on. 

That still doesn't change the behavior of importing recipes via the API - it probably shouldn't default all ingredients to a unit of 1? (Maybe this a a feature request? - is there a plan to have the import API use the NLP?)

**Comment by RealFoxie** [comment]
I think your point:
`Find some way to visually separate the quantity [and food] from the description, using some separator that won't be confused for something else (i.e. a '-', '.', etc)` makes sense even outside of this problem.
When using this feature as intended, the description should be visually separated, I think? E.g. putting it cursive. This would also make it more clear what is happening.

Also note you can press the blue "Parse" button to already import everything via (some kind of) NLP. It just doesn't do it directly because you'd probably have to make some changes like creating units and foods.
