### ISSUE TITLE
[v1.0.0b] - API uses invalid LDAP query

### ISSUE THREAD

**Issue by tnunamak** [mealie-recipes/mealie#1832]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

In short, it does not appear that the backend LDAP query supports my current LDAP configuration. As you can see, the LDAP log shows a query using objectClass=user and cn=tnunamak, but I do not use this objectClass and I use uid instead of cn. FWIW, I was able to get it working with 0.5.

API configuration:
```
LDAP_AUTH_ENABLED: "true"
LDAP_SERVER_URL: "ldap://ldap.my.domain"
LDAP_TLS_INSECURE: "true"
LDAP_BIND_TEMPLATE: uid={},ou=People,dc=my,dc=domain
LDAP_BASE_DN: dc=my,dc=domain
LDAP_ADMIN_FILTER: (memberOf=cn=Admins,dc=my,dc=domain)
```

LDAP log:
```
6373df5e conn=12748 op=0 BIND dn="uid=tnunamak,ou=People,dc=my,dc=domain" method=128
6373df5e conn=12748 op=0 BIND dn="uid=tnunamak,ou=People,dc=my,dc=domain" mech=SIMPLE ssf=0
6373df5e conn=12748 op=0 RESULT tag=97 err=0 text=
6373df5e conn=12748 op=1 SRCH base="dc=my,dc=domain" scope=2 deref=0 filter="(&(?objectClass=user)(|(cn=tnunamak)(?sAMAccountName=tnunamak)(mail=tnunamak)))"
6373df5e conn=12748 op=1 SRCH attr=name mail
6373df5e conn=12748 op=1 SEARCH RESULT tag=101 err=32 nentries=0 text=
```

LDAP user:
![image](https://user-images.githubusercontent.com/1095217/202002283-46f30223-8af5-48f5-9777-717c144f9b4a.png)
![image](https://user-images.githubusercontent.com/1095217/202002487-828f9d0e-851c-4753-9665-6f0c337356e3.png)
![image](https://user-images.githubusercontent.com/1095217/202002560-1af1fd29-a125-4125-b481-8d9c9df3b00f.png)
![image](https://user-images.githubusercontent.com/1095217/202002619-bbd49995-ea75-4573-b754-747e41d401c0.png)

### Deployment

Docker (Linux)

### Deployment Details

beta-5

**Comment by proffalken** [comment]
I suspect this is linked to https://github.com/hay-kot/mealie/issues/1775 ?

**Comment by tnunamak** [comment]
> I suspect this is linked to #1775 ?

Possibly... I'm an LDAP noob, but I'm not sure how my use case would work as long as `cn` and `objectClass=user` are hardcoded.
