### ISSUE TITLE
[v1.0.0b] - recipe-scraper v14.23.0 fixes importing on several websites

### ISSUE THREAD

**Issue by elliotmatson** [mealie-recipes/mealie#1834]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Attempting to import anything from Delish.com fails with the following debug message:
`"recipe_scrapers was unable to scrape this URL"`
This also fails on the demo site.
I tried just using the recipe-scrapers library by itself, and it seems to work fine

### Deployment

Docker (Linux)

**Comment by elliotmatson** [comment]
Just tried recipe-scrapers v14.20.0 that the current build of mealie uses, and it indeed fails. Looks like it was fixed in v14.23.0:
 hhursev/recipe-scrapers/pull/676

**Comment by michael-genson** [comment]
Interestingly the newest version fails to pull in the picture, while the version we're on finds it fine.
Obviously it's much preferable to upgrade and get the recipe vs staying on the existing version and only getting the image, but I found that interesting.

Thanks for the report! I'll put in a PR
