### ISSUE TITLE
[v1.0.0b] - Creating New Recipe - Only Notes available for Ingredients

### ISSUE THREAD

**Issue by thewolfman56** [mealie-recipes/mealie#1841]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When creating new recipe or editing an imported recipe, only the Notes are available to add for ingredients.  Food and quantity are not shown.  I attempted to create new docker images to see if it was in issue with my current configuration, but the fresh instance has this same issue when creating a new recipe.  This is the first time I have tried to add a new recipe since updating to beta-5 from beta-4 and is the first time I noticed this issue.

Mealie Version: v1.0.0beta-5
Tried using Chrome and MS Edge and see the same result. 

![image](https://user-images.githubusercontent.com/71470070/202884762-5495fff3-5415-4fd0-b2e1-13cd9172a31d.png)

### Deployment

Unraid

### Deployment Details

Deployment is in unRAID using custom templates to add the 2 containers.

**Comment by michael-genson** [comment]
Did you enables foods on the recipe options?

**Comment by thewolfman56** [comment]
> Did you enables foods on the recipe options?

I didn't see "Foods", but after seeing your response, I see that "Disable Ingredient Amounts" was defaulted to "On".  Turning that off allowed me to enter the food amounts.

**Comment by thewolfman56** [comment]
Not sure why "Disable Ingredient Amounts" defaults to "On".  I never noticed that setting before when I entered recipes when I first started using it.

**Comment by michael-genson** [comment]
> Not sure why "Disable Ingredient Amounts" defaults to "On".  I never noticed that setting before when I entered recipes when I first started using it.

In your group settings you can choose the default behavior so new recipes don't disable ingredient amounts

**Comment by thewolfman56** [comment]
> > Not sure why "Disable Ingredient Amounts" defaults to "On".  I never noticed that setting before when I entered recipes when I first started using it.
> 
> In your group settings you can choose the default behavior so new recipes don't disable ingredient amounts

Thanks, but I do not see that in the group management.

![image](https://user-images.githubusercontent.com/71470070/203121431-a9a0d681-3065-4618-802a-b215846cb17f.png)

**Comment by michael-genson** [comment]
It's the bottom option:
>Disable organizing recipe ingredients by units and food

If you uncheck that, then new recipes will have `Disable Ingredient Amounts` disabled
