### ISSUE TITLE
[v1.0.0b] - Import from recettesjecuisine.com fails

### ISSUE THREAD

**Issue by sochartgit** [mealie-recipes/mealie#1842]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Unable to import recipes from recettesjecuisine.com (french site).

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
I tried scraping using the latest version of recipe-scrapers but got a `WebsiteNotImplementedError` exception. Looks like the scraper doesn't support it.

You can try heading over to https://github.com/hhursev/recipe-scrapers to see if you can request to have it added.
