### ISSUE TITLE
Slow (20s) to load recipes/database

### ISSUE THREAD

**Issue by BrandonG777** [mealie-recipes/mealie#1846]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I have checked for existing issues that have been resolved in v1-beta

### What is the issue you are experiencing?

The base interface loads quickly but then I find myself waiting nearly 20s for the recipes to populate. Sometimes while loading a a single recipe I'll experience the same delay, as if it's struggling for connectivity with the database for some reason. I can navigate for a short period of time very quickly and then it's like the database has to reload on the client side. Hardware is a Dell Precision T7910 with dual Intel® Xeon® CPU E5-2630 v3 @ 2.40GHz & 64GB of ECC RAM. I've experienced this issue for over a year but was thinking it was related to the sqlite database I was using. Yesterday I migrated to a postgresql14 setup but I'm still experiencing this delay. I realize you will most likely need more information to track this down but short of logs, that don't seem to show any real problems, I'm not sure what I need to provide at this time. I can provide direct access to my site but prefer not to give the URL publicly. There is a few browser console errors but none that point to anything obvious, for me at least.

### Deployment

Unraid

### Deployment Details

unRAID 6.11.5 
Experienced this issue immediately after setting up Mealie approx. one year ago and bulk imported my recipes via a text file with URLs into an initial sqlite database.
A year later, running version 0.5.6 (latest tag), migrated data into postgresql14 docker container via mealie's backup/restore function. Cleared appdata during this migration as well to have a clean start.

### Mealie Version

0.5.6

**Comment by michael-genson** [comment]
I strongly recommend upgrading to the 1.0.0 beta, which is vastly more performant over 0.5.6:
https://github.com/hay-kot/mealie/discussions/1073

**Comment by BrandonG777** [comment]
Not sure I have the time to figure out this migration. Appreciate your efforts though.

**Comment by hay-kot** [comment]
@BrandonG777 At this point the v1 betas are more stable than the v0.5 versions. The main reason for not publishing a solid v1 is that we're still missing some sharing features that I think should be finished before we call it v1.

Migrating should be fairly straight forward, https://nightly.mealie.io/documentation/getting-started/migrating-to-mealie-v1/

Closing this issue since these problems have all been addressed in the Beta. Thanks!
