### ISSUE TITLE
[v1.0.0b] - Administrator Account Can Be Locked Out

### ISSUE THREAD

**Issue by Zackptg5** [mealie-recipes/mealie#1859]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I got locked out of my admin account (obviously my fault). Since it was the admin account, there was nothing I could do about it but wait or just wipe it and restore a backup. Can admin accounts be exempt from account lockouts?

### Deployment

Docker (Linux)

**Comment by RealFoxie** [comment]
Is this not exactly like  #1317 ?
For which a PR already exists: [#1848](https://github.com/hay-kot/mealie/pull/1848)

**Comment by Zackptg5** [comment]
Aw shoot I'll need to use more broad keywords when I search issues next time. Sorry and thanks!

**Comment by hay-kot** [comment]
@Zackptg5, I don't think that is the same? 

You're saying you got locked out by using the wrong password too many times? That get's automatically unlocked after 24 hours I believe. Otherwise you can exec into the container and run the script below to reset locked users. You can find it in the container in `/app/scripts` I believe.

https://github.com/hay-kot/mealie/blob/mealie-next/mealie/scripts/reset_locked_users.py

The issues @Melsarion is referring too is for users who delete their own accounts.

**Comment by Zackptg5** [comment]
@hay-kot 

Oh ok. That's definitely easier than wiping the container volume lol. Can that get added to the faq? Thanks!

**Comment by tonka3000** [comment]
@hay-kot I tried https://github.com/hay-kot/mealie/blob/mealie-next/mealie/scripts/reset_locked_users.py today but the script is screaming for a groupid. Any ideas?

![image](https://github.com/user-attachments/assets/a6f17568-37e1-44db-81e7-48ff7d0ca0eb)

**Comment by freebs65** [comment]
i have the same issue.. i guess there is no answer yet

**Comment by tonka3000** [comment]
I got it working by connect into the container, open a python shell and manipulate the SQLite database by hand via regular sqlite3 library from python.

**Comment by freebs65** [comment]
ok.. I just did the same .. i set login_attemps  <-- spelt let wrong in database  to 0 and locked_at to NULL 
worked fine.. pain in the ass though

thanks!

**Comment by Trevo525** [comment]
> ok.. I just did the same .. i set login_attemps <-- spelt let wrong in database to 0 and locked_at to NULL

`update users set login_attemps='0', locked_at=NULL where id = 'USER_ID';`
That's the exact command I used to get this to work for me in case anyone else needs it in the future.
