### ISSUE TITLE
[v1.0.0b] - Calendar inputfield does not reflect the locale settings

### ISSUE THREAD

**Issue by coolkau** [mealie-recipes/mealie#1860]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I select a language such as British English or German,.
I open the recipe menu " add to mealplan".

The data picker still is in US "mm dd yyyy" format and the week starts with Sunday.
I guess the locale settings arent fed to the date picker.

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Can you show an example? All my date pickers are in YYYY-MM-DD format, regardless of locale:
![image](https://user-images.githubusercontent.com/71845777/204098289-cfd4a70e-9770-477f-ac3d-531f47f3201e.png)

It would be nice to localize this, and we should probably remove the hint that says `MM/DD/YYYY` format, but if you're actually seeing a different format in the date picker maybe my instance is just busted

**Comment by hay-kot** [comment]
FYI #1864 will fix this issue. There's likely more inconsistencies across the application with the date pickers though. 

Format will likely stay YYYY-MM-DD format since it's the format the backend uses and every time I try to do something with time I want to pull my hair out. 👍 - though I did change the hint so it's at least accurate!

**Comment by coolkau** [comment]
So yes indeed hint is wrong but the time is indeed YYYY-MM-DD. I am fine with that, its a less opinionated locale.

I was mainly triggered by the hint, in combiantion with the week starting Sunday.. and the week starting in the middle of the weekend is something so confusing.

And I am amazed how there is no language out there which can even remotely handle language in an OK way :D ...the hours, the tears, the sweat, the desperation, ...
