### ISSUE TITLE
[v1.0.0b] - drewq2004 - mealie error populating recipe from URL 

### ISSUE THREAD

**Issue by Drewq2004** [mealie-recipes/mealie#1874]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

After installing v1.0.0b attempted to import a recipe from multiple sites and all returned the same error.  Running from both Brave and Firefox but same error comes back after importing URL.  
I am running most current front end and api end of mealie.  

![Pasted Screenshot 2022-12-01 21-32-38](https://user-images.githubusercontent.com/43890373/205224315-dcae1c8c-7951-4ac1-ac72-1ce33d4e62e6.png)

Any help as to why application version is not approved?

![Pasted Screenshot 2022-12-01 21-33-23](https://user-images.githubusercontent.com/43890373/205224367-15449349-76be-4796-8556-b6711c486d06.png)

### Deployment

Docker (Synology)

### Deployment Details

running current beta of mealie v1.0.0-b.

**Comment by hay-kot** [comment]
URL in the image you provided seems to work just fine. Best guess is that you don't have your container configured for external access. Can you exec into your container and see if you can access the outside internet? 

https://demo.mealie.io/recipe/meatloaf-recipe-with-the-best-glaze?edit=false

**Comment by bartmans** [comment]
You have to edit the Synology firewall to allow traffic to the subnet Mealie instance is using.

In DSM go to Docker - Network - Mealie v1-default - unhide details. 
Copy the subnet
Go to Configuration - Security - Firewall - Edit rules
Add rule Allow all - all for the subnet you found above
Make sure this rule comes before the end rule Deny Deny Everyting (move it up)

**Comment by Drewq2004** [comment]
Not sure if there is another ip address and port that I need to allow.  I do have wild card certtificate and reverse proxy so I can access via https.  Can you explain?


Andrew Carl

West Seattle Bowl

P: 206.932.3731  ​HO: 206.282-7394

A: 4505 39th Ave. S.W., Seattle, WA 98116

W: www.wsbowl.com<http://www.wsbowl.com/>  -  www.three9lounge.com<http://www.three9lounge.com>





This e-mail message may contain confidential or legally privileged information and is intended only for the use of the intended recipient(s). Any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is prohibited. E-mails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, or contain viruses. Anyone who communicates with us by e-mail is deemed to have accepted these risks. Company Name is not responsible for errors or omissions in this message and denies any responsibility for any damage arising from the use of e-mail. Any opinion and other statement contained in this message and any attachment are solely those of the author and do not necessarily represent those of the company.



________________________________

**Comment by bartmans** [comment]
> Not sure if there is another ip address and port that I need to allow. I do have wild card certtificate and reverse proxy so I can access via https. Can you explain?

I edited my first reply with howto find the subnet and add that to the Synology firewall. Should fix it. No need for other rules (as this is traffic going from inside to outside, not from outside to inside).

**Comment by Drewq2004** [comment]
Thanks for the Edit but I can't see anywhere to test that outside access from Portainer.  I have included a couple more screen shots of the synology docker side and it may shed some light.



Andrew Carl

West Seattle Bowl

P: 206.932.3731  ​HO: 206.282-7394

A: 4505 39th Ave. S.W., Seattle, WA 98116

W: www.wsbowl.com<http://www.wsbowl.com/>  -  www.three9lounge.com<http://www.three9lounge.com>





This e-mail message may contain confidential or legally privileged information and is intended only for the use of the intended recipient(s). Any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is prohibited. E-mails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, or contain viruses. Anyone who communicates with us by e-mail is deemed to have accepted these risks. Company Name is not responsible for errors or omissions in this message and denies any responsibility for any damage arising from the use of e-mail. Any opinion and other statement contained in this message and any attachment are solely those of the author and do not necessarily represent those of the company.



________________________________

**Comment by bartmans** [comment]
The way to check is to import an URL (including image) works from a recipe site that is known to work. Ie this one: https://dagelijksekost.een.be/gerechten/stoofvlees-friet

In Portainer there is a page with the networks. They look something like 172.x.0.0. Add this subnet to your firewall in the Synology configuration - Networks - Firewall section.

**Comment by Drewq2004** [comment]
Thanks a bunch.  That worked perfectly.


Andrew Carl

West Seattle Bowl

P: 206.932.3731  ​HO: 206.282-7394

A: 4505 39th Ave. S.W., Seattle, WA 98116

W: www.wsbowl.com<http://www.wsbowl.com/>  -  www.three9lounge.com<http://www.three9lounge.com>





This e-mail message may contain confidential or legally privileged information and is intended only for the use of the intended recipient(s). Any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is prohibited. E-mails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, or contain viruses. Anyone who communicates with us by e-mail is deemed to have accepted these risks. Company Name is not responsible for errors or omissions in this message and denies any responsibility for any damage arising from the use of e-mail. Any opinion and other statement contained in this message and any attachment are solely those of the author and do not necessarily represent those of the company.



________________________________
