### ISSUE TITLE
[v1.0.0b] - SMTP Error: Multiple Addresses in a From header

### ISSUE THREAD

**Issue by andrewdunndev** [mealie-recipes/mealie#1887]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Attempting to use Fastmail as an SMTP provider, using this for several other applications with similar deployment patterns.

Seeing error when attempting to send mail:
```
ERROR: 06-Dec-22 10:06:37 	(551, b'5.7.1 Multiple addresses in a From header is not allowed')
```

### Deployment

Docker (Linux)

### Deployment Details

Environmental variable set:
```
SMTP_HOST=smtp.fastmail.com
SMTP_PORT=587
SMTP_AUTH_STRATEGY=TLS
SMTP_FROM_NAME=user@domain.tld
SMTP_FROM_EMAIL=user@domain.tld
SMTP_USER=user@domain.tld
SMTP_PASSWORD=<REDACT>
```

**Comment by andrewdunndev** [comment]
Not sure if anyone has suggestions on how to debug, I'd love to sort this out and get it working.

**Comment by andrewdunndev** [comment]
Just to report, I'd moved my instance to the single/monolith container so I'm consuming nightly. I could do some interactive debugging on discord if that's desired.

**Comment by smarthall** [comment]
I got it working with these variables:

```
    SMTP_FROM_EMAIL: "mealie@my.domain.name"
    SMTP_FROM_NAME: " "
```

Which resulted in the following `From` header in the email, which still looks unexpected, but seemed to work

```
Subject: Test Email
From:  , mealie@my.domain.name
```

**Comment by mtshv** [comment]
I also can not configure SMTP for the fastmail. Same error.
```
{
    "success": false,
    "error": "(551, b'5.7.1 Multiple addresses in a From header is not allowed')"
}
```

@andrewgdunn were you able to sort this out?

----

@smarthall I tried your suggestion and it did not work for me. Are you using fastmail? If so is it `465` or `587` ?

**Comment by smarthall** [comment]
I always use the TLS auth strategy (I worry about the mechanics of STARTTLS). So that would be port 465 for most providers, including fastmail.

**Comment by mtshv** [comment]
@smarthall  thank you for the fast response 🙏 

Here is my config:
```
      - SMTP_HOST=smtp.fastmail.com
      - SMTP_PORT=465
      - SMTP_FROM_NAME=" "
      - SMTP_AUTH_STRATEGY=SSL
      - SMTP_FROM_EMAIL="name@domain.com"
      - SMTP_USER=name@domain.com
      - SMTP_PASSWORD=<password>
 ```
 Unfortunately test email from `admin/site-settings` still fails with `{"success":false,"error":"(551, b'5.7.1 Multiple addresses in a From header is not allowed')"}`

**Comment by Gamodeur** [comment]
Good morning,
I have exactly the same problem with the supplier OVH.

**Comment by Stunt0265** [comment]
I'm also not able to send using Fastmail.
