### ISSUE TITLE
https://kochclub.schuhbeck.de doesn't work

### ISSUE THREAD

**Issue by motocamp** [mealie-recipes/mealie#1901]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Import not possible

### Deployment

Docker (Synology)

**Comment by hay-kot** [comment]
This site provides no Schema data, and since we don't maintain the scraper this is outside of the scope for this project. Thanks!
