### ISSUE TITLE
Thekitchn.com Recipe Import Failure

### ISSUE THREAD

**Issue by pKai3** [mealie-recipes/mealie#1902]
Other recipes from this site do import succesfully.

Deployment: Docker (Unraid)

URL: https://www.thekitchn.com/recipe-nobu-miso-marinated-black-cod-117238

Data:
{
  "totalTime": "PT0S",
  "nutrition": {
    "saturatedFatContent": "0.5 g",
    "unsaturatedFatContent": "0.0 g",
    "carbohydrateContent": "15.4 g",
    "sugarContent": "10.4 g",
    "servingSize": "Serves 4",
    "proteinContent": "42.5 g",
    "fatContent": "2.6 g",
    "calories": "295 cal",
    "sodiumContent": "763.9 mg",
    "fiberContent": "0.9 g",
    "cholesterolContent": "0 mg",
    "@type": "NutritionInformation"
  },
  "description": "",
  "creator": {
    "@type": "Person",
    "name": "Kathryn Hill"
  },
  "datePublished": "2015-02-17T07:30:00-05:00",
  "brand": {
    "@type": "Thing",
    "name": "The Kitchn"
  },
  "recipeCuisine": [
    "Japanese",
    "Asia"
  ],
  "dateCreated": "2015-02-17T07:30:00-05:00",
  "aggregateRating": {
    "ratingCount": 35,
    "@type": "AggregateRating",
    "ratingValue": 4.5
  },
  "recipeInstructions": [
    {
      "text": "Two to 3 days beforehand, make the miso marinade and marinate the fish. Bring the sake and mirin to a boil in a medium saucepan over high heat. Boil for 20 seconds to evaporate the alcohol. Turn the heat down to low, add the miso paste, and whisk. When the miso has dissolved completely, turn the heat up to high again and add the sugar, whisking constantly to ensure that the sugar doesn&#x27;t burn on the bottom of the pan. Remove from heat once the sugar is fully dissolved. Cool to room temperature.",
      "image": null,
      "@type": "HowToStep",
      "name": "Step 1"
    },
    {
      "text": "Pat the black cod fillets thoroughly dry with paper towels. Slather the fish with the miso marinade and place in a non-reactive dish or bowl and cover tightly with plastic wrap. Leave to marinate in the refrigerator for 2 to 3 days.",
      "image": null,
      "@type": "HowToStep",
      "name": "Step 2"
    },
    {
      "text": "To cook the fish: Preheat oven to 400°F. Heat an oven-proof skillet over high heat on the stovetop. Lightly wipe off any excess miso clinging to the fillets, but don&#x27;t rinse it off. Film the pan with a little oil, then place the fish skin-side-up on the pan and cook until the bottom of the fish browns and blackens in spots, about 3 minutes. Flip and continue cooking until the other side is browned, 2 to 3 minutes. Transfer to the oven and bake for 5 to 10 minutes, until fish is opaque and flakes easily.",
      "image": null,
      "@type": "HowToStep",
      "name": "Step 3"
    }
  ],
  "HowtoTip": {
    "text": "Adapted from Nobu: The CookbookInstead of cooking the fish on the stovetop, you can do this step on an outdoor grill or under the broiler in your oven.This post was originally published May 2010."
  },
  "articleSection": "Recipes",
  "keywords": [
    "asian",
    "blitz",
    "dinner",
    "easy",
    "Gluten-Free",
    "Healthy Living",
    "japanese",
    "Main Dish",
    "Make Ahead",
    "Party Food",
    "recipe",
    "seafood",
    "weeknight dinner",
    "purpose:search",
    "platform:search",
    "course:main dish",
    "cuisine:japanese",
    "cuisine:asia",
    "mainingredients:seafood",
    "mainingredients:fish",
    "diet:low-fat",
    "diet:low-calorie",
    "diet:gluten-free",
    "diet:under 500 calories",
    "diet:under 400 calories",
    "diet:under 300 calories",
    "meal:dinner",
    "updated:2022-10-02"
  ],
  "suitableforDiet": "https://schema.org/GlutenFreeDiet,https://schema.org/LowCalorieDiet,https://schema.org/LowFatDiet",
  "thumbnailUrl": "https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fill,g_auto,w_1500,ar_3:2/k%2Farchive%2F3931a592af8ade154bf5357f733ba57fbd54ba51",
  "recipeCategory": [
    "Main dish",
    "Dinner"
  ],
  "dateModified": "2022-10-02T13:25:00-04:00",
  "publisher": {
    "logo": {
      "url": "https://www.thekitchn.com/static/logos/publisher-logo.png",
      "width": 180,
      "@type": "ImageObject",
      "height": 46
    },
    "@type": "Organization",
    "name": "Apartment Therapy, LLC."
  },
  "name": "Nobu&#8217;s Miso-Marinated Black Cod",
  "author": [
    {
      "URL": "https://thekitchn.com/authors/kathryn-hill",
      "jobTitle": "",
      "description": "",
      "@type": "Person",
      "name": "Kathryn Hill"
    }
  ],
  "url": "https://www.thekitchn.com/recipe-nobu-miso-marinated-black-cod-117238",
  "image": [
    {
      "url": "https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_16:9/k%2Farchive%2F3931a592af8ade154bf5357f733ba57fbd54ba51",
      "@type": "ImageObject"
    },
    {
      "url": "https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_4:3/k%2Farchive%2F3931a592af8ade154bf5357f733ba57fbd54ba51",
      "@type": "ImageObject"
    },
    {
      "url": "https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_1:1/k%2Farchive%2F3931a592af8ade154bf5357f733ba57fbd54ba51",
      "@type": "ImageObject"
    }
  ],
  "recipeIngredient": [
    "1/4 cup sake",
    "1/4 cup mirin",
    "1/4 cup white miso paste",
    "3 tablespoons granulated sugar",
    "4  (8-ounce) black cod fillets"
  ],
  "headline": "Nobu&#8217;s Miso-Marinated Black Cod",
  "recipeYield": 4,
  "mainEntityOfPage": "https://www.thekitchn.com/recipe-nobu-miso-marinated-black-cod-117238",
  "@context": "https://schema.org",
  "@type": "Recipe"
}

**Comment by hay-kot** [comment]
This seems to work in the latest version. What version are you using?

**Comment by pKai3** [comment]
I was using the docker hkotel/mealie:latest tag, which seems to be v0.5.0. Shows last pushed one year ago?
https://hub.docker.com/r/hkotel/mealie/tags

On unraid, this is the defaut repository. Should we be using something different?
Thanks!

**Comment by hay-kot** [comment]
Gotcha. I don't know much about the Unraid package stuff, but I've been suggesting folks move to the v1 beta. It's more stable, but is missing some features hence the beta tag. 

I know some people have it working on Unraid, but I'm not super sure how to get all the working. The nighty docs have more information on how to set it up in docker, though I don't know how helpful that may be.

https://nightly.mealie.io/documentation/getting-started/migrating-to-mealie-v1/

**Comment by pKai3** [comment]
Thanks for the advice, I will try the suggested tag and if I have anything useful to report from the migration process / usage on unraid I'll try to document it for you. Thanks again!
