### ISSUE TITLE
[v1.0.0b] - Star rating shows as a number next to recipe title in recipe page

### ISSUE THREAD

**Issue by Spalfnaganalf1** [mealie-recipes/mealie#1903]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

This is a minor cosmetic issue and i couldn't see it mentioned anywhere, but when you rate a recipe, the number of stars appears as a number next to the recipe title. For example - a recipe titled 'Rum Balls' would appear as 'Rum Balls 5' if they were rated as 5 stars. 

### Deployment

Docker (Synology)

### Deployment Details

**Details**
Version: v1.0.0beta-5
Build: ee121a12f8db33ecb4db5f8582f7ea9788d019e4
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.20.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: Yes
Docker Volumes: success

**Comment by michael-genson** [comment]
This is fixed in nightly: https://github.com/hay-kot/mealie/pull/1779
