### ISSUE TITLE
[v1.0.0b] - Deleting Current Logged In User in Admin Dashboard does not redirect to Login Page

### ISSUE THREAD

**Issue by smvdbrink** [mealie-recipes/mealie#1979]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I logged in the app for the first time, with username changeme@email.com and password MyPassword. I went to Settings -> Users and created a new user with all the options at the bottom checked (Administrator, group stuff and advanced features). I then clicked on the bin-icon behind the changeme@email.com account. This resulted in both the accounts (the one I intended to delete ánd the newly created account) to be deleted.

I tried to add my new user again, but that is not possible. There is no error, the Create-button at the bottom doesn't do anything. 

### Deployment

Docker (Linux), Docker (Synology)

### Deployment Details

I use Docker on a synology, but the installation was done via SSH. See my docker-compose file attached.
[docker-compose.txt](https://github.com/hay-kot/mealie/files/10339076/docker-compose.txt)

**Comment by hay-kot** [comment]
I'm not able to verify this. Are you sure that both accounts were deleted? If you delete the Admin account your logged in with your token is automatically invalidated therefor you can no longer access data via the API so you see the following

![CleanShot 2023-01-03 at 16 13 35](https://user-images.githubusercontent.com/64056131/210466759-71ef8e9d-1340-4eef-8978-4290a749a2af.png)

That might give the indication that all users have been deleted, but in reality you've just deleted yourself.

--- 

After you deleted the administrator did you try to log in with the newly created user?

**Comment by smvdbrink** [comment]
That was exactly what I saw when I deleted the user. I wasn't sure if it would still work after logging off, so I only tried that just now. I was able to log in with the account I created yesterday and it also shows in User Management. So it appears to be a visual bug rather than something really nasty.
