### ISSUE TITLE
[v1.0.0b] - ingredients and unit management ( edition and delete ) not possible

### ISSUE THREAD

**Issue by gniackman** [mealie-recipes/mealie#1988]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

impossible to edit or delete ingredients or unit once created.

creating unit and ingredients works fine 
but once created, there is no way to delete or edit the elements.

### Deployment

Docker (Linux)

### Deployment Details

docker

![image](https://user-images.githubusercontent.com/17276499/210751347-2706f261-7634-4124-b1cb-3f8004d8e766.png)

**Comment by Kuchenpirat** [comment]
Hey, 
if you are logged in as a a admin / user with manage privileges, in your profile you should see a point "Manage Data" where you can alter and delete ingredients, recipes, units, labels and also foods. 

Hope this helps

**Comment by gniackman** [comment]
found ! thanks it miss some refresh page on delete validation
