### ISSUE TITLE
[v1.0.0b] - docker compose postgresql doc exposes wrong port

### ISSUE THREAD

**Issue by EasternPA** [mealie-recipes/mealie#1991]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

The PostgreSQL instructions [here](https://nightly.mealie.io/documentation/getting-started/installation/postgres/) show port 9925 being forwarded to 3000 on frontend but frontend is listening on 3001.

I'm using this with a Cloudflare tunnel hosted within the same docker compose stack so I actually don't expose any ports to my LAN. It's working beautifully.

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
The frontend container _does_ expose port 3000. We're using Caddy internally to optimize the redirects and file serving, so the docker-compose example is correct. 

You can see the dockerfiles here https://github.com/hay-kot/mealie/tree/mealie-next/docker

**Comment by EasternPA** [comment]
Okay. I saw 3001 in the logs and didn't get a web page until I changed it. Thank you.
