### ISSUE TITLE
[v1.0.0b] - Can't change password in mobile browser

### ISSUE THREAD

**Issue by kenske** [mealie-recipes/mealie#2002]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I created a user, and I'm able to log in just fine using a desktop browser and the PWA. However, I can only change the user's password using a desktop browser. When I try to do it in the PWA it returns an error saying my existing password does not match.

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
Can you provide any more detail on this and/or double check your results? I've tried to replicate it a few times, but it works fine on every PWA/mobile device I have.
