### ISSUE TITLE
[v1.0.0b] - Can't have empty instructions/ingredients

### ISSUE THREAD

**Issue by PaddiM8** [mealie-recipes/mealie#2003]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

If I delete the default instructions or the default ingredient, they reappear after I save and refresh. This means that it isn't possible to store dishes without any instructions. I don't have a recipe for all dishes, but I still want to store them in order to use them for meal planning and such.

I guess this would be solved if it was possible to customize the default values, but I haven't found a way to do that.

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
That is super annoying. Best course of action is to probably eliminate the defaults all together and just provide some in-browser help for information on what's supported in the markdown format.

**Comment by PaddiM8** [comment]
> That is super annoying. Best course of action is to probably eliminate the defaults all together and just provide some in-browser help for information on what's supported in the markdown format.

Hm yeah. I have some ideas for this, and I could try to implement it. How about removing the defaults, but maybe create an example recipe automatically when a new group is created? This way you could look at how that recipe was made and it might also help users get a better understanding of the interface right away, before creating any recipes of their own.

It might also be useful to have an info button above the recipe instruction field, that opens a markdown guide dialog? Not sure what would be best here though.

**Comment by zierbeek** [comment]
Oh that would be nice. A tooltip for for example "how to show a video" or "how to link other recipes"

**Comment by fleshgolem** [comment]
The defaults really are not the problem here, there is just a subtle bug in the `__init__` method of RecipeModel, caused by empty lists being falsy, that will lead to this behaviour. I can provide a fix for it in short time

**Comment by PaddiM8** [comment]
@fleshgolem Are the defaults needed though? I find it a bit annoying to have to remove them all the time. They're good for demonstrative purposes, but that could be done with a default recipe.

**Comment by hay-kot** [comment]
> The defaults really are not the problem here, there is just a subtle bug in the __init__ method of RecipeModel, caused by empty lists being falsy, that will lead to this behaviour. I can provide a fix for it in short time

I agree that the core problem is not the defaults, it's a logical error.

> Are the defaults needed though? I find it a bit annoying to have to remove them all the time. They're good for demonstrative purposes, but that could be done with a default recipe.

Though this point about UX is a pretty valid one. I think there's better ways to accomplish what I'm trying to do. 

Happy to accept a PR to fix the initial issue here, and another on updating the UX issues, or one together.

**Comment by fleshgolem** [comment]
Yeah sure, that both makes sense. I will provide a fix on the issue itself and you can make a decision on how the UX here should be handled in general

**Comment by PaddiM8** [comment]
That makes sense. I'll make a quick PR for what I had in mind!

**Comment by hay-kot** [comment]
Thanks @fleshgolem!

See 

- #2012

for UX discussion/tracking
