### ISSUE TITLE
[v1.0.0b] - Nightly v1: UI white screen on login screen (using Synology)

### ISSUE THREAD

**Issue by bartmans** [mealie-recipes/mealie#2010]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I pulled the latest nightly. I see both container running. When trying to access the UI I only see a spinner. There is no time out, no error en no interface: just a white screen. I see the error:

 ERROR  connect ETIMEDOUT 172.18.0.2:9000  at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
repeated in the log for the frontend container.

**Frontend log**
https://pastebin.com/L668YEGq

**API log**
https://pastebin.com/rGkwbArL

### Deployment

Docker (Synology)

**Comment by hay-kot** [comment]
Frontend Container can't communicate with the backend container. This probably has to do with how the Synology docker network is configured.

**Comment by bartmans** [comment]
Ah. I tightened up the firewall settings. Too tight as it turns out. Added the networks back in, now works. Case closed.
