### ISSUE TITLE
Recipe from https://www.bildderfrau.de don't work

### ISSUE THREAD

**Issue by Baerchen822** [mealie-recipes/mealie#2017]
https://www.bildderfrau.de/kochen-backen/rezepte/article237242947/Penne-in-Tomaten-Kaesesosse.html

as example.

json is used but can not found. 

An idea? Or help?

Or do they don's use json??

kind Regards

**Comment by jeffreytigch** [comment]
I think this is an issue of the website. I am not sure about the inner workings yet, but you can do a basic test by seeing if Google Search can find recipe metadata. If Google can, I can import the recipe into Mealie.

I tested this out with the URL you provided, and it does not have recipe metadata. You can test it out for yourself, or if you want to see the difference, grab one of your URL's you already imported. 

Link to test: https://search.google.com/test

**Comment by jeffreytigch** [comment]
You can also check #1900 , which is a similar issue.
