### ISSUE TITLE
Keep getting logged out

### ISSUE THREAD

**Issue by antonichoudhuri** [mealie-recipes/mealie#2023]
I am the only user on my instance. I use the site on my MBP (chrome), iPad (safari), iPhone (safarI). I notice that I need to log in every single day which is frustrating. 

I looked through Chrome Developer Tools and saw that there are no cookies. It seems that my "token" is stored in Local Storage under `userSettings`.

Is this expected behavior? I would suggest at least a 30 day cookie if not auto-renewing.

**Comment by michael-genson** [comment]
Should be fixed in nightly: https://github.com/hay-kot/mealie/issues/1077

You should also make sure you set the backend env variable appropriately:
https://nightly.mealie.io/documentation/getting-started/installation/backend-config/

**Comment by antonichoudhuri** [comment]
Thanks for responding. I am using docker:latest so I should get the latest when it is released: [hkotel/mealie](https://hub.docker.com/r/hkotel/mealie/)

I adjusted the token time, here is my docker run cmd:
```
docker run -d --name='Mealie' --net='bridge' -e TZ="America/Los_Angeles" -e HOST_OS="Unraid" -e 'DB_TYPE'='sqlite' -e 'TOKEN_TIME'='99999' -p '9925:80/tcp' -v '/mnt/user/appdata/mealie':'/app/data':'rw' 'hkotel/mealie:latest'
252b0bf1b6a27250cc82885d2aa074ee419b3
```

Increased the timeout to ~10 years so I will try for a few days and report back. Since this PWA is using Local Storage I would expect that I need to login on each device at least one more time.

Thanks!

**Comment by michael-genson** [comment]
> Thanks for responding. I am using docker:latest so I should get the latest when it is released: [hkotel/mealie](https://hub.docker.com/r/hkotel/mealie/)

This is actually the old 0.5.x version, which is fairly outdated. You'll want to check out the 1.0.0 beta. Specifically for the token not persisting issue, this was fixed a few days ago in nightly (check out the link above)

I strongly recommend you upgrade to 1.0.0 beta, which is vastly improved over 0.5.x, check out the guide below:
https://nightly.mealie.io/documentation/getting-started/migrating-to-mealie-v1/

**Comment by antonichoudhuri** [comment]
Oh interesing, thanks for responding and letting me know. I had NO idea, lol.

From the [docker hub repo](https://hub.docker.com/r/hkotel/mealie/tags) should I be using the [omni-nightly](https://hub.docker.com/layers/hkotel/mealie/omni-nightly/images/sha256-77d7e5500c56dd2a4f1fc143340917a28b1c41d6999c2c47b801de75e7816a92?context=explore) tag?

Do you have an official docker repo? I wonder why this repo doesn't use `latest` as intended

**Comment by antonichoudhuri** [comment]
I tried to get he `omni-nightly` tag working but it seems it doesn't have a web server running or something I couldn't figure out. I looked at the [dockerfile](https://hub.docker.com/layers/hkotel/mealie/omni-nightly/images/sha256-77d7e5500c56dd2a4f1fc143340917a28b1c41d6999c2c47b801de75e7816a92?context=explore) and couldn't make head or tail of why the web page wasn't loading.

**Comment by hay-kot** [comment]
@antonichoudhuri

You have to expose port 3000 on the omni container, it's missing from the documentation right now.

> Do you have an official docker repo? I wonder why this repo doesn't use latest as intended

That's the official docker repo. As for the latest tag, as with most thing it started with good intentions but as beta software in general, I was shipping breaking changes a lot (with migration paths) and people were constantly coming here and sending me messages complaining about how shit of a person I was for writing such terrible software.

So now we use a nightly tag until I'm confident we have a stable-enough release with feature parity.

We've hit the stable part, but we're missing a few features that were in the original implementation.

**Comment by michael-genson** [comment]
> people were constantly coming here and sending me messages complaining about how shit of a person I was for writing such terrible software

https://xkcd.com/1172/

Honestly though that's terrible. Sorry you had (have?) to put up with that. And for such a massive *free and open source* project that works great. It's also more polished than most open source projects I've worked with at this size

**Comment by antonichoudhuri** [comment]
Yep, thank you for your work on this project @hay-kot. My family and I love it!

**Comment by antonichoudhuri** [comment]
> You have to expose port 3000 on the omni container, it's missing from the documentation right now.

I tried doing this via the below command and still was not able to access the UI via port 9926 and 9927:
`docker run -d --name='Mealie-omni' --net='bridge' -e TZ="America/Los_Angeles" -e HOST_OS="Unraid" -e 'DB_TYPE'='sqlite' -p '9926:80/tcp' -p '9927:3000/tcp' -v '/mnt/user/appdata/mealie':'/app/data':'rw' 'hkotel/mealie:omni-nightly'`

Any tips on what I am doing wrong? Thanks

**Comment by antonichoudhuri** [comment]
Actually I was able to hit a UI at port 9927 but got this error client side:

```
Server error (500 RuntimeError) 
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.
```

Here is the server log:
```
ERROR Cannot find module 'vuetify/src/locale' from '/app/frontend'

at Function.resolveSync [as sync] (node_modules/resolve/lib/sync.js:102:15)
at node_modules/vue-server-renderer/build.prod.js:1:77905
at Object.<anonymous> (webpack:/external "vuetify/src/locale":1:0)
at __webpack_require__ (webpack/bootstrap:25:0)
at Module.<anonymous> (server.js:26791:15)
at __webpack_require__ (webpack/bootstrap:25:0)
at Object.<anonymous> (server.js:22380:18)
at __webpack_require__ (webpack/bootstrap:25:0)
at server.js:118:18
at Object.<anonymous> (server.js:121:10)
```

**Comment by michael-genson** [comment]
That's a bug in the latest version of nightly. A fixed image is already being created. Try again in an hour with the latest image

On the bright side, that probably means you fixed the issue you were having before!
