### ISSUE TITLE
[v1.0.0b] - Executing Maintenance > Tools > Clean Temporary Files reports "Failed to clean temp"

### ISSUE THREAD

**Issue by bentolor** [mealie-recipes/mealie#2031]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

On a fresh installed Mealie installation I tried to execute _Maintenance > Tools > Clean Temporary Files_

As a result I only receive a popup declaring _Failed to clean temp_. No log entry can be found.

Not sure how to debug this.

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
Please provide your deployment details and logs.

**Comment by bentolor** [comment]
Hi @hay-kot! Thanks for you reply.

Deployment follows [single container](https://nightly.mealie.io/documentation/getting-started/installation/single-container/) with only one difference: Omission of `driver: local`.

Logs stays empty. Not sure how to change log levels. But container output reads as follows:

```
INFO:     46.142.79.219:0 - "POST /api/admin/maintenance/clean/temp HTTP/1.1" 500 Internal Server Error
```

`docker exec -it mealie /bin/bash -c 'ls -la /app/'` does not list any `.temp`-Directory. I think it just hasn't used/created.
