### ISSUE TITLE
[v1.0.0b] - "Sort" -> "Last made" and "Rating": Entries missing

### ISSUE THREAD

**Issue by ghuser238490** [mealie-recipes/mealie#2041]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When using the "Sort" Button on the "All Recipes" page _(edit: and the Cookbook pages)_:
- "Last made": Recipes never made are missing in the list
- "Rating": Recipes with no stars are missing.

I'm not sure if this was intended but since it's a sorting and not a filter feature all recipes should be visible.

### Deployment

Docker (Linux)

### Deployment Details

Version
v1.0.0beta-5

Build
c8be9221112136b4929d72ef2a3c96e856ab86c2

**Comment by ghuser238490** [comment]
Obsolete because of https://github.com/hay-kot/mealie/issues/2148

**Comment by hay-kot** [comment]
@ghuser238490 - are you sure? I'm still seeing the same issue on the new search page

Edit: It wasn't working, but now it is for me. Maybe it was a cache issue. Nevertheless - if anyone stumbles here and is having the same issue with the latest nightly, please let me know!

**Comment by fleshgolem** [comment]
I cant test right now, but i am fairly certain that i ported this behaviour over when doing infinite scroll on the page
If we want to get rid of this, it should be fairly trivial, just need to remove the custom queryFilter from RecipeCardSection. Personally i dont really like this behaviour either

**Comment by ghuser238490** [comment]
Yes, the behavior of the 'new' search page seems to be as it should be. But as @hay-kot mentioned in https://github.com/hay-kot/mealie/issues/2194 the additional sort drop-down ist no longer useful.

In the meantime I noticed that the cookbook pages are affected by this issue as well. Recipes in cookbooks with no "last made' date or  no stars are hidden without any hint when sorting by last made date or rating. I'll re-open this issue.
