### ISSUE TITLE
[v1.0.0b] - Repeated log entries, "Running minutely callbacks" should be at debug level instead of info

### ISSUE THREAD

**Issue by ken8521** [mealie-recipes/mealie#2045]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Running v1.0.0beta-4 in docker.

I've never noticed this before, but just noticed these two log entries after the docker service restarted after an update
.
2023-01-19T15:50:39.322507645Z INFO: 19-Jan-23 10:50:39 	Running hourly callbacks
2023-01-19T15:50:39.443129434Z INFO: 19-Jan-23 10:50:39 	Running minutely callbacks

Now, sure enough, I'm getting this entry every single minute.

2023-01-19T15:54:15.774250416Z 127.0.0.1:42114 - "GET /docs HTTP/1.1" 200

### Deployment

Docker (Linux)

### Deployment Details

version: "3.7"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-4
    container_name: mealie-frontend
    network_mode: swag_default
    depends_on:
      - mealie-api
    environment:
    # Set Frontend ENV Variables Here
      - API_URL=http://mealie-api:9000 # 
    restart: always
    ports:
      - 9925:3000 # 
    volumes:
      - /NAS/AppData/mealie:/app/data/ # 

  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-4
    container_name: mealie-api
    network_mode: swag_default
    depends_on:
      - postgres
    volumes:
      - /NAS/AppData/mealie:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.yourdomain.com

    # Database Settings
      - DB_ENGINE=postgres
      - POSTGRES_USER=mealie
      - POSTGRES_PASSWORD=mealie
      - POSTGRES_SERVER=mealie-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mealie
    restart: always
  postgres:
    container_name: mealie-postgres
    image: postgres
    network_mode: swag_default
    restart: always
    environment:
      POSTGRES_PASSWORD: mealie
      POSTGRES_USER: mealie

volumes:
  mealie-data:
    driver: local

**Comment by hay-kot** [comment]
> Now, sure enough, I'm getting this entry every single minute.

That means they're working! We run some scheduled tasks on several internals and this is just the log statement that kicks off the tasks. 

Though these logs should probably be at the debug level instead of info.
