### ISSUE TITLE
[v1.0.0b] - Restoring a Backup in Postgres does not correctly set DB sequence counters

### ISSUE THREAD

**Issue by nkringle** [mealie-recipes/mealie#2051]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

**The side effect/symptom:**
When attempting to create a recipe from a url (both via the api and the ui) it errors out. The API gives a generic 500 error (nothing noted in the logs). When using the UI it acts like the recipe had invalid json+ld data, but you could go to the debug tab it shows great json+ld data. I spun up mealie with sqlite and recipe scraping works fine for the same recipe. I tried several recipes and was able to recreate the issue. 
Here is on of the recipes I used but you could use anything with valid JSON+LD: https://www.allrecipes.com/recipe/7016/french-toast-i/

**Important Context**
I reported this in https://github.com/hay-kot/mealie/issues/1193 (closed due to being stale/unreproducible at the time). Another user (@Naticus) was able to reproduce it and actually uncovered that it is an issue with the sequences in Postgres (more specially their 'current value' counter) being at the value of 1 instead of what they should be. 

**Steps to Reproduce:** 
1. Using a mealie 1.0-beta5 instance running on sqlite and with at least 2 recipes saved with ingredients parsed, create a backup. 
2. Spin up a new instance of mealie 1.0-beta5, but configured with Postgres 4.2. 
3. Upload the backup from step 1 into the new instance from step 2 and restore it. 
4. Attempt to Import a recipe by url, check the 'import original keyboards' checkbox. 
5. See that mealie errors out (the UI will report invalid json ld data). 
6. Using a sql client (like PGAdmin), look at the properties of the sequences on the mealie schema. See that the `current_value` for each sequence is `1`, even when there are more than 1 of a given type (like recipes / ingredients).
7. Using a sql client (I spun up PGAdmin), run the following migrations: (Credit to @naticus for this!)

```SQL
SELECT SETVAL('api_extras_id_seq', (SELECT MAX(id) FROM api_extras));
SELECT SETVAL('group_meal_plans_id_seq', (SELECT MAX(id) FROM group_meal_plans));
SELECT SETVAL('ingredient_food_extras_id_seq', (SELECT MAX(id) FROM ingredient_food_extras));
SELECT SETVAL('invite_tokens_id_seq', (SELECT MAX(id) FROM invite_tokens));
SELECT SETVAL('long_live_tokens_id_seq', (SELECT MAX(id) FROM long_live_tokens));
SELECT SETVAL('notes_id_seq', (SELECT MAX(id) FROM notes));
SELECT SETVAL('password_reset_tokens_id_seq', (SELECT MAX(id) FROM password_reset_tokens));
SELECT SETVAL('recipe_assets_id_seq', (SELECT MAX(id) FROM recipe_assets));
SELECT SETVAL('recipe_ingredient_ref_link_id_seq', (SELECT MAX(id) FROM recipe_ingredient_ref_link));
SELECT SETVAL('recipe_nutrition_id_seq', (SELECT MAX(id) FROM recipe_nutrition));
SELECT SETVAL('recipe_settings_id_seq', (SELECT MAX(id) FROM recipe_settings));
SELECT SETVAL('recipes_ingredients_id_seq', (SELECT MAX(id) FROM recipes_ingredients));
SELECT SETVAL('server_tasks_id_seq', (SELECT MAX(id) FROM server_tasks));
SELECT SETVAL('shopping_list_extras_id_seq', (SELECT MAX(id) FROM shopping_list_extras));
SELECT SETVAL('shopping_list_item_extras_id_seq', (SELECT MAX(id) FROM shopping_list_item_extras));
```

8. Using a sql client (like PGAdmin), look at the properties of the sequences on the mealie schema. See that the `current_value` for each sequence is now equivalent to the current count of recipes (for example).
9. Attempt to Import a recipe by url, check the 'import original keyboards' checkbox. 
10. See that the recipe now imports correctly without errors. 

### Deployment

Other

### Deployment Details

Docker on Mac

**Details**
Version: v1.0.0beta-5
Build: ee121a12f8db33ecb4db5f8582f7ea9788d019e4
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.20.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: Yes
Docker Volumes: success

**Comment by Naticus** [comment]
Just for documentation purposes, my details were:

Docker on Unraid 

Version: v1.0.0beta-5
Build: c8be9221112136b4929d72ef2a3c96e856ab86c2
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: postgres
Default Group: Home
Recipe Scraper Version: 14.26.0
PostgreSQL Version: 14.6.1

**Comment by hay-kot** [comment]
@nkringle, thanks for the dudiligence on this issue, I know it's been around for some time! Is there any reason we couldn't run the SQL statement in the post to the import workflow? So after all the current steps are complete, we then make sure all the sequence counters are correct?

I'm not sure if there are any edge cases that might cause problems...

**Comment by nkringle** [comment]
I can't think of any reason that you couldn't run that SQL statement after
import to a postrgres DB. The only thing I can think of is if for some
reason the existing import process has a bug or something that would
manifest elsewhere (but I have no evidence to say either way).

--
*Nick Aceto*
