### ISSUE TITLE
[v1.0.0b] - Make quantity optional for shopping list

### ISSUE THREAD

**Issue by wcedmisten** [mealie-recipes/mealie#2068]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When adding unparsed ingredients from a recipe to a list through the "Add to shopping list" feature, the items appear with a default quantity `1`, because the quantity is already a part of the ingredient text. This makes the list a bit hard to read.

Ideally all the recipes would be already parsed for quantity, but since that step is currently optional this is the default behavior when adding items to a list.

Maybe a checkbox to hide the quantity would be a good short-term workaround for this?

![image](https://user-images.githubusercontent.com/4565200/215274727-9cc11daf-94d0-4e18-aa6a-a38b2942e69b.png)

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
I've addressed this in PR #2021. Once that's merged, if the quantity is "1" and the item does not have "use foods" enabled, the quantity will be hidden
