### ISSUE TITLE
[v1.0.0b] - iOS Shortcut stopped working

### ISSUE THREAD

**Issue by zippyy** [mealie-recipes/mealie#2092]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

none of the ios shortcuts seem to be working. even with an api token still cant seem to get any of them setup to work like they did with previous versions.

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Which version of Mealie are you using? The PWA (i.e. the app icon) has had a lot of issues, but is (_finally_) fixed in nightly

**Comment by zippyy** [comment]
The most recent 1.x version

**Comment by michael-genson** [comment]
Check out https://github.com/hay-kot/mealie/issues/1077 which is nightly (not in a major release yet). This will probably solve the issue

**Comment by zippyy** [comment]
I pulled the omni-nightly tagged release and still cant get the shortcut to work. 

Version

v1.0.0beta-5

Build

"20160346d78de2ccb481447099e9ae1a8632d028"

**Comment by zippyy** [comment]
could we get an update documentation for the guide on the ios shortcut? I have tried everything and am running the most current nightly as of today with no luck on either the original shortcut or the v2 shortcut.

**Comment by hay-kot** [comment]
> https://nightly.mealie.io/documentation/community-guide/ios/

Was submitted by a community member, I don't even have an IPhone to know if it works. Someone from the community would have to resolve the issues and update the guide.

**Comment by zippyy** [comment]
I can not seem to figure out how to pass the API token to it. 

it seems when the api was made more secure, these shortcuts broke. 

I checked the documentation for the api and even in a browser i get  "Not authenticated" in the json output

**Comment by michael-genson** [comment]
> I checked the documentation for the api and even in a browser i get "Not authenticated" in the json output

I don't have an iPhone so I have no idea what options you have, but this is the header you need to supply when authenticating with Mealie:
```
key:
Authorization

value:
Bearer ${YourToken}
```

(where your token is generated in Mealie settings)

Also be sure to check your API documentation at `https://YOUR-URL.com/docs` and make sure you're using the right endpoint. Hope this helps!

**Comment by zippyy** [comment]
thanks. thats exactly what I needed. neither of the existing shortcuts in that guide above would work however I was able to create a new one with the info you gave me on the token. I will write up a guide and submit a PR 

Edit: here is a link to the shortcut with setup questions until I can write up a full guide

https://www.icloud.com/shortcuts/cc568d1615bc4f998789f85d1ef74846

**Comment by quoque12** [comment]
Hi @zippyy, thanks for creating and sharing the new shortcut. I create a new token, but I'm still getting the "Not authenticated" message. I'm running the omni docker, latest version. Is the shortcut working for you?

**Comment by zippyy** [comment]
When your setting up the shortcut. The part where the key goes. Do you have Bearer api key here or does your just have the api key in that field? It has to have Bearer in front of it

Sorry I am on mobile right now, also you can test it be using a rest application like soap UI to make sure your key and everything is right before setting up the shortcut 

I plan on writing a full guide and posting it on my blog and here on the GitHub, I just finished moving and have to get settled first. I will try to get a rough draft this weekend

**Comment by quoque12** [comment]
Yes! That did the trick. Thank you a lot. I didn't realize the bearer part had to stay there. Sry

**Comment by zippyy** [comment]
Awesome! And sorry I should have been clearer in the setup questions but I set that up later at night before I went to bed. I will write a guide for others once I get settled from moving

**Comment by SawkeeReemo** [comment]
Did anyone ever get this to work including the Gemini API key? Unfortunately the guide on mealie.io was never updated so I just learned all this the hard way. 😅

**Comment by zippyy** [comment]
I can share my shortcuts.
