### ISSUE TITLE
White screen when installing as web application (Android with Chrome/Firefox)

### ISSUE THREAD

**Issue by 13hannes11** [mealie-recipes/mealie#2098]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When I use the Install option in Firefox or Chrome I get an icon on the home screen to have web apps as "standalone" apps.

When doing this with mealie it upon opening briefly flashes the login screen and then only shows a blank screen. This seems to be a strange client side issue.

https://user-images.githubusercontent.com/9381167/217026741-2b7411aa-6440-4195-9bf4-537322081503.mp4

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Which version of Mealie are you using? 1.0.0b5, or nightly?

**Comment by 13hannes11** [comment]
> Which version of Mealie are you using? 1.0.0b5, or nightly?

I am using beta5

**Comment by michael-genson** [comment]
> > Which version of Mealie are you using? 1.0.0b5, or nightly?
> 
> I am using beta5

Ah okay. This was recently fixed in nightly. If it's a must have you can upgrade to nightly (newest features, occasionally unstable) or wait for the next release.

If/when you do upgrade, be sure to delete the PWA, clear all app data for Mealie, then try installing again. That should work!

**Comment by 13hannes11** [comment]
That's great! I consider the issue closed then.
