### ISSUE TITLE
How to reset admin password?

### ISSUE THREAD

**Issue by TheGreatMisconception** [mealie-recipes/mealie#2115]
Hello everyone,

let's get straight to the point. I need to reset the password of the only admin account. I have full access to the host system. 
Newer Versions seem to have a scripts folder, but mine doesn't. I've also searched the documentation but none of the steps describes the situation to reset the only admin accounts password. How do i reset it?

System Details:
OS: Linux/Raspbian
Docker: version 18.09.7, build 2d0083d
Mealie: v.0.5.6 -> hkotel/mealie:latest

Thanks in advance

Tom

**Comment by hay-kot** [comment]
There is no official way to do that at the release you're on 

See here for a work around https://github.com/hay-kot/mealie/discussions/1039

**Comment by Trevo525** [comment]
I found this issue when I was searching for myself. So, I am going to link the official doc for future searchers.
https://docs.mealie.io/documentation/getting-started/faq/#how-can-i-change-my-password
