### ISSUE TITLE
[v1.0.0b] [Task] - Remove Remaining Non-Paginated Recipe Requests

### ISSUE THREAD

**Issue by hay-kot** [mealie-recipes/mealie#2118]
### What is the problem this task addresses?

Issue outlined in 

- #2076

### Proposed/Possible Solution(s)?

Two areas still need to be updated

1. Data Management

https://github.com/hay-kot/mealie/blob/feat/server-side-search/frontend/pages/group/data/recipes.vue#L181

2. Meal Planner

https://github.com/hay-kot/mealie/blob/feat/server-side-search/frontend/pages/group/mealplan/planner.vue#L306

**Comment by fleshgolem** [comment]
So the second part was simple enough, but the first really isnt and poses some further questions
We could rewrite the data-table to use server-side pagination, which thankfully is simple enough in vuetify, and implement that similarly to the RecipeCardSection. This is pretty straightforward for the most part, however ordering by categories/tags/tools isnt really possible with the api as it is right now. You could scrap that, but that probably limits the usefulness of this page
So to do this properly we would need to add ordering by these parameters to the api, but to me it isnt even clear how exactly that should work in the first place, it kind of automagically does in the data-table, but i am not sure what it does exactly
Additionally, if we are changing this page that much to begin with, wouldnt it be useful to maybe add a search field here as well, to be able to really dig for certain recipes?
Overall I think this warrants a standalone issue that is fleshed out a bit more. I also dont think this necessarily needs to be a blocker for v1. This is really not a page you should need to visit very often and in the cases where you do a lot of work here and have a huge collection, it might just be ok for now to maybe wait a few seconds

**Comment by hay-kot** [comment]
> This is pretty straightforward for the most part, however ordering by categories/tags/tools isnt really possible with the api as it is right now. You could scrap that, but that probably limits the usefulness of this page
>
> So to do this properly we would need to add ordering by these parameters to the api, but to me it isnt even clear how exactly that should work in the first place, it kind of automagically does in the data-table, but i am not sure what it does exactly

I don't think sorting by category/tag/tool is _really_ necessary at all. What I really want when I do that is to see Recipes that don't have those defined at all. So if we had filters for "Show recipes with null Categories" etc... that would fulfill the require IMO. 

> Additionally, if we are changing this page that much to begin with, wouldn't it be useful to maybe add a search field here as well, to be able to really dig for certain recipes?

That's a super valid point. In reality we could reuse the search logic and components via a composable or something to get most of the behavior we're looking for without _too_ much rework.

> Overall I think this warrants a standalone issue that is fleshed out a bit more. I also dont think this necessarily needs to be a blocker for v1. This is really not a page you should need to visit very often and in the cases where you do a lot of work here and have a huge collection, it might just be ok for now to maybe wait a few seconds

I can agree with that 👍
