### ISSUE TITLE
Scrap Issue

### ISSUE THREAD

**Issue by chriswiso** [mealie-recipes/mealie#2135]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I have checked for existing issues that have been resolved in v1-beta

### What is the issue you are experiencing?

I tried scraping the URL below but got an error.  JSON was rendered. 

https://www.thekitchn.com/creamy-wild-mushroom-instant-pot-pasta-recipe-23099339

### Deployment

Unraid

### Mealie Version

0.5.6

**Comment by jlssmt** [comment]
it's working on latest mealie version. can be closed.
