### ISSUE TITLE
[v1.0.0b] - 500 internal server error when numerator or denominator in a shopping list quantity is > 9

### ISSUE THREAD

**Issue by kbielefe** [mealie-recipes/mealie#2154]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Numerators and denominators in shopping list quantities may have values up to 32, which causes a `KeyError` [here](https://github.com/hay-kot/mealie/blob/df8459a95c35df4a66b9aa9cafd69b9ef1271a03/mealie/schema/group/group_shopping_list.py#L129) since `SUPERSCRIPT` and `SUBSCRIPT` only support 0-9. That `KeyError` results in a 500 internal server error which prevents the shopping list from displaying.

### Deployment

Docker (Linux)

### Deployment Details

Docker-compose running the `api-nightly` and `frontend-nightly` containers from docker hub.

**Comment by michael-genson** [comment]
🤦 yup that's a bug on me, thanks!
