### ISSUE TITLE
[v1.0.0b] - Recipes not public

### ISSUE THREAD

**Issue by Systemedic** [mealie-recipes/mealie#2161]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I would show the recipes public so you can view them without the need of login in. The recipes and the group are set to public. However I still have to login before someone can view the recipes.

### Deployment

Docker (Synology)

### Deployment Details

version: "3.7"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-5
    container_name: mealie-frontend
    restart: always
    ports:
      - 9925:3000
    environment:
      - API_URL=http://mealie-api:9000
    volumes:
      - /volume1/docker/mealie:/app/data/
  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-5
    container_name: mealie-api
    volumes:
      - /volume1/docker/mealie:/app/data/
    environment:
      - ALLOW_SIGNUP=true
      - PUID=1026
      - PGID=100
      - TZ=Europe/Amsterdam
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=http://192.168.178.18
    restart: always

volumes:
  mealie-data:
    driver: local

**Comment by Kuchenpirat** [comment]
Hey, 
so there is already an issue open adressing your issue. 

#1326 should solve it once it has been completed.
