### ISSUE TITLE
[v1.0.0b] [Task] Prompt User For Action on Login (Reset Password)

### ISSUE THREAD

**Issue by hay-kot** [mealie-recipes/mealie#2166]
### What is the problem this task addresses?

Currently there is no way to force a user to do anything on initial login. Things like forced password resets are not a thing. 

### Proposed/Possible Solution(s)?

The Mealie API should provide a framework to alert the frontend that a User must complete some "action" this should be generic enough to be reused for different things in the future but currently they would be for at least:

1. Password Resets / Force New Password
2. Initial Guided Setup for Mealie #1164 

I see this being implemented in 2 phases

1. API Setup, set the initial API that checks a User for required actions
2. Frontend redirect logic based on backend, this would likely be done through some kind of enum "actions". For example user get's payload with action `password-reset-required` which redirects the user to the reset password route. 

I have not looked much into how other projects implement this, so it may be worth taking some time to investigate how this kind of thing is normally done.

**Comment by cmintey** [comment]
I'm curious to know what other "actions" you think would be needed other than your two proposed use cases.

Just spit-balling, but this is how I see we could do those two things without an "actions" enum.

## Password resets / force new password

Have a `passwordLastChanged` field in the user table, this field should be nullable. If the field is null, then the user will be required to change their password. 

On user creation, the admin would set a temporary password for the user, but the `passwordLastChanged` would be null. The user then logs in with that temp password, and is required to change it after successful authentication. Then the `passwordLastChanged` is updated to the date/time.

To perform force password resets, we could have it be an option to change password after 30/60/90 days, just by checking this field. Or manually force a password reset by having a button in the admin panel which sets the field to null.

## Initial Guided Setup for Mealie

For the wizard, this could be initiated by checking the number of users when the admin first goes to Mealie. We could remove the default administrator so the total number of users would be 0, then this would be our condition to show the wizard. 

This would also fix an (albeit probably rare) issue where if the administrator accidentally deletes him/herself (and everyone else), then the wizard would start again the next time they try to access Mealie so they wouldn't be locked out.
