### ISSUE TITLE
[v1.0.0b] - Webhooks are not fired ('Error in scheduled task func='post_group_webhooks')

### ISSUE THREAD

**Issue by ghuser238490** [mealie-recipes/mealie#2169]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

The webhooks are not working, the 'Test' button does nothing as well.
At the specified time of the day the logs say:
`Error in scheduled task func='post_group_webhooks': exception=''NoneType' object has no attribute 'scalar''`

The recipe in the meal planner contains:
```
  "extras": {
    "test": "value"
  },
```
I'm not sure if I missed something. Any ideas?
Thanks a lot!

### Deployment

Docker (Linux)

### Deployment Details

Version
v1.0.0beta-5
Build
9d35b0923a05bcc2b99521ccfef3e5db6f4c7622

**Comment by fleshgolem** [comment]
This might be an issue caused by my sqlalchemy migration from the looks of that error. Unfortunately I am really not sure how to look into that, because - quite frankly - I have never used webhooks before and I am not sure I quite understand how you set them. Are there any simple steps to go to recreate this failing scenario?

**Comment by ghuser238490** [comment]
Hi @fleshgolem! You could simply get a webhook URL for testing purpose from an online service, such as https://webhook.site and use it with mealie.

When calling the webhook URL, for example:
`curl --request POST --header "Content-Type: application/json" --data '{"test":"value"}' https://demo.server/abcde...` 
you'll see the response on their website.

I tried with different webhooks and servers and still got the same error message in mealie.
Thanks for looking into that!
