### ISSUE TITLE
[v1.0.0b] - Annoyance in adding Foods/Amount to recipes, ingredients disappear at first

### ISSUE THREAD

**Issue by fleshgolem** [mealie-recipes/mealie#2183]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

So there are two ways to use the parser and add foods/amounts to ingredients where that feature was previously disabled and both are quite annoying to deal with

The first one:
* Go to recipe
* Hit settings
* Toggle "Disable Ingredient Amounts" off
* Scroll to the bottom of the ingredient list and hit "Parse"
* Get asked to save, hit "Ok" (This is the part that actually doesnt work, as you will see later)
* Use the Parser, do your stuff hit save
* Now a lot of the times (but not all of them) the ingredients table will only show the extras
![image](https://user-images.githubusercontent.com/657606/221424970-c3fec957-ddcc-49d1-a320-e782debdc1a7.png)
* Hit edit again, hit settings again, enable Ingredient Amounts again

Sometimes this does work, I have not been able to discern when it does and doesnt
Alternatively you can just save manually after enabling amounts for the first time, but that will get you out of the edit view and thats really not a great experience as well

### Deployment

Docker (Linux)

**Comment by RealFoxie** [comment]
I just want to confirm I have the exact same problems you describe. I also do the fix of first saving it myself, and then pressing edit again as the message box to save doesn't seem to do the job.
