### ISSUE TITLE
[v1.0.0b] - LDAP server requiring STARTTLS causes error

### ISSUE THREAD

**Issue by Caligatio** [mealie-recipes/mealie#2185]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

My LDAP server requires STARTTLS which causes Mealie to throw an exception when trying to authenticate any user:

`ldap.CONFIDENTIALITY_REQUIRED: {'msgtype': 97, 'msgid': 1, 'result': 13, 'desc': 'Confidentiality required', 'ctrls': [], 'info': 'TLS confidentiality required'}`

Quickly looking through the code, I don't see any reference to a `.start_tls_s()` call by the LDAP client.

### Deployment

Docker (Linux)

**Comment by cmintey** [comment]
Hey there. Unfortunately, ~~I don't have STARTTLS enabled with my LDAP setup so I cannot test this fix~~. Are you able to do some testing locally? I have a working branch if you'd be able to clone and try it out: https://github.com/cmintey/mealie/tree/fix/ldap-starttls

I've added a new `LDAP_ENABLE_STARTTLS` environment variable that you can set to True and test

**Comment by Caligatio** [comment]
Sorry for the delay @cmintey on testing this.

I can confirm that your branch makes STARTTLS work, thank you!
