### ISSUE TITLE
[v1.0.0b] - Webhook Test Button Does Nothing

### ISSUE THREAD

**Issue by hay-kot** [mealie-recipes/mealie#2186]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Test Button doesn't do anything

![image](https://user-images.githubusercontent.com/64056131/221432172-be5025c2-0e36-4bad-af5d-2b8439b0f8c7.png)

### Deployment

Docker (Linux), Docker (Windows), Docker (Synology), Unraid

**Comment by fleshgolem** [comment]
Additional info for anyone looking into this:
1) The button is not hooked up to any functionality
2) As of right now there is also no API that the frontend could even call to begin with to trigger a single specific webhook
