### ISSUE TITLE
[v1.0.0b] [Task] - Audit Experimental Features

### ISSUE THREAD

**Issue by hay-kot** [mealie-recipes/mealie#2193]
### What is the problem this task addresses?

Several places around the application have experimental warning banners but the current state is untracked. 

<img width="891" alt="CleanShot 2023-02-26 at 16 05 40@2x" src="https://user-images.githubusercontent.com/64056131/221449685-25ab94ef-05f8-4445-8637-310d0c2accde.png">

### Proposed/Possible Solution(s)?

- Identify all places with experimental flags
- Audit status and either remove experimental status if still experimental create issue to track status.

**Comment by michael-genson** [comment]
After https://github.com/mealie-recipes/mealie/issues/2186 is resolved we can remove the banner from the webhook page
