### ISSUE TITLE
[v1.0.0b] - Empty Recipe Section Results in Infinite Request Loop

### ISSUE THREAD

**Issue by hay-kot** [mealie-recipes/mealie#2195]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When navigating to a Category or Tool page with no recipes, you enter a infinite request loop, I think this will happen in any instance where the results of the query is 0

### Deployment

Docker (Linux), Docker (Windows), Docker (Synology), Unraid, Other

**Comment by michael-genson** [comment]
Seems like this happens with cookbooks too, even when there are recipes. Thought I broke something with the public recipe browser, but it happens in nightly, too
