### ISSUE TITLE
[v1.0.0b] - Meal Planner (Note Only meals) hyperlink to 404

### ISSUE THREAD

**Issue by coffee-mage** [mealie-recipes/mealie#2207]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Note only meal planning behavior has changed in the new meal planner rework.

**Old behaviour:**
- Create a meal note, with a title and no url in note field.  Clicking on the meal card (in planner) would not do anything.
- Create a meal note, with a title and a url in note field.   Clicking on the meal card (in planner) would link you to the external website.

**New behaviour:**
- Create a meal note with title and no url in note field.    Clicking on the meal card (in planner) would take you to a nonexistant recipe in mealie, using the meal title  (E.g.  http://mealie:9925/recipe/tasty%20soup.)
- Create a meal note with title and url in note field.    Clicking on the meal card (in planner) would take you to a nonexistant recipe in mealie, using the meal title  (E.g.  http://mealie:9925/recipe/tasty%20soup.).   Ideally it would link to external website.

### Deployment

Unraid

### Deployment Details

omni-nightly

**Comment by Aeklipse** [comment]
The edit button of a note also redirects to a non existing recipe. Editing the note note does not seem to be possible.

**Comment by michael-genson** [comment]
Closing in favor of https://github.com/mealie-recipes/mealie/issues/2350
