### ISSUE TITLE
[v1.0.0b] - PUT /recipes/<slug>  500 error inserting ingredients, causes db issues

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [mealie-recipes/mealie#2221]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

PATCHing a recipe with the following data:
```json
{
   "name":"\ud83c\udf83Pumpkin Cheesecake Chimichangas",
   "description":null,
   "recipeIngredient":[
      {
         "originalText":"\ud83c\udf83Ingredients:"
      },
      {
         "originalText":"3 @CutDaCarb Flatbreads"
      },
      {
         "originalText":"8 oz cream cheese, softened"
      },
      {
         "originalText":"1 cup pumkin puree"
      },
      {
         "originalText":"1/2 cup zero calorie powdered sweetener"
      },
      {
         "originalText":"1 tbsp pumpkin spice"
      },
      {
         "originalText":"Splash of vanilla extract"
      },
      {
         "originalText":"2 tbsp butter, melted"
      },
      {
         "originalText":"1/4 cup granular sweetener"
      },
      {
         "originalText":"1 tbsp pumpkin spice"
      },
      {
         "originalText":"Sugar free Caramel for drizzle"
      },
      {
         "originalText":"\ud83e\udde1"
      }
   ],
   "recipeInstructions":[
      {
         "text":"Directions:"
      },
      {
         "text":"1. In a large mixing bowl combine cream cheese, pumpkin, powdered sweetener, pumpkin spice and vanilla. Whip with hand mixer until light and fluffy."
      },
      {
         "text":"2. Working with one flatbread at a time, cut the bread in half widthwise and use a large scoop to place filling into the center. Fold in the outside edges and roll tightly. Repeat with remaining flatbreads."
      },
      {
         "text":"3. Brush with butter and air fry at 325 for 8-10 minutes watching closely as browning occurs quickly."
      },
      {
         "text":"4. Mix granular sweetener and pumpkin spice in a bowl. Set aside."
      },
      {
         "text":"5. Once crisped brush the chimichangas with butter again and sprinkle on the sweetener and spice mixture."
      },
      {
         "text":"6. Serve immediately with a drizzle of SF caramel."
      },
      {
         "text":"ENJOY!!!."
      }
   ],
   "orgUrl":null,
   "recipeYield":null,
   "prepTime":null,
   "cookTime":null,
   "recipeCategory":[
      
   ]
}
```

Results in the error:

```
Request failed: 500 Server Error: Internal Server Error for url: https://mealie.nas.lan/api/recipes/pumpkin-cheesecake-chimichangas-1
{"detail":{"message":"Unknown Error","error":true,"exception":"RecipeInstruction.__init__() missing 1 required positional argument: 'ingredient_references'"}}
```

Traceback in docker logs:

```
ERROR: 08-Mar-23 13:42:21 	Unknown Error on recipe controller action
ERROR: 08-Mar-23 13:42:21 	RecipeInstruction.__init__() missing 1 required positional argument: 'ingredient_references'
Traceback (most recent call last):
  File "/app/./mealie/routes/recipe/recipe_crud_routes.py", line 326, in patch_one
    recipe = self.service.patch_one(slug, data)
  File "/app/./mealie/services/recipe/recipe_service.py", line 215, in patch_one
    new_data = self.repos.recipes.by_group(self.group.id).patch(recipe.slug, patch_data.dict(exclude_unset=True))
  File "/app/./mealie/repos/repository_generic.py", line 193, in patch
    return self.update(match_value, entry_as_dict)
  File "/app/./mealie/repos/repository_generic.py", line 180, in update
    entry.update(session=self.session, **new_data)  # type: ignore
  File "/app/./mealie/db/models/_model_base.py", line 23, in update
    self.__init__(*args, **kwarg)
  File "<string>", line 6, in __init__
  File "/app/./mealie/db/models/recipe/api_extras.py", line 18, in wrapper
    return func(*args, extras=extras, **kwargs)
  File "/app/./mealie/db/models/_model_utils/auto_init.py", line 188, in wrapper
    return init(self, *args, **kwargs)
  File "/app/./mealie/db/models/recipe/recipe.py", line 143, in __init__
    self.recipe_instructions = [RecipeInstruction(**step, session=session) for step in recipe_instructions]
  File "/app/./mealie/db/models/recipe/recipe.py", line 143, in <listcomp>
    self.recipe_instructions = [RecipeInstruction(**step, session=session) for step in recipe_instructions]
  File "<string>", line 4, in __init__
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state.py", line 481, in _initialize_instance
    with util.safe_reraise():
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/app/./mealie/db/models/_model_utils/auto_init.py", line 188, in wrapper
    return init(self, *args, **kwargs)
TypeError: RecipeInstruction.__init__() missing 1 required positional argument: 'ingredient_references'
```

This also appears to mess up the GET /recipes endpoint, since it now returns a 500 error, with this in the logs:

```
pydantic.error_wrappers.ValidationError: 12 validation errors for RecipePagination
items -> 2 -> recipeIngredient -> 0 -> referenceId
  none is not an allowed value (type=type_error.none.not_allowed)
items -> 2 -> recipeIngredient -> 1 -> referenceId
  none is not an allowed value (type=type_error.none.not_allowed)
items -> 2 -> recipeIngredient -> 2 -> referenceId
  none is not an allowed value (type=type_error.none.not_allowed)
items -> 2 -> recipeIngredient -> 3 -> referenceId
  none is not an allowed value (type=type_error.none.not_allowed)
items -> 2 -> recipeIngredient -> 4 -> referenceId
  none is not an allowed value (type=type_error.none.not_allowed)
items -> 2 -> recipeIngredient -> 5 -> referenceId
  none is not an allowed value (type=type_error.none.not_allowed)
items -> 2 -> recipeIngredient -> 6 -> referenceId
  none is not an allowed value (type=type_error.none.not_allowed)
items -> 2 -> recipeIngredient -> 7 -> referenceId
  none is not an allowed value (type=type_error.none.not_allowed)
items -> 2 -> recipeIngredient -> 8 -> referenceId
  none is not an allowed value (type=type_error.none.not_allowed)
items -> 2 -> recipeIngredient -> 9 -> referenceId
  none is not an allowed value (type=type_error.none.not_allowed)
items -> 2 -> recipeIngredient -> 10 -> referenceId
  none is not an allowed value (type=type_error.none.not_allowed)
items -> 2 -> recipeIngredient -> 11 -> referenceId
  none is not an allowed value (type=type_error.none.not_allowed)
```

Apparently `referenceID` is a required field for ingredient items but it's completely unclear what it should be.

### Deployment

Docker (Linux)

### Deployment Details

docker-compose v1.0.0beta-5

**Comment by ColonelThirtyTwo** [comment]
Related: what is the best way to specify an ingredient as a simple text line, like what you would enter into the UI? The endpoint documentation says the ingredient should be specified as an object with quantity and unit fields, which is inconvenient when all I have is the text.

**Comment by fleshgolem** [comment]
> Results in the error:

This does not seem to happen, when you add `"ingredientReferences": []` to all of your recipeInstructions entries. I dont quite understand why this happens either and agree that it shouldnt be necessary according to documentation of the endpoint

> Apparently referenceID is a required field for ingredient items but it's completely unclear what it should be.

This should be autofilled with a random UUID4. The fact that you can arrive at a corrupted state like you have now is definitely bad, but I am quite unsure right now how that even happens. Does patching the recipes with workaround from the previous point maybe help in repairing them?

> Related: what is the best way to specify an ingredient as a simple text line, like what you would enter into the UI? The endpoint documentation says the ingredient should be specified as an object with quantity and unit fields, which is inconvenient when all I have is the text.

The frontend uses the field `note` for all recipes where foods/amounts have been disabled, so you should go with that

**Comment by hay-kot** [comment]
Currently the `PATCH` behavior only applies to top level keys on the recipes. Nested fields need to be fully defined based on the API requirements. Supporting patch methods for nested fields as well will likely be a nightmare. 

> This should be autofilled with a random UUID4.

Pretty sure we're generating these on the Frontend so we can do linking without saving to the database, we can probably set Pydantic to create one if one doesn't exist.

**Comment by ColonelThirtyTwo** [comment]
@hay-kot Requiring subfields to be complete for PATCH seems very inconvenient when you can't fill out a recipe via POST - POST seems to take only the name, then you have to PATCH later with the data. PUT on an existing slug results in an already exists message, but I don't know how I'm supposed to PUT without knowing what the slug should be.

**Comment by michael-genson** [comment]
> I don't know how I'm supposed to PUT without knowing what the slug should be

When you create the recipe, the response is the slug. We could probably use some clearer documentation on this (or just return the new recipe in full)

**Comment by hay-kot** [comment]
> Requiring subfields to be complete for PATCH seems very inconvenient when you can't fill out a recipe via POST - POST seems to take only the name

I don't disagree, but like I said, it's going to be a nightmare to fix that so it's unlikely to happen.

> but I don't know how I'm supposed to PUT without knowing what the slug should be.

You don't, you first create the resources with the POST request, then you update it via PUT. That's how the UI does it. You can look in the network tab in your browser to see exactly what's happening if you need a better example.

---

Always happy to accept PRs to improve the API ergonomics.

**Comment by ColonelThirtyTwo** [comment]
@michael-genson @hay-kot But as I said in my comment, you can't PUT the recipe if it already exists:

```
Request failed: 400 Client Error: Bad Request for url: https://mealie.nas.lan/api/recipes/pumpkin-cheesecake-chimichangas-3
{"detail":{"message":"Recipe already exists","error":true,"exception":null}}
```

Using the same body as in the OP

**Comment by hay-kot** [comment]
> But as I said in my comment, you can't PUT the recipe if it already exists:

This is literally what the UI editor does, so you absolutely can.

> Recipe already exists

You will get this error if you try to change a recipes name to an existing name, which will cause the slug to be re-computed and if there's a collision in the database you'll get the error. 

I would check your payload and make sure the name you're passing to Mealie doesn't conflict with an existing recipe.

**Comment by ColonelThirtyTwo** [comment]
Well, the UI is showing no recipes in my system, so I'm gonna have to reset the database to test this further...

**Comment by jecorn** [comment]
@hay-kot @michael-genson I can confirm the same error as above from ColonelThirtyTwo. I'm trying to programmatically (via python) populate the recipe database with thousands of json recipes. 

Starting from an empty database, I can create a recipe using POST and the recipe's name (e.g. "Foo bar") then get the slug from the response (e.g. "foo-bar"). 

Side-note: In an earlier discussion with @michael-genson I found a bug in the POST response string. The string is currently returned **including** quotes. `"foo-bar"` instead of `foo-bar` and must be sliced to yield a valid slug. Happens both programmatically via python and using curl through the mealie API docs web interface.

I then PUT the rest of the recipe JSON to /api/recipes/<slug> and get the Request failure `{"detail":{"message":"Recipe already exists","error":true,"exception":null}}`. It does not matter whether the JSON I upload contains a slug, a name, or neither. The error occurs even when PUTing a JSON that contains only the description. Again, happens whether I do this programmatically or via the web API (curl).

**Comment by hay-kot** [comment]
@jecorn

Can you provide a small reproduction via a python script? (or some other language)

If we have a reproducible example it will be much easier to help.

**Comment by jecorn** [comment]
Absolutely. The script is attached here with .txt extension (since GitHub doesn't allow .py extension attachments in comments). The toy entries here, as well as all other real names/schema that I've tried either pythonic or submitted ("Try it Out") via the API have given the same result when I try to use PUT with recipe data. It would be excellent if I'm just doing something wrong. 

[test.txt](https://github.com/hay-kot/mealie/files/11015527/test.txt)

```python
#!/usr/bin/env python
import requests
import json

def authentication(mail, password, mealie_url):
  headers = {
    'accept': 'application/json',
    'Content-Type': 'application/x-www-form-urlencoded',
  }
  data = {
    'grant_type': '',
    'username': mail,
    'password': password,
    'scope': '',
    'client_id': '',
    'client_secret': ''
  }
  auth = requests.post(mealie_url + "/api/auth/token", headers=headers, data=data)
  token = re.sub(r'.*token":"(.*)",.*', r'\1', auth.text)
  return token

mail="changeme@email.com"
password="MyPassword"
mealie_url="http://localhost:9926"
token = authentication(mail, password, mealie_url)

headers = {
  'Authorization': "Bearer " + token,
  'accept': 'application/json',
  'Content-Type': 'application/json'
}
# CREATE empty recipe
response = requests.post(mealie_url + "/api/recipes", headers=headers, json={"name": "A Delicious Recipe"})
slug = response.text
print(slug)
slug = slug[1:-1] # need to do this, otherwise the quotes in the string break the slug (not found response in later PUT)
print(slug)

recipe = '{"description": "This is a description of my recipe."}'
data = json.loads(recipe)

# REPLACE empty recipe with recipe from json
response = requests.put(mealie_url + "/api/recipes/"+slug, headers=headers, json=data)
print(response, response.text)
```

**Comment by hay-kot** [comment]
@jecorn - 2 things

## 1 

instead of this

```python
slug = response.text
print(slug)
slug = slug[1:-1] # need to do this, otherwise the quotes in the string break the slug (not found response in later PUT)
print(slug)
```

Just treat is as json

```python
slug = json.loads(response.text)
```

## 2

`PUT` requests require you to update the entire record, so you must specify all values on the recipe. You're looking for `PATCH`

```python
response = requests.patch(mealie_url + "/api/recipes/"+slug, headers=headers, json=data)
```

This script works

```python
#!/usr/bin/env python
import json
import re

import requests


def authentication(mail, password, mealie_url):
    headers = {
        "accept": "application/json",
        "Content-Type": "application/x-www-form-urlencoded",
    }
    data = {"grant_type": "", "username": mail, "password": password, "scope": "", "client_id": "", "client_secret": ""}
    auth = requests.post(mealie_url + "/api/auth/token", headers=headers, data=data)
    token = re.sub(r'.*token":"(.*)",.*', r"\1", auth.text)
    return token


mail = "changeme@email.com"
password = "demo"
mealie_url = "https://demo.mealie.io"
token = authentication(mail, password, mealie_url)

headers = {"Authorization": "Bearer " + token, "accept": "application/json", "Content-Type": "application/json"}
# CREATE empty recipe
response = requests.post(mealie_url + "/api/recipes", headers=headers, json={"name": "A Delicious Recipe"})
slug = json.loads(response.text)

recipe = '{"description": "This is a description of my recipe."}'
data = json.loads(recipe)

# REPLACE empty recipe with recipe from json
response = requests.patch(mealie_url + "/api/recipes/" + slug, headers=headers, json=data)
print(response, response.text)
```

**Comment by jecorn** [comment]
Thank you very much! I somehow got confused with the impression that PUT was the method that allowed putting in additional recipe info and that PATCH was instead patching an already full record to modify values that had already been added.

With PATCH and a real recipe that contains recipe instructions, I'm now getting the error mentioned earlier in this thread `<Response [500]> {"detail":{"message":"Unknown Error","error":true,"exception":"RecipeInstruction.__init__() missing 1 required positional argument: 'ingredient_references'"}}`.

But I'm a little unclear about the best way for me to solve this without ending up in a broken state. Is it safe in the long term for me to generate my own UUID4s and add them into `recipeInstructions`?  `"recipeInstructions": [ {"id": "<UUID4>", "text":"my text"}]`? Or is there a way that I'm not seeing to get mealie to generate them?

On a related note, I see there's also a field in `recipeIngredient` called `referenceId`. For long-term safety, can I pre-generate my own UUID4 referenceId for each recipeIngredient, or does mealie generate them?

I'm not sure what these IDs are being used for in the background, so I'm just trying to educate myself before I go full-bore on thousands of recipes each with several instructions and ingredients.

**Comment by michael-genson** [comment]
Ingredient references are for linking ingredients to steps (e.g. "eggs" can be linked to "step 2"). Unless you're working with linking ingredients to recipes, you can just supply an empty list. This seems like a bug though, it should default to an empty list if you don't supply it.

The `referenceId` field on ingredients is a utility for frontend rendering, it doesn't get saved in the database, so you can ignore it.

You shouldn't need to generate instruction ids either, but if you're modifying or replacing them you should pass the id generated by Mealie (otherwise you'll create new ones)

**Comment by jondyer** [comment]
@jecorn I'm getting the exact same error with ` missing 1 required positional argument: 'ingredient_references'"}`. Would you mind sharing how you got around that one?

Edit: I got a response on Discord, looks like mealie requires json fields with subfields to have some/all of their subfields defined. Thanks anyways!
