### ISSUE TITLE
[v1.0.0b] - Your current version (nightly) does not match the latest release. 

### ISSUE THREAD

**Issue by modem7** [mealie-recipes/mealie#2224]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When running `hkotel/mealie:omni-nightly`, there is a message stating:

`Your current version (nightly) does not match the latest release. Considering updating to the latest version (v1.0.0beta-5).
`

Whilst this doesn't affect functionality, it's not strictly correct. 

It may be worthwhile extracting the version so that it reflects correctly (especially if a Docker image update didn't work/was missed etc).

Build: [1b26ca0cb3be21494ab94a04a9f48f2dd8878ce9](https://github.com/hay-kot/mealie/commit/1b26ca0cb3be21494ab94a04a9f48f2dd8878ce9)

![image](https://user-images.githubusercontent.com/4349962/223861054-3ce52e84-a21f-43bd-a896-8cb3afd4cdb7.png)

### Deployment

Docker (Linux)

### Deployment Details

```yaml
  mealie:
    image: hkotel/mealie:omni-nightly
    container_name: Mealie
```

**Comment by hay-kot** [comment]
You're running the nightly versions which is correctly set at build time.

I suppose the suggestion to upgrade isn't strictly correct, but this is only the case for nightly.

What would you expect it to say in this case where you're running the nightly versions but not the latest released version?

**Comment by modem7** [comment]
Heya!

Aye, you definitely make a good point!

Would it maybe be worthwhile checking against commits/sha on nightly, with a message of "your commit isn't the latest etc etc etc"?

Alternatively, as a simple solution..."If nightly > don't display update notification".

**Comment by hay-kot** [comment]
> Alternatively, as a simple solution..."If nightly > don't display update notification".

That's a pretty sound suggestion (and easy!). I (or someone) will get this implemented!
