### ISSUE TITLE
[v1.0.0b] - Recipe editor does not use unit abbreviations, if selected

### ISSUE THREAD

**Issue by Caligatio** [mealie-recipes/mealie#2227]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When using ingredient amounts, the recipe editor does not honor the user selection for using abbreviations for units. It instead always shows the full name.

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
Seems to work here

https://demo.mealie.io/recipe/test-recipe-abbrv-ingredients

Can you provide any more details or a reproducible example?

**Comment by Caligatio** [comment]
Sorry if I'm describing this poorly, see the attached screenshot.

![screenshot](https://user-images.githubusercontent.com/2017685/223928078-47e87c65-9c9d-4907-9ef0-d73cda948fe2.png)

EDIT: In case other people see this, the unit is  "test-unit" with an abbreviation of "tu". "tu" is correctly showed when viewing the recipe but my screenshot shows "test-unit" being used in the recipe editor.

**Comment by hay-kot** [comment]
>  In case other people see this, the unit is "test-unit" with an abbreviation of "tu". "tu" is correctly showed when viewing the recipe but my screenshot shows "test-unit" being used in the recipe editor.

That's intentional. My assumption was that you'd want to edit by the full name and not the abbreviation. Abbreviation is only for display purposes in view mode.

**Comment by Caligatio** [comment]
Ahh ok! I don't have a strong opinion on this either way but the inconsistency caught my eye.
