### ISSUE TITLE
[v1.0.0b] - LDAP_USER_FILTER is confusingly named

### ISSUE THREAD

**Issue by Caligatio** [mealie-recipes/mealie#2228]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I'll be upfront and say this is probably 60% user error and 40% bug.

Typically, things like `LDAP_USER_FILTER` is used to filter all available LDAP users down to those eligible to log into a particular service. Some software offers to do a simple `memberOf` check against a group or let's you specify the full LDAP filter string.

The [Mealie documentation ](https://github.com/hay-kot/mealie/blob/mealie-next/docs/docs/documentation/getting-started/installation/backend-config.md) says `LDAP_USER_FILTER` is "The LDAP search filter to find users" and then provides an example LDAP string that is clobbered by markdown syntax. The `LDAP_ADMIN_FILTER` behavior matches what I described above.

What I found, and is admittedly documented in the clobbered example, is that `LDAP_USER_FILTER` is actually not a filter but rather is used to find a particular user. This is how this caused me problems:

1. I initially created a new LDAP group and put my user as the sole member.
2. I set the `LDAP_USER_FILTER` to do essentially a membership check on that group.
3. Tried out Mealie and sold my wife on trying it
4. Put her user in the new group
5. I continued to use/log into Mealie without problem
6. When she finally tried logging in, she got a password incorrect message.

What I'm nearly certain is happening is that, due to my incorrect usage of `LDAP_USER_FILTER`, the filter was returning both of our users, my user was listed first, the [code actually just picks the first item returned by the LDAP filter](https://github.com/hay-kot/mealie/blob/mealie-next/mealie/core/security/security.py#L77-L90) (which happened to be my user), I was able to continue to log in, and she was not as her credentials were attempted against my user.

### Deployment

Docker (Linux)

**Comment by cmintey** [comment]
Your analysis is correct. In the documentation (looks fine [here](https://nightly.mealie.io/documentation/getting-started/installation/backend-config/)), shows a simple example of `(&(|({id_attribute}={input})({mail_attribute}={input}))(objectClass=person))` as the filter. What will happen is that this template will be transformed into `(&(|(uid=testusername)(mail=testusername))(objectClass=person))`, assuming the user entered `testusername` as their username. Then it will search in LDAP for both user id and email of `testusername` who is also a `objectClass=person`.

You can extend this to be whatever. In my case, I also do a `memberOf` check, so my total filter looks like `(&(|({id_attribute}={input})({mail_attribute}={input}))(objectClass=person)(memberOf=cn=mealie_user,ou=groups,dc=example,dc=com))`.

For reference, the inspiration for this was from how [authelia](https://www.authelia.com/integration/ldap/introduction/) does their LDAP setup.

I can see the confusion here, and can see three solutions:
1. Update the documentation to more explicitly call this out
2. Change the name of the `LDAP_USER_FILTER` to be more fitting
3. Keep `LDAP_USER_FILTER`, but change it's functionality to be more similar to `LDAP_ADMIN_FILTER` and implicitly implying the `&(|({id_attribute}={input})({mail_attribute}={input}))` part of the filter

**Comment by Caligatio** [comment]
I would personally vote for number 3 but I also hate breaking changes :) 

What if the documentation gets updated but an exception is also thrown if the LDAP search returns more than one item? I can't foresee any circumstance were that particular query should return >1 items.

**Comment by cmintey** [comment]
Here's what I've been playing with. I think we can do number 3, but without breaking changes.

To keep the existing functionality, if "id_attribute" or "mail_attribute" are present in the search filter, then we use it as is. However, if both of those are left out, i.e. your search filter is simply `(memberOf=<blah>)`, then the "id_attribute" and "mail_attribute" will be implied.

Going forward, I will also update the documentation to leave out the "id_attribute" and "mail_attribute" parts, so it will be implied by default.

I've also added in some logging so you know when multiple users are returned
