### ISSUE TITLE
[v1.0.0b] - Disallow duplicate ingredients

### ISSUE THREAD

**Issue by Caligatio** [mealie-recipes/mealie#2229]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

It's currently possible to add exact duplicate ingredients (which is a problem) and the duplicate ingredient also then breaks the combine food functionality (a separate bug but one that could be bypassed by disallowing duplicate ingredients).

See the below screenshot:
![duplicate_ingredients](https://user-images.githubusercontent.com/2017685/223931504-41fd2ffc-2fac-4b09-b09b-12d283cc762b.png)

I admittedly do not know how I got two "Jalapeño Peppers" in my database. I went to combine them to then discover I only get one of them listed in the dropdown. I then tried combining the one instance of the ingredient as the source with the same named ingredient as the target; literally nothing happened.

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
I can confirm I've seen this before, a long time ago (at least a year). I was never able to reproduce it though and haven't seen it since, so I'd just assumed it was fixed

**Comment by RealFoxie** [comment]
I have also had this happen, but also could never reproduce it. I could still combine it though with some fiddling.
However I think the combining also didn't work great in this instance and produced some bugs where some recipes missed the ingredient (as in the ingredient got deleted instead of combined).

I'm guessing this is a frontend bug, where the action to create a new food might be quicker than the check to choose an existing food if it exists.

**Comment by Caligatio** [comment]
I haven't spent much time trying to reproduce how ingredients get duplicated. However, it has now happened twice and I only have 8 recipes.

The one ingredient-related thing that always seems fiddly is importing a recipe + directly going to edit mode, enabling ingredient/unit editing, and then using ingredient parsing. Firefox unexpectedly prompts for a save as using the parser "leaves" the recipe. Both of my duplicated ingredients (jalapeno peppers and vinegar) may be in recipes without amounts; maybe they're getting created on import but then the parser screen isn't seeing the new ingredients and recreating?

**Comment by coffee-mage** [comment]
I can't speak to the bug, as I haven't seen it.  But I think there could be use cases were we would want duplicate ingredients?  I had a recipe today that had carrots two ways  (one big carrot to flavor the stew, one chopped carrot for eating in the stew).   I like keeping the two ingredients separate for ingredient/instruction linking.

**Comment by Caligatio** [comment]
@braddillon You already can have duplicate ingredients in a recipe without having duplicate ingredients in the ingredients database. I think we're talking about different things.

**Comment by coffee-mage** [comment]
Ahh apologies!   I misunderstood.

**Comment by Shaddowrunner414** [comment]
@Caligatio May I ask, how can I access the Data Management Tab in your screenshot?

**Comment by Caligatio** [comment]
Click on your avatar in the top right and then "Manage Data" in the bottom right. The URL is your.tld/group/data/foods

**Comment by Shaddowrunner414** [comment]
> Click on your avatar in the top right and then "Manage Data" in the bottom right. The URL is your.tld/group/data/foods

My hero, thank you! Searched everywhere, except the Avatar :D
