### ISSUE TITLE
[v1.0.0b] - omni docker compose - 404 error on register screen

### ISSUE THREAD

**Issue by jenny787** [mealie-recipes/mealie#2232]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Using the omni docker compose.  It works  and the site loads, however you can't register.  On the register screen it shows 404.  I tried it on Windows docker, and Ubuntu docker, and both give 404.  Allow signup is true (not changed).

### Deployment

Docker (Linux), Docker (Windows)

### Deployment Details

docker desktop on windows server 2022
docker desktop on ubuntu 22
both same result

**Comment by michael-genson** [comment]
This is a known issue:
https://github.com/hay-kot/mealie/issues/2222
