### ISSUE TITLE
[v1.0.0b] - Ingredient Parser Issues

### ISSUE THREAD

**Issue by coffee-mage** [mealie-recipes/mealie#2238]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

1) When parsing ingredients, the delete button doesn't seem to do anything.

2) What typing in the combo box (e.g. units), you can't tab away when you get down to one item left in the combo box.
example: I type cup  (there is only one hit in the combo box), I have to either select it with the mouse, or hit arrow down, then tab away.

3) When creating a new ingredient in the parser, if you hit the green button (to create), everything works as expected.
If you type an ingredient, e.g. banana.  Then hit enter to create.   The combo box does not select the item you just created.  It leaves a large drop down.   The best workaround I have right now is after typing the ingredient and hitting enter to create. 
 Delete the last character,  it will refresh the combo box and filter to the item you want,  then hit down to select, then tab away.
Ideally the enter key would automatically select the new item like the green button.

### Deployment

Unraid

### Deployment Details

omni-nightly 
Build 11cd277975621850e7fbd2b7030523ddcb5d59f8

**Comment by michael-genson** [comment]
> When parsing ingredients, the delete button doesn't seem to do anything.

This should be fixed in https://github.com/hay-kot/mealie/pull/2249
