### ISSUE TITLE
[v1.0.0b] - bookmarklet not working anymore

### ISSUE THREAD

**Issue by jlssmt** [mealie-recipes/mealie#2266]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

https://hay-kot.github.io/mealie/documentation/recipes/recipes/#using-bookmarklets

no longer works. It will only redirect to mealie without adding the recipe.
The url itself works when added manually.
The bookmarklet itself also works and generates this URL:

https://mealie.domain.com/?recipe_import_url=https%3A%2F%2Fwww.chefkoch.de%2Frezepte%2F1495691254829099%2FEckis-italienischer-Nudelsalat-mit-Pesto.html

### Deployment

Docker (Linux)

**Comment by cmintey** [comment]
Hey there. It seems like this url was changed at some point but not updated in the docs. Please try the following code in the [bookmarklet generator](https://caiorss.github.io/bookmarklet-maker/)
```js
var url = document.URL ;
var mealie = "http://localhost:8080"
var dest = mealie + "/recipe/create/url?recipe_import_url=" + url
window.open(dest, '_blank') 
```

**Comment by jlssmt** [comment]
@cmintey works. ty.
