### ISSUE TITLE
[v1.0.0beta-5] Sometimes Recipe Edit button does not do anything

### ISSUE THREAD

**Issue by jlar0che** [mealie-recipes/mealie#2273]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

There is no option to delete a recipe... I've looked everywhere. Three dots on the menu card give the following options only:
1. Edit
2. Download
3. Add to Plan
4. Add to List
5. Share

**Pertinent information:**
Version of Mealie: v1.0.0beta-5 
Build:  ee121a12f8db33ecb4db5f8582f7ea9788d019e4 
Demo Status: Not Demo 

### Deployment

Docker (Linux)

### Deployment Details

Docker deployment on Synology NAS

**Comment by michael-genson** [comment]
If you click "edit" on the recipe a delete button appears
![image](https://user-images.githubusercontent.com/71845777/227219347-65fc9f52-714d-45ff-a164-0ff4e6c25701.png)

**Comment by jlar0che** [comment]
Wow. I hit edit before and that menu did not turn up. But now I did a hard refresh (ctrl + f5) after clicking on edit and the menu with delete button suddenly appears.

Problem solved.

Thanks

**Comment by fleshgolem** [comment]
You can also click your name on the left and then go to "Manage Data" to delete multiple at once

**Comment by michael-genson** [comment]
I discovered some reproduction steps:

1. Open any recipe
2. Refresh the page
3. Click on Mealie (in the upper left) to go home
4. Click on the same recipe
5. Click on edit and observe that it doesn't work

**Comment by mkobler** [comment]
Just adding that I'm also seeing this behavior of being unable to edit an existing recipe, either imported via URL or added manually.

Am running build https://github.com/hay-kot/mealie/commit/693608d59fd1cd9f474108bd74576cd6c82b2dac
