### ISSUE TITLE
[v1.0.0b] - Hellofresh Canada Support

### ISSUE THREAD

**Issue by DerpyJakey** [mealie-recipes/mealie#2297]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Hello Im trying to import recipes from Hellofresh.ca
It grabs the image and name just fine but does not get the ingredient and steps. 
I know recipe_scrapers supports it now so it would be great to be able to use it with mealie
Thank you

### Deployment

Docker (Linux)

### Deployment Details

Build: 027fcbdcef743ff2767782f34fff7593ab32f1cf

**Comment by PeterJT** [comment]
This needs recipe_scrapers >= 14.34.0. Omni nightly current uses 14.31.0

**Comment by DerpyJakey** [comment]
Closing as recipe_scrapers has been updated in #2326 which i have confirmed to be working with Hellofresh.ca
