### ISSUE TITLE
[v1.0.0b] - Slow initial load times if Mealie has not been used recently

### ISSUE THREAD

**Issue by GovSat1** [mealie-recipes/mealie#2302]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Mealie initial page load time can be very slow if the app has not been used in a while. From blank page to Mealie interface (not accounting for recipe load time), it can take 5-10 or more seconds to load.

I've tested with both omni and split containers, both ssl (nginx) and http only. Running on intel x64 4core, ssd, LAN, no docker resource limitations. I do not see a significant server resource spike during loading. My db is small (<20 recipes), sqllite. Issue is the same with desktop chrome/safari and mobile/pwa.

Once loaded, it seems performant while being actively used. If closed and re-opened immediately, the page loads quickly. After some period of idle time, perhaps 30min+ (just a guess) the extended load time returns. 

I do not see any clues in the frontend or API logs. Sorry if this falls more into troubleshooting but I wasn't sure if this is expected behavior or perhaps just something that will be optimized in the future.

### Deployment

Docker (Linux)

**Comment by Seehundkuschler** [comment]
Yes, I have observed this as well. The effect also occurs with me since the beginning. On the desktop personal computer with Windows 10 and Firefox (esr), the effect is also noticeable, but not as strong. Loading time here is about 10 seconds. On my old Android tablet, the effect occurs with an initial load time of up to three minutes. I suspect as a non-expert that it is highly dependent on the performance of the end device. My NAS does not go into sleep mode. Unfortunately, I can't be more specific.
-QNAP NAS TS230, mealie nightly, Build (latest), sqlite) -

**Comment by GovSat1** [comment]
The newer nightlies "seem" to have improved this to some degree.

Also should note this behavior can be immediately replicated by restarting the container. First load is always slow.

**Comment by hay-kot** [comment]
I haven't been able to reproduce this on any of the instances I have running. Is there anything more specific I can try?

**Comment by Seehundkuschler** [comment]
I really think in the meantime that it is an effect of the end device and the dockerengine/NAS and not a real error of mealie. Sorry, don't want to lead you down a wrong path. I think, there is no need to waste time on that issue if other user have not the same issue. Thanks!

**Comment by GovSat1** [comment]
Hmm, I'll do some more testing. Perhaps there's some quirk to Synology's docker implementation causing the issue.. testing with Docker on Ubuntu I can't reproduce. Odd that it only affects Mealie, I have 15 containers or so that have no issues.

**Comment by fidesachates** [comment]
Not to bring back an old thread, but I'm starting to hit this now. I _think_ it started with 1.0 though I'm not quite sure. I do think it started when I upgraded from RC2 to 1.1 I think? Sorry for the vagueness. I've deployed this onto Ubuntu via kubernetes and when it was running the first version I deployed, things were working wonderfully. I only have 20 or so recipes. 

Please let me know if there's more data I can provide. I can't find much in the logs.

**Comment by Coryrichter94** [comment]
> Not to bring back an old thread, but I'm starting to hit this now. I _think_ it started with 1.0 though I'm not quite sure. I do think it started when I upgraded from RC2 to 1.1 I think? Sorry for the vagueness. I've deployed this onto Ubuntu via kubernetes and when it was running the first version I deployed, things were working wonderfully. I only have 20 or so recipes.
> 
> Please let me know if there's more data I can provide. I can't find much in the logs.

I am also experiencing the same issue on Version
v1.9.0
Build
[d96c36333b9cb9461c5dee96ae28b60d912b38fd]
I have multiple dockers running on a qnap tvs-882 i5 with 16gb of ram with no issues (system resources are not running out). I am running the sqlite database with only 5 recipes. Would the postersql database solve the issue?
