### ISSUE TITLE
[v1.0.0b] - Duplicate "Server" header sent by internal Caddy and gunicorn instances

### ISSUE THREAD

**Issue by Caligatio** [mealie-recipes/mealie#2308]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

As I described in #2294, I currently have nginx sitting in front of Mealie to do internal SSL/TLS. I noticed the following oddity in my nginx logs (I've omitted the full path):

    [warn] 31#31: *27 upstream sent duplicate header line: "Server: uvicorn", previous value: "Server: Caddy", ignored while reading response header from upstream,

I was going a bit insane because I'm using Caddy elsewhere and I thought it was somehow leaking its server header. However, I found out it's coming directly from the frontend container. Example response:

```
HTTP/1.0 200 OK
Content-Encoding: gzip
Content-Type: application/json
Date: Fri, 31 Mar 2023 04:14:59 GMT
Server: Caddy
Server: uvicorn
Vary: Accept-Encoding
```

I'm not a Caddy expert but I suspect something needs to be tweaked with the config for the Caddy instance running in the frontend container to avoid sending duplicate headers.

### Deployment

Docker (Linux)

### Deployment Details

I am running split frontend and backend containers if that makes a difference.

**Comment by hay-kot** [comment]
Hey! This is no longer applicable with the latest deployment stack. If you are still seeing issues please fill out another ticket. Thanks!
