### ISSUE TITLE
FR: Disable Ratings

### ISSUE THREAD

**Issue by DrSpaldo** [mealie-recipes/mealie#2324]
### Discussed in https://github.com/hay-kot/mealie/discussions/2237

<div type='discussions-op-text'>

<sup>Originally posted by **DrSpaldo** March 12, 2023</sup>
Hi, I have no intention of using ratings and if they are not used, it is a bit of an unneeded clutter. Is there a way to just turn them off? </div>

**Comment by hay-kot** [comment]
There is no way to turn them off, and there are no plans to implement such a feature.

In the future please use the feature request discussion format 

- https://github.com/hay-kot/mealie/issues/317
