### ISSUE TITLE
[v1.0.0b] - Sorting is not remembering the last used order

### ISSUE THREAD

**Issue by DrSpaldo** [mealie-recipes/mealie#2352]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Although it would be great if this was simply an option in the settings for the server/user, which sort order is default. I have tried to adapt and just use the sort button, then hope that it will remember my last selected order. It is not working for me.

The last used sort order is forgotten every time when using the iOS home page shortcut. The last used sort order is forgotten when using Edge or Brave, if you click the search button or Mealie icon up the top to return to the main page. 

I am currently using nightly build 73476c10f80b686225c7008547c0e531810f0e09. However, happy to repull the docker if there have been any sorting related changes. Hope this makes sense, thanks.

### Deployment

Unraid

### Deployment Details

Unraid

**Comment by godsgood33** [comment]
I agree, this is a problem and glad to see that the dev saw it.  I'd like to add that it would be nice if this isn't implemented there is a way to change a users default sorting order.

**Comment by damomato** [comment]
Any updates on this? I would like to sort by alphabetical order by default but it keeps changing to sort by created which is very annoying.

**Comment by boc-the-git** [comment]
The issue is open, and noted as a confirmed bug. I would expect at some point in the future someone will pick it up.

It's not an overly high priority.

The team would welcome a PR from yourself or anyone wanting this progressed in the short term.

**Comment by DrSpaldo** [comment]
I can’t see why this wouldn’t be a high priority issue. It’s a bug and preventing me from using the app. It’s more important than any new features

_Edit: nevermind, I just read and noticed that the maintainer is moving to the paid version and isn’t doing much on this anymore. What a shame_

**Comment by boc-the-git** [comment]
As I mentioned @DrSpaldo, PRs are welcome.

We have a small team maintaining this project in our spare time, and this is not our highest priority to work on. That's not saying it won't be done.

**Comment by michael-genson** [comment]
> noticed that the maintainer is moving to the paid version and isn’t doing much on this anymore

Not sure where you heard or read this, but it wasn't from any maintainers of Mealie. Spreading rumors isn't going to make anyone work on this issue faster

**Comment by DrSpaldo** [comment]
> > noticed that the maintainer is moving to the paid version and isn’t doing much on this anymore
> 
> Not sure where you heard or read this, but it wasn't from any maintainers of Mealie. Spreading rumors isn't going to make anyone work on this issue faster

I don't really care anymore if someone fixes the bug or not. If they do, I will start using the app again, if they don't I will just keep using the webpage setup that I have. 

The info came from [hay-kot](https://github.com/hay-kot) himself, see this post... https://github.com/mealie-recipes/mealie/releases/tag/v1.0.0-RC1

**Comment by damomato** [comment]
> The issue is open, and noted as a confirmed bug. I would expect at some point in the future someone will pick it up.
> 
> It's not an overly high priority.
> 
> The team would welcome a PR from yourself or anyone wanting this progressed in the short term. 

Thanks. I didn't mean to come off as pushy, just genuinely was looking for an update. I would work on it myself if I knew how or had the time to learn and do it.

**Comment by michael-genson** [comment]
> The info came from [hay-kot](https://github.com/hay-kot) himself... https://github.com/mealie-recipes/mealie/releases/tag/v1.0.0-RC1

> moving to the paid version and isn’t doing much on this anymore

Is a far cry from

> I've decided to dial back my involvement a bit. My focus will shift primarily to maintenance and squashing bugs...

There are also several maintainers of Mealie. At the time of writing, there have been 89 closed PRs since that post was created two months ago, not including the automated crowdin ones:

https://github.com/mealie-recipes/mealie/pulls?q=is%3Apr+created%3A%3E2023-10-07+in%3Atitle+NOT+Crowdin+is%3Aclosed

**Comment by DrSpaldo** [comment]
Still doesn't remember the last used sort order if you refresh. For the love of god, can't there just be selectable default sort order

**Comment by Kuchenpirat** [comment]
Have you updated to the newest nightly?

**Comment by DrSpaldo** [comment]
> Have you updated to the newest nightly?

Looks like my unraid was using the old omni nightly tag and never updated correctly. This new version is working so far, thanks
