### ISSUE TITLE
[v1.0.0b] - Can't delete recipes

### ISSUE THREAD

**Issue by ctrlaltd1337ed** [mealie-recipes/mealie#2353]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I cannot delete recipes on Mealie. I have tried importing recipes and creating new recipes myself, and I cannot delete them. I've tried logging in and out, and restarting the container.

I also went to the Mealie demo site and I was able to click edit and then the delete button showed up, but it does not for my installation.

**Details**
Version: nightly
Build: fa59c1eb0b14971768f9593ee5781ec166914353
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.36.0

**Checks**
Secure Site: No
Server Side Base URL: No
LDAP Ready: No
Email Configured: Yes
Docker Volumes: success

### Deployment

Unraid

**Comment by ctrlaltd1337ed** [comment]
Created a reverse proxy to my Mealie install and logged into it rather than the local IP and the delete function was working.

**Comment by tristan-k** [comment]
I'm having the same issue but the delete function isn't there. I'm already using a reverse proxy. The only way I can delete receipts is through the API.

**Comment by NaruZosa** [comment]
@tristan-k If you're unable to find it, it's under the edit menu, not the hotdog menu.
