### ISSUE TITLE
Importing recipe from tantefanny.at not working

### ISSUE THREAD

**Issue by jjj120** [mealie-recipes/mealie#2356]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I have checked for existing issues that have been resolved in v1-beta

### What is the issue you are experiencing?

I tried importing a recipe from www.tantefanny.at and it did not work, but the collected data seems to be standard json data. 

The specific link I used was https://www.tantefanny.at/rezept/schafkaese-tomaten-dreiecke/

### Deployment

Docker (Linux)

### Mealie Version

v0.5.6

**Comment by michael-genson** [comment]
If you're using version 0.5.6, that is no longer being updated. I recommend migrating to the 1.0.0 beta:
https://nightly.mealie.io/documentation/getting-started/migrating-to-mealie-v1/

The link you shared works fine on the demo, which uses the nightly version of Mealie:
https://demo.mealie.io/recipe/schafkase-tomaten-dreiecke
