### ISSUE TITLE
[v1.0.0b] - Missing Cookbook delete button

### ISSUE THREAD

**Issue by fakethinkpad85** [mealie-recipes/mealie#2360]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Sorry if i missed something but i cant seem to find a way to delete cookbooks. Also not sure if that would be a bug or feature request to be honest.

### Deployment

Docker (Synology)

**Comment by hay-kot** [comment]
It's on the cookbook editor page

![CleanShot 2023-04-26 at 10 33 42@2x](https://user-images.githubusercontent.com/64056131/234670476-41d20348-b3ce-47ec-81eb-12de570cb271.png)
