### ISSUE TITLE
nightly - Refreshing Timeline or going to the Timeline url directly causes a server error on postgres

### ISSUE THREAD

**Issue by jecorn** [mealie-recipes/mealie#2370]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?
@michael-genson 
I love the new Timeline! But refreshing the Timeline page or going to `http://<mealie-url>/group/timeline` without clicking on the Timeline causes my Postgres production instance of mealie to experience a server error (reported by nuxt, error output to stdout linked below). And despite the title, this also happens with sqlite (just figured that out).

Clicking on the Timeline link/icon loads the timeline just fine and the Timeline can be navigated as intended. I can even click on a recipe in the Timeline, then go "Back" in the browser and the Timeline loads OK. But refreshing the Timeline once I'm on it, or directly entering the Timeline URL, or even copying the link behind the Timeline icon and then pasting it into the address bar gives the server error linked below.

[servererror.log](https://github.com/hay-kot/mealie/files/11367340/servererror.log)

This does **not** happen on an empty dev instance of mealie nightly, using either sqlite or postgres. Which means it's going to be a pain in the butt to debug.

### Deployment

Docker (Linux)

### Deployment Details

Postgres and sqlite backend

**Comment by michael-genson** [comment]
Thanks for this, I _might_ have a fix, but I'm not too sure what the issue is. Either way, the logs are super helpful, so thank you!

**Comment by jecorn** [comment]
Wow, incredibly fast debugging! Kudos!

**Comment by michael-genson** [comment]
Haha don't get too excited yet, I have no idea if this will fix it or not since I can't reproduce in dev, only in production

**Comment by hay-kot** [comment]
@michael-genson I'm like 99% sure that #2372 is _not_ the issue. $auth should be fine for SSR. 

This is likely the culprit

https://github.com/hay-kot/mealie/blob/75698c531aaa057e1d35ae5bd4fb09ee8a11b47b/frontend/components/Domain/Recipe/RecipeTimeline.vue#L107-L124

You cannot directly access DOM api's fro the setup script and rely on SSR to work. You should be able to wrap it in a `onMounted` hook though and that should fix it. 

For testing, you can use the `make docker/prod` to build a production like container, (or just copy the command if you're on windows).

This in the logs makes me pretty sure.

```
mealie-frontend  |  ERROR  document is not defined
mealie-frontend  | 
mealie-frontend  |   at setup (components/Domain/Recipe/RecipeTimeline.vue)
```

**Comment by michael-genson** [comment]
Ahhh okay, thanks! I'll go ahead and update #2372 (I like the small cleanup that provides anyway so I'll keep it there instead of making a new PR)
