### ISSUE TITLE
Do not style with "Dark" mode when printing

### ISSUE THREAD

**Issue by 3xcellent** [mealie-recipes/mealie#2374]
When a user is in "Dark" mode, do not print with that style.  Ink is expensive, and printing a page with an all black background uses a lot of ink.

**Comment by michael-genson** [comment]
What version of Mealie are you on? I have never seen the print view have anything other than black text on a white background, and I use dark mode exclusively

**Comment by 3xcellent** [comment]
I did a `docker-compose pull` last night, so i dunno.  it doesn't seem to be doing it now.... great, now I'm *that* guy.
