### ISSUE TITLE
[v1.0.0b] - Integrity Error on User Creation with LDAP Authentication

### ISSUE THREAD

**Issue by ds-sebastian** [mealie-recipes/mealie#2378]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

**Issue Description**

I'm encountering an issue with the LDAP authentication feature in Mealie. When attempting to authenticate a user from LDAP, the user creation process fails with an integrity error related to the "group_id" column in the "users" table. This error suggests that the "group_id" value is not being provided when creating a new user (or that I have no idea what I'm doing with LDAP which is also likely). 

**Steps to Reproduce**
1. Start Mealie with LDAP authentication enabled.
2. Attempt to authenticate a user from LDAP.

**Expected Behavior**
The user should be successfully authenticated and created in the Mealie database, with the appropriate group association.

**Actual Behavior**
The user creation process fails with an integrity error related to the "group_id" column.

**Error Logs**
```
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "group_id" of relation "users" violates not-null constraint
DETAIL:  Failing row contains (2023-05-06 03:25:55.126565, 2023-05-06 03:25:55.126568, 5ff49ee7-bc3d-4fbc-92c3-735ee60ba1d1, user1, user1, user1.name2@gmail.com, LDAP, f, f, null, 1234, f, f, f, null, 0, null, LDAP).

[SQL: INSERT INTO users (id, full_name, username, email, password, auth_method, admin, advanced, group_id, cache_key, login_attemps, locked_at, can_manage, can_invite, can_organize, owned_recipes_id, created_at, update_at) VALUES (%(id)s::UUID, %(full_name)s, %(username)s, %(email)s, %(password)s, %(auth_method)s, %(admin)s, %(advanced)s, %(group_id)s::UUID, %(cache_key)s, %(login_attemps)s, %(locked_at)s, %(can_manage)s, %(can_invite)s, %(can_organize)s, %(owned_recipes_id)s::UUID, %(created_at)s, %(update_at)s)]
[parameters: {'id': '5ff49ee7-bc3d-4fbc-92c3-735ee60ba1d1', 'full_name': 'user1', 'username': 'user1', 'email': 'user1.name2@gmail.com', 'password': 'LDAP', 'auth_method': 'LDAP', 'admin': False, 'advanced': False, 'group_id': None, 'cache_key': '1234', 'login_attemps': 0, 'locked_at': None, 'can_manage': False, 'can_invite': False, 'can_organize': False, 'owned_recipes_id': None, 'created_at': datetime.datetime(2023, 5, 6, 3, 25, 55, 126565), 'update_at': datetime.datetime(2023, 5, 6, 3, 25, 55, 126568)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
```

**LDAP Settings**
```
'LDAP_AUTH_ENABLED'='true'
'LDAP_TLS_INSECURE'='true'
'LDAP_SERVER_URL'='ldap://****:3389'
'LDAP_ENABLE_STARTTLS'='false'
'LDAP_BASE_DN'='DC=ldap,DC=goauthentik,DC=io'
'LDAP_QUERY_BIND'='cn=ldapservice,ou=users,DC=ldap,DC=goauthentik,DC=io'
'LDAP_QUERY_PASSWORD'='****'
'LDAP_ID_ATTRIBUTE'='cn'
'LDAP_NAME_ATTRIBUTE'='cn'
'LDAP_MAIL_ATTRIBUTE'='mail'
'LDAP_ADMIN_FILTER'='(memberOf=cn=authentik Admins,ou=groups,dc=ldap,dc=goauthentik,dc=io)'
'LDAP_USER_FILTER'='(memberOf=cn=UserGroup WebApps,ou=groups,dc=ldap,dc=goauthentik,dc=io)'

```

**Relevant Code?**
https://github.com/hay-kot/mealie/blob/23786c1f5ea1c67842d4a44cead645d3ff59f643/mealie/core/security/security.py#LL149C3-L149C3

### Deployment

Unraid

### Deployment Details

Authentik is my LDAP provider.

**Comment by ds-sebastian** [comment]
Updated, , wiped the database (postgresql), and deleted the appdata to have a fresh install and now the user is working fine. I think it was a database issue as the LDAP user existed previously as a standard mealie auth user (but was deleted).

**Comment by fnonnenmacher** [comment]
I faced the same issue and I was able to solve it without resetting the database.

I admit that it was a lucky shot, but I found in the [AppSettings](https://github.com/mealie-recipes/mealie/blob/23786c1f5ea1c67842d4a44cead645d3ff59f643/mealie/core/settings/settings.py#L80C27-L80C31)  a default group attribute of the name "Home". Creating a group with this name has actually fixed the issue for me.

I don't recall if I deleted this group earlier, but probably it will be initialized at the first start.

**Comment by oddomatik** [comment]
Confirmed to have had the same issue - if the LDAP settings aren't perfect the first time, this issue with is encountered after the database populates. I referenced ldap.py to use python-ldap to manually verify my authentik filters and mappings, then nuked the database/config and started over and it worked fine. The documentation could be improved there.

**Comment by cmintey** [comment]
This is likely related to #2648. If you change the group name or no longer have a group called "Home", you can set the default group in your environment so that a new LDAP user is added to that group. 

If the user needs to be switched to a different group later, you can do that in the admin UI.
