### ISSUE TITLE
[v1.0.0b] - LDAP_BIND_TEMPLATE is missing in Documentation

### ISSUE THREAD

**Issue by DunklerPhoenix** [mealie-recipes/mealie#2385]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Heho
Mealie says that the LDAP configuration is not complete and I saw `LDAP_BIND_TEMPLATE null` in the logs. So I searched for it and found some example in the discussions. This was definitve the missing variable. It should be added to the documentation.

### Deployment

Docker (Linux)

**Comment by cmintey** [comment]
That environment variable was removed and thus not present in the docs. This change is reflected in the latest nightly docker tag. See #2107
