### ISSUE TITLE
[v1.0.0-nightly] - Meal Planner Pagination off, makes it look like there are no meals for today. 

### ISSUE THREAD

**Issue by Scags104** [mealie-recipes/mealie#2388]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When trying to append recipes to todays date, the dialog boxes allow me to select what i want but then nothing applies. Works as intended for all other days in the range.

### Deployment

Other

### Deployment Details

Deployed via HomeAssistant addon - was advised to move my issue upstream [here](https://github.com/alexbelgium/hassio-addons/issues/831)

omni-nightly image

**Comment by hay-kot** [comment]
Issue is likely in from commit https://github.com/hay-kot/mealie/commit/5d87b7e411c8acca3e92fd685d0fad0f31377ffb

It actually looks like it's apply the recipes, but the pagination if off, you can test this by changing the date in the date picker, the first day will always be missing

<img width="1307" alt="CleanShot 2023-05-11 at 14 00 42@2x" src="https://github.com/hay-kot/mealie/assets/64056131/7a39fc48-4302-4d11-8ad2-49f564f70d76">

<img width="1327" alt="CleanShot 2023-05-11 at 14 00 54@2x" src="https://github.com/hay-kot/mealie/assets/64056131/2164cecb-c786-4401-be36-10d8487ed654">

**Comment by Scags104** [comment]
Tested and you are correct. Thanks atleast I have a workaround for now!

**Comment by michael-genson** [comment]
Fix incoming, thanks for the report!
