### ISSUE TITLE
SMTP with gmail errors and not working. Log says login with web browser?

### ISSUE THREAD

**Issue by ViperJPB** [mealie-recipes/mealie#2395]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Made a new gmail account and fed the docker config all the proper info but I continue to get an error trying to use SMTP. Ports are open and like I said config seems correct (in uraid compose template). Tried both ports and TSL and SSL

Log says:
ERROR: 18-May-23 18:45:05 	(534, b'5.7.9 Please log in with your web browser and then try again. Learn more at\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired p26-20020a62ab1a000000b006259e883ee9sm205331pff.189 - gsmtp')

Here is what I have entered: 

ALLOW_SIGNUP: false
DEFAULT_EMAIL: my personal email@gmail.com
SMTP_FROM_EMAIL: new mealie email @gmail.com
SMTP_HOST: smtp.gmail.com
SMTP_USER: new mealie email @gmail.com
SMTP_PASSWORD: new mealie email @gmail.com password
SMTP_PORT: 587

Reading on googles documentation is this no longer an available option? If so what would you recommend?        

### Deployment

Unraid

**Comment by PeterJT** [comment]
FYI; I have no issues with the following settings
        SMTP_HOST="smtp.gmail.com"
        SMTP_PORT=587
        SMTP_FROM_NAME="Mealie"
        SMTP_AUTH_STRATEGY=TLS
        SMTP_FROM_EMAIL="<my_id>t@gmail.com" 
        SMTP_USER="<my_id>@gmail.com"
        SMTP_PASSWORD="<app specific password for <my_id>@gmail.com"

**Comment by ViperJPB** [comment]
> FYI; I have no issues with the following settings SMTP_HOST="smtp.gmail.com" SMTP_PORT=587 SMTP_FROM_NAME="Mealie" SMTP_AUTH_STRATEGY=TLS SMTP_FROM_EMAIL="<my_id>[t@gmail.com](mailto:t@gmail.com)" SMTP_USER="<my_id>@gmail.com" SMTP_PASSWORD="<app specific password for <my_id>@gmail.com"

Thats so odd. Wonder what I'm missing. My settings match yours. Why does the log want me to log in with a web browser? I tried the whole app password thing to that google gives. no luck.

**Comment by ViperJPB** [comment]
Hold the phone. Randomly went back and ran a test and it worked now! Nobody move. Just needed some simmering time apparently.
