### ISSUE TITLE
Evernote import? Can't find a fast option. 

### ISSUE THREAD

**Issue by ViperJPB** [mealie-recipes/mealie#2396]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Evernote has it's own format to export, an html file with image, or pdf as export options. None of which can be brought into Mealie  quickly or in bulk. Any way or process I'm unaware of?

### Deployment

Unraid

**Comment by michael-genson** [comment]
Currently your best bet is to convert the PDF to an image and use OCR. There's some talk about building that feature into Mealie at some point, but currently OCR only accepts images.

If you'd like to to see support for Evernote imports, please [submit a feature request](https://github.com/hay-kot/mealie/issues/317) and include a few sample exported recipes (more is better)

**Comment by ViperJPB** [comment]
Thx for the quick response. Yeah I considered that route as well. Maybe I will do the feature request. Love Mealie so far though!
