### ISSUE TITLE
[v1.0.0b] - Tags not being saved intermittently when the saved.

### ISSUE THREAD

**Issue by ViperJPB** [mealie-recipes/mealie#2398]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Has happened to me several times today. Add a ton of tags to an entry. Hit the save button. Page saves and shows the Recipe entry but all the added tags of that session are not in the recipe. Any created tags are in the tag library but whatever was added to that recipe that session was simply not saved.  Not every time. But I would say almost every third entry I edit. Any thoughts?

### Deployment

Unraid

**Comment by hay-kot** [comment]
If you refresh the page does anything change?

**Comment by ViperJPB** [comment]
Sadly no. But this has yet to happen again since this post so that’s good.
