### ISSUE TITLE
Admin locked out of account

### ISSUE THREAD

**Issue by crankycowboy** [mealie-recipes/mealie#2422]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I have checked for existing issues that have been resolved in v1-beta

### What is the issue you are experiencing?

I recently migrated from a pre V1 release. I did so by backing up the old version and importing into the new to transfer my recipes. All worked well.  I'm running via unraid. I went into settings and changed my password and received a "password changed successfully". I then logged out to log back in via the updated password and I'm getting a "account is locked, please try again later" error message. I stopped my container and restarted thinking it may reset  any lock behavior but it's still doing it. Any suggestion of what I can try to rectify?

### Deployment

Unraid

### Deployment Details

Unraid

### Mealie Version

v1

**Comment by hay-kot** [comment]
Have you looked at this?

https://nightly.mealie.io/documentation/getting-started/faq/#how-can-i-unlock-my-account
