### ISSUE TITLE
[vomni-nightly] - OCR recipe creation doesn't honor group settings.

### ISSUE THREAD

**Issue by JvdMaat** [mealie-recipes/mealie#2424]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When creating a recipe from image (OCR), and savings it, it does not get the default group settings (public recipe, disable comments, landscape, etc).
This could be linked to https://github.com/hay-kot/mealie/issues/2394.

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
FYI we have decided to remove OCR from Mealie. You can read more on #2838.

If you need to use OCR to import recipes, I recommend using external tools such as this [online OCR tool](https://www.onlineocr.net/) to extract the text, which you then copy-paste into Mealie.
