### ISSUE TITLE
[v1.0.0b] - Natural Language Processor doesn't auto-select items with capital letters

### ISSUE THREAD

**Issue by Rojikku** [mealie-recipes/mealie#2426]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Finally got the app working, it's great. But when using the ingredient quantity parsing with the natural language parser, I noticed it will match, but not select, on ingredients/quantities where I have capitalized the letter by manually inputting values. It works fine on values where I allowed it to auto-fill uncapitalized.

![image](https://github.com/hay-kot/mealie/assets/1676068/ba60c2f1-cefd-44c9-b81c-24d595e7dc30)

Theoretically very easy fix.

I learned how to mass-edit the ingredients list, and uncapitalizing them definitely fixed my issue.

### Deployment

Other

**Comment by michael-genson** [comment]
This should be fixed in nightly: https://github.com/mealie-recipes/mealie/pull/2535

I'm going to close this for now, but if you upgrade to nightly and still experience this feel free to re-open
