### ISSUE TITLE
[v1.0.0b] - Pushover notifications for shopping lists fail with a 400 error - Unsupported Parameters

### ISSUE THREAD

**Issue by sudermanjr** [mealie-recipes/mealie#2428]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I have the pushover integration working when I use the "test notification" button, but when I modify a shopping list to trigger a notification, I see this in the logs:

`Failed to send Pushover notification to ALL_DEVICES: Bad Request - Unsupported Parameters., error=400.`

### Deployment

Docker (Synology)

### Deployment Details

I am using the unified single docker container on Synology NAS with postgres. The container was pulled 2023-06-26.

**Comment by boc-the-git** [comment]
@sudermanjr, do you have an update on this, using a recent version of Mealie?
If so, can you please provide more specifics about what exactly you're doing, your relevant configuration, logs, etc?

**Comment by boc-the-git** [comment]
Closing due to lack of updates. If there is an issue here using a recent version of Mealie, please feel free to re-open with appropriate logs etc.
