### ISSUE TITLE
[v1.0.0b] - Importing recipe adds "2 * " to all ingredients.

### ISSUE THREAD

**Issue by Noxeus** [mealie-recipes/mealie#2433]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

**How to reproduce:**
1. Log in.
2. Add recipe using importer
3. Import recipe from hellofresh.nl (example: https://www.hellofresh.nl/recipes/heeklende-met-knoflook-botersaus-63e1147584fc3c82a5383c47)

Now the list of ingredients has `2 * ` in front of every ingredient. Note that quantity is disabled in this example.
![image](https://github.com/hay-kot/mealie/assets/1268003/acca5b16-09b9-4471-af4e-c9a28f02ed1c)
I have confirmed that it's actually added to the ingredient 'note' not the quantity.
Gamecrazy721 on the Discord has confirmed he can reproduce this.

### Deployment

Docker (Linux)

### Deployment Details

**Details**
Versie: v1.0.0beta-5
Build: ee121a12f8db33ecb4db5f8582f7ea9788d019e4
Applicatie modus: Productie
Demo status: Niet Demo
API Poort: 9000
API-documentatie: Ingeschakeld
Databasetype: sqlite
Recipe Scraper Version: 14.20.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: Yes
Docker Volumes: success

**Comment by michael-genson** [comment]
Just to add to this, I can reproduce in nightly. Weirdly, the scraper debugger doesn't show the extra "2 *" characters:
![image](https://github.com/hay-kot/mealie/assets/71845777/4cd9f447-0d27-4456-a5bf-e69e59ebe014)

But the recipe appears as shown in the first screenshot. I thought it might be related to recipe scaling (and it might be) but it happens immediately upon recipe creation, so it's not user error

**Comment by user34756361233** [comment]
I imported the same recipe, it showed the same 2 * for every ingredient. Above that editing (and deleting) the recipe is not possible...

**Comment by ccalby** [comment]
Can confirm this also occurs with Hello Fresh UK.
Recipe:
![image](https://github.com/hay-kot/mealie/assets/680553/39f2b6a1-08e0-42e1-9aab-2f8b750468f8)

Mealie Import:
![image](https://github.com/hay-kot/mealie/assets/680553/19dea0d8-7b1f-418d-971a-669a7e2e8ec6)

**Comment by ItsMly** [comment]
Also happening to me - tried with einfachbacken.de and Hello Fresh DE

**Comment by Noxeus** [comment]
Can be fixed by updating recipe-scraper to ^[14.38.0](https://github.com/hhursev/recipe-scrapers/releases/tag/14.38.0) .

**Comment by hay-kot** [comment]
Looks to be fixed in nightly. Thanks!
