### ISSUE TITLE
Share Buttons / Links not working?

### ISSUE THREAD

**Issue by crispybegs** [mealie-recipes/mealie#2443]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I have checked for existing issues that have been resolved in v1-beta

### What is the issue you are experiencing?

Neither the share button on recipes are the share sign-up link button are working for me. When I click either of them there's subtle shade animation, but nothing is generated nor copied to the clipboard.

I'm on MacOS Catalina using lastest version of chrome. I also tried in Safari but got exactly the same behaviour, so any intereference from chrome plug-ins including any adblocking (which was the first thing i turned off for testing) is ruled out.

Any ideas?

### Deployment

Docker (Linux)

### Mealie Version

v0.5.6

**Comment by michael-genson** [comment]
v0.5.6 is very old, you probably want to upgrade to the latest 1.0.0 beta version. That said, web browsers don't support the clipboard through insecure HTTP (it only works with HTTPS). Do you have a certificate for your Mealie instance?

**Comment by crispybegs** [comment]
> v0.5.6 is very old, you probably want to upgrade to the latest 1.0.0 beta version. That said, web browsers don't support the clipboard through insecure HTTP (it only works with HTTPS). Do you have a certificate for your Mealie instance?

ah strange, my compose file asks to pull `hkotel/mealie:latest`, and that's the version it pulled. I'll go over everything again today and try again

**Comment by crispybegs** [comment]
oh it seems like i stumbled across a totally different set of installation instructions. 

I followed the SQLite compose here - https://hay-kot.github.io/mealie/documentation/getting-started/install

But I've just now seen this, which is quite different - https://nightly.mealie.io/documentation/getting-started/installation/sqlite

confusing stuff

**Comment by michael-genson** [comment]
Yup, those are the right docs! If you're still running into issues, let us know!

**Comment by crispybegs** [comment]
> Yup, those are the right docs! If you're still running into issues, let us know!

sorry for my late reply, i was away for a few days. I deleted eveything and went with the second set of instructions which indeed pulled quite a different and updated version, so thank you! My current version is **hkotel/mealie:frontend-v1.0.0beta-5** - i'm not sure if that's the best one to use, but pulling 'latest' downloaded that older version so I guess this one is generally better.

**Comment by michael-genson** [comment]
Yup, that's the newest stable version. The newest (usually stable but not technically guaranteed to be stable) version is nightly
