### ISSUE TITLE
[nightly] - Meal Plan Notes allow Submission Without Title/Note Text, but Return 422

### ISSUE THREAD

**Issue by Grygon** [mealie-recipes/mealie#2446]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

![image](https://github.com/hay-kot/mealie/assets/647846/367c8291-0864-465b-be0d-36a9034c729a)

![image](https://github.com/hay-kot/mealie/assets/647846/7f25cf56-1ba8-47d6-a4d2-2633b5ff6385)

![image](https://github.com/hay-kot/mealie/assets/647846/2abedb65-a9b1-41b0-9e16-2076b5ee45b1)

Planning to handle in #2399 but submitting since it may be a little while before I get to it.

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Ah I see, looks like we need to add validation to the frontend. This is the backend:
```python
class CreatePlanEntry(MealieModel):
    date: date
    entry_type: PlanEntryType = PlanEntryType.breakfast
    title: str = ""
    text: str = ""
    recipe_id: UUID | None

    @validator("recipe_id", always=True)
    @classmethod
    def id_or_title(cls, value, values):
        if bool(value) is False and bool(values["title"]) is False:
            raise ValueError(f"`recipe_id={value}` or `title={values['title']}` must be provided")

        return value
```

**Comment by Grygon** [comment]
Fixed by 776d56eb75d2738d3a8584b5378c65dd39edd06c

**Comment by boc-the-git** [comment]
Adding bug confirmed, based on Michael's comment way back when.

**Comment by dzek69** [comment]
Bump. Can we get this fix implemented?

It seems that the fix is not a part of this repo, but it's ready to use (idk Vue, but looks correct), so it's probably a quick upgrade that fixes pretty annoying bug 👍🏻

**Comment by boc-the-git** [comment]
I've just tested the solution posted here and it doesn't seem to work for me - the UI tells me the field is required but doesn't actually stop me submitting it and hitting the 422 error.
I'm not going to dig into it any more right now.

**Comment by 20kaushik02** [comment]
Getting the same error even on 1.12.0

**Comment by Arshad561** [comment]
Hi @boc-the-git,  I have fixed this issue in this PR
https://github.com/mealie-recipes/mealie/pull/4615
