### ISSUE TITLE
[v1.0.0b] - Recipe tags on main/search page do not work when clicking on a tag on the recipe card

### ISSUE THREAD

**Issue by shiruken** [mealie-recipes/mealie#2447]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Clicking recipe tags on the main/search page do not actually filter the results. The page URL is updated with the appropriate tag ID but the filter is not applied.

This may be related to #2259.

### Deployment

Docker (Linux)

### Deployment Details

Version: omni-nightly
Build: 4af9eec89dd0b309ebea752d715add3fe0980b3d

**Comment by michael-genson** [comment]
Pretty sure this was fixed a while ago. Feel free to re-open if you're still seeing this behavior

**Comment by shiruken** [comment]
This appears to still be broken. The page URL is being updated with the appropriate tags but the filter isn't actually being applied.

**Comment by michael-genson** [comment]
Can you post your deployment details? I checked on my instance and it works. It also seems to work on the demo

**Comment by shiruken** [comment]
Version: `v1.0.0-RC2`
Build: `c9852daf0e213dc4cadf97971c7787cf6fc66dfc`

Also, I'm not seeing this working on the Demo site. On the main page, clicking on the tag "Test" does not result in the recipes being filtered by that tag.

https://github.com/mealie-recipes/mealie/assets/867617/dce35500-6fc7-43cf-826e-77aabaea6135

**Comment by michael-genson** [comment]
Oooh okay, I didn't even know that was a feature. I was clicking on the "Tags" button at the top under the search bar (which does work). Thanks for the clarification!

**Comment by boc-the-git** [comment]
Adding bug confirmed, based on Michael's comment way back when.
