### ISSUE TITLE
[v1.0.0b] - Editing recipe timeline events changes the date to current date

### ISSUE THREAD

**Issue by shiruken** [mealie-recipes/mealie#2450]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Editing recipe timeline events (whether created manually or via the Meal Planner) result in the event date being changed to the current date.

1. Manual event created on recipe with date 2023-07-01 
   <img width="1177" alt="image" src="https://github.com/hay-kot/mealie/assets/867617/8f4f2fc2-916d-4561-975c-8edf08fe8775">
2. Edit event
   <img width="502" alt="image" src="https://github.com/hay-kot/mealie/assets/867617/f606c312-10ac-41f5-b01a-346ae5685334">
3. Event date changed to edit date (today, 2023-07-09)
   <img width="1173" alt="image" src="https://github.com/hay-kot/mealie/assets/867617/1b369831-da11-45f1-a458-661dae4208e9">

### Deployment

Docker (Linux)

### Deployment Details

Version: omni-nightly
Build: 4af9eec89dd0b309ebea752d715add3fe0980b3d

**Comment by michael-genson** [comment]
It's funny, I actually just discovered this by accident a couple days ago while testing a different new feature. Should be fixed with this PR:

https://github.com/hay-kot/mealie/pull/2444
