### ISSUE TITLE
Created a test recipe, now unable to delete it

### ISSUE THREAD

**Issue by crispybegs** [mealie-recipes/mealie#2451]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I have checked for existing issues that have been resolved in v1-beta

### What is the issue you are experiencing?

I found the OCR feature and tested it out. For some reason it refused to save and just kept giving me an error message, but I don't have an issue with that. Back on the recipe homepage I now have this created by that test...

<img width="403" alt="Screenshot 2023-07-09 at 23 32 53" src="https://github.com/hay-kot/mealie/assets/129169122/5169b11a-74f5-4fe9-965a-6408290e572d">

But I can't find a way to delete it. When I click the 'Edit' button i get this 404

<img width="489" alt="Screenshot 2023-07-09 at 23 33 03" src="https://github.com/hay-kot/mealie/assets/129169122/d7a5b9a9-a730-42ea-8444-2445f55dce83">

Is there some way I'm missing where I can get rid of it?

### Deployment

Docker (Linux)

### Mealie Version

v1.0.0beta-5

**Comment by boc-the-git** [comment]
@crispybegs, is this something that can be replicated on either the nightly or RC1.1 images? Do you have more specific info about the replication steps?
Can you please provide the logs?

**Comment by michael-genson** [comment]
FYI we have decided to remove OCR from Mealie. You can read more on #2838.

If you need to use OCR to import recipes, I recommend using external tools such as this [online OCR tool](https://www.onlineocr.net/) to extract the text, which you then copy-paste into Mealie.
