### ISSUE TITLE
Logging issue when "Add Mealie to home screen" app to pixle7

### ISSUE THREAD

**Issue by 4pendesigns** [mealie-recipes/mealie#2453]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I have checked for existing issues that have been resolved in v1-beta

### What is the issue you are experiencing?

**Details**
Version: v1.0.0beta-5
Build: ee121a12f8db33ecb4db5f8582f7ea9788d019e4
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.20.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: Yes
Docker Volumes: success

After opening mealie in chrome on my pixel7, I login fine.  Then I click the button to "Add Mealie to Home Screen".  After closing chrome, If I use the new Mealie shortcut I can log in and check remember me box.  Logs in fine.  After closing Mealie and reopen with shortcut, it flashes the login screen then page goes blank.  I believe its auto clicking the login button before the app has the  chance to autofill login credentials. 

### Deployment

Docker (Linux)

### Mealie Version

v1.0.0beta-5

**Comment by michael-genson** [comment]
This is fixed in nightly. If you're relying heavily on the PWA, I recommend upgrading to nightly until there's a new release

**Comment by michael-genson** [comment]
FYI: https://github.com/hay-kot/mealie/issues/1077
