### ISSUE TITLE
Not able to pull ARM64 image with message "no manifest for linux/arm/v8" on Raspberry Pi 4

### ISSUE THREAD

**Issue by Strehk** [mealie-recipes/mealie#2454]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I have checked for existing issues that have been resolved in v1-beta

### What is the issue you are experiencing?

I am trying to pull the docker image onto my Raspberry Pi 4 with `docker pull hkotel/mealie:latest`, but all I get is an error: 
```
❯ docker pull hkotel/mealie:latest
latest: Pulling from hkotel/mealie
no matching manifest for linux/arm/v8 in the manifest list entries
```

I have been trying and searching for issues on my end for hours now and I cannot figure out why I am not able to pull, because to my understanding, the provided arm64 Image should work on a arm/v8 raspberry pi.

Do you guys have any idea what the problem might be? Thanks alot for the help and I am really looking forward to start using this awesome app at home!

### Deployment

Docker (Linux)

### Deployment Details

Here some CPU diagnostics:
```
❯ cat /proc/cpuinfo
processor	: 0
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 1
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 2
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 3
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

Hardware	: BCM2835
Revision	: b03115
Serial		: 10000000f6210b40
Model		: Raspberry Pi 4 Model B Rev 1.5
```
```
❯ uname -a
Linux server 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
```

### Mealie Version

v0.5.6

**Comment by boc-the-git** [comment]
@TadeSF, is this something that can be replicated with either the nightly or RC1.1 images? We should be building an ARM64 image, per here: https://github.com/mealie-recipes/mealie/blob/mealie-next/.github/workflows/partial-builder.yml#L44C22-L44C45
(I'm not certain if the same was in place for the older docker hub images)

**Comment by MaikuMori** [comment]
I don't think there is a `latest` tag which is the actual bug here. Having a `latest` tag is a very common convention and in this case the RC1 image should be tagged also as `latest`.

**Comment by Strehk** [comment]
@boc-the-git Hmm, unfortunatly, I switched from Raspberry Pi OS to an ubuntu server some weeks ago, since I ran into the same issue with other open source software as well. That being said, I don't really have a way of testing your proposal.

You may close the Issue for me – unless, you want to investigate what the problem is in general ;)
Thanks anyways for your help!

**Comment by boc-the-git** [comment]
Will close now and someone can reopen in future with more info if needed.
