### ISSUE TITLE
[v1.0.0b] - Recipe is printed only on half page

### ISSUE THREAD

**Issue by ZvikaZ** [mealie-recipes/mealie#2469]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When I print my recipe (as PDF) it's printed over two pages, each one of them taking only half of the page's width.
The recipe's .json (zipped) is attached.
[rvglk-shl-tl.zip](https://github.com/hay-kot/mealie/files/12184230/rvglk-shl-tl.zip)

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Can you post a picture of what the recipe looks like when printed? Or attach the PDF if you can.
If posting a picture, can you tell me what the paper size is?

**Comment by ZvikaZ** [comment]
Here's the PDF:
[רוגלך (של טל).pdf](https://github.com/mealie-recipes/mealie/files/12358204/default.pdf)

**Comment by michael-genson** [comment]
Ah I see, I'm guessing this is related to https://github.com/mealie-recipes/mealie/issues/2452 and the spacing isn't being interpreted correctly which is messing up the formatting. Once we get that sorted we can see if this is fixed

**Comment by michael-genson** [comment]
This will _probably_ be fixed by https://github.com/mealie-recipes/mealie/pull/2832. Once that gets merged, if you could test with your recipe(s) that would be great. If it's not fixed, feel free to re-open (this issue will auto-close when https://github.com/mealie-recipes/mealie/pull/2832 is merged)
