### ISSUE TITLE
[v1.0.0 - Nightly] - Images/img src block in Steps does not save

### ISSUE THREAD

**Issue by BonzTM** [mealie-recipes/mealie#2473]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Images, when dragged/attached to a step (img src block html/markdown) and the `Save` button is clicked, does not trigger a `PUT`+`GET` request to the API.  Only a single `GET` request is triggered when clicking `Save`, causing the loss of any changes to the recipe.

I would imagine this is any HTML 

![image](https://github.com/hay-kot/mealie/assets/514931/846f3402-cbaf-427f-9080-0d5f9421c754)

### Deployment

Docker (Linux), Other

### Deployment Details

Deployed in OpenShift/OKD/K8s, using the nightly image from Dockerhub and backed by SQLite.

**Comment by michael-genson** [comment]
I can't reproduce this on the demo (which uses the nightly version); are you still seeing this issue on the latest nightly build?
![ezgif-5-2f119d0a09](https://github.com/mealie-recipes/mealie/assets/71845777/c5a39958-2aa7-43e1-89fc-8fe34fc9e256)

**Comment by BonzTM** [comment]
I am still seeing the issue on the nightly (container frontend/backend images, not unified image).  I'm going to continue to troubleshoot.  Is there a suggestion on appropriate procedure to back everything up, start fresh and re-import?

**Comment by hay-kot** [comment]
What browser are you using?

**Comment by BonzTM** [comment]
> What browser are you using?

I have used Edge, Firefox, Chrome, Brave.  It appears after I re-built mealie from the ground up (w/ postgres) and imported my save, my existing attachments are borked but new ones appear good.  I'm not sure if it was something with my install (k8s) or db related (sqlite) with the initial attachments.
