### ISSUE TITLE
[v1.0.0b] - Broken Image On Test Email

### ISSUE THREAD

**Issue by michael-genson** [mealie-recipes/mealie#2480]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

The test email (`/admin/site-settings` and click "test") contains a .png that links to an insecure site, which most browsers/email clients won't render:

https://github.com/hay-kot/mealie/blob/e71155a55d34267bb8acb33758d5cfec350bff4c/mealie/services/email/templates/default.html#L215

(`https://api-test.emailbuilder.top/saemailbuilder/dc23dc82-ffd7-4f4c-b563-94f23db4c2c3/images/256d8bd6-ffde-4bf2-b577-dd8306dae877/file.png`)

This should be hosted somewhere else, maybe on GitHub, or on the Mealie instance (and made publicly accessible) 
[image file](https://github.com/hay-kot/mealie/files/12268639/file.zip)

### Deployment

Docker (Synology)

**Comment by ceminess** [comment]
Thank you for opening this!  I noticed this is happening for all my mealie emails.  Not sure if it that matters, I assume all emails are referencing the same image.

**Comment by michael-genson** [comment]
Yeah good point, I think all emails reference that template
