### ISSUE TITLE
Nightly build failing to import tandoor export correctly

### ISSUE THREAD

**Issue by qanadin** [mealie-recipes/mealie#2486]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

When importing from Tandoor, the image that was exported from Tandoor, is not being imported by Mealie.  

### Steps to Reproduce

1. Export from Tandoor
2. Import into Mealie

### Please provide relevent logs

Logs reported as successful

### Mealie Version

Nightly

### Deployment

Docker (Linux)

**Comment by qanadin** [comment]
[export_2023-08-07.zip](https://github.com/mealie-recipes/mealie/files/12282103/export_2023-08-07.zip)
Here is the export I used

**Comment by michael-genson** [comment]
Thanks! I have a fix incoming, but if you want to get a head start prior to the PR/merge, I have a fixed file for you:
[export_2023-08-07.zip](https://github.com/mealie-recipes/mealie/files/12282607/export_2023-08-07.zip)

Looks like a few of them still didn't work with that modified file, but most of them worked:
![image](https://github.com/mealie-recipes/mealie/assets/71845777/fbb13b74-b5eb-4c45-a30a-7dcce707959a)

Once I get the PR in it should work for all of them, as long as they're valid images

**Comment by michael-genson** [comment]
Actually it looks like the missing ones just don't have image files, so I think this gets them all!
