### ISSUE TITLE
Tag import not working when "stay in edit mode"

### ISSUE THREAD

**Issue by qanadin** [mealie-recipes/mealie#2488]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

Tags aren't showing up when importing a recipe via url while in stay in edit mode

### Steps to Reproduce

1. Import via URL
2. https://www.dinneratthezoo.com/slow-cooker-chicken-tortilla-soup/
3. Select import original keywords as tags
4. Select Stay in edit mode
5. import

### Please provide relevent logs

N/A (Let me know where they can be pulled and I will)

### Mealie Version

Nightly

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Just to clarify - are you saying it's not working at all, or _only_ when using "stay in edit mode"?

**Comment by qanadin** [comment]
Yes, my apologies.  When I don't check that box, it will import the tags just fine.  The URL is an example, and it was able to duplicate this in the demo.

**Comment by qanadin** [comment]
So, it isn't just when in stay in edit mode.  I came across this recipe:

https://recipe.zenists.com/recipe/anything-you-have-coconut-curry-soup

It showed the tags, but when you edit the tags aren't shown.  They appear if you add the tag soup to it.

**Comment by pendraggon87** [comment]
I will note that when I don't check the box, the tags will show up in the UI, but it doesn't seem to create them properly - clicking the tag takes you to a 404 page

**Comment by michael-genson** [comment]
I looked into this more, it's a bit more subtle. It's actually working fine on the backend, but however the frontend is pre-populating the tag list isn't working for the new tags.

To see what I mean, try adding a recipe by URL that creates new tags (and notice that they're missing). Then hard refresh the page and you'll see they're there and they work fine.

**Comment by pendraggon87** [comment]
I see the tags showing up, but I do get a 404 error when I click on one of the tags.
