### ISSUE TITLE
Not a bug - Themes 

### ISSUE THREAD

**Issue by Readus-01** [mealie-recipes/mealie#2509]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

have the theme and colour changes been removed from the latest version as the ability to do this, i can not find.
the app is working perfectly but i also cannot add recipes to categories 

### Steps to Reproduce

docker build using portainer

### Please provide relevent logs

none

### Mealie Version

1.0 beta 5

### Deployment

Docker (Synology)

### Additional Deployment Details

docker - portainer on synology

**Comment by hay-kot** [comment]
Theming has moved to by instance configuration for the sake of developer simplicity

See https://nightly.mealie.io/documentation/getting-started/installation/frontend-config/#themeing

Though, I'm not sure a lot of users are using it so it worked last time i checked, so please report any bugs you find!
