### ISSUE TITLE
[BUG] - Ingredients on 3 lines instead of one since latest update

### ISSUE THREAD

**Issue by gravelfreeman** [mealie-recipes/mealie#2522]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

Since yesterday update, ingredients appears on 3 lines instead of one on all recipes page.

![image](https://github.com/mealie-recipes/mealie/assets/44218371/3cb1154e-e989-4c57-bffc-08009a07a778)

### Steps to Reproduce

Update to latest version.

### Please provide relevent logs

No relevant logs in pod logs.

### Mealie Version

 693608d59fd1cd9f474108bd74576cd6c82b2dac 

### Deployment

Docker (Linux)

### Additional Deployment Details

TrueCharts catalog on TrueNAS (kubernetes)

**Comment by michael-genson** [comment]
Is this fixed in the newest nightly? See: https://github.com/mealie-recipes/mealie/pull/2521

**Comment by gravelfreeman** [comment]
Yes fixed thank you, you guys rock!
