### ISSUE TITLE
[BUG] - Can't increase ingredients quantities

### ISSUE THREAD

**Issue by gravelfreeman** [mealie-recipes/mealie#2523]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

Since latest update can't increase ingredient quantities on any recipe.

Quantity before

![image](https://github.com/mealie-recipes/mealie/assets/44218371/d3a8fd29-abda-4048-adf6-bce3968e843e)

Quantity after

![image](https://github.com/mealie-recipes/mealie/assets/44218371/a1740a32-8e95-49d2-bac7-a0aee6f8e85b)

As you can see it stayed the same.

### Steps to Reproduce

Press [+] button on quantity on a recipe.

### Please provide relevent logs

No relevant logs

### Mealie Version

 693608d59fd1cd9f474108bd74576cd6c82b2dac 

### Deployment

Docker (Linux)

### Additional Deployment Details

TrueCharts catalog on TrueNAS (kubernetes)

**Comment by michael-genson** [comment]
This is a known issue, please see https://github.com/mealie-recipes/mealie/pull/2520
