### ISSUE TITLE
[BUG] - Copy ingredients includes html tags for <sup><sub>

### ISSUE THREAD

**Issue by coffee-mage** [mealie-recipes/mealie#2531]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

On my instance, 1.5 measurement ingredients show up as 1 1/2 (with special html formatting).   When i hit the copy ingredients button, it includes the sup/sub tags in the copied text:

3 cup bread crumbs dried
3 tablespoon cornmeal
3 tablespoon corn starch
1 tablespoon onion powder granulated
1 <sup>1</sup>⁄<sub>2</sub> teaspoon garlic powder granulated
1 teaspoon black pepper
1 tablespoon salt
1 <sup>1</sup>⁄<sub>2</sub> teaspoon chili powder
1 teaspoon thyme (dried)
1 <sup>1</sup>⁄<sub>2</sub> teaspoon oregano

I tested on the demo site, and for some reason it displays the ingredients (on the webpage) as 1.5 instead of 1 1/2.  So when I copy those ingredients, the issue doesn't exist.

### Steps to Reproduce

Have ingredients that are displays in ingredients window as 1 1/2.  
Hit the copy ingredients button,  paste into notepad.

### Please provide relevent logs

None

### Mealie Version

omni-nightly

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
The HTML tags are intended (they format the fraction to make it look nice) but I agree, they shouldn't be in the copy text
