### ISSUE TITLE
[BUG] - Creating recipe, must save/exit before you can parse ingredients.

### ISSUE THREAD

**Issue by coffee-mage** [mealie-recipes/mealie#2532]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

When creating recipe, must exit the recipe and go back in before I can parse the ingredients.  

### Steps to Reproduce

1) Create recipe
2) Delete flour
3) Paste ingredients in bulk
4) Hit save
5) Enable ingredient amounts in settings
6) Hit parse
7) Site will pop up dialog box saving you have unsaved ingredients, and you must hit okay to proceed.
8) Hit okay.   Only flour appears in the parse list.
9) If I exit out of the recipe, and go back in (hit edit),  and then parse.  Everything works as expected.

It's almost like the Ok button saves the recipe on the website,  but my memory isn't up to date.

### Please provide relevent logs

None

### Mealie Version

[408ca88cb2013210d3a3bfee26a16bf47195915a](https://github.com/hay-kot/mealie/commit/408ca88cb2013210d3a3bfee26a16bf47195915a)

Demo-nightly.

### Deployment

Other

**Comment by regularguy01** [comment]
The FAQ shows this https://nightly.mealie.io/documentation/getting-started/faq/#set-up-recipes-to-use-foods-and-units

Is that how you did it?

Main link https://nightly.mealie.io/documentation/getting-started/faq/#how-do-i-enable-smart-ingredient-handling

**Comment by coffee-mage** [comment]
Hi regular,
Yes I do have my system set up to use food and ingredients, and it works as long as the new recipes is already saved before I try to parse.

Just as a double check, I also tried the demo site?  I presume that was set up to use ingredients?  Again it works as long as the recipe ingredients text is saved before I try to parse.

**Comment by regularguy01** [comment]
> it works as long as the new recipes is already saved

I guess what I mean isn't saving part of the documented process.  

From the LInk:
Do the following for each recipe you want to intelligently handle ingredients.
    Go to a recipe
    Click the Edit button/icon
    Click the Recipe Settings gear and deselect Disable Ingredient Amounts
    Save
    The ingredients should now look a little weird (1 1 cup broth and so on)
    Click the Edit button/icon again
    Scroll to the ingredients and you should see new fields for Amount, Unit, Food, and Note. The Note in particular will contain the original text of the Recipe.
    Click Parse and you will be taken to the ingredient parsing page.
    Choose your parser. the Natural Language Parser works very well, but you can also use the Brute Parser.
    Click Parse All and your ingredients should be separated out into Units and Foods based on your seeding in Step 1 above.
    For ingredients where the Unit or Food were not found, you can click a button to accept an automatically suggested Food to add to the database. Or manually enter the Unit/Food and hit Enter (or click Create) to add it to the database
    When done, click Save All and you will be taken back to the recipe. Now the Unit and Food fields of the recipe should be filled out.

**Comment by coffee-mage** [comment]
Hi Regular,
I think the disconnect is that i'm trying to do the parsing when I create the recipe.  Your instructions are covering the use case of an existing recipe that you want to parse.

If you tell me that parsing recipes on creation is not supported, and I should only parse existing recipes.  I can close the ticket.

But I wanted to flag that the workflow for parsing recipes on creation, is not ideal.

**Comment by hay-kot** [comment]
@braddillon - The recipe must be saved before trying to parse ingredients. If you click parse with unsaved changes, you should be prompted to save your changes before navigating away, is that happening?

**Comment by JvdMaat** [comment]
> If you click parse with unsaved changes, you should be prompted to save your changes before navigating away, is that happening?

No. (from recent omni-nightly experience). It does pop up with a browser notice saying it needs to be saved. But clicking OK does not actually execute a save.

**Comment by coffee-mage** [comment]
I have the same experience as jvdmaat.

**Comment by jtruland** [comment]
Sorry to jump on an old thread.  I'm just starting to use this, and it does prompt for save before taking me to the parsing, however, it feels like the UI could be adjusted to make this less of an issue.

- Don't exit edit mode when pressing Save. 
- Either add a second Save and Close button or prompt for Save or Discard on pressing the Close button (maybe change this to "Done"?)

**Comment by ekcom** [comment]
> It does pop up with a browser notice saying it needs to be saved. But clicking OK does not actually execute a save.

This issue persists and is still reproducible on the demo site.

I suspect that this is a race condition issue as the parser loads without the saved changes, but navigating back shows the updated ingredient list. (Refreshing the page on the parser tool also will get the newly saved ingredients populated.)
