### ISSUE TITLE
[BUG] - Star Rating cant remove all stars

### ISSUE THREAD

**Issue by regularguy01** [mealie-recipes/mealie#2534]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

You can add stars and update stars.  
![Screen Shot 2023-08-31 at 09 30 35](https://github.com/mealie-recipes/mealie/assets/22330436/5566e71f-2ae7-44b3-8630-67c2eb301569)
![Screen Shot 2023-08-31 at 09 30 52](https://github.com/mealie-recipes/mealie/assets/22330436/fc9371b7-3c69-4782-a855-b6b37ce71bf2)
![Screen Shot 2023-08-31 at 11 22 30](https://github.com/mealie-recipes/mealie/assets/22330436/e1ff3f15-e65d-46e4-9f44-6b614f0aa405)
![Screen Shot 2023-08-31 at 09 34 58](https://github.com/mealie-recipes/mealie/assets/22330436/d68b72c9-27d1-46b4-b92b-d9b630d9c01d)
 
You can not remove all stars.  If you give it a one Star you cannot remove it.  Unless you go in the JSON file and delete the RATING line from the file.  Then save and refresh the browser. 

### Steps to Reproduce

Pick any recipe give it one star.
The click the same star to remove 
nothing happens.

I also don't see an X or anything that has a tool-tip click to remove all stars.

### Please provide relevent logs

none found.

### Mealie Version

Version
nightly
Build
408ca88cb2013210d3a3bfee26a16bf47195915a
DB Postgres

### Deployment

Docker (Linux)

**Comment by regularguy01** [comment]
Some of the SS are from Beta5 switched to Nightly just to see if it was fixed there.  

If you need more info just let me know.

**Comment by JvdMaat** [comment]
Can confirm this. I don't use ratings and due to some lag accidentally clicked on a star, and now I have one recipe that is rated, and I can't remove it.
(We've talked about this in discord. Ratings are currently also per group, not per user. So if you rate a recipe 5 stars, and another user then rates it 2 stars, it will be 2 stars, not the average of your two ratings) Relevant conversation starts here: https://discord.com/channels/795445547577770014/795489645227671584/1140644629625196627

**Comment by regularguy01** [comment]
"I can't remove it."

Workaround:

Go to the Recipe.  Click Edit.  Choose JSON.
Scroll through the file look for "rating"
Delete the entire line.
Also pay attention to the commas at the end if you need it.
Then Save 
Then refresh the Browser.
Star should be gone.

I dont have discord.

**Comment by JvdMaat** [comment]
> Go to the Recipe. Click Edit. Choose JSON. 

Awesome! That got rid of that rating.

> I dont have discord.

We basically briefly discussed how ratings were not removable, and how they were stored as part of the recipe for the group, not as individual user's ratings. But there was no ultimate action on any of it.

**Comment by regularguy01** [comment]
Glad that work around helped.

I am just going by if I can add rating I should be able to remove ratings.  Maybe like you I added 1 star to test.  Now I need a remove stars X or something.
