### ISSUE TITLE
[BUG] - ARM postgres broken again (repeat of #1243)

### ISSUE THREAD

**Issue by disconn3ct** [mealie-recipes/mealie#2542]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

The postgresql incompatibility error is back, preventing Mealie from connecting

### Steps to Reproduce

Run the docker ARM64 container with postgresql

### Please provide relevent logs

mealie-beta-f87d677f7-gkfbr mealie-api ERROR: 10-Sep-23 09:58:00        Database connection failed. Retrying in 1 seconds...
mealie-beta-f87d677f7-gkfbr mealie-api ERROR: 10-Sep-23 09:58:01        Error connecting to database: (psycopg2.OperationalError) SCRAM authentication requires libpq version 10 or above
mealie-beta-f87d677f7-gkfbr mealie-api 
mealie-beta-f87d677f7-gkfbr mealie-api (Background on this error at: https://sqlalche.me/e/14/e3q8)
mealie-beta-f87d677f7-gkfbr mealie-api ERROR: 10-Sep-23 09:58:01        Database connection failed. Retrying in 1 seconds...
mealie-beta-f87d677f7-gkfbr mealie-api Traceback (most recent call last):
mealie-beta-f87d677f7-gkfbr mealie-api   File "/app/mealie/db/init_db.py", line 107, in <module>
mealie-beta-f87d677f7-gkfbr mealie-api     main()
mealie-beta-f87d677f7-gkfbr mealie-api   File "/app/mealie/db/init_db.py", line 86, in main
mealie-beta-f87d677f7-gkfbr mealie-api     raise ConnectionError("Database connection failed - exiting application.")
mealie-beta-f87d677f7-gkfbr mealie-api ConnectionError: Database connection failed - exiting application.

### Mealie Version

api-v1.0.0beta-5

### Deployment

Docker (Linux)

### Additional Deployment Details

K3S cluster on Arm. The alternate installation using sqlite is still working. 
This is a fresh install, and the DB settings are configured via environment and k8s secrets.

**Comment by boc-the-git** [comment]
@disconn3ct, is this something that can be replicated on either the nightly or RC1.1 images? Can you please share the scripts used?
I'm not across the finer details of k3s as opposed to Docker, so my ability to help may be limited.

**Comment by disconn3ct** [comment]
Sorry, I think I missed the notification. Nightly is working fine.

**Comment by boc-the-git** [comment]
Awesome! I'll close this as resolved.
