### ISSUE TITLE
[BUG] - LDAP library missing in beta5 (arm64 and x86)

### ISSUE THREAD

**Issue by disconn3ct** [mealie-recipes/mealie#2544]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

The ldap library appears to be missing from the docker image. Tested on arm and x64.

```
LDAP_AUTH_ENABLED: "true"
LDAP_SERVER_URL: "ldap://localhost:389/"
LDAP_BIND_TEMPLATE: "cn={},ou=users,dc=foo,dc=com"
``` 
results in:
`ImportError: libldap_r-2.4.so.2: cannot open shared object file: No such file or directory`

### Steps to Reproduce

1) Using the example compose, add `LDAP_AUTH_ENABLED="true"` `LDAP_SERVER_URL="localhost:389"` `LDAP_BIND_TEMPLATE="cn={},ou=users,dc=foo,dc=com"`
2) docker-compose up
3) Attempt to log in.

The specific values do not matter, but it does not load LDAP until a login is attempted.

### Please provide relevent logs

ARM (helm):
```
mealie-beta-666b66fb65-fgw7d mealie-api   File "/app/./mealie/core/security/security.py", line 120, in authenticate_user
mealie-beta-666b66fb65-fgw7d mealie-api     return user_from_ldap(db, email, password)
mealie-beta-666b66fb65-fgw7d mealie-api   File "/app/./mealie/core/security/security.py", line 51, in user_from_ldap
mealie-beta-666b66fb65-fgw7d mealie-api     import ldap
mealie-beta-666b66fb65-fgw7d mealie-api   File "/opt/pysetup/.venv/lib/python3.10/site-packages/ldap/__init__.py", line 34, in <module>
mealie-beta-666b66fb65-fgw7d mealie-api     import _ldap
mealie-beta-666b66fb65-fgw7d mealie-api ImportError: libldap_r-2.4.so.2: cannot open shared object file: No such file or directory
```

X86 (compose):
```
mealie-api         |     return user_from_ldap(db, email, password)
mealie-api         |   File "/app/./mealie/core/security/security.py", line 51, in user_from_ldap
mealie-api         |     import ldap
mealie-api         |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/ldap/__init__.py", line 34, in <module>
mealie-api         |     import _ldap
mealie-api         | ImportError: libldap_r-2.4.so.2: cannot open shared object file: No such file or directory
```

### Mealie Version

api-v1.0.0beta-5

### Deployment

Docker (Linux), Other

**Comment by michael-genson** [comment]
I believe this is fixed in nightly. Can you try pulling the latest nightly and see if you're having the same issues?

**Comment by disconn3ct** [comment]
Nightly ran great!
