### ISSUE TITLE
[SCRAPER] - Importing Gousto recipes is missing image and total time.

### ISSUE THREAD

**Issue by daniel-tp** [mealie-recipes/mealie#2547]
### First Check

- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have verified that this issue _is not_ related to the underlying library
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers) by **1)** checking
the [debugger](https://demo.mealie.io/recipe/create/debug) and data is returned, **2)**
verifying that there _are_ errors in the log related to application level code, or
**3)** verified that the site provides recipe data, or is otherwise supported by
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers)

- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### Please provide 1-5 example URLs that are having errors

https://www.gousto.co.uk/cookbook/pork-recipes/crispy-pork-belly-noodle-ramen
https://www.gousto.co.uk/cookbook/recipes/oven-baked-sweet-sesame-chicken-breast-with-hoisin-rice

### Please provide your logs for the Mealie container `docker logs <container-id> > mealie.logs`

```
    responses: list[Response] = await gather_with_concurrency(10, *tasks)
  File "/app/mealie/services/recipe/recipe_data_service.py", line 22, in gather_with_concurrency
    return await asyncio.gather(*(sem_coro(c) for c in coros))
  File "/app/mealie/services/recipe/recipe_data_service.py", line 20, in sem_coro
    return await coro
  File "/app/mealie/services/recipe/recipe_data_service.py", line 30, in do
    return await client.head(url, headers={"User-Agent": _FIREFOX_UA})
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1815, in head
    return await self.request(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
INFO:     127.0.0.1:40958 - "POST /api/recipes/create-url HTTP/1.1" 201 Created
INFO:     127.0.0.1:40964 - "GET /api/recipes/crispy-pork-belly-noodle-ramen-1 HTTP/1.1" 200 OK
INFO:     127.0.0.1:40978 - "GET /api/media/recipes/67831ea2-e7b2-48fa-a04e-45194e876dbf/images/original.webp?rnd=1&version=no%20image HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:40986 - "GET /api/recipes/crispy-pork-belly-noodle-ramen-1/comments HTTP/1.1" 200 OK
INFO:     127.0.0.1:40990 - "GET /api/media/recipes/67831ea2-e7b2-48fa-a04e-45194e876dbf/images/original.webp?rnd=1&version=no%20image HTTP/1.1" 404 Not Found
```

### Deployment

Docker (Linux)

**Comment by daniel-tp** [comment]
I have checked that recipe-scraper returns valid images and total time for the version Mealie uses. It seems to be failing in `clean_scraper`, as checking the output of recipe scraper before that returns expected values.

Description is also missing, but this is not present in the version of recipe-scraper that mealie uses. I have contributed a fix for that in  https://github.com/hhursev/recipe-scrapers/pull/853

**Comment by jayaddison** [comment]
This is a guess: could the problem here relate to retrieval of images that use a relative URL scheme (`src="images/foo.png"` or similar)?

That could explain the missing-protocol error from `httpx`.

If so: [there's a way to provide a `base_url` argument to `AsyncClient`](https://www.python-httpx.org/api/#asyncclient), so it might be possible to provide the (post-redirect, ideally) URL of the recipe to the client.

**Comment by daniel-tp** [comment]
The gousto scraper from recipe-scraper returns an image in this format: https://s3-eu-west-1.amazonaws.com/s3-gousto-production-media/cms/mood-image/854---CrispyPorkBellyAndNoodleRamen_AltChopstick_HERO_Diffused-1606823593145.jpg

There is a protocol error, because clean_scraper in Mealie seems to fail to get this image from recipe-scraper (though it is is there if you use image()) and instead returns "No Image" (which has no protocol, haha).

From a brief look clean_scraper tries to get the attribute "image" (`image=try_get_default(None, "image", None, cleaner.clean_image),`) via .schema.data.get("image") of recipe-scraper and fails. If you use recipe-scrapers .image() function here, it gets the image successfully. 

Maybe schema.data.get("image") isn't supported for some recipes in recipe-scraper?

**Comment by jayaddison** [comment]
Ok, interesting.  And `clean_image` uses some structural pattern matching (nice!) to handle and extract URLs from different types of `image` object:

https://github.com/mealie-recipes/mealie/blob/e28b830cd41c78efa05d17f66799b3a300b38cb4/mealie/services/scraper/cleaner.py#L101-L111

> Maybe schema.data.get("image") isn't supported for some recipes in recipe-scraper?

Could be.  Maybe the fact that there is an array access (`[0]`) on the value here: https://github.com/mealie-recipes/mealie/blob/e28b830cd41c78efa05d17f66799b3a300b38cb4/mealie/services/scraper/cleaner.py#L50

Could that mean that the value `h` becomes the image URL for the recipe?  `recipe-scrapers` [doesn't declare a return value type hint in v14.42.0 for that field](https://github.com/hhursev/recipe-scrapers/blob/1eb6528babe9aa0c232cf23d2beaeaba07e87995/recipe_scrapers/_abstract.py#L97) but my understanding is that it's usually a single `str`, not `list[str]`.

**Comment by jayaddison** [comment]
> Could that mean that the value `h` becomes the image URL for the recipe? `recipe-scrapers` [doesn't declare a return value type hint in v14.42.0 for that field](https://github.com/hhursev/recipe-scrapers/blob/1eb6528babe9aa0c232cf23d2beaeaba07e87995/recipe_scrapers/_abstract.py#L97) but my understanding is that it's usually a single `str`, not `list[str]`.

Sorry, I think this theory is wrong.  The array access is on the output of `clean_image`, and [_that_ method does declare that it returns `list[str]`](https://github.com/mealie-recipes/mealie/blob/e28b830cd41c78efa05d17f66799b3a300b38cb4/mealie/services/scraper/cleaner.py#L82).

**Comment by jayaddison** [comment]
> Maybe schema.data.get("image") isn't supported for some recipes in recipe-scraper?

Yep, I should have followed your line of thinking here: I think that is correct.

```pyi
>>> from recipe_scrapers import scrape_me
>>> s = scrape_me('https://www.gousto.co.uk/cookbook/pork-recipes/crispy-pork-belly-noodle-ramen')
>>> s.image()
'https://s3-eu-west-1.amazonaws.com/s3-gousto-production-media/cms/mood-image/854---CrispyPorkBellyAndNoodleRamen_AltChopstick_HERO_Diffused-1606823593145.jpg'
>>> s.data.get('image')  # None
>>> 
```

**Comment by jayaddison** [comment]
OK, there's some plugin magic going on here, I think.  :magic_wand: 

The same URL, this time with [debug logging](https://github.com/hhursev/recipe-scrapers/blob/1eb6528babe9aa0c232cf23d2beaeaba07e87995/recipe_scrapers/settings/default.py#L46) enabled:

```pyi
>>> from recipe_scrapers import scrape_me
>>> s = scrape_me('https://www.gousto.co.uk/cookbook/pork-recipes/crispy-pork-belly-noodle-ramen')
>>> s.image()
DEBUG:recipe_scrapers.plugins.opengraph_image_fetch:Decorating: GoustoJson.image() with OpenGraphImageFetchPlugin
DEBUG:recipe_scrapers.plugins.schemaorg_fill:Decorating: GoustoJson.image() with SchemaOrgFillPlugin
'https://s3-eu-west-1.amazonaws.com/s3-gousto-production-media/cms/mood-image/854---CrispyPorkBellyAndNoodleRamen_AltChopstick_HERO_Diffused-1606823593145.jpg'
```

So I think the `image()` call's result is being completed by this plugin: https://github.com/hhursev/recipe-scrapers/blob/1eb6528babe9aa0c232cf23d2beaeaba07e87995/recipe_scrapers/plugins/opengraph_image_fetch.py

... and that plugin _doesn't_ populate the `scraper.data` dictionary's image key.

**Comment by daniel-tp** [comment]
The gousto image call in recipe-scraper shouldn't be failing as far as I can see, so I'm confused why opengraph_image_fetch is stepping in?

**Comment by jayaddison** [comment]
@daniel-tp `opengraph_image_fetch` only runs if `scraper.image()` is called, whereas `mealie` currently accesses `scraper.data.get("image")` -- and that value is `None`/empty for these recipes, as far as I can tell.

**Comment by jayaddison** [comment]
I'm finding it slightly confusing, but I think it's intentional that Mealie _doesn't_ call `scraper.image()` any more -- because that method can only return a single result.  That was changed with #745 where the ability to pick from multiple images for display was implemented.

I also don't have a local Mealie developer environment set up, so it's a little tricky for me to test changes at the moment.  I'll do some reading to figure that out.

**Comment by jayaddison** [comment]
Note: if multi-image results from `recipe-scrapers` would be useful in future, then I think that hhursev/recipe-scrapers#307 is the place to build some more support and discussion for that.

**Comment by cadamswaite** [comment]
Hi guys, yeah I removed the call from "scraper.image()" in that MR a while back

What that function would [normally do](https://github.com/hhursev/recipe-scrapers/blob/e0faf0cbfa6c27a0191beae4e04bd76902a547a2/recipe_scrapers/gousto.py#L20) is:
```python
    def image(self):
        return self.schema.image()
```

which would [grab the first image](https://github.com/hhursev/recipe-scrapers/blob/e0faf0cbfa6c27a0191beae4e04bd76902a547a2/recipe_scrapers/_schemaorg.py#L149) (hence #745, which would instead grab the best image )
```python
        if isinstance(image, list):
            # Could contain a dict
            image = image[0]
```

This was then broken by https://github.com/hhursev/recipe-scrapers/issues/376: since gusto are making it harder to scrape they had to use a different method to get the image. In this case the schema (including the list of images) is not populated.


ITT best solution would be to move the best image selection step from #745 into recipe-scrapers then:
- everyone downstream of that tool would benefit from prettier images
- we could revert #745 and use the standard functions provided by recipe-scrapers here
-- we would benefit from any custom behaviours implemented - so changes like this gusto API would not effect us

The only downside is that it would take some time (assuming it was accepted), since would require both to bump releases


Does someone have the time to put together an MR for recipe-scrapers?

cheers

**Comment by jayaddison** [comment]
Thanks for providing the history @cadamswaite.  I tentatively agree, and I think we should file an issue in `recipe-scrapers` to track this.  One thought and one request from me:

* The best-image-evaluation logic requires making network requests to download the images listed on the page.  Should those requests be made when the page is scraped, or only when the `image` method is called -- or perhaps be configurable?

* As someone who is both a maintainer of `recipe-scrapers` and also a consumer of the library (maybe a conflict-of-interest here), in my use case (a web crawler) I'd like _not_ to download images, even if it means slightly poorer-quality image URLs, and would still to be able to call the `image` and `to_json` methods.  I think that means I'd like to suggest a `settings` value or environment variable to skip the best-image-evaluation process.  The reason for that is that I want to minimize traffic and bandwidth costs (especially for potentially large content such as images) for recipe websites.

I think my use-case is in the minority; most people are using `recipe-scrapers` as part of local recipe gathering, where they only scrape a few URLs and where a better-quality representation of a small number of recipes is preferable to minimizing bandwidth for a large number of recipes.

**Comment by jayaddison** [comment]
(and to actually answer your question: yep, I think I could offer some time to code this up.  some discussion time could be good first to see what other folks think about the approach)

**Comment by cadamswaite** [comment]
@jayaddison you're totally right, `.image()` should be kept lightweight for usecases like yours

We could extend the api (backwards compatible) with something like `.best_image()` that would try to get the best image using fetches and fall back on `self.image()` if it fails

That would allow for custom implementations of `best_image` for websites like gusto too

**Comment by jayaddison** [comment]
Thanks @cadamswaite - I think I'd see it as a case where the interface should stay the same - the `.image()` method is a well-named and unambiguous interface for the caller to use -- but we want something like a behaviour modifier/plugin/mixin (although maybe not _literally_ a mixin) that upgrades the behaviour at the expense of additional network traffic.  And it's OK for that to be the default.

**Comment by Dusty-Meg** [comment]
Hate just bumping for bumping, but is there any potential progress on this?

**Comment by daniel-tp** [comment]
I think with the lack of Issues made in the recipe scraper, this might be currently dead in the water.
