### ISSUE TITLE
[BUG] - Unexpected behavior of the "Show Nutrition Information" option in Group settings

### ISSUE THREAD

**Issue by JeremyTheMiner** [mealie-recipes/mealie#2552]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

"Show Nutrition Information" option on the Group page does not toggle whether or not nutrition information is shown.  Instead, it seems to toggle whether or not the nutrition information (when available) is IMPORTED.  Recipes imported with the checkbox empty will never show nutrition, while recipes imported with the checkbox checked will ALWAYS show nutrition information, regardless of the later state of that checkbox.

See https://www.youtube.com/watch?v=eS9FmTnPoEE for a full demonstration of the issue.

### Steps to Reproduce

Steps outlined in YouTube video linked in issue description.

### Please provide relevent logs

Nothing relevant found in mealie.log

### Mealie Version

v1.0.0beta-5

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
I think you're just misunderstanding the effects of the Group Settings. They are defaults that are applied to recipes at **creation** time. So if you have it set to not show nutrition values they will still be imported, but they aren't show. 

After creating a recipe you can change the recipe settings to anything you want

<img width="631" alt="CleanShot 2023-09-15 at 13 04 32@2x" src="https://github.com/mealie-recipes/mealie/assets/64056131/8a95ba65-9a0e-4199-ad49-a192b8b79306">

If you go to each of the recipes that you've imported and you toggle the show nutrition values in the recipes settings they should be there on both times you imported. I was able to do that on the demo site.

**Comment by JeremyTheMiner** [comment]
You're 100% correct, I misunderstood.  I totally overlooked the writeup explaining the Default Recipe Preferences section.  Reading the settings explains the settings...
