### ISSUE TITLE
[BUG] - Administrator flag for LDAP user can't be saved

### ISSUE THREAD

**Issue by Smile1975** [mealie-recipes/mealie#2554]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

I'm using LDAP authentification. When switching my user from mealie authentification to ldap authentification, then activating the administrator flag, saving the settings and log of, after login with this LDAP user the user has no admin rights.
When I log off the LDAP user and logging in with an administrativ user with mealie authentification and looking for the LDAP User I have activated the admin flag, the flag is no longer ativated.
This can be reproduced. It is not possible to activate to administrator flag for an user with LDAP authentification.

### Steps to Reproduce

1) Set LDAP Settings in Docker-Compose.yml
2) Logging in with a LDAP user
3) Log off
4) Log in with a administrativ user with mealie authentification
5) Go to Users and select the LDAP user.
6) Set the administrator flag and save this setting.
7) Log off
8) Log on with LDAP User
9) Go to users an open the LDAP user. The administrator flag ist deactivated. 

### Please provide relevent logs

**Details**
Version: nightly
Build: 0a00a6ea0d05d2dd944dd9cc6713156dc767e1ed
Anwendungsmodus: Produktivumgebung
Demostatus: Keine Demo
API-Port: 9000
API Dokumentation: Aktiviert
Datenbanktyp: sqlite
Rezept Scraper Version: 14.42.0

**Checks**
Sichere Website: Yes
Serverseitige Basis-URL: Yes
LDAP bereit: Yes
Email Configured: Yes
Docker Volumes: success

### Mealie Version

nightly
Build: 0a00a6ea0d05d2dd944dd9cc6713156dc767e1ed

### Deployment

Docker (Linux)

**Comment by cmintey** [comment]
This is intended behavior. Every time a user logs in with LDAP, mealie checks in to see if they have an admin group in the _LDAP server_. If they are not, then they are not admins.

You can create a "mealie_admin" group in your LDAP server and add an `LDAP_ADMIN_FILTER` to mealie, and mealie will pick up the changes. See the configuration for LDAP here: https://nightly.mealie.io/documentation/getting-started/installation/backend-config/

**Comment by Smile1975** [comment]
Thank you, with the extra admin group in my domain and the modified ldap-admin-filter it works. I thought that it also will be possible to set an mealie admin flag manually to a ldap user.

**Comment by michael-genson** [comment]
It might be worth it to disable that field if a user is an LDAP user (i.e. make it read only). But I don't use LDAP so I'm not sure if that would cause issues or not

**Comment by cmintey** [comment]
Yeah that would probably be helpful. Should be pretty straightforward to implement. I'll try to work on that if I get the time unless someone else wants to pick it up
