### ISSUE TITLE
[BUG] Non-admin users are not allowed to access recipe list

### ISSUE THREAD

**Issue by becker-s** [mealie-recipes/mealie#2557]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

Non-admin users cannot access the recipes of their group on the main / search page. Once they visit the page, no recipe list is loaded and a HTTP 401 Forbidden response for a GET request to the `/api/admin/groups/{group-id}` endpoint can be observed in the browser developer tools.

### Steps to Reproduce

1. Create a non-admin user for a group with recipes
2. Log in as the created non-admin user
3. Open the developer tools in your browser
4. Navigate to the search page and observe a 401 response for the group site and a blank search page

### Please provide relevent logs

None.

### Mealie Version

Nightly

- I noticed the issue with a nightly version running https://github.com/mealie-recipes/mealie/commit/15c6df88ab289b3983ef541be42ec710034bece6
- The previously used version was https://github.com/mealie-recipes/mealie/commit/0a00a6ea0d05d2dd944dd9cc6713156dc767e1ed
- I suspect that the root cause of the issue was introduced in https://github.com/mealie-recipes/mealie/commit/2c5e5a8421e7bc9337fb93309c9f986abee26054, see https://github.com/mealie-recipes/mealie/commit/2c5e5a8421e7bc9337fb93309c9f986abee26054#diff-26b31ee4412dd37382d14e9615f9f33be0770f6c34c2657f4d9a8b54361e3fbcR69

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
I have a PR open for it:
https://github.com/mealie-recipes/mealie/pull/2556

FYI in the meantime, the public explore link works for everyone

**Comment by becker-s** [comment]
@michael-genson Thank you for the quick reply. Sorry for the noise, I only searched for issues and not for pull requests :confused:

**Comment by michael-genson** [comment]
No worries!
