### ISSUE TITLE
[BUG] unable to delete entry??

### ISSUE THREAD

**Issue by darrin17** [mealie-recipes/mealie#2560]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

i am using the current combined docker build. I am unable to delete an entry, even if it is botched during the scrape.  Is it not possible to delete an entry?  if so may i ask how, i am unable to do it.

Thank you

### Steps to Reproduce

create recipe, try to remove recipe

### Please provide relevent logs

i have no logs

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
![image](https://github.com/mealie-recipes/mealie/assets/71845777/2f9c293c-4979-4b01-964d-969751fc4100)

![image](https://github.com/mealie-recipes/mealie/assets/71845777/7acd7566-841f-40c8-9987-6fa57618e558)

![image](https://github.com/mealie-recipes/mealie/assets/71845777/9b8a2351-e0fb-4e7d-95d1-11a7b0f5453c)
