### ISSUE TITLE
[BUG] - & Symbol not imported correctly

### ISSUE THREAD

**Issue by Doublemyst** [mealie-recipes/mealie#2567]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

When importing a recipe like here: https://aaronandclaire.com/easy-sesame-chicken/ in the step "Prep Vegetables & Make Sauce" it is imported as "Prep Vegetables u0026 Make Sauce" 

### Steps to Reproduce

Import the recipe https://aaronandclaire.com/easy-sesame-chicken/ (in my case it was a part of bulk import)

### Please provide relevent logs

don't know how

### Deployment

Unraid

**Comment by michael-genson** [comment]
This isn't a Mealie issue, the website's source has the same problem:
![image](https://github.com/mealie-recipes/mealie/assets/71845777/44ff401b-5fd4-47af-b535-9a821a516504)

```json
    {
      "@type": "HowToSection",
      "name": "Prep Vegetables u0026 Make Sauce",
      "itemListElement": [
        {
          "@type": "HowToStep",
          "name": "Finely chop the garlic cloves. Gate a small knob of ginger (2 tsp).",
          "text": "Finely chop the garlic cloves. Gate a small knob of ginger (2 tsp).",
          "url": "https://aaronandclaire.com/easy-sesame-chicken/#wpzoom-rcb-direction-step-650d8a0b0db46",
          "image": ""
        },
        {
          "@type": "HowToStep",
          "name": "Thinly slice the green onions, separating the whites and greens. Cut the broccoli into small florets. (If you have some other vegetables to pair with, you can skip the broccoli. No problem at all.)",
          "text": "Thinly slice the green onions, separating the whites and greens. Cut the broccoli into small florets. (If you have some other vegetables to pair with, you can skip the broccoli. No problem at all.)",
          "url": "https://aaronandclaire.com/easy-sesame-chicken/#wpzoom-rcb-direction-step-650d8a0b0db47",
          "image": ""
        },
        {
          "@type": "HowToStep",
          "name": "To make the sauce, in a small container, stir together the soy sauce, oyster sauce, sugar, honey, vinegar,  ketchup, chicken bouillon powder, water, and cornstarch.",
          "text": "To make the sauce, in a small container, stir together the soy sauce, oyster sauce, sugar, honey, vinegar,  ketchup, chicken bouillon powder, water, and cornstarch.",
          "url": "https://aaronandclaire.com/easy-sesame-chicken/#wpzoom-rcb-direction-step-16953913122011298",
          "image": ""
        }
      ]
    },
```

**Comment by Doublemyst** [comment]
Ah, thanks for the info!
