### ISSUE TITLE
[BUG] - Bulk import hangs in "In Progress"

### ISSUE THREAD

**Issue by Doublemyst** [mealie-recipes/mealie#2568]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

Can't launch an bulk import, figured out, that those two items can't be imported in bulk together, but it worked, if using "bulk" import, but adding each item separately:
https://aaronandclaire.com/butter-chicken-murgh-makhani-recipe/
https://aaronandclaire.com/karaage-don-karaage-rice-bowl-recipe/

**Details**
Version: nightly
Build: 0a00a6ea0d05d2dd944dd9cc6713156dc767e1ed
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.42.0

**Checks**
Secure Site: No
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: Yes
Docker Volumes: success

### Steps to Reproduce

Import recipies in bulk and try to import those two at once:
https://aaronandclaire.com/butter-chicken-murgh-makhani-recipe/
https://aaronandclaire.com/karaage-don-karaage-rice-bowl-recipe/

### Please provide relevent logs

-

### Deployment

Unraid

**Comment by hay-kot** [comment]
Working fine on the demo-site, 

https://demo.mealie.io/group/reports/3e2868a1-6fb0-4333-b2bd-f0368c58c2ad

Could you provide your logs?

**Comment by Doublemyst** [comment]
I have deleted now all recipes I had, and relaunched the import, and it worked. Then I added items twice, and got again this hanging issue (I also tried the same data on your demo site, but it worked just fine). Here are the logs, where it "broke" but on demo not:
https://pastebin.com/ncA46FxB

and so it does look in the app (there is some time differences, as at my place it's 17:35 (in mealie it's 15:35) and I took the logs from dozzle -> easier to download

![image](https://github.com/mealie-recipes/mealie/assets/40290451/f175a8e2-7188-42ce-8564-5fe36d866865)

Please let me know, if you need any other information.


Edit: I think those are the URLs, which went into "in progress" status without changes (after deleting all recipies and reimport of those 2 from the issue description, i started to import approx. 30 URLs batches at a time, and on the second run it hanged - those must be the URLs i tried to import)

https://aaronandclaire.com/4-easy-instant-pot-recipes/
https://aaronandclaire.com/10-minute-bibim-guksu-korean-spicy-mixed-noodles-recipe/
https://aaronandclaire.com/jjimdak-dakbokkeumtanga-k-a-dakdoritang-recipes/
https://aaronandclaire.com/best-korean-fried-chicken-sandwich-recipe/
https://aaronandclaire.com/pad-see-ew-thai-stir-fried-noodles-recipe/
https://aaronandclaire.com/jjajangmyeon-korean-black-bean-sauce-noodles-recipe/
https://aaronandclaire.com/oyakodon-japanese-chicken-and-egg-rice-bowl-recipe/
https://aaronandclaire.com/korean-beef-and-vegetable-porridge-sogigi-yachaejuk-recipe/
https://aaronandclaire.com/4-perfect-korean-porridges-for-breakfast/
https://aaronandclaire.com/15-minute-miso-ramen-recipe/
https://aaronandclaire.com/korean-dumpling-soup-manduguk-recipe/
https://aaronandclaire.com/korean-dumpling-hot-pot-mandu-jeongol-recipe/
https://aaronandclaire.com/4-ways-to-enjoy-frozen-dumplings/
https://aaronandclaire.com/korean-soft-tofu-stew-sundubu-jjigae-recipe/
https://aaronandclaire.com/easy-tuna-kimchi-stew-kimchi-jjigae-recipe/
https://aaronandclaire.com/classic-kimchi-stewkimchi-jjigaerecipe/
https://aaronandclaire.com/10-minute-kimchi-stew-kimchi-jjigae-recipe/
https://aaronandclaire.com/4-quick-easy-stir-fry-noodle-recipes/
https://aaronandclaire.com/4-quick-easy-korean-breakfast-recipes/
https://aaronandclaire.com/7-minute-budae-jjigae-korean-army-base-stew-recipe/
https://aaronandclaire.com/3-best-korean-fried-chicken-recipes/
https://aaronandclaire.com/4-ways-to-enjoy-instant-pot/
https://aaronandclaire.com/squid-game-lunchbox-traditional-korean-lunchbox/
https://aaronandclaire.com/10-minute-yaki-udon-japanese-stir-fried-udon-noodles-recipe/
https://aaronandclaire.com/easy-chicken-teriyaki-recipe/
https://aaronandclaire.com/easy-pork-bone-soup-gamjatang-recipe/
https://aaronandclaire.com/chicken-katsudon-japanese-chicken-cutlet-rice-bowl-recipe/
https://aaronandclaire.com/the-easiest-chicken-katsu-recipe/
https://aaronandclaire.com/cheese-buldak-korean-fire-chicken-recipe/
https://aaronandclaire.com/the-best-kimchi-pancake-with-korean-pancake-mix/
