### ISSUE TITLE
[BUG] - Docker Desktop container not starting

### ISSUE THREAD

**Issue by heyepic** [mealie-recipes/mealie#2570]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

I'm unable to launch Mealie. I run a bunch of other docker containers without issue...

![image](https://github.com/mealie-recipes/mealie/assets/12517908/fe86f144-9b77-43cb-abbb-6e26e899507b)

![image](https://github.com/mealie-recipes/mealie/assets/12517908/e16ef9a6-2ff6-46df-86cd-3ceedb7bf141)

### Steps to Reproduce

Install Mealie via Docker Desktop. Map port 3000.

### Please provide relevent logs

When I go to the port after starting the container, I see this in the logs:

![image](https://github.com/mealie-recipes/mealie/assets/12517908/3eccf6e7-973b-4b8e-a1db-ace0626b5f6b)

### Mealie Version

Latest nightly

### Deployment

Docker (Linux)

### Additional Deployment Details

On a Proxmox Debian setup running a few other containers like Portainer, IT Tools, Uptime Kuma, VS Code, etc.

**Comment by michael-genson** [comment]
It looks like you're only running the frontend. Did you follow the installation guide?

https://nightly.mealie.io/documentation/getting-started/installation/installation-checklist/

**Comment by heyepic** [comment]
I did and I thought I was going about it the right way. Also tried running the combination container but similar issue.

![image](https://github.com/mealie-recipes/mealie/assets/12517908/1e4085bd-5847-4ea7-8860-201683148618)

**Comment by michael-genson** [comment]
Can you provide your docker compose file?

**Comment by heyepic** [comment]
Just kidding - this time it just started working. :) No idea what changed.

![image](https://github.com/mealie-recipes/mealie/assets/12517908/199dbffb-1b8c-4968-8d34-696f015529b7)
