### ISSUE TITLE
[BUG] - Cannot remove a tag from recipe (throws an "Unknown error") or from tag list

### ISSUE THREAD

**Issue by plunata** [mealie-recipes/mealie#2592]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

I imported a hello fresh recipe with the original keywords as tags. One of those keywords/tags in [this recipe](https://www.hellofresh.de/recipes/spatzle-pfanne-mit-mozzarella-und-senfsosse-63e9e0667e26a9cd9d005993) is "Klimaheld" and for some reason, it cannot be deleted from the tags list (while it works fine with others so far). Also, when trying to remove the tag "Klimaheld" from the recipe and saving the changes afterwards, it throws an "Unknown error". In some cases the changes will be saved, and other times the tag will still be there. This can be reproduced in the demo with [this particular recipe](https://demo.mealie.io/recipe/spatzle-pfanne-mit-mozzarella-und-senfsosse-bei-diesem-gericht-wird-mind-2-3-weniger-co2e-durch-zutaten-verursacht-als-bei-einem-durchschnittlichen-hellofresh-rezept).

### Steps to Reproduce

**Create recipe**
1) Import a Hello Fresh recipe from German website containing the keyword "Klimaheld": [Link](https://www.hellofresh.de/recipes/spatzle-pfanne-mit-mozzarella-und-senfsosse-63e9e0667e26a9cd9d005993)
2) Select "Import original keywords as tags" before completing the import
3) Edit recipe > try to remove tag "Klimaheld" > Save
4) An "Unknown error" will appear

**Delete tag**
1) Go to tag overview via sidebar or Profile > Tags
2) Try to delete tag "Klimaheld"

### Please provide relevent logs

I don't have access to the logs right now unfortunately, but I will upload them later if you did not already stumble upon this error while recreating the bug.

### Mealie Version

nightly Build 0a00a6ea0d05d2dd944dd9cc6713156dc767e1ed

### Deployment

Unraid

**Comment by michael-genson** [comment]
Can confirm this on the latest nightly too. Thanks for the report!
Needs some more investigation, but somehow the `recipes_to_tags` table is getting two entries, so when trying to delete the recipe/tag relationship, this error is thrown:
```
StaleDataError: DELETE statement on table 'recipes_to_tags' expected to delete 1 row(s); Only 2 were matched.
```

**Comment by michael-genson** [comment]
Looks like the source data has the offending tag twice. We're probably not handling that correctly:
![image](https://github.com/mealie-recipes/mealie/assets/71845777/d8378194-f36a-4a65-af3f-3d4bc88deed5)
