### ISSUE TITLE
[BUG] - Food data duplicates after seeding, combining not working

### ISSUE THREAD

**Issue by plunata** [mealie-recipes/mealie#2593]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

Multiple entries of the same word appear in the food data list after seeding the database with foods (German in this case). For instance, "Brokkoli" appears four times in the food data list while it only appears as one single entry in the dropdown menu in the ingredients list (in the edit menu of a recipe). Combining entries is not working for me so far, unfortunately. When trying to do so, "Brokkoli" only has one entry in the dropdown menu. Perhaps it happened when entering recipe ingredients and pressing enter afterwards (without selecting a suggested entry) but I cannot say for sure. 
I know it's an experimental feature still but I thought I should report the bug anyway :)

### Steps to Reproduce

**Multiple entries of the same word**
1) Seed food data (German)
2) Create or edit some test recipes > Enable Ingredient Amounts > Enter Food > Create food by pressing Enter or clicking on Create button
3) Create or edit some test recipes > Enable Ingredient Amounts > Select Food from dropdown menu

**Combining food**
1) Go to Data Management > Foods > Combine
2) Select food to combine > Confirm
3) Check if food words were combined

(Not sure if any of those steps can recreate the bug but that is what I remember doing at least.)

### Please provide relevent logs

It does not throw an error in both cases.

### Mealie Version

nightly Build 0a00a6ea0d05d2dd944dd9cc6713156dc767e1ed

### Deployment

Unraid

**Comment by PeterJT** [comment]
I think this is the same issue I'd reported in #2342
