### ISSUE TITLE
[BUG] - Recipes not sharing across groups

### ISSUE THREAD

**Issue by sirmeili** [mealie-recipes/mealie#2612]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [x] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

Recipes are not visible across groups even though the Recipes and the groups are both set to public.

### Steps to Reproduce

1. Ensure recipes in group 1 are public
2. Ensure group 1 is set to public
3. Create second group
4. Assign user to second group
5. User sees zero recipes

### Please provide relevent logs

INFO:     73.27.90.116:0 - "PUT /api/admin/groups/92dd11e4-be35-4f0e-971f-63cd3ca6ba5b HTTP/1.1" 200 OK
INFO:     10.0.0.158:38710 - "GET /api/groups/mealplans/today HTTP/1.1" 200 OK
INFO:     10.0.0.158:38716 - "GET /api/groups/mealplans/today HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/users/self/group HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/recipes?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1696867584817&searchSeed=1696867584817&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/recipes?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1696867590048&searchSeed=1696867590048&search=key&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/recipes?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1696867591788&searchSeed=1696867591788&search=key+lime+pie&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/recipes?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1696867591867&searchSeed=1696867591867&search=key+lime+pie&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
INFO:     127.0.0.1:55750 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/groups/mealplans?page=1&perPage=-1&start_date=2023-10-09&end_date=2023-10-15 HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/users/self/group HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/recipes?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1696867605118&searchSeed=1696867605118&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/recipes/jalapeno-popper-grilled-cheese-sandwich HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/recipes/jalapeno-popper-grilled-cheese-sandwich/comments HTTP/1.1" 200 OK
INFO:     10.0.0.158:57130 - "GET /api/groups/mealplans/today HTTP/1.1" 200 OK
INFO:     10.0.0.158:57146 - "GET /api/groups/mealplans/today HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "PUT /api/recipes/jalapeno-popper-grilled-cheese-sandwich HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/recipes/jalapeno-popper-grilled-cheese-sandwich/comments HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "PUT /api/recipes/jalapeno-popper-grilled-cheese-sandwich HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/recipes/jalapeno-popper-grilled-cheese-sandwich/comments HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/users/self/group HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/recipes?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1696867625610&searchSeed=1696867625610&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/admin/about HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/admin/about/check HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/users?page=1&perPage=-1 HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/admin/users/5e38dd71-efa3-4eca-86cd-f4548d0b974d HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/admin/groups?page=1&perPage=-1 HTTP/1.1" 200 OK
INFO:     127.0.0.1:44970 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "PUT /api/admin/users/5e38dd71-efa3-4eca-86cd-f4548d0b974d HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/users/self/group HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/recipes?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1696867640637&searchSeed=1696867640637&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
INFO:     10.0.0.158:56848 - "GET /api/groups/mealplans/today HTTP/1.1" 200 OK
INFO:     10.0.0.158:56858 - "GET /api/groups/mealplans/today HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/admin/about HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/admin/about/check HTTP/1.1" 200 OK
INFO:     127.0.0.1:37760 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     10.0.0.158:57820 - "GET /api/groups/mealplans/today HTTP/1.1" 200 OK
INFO:     10.0.0.158:57822 - "GET /api/groups/mealplans/today HTTP/1.1" 200 OK
INFO:     127.0.0.1:49406 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     10.0.0.158:37994 - "GET /api/groups/mealplans/today HTTP/1.1" 200 OK
INFO:     10.0.0.158:37988 - "GET /api/groups/mealplans/today HTTP/1.1" 200 OK
INFO:     127.0.0.1:42190 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     10.0.0.158:50344 - "GET /api/groups/mealplans/today HTTP/1.1" 200 OK
INFO:     10.0.0.158:50354 - "GET /api/groups/mealplans/today HTTP/1.1" 200 OK
INFO:     10.0.0.158:41850 - "GET /api/media/recipes/unknown/images/original.webp HTTP/1.1" 404 Not Found
INFO:     10.0.0.158:41850 - "GET /api/media/recipes/unknown/images/original.webp HTTP/1.1" 404 Not Found
INFO:     73.27.90.116:0 - "GET /api/admin/about/docker/validate HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/media/docker/validate.txt HTTP/1.1" 200 OK
INFO:     10.0.0.158:57998 - "GET /api/groups/mealplans/today HTTP/1.1" 200 OK
INFO:     10.0.0.158:58008 - "GET /api/groups/mealplans/today HTTP/1.1" 200 OK
INFO:     10.0.0.158:58020 - "GET /api/media/recipes/unknown/images/original.webp HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:60590 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     10.0.0.158:35826 - "GET /api/media/recipes/unknown/images/original.webp HTTP/1.1" 404 Not Found
INFO:     73.27.90.116:0 - "GET /api/users?page=1&perPage=-1 HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/users/self/group HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/recipes?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1696867781008&searchSeed=1696867781008&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
INFO:     10.0.0.158:34516 - "GET /api/media/recipes/unknown/images/original.webp HTTP/1.1" 404 Not Found
INFO:     73.27.90.116:0 - "GET /api/admin/about/check HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/admin/about HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/users?page=1&perPage=-1 HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/admin/groups?page=1&perPage=-1 HTTP/1.1" 200 OK
INFO:     10.0.0.158:42652 - "GET /api/groups/mealplans/today HTTP/1.1" 200 OK
INFO:     10.0.0.158:42636 - "GET /api/groups/mealplans/today HTTP/1.1" 200 OK
INFO:     10.0.0.158:42658 - "GET /api/media/recipes/unknown/images/original.webp HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:58136 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     10.0.0.158:47740 - "GET /api/media/recipes/unknown/images/original.webp HTTP/1.1" 404 Not Found
INFO:     10.0.0.158:47336 - "GET /api/media/recipes/unknown/images/original.webp HTTP/1.1" 404 Not Found
INFO:     10.0.0.158:51190 - "GET /api/groups/mealplans/today HTTP/1.1" 200 OK
INFO:     10.0.0.158:51202 - "GET /api/groups/mealplans/today HTTP/1.1" 200 OK
INFO:     127.0.0.1:49090 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     10.0.0.158:49318 - "GET /api/groups/mealplans/today HTTP/1.1" 200 OK
INFO:     10.0.0.158:49326 - "GET /api/groups/mealplans/today HTTP/1.1" 200 OK
INFO:     10.0.0.158:49338 - "GET /api/media/recipes/unknown/images/original.webp HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:40428 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/users/self/group HTTP/1.1" 200 OK
INFO:     73.27.90.116:0 - "GET /api/recipes?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1696867877042&searchSeed=1696867877042&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
INFO:     10.0.0.158:53272 - "GET /api/groups/mealplans/today HTTP/1.1" 200 OK
INFO:     10.0.0.158:53268 - "GET /api/groups/mealplans/today HTTP/1.1" 200 OK
INFO:     127.0.0.1:54930 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     10.0.0.158:52658 - "GET /api/groups/mealplans/today HTTP/1.1" 200 OK
INFO:     10.0.0.158:52652 - "GET /api/groups/mealplans/today HTTP/1.1" 200 OK
INFO:     10.0.0.158:52664 - "GET /api/media/recipes/unknown/images/original.webp HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:49866 - "GET /api/app/about HTTP/1.1" 200 OK
INFO: 09-Oct-23 12:12:16 	HTTP Request: GET https://thesaltymarshmallow.com/best-easy-chili-recipe/ "HTTP/1.1 200 OK"
INFO: 09-Oct-23 12:12:17 	Image URL: ['https://thesaltymarshmallow.com/wp-content/uploads/2018/10/chili-recipe1.jpg', 'https://thesaltymarshmallow.com/wp-content/uploads/2018/10/chili-recipe1-500x500.jpg', 'https://thesaltymarshmallow.com/wp-content/uploads/2018/10/chili-recipe1-500x375.jpg', 'https://thesaltymarshmallow.com/wp-content/uploads/2018/10/chili-recipe1-480x270.jpg']
INFO: 09-Oct-23 12:12:17 	HTTP Request: HEAD https://thesaltymarshmallow.com/wp-content/uploads/2018/10/chili-recipe1.jpg "HTTP/1.1 200 OK"
INFO: 09-Oct-23 12:12:18 	HTTP Request: HEAD https://thesaltymarshmallow.com/wp-content/uploads/2018/10/chili-recipe1-500x500.jpg "HTTP/1.1 200 OK"
INFO: 09-Oct-23 12:12:18 	HTTP Request: HEAD https://thesaltymarshmallow.com/wp-content/uploads/2018/10/chili-recipe1-500x375.jpg "HTTP/1.1 200 OK"
INFO: 09-Oct-23 12:12:18 	HTTP Request: HEAD https://thesaltymarshmallow.com/wp-content/uploads/2018/10/chili-recipe1-480x270.jpg "HTTP/1.1 200 OK"
INFO: 09-Oct-23 12:12:18 	HTTP Request: GET https://thesaltymarshmallow.com/wp-content/uploads/2018/10/chili-recipe1-500x500.jpg "HTTP/1.1 200 OK"
INFO: 09-Oct-23 12:12:19 	original.jpg minified
INFO: 09-Oct-23 12:12:19 	Tiny image saved
INFO:     2600:1006:b011:55ae:0:47:d867:1301:0 - "POST /api/recipes/create-url HTTP/1.1" 201 Created
INFO:     10.0.0.158:47232 - "GET /api/media/recipes/unknown/images/original.webp HTTP/1.1" 404 Not Found
INFO:     2600:1006:b011:55ae:0:47:d867:1301:0 - "GET /api/organizers/tags?page=1&perPage=-1 HTTP/1.1" 200 OK
INFO:     2600:1006:b011:55ae:0:47:d867:1301:0 - "GET /api/recipes/best-easy-chili-recipe HTTP/1.1" 200 OK
INFO:     2600:1006:b011:55ae:0:47:d867:1301:0 - "GET /api/recipes/best-easy-chili-recipe/comments HTTP/1.1" 200 OK
INFO:     2600:1006:b011:55ae:0:47:d867:1301:0 - "GET /api/media/recipes/d265251d-6658-48c0-98fa-c6fec5cceabd/images/original.webp?rnd=1&version=2x5F HTTP/1.1" 200 OK
INFO:     10.0.0.158:47238 - "GET /api/groups/mealplans/today HTTP/1.1" 200 OK
INFO:     10.0.0.158:47246 - "GET /api/groups/mealplans/today HTTP/1.1" 200 OK

### Mealie Version

nightly

### Deployment

Docker (Linux)

### Additional Deployment Details

Installed on a Rpi3 using docker with Posgres as the DB.

**Comment by Kuchenpirat** [comment]
I am pretty shure this is intended behavior.

Groups can kinda be understood as their own instances. 

There is an discussion (#2134) about the vision how to implement 'households'. Which should be able to share recipes. But as of now this is not implemented

**Comment by sirmeili** [comment]
Ok, but then why have an option that says "Allow users outside of your group to see your recipes"

and why is there an option to make recipes Public?

**Comment by sirmeili** [comment]
After looking into this and finding the setting somewhere else with more information, it does appear this is expected behavior.

"When enabled you can use a public share link to share specific recipes without authorizing the user. When disabled, you can only share recipes with users who are in your group or with a pre-generated private link"

Seems odd that you can't share recipes more easily between groups Not sure what the point of "Groups" is unless you are using this to publicly host a website and not really use it for personal use.

I will check out the "households" feature in #2134 and though I know it's not implemented, I can maybe see how hard it would be if I contributed to it.

**Comment by michael-genson** [comment]
> and why is there an option to make recipes Public?

FYI there's also a public recipe browser: if you click on your name there should be a "Get Public Link" at the top which you can share
