### ISSUE TITLE
[BUG] - Build number not visible anymore on /admin/site-settings

### ISSUE THREAD

**Issue by pathia** [mealie-recipes/mealie#2624]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

While checking to see if I was running the latest greatest build I found that it isn't possible to view the current build we're running.

### Steps to Reproduce

Go to https://demo.mealie.io/admin/site-settings and you will see the missing build number. I attached a screenshot.
![afbeelding](https://github.com/mealie-recipes/mealie/assets/126187/d5f1b40a-ed24-4974-b15a-e54721f0d289)

### Please provide relevent logs

none

### Mealie Version

Funny question for a bug report regarding the missing build number 😄
I experienced it right after I migrated to the new mealie docker image ghcr.io/mealie-recipes/mealie:nightly just half an hour ago so I am really very up-to-date.

### Deployment

Docker (Linux)

**Comment by JvdMaat** [comment]
RC1 has the same. Did it ever list a build number prior? (I honestly do not recall that field having anything)
![image](https://github.com/mealie-recipes/mealie/assets/90044149/6dc7a16d-e3df-4b2f-89a1-cd5370987219)
Or is this a bug related to moving from docker hub to ghcr?

**Comment by pathia** [comment]
Yes it did. I double checked prior to migrating to the new docker image and so. I cannot really easily see the build version but I saw that the image was updated by watchtower the 1st of September. So I guess it was the build of August 31th that still showed it.

**Comment by pathia** [comment]
I did a quick restore of the snapshot I took beforehand just to grab the screenshot showing the build number:
![afbeelding](https://github.com/mealie-recipes/mealie/assets/126187/4937534a-e5d8-4db3-b082-7d2d1ae52810)

**Comment by boc-the-git** [comment]
Can also confirm build is visible on beta 5: 
<img width="267" alt="image" src="https://github.com/mealie-recipes/mealie/assets/3479092/30167611-bb9e-4b35-bc30-e283a9439757">

The source for which is [here](https://hub.docker.com/layers/hkotel/mealie/api-v1.0.0beta-5/images/sha256-91cbcf6d0db302e942706838d659e6b03d5d8a194b57d7bb6054754e728e5722?context=explore). Do ctrl+f for `ee121a12f8db33ecb4db5f8582f7ea9788d019e4`

Perhaps GHCR doesn't allow for similar?

**Comment by boc-the-git** [comment]
The Dockerfile is looking for an argument: https://github.com/mealie-recipes/mealie/blob/3af400ab288123549c2c90446006c6d65867d467/docker/Dockerfile#L86

Which I'm _assuming_ should be supplied [here](https://github.com/mealie-recipes/mealie/blob/mealie-next/.github/workflows/partial-builder.yml#L39-L46), but isn't. (Don't quote me on that location, haven't looked at these workflows before)

**Comment by boc-the-git** [comment]
PR raised. I believe the change I've made should fix the issue, but as noted on the PR, I'm not sure how I can actually test this from a workflow perspective!
Any advice welcome.

**Comment by boc-the-git** [comment]
Just installed latest nightly:
<img width="315" alt="image" src="https://github.com/mealie-recipes/mealie/assets/3479092/1e43b566-06ed-49a9-a1a7-343938c07bad">

Where the link is: https://github.com/hay-kot/mealie/commit/8acd6f906e84ade08d0ab5b1da89f7b41570e674

**Comment by pathia** [comment]
Works for me too. Thank you both for the quick and adequate responses and actions. 👍
