### ISSUE TITLE
Unable to create recipe by sharing url to PWA

### ISSUE THREAD

**Issue by PeterJT** [mealie-recipes/mealie#2643]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

With the 0.x release of Mealie it was possible to quickly create a recipe by using Android's share option to share the URL with a PWA. This does not work in the new 1.0.x stream.

### Steps to Reproduce

Create a PWA shortcut
Browse to a recipe on the web
Select the Android share option specifying the PWA as the destination

The PWA launches to the create menu but does not populate the URL field with the page

### Please provide relevent logs

n/a

### Mealie Version

Version
v1.0.0-RC1.1

### Deployment

Docker (Linux)

**Comment by boc-the-git** [comment]
I didn't even know this was a feature!
Now I do, so thanks for that!

**Comment by boc-the-git** [comment]
I haven't yet worked out the full answer.. I've got no idea what I'm doing with Vue 😅  My main issue has been struggling to get debugging/logging info, but I haven't tried anything other than console.log. Any advice anyone wants to provide, is much appreciated.

I'm reasonably confident the answer lies in here, as when I hardcode the return value, it works as expected. https://github.com/mealie-recipes/mealie/blob/df3b10b5c274f32664ef0224f38bb512a9ce60be/frontend/pages/recipe/create/url.vue#L112-L114

I'll probably look a bit more in the coming days and see if I can work it out.

**Comment by boc-the-git** [comment]
Top log is from my phone.. bottom is accessing directly in a browser.. note that the phone doesn't seem to be passing the query parameters through.
<img width="838" alt="image" src="https://github.com/mealie-recipes/mealie/assets/3479092/304c90db-5d5a-4e8a-835b-dc13827b25e5">

**Comment by boc-the-git** [comment]
This was a challenging one to solve! The solution was just not something I was even looking at for the majority of the time.. 

@PeterJT please note once it's merged, there are some release notes on the PR: https://github.com/mealie-recipes/mealie/pull/2654

**Comment by PeterJT** [comment]
Well done.

**Comment by PeterJT** [comment]
OK. Installed latest nightly, recreated PWA on phone. All works as expected. Thanks

**Comment by boc-the-git** [comment]
Awesome, thanks for confirming Peter
