### ISSUE TITLE
[BUG] - Can't copy paste shopping list.

### ISSUE THREAD

**Issue by Hezza11** [mealie-recipes/mealie#2645]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

Just setup Mealie and loving it so far, bought you a coffee! Something I've run into though is I can't seem to copy the shipping list. I click the button, it says "7 items copied" or how ever many, then I go to paste it somewhere else but it just pastes what ever was previously in my copy buffer.

On your test website it works. Though in Apples Reminder they get pasted it one big block, it'd be nice if they were line separated so they could be tickled off individually. TickTick actually does that nicely, but I'm moving away from using that. 
![Screenshot 2023-10-16 at 10 29 23]

![Screenshot 2023-10-16 at 10 30 15](https://github.com/mealie-recipes/mealie/assets/148050716/36934299-4e0b-4e4d-893c-1251c68bd897)

![Screenshot 2023-10-16 at 10 31 15](https://github.com/mealie-recipes/mealie/assets/148050716/08d4d552-e95e-4e3d-ad60-d02d7adc6dd2)

I am on Mac OS, tried Safari and Chrome, iPad and iPhone

### Steps to Reproduce

Create a shopping list and try and copy it into another app.

### Please provide relevent logs

**Details**
Version: nightly
Build: 0a00a6ea0d05d2dd944dd9cc6713156dc767e1ed
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.42.0

**Checks**
Secure Site: No
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: Yes
Docker Volumes: success

### Deployment

Unraid

**Comment by Kuchenpirat** [comment]
The most likely reason why you cannot copy from your mealie instance but from the demo version is that the demo version is reached through a secure https connection and your instance is either running over http or you are directly accesing it at the exposed port. 
Browsers usually do not allow "Copy to Clipboard" over an unsecure connection. 

For your problem with pasting. I am not sure mealie can influence how different apps are interpreting the copied data.

**Comment by michael-genson** [comment]
Closing this one for now, if you're able to check the above and you're still seeing the same behavior, feel free to re-open
