### ISSUE TITLE
[BUG] - Missing group_id when creating new user via LDAP after changing Home group name

### ISSUE THREAD

**Issue by cooljoebob64** [mealie-recipes/mealie#2648]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

When attempting to log in with an LDAP user (with verified correct credentials and permissions) that does not have a Mealie account yet, an SQL query attempts to add the user to the user table, but fails due to a null entry in the group_id column.

Default group is still set to "Home" - originally set by default, then set explicitly via env variable. 

This started occurring after changing the name of the original "Home" group to something else - I imagine the query is built by looking up the UUID of the group by name, but without a group that matches it returns null, and tries to insert the user with a null group_id.

Setting the name of the original group back to Home fixes the issue.

### Steps to Reproduce

1) Set default group to "Home".
2) Change name of the "Home" group to something else ("Everyone"). 
3) Add a new user by logging in with an LDAP account that has not logged in before.
4) Observer error logging in, and logs of failed user creation query.

### Please provide relevent logs

```
ERROR:    Exception in ASGI application

Traceback (most recent call last):

  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context

    self.dialect.do_execute(

  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute

    cursor.execute(statement, parameters)

psycopg2.errors.NotNullViolation: null value in column "group_id" of relation "users" violates not-null constraint

DETAIL:  Failing row contains (2023-10-16 14:43:26.21429, 2023-10-16 14:43:26.214292, 20e40cdb-2d52-4eb1-8e08-36a0e6c6d606, testo, testo, myemail+testo@gmail.com, LDAP, f, f, null, 1234, f, f, f, null, 0, null, LDAP).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi

    result = await app(  # type: ignore[func-returns-value]

  File "/opt/pysetup/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__

    return await self.app(scope, receive, send)

 << Traceback stuff >>

  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute

    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "group_id" of relation "users" violates not-null constraint

DETAIL:  Failing row contains (2023-10-16 14:43:26.21429, 2023-10-16 14:43:26.214292, 20e40cdb-2d52-4eb1-8e08-36a0e6c6d606, testo, testo, myemail+testo@gmail.com, LDAP, f, f, null, 1234, f, f, f, null, 0, null, LDAP).

[SQL: INSERT INTO users (id, full_name, username, email, password, auth_method, admin, advanced, group_id, cache_key, login_attemps, locked_at, can_manage, can_invite, can_organize, owned_recipes_id, created_at, update_at) VALUES (%(id)s::UUID, %(full_name)s, %(username)s, %(email)s, %(password)s, %(auth_method)s, %(admin)s, %(advanced)s, %(group_id)s::UUID, %(cache_key)s, %(login_attemps)s, %(locked_at)s, %(can_manage)s, %(can_invite)s, %(can_organize)s, %(owned_recipes_id)s::UUID, %(created_at)s, %(update_at)s)]


```

### Mealie Version

v1.0.0-RC1.1

### Deployment

Docker (Linux)

### Additional Deployment Details

Configured via docker-compose with working LDAP configuration. 

Settings page all green checks, docker volumes verified.

**Comment by cmintey** [comment]
I was able to reproduce this issue. A workaround is to also update your `DEFAULT_GROUP` environment to be the new name of the group you updated. When I changed my group name to "Family" and updated `DEFAULT_GROUP=Family`, I was able to log in, as expected
