### ISSUE TITLE
Mealie Migration to v1 Missing Recipes

### ISSUE THREAD

**Issue by Slither13** [mealie-recipes/mealie#2650]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

Importing data from 0.5.6 to v1. Original folder is showing all 349 recipes. After import from .zip, only 126 recipes are being imported. 

All categories and tags were imported correctly.

### Steps to Reproduce

1) Settings
2) Backups
3) Looking for Migration
4) Dropdown -> Mealie Pre v1.0
5) Select file -> Backup.zip
6) Submit
7)Import finishes

### Please provide relevent logs

INFO: 17-Oct-23 00:09:45 	Database connection established.
INFO: 17-Oct-23 00:09:45 	Context impl SQLiteImpl.
INFO: 17-Oct-23 00:09:45 	Will assume non-transactional DDL.
INFO: 17-Oct-23 00:09:45 	Migration needed. Performing migration...
INFO: 17-Oct-23 00:09:45 	Context impl SQLiteImpl.
INFO: 17-Oct-23 00:09:45 	Will assume non-transactional DDL.
INFO: 17-Oct-23 00:09:45 	Running upgrade  -> 6b0f5f32d602, Initial tables
INFO: 17-Oct-23 00:09:47 	Running upgrade 6b0f5f32d602 -> 263dd6707191, convert quantity from integer to float
INFO: 17-Oct-23 00:09:47 	Running upgrade 263dd6707191 -> f1a2dbee5fe9, Add original_text column to recipes_ingredients
INFO: 17-Oct-23 00:09:47 	Running upgrade f1a2dbee5fe9 -> 59eb59135381, add tags to cookbooks
INFO: 17-Oct-23 00:09:48 	Running upgrade 59eb59135381 -> 09dfc897ad62, add require_all for cookbook filters
INFO: 17-Oct-23 00:09:48 	Running upgrade 09dfc897ad62 -> ab0bae02578f, Add use_abbreviation column to ingredients
INFO: 17-Oct-23 00:09:48 	Running upgrade ab0bae02578f -> f30cf048c228, add new webhook fields
INFO: 17-Oct-23 00:09:48 	Running upgrade f30cf048c228 -> 188374910655, add login_attemps and locked_at field to user table
INFO: 17-Oct-23 00:09:48 	Running upgrade 188374910655 -> 089bfa50d0ed, Add is_ocr_recipe column to recipes
INFO: 17-Oct-23 00:09:48 	Running upgrade 089bfa50d0ed -> 44e8d670719d, add extras to shopping lists, list items, and ingredient foods
INFO: 17-Oct-23 00:09:48 	Running upgrade 44e8d670719d -> 2ea7a807915c, add recipe_timeline_events table
INFO: 17-Oct-23 00:09:48 	Running upgrade 2ea7a807915c -> 1923519381ad, added recipe last made timestamp
INFO: 17-Oct-23 00:09:48 	Running upgrade 1923519381ad -> 167eb69066ad, add recipe_scale to shopping list item ref
INFO: 17-Oct-23 00:09:48 	Running upgrade 167eb69066ad -> 165d943c64ee, add related user to mealplan
INFO: 17-Oct-23 00:09:48 	Running upgrade 165d943c64ee -> ff5f73b01a7a, add missing foreign key and order indices
INFO: 17-Oct-23 00:09:51 	Running upgrade ff5f73b01a7a -> 16160bf731a0, add more indices necessary for search
INFO: 17-Oct-23 00:09:51 	Running upgrade 16160bf731a0 -> 5ab195a474eb, add normalized search properties
INFO: 17-Oct-23 00:09:52 	Running upgrade 5ab195a474eb -> b04a08da2108, added shopping list label settings
INFO: 17-Oct-23 00:09:52 	Running upgrade b04a08da2108 -> 38514b39a824, add auth_method to user table
INFO: 17-Oct-23 00:09:52 	Running upgrade 38514b39a824 -> b3dbb554ba53, postgres fuzzy search
INFO: 17-Oct-23 00:09:52 	Running upgrade b3dbb554ba53 -> 04ac51cbe9a4, added group slug
INFO: 17-Oct-23 00:09:52 	Running upgrade 04ac51cbe9a4 -> 1825b5225403, added recipe note to shopping list recipe ref
INFO: 17-Oct-23 00:09:52 	Running upgrade 1825b5225403 -> bcfdad6b7355, remove tool name and slug unique contraints
WARNING: 17-Oct-23 00:09:52 	"get_all" method is deprecated; use "page_all" instead
INFO: 17-Oct-23 00:09:52 	Database contains no users, initializing...
INFO: 17-Oct-23 00:09:52 	Generating Default Group
INFO: 17-Oct-23 00:09:53 	Generating Default User
INFO: 17-Oct-23 00:09:53 	No food found with slug: 'dairy-products-and-dairy-substitutes' skipping fix
INFO: 17-Oct-23 00:10:06 	-----SYSTEM STARTUP----- 

INFO: 17-Oct-23 00:10:06 	------APP SETTINGS------
INFO: 17-Oct-23 00:10:06 	{
    "PRODUCTION": true,
    "BASE_URL": "https://mealie.mydomain.net",
    "IS_DEMO": false,
    "API_PORT": 9000,
    "API_DOCS": true,
    "TOKEN_TIME": 48,
    "LOG_LEVEL": "INFO",
    "GIT_COMMIT_HASH": "0a00a6ea0d05d2dd944dd9cc6713156dc767e1ed",
    "ALLOW_SIGNUP": false,
    "SECURITY_MAX_LOGIN_ATTEMPTS": 5,
    "SECURITY_USER_LOCKOUT_TIME": 24,
    "DB_ENGINE": "sqlite",
    "DB_PROVIDER": {
        "data_dir": "/app/data",
        "prefix": ""
    },
    "DEFAULT_GROUP": "home",
    "DEFAULT_EMAIL": "*****@gmail.com",
    "SMTP_HOST": "smtp.gmail.com",
    "SMTP_PORT": "587",
    "SMTP_FROM_NAME": "Mealie",
    "SMTP_FROM_EMAIL": "*****@gmail.com",
    "SMTP_AUTH_STRATEGY": "TLS",
    "LDAP_AUTH_ENABLED": false,
    "LDAP_SERVER_URL": null,
    "LDAP_TLS_INSECURE": false,
    "LDAP_TLS_CACERTFILE": null,
    "LDAP_ENABLE_STARTTLS": false,
    "LDAP_BASE_DN": null,
    "LDAP_QUERY_BIND": null,
    "LDAP_QUERY_PASSWORD": null,
    "LDAP_USER_FILTER": null,
    "LDAP_ADMIN_FILTER": null,
    "LDAP_ID_ATTRIBUTE": "uid",
    "LDAP_MAIL_ATTRIBUTE": "mail",
    "LDAP_NAME_ATTRIBUTE": "name",
    "TESTING": false
}

### Mealie Version

Mealie v1 Nightly

### Deployment

Unraid

**Comment by hay-kot** [comment]
🤔 

![CleanShot 2023-10-17 at 11 15 52@2x](https://github.com/mealie-recipes/mealie/assets/64056131/77970eab-0026-4b08-89fc-4021ef04abcd)

---

> Please provide relevent logs
> INFO: 17-Oct-23 00:09:45 Database connection established.
> INFO: 17-Oct-23 00:09:45 Context impl SQLiteImpl.
> ...

These are just the startup logs and not logs related to your import. In order to troubleshoot this we either need the relevant logs or a copy of your backup file

**Comment by Slither13** [comment]
Being dumb is difficult, title is updated.

I have the full backup I made in 0.5.6. Do I just share that .zip or is there any personal stuff I should be removing?

**Comment by michael-genson** [comment]
Can you post your .zip? You can take a look through it and make sure there's nothing in there you don't want to share, but other than recipe info there shouldn't be

**Comment by lironamoovit** [comment]
any updates on this one? i have the same issue, backup didnt restore any of my users, recipes etc. having a blank app now

**Comment by michael-genson** [comment]
We're going to need more information. What version is your backup from? How are you trying to use the backup? If it's from 0.5.6, did you follow the migration guide?

https://docs.mealie.io/documentation/getting-started/migrating-to-mealie-v1/

**Comment by lironamoovit** [comment]
sorry, i missed it. i updated the docker file and didnt notice that migration process.
i followed the instructions and everything is working now, thank you!

**Comment by michael-genson** [comment]
Glad to hear!
