### ISSUE TITLE
[BUG?] - Demo site is down (404)

### ISSUE THREAD

**Issue by boc-the-git** [mealie-recipes/mealie#2667]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

The demo site is currently returning a 404.

<img width="542" alt="image" src="https://github.com/mealie-recipes/mealie/assets/3479092/44c91602-08bf-4d09-a6d9-9a861e506cf3">

### Steps to Reproduce

Navigate to the demo site.

### Please provide relevent logs

N/A

### Deployment

Other

### Additional Deployment Details

N/A

**Comment by boc-the-git** [comment]
Back up now. I noted it as having been down for roughly 10 minutes, not sure the actual duration.

**Comment by boc-the-git** [comment]
Reopening as the demo site is down again now. There might be a systemic issue at play?

**Comment by hay-kot** [comment]
Some server error happening in the background, reset the instance seems to be good now. Thanks!

**Comment by boc-the-git** [comment]
Off topic for this issue (sorry) but @hay-kot I sent you an email a few days ago at `hayden@haybytes.com`, I'm guessing it might've gone unnoticed.  Please have a look when you get the chance :)
