### ISSUE TITLE
[BUG] - Creating new ingredient does not select it

### ISSUE THREAD

**Issue by Kuchenpirat** [mealie-recipes/mealie#2682]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

When creating an new ingredient on the recipe page with the Create-button or Enter-key the new ingredient is not automatically selected. When leaving the input field with the tab key the input switches back to the first ingredient displayed in the list. 

When leaving the input field by clicking on another cell the ingredient stays selected. 

Expected behaviour is that the newly created ingredient stays selected when exiting the field with tab. I am pretty sure this was working in earlier versions.  

### Steps to Reproduce

- Create a new recipe. 
- Enable Ingredient Amounts
- Edit Recipe
- Create new Ingredient 
  - The Name of the newly created Ingredient is displayed in the Input field
- Press Tab to get to next input field
  - Ingredient changes to the first entry in the list of ingredients

### Please provide relevent logs

INFO:     172.18.0.2:58290 - "POST /api/foods HTTP/1.1" 201 Created

### Mealie Version

**Version:** nightly

**Build:** 14cc44f94848bcc1b44eadc648853bd87b9b004b

### Deployment

Docker (Linux)

**Comment by boc-the-git** [comment]
Replicated this running the latest nightly. Definitely a bad UX.

**Comment by boc-the-git** [comment]
@Kuchenpirat this might've been fixed by Michael about a week ago. Are you happy this is resolved?

**Comment by Kuchenpirat** [comment]
Oh i completly forgot about this. Works now. Thx @michael-genson 😊
