### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by AlphaDog01** [mealie-recipes/mealie#2689]
I have a question in regards to the image api request. This just returns raw webp what am I supposed to do with that to get an image to display in my web app? This seems like it should be simple to do but seems overly complicated.

**Comment by boc-the-git** [comment]
I'm not sure this is a Mealie issue/question, but rather general software development. I'll admit I don't know the answer, or I'd try to give it. Though with a Google search I could find how to display webp in html.
Some other things you could look into is how Mealie renders the images, as well as how Home Assistant renders images - specifically I display the webp images (from my `baseurl/api/media/recipes/{{ state_attr('sensor.mealie_todays_dinner', 'id') }}/images/min-original.webp` URL) using HA's 'Generic Camera' integration.

If you think the information has a place in Mealie's documentation, please raise a PR to add it once you've found it.

In future, please follow issue/PR templates when raising one.
