### ISSUE TITLE
[BUG] - Migration problem - error when mealie api start

### ISSUE THREAD

**Issue by Kanzll** [mealie-recipes/mealie#2693]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

Hello,
I'm tried to make un automatic update within docker-compose upgrade without seeing documentation, I have a 1.0.0-beta5, it's worked well.
the installation obviously didn't work, I have this error when api try to start :
`alembic.script.revision.ResolutionError: No such revision or branch 'dded3119c1fe'`
I tried to restore my previous version, no way ! I have the same error even with a new installation.
can you tell me how I can restore my mealie environment please :)
Thanks

### Steps to Reproduce

1) past docker-compose content from https://nightly.mealie.io/documentation/getting-started/installation/sqlite/
2) Change frontend port to match with my reverse-proxy
3) docker-compose pull
4) docker-compose up

### Please provide relevent logs

Recreating mealie-api    ... done
Starting mealie-frontend ... done
Attaching to mealie-frontend, mealie-api
mealie-frontend    | {"level":"info","ts":1698537591.0688343,"msg":"using provided configuration","config_file":"/app/Caddyfile","config_adapter":""}
mealie-frontend    | {"level":"warn","ts":1698537591.075361,"msg":"Caddyfile input is not formatted; run the 'caddy fmt' command to fix inconsistencies","adapter":"caddyfile","file":"/app/Caddyfile","line":36}
mealie-frontend    | {"level":"warn","ts":1698537591.0765612,"logger":"admin","msg":"admin endpoint disabled"}
mealie-frontend    | {"level":"warn","ts":1698537591.0770347,"logger":"http","msg":"automatic HTTPS is completely disabled for server","server_name":"srv0"}
mealie-frontend    | {"level":"info","ts":1698537591.172346,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0005ce9a0"}
mealie-frontend    | {"level":"info","ts":1698537591.1733806,"msg":"autosaved config (load with --resume flag)","file":"/root/.config/caddy/autosave.json"}
mealie-frontend    | {"level":"info","ts":1698537591.173395,"msg":"serving initial configuration"}
mealie-frontend    | {"level":"info","ts":1698537591.1857636,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/root/.local/share/caddy"}
mealie-frontend    | {"level":"info","ts":1698537591.1858363,"logger":"tls","msg":"finished cleaning storage units"}
mealie-frontend    | Successfully started Caddy (pid=10) - Caddy is running in the background
mealie-api         | Production
mealie-frontend    | yarn run v1.22.19
mealie-frontend    | $ nuxt start -p 3001
mealie-api         | 
mealie-api         |     User uid:    1000
mealie-api         |     User gid:    1000
mealie-api         |     
mealie-frontend    | ℹ [HPM] Proxy created: api  -> http://mealie-api:9000
mealie-frontend    | ℹ [HPM] Proxy rewrite rule created: "api" ~> "/api"
mealie-frontend    | ℹ [HPM] Proxy created: /api  -> http://mealie-api:9000
mealie-frontend    | ℹ Listening on: http://172.23.0.2:3001/
mealie-api         | INFO: 28-Oct-23 16:00:14 	Database connection established.
mealie-api         | INFO: 28-Oct-23 16:00:14 	Context impl SQLiteImpl.
mealie-api         | INFO: 28-Oct-23 16:00:14 	Will assume non-transactional DDL.
mealie-api         | INFO: 28-Oct-23 16:00:14 	Migration needed. Performing migration...
mealie-api         | INFO: 28-Oct-23 16:00:14 	Context impl SQLiteImpl.
mealie-api         | INFO: 28-Oct-23 16:00:14 	Will assume non-transactional DDL.
mealie-api         | Traceback (most recent call last):
mealie-api         |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/base.py", line 233, in _catch_revision_errors
mealie-api         |     yield
mealie-api         |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/base.py", line 443, in _upgrade_revs
mealie-api         |     for script in reversed(list(revs))
mealie-api         |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/revision.py", line 799, in iterate_revisions
mealie-api         |     revisions, heads = fn(
mealie-api         |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/revision.py", line 1454, in _collect_upgrade_revisions
mealie-api         |     current_revisions = self.get_revisions(lower)
mealie-api         |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/revision.py", line 527, in get_revisions
mealie-api         |     return sum([self.get_revisions(id_elem) for id_elem in id_], ())
mealie-api         |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/revision.py", line 527, in <listcomp>
mealie-api         |     return sum([self.get_revisions(id_elem) for id_elem in id_], ())
mealie-api         |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/revision.py", line 552, in get_revisions
mealie-api         |     return tuple(
mealie-api         |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/revision.py", line 553, in <genexpr>
mealie-api         |     self._revision_for_ident(rev_id, branch_label)
mealie-api         |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/revision.py", line 624, in _revision_for_ident
mealie-api         |     raise ResolutionError(
mealie-api         | alembic.script.revision.ResolutionError: No such revision or branch 'dded3119c1fe'
mealie-api         | 
mealie-api         | The above exception was the direct cause of the following exception:
mealie-api         | 
mealie-api         | Traceback (most recent call last):
mealie-api         |   File "/app/mealie/db/init_db.py", line 108, in <module>
mealie-api         |     main()
mealie-api         |   File "/app/mealie/db/init_db.py", line 94, in main
mealie-api         |     command.upgrade(alembic_cfg, "head")
mealie-api         |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/command.py", line 322, in upgrade
mealie-api         |     script.run_env()
mealie-api         |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/base.py", line 569, in run_env
mealie-api         |     util.load_python_file(self.dir, "env.py")
mealie-api         |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
mealie-api         |     module = load_module_py(module_id, path)
mealie-api         |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
mealie-api         |     spec.loader.exec_module(module)  # type: ignore
mealie-api         |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
mealie-api         |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
mealie-api         |   File "/app/alembic/env.py", line 77, in <module>
mealie-api         |     run_migrations_online()
mealie-api         |   File "/app/alembic/env.py", line 71, in run_migrations_online
mealie-api         |     context.run_migrations()
mealie-api         |   File "<string>", line 8, in run_migrations
mealie-api         |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/runtime/environment.py", line 853, in run_migrations
mealie-api         |     self.get_context().run_migrations(**kw)
mealie-api         |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/runtime/migration.py", line 611, in run_migrations
mealie-api         |     for step in self._migrations_fn(heads, self):
mealie-api         |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/command.py", line 311, in upgrade
mealie-api         |     return script._upgrade_revs(revision, rev)
mealie-api         |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/base.py", line 431, in _upgrade_revs
mealie-api         |     with self._catch_revision_errors(
mealie-api         |   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
mealie-api         |     self.gen.throw(typ, value, traceback)
mealie-api         |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/alembic/script/base.py", line 265, in _catch_revision_errors
mealie-api         |     raise util.CommandError(resolution) from re
mealie-api         | alembic.util.exc.CommandError: Can't locate revision identified by 'dded3119c1fe'

### Mealie Version

tested with 1.0.0beta5 and 1.0.0RC1.1

### Deployment

Docker (Linux)

**Comment by boc-the-git** [comment]
Your logs don't indicate that you're using the compose file from the page you've linked.

Please share your full docker-compose file with only sensitive info redacted.

This post might help you: https://github.com/mealie-recipes/mealie/issues/2685#issuecomment-1780200491

**Comment by boc-the-git** [comment]
In future, please honestly answer the check list for the bug report. We can't support you without accurate information.

**Comment by Kanzll** [comment]
Thanks @boc-the-git for you reply, I can confirm that I have been looking for a solution for two days, I have not found anything similar in the tracker; maybe I didn't use the right keywords.
You are right I exposes two scenario in the same request, my faulty migration and new installation. 
I'll try the solution on post #2685  and I'll let you know.

**Comment by boc-the-git** [comment]
My comment re the check list was in terms of being able to replicate on the demo site.

The comment I've linked is almost exactly targeted at your scenario. Hope it helps.

**Comment by Kanzll** [comment]
Thanks @boc-the-git  Your are right I see my mistake sorry about that !
I reviewed my docker-compose.yaml and did the modification, but I got the same error with new installation `Aborted (core dumped)`

**docker-compse.yaml:**

```
version: "3.7"
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:nightly
    container_name: mealie
    ports:
      - "9925:9000"
    volumes:
      - mealie-data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/Anchorage
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://XXXXX
    # ENV EMAIL
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_FROM_NAME=Cookbook
      - SMTP_AUTH_STRATEGY=TLS
      - SMTP_FROM_EMAIL=XXXXX
      - SMTP_USER=XXXXX
      - SMTP_PASSWORD=XXXXX
    restart: always

volumes:
  mealie-data:
```

**here is my complete log :**

> mealie    | INFO: 28-Oct-23 17:35:23 	Database connection established.
> mealie    | INFO: 28-Oct-23 17:35:23 	Context impl SQLiteImpl.
> mealie    | INFO: 28-Oct-23 17:35:23 	Will assume non-transactional DDL.
> mealie    | WARNING: 28-Oct-23 17:35:24 	"get_all" method is deprecated; use "page_all" instead
> mealie    | INFO: 28-Oct-23 17:35:24 	No food found with slug: 'dairy-products-and-dairy-substitutes' skipping fix
> mealie    | INFO:     Started server process [15]
> mealie    | INFO:     Waiting for application startup.
> mealie    | INFO: 28-Oct-23 17:35:32 	-----SYSTEM STARTUP----- 
> mealie    | 
> mealie    | INFO: 28-Oct-23 17:35:32 	------APP SETTINGS------
> mealie    | INFO: 28-Oct-23 17:35:32 	{
> mealie    |     "theme": {
> mealie    |         "light_primary": "#E58325",
> mealie    |         "light_accent": "#007A99",
> mealie    |         "light_secondary": "#973542",
> mealie    |         "light_success": "#43A047",
> mealie    |         "light_info": "#1976D2",
> mealie    |         "light_warning": "#FF6D00",
> mealie    |         "light_error": "#EF5350",
> mealie    |         "dark_primary": "#E58325",
> mealie    |         "dark_accent": "#007A99",
> mealie    |         "dark_secondary": "#973542",
> mealie    |         "dark_success": "#43A047",
> mealie    |         "dark_info": "#1976D2",
> mealie    |         "dark_warning": "#FF6D00",
> mealie    |         "dark_error": "#EF5350"
> mealie    |     },
> mealie    |     "PRODUCTION": true,
> mealie    |     "BASE_URL": "https://XXXXX",
> mealie    |     "STATIC_FILES": "/spa/static",
> mealie    |     "IS_DEMO": false,
> mealie    |     "API_PORT": 9000,
> mealie    |     "API_DOCS": true,
> mealie    |     "TOKEN_TIME": 48,
> mealie    |     "LOG_LEVEL": "INFO",
> mealie    |     "GIT_COMMIT_HASH": "2764d9e2dd5ab0e11aebe3b7217d61633a279c4a",
> mealie    |     "ALLOW_SIGNUP": true,
> mealie    |     "SECURITY_MAX_LOGIN_ATTEMPTS": 5,
> mealie    |     "SECURITY_USER_LOCKOUT_TIME": 24,
> mealie    |     "DB_ENGINE": "sqlite",
> mealie    |     "DEFAULT_GROUP": "Home",
> mealie    |     "DEFAULT_EMAIL": "changeme@example.com",
> mealie    |     "SMTP_HOST": "smtp.gmail.com",
> mealie    |     "SMTP_PORT": "587",
> mealie    |     "SMTP_FROM_NAME": "XXXXX",
> mealie    |     "SMTP_FROM_EMAIL": "XXXXX",
> mealie    |     "SMTP_AUTH_STRATEGY": "TLS",
> mealie    |     "LDAP_AUTH_ENABLED": false,
> mealie    |     "LDAP_SERVER_URL": null,
> mealie    |     "LDAP_TLS_INSECURE": false,
> mealie    |     "LDAP_TLS_CACERTFILE": null,
> mealie    |     "LDAP_ENABLE_STARTTLS": false,
> mealie    |     "LDAP_BASE_DN": null,
> mealie    |     "LDAP_QUERY_BIND": null,
> mealie    |     "LDAP_QUERY_PASSWORD": null,
> mealie    |     "LDAP_USER_FILTER": null,
> mealie    |     "LDAP_ADMIN_FILTER": null,
> mealie    |     "LDAP_ID_ATTRIBUTE": "uid",
> mealie    |     "LDAP_MAIL_ATTRIBUTE": "mail",
> mealie    |     "LDAP_NAME_ATTRIBUTE": "name",
> mealie    |     "TESTING": false
> mealie    | }
> mealie    | INFO:     Application startup complete.
> mealie    | Aborted (core dumped)

**Comment by Kanzll** [comment]
Thanks @boc-the-git  the problem was same than [#2685 (comment)](https://github.com/mealie-recipes/mealie/issues/2685#issuecomment-1780200491)
My last error apparently concenrn my ubuntu/docker version, I added following instruction according this [link ](https://docs.linuxserver.io/FAQ/)(resolution #_2)
```
    security_opt:
      - seccomp=unconfined
```
problem resolved !

**Comment by boc-the-git** [comment]
Awesome, glad you're up and running @kanzn!
