### ISSUE TITLE
[BUG] - Bookmarklet error 404 with demo

### ISSUE THREAD

**Issue by Marly212** [mealie-recipes/mealie#2705]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

When creating a bookmarklet, like in the doc, with the mealie variable set to https://demo.mealie.io I'm getting an error 404 page not found error. I tried it with the demo address cause with my instance I got the same error and I wanted to make sure I didn't do anything wrong.

### Steps to Reproduce

1. Create a bookmarklet with the linked [bookmarklet maker](https://caiorss.github.io/bookmarklet-maker/)
2. Drag and drop the blue button to your browser bar.
3. I tested it with [this ](https://www.allrecipes.com/recipe/221160/pan-roasted-chicken-with-lemon-garlic-brussels-sprouts-and-potatoes/)recipe and got the error

### Please provide relevent logs

Not sure which logs I can provide in this case with the demo url

### Mealie Version

Build: "80968b02bb1068eaba74e035691dcf7245563342"

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Thanks for this, just opened a PR to get it fixed. Here's the fixed one:
```js
var url = document.URL;
var mealie = "http://localhost:8080";
var group_slug = "home" // Change this to your group slug. You can obtain this from your URL after logging-in to Mealie
var use_keywords= "&use_keywords=1" // Optional - use keywords from recipe - update to "" if you don't want that
var edity = "&edit=1" // Optional - keep in edit mode - update to "" if you don't want that
var dest = mealie + "/r/create/url?recipe_import_url=" + url + use_keywords + edity;

if (mealie.slice(-1) === "/") {
    mealie = mealie.slice(0, -1)
}
var dest = mealie + "/g/" + group_slug + "/r/create/url?recipe_import_url=" + url + use_keywords + edity;
window.open(dest, "_blank");
```

**Comment by Marly212** [comment]
Thanks for the fixed one. Its fixed for my instance
