### ISSUE TITLE
[BUG] - Going back after url import creates duplicate recipes

### ISSUE THREAD

**Issue by jaredcat** [mealie-recipes/mealie#2711]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [x] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

After importing a recipe by URL, if a user hits back on their browser the recipe is imported again.

### Steps to Reproduce

1. Go to https://demo.mealie.io/recipe/create/url
2. Paste some random recipe. Example: https://www.allrecipes.com/chef-johns-best-meatloaf-recipes-8386699
3. Click "Create"
4. Go back in your browser
Repeat step 4 and create as many duplicates as you want

### Please provide relevent logs

https://github.com/mealie-recipes/mealie/blob/mealie-next/frontend/pages/g/_groupSlug/r/create/url.vue#L106

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
Duplicate 

- https://github.com/mealie-recipes/mealie/issues/2267
