### ISSUE TITLE
[BUG] Docker container does not respond to SIGTERM and only stop at SIGKILL

### ISSUE THREAD

**Issue by paladincorners** [mealie-recipes/mealie#2723]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

When you stop the Mealie container with "docker stop ...", Mealie does not respond to the SIGTERM until after the 10 second default docker timeout, when docker issues a SIGKILL.

The solution should be to add "exec" to lines 52 and 54 of entry.sh for docker. Explanation here:
https://madflojo.medium.com/shutdown-signals-with-docker-entry-point-scripts-5e560f4e2d45

### Steps to Reproduce

1) Launch Mealie container
2) docker stop <Mealie container name or ID>
3) Observe that Mealie does not stop until after 10 seconds
4) Run 'docker ps -a'
5) Observe that Mealie container status is exited (137), with return code 137 signifying it exited due to SIGKILL

### Please provide relevent logs

No relevant logs

### Deployment

Docker (Linux)

**Comment by boc-the-git** [comment]
@paladincorners thanks for raising this. It sounds like you've got a good understanding of it; is this something you're able to raise a PR for?

I note you've not included version information - I assume you've tested this on at least RC1.1, if not the nightly image?

**Comment by paladincorners** [comment]
Hi, yes this is on the image ghcr.io/mealie-recipes/mealie:v1.0.0-RC1.1.

After some more research, it seems like there's more than one way to fix this. For example using 'tiny' in the docker image to launch the the entrypoint under a PID other than 1. This may also resolve other issues with the entrypoint signal handling which may not be evident.

In the meantime, adding `--init` to your docker run command or `init: true` to your docker compose file fixes this. This uses `tiny` to launch the entrypoint script under a PID other than 1. I have tested this and `docker compose stop` now stops immediately.

 I will have to first look into building from source to test and submit a pull request for a solution that does not require using `--init` in the run command into the entrypoint script or Dockerfile,

**Comment by Sonlis** [comment]
I noticed the same issue in my environment.
Why not simply add `exec` to the init scripts, as proposed in the issue description? It's a solution without tradeoff used by popular open-source docker images, which does not require the user to add arguments to their docker-compose file / docker command.
