### ISSUE TITLE
Conversion of temp/weights

### ISSUE THREAD

**Issue by minkshaman** [mealie-recipes/mealie#2731]
### Discussed in https://github.com/mealie-recipes/mealie/discussions/2730

<div type='discussions-op-text'>

<sup>Originally posted by **minkshaman** November 18, 2023</sup>
### First Check

- [X] I used the GitHub search to find a similar requests and didn't find it.
- [X] Checked the [tasks tagged](https://github.com/hay-kot/mealie/issues?q=is%3Aissue+is%3Aopen+label%3Atask+) issues and verified my feature is not covered

### Please provide a concise description of the problem that would be addressed by this feature.

I've had many recipes successfully imported from URL, but have found they are in imperial weights and fahrenheit.

I have to manually adjust these when entering the recipe.

### Please provide a concise description of the feature that would resolve your issue.

It would be very useful to have a function that can scan through all text (ingredients and method) and alert if it finds something that appears to be either a temperature or a measurement, and then prompt for if it should be metric/Celsius or imperial/fahrenheit.

**Comment by boc-the-git** [comment]
Can you provide some sample URLs for this @minkshaman? I'm keen to have some reference recipes.

**Comment by boc-the-git** [comment]
(to be clear, I'm not starting development work on this, just wanting to understand the scenario)

**Comment by minkshaman** [comment]
All good.

https://www.allrecipes.com/recipe/42176/all-american-roast-beef/

This is a pretty good example.
So in this, I’d like it to prompt and suggest 450g instead of 1lb (or the exact to 2 places? Whatever’s easiest.)

For temps, it should look at the temperature and prompt me if it needs to be C or F and change the temperature accordingly.

if you wanted to be fancy, you could probably put something that looks for Imperial weights and use that to prompt? I don’t know if it’s consistent enough though.
