### ISSUE TITLE
[BUG] - Tools cannot be "on Hand"

### ISSUE THREAD

**Issue by Kuchenpirat** [mealie-recipes/mealie#2738]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When creating a Tool and checking the "on Hand" Button the tool gets created but when checking the database the "on Hand" field is set to false. 

Not checking the Checkbox leads to the same issue. 

Furthermore i have not found a single option to view or change the "on Hand" status of a tool. So currently this data entry cannot be set by the user and cannot be checked or used anywhere. 

### Steps to Reproduce

- create a tool
  - check "on Hand" checkbox
-check database for the entries on "on_hand" which should all be set to false

Cannot be reproduced on the demo site by me as i do not have access to the database

### Please provide relevant logs

127.0.0.1:0 - "POST /api/organizers/tools HTTP/1.1" 201

Logs just show that the tool has been created

### Mealie Version

Version
nightly

Build
[25898496828a04d5a384ffd33b2cb79560978a76](https://github.com/hay-kot/mealie/commit/25898496828a04d5a384ffd33b2cb79560978a76)

### Deployment

Docker (Linux), Docker (Windows)

**Comment by Kuchenpirat** [comment]
Tools get created [here](https://github.com/mealie-recipes/mealie/blob/b7cc5c066658bf4473af83d0a5af80c4aaab4ba8/frontend/components/Domain/Recipe/RecipeOrganizerDialog.vue#L135C15-L135C15) with just their name

**Comment by michael-genson** [comment]
FYI - you can change the on hand property from a recipe. Add the tool to a recipe, then use that checkbox.

However, this doesn't resolve the bug, it should be able to be set upon creation, too

**Comment by Kuchenpirat** [comment]
maybe i missunderstand what you are saying, but if i set an existing tool as required in an recipe, it will still display false in the database. 

Same when i am creating an tool inside of the recipe editor and check the "on Hand" checkbox

**Comment by michael-genson** [comment]
After adding the tool to a recipe, you have to check the tool's checkbox:

![image](https://github.com/mealie-recipes/mealie/assets/71845777/3689a28d-a94b-46e9-ba2a-ee2dfb9cd085)

Then it will save it to the db:

![image](https://github.com/mealie-recipes/mealie/assets/71845777/b07bd74a-584e-4dcf-b6f1-91f9c9bfa2af)

**Comment by Kuchenpirat** [comment]
Yeah, i have just found it :D
