### ISSUE TITLE
Possible to backup recipes outside of mealie?

### ISSUE THREAD

**Issue by techrivertree** [mealie-recipes/mealie#2758]
I upgraded my network from a wifi router to a UI dream machine and UI access point. I have the same static IP assigned to my RPI mealie server but when I try to access the web interface, page cannot be displayed.

I dug through the rootfs and bootfs folders but I could not find the recipes. Is there any way to backup the recipes outside of mealie? I think I might have to reinstall.

**Comment by michael-genson** [comment]
Can we see your docker compose? If you're mounting your volume locally all your data is in there.

**Comment by techrivertree** [comment]
I do not use docker. What folder is the recipe data in?

**Comment by michael-genson** [comment]
If you're not using docker, I can't really help, it's completely dependent on your deployment details

**Comment by boc-the-git** [comment]
We'll need a lot more info to be able to provide any help here.

**Comment by techrivertree** [comment]
Delete this thread, I am starting over (reinstalling). I know I lost everything, oh well.

**Comment by boc-the-git** [comment]
If all you did was change your router, I can't fathom how that would impact a Mealie instance in any substantial way.
We've got no info to be able to help you with though, so will close this as you've requested.
