### ISSUE TITLE
[BUG] - Display error: Buttons on meal planner datepicker invisible

### ISSUE THREAD

**Issue by ghuser238490** [mealie-recipes/mealie#2763]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

In the current nightly the buttons on the meal planner datepicker on the top left and right are invisible:
![Screenshot](https://github.com/mealie-recipes/mealie/assets/80325288/0fbf35f4-756e-489c-af00-64f2da2b5c5b)

### Steps to Reproduce

Open Meal Planner, then select date range.

### Please provide relevant logs

Please see screenshot above.

### Mealie Version

Version: nightly
Build: 340841b37a3afa7df808547d64ba5dd5c83c5daa

### Deployment

Docker (Linux)

**Comment by Kuchenpirat** [comment]
You ticked the checkbox that said you can reproduce this on the demo site. 

I can neither reproduce this on the demo site, nor my own mealie instance. Have you tried a different browser to see if the problem persists?

**Comment by boc-the-git** [comment]
I'd echo that, having just tested on my instance (which is up to date as of yesterday), looking in the PWA it looks perfectly normal.
I'm using dark mode.

Perhaps there's more detail you can provide to help confirm this.

**Comment by ghuser238490** [comment]
It might be a Mac issue - I'm able to reproduce it on my own server and on the demo site with Safari 17.1 on macOS 14.1.1 and iOS 17.1.1 (both Safari and PWA).
Just noticed that the "Remember me" checkbox on the login page is invisible, too.

**Comment by Kuchenpirat** [comment]
just checked on my ipad to make sure. I cannot reproduce the missing checkbox, nor the arrows.

**Comment by boc-the-git** [comment]
I'd note I'm running the exact same version as @ghuser238490 reports, https://github.com/mealie-recipes/mealie/commit/340841b37a3afa7df808547d64ba5dd5c83c5daa

No issues in dark mode on PWA, nor dark or light mode on Chrome.

Can you share your config as reported in the logs, it's one of the very first messages after boot. I'm wanting to rule out any theming variables

**Comment by Kuchenpirat** [comment]
if it can be reproduced on the demo (as indicated above) it should not be that version specific and the env variables should also not be set wrongly on the demo site. 
but having the config cannot hurt

**Comment by ghuser238490** [comment]
Thank you guys for looking into that! Turned out that this is not a mealie issue. 

Apparently there is an issue with one of the default pi-hole ad block lists:
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

Since yesterday the domain cdn.jsdelivr.net is on that list, here's the bug report:
https://github.com/StevenBlack/hosts/issues/2515

 Whitelisting cdn.jsdelivr.net resolves that screen error.

**Comment by Kuchenpirat** [comment]
thanks for reporting back to us. 
And could you on your way out close the issue 😉

**Comment by ghuser238490** [comment]
I can confirm that cdn.jsdelivr.net is finally removed from the ad list.
