### ISSUE TITLE
[BUG] - Clarify docker image confusion

### ISSUE THREAD

**Issue by 0verEngineer** [mealie-recipes/mealie#2768]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

A short time ago i converted my mealie instance from the old combined image to the separate front and backend images hosted on dockerhub. I just wanted to update mealie and it seems there were changed to the images AGAIN....

1. The dockerhub images are not updated, why?!
2. I cannot find the frontend and backend images in the ghcr, did mealie again change this to a combined image?!
3. The readme does not clarify this changes, this leaves many users confused and many users will run very old versions because they do not look it up.

Please stop changing everything about the project every few months, it is super annoying to keep up with this confusing, non-documented changes.

### Steps to Reproduce

...

### Please provide relevant logs

...

### Deployment

Docker (Linux)

**Comment by boc-the-git** [comment]
Please don't raise bug tickets for things that are not bugs/defects. Posts like this are not constructive.

I suggest you read the RC1 release notes: https://github.com/mealie-recipes/mealie/releases/tag/v1.0.0-RC1

If you have specific questions, the Discord is a great place to get help. If there's issues with the documentation that could be improved, we'd welcome a PR.

As is common for all software, changes are likely before a v1 release.

**Comment by Kuchenpirat** [comment]
hey, as mealie is still in beta, there are a certain amount of breaking changes that cannot be avoided to build the best version of mealie possible. 

1. The image on dockerhub has been deprecated as of a few month ago and mealie is now published on ghcr exclusivly. 

2. Mealie is no longer split in backend and frontend containers, instead the frontend has been migrated into the backend container to allow people to much easier host their own instance without having to take much care of networking api calls within mealie.

3. As literaly the first paragraph in the getting started states, mealie is still in beta and a work in progress, so there are changes to be expected. The release notes of [RC1](https://github.com/mealie-recipes/mealie/releases/tag/v1.0.0-RC1) state  clearly that mealie moved to a single container setup, so there is not much more the developers can do

**Comment by 0verEngineer** [comment]
> Please don't raise bug tickets for things that are not bugs/defects. Posts like this are not constructive.
> 
> I suggest you read the RC1 release notes: https://github.com/mealie-recipes/mealie/releases/tag/v1.0.0-RC1
> 
> If you have specific questions, the Discord is a great place to get help. If there's issues with the documentation that could be improved, we'd welcome a PR.
> 
> As is common for all software, changes are likely before a v1 release.

This is an Issue, so i created a Issue, for me and all other confused users that check the issues page on github a issue like this is VERY CONSTRUCTIVE.

**Comment by 0verEngineer** [comment]
> hey, as mealie is still in beta, there are a certain amount of breaking changes that cannot be avoided to build the best version of mealie possible.
> 
>     1. The image on dockerhub has been deprecated as of a few month ago and mealie is now published on ghcr exclusivly.
> 
>     2. Mealie is no longer split in backend and frontend containers, instead the frontend has been migrated into the backend container to allow people to much easier host their own instance without having to take much care of networking api calls within mealie.
> 
>     3. As literaly the first paragraph in the getting started states, mealie is still in beta and a work in progress, so there are changes to be expected. The release notes of [RC1](https://github.com/mealie-recipes/mealie/releases/tag/v1.0.0-RC1) state  clearly that mealie moved to a single container setup, so there is not much more the developers can do

Thanks a lot, but this should be linked in the Readme somewhere.
