### ISSUE TITLE
[BUG] - UI Checkboxes are missing after first time nightly run/setup

### ISSUE THREAD

**Issue by brent20** [mealie-recipes/mealie#2771]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Check boxes that are part of the material UI design elements are not appearing. I'm a first time/new mealie user and I noticed this in my nightly docker container that I just spun up and noticed it on demo.meali.io. Checkboxes are still working, the box icon is just missing from the page. This shows on the grocery lists, recipes pages, etc. 

Screenshots from demo.mealie.io:

![image](https://github.com/mealie-recipes/mealie/assets/1820253/e75fd722-78f4-4f41-9ca3-61d01f3146e3)

the grey circle shows when my cursor was clicked (part of material UI)
![image](https://github.com/mealie-recipes/mealie/assets/1820253/f7047e41-46fe-4dec-8ace-4df57ed738b7)

### Steps to Reproduce

Run the latest nightly build, check for checkboxes where they are supposed to be.

### Please provide relevant logs

NA

### Mealie Version

**Details**
Version: nightly
Build: 0a00a6ea0d05d2dd944dd9cc6713156dc767e1ed
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: postgres
Recipe Scraper Version: 14.42.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: No
Docker Volumes: success

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Are you running pihole or some other DNS-level adblocker? Someone in Discord reported a similar issue the other day and it turned out to be a network issue.

Checkboxes look fine on my end; from the demo:

![image](https://github.com/mealie-recipes/mealie/assets/71845777/c7e2e241-a962-419a-aa8e-d3dedac35c93)

**Comment by michael-genson** [comment]
Similar GH issue: https://github.com/mealie-recipes/mealie/issues/2763

**Comment by brent20** [comment]
Ah, shoot- https://github.com/mealie-recipes/mealie/issues/2763#issuecomment-1827620982

This person didn't use the same UI terms I was searching for. I am using Pi-Hole locally. Let me give this another go! thank you!

**Comment by brent20** [comment]
User error - Pi-Hole was blocking cdn.jsdelivr.net
Thanks!!
