### ISSUE TITLE
[BUG] - Ingredient checkboxs missing

### ISSUE THREAD

**Issue by mantellian** [mealie-recipes/mealie#2775]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

No matter what device or browser I use to access mealie, even the demo site, the ingredient check boxes are missing.
![Screenshot 2023-11-29 160842](https://github.com/mealie-recipes/mealie/assets/83597208/0144731d-617f-40fd-a2d3-8d6fd7c620ef)

### Steps to Reproduce

clicking on any recipe 

### Please provide relevant logs

INFO:     10.1.1.5:0 - "GET /api/media/recipes/5e5278df-40e4-40c4-9291-a9698da6bf55/images/min-original.webp?rnd=1&version=MIug HTTP/1.1" 404 Not Found
     
INFO:     10.1.1.5:0 - "GET /api/recipes?page=3&perPage=32&orderBy=created_at&orderDirection=desc&paginationSeed=1701295540042&searchSeed=1701295540042&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/admin/about HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/admin/about/check HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /_nuxt/27eabd6.js HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /admin/site-settings HTTP/1.1" 307 Temporary Redirect
INFO:     10.1.1.5:0 - "GET /admin/site-settings/ HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /_nuxt/70a319d.js HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /_nuxt/98d67ff.js HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /_nuxt/1174c0e.js HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /_nuxt/6fbde07.js HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /_nuxt/5f4b5be.js HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /_nuxt/170bca6.js HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /icons/android-chrome-maskable-512x512.png HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /favicon.ico HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/app/about/theme HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/users/self HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/admin/about/check HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/admin/about HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/users/2685a965-b95a-48ae-9a11-a240bd13e7fd/profile.webp?cacheKey=pz8Z HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /_nuxt/img/admin-site-settings.09a9edb.svg HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/admin/about/docker/validate HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/docker/validate.txt HTTP/1.1" 200 OK
INFO:     127.0.0.1:37312 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:57866 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:52588 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:47468 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/organizers/tags?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/groups/cookbooks?page=1&perPage=-1&orderBy=position&orderDirection=asc HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/organizers/categories?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/foods?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
     
INFO:     10.1.1.5:0 - "GET /api/recipes?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1701295659151&searchSeed=1701295659151&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/5e5278df-40e4-40c4-9291-a9698da6bf55/images/min-original.webp?rnd=1&version=MIug HTTP/1.1" 404 Not Found
INFO:     10.1.1.5:0 - "GET /api/media/recipes/ff766c6a-7957-4c54-8105-c0be22b8e405/images/min-original.webp?rnd=1&version=AAel HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/8f3d3425-8b25-4f8e-b162-8b49dd6b9731/images/min-original.webp?rnd=1&version=zKHK HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/446ae3a3-81cf-444c-ba82-3800fbc31de9/images/min-original.webp?rnd=1&version=fVem HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/27cb7420-c9d3-4fba-a7c7-a068fef18296/images/min-original.webp?rnd=1&version=102 HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/f9547aff-9d01-4b1b-b74d-e5f2501160f1/images/min-original.webp?rnd=1&version=R6ef HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/78d0fff2-92e8-48c3-bf35-50e99c5eef2e/images/min-original.webp?rnd=1&version=eWPM HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/f58e4ee4-cef9-4bae-80b4-f40c0fca8f41/images/min-original.webp?rnd=1&version=2VKt HTTP/1.1" 200 OK
     
INFO:     10.1.1.5:0 - "GET /api/recipes?page=3&perPage=32&orderBy=created_at&orderDirection=desc&paginationSeed=1701295659151&searchSeed=1701295659151&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/79193435-4154-4fa3-9502-06a55218f49e/images/min-original.webp?rnd=1&version=02nL HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/d9bbf01b-b949-4237-a1ae-a520e3c07905/images/min-original.webp?rnd=1&version=aS0O HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/2dbb47f8-6eb7-47cc-8877-59eec1eb85ff/images/min-original.webp?rnd=1&version=m9UE HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/a703b76e-131a-41ef-aaa0-7e24f46e4110/images/min-original.webp?rnd=1&version=pOiF HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/41d82dc2-f606-4661-a539-2da34826ad50/images/min-original.webp?rnd=1&version=GnxT HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/c72be433-8e51-44fe-9954-3c4c12fadd99/images/min-original.webp?rnd=1&version=p9PU HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/c37fdfd3-05da-4fe1-bfe3-75cc71bd6f73/images/min-original.webp?rnd=1&version=WDP5 HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/c0fc5465-fa32-4223-8122-c9ba77e5340b/images/min-original.webp?rnd=1&version=saal HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/f2452ab2-4a76-4c56-a608-0367d1821507/images/min-original.webp?rnd=1&version=qrAV HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/2ce4a421-a08e-40e4-83a7-13fcaa97e0fb/images/min-original.webp?rnd=1&version=JOAm HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/8d3fbde1-1da3-4e5e-8e50-e137e449bfb8/images/min-original.webp?rnd=1&version=jMGO HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/0d08d9ba-557e-43c5-a3e5-c22092eb05d4/images/min-original.webp?rnd=1&version=SsAq HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/82273333-7618-4d76-97eb-5d5bbba4a577/images/min-original.webp?rnd=1&version=e3ZI HTTP/1.1" 404 Not Found
INFO:     10.1.1.5:0 - "GET /api/media/recipes/29902a9e-c9db-453b-b932-ecd720f93b1b/images/min-original.webp?rnd=1&version=D9gJ HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/506d25c9-baf2-4f05-a76e-a32cffad65eb/images/min-original.webp?rnd=1&version=K0EQ HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/e52efecb-6da4-4a8d-9ae5-192f334896f8/images/min-original.webp?rnd=1&version=234 HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/77d43d74-1ca3-4166-9479-b318c287c045/images/min-original.webp?rnd=1&version= HTTP/1.1" 404 Not Found
INFO:     10.1.1.5:0 - "GET /api/media/recipes/9466d1e8-25fd-4324-8f6c-546aa5232706/images/min-original.webp?rnd=1&version=K2R2 HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/5ad6042a-e072-4ad9-be78-1739588c3ec4/images/min-original.webp?rnd=1&version=cxn5 HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/be865710-3541-4d0a-aad7-f8aa20d88e0d/images/min-original.webp?rnd=1&version=188 HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/693e8420-2b2a-46e8-a8ce-d08046b25985/images/min-original.webp?rnd=1&version=no%20image HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/2f8dd336-e256-41ef-9b96-0e9bd9f9c986/images/min-original.webp?rnd=1&version= HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/2cd70975-fc09-444b-af8f-3b3eba2b18aa/images/min-original.webp?rnd=1&version=sDQh HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/e03f3633-fc21-47ae-9bcd-540f95d3beae/images/min-original.webp?rnd=1&version=OKy1 HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/1515527d-f63f-4e2e-a08f-09c914f82f4a/images/min-original.webp?rnd=1&version= HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/c0281b78-99a5-4220-bfbf-cd9e4458aaeb/images/min-original.webp?rnd=1&version=197 HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/35435b95-623a-4f2a-812f-0cc857b95622/images/min-original.webp?rnd=1&version= HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/f5882871-7312-4603-9c3b-e48a14632fb3/images/min-original.webp?rnd=1&version=ePgp HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/7f84aad9-7d80-4fe4-a485-1dcc4a5a51e7/images/min-original.webp?rnd=1&version=170 HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/232514a9-a029-474e-9b0c-1041772905c5/images/min-original.webp?rnd=1&version=pZC4 HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/e6454314-2707-47dd-8646-febfa0996e0d/images/min-original.webp?rnd=1&version=ygPc HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/d695942d-07ee-42ef-b96d-5f9f1be39565/images/min-original.webp?rnd=1&version= HTTP/1.1" 200 OK
INFO:     127.0.0.1:46696 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/recipes/marinara-sauce HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/recipes/9466d1e8-25fd-4324-8f6c-546aa5232706/images/original.webp?rnd=1&version=K2R2 HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /_nuxt/fonts/Roboto-700-latin35.227c931.woff2 HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/recipes/marinara-sauce/comments HTTP/1.1" 200 OK
INFO:     127.0.0.1:52050 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:48794 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:45924 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/admin/about/check HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/admin/about HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /_nuxt/img/admin-site-settings.09a9edb.svg HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/admin/maintenance/logs?lines=500 HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/admin/about/check HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/admin/about HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/admin/about/docker/validate HTTP/1.1" 200 OK
INFO:     10.1.1.5:0 - "GET /api/media/docker/validate.txt HTTP/1.1" 200 OK
INFO:     127.0.0.1:34372 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:39882 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:34214 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:44994 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:34756 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:40492 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:38376 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:54582 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:54166 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:37580 - "GET /api/app/about HTTP/1.1" 200 OK

### Mealie Version

Version: nightly
Build: ee121a12f8db33ecb4db5f8582f7ea9788d019e4

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Are you running pihole or some other DNS-level blocker?

See https://github.com/mealie-recipes/mealie/issues/2763 and https://github.com/mealie-recipes/mealie/issues/2771

**Comment by mantellian** [comment]
> Are you running pihole or some other DNS-level blocker?
> 
> See #2763 and #2771

Yes I'm running pihole

**Comment by michael-genson** [comment]
In that case you'll want to check out the two issues linked above, they should solve your issue. Specifically it looks like pihole is blocking `cdn.jsdelivr.net` out of the box, which will break certain UI elements. You'll want to take that off your block list.

**Comment by mantellian** [comment]
I just disabled ad blocking and reloaded the page, they are back. Interesting, I've been running pihole longer than mealie and the check boxes used to be there.

FIY I did search for this issue, apparently I'm blind.

Thanks

**Comment by michael-genson** [comment]
No worries, glad you got it working! Since this is the third reported issue recently, it's possible it was a recent pihole update that added jsdelivr to the blacklist for some reason.

**Comment by mantellian** [comment]
Whitelisted  cdn.jsdelivr.net and everything is working again
