### ISSUE TITLE
Can't sign in with default username/password

### ISSUE THREAD

**Issue by jveronese** [mealie-recipes/mealie#2787]
Recently been playing with Portainer, so maybe there is a config there I need to set? Did a fresh install by adding a container and pulling ghcr.io/mealie-recipes/mealie:nightly

I have Mealie installed and I can access the login page, however, when I try to login using the default login I get a "Something went wrong!" error. 

Tried both changeme@example.com and changeme@email.com with the default password MyPassword, both give the same error. Any thoughts?

**Comment by Kuchenpirat** [comment]
hey, to adress your issue we would need the logs and your deployment details (with sensitive informations removed)

For the next time, please use the provided templates to create an issue!

**Comment by jveronese** [comment]
Sorry, didn't see a template anywhere, and assumed this wasn't necessarily a bug so much as me just being new and unfamiliar with deploying through portainer.

For deployment, I have a portainer machine setup and went to add the container like this

![image](https://github.com/mealie-recipes/mealie/assets/48799290/a5c6c9b8-8712-4f51-884d-bec91e568486)

Then published the port and mapped the volume to my network share

![image](https://github.com/mealie-recipes/mealie/assets/48799290/53fc8d5a-7a28-4a1f-8b14-fa1ad585471a)

This allows me to get to the web interface, but not login.

Logs are below

[_mealie2_logs (1).txt](https://github.com/mealie-recipes/mealie/files/13561426/_mealie2_logs.1.txt)


Do I have to deploy a second container running the database? Or does pulling this one do it all? I feel like that might be where I am going wrong.

**Comment by michael-genson** [comment]
Based on those logs, your database doesn't seem set up right, which could happen for any number of reasons. Can you try clearing your data and starting with a fresh install? Then post your logs?

**Comment by jveronese** [comment]
Here are two sets of logs, one before binding my volume to my NAS share and one after. It seems that binding to the share is what is breaking it. Is there an additional binding I need to make or a better way to do that?

Before:
[_mealie2_logs (2).txt](https://github.com/mealie-recipes/mealie/files/13561533/_mealie2_logs.2.txt)

After:
[_mealie2_logs (3).txt](https://github.com/mealie-recipes/mealie/files/13561534/_mealie2_logs.3.txt)

**Comment by michael-genson** [comment]
Yup, that first log looks good. I'm not too familiar with portainer, so I can't answer your second question, but hopefully someone can chime in. You may also get a faster answer on Discord.

**Comment by boc-the-git** [comment]
@jveronese do you know what change is happening technically when binding the volume?
Is there a change in a docker-compose file?
Is it some front end setting in Portainer? (if so I won't be familiar)

Are you doing any moving of files/data to coincide with whatever that change is?

**Comment by boc-the-git** [comment]
Not something I ever really use but I think `docker inspect <container>` is a command to get detailed info about a container, perhaps that is useful for each of the 2 container examples you have, to compare what differs

**Comment by clrudolphi** [comment]
> Yup, that first log looks good. I'm not too familiar with portainer, so I can't answer your second question, but hopefully someone can chime in. You may also get a faster answer on Discord.

I'm not so sure. The first log shows the initial DB migrations running successfully. That doesn't sound like a broken DB. The second log definitely demonstrates a broken DB. Thus I'm confused.

I don't use the Portainer UI first these things but instead use the Editor tab on the Stack screen to paste in a docker compose file. Gives more control such as setting the UID/GUID.

**Comment by hay-kot** [comment]
Sounds like this issue is related to using SQLite over a network share which is not supported. Either use the storage on the local device or use Postgres as your database and manage your data that way. If you still see an issue after you've tried those please file a new issue using the template and include your logs. 

Thanks!
