### ISSUE TITLE
[BUG] - Lack of Group Naming Validation

### ISSUE THREAD

**Issue by Kuchenpirat** [mealie-recipes/mealie#2800]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Mealie allows users to create groups without assigning them a name. 

Once created it is not possible to move users into the group, because for user creation or moving into a new group the group name is required, but an empty string will not be accepted. 

### Steps to Reproduce

Via the Gui: 
- visit `/admin/manage/groups` page
- Click **Create** Button
- Click Create without doing anything

Via the API
- post a request to `/api/admin/groups` with the content `{ "name": "" }`
- get this response:
```
{
  "name": "",
  "id": "8944b068-71e6-40ed-9855-037621d76fd0",
  "slug": "",
  "categories": [],
  "webhooks": [],
  "users": [],
  "preferences": null
}
```

### Please provide relevant logs

Just a 201

[12/08/23 09:30:39] INFO     127.0.0.1:0 - "POST /api/admin/groups HTTP/1.1" 201 

### Mealie Version

Issue can be reproduced in my dev container and the demo

### Deployment

Docker (Linux), Docker (Windows)

**Comment by boc-the-git** [comment]
Replicated on demo.

The interesting thing was that if I click back onto the create button after, it looks like it has added an error message saying the name is required, just that it didn't stop the actual creation.
