### ISSUE TITLE
[BUG] - group/data/recipes/ does not handle imports (at all)

### ISSUE THREAD

**Issue by duckhead** [mealie-recipes/mealie#2802]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

This page should allow the export and import of recipes. Right now, the export appears to work, but the facility to import is not. It looks like the flow is to go like this:

1. Select an export to import.
2. Display the items in that export.
3. Select which items you want to import.
4. Press the Import button.

The issue is that there is no way to import the export file. So, the entire process breaks.

### Steps to Reproduce

Go to group/data/recipes

Done, there is no way to provide an export file to import.

### Please provide relevant logs

No logs are produced.

### Mealie Version

v1.0.0-RC1.1

### Deployment

Other

### Additional Deployment Details

Kubernetes helm chart on TrueNAS SCALE.

**Comment by Kuchenpirat** [comment]
can confirm
Guess this is currently a placeholder button, as it seems that there is no functionality linked to it. 

https://github.com/mealie-recipes/mealie/blob/f8ad72ec3147320c191b1bb1284f06e345a708b0/frontend/pages/group/data/recipes.vue#L120-L125

**Comment by duckhead** [comment]
I think the button you are referring to is the one in step 4 (the last one), which would actually import the data from the export file.  Having it not do anything is certainly an issue, of course.

What I'm talking about is the front end of the process. Where you pick an exported file, Mealie uploads, parses, and displays the objects in it. Those pieces don't exist on the page yet.

**Comment by Kuchenpirat** [comment]
ok, sorry, the workflow above is a bit confusing. 
my idea for a workflow was 

1. export selected recipes (working)
2. download export (working)
3. click import button
4. import dialog opens
5. upload file
6. (optional) select which recipes to import
7. confirm import

**Comment by michael-genson** [comment]
Which exports are you referring to? Recipe exports?

You can import Recipe ZIP files on the "create recipe" page:
![image](https://github.com/mealie-recipes/mealie/assets/71845777/831e5d48-a36d-4605-b508-aa330aff9848)

https://demo.mealie.io/recipe/create/zip

Though I agree it should also be available on the data management page

**Comment by duckhead** [comment]
OK, that does work for a single recipe on the demo instance. The data management page does multiple recipes in one zip though, and I suspect that may very well not work. Also, the demo instance now has my chili recipe on it, if you cook.

**Comment by michael-genson** [comment]
Yeah good point, so we need to add some basic multi-recipe parsing there

>  the demo instance now has my chili recipe on it

Don't mind me just nabbing that...

**Comment by duckhead** [comment]
That's why I used it. I have no issue sharing my recipes.

**Comment by duckhead** [comment]
But seriously, I don't care how it's implemented. I just want it to work, and for the directions to be clear enough that someone can export their recipes and someone else can import them. If data management page just does exports that's fine. Change it to not attempt to import, and put a note in there that says "Hey, to import these, do the following"

**Comment by yestrdave** [comment]
I am having the same issue.  I have tried to export (download) a recipe from my mealie for my mother and import the zip file into her mealie and it does nothing.  I have her as her as an independent group with her assigned as a user.  The docker container contains both my wife and I as one  group and her as a separate group.  I am trying to import from the create recipe section.


**Details**
Version: v1.9.0
Build: b54cdf642505bcb63384bddcc21f15d751c2f85b
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.56.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
OIDC Ready: No
OpenAI Ready: No
Email Configured: Yes
