### ISSUE TITLE
[BUG] -  'Error Submitting Form' Error When Uploading Asset

### ISSUE THREAD

**Issue by awirthy** [mealie-recipes/mealie#2805]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When I upload any file in the version 'v1.0.0-RC2' I receive the error 'Error Submitting Form'.

### Steps to Reproduce

Enable assets on a recipe.
Select file to upload.
Click create.

### Please provide relevant logs

INFO:     127.0.0.1:46668 - "GET /api/app/about HTTP/1.1" 200 OK

INFO:     172.21.0.1:38532 - "GET /g/home/r/mars-bar-slice HTTP/1.1" 200 OK

INFO:     127.0.0.1:46670 - "GET /api/app/about HTTP/1.1" 200 OK

### Mealie Version

v1.0.0-RC2

### Deployment

Docker (Linux)

**Comment by boc-the-git** [comment]
Any extra details @awirthy ?
Just realised it was user error or something like that?
All sorted now?
