### ISSUE TITLE
[SCRAPER] - dietdoctor.com

### ISSUE THREAD

**Issue by beasthouse-au** [mealie-recipes/mealie#2837]
### First Check

- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have verified that this issue _is not_ related to the underlying library
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers) by **1)** checking
the [debugger](https://demo.mealie.io/g/home/r/create/debug) and data is returned, **2)**
verifying that there _are_ errors in the log related to application level code, or
**3)** verified that the site provides recipe data, or is otherwise supported by
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers)

- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### Please provide 1-5 example URLs that are having errors

https://www.dietdoctor.com/recipes/keto-tuna-burgers

https://www.dietdoctor.com/recipes/keto-pizza-omelet

https://www.dietdoctor.com/recipes/low-carb-flank-steak-with-pepper-sauce-and-cauliflower-and-broccoli-gratin

### Please provide your logs for the Mealie container `docker logs <container-id> > mealie.logs`

```
INFO: 13-Dec-23 12:02:29 	HTTP Request: GET https://www.dietdoctor.com/recipes/keto-tuna-burgers "HTTP/1.1 200 OK"
ERROR: 13-Dec-23 12:02:30 	Error parsing recipe func_call for 'recipeInstructions'
INFO: 13-Dec-23 12:04:28 	HTTP Request: GET https://www.dietdoctor.com/recipes/low-carb-flank-steak-with-pepper-sauce-and-cauliflower-and-broccoli-gratin "HTTP/1.1 200 OK"
ERROR: 13-Dec-23 12:04:28 	Error parsing recipe func_call for 'recipeInstructions'
```

### Deployment

Unraid

**Comment by Kuchenpirat** [comment]
Hey, thanks for raising this issue. 
The recipe import fails because dietdoctor does not use the standard recipe schema, but  instead uses a verry unconventional implementation for recipe instructions that is neither suported by mealie, nor the scraper. 

The Layout for their System is as follows: 

```json
{
  "@type": "HowToSection",
  "name": "Instructions",
  "itemListOrder": "Ascending",
  "numberOfItems": 3,
  "itemListElement": [
    {
      "@type": "HowToStep",
      "position": "1",
      "itemListElement": {
        "@type": "HowToDirection",
        "position": "1",
        "text": "Mix the ingredients together (minus the oil) in a medium-sized bowl. Shape the mixture into small burgers, about 2 inches (5 cm) wide and 0.4 inch (1 cm) thick."
      }
    },
  ]
}
```

Mealie does support the systen down to the HowToStep where Mealie does expect an text field instead of another dict of the HowToDirection Type. 

I would say opening an ticket with [hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers) would be the way to go, but i am happy to be convinced otherwise if there are arguments that show that we should support this special structure.

**Comment by beasthouse-au** [comment]
Thanks @Kuchenpirat - happy to raise a ticket with the [hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers) - should I just be asking them to support this specific layout?

**Comment by Kuchenpirat** [comment]
Sounds good to me. 
They also do have an issue template to request support for a new website. Stick to that, and you should be good to go.

**Comment by beasthouse-au** [comment]
Thanks, have raised a ticket there.

https://github.com/hhursev/recipe-scrapers/issues/966

**Comment by beasthouse-au** [comment]
@Kuchenpirat have had a response on the other ticket.

```
Functionality to support websites that use this type of instruction listing was added in version 14.53.0 via wild_mode (wont be listed in the supported sites list but should function as expected).

It appears that the mealie library is running 14.52.0, I'd let a maintainer of the mealie project know that an updating the dependency should fix it!
```

Over to you!

**Comment by boc-the-git** [comment]
@beasthouse-au PRs are welcome 😊

**Comment by Kuchenpirat** [comment]
Thanks for relaying that back to us. Will open a PR to bump the scraper version tomorrow if nobody gets ahead of me.

**Comment by beasthouse-au** [comment]
> Thanks for relaying that back to us. Will open a PR to bump the scraper version tomorrow if nobody gets ahead of me.

Did you end up doing this or would you like me to raise the PR?

**Comment by Kuchenpirat** [comment]
Yeah, this is already included in the nightly. 
The links you posted above are now working on my instance

**Comment by beasthouse-au** [comment]
Thank you!!!
