### ISSUE TITLE
[BUG] - Docker volume Status validation disappeared

### ISSUE THREAD

**Issue by panteLx** [mealie-recipes/mealie#2839]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Since the last update to the nightly build my docker volume Status validation is gone. It showed `docker volumes not configured properly` first and now I can’t even see an option to check the docker volumes again. 

### Steps to Reproduce

1. Update at least to nightly Build [ce5b31dce5f7c912c51fe07d4e588281cb456cf4](https://github.com/hay-kot/mealie/commit/ce5b31dce5f7c912c51fe07d4e588281cb456cf4)
2. Visit settings page 
3. Search for the Docker Volume Section
4. (Click on "validate")
5. (Reload the page) 
6. No Docker Volume Section 

### Please provide relevant logs

No error while starting mealie docker container. Also no error while accessing settings page.

```
mealie    | INFO: 13-Dec-23 16:17:45    Database connection established.
mealie    | INFO: 13-Dec-23 16:17:45    Context impl SQLiteImpl.
mealie    | INFO: 13-Dec-23 16:17:45    Will assume non-transactional DDL.
mealie    | WARNING: 13-Dec-23 16:17:45         "get_all" method is deprecated; use "page_all" instead
mealie    | INFO:     Started server process [14]
mealie    | INFO:     Waiting for application startup.
mealie    | INFO: 13-Dec-23 16:17:51    -----SYSTEM STARTUP----- 
mealie    | 
mealie    | INFO: 13-Dec-23 16:17:51    ------APP SETTINGS------
mealie    | INFO: 13-Dec-23 16:17:51    {
mealie    |     "theme": {
mealie    |         "light_primary": "#E58325",
mealie    |         "light_accent": "#007A99",
mealie    |         "light_secondary": "#973542",
mealie    |         "light_success": "#43A047",
mealie    |         "light_info": "#1976D2",
mealie    |         "light_warning": "#FF6D00",
mealie    |         "light_error": "#EF5350",
mealie    |         "dark_primary": "#E58325",
mealie    |         "dark_accent": "#007A99",
mealie    |         "dark_secondary": "#973542",
mealie    |         "dark_success": "#43A047",
mealie    |         "dark_info": "#1976D2",
mealie    |         "dark_warning": "#FF6D00",
mealie    |         "dark_error": "#EF5350"
mealie    |     },
mealie    |     "PRODUCTION": true,
mealie    |     "BASE_URL": "https://dev-mealie.xx.net",
mealie    |     "STATIC_FILES": "/spa/static",
mealie    |     "IS_DEMO": false,
mealie    |     "API_PORT": 9000,
mealie    |     "API_DOCS": true,
mealie    |     "TOKEN_TIME": 48,
mealie    |     "LOG_LEVEL": "INFO",
mealie    |     "GIT_COMMIT_HASH": "861e8ac564e9df0a41620301e313d5333b572522",
mealie    |     "ALLOW_SIGNUP": true,
mealie    |     "SECURITY_MAX_LOGIN_ATTEMPTS": 5,
mealie    |     "SECURITY_USER_LOCKOUT_TIME": 24,
mealie    |     "DB_ENGINE": "sqlite",
mealie    |     "DEFAULT_GROUP": "User",
mealie    |     "SMTP_HOST": null,
mealie    |     "SMTP_PORT": "587",
mealie    |     "SMTP_FROM_NAME": "Mealie",
mealie    |     "SMTP_FROM_EMAIL": null,
mealie    |     "SMTP_AUTH_STRATEGY": "TLS",
mealie    |     "LDAP_AUTH_ENABLED": false,
mealie    |     "LDAP_SERVER_URL": null,
mealie    |     "LDAP_TLS_INSECURE": false,
mealie    |     "LDAP_TLS_CACERTFILE": null,
mealie    |     "LDAP_ENABLE_STARTTLS": false,
mealie    |     "LDAP_BASE_DN": null,
mealie    |     "LDAP_QUERY_BIND": null,
mealie    |     "LDAP_QUERY_PASSWORD": null,
mealie    |     "LDAP_USER_FILTER": null,
mealie    |     "LDAP_ADMIN_FILTER": null,
mealie    |     "LDAP_ID_ATTRIBUTE": "uid",
mealie    |     "LDAP_MAIL_ATTRIBUTE": "mail",
mealie    |     "LDAP_NAME_ATTRIBUTE": "name",
mealie    |     "TESTING": false
mealie    | }
mealie    | INFO:     Application startup complete.
mealie    | INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
```

### Mealie Version

Mealie Build [ce5b31dce5f7c912c51fe07d4e588281cb456cf4](https://github.com/hay-kot/mealie/commit/ce5b31dce5f7c912c51fe07d4e588281cb456cf4) (wont work on Build [861e8ac564e9df0a41620301e313d5333b572522](https://github.com/hay-kot/mealie/commit/861e8ac564e9df0a41620301e313d5333b572522) too)

Docker version 20.10.24+dfsg1, build 297e128

### Deployment

Docker (Linux)

### Additional Deployment Details

Hosted in Proxmox LXC Container.

**Comment by Kuchenpirat** [comment]
This is expected, as the docker volume check is an artifact of the times when mealie had two seperate containers for frontend and backend. (See #2830)
Since this is no longer the case the option for misconfiguration is kinda gone. 

The field should no longer be there.

**Comment by panteLx** [comment]
Alright. So its a bug that it disappears but my docker volume is not misconfigured? Never got that error prior while testing the  docker volume Status validation.

**Comment by Kuchenpirat** [comment]
No the check was removed because it is no longer needed. 

It should not apear on the admin page. I guess that you had the page still cached which is why the field was visible in the frontend. 
When clicking on validate it tried to acces backend resources that were no longer existent.

**Comment by panteLx** [comment]
Oh it might be cached in the browser and after the upgrade to the latest nightly build the function was not longer available (so check failed) and now it's gone because you removed it in the source code. :D 

Got it.

**Comment by Kuchenpirat** [comment]
Yep, thats it.
