### ISSUE TITLE
[BUG] - Documentation site, 404 pages link to invalid CSS, and display poorly

### ISSUE THREAD

**Issue by ekcom** [mealie-recipes/mealie#2841]
### First Check

- [x] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Error 404 pages on the documentation site are not properly displaying.

The CSS markup is not being loaded due to failed network requests.

### Steps to Reproduce

1. Navigate to a page that does not exist
    - e.g., https://nightly.mealie.io/404

### Please provide relevant logs

Requests to `GET` files is looking at the wrong path. E.g., the request for `custom.css` is looking at `https://nightly.mealie.io/mealie/assets/stylesheets/custom.css` on a 404 page instead of `https://nightly.mealie.io/assets/stylesheets/custom.css` as it should and does on other pages.

(There is an extra `mealie/` at the beginning of the URL path that is causing this.)

Several other CSS and JS files fail to load due to the same issue.

### Mealie Version

N/A

### Deployment

Other (please specify below)

### Additional Deployment Details

N/A

**Comment by boc-the-git** [comment]
Thanks for pointing it out @ekcom! :)
