### ISSUE TITLE
[BUG] - Unhealthy in Portainer, curl not found

### ISSUE THREAD

**Issue by kf0mlb** [mealie-recipes/mealie#2842]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I setup the 1.0.0-RC2 build using Portainer, and once the container was up and running I used the migration tool to import my Pre-v1 database of recipes.  It seems to be working fine, except Portainer is reporting the container is unhealthy because `/bin/sh: 1: curl: not found`.

### Steps to Reproduce

The webapp itself appears to be running fine, but the unhealthy status in Portainer makes me wonder if something in the container is missing.

### Please provide relevant logs

> INFO: 13-Dec-23 20:07:36 	Database connection established.
INFO: 13-Dec-23 20:07:36 	Context impl SQLiteImpl.
INFO: 13-Dec-23 20:07:36 	Will assume non-transactional DDL.
WARNING: 13-Dec-23 20:07:36 	"get_all" method is deprecated; use "page_all" instead
INFO: 13-Dec-23 20:07:37 	No food found with slug: 'dairy-products-and-dairy-substitutes' skipping fix
INFO:     Started server process [15]
INFO:     Waiting for application startup.
INFO: 13-Dec-23 20:07:50 	-----SYSTEM STARTUP----- 
INFO: 13-Dec-23 20:07:50 	------APP SETTINGS------
INFO: 13-Dec-23 20:07:50 	{
    "theme": {
        "light_primary": "#E58325",
        "light_accent": "#007A99",
        "light_secondary": "#973542",
        "light_success": "#43A047",
        "light_info": "#1976D2",
        "light_warning": "#FF6D00",
        "light_error": "#EF5350",
        "dark_primary": "#E58325",
        "dark_accent": "#007A99",
        "dark_secondary": "#973542",
        "dark_success": "#43A047",
        "dark_info": "#1976D2",
        "dark_warning": "#FF6D00",
        "dark_error": "#EF5350"
    },
    "PRODUCTION": true,
    "BASE_URL": "https://mealie.kf0mlb.xyz",
    "STATIC_FILES": "/spa/static",
    "IS_DEMO": false,
    "API_PORT": 9000,
    "API_DOCS": true,
    "TOKEN_TIME": 48,
    "LOG_LEVEL": "INFO",
    "GIT_COMMIT_HASH": "c9852daf0e213dc4cadf97971c7787cf6fc66dfc",
    "ALLOW_SIGNUP": false,
    "SECURITY_MAX_LOGIN_ATTEMPTS": 5,
    "SECURITY_USER_LOCKOUT_TIME": 24,
    "DB_ENGINE": "sqlite",
    "DEFAULT_GROUP": "Home",
    "SMTP_HOST": null,
    "SMTP_PORT": "587",
    "SMTP_FROM_NAME": "Mealie",
    "SMTP_FROM_EMAIL": null,
    "SMTP_AUTH_STRATEGY": "TLS",
    "LDAP_AUTH_ENABLED": false,
    "LDAP_SERVER_URL": null,
    "LDAP_TLS_INSECURE": false,
    "LDAP_TLS_CACERTFILE": null,
    "LDAP_ENABLE_STARTTLS": false,
    "LDAP_BASE_DN": null,
    "LDAP_QUERY_BIND": null,
INFO:     Application startup complete.
    "LDAP_QUERY_PASSWORD": null,
    "LDAP_USER_FILTER": null,
    "LDAP_ADMIN_FILTER": null,
    "LDAP_ID_ATTRIBUTE": "uid",
    "LDAP_MAIL_ATTRIBUTE": "mail",
    "LDAP_NAME_ATTRIBUTE": "name",
    "TESTING": false
}
INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
INFO:     172.17.0.1:36808 - "GET /api/groups/statistics HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/app/about/startup-info HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /icons/apple-touch-icon.png HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /sw.js HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "POST /api/auth/token HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/users/self HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/organizers/tags?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/groups/cookbooks?page=1&perPage=-1&orderBy=position&orderDirection=asc HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/organizers/categories?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/foods?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/recipes?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1702519697313&searchSeed=1702519697313&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/recipes?page=3&perPage=32&orderBy=created_at&orderDirection=desc&paginationSeed=1702519697313&searchSeed=1702519697313&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/groups/statistics HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/users/self/group HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/groups/storage HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/admin/about/check HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/admin/about HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/admin/about/docker/validate HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/media/docker/validate.txt HTTP/1.1" 200 OK
INFO:     172.17.0.1:43846 - "GET /api/groups/statistics HTTP/1.1" 200 OK
INFO: 13-Dec-23 21:07:50 	locked users reset
INFO:     172.17.0.1:60860 - "GET /api/groups/statistics HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/users/self HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /icons/apple-touch-icon.png HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/recipes?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1702526118278&searchSeed=1702526118278&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/organizers/tags?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/foods?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/organizers/categories?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/groups/cookbooks?page=1&perPage=-1&orderBy=position&orderDirection=asc HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/recipes?page=3&perPage=32&orderBy=created_at&orderDirection=desc&paginationSeed=1702526118278&searchSeed=1702526118278&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/admin/about/check HTTP/1.1" 200 OK
INFO:     2600:6c40:600:10e7:2718:5762:3757:c9fa:0 - "GET /api/admin/about HTTP/1.1" 200 OK

### Mealie Version

1.0.0-RC2

### Deployment

Docker (Linux)

### Additional Deployment Details

This is a fresh Debian 12 install.

**Comment by boc-the-git** [comment]
You've shared your url, in case you care.

Can you share your docker-compose file please?

I'm running nightly and have no issue like this, the initial assumption would be it's something local to your setup.

**Comment by boc-the-git** [comment]
I'm seeing IPV6 in the logs there.. Wonder if that's related on some way.. There's a known issue (with a workaround) document on one of the open issues.

Could be worth exploring.

**Comment by Humschi** [comment]
Did you create a new container or did you re-use your old one only changing the container image?
I had the same problem when only changing the image and not re-creating the whole container.
Portainer seams to keep the old health-settings even tho the new image does not include any health configuration.

**Comment by hay-kot** [comment]
We no longer use curl for health checks and haven't for some time. This issue is likely related to a cacheing issue on your device. I'd try to replicate it on a new server and see if it persists. Alternatively you can clear your cache on the main server and try redeploying with a fresh image set.
