### ISSUE TITLE
[BUG] - Updating foods does not update frontend

### ISSUE THREAD

**Issue by ekcom** [mealie-recipes/mealie#2862]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Creating, labelling, and deleting foods at `/group/data/foods` does not update the frontend table.
Trying to delete an item "again" since it didn't disappear leads to an error message.

The backend is still functioning; a refresh of the page reflects the updates/deletions.

Renaming *does* update the frontend immediately.

### Steps to Reproduce

1. Navigate to `/group/data/foods`
2. Delete an existing food
3. Observe that it is not removed from the list

### Please provide relevant logs

N/A

### Mealie Version

mealie:nightly

### Deployment

Docker (Linux)

**Comment by Kuchenpirat** [comment]
Thanks for raising this issue. 

I had this happen to me a few times as well, but cannot reliably reproduce it and did not jet have the time to take a deeper look into it. 

The CRUD Table component which is used here is reactive most of the time but not always which leads to the issue described in this ticket. There are also sorting issues when creating new items which might be connected.
