### ISSUE TITLE
[BUG] - Copy to clipboard failure not displayed

### ISSUE THREAD

**Issue by ekcom** [mealie-recipes/mealie#2863]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When a copy to clipboard fails, a toast still appears saying "Copied!" as a success message, which is conveying false information to the user.

Errors are still logged to the console about the copy failing.

This occurs, e.g., when the user is connected insecurely to a website and the browser rejects copy to clipboard requests, but also happens anytime a copy command fails.
This is especially relevant for fresh Mealie instances which do not have TLS (SSL) configured yet.

### Steps to Reproduce

1. Navigate to a Mealie instance using *http* for an unsecured connection
2. Click a copy button
  - E.g., `/admin/manage/users` -> click a user -> "Generate Password Reset Link" -> click the copy button

### Please provide relevant logs

N/A

### Deployment

Docker (Linux)

### Additional Deployment Details

Not easily reproducible on the demo site since it forces https.

**Comment by michael-genson** [comment]
Do you have any examples of the error logs when trying to copy over HTTP? Just so we have it here on the issue

**Comment by ekcom** [comment]
I do not on hand. If I recall correctly, it was just a stack trace of minified JS, so not very useful.
I would just `catch` the call to `window.navigator.writeText`

**Comment by clarkwmcd** [comment]
I am having the same issue on the ingredients list. When the copy button is clicked it say "Copied!" but there is nothing to paste.

**Comment by Kuchenpirat** [comment]
@clarkwmcd are you meaning if you copy the ingredient list you can copy from the shopping list or from somewere else?
because the shopping list should catch if copy is supported.

**Comment by Kuchenpirat** [comment]
i just found the error for the shopping list. It checks isSupported and not isSupported.value so it never enters the fail state. 

This will be fixed in an upcomming pr along with the rest of the copy boxes.
