### ISSUE TITLE
[BUG] - ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by duckhead** [mealie-recipes/mealie#2879]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When I attempt to log into my HTTP mealie instance (secured with a LetsEncrypt cert) it fails immediately, with a alert that says "Something went wrong." There is nothing in any of the pod's log files. If I look in the browser console, I have this error:

98d67ff.js:2 
        
        
       POST https://mealie.kcfrankhome.net/api/auth/token net::ERR_CERT_AUTHORITY_INVALID
       
       This one has me stumped, the browser thinks the cert is valid, but it doesn't?

       This is on a TrueNAS SCALE box, running the TrueCommand charts. There's been a lot of churn with the charts for the past few days due to a major release of upgrades. It seems like this may be more of an app issue though. Prior to that, it had been working fine with the SSL cert for a week or so.
       
       Accessing the site directly by port using http is working fine.

### Steps to Reproduce

Attempt to log in, you get the error message

### Please provide relevant logs

The only log message is above.

### Mealie Version

UI is not working. 

ghcr.io/mealie-recipes/mealie@sha256:9881b16dda92272c6eeeb132697ad2379be1c562f0f53f86f20ce2654b57f455

### Deployment

TrueNAS

### Additional Deployment Details

SCALE Cobia, TrueCharts version

**Comment by hay-kot** [comment]
Can you try a hard refresh and clear your browser storage/cookies for that site? 

It may be that the service worker is caching the certificate.

**Comment by duckhead** [comment]
Sorry, I've been out of town without access to my mealie instance for a few days. I cleared cookies, deleted browser storage and cookies, and unregistered the service worker, and it is still failing.

**Comment by duckhead** [comment]
OK, I think I've finally gotten this sorted. It was an issue with TrueCharts wiping out some data, and then moving where it's  stored and hiding it behind a checkbox.
