### ISSUE TITLE
Scaper can not recognise anything on Allerhande.nl (ah.nl) anymore while it did in the past

### ISSUE THREAD

**Issue by zandhaas** [mealie-recipes/mealie#2888]
### First Check

- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have verified that this issue _is not_ related to the underlying library
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers) by **1)** checking
the [debugger](https://demo.mealie.io/g/home/r/create/debug) and data is returned, **2)**
verifying that there _are_ errors in the log related to application level code, or
**3)** verified that the site provides recipe data, or is otherwise supported by
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers)

- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### Please provide 1-5 example URLs that are having errors

https://www.ah.nl/allerhande/recept/R-R1199309/courgettelasagne-met-3-kazen-en-gehakt
https://www.ah.nl/allerhande/recept/R-R1199239/vegan-groenterollade-met-saliestuffing-van-sanne-vogel

### Please provide your logs for the Mealie container `docker logs <container-id> > mealie.logs`

[mealie-log.zip](https://github.com/mealie-recipes/mealie/files/13795575/mealie-log.zip)

### Deployment

Docker (Synology)

**Comment by zandhaas** [comment]
The scraper debugger returns:

**recipe_scrapers was unable to scrape this URL**

**Comment by Kuchenpirat** [comment]
So it seems (as already suggested in the Discord by other members of the team) that the scraper is being blocked by the website. 

All i can get out of the scraper is the domain and via html mode the following "Access Denied" Message. 

```
b'<HTML><HEAD>\n<TITLE>Access Denied</TITLE>\n</HEAD><BODY>\n<H1>Access Denied</H1>\n \nYou don\'t have permission to access "http&#58;&#47;&#47;www&#46;ah&#46;nl&#47;allerhande&#47;recept&#47;R&#45;R1199309&#47;courgettelasagne&#45;met&#45;3&#45;kazen&#45;en&#45;gehakt" on this server.<P>\nReference&#32;&#35;18&#46;84601302&#46;1703930024&#46;5a077ebe\n</BODY>\n</HTML>\n'
```

I'll be closing this, as there is not much mealie can do against that.

**Comment by jeffreytigch** [comment]
This issue is being worked on: https://github.com/hhursev/recipe-scrapers/issues/990

**Comment by bilhert** [comment]
I ran into the same issue. Doing some additional research gave me the following insights:
ah.nl/allerhande  uses TLS fingerprinting detection to do bot detection.

A regular request with insomnia gave the same results as reported here.
however when using a tls spoofer proxy (https://github.com/LyleMi/ja3proxy)
and making sure the "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0" and "Accept-Encoding:" header were set resulted in a correct result. (note accept-encoding only needed to be present the value does not matter)

Thus this issue may easily be resolved if the request is altered in such a way that this information is send with the scrape request.

tls spoofing can be directly build into mealie perhaps to be used optionally or by allowing the use of a proxy

additionally the "Accept" header should probably be set next to the user-agent

https://github.com/mealie-recipes/mealie/blob/mealie-next/mealie/services/scraper/scraper_strategies.py
https://github.com/mealie-recipes/mealie/blob/mealie-next/mealie/services/recipe/recipe_data_service.py

**Comment by burgerga** [comment]
Works perfectly now using the raw import mode:
1. Go to the recipe, right click -> inspect (this opens DevTools)
2. Search for the https://schema.org/Recipe json-ld:
    * Make sure you're on the "Elements" tab
    * Press Ctrl+F to search, search for "schema.org"
    * Press Enter until you're on the one with `"@type": "Recipe"` (it starts with `{"@context":"https://schema.org","@type":"Recipe",...`, you can see it contains the ingredients and the recipe steps)
4. Right-click on this json-ld -> Copy -> Copy Element 
5. Paste into Mealie raw import

EDIT: updated instructions

**Comment by Aporiatic** [comment]
> Works perfectly now using the raw import mode:
> 
> 1. Go to the recipe, right click -> inspect
> 2. Search for "schema.org", press Enter until you're on the one with `"@type": "Recipe"`
> 3. Right-click -> Copy -> Copy Element
> 4. Paste into Mealie raw import

Would you please elaborate on step 2 and 3 a bit more? Where do I search and what do I right-click? Have tried to follow the steps, but it leaves me nowhere, unfortunately.

**Comment by burgerga** [comment]
@Aporiatic Updated the instructions!

**Comment by mobiledude** [comment]
this works. Just makes me wonder why scraping it from a url is so difficult....It is an ok workaround, but for my family a big dissatisfier to use Mealie not having an easy import from Allerhande.

thank you for this

**Comment by burgerga** [comment]
@mobiledude It's because (I'm simplifying a bit) if the request isn't coming from a browser, AH will think it's a bot trying to steal their recipes. So if you want this to work you should vote for https://github.com/mealie-recipes/mealie/discussions/4457 (a mealie browser extension), this will allow to automate the steps I shared above because it will have access to the recipe already loaded in the browser :)
