### ISSUE TITLE
[BUG] - Unable to migrate from MySQL to Postgres

### ISSUE THREAD

**Issue by djmega152** [mealie-recipes/mealie#2891]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I have a deployment of Mealie running on MySQL.  Here is the relevant build info:

`**Details**
Version: nightly
Build: f6f9a1c5324abaa8d5653efbc4f1cdd8f4819d75
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.53.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: Yes
`
I went to Admin -> Backups and selected Create a backup.  The zip file gets created and I downloaded it.  The format for the zip file looks like this:

![image](https://github.com/mealie-recipes/mealie/assets/99622018/60733313-26df-44be-a5ee-6faa90179bbb)

I spun up another instance of Mealie using postgres.  Here is the build info from that deployment:

`**Details**
Version: nightly
Build: 6a71af98bde8c69bdcc91b1c77cb1b7127560185
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: postgres
Recipe Scraper Version: 14.53.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: No
`
I followed the instructions on [this](https://nightly.mealie.io/documentation/getting-started/faq/#what-is-fuzzy-search-and-how-do-i-use-it) article to try to migrate the recipes.  I select Mealie Pre-v1.0 (the only Mealie option) and then upload the backup zip file from the MySQL deployment.  When I click Submit, nothing happens.  There is no error message and the migration does not show in the bottom section.  When I refresh the page, there is nothing showing in the previous migrations section.

![image](https://github.com/mealie-recipes/mealie/assets/99622018/dc456cd5-e443-4fb6-b9bb-c7db82fd44ef)

I tried using the MySQL backup on the demo site and the same issue is present there.
![image](https://github.com/mealie-recipes/mealie/assets/99622018/532b12bf-b955-41c5-8332-1114330edb5e)

I'd really like to use fuzzy search and avoid having to recreate all of my recipes manually.  Can someone help me figure out what's going wrong here?

### Steps to Reproduce

1. Perform a backup from a current Mealie MySQL instance and download the zip file
2. Create a Postgres instance and navigate to group/migrations and try to run a migration using the MySQL backup

### Please provide relevant logs

From the mealie container:
`12/30/2023
10:28:20 AM
INFO:     192.168.1.1:0 - "POST /api/groups/migrations HTTP/1.1" 400 Bad Request
12/30/2023
10:28:21 AM
INFO:     192.168.1.1:0 - "GET /group/migrations HTTP/1.1" 307 Temporary Redirect
12/30/2023
10:28:21 AM
INFO:     192.168.1.1:0 - "GET /group/migrations/ HTTP/1.1" 200 OK`

from the Mealie DB container:
`12/30/2023
10:22:14 AM
PostgreSQL Database directory appears to contain a database; Skipping initialization
12/30/2023
10:22:14 AM
12/30/2023
10:22:14 AM
2023-12-30 15:22:14.370 UTC [1] LOG:  starting PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
12/30/2023
10:22:14 AM
2023-12-30 15:22:14.370 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
12/30/2023
10:22:14 AM
2023-12-30 15:22:14.370 UTC [1] LOG:  listening on IPv6 address "::", port 5432
12/30/2023
10:22:14 AM
2023-12-30 15:22:14.407 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
12/30/2023
10:22:14 AM
2023-12-30 15:22:14.455 UTC [29] LOG:  database system was shut down at 2023-12-30 15:09:39 UTC
12/30/2023
10:22:14 AM
2023-12-30 15:22:14.471 UTC [1] LOG:  database system is ready to accept connections
12/30/2023
10:27:14 AM
2023-12-30 15:27:14.521 UTC [27] LOG:  checkpoint starting: time
12/30/2023
10:27:14 AM
2023-12-30 15:27:14.728 UTC [27] LOG:  checkpoint complete: wrote 4 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.101 s, sync=0.039 s, total=0.208 s; sync files=3, longest=0.013 s, average=0.013 s; distance=0 kB, estimate=0 kB; lsn=0/1BAD678, redo lsn=0/1BAD640`

### Mealie Version

MySQL:
`**Details**
Version: nightly
Build: f6f9a1c5324abaa8d5653efbc4f1cdd8f4819d75
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.53.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: Yes`

Postgres:
`**Details**
Version: nightly
Build: 6a71af98bde8c69bdcc91b1c77cb1b7127560185
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: postgres
Recipe Scraper Version: 14.53.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: No
`

### Deployment

Docker (Synology)

### Additional Deployment Details

DSM 7.2.1-69057 Update 3

**Comment by djmega152** [comment]
If you'd like a copy of the MySQL backup export (.zip), let me know and I can either attach it here or send it directly.

**Comment by Kuchenpirat** [comment]
i think the right way to do this would be:

- create the backup on the sqlite instance on the `/admin/backups` page and download it
- go to the same page on the postgres instance
- use the upload button to upload the backup
- use the restore functionality on this page to restore from backup

**Comment by djmega152** [comment]
I'll give that a shot and report back.

**Comment by djmega152** [comment]
Nope, here's the logs from the mealie container:

`12/30/2023
10:55:10 AM
INFO: 30-Dec-23 10:55:10 	initially backup restore
12/30/2023
10:55:10 AM
ERROR: 30-Dec-23 10:55:10 	[Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/app']
12/30/2023
10:55:10 AM
Traceback (most recent call last):
12/30/2023
10:55:10 AM
  File "/app/mealie/routes/admin/admin_backups.py", line 105, in import_one
12/30/2023
10:55:10 AM
    backup.restore(file)
12/30/2023
10:55:10 AM
  File "/app/mealie/services/backups_v2/backup_v2.py", line 81, in restore
12/30/2023
10:55:10 AM
    with backup as contents:
12/30/2023
10:55:10 AM
  File "/app/mealie/services/backups_v2/backup_file.py", line 52, in __enter__
12/30/2023
10:55:10 AM
    self.temp_dir = Path(tempfile.mkdtemp())
12/30/2023
10:55:10 AM
  File "/usr/local/lib/python3.10/tempfile.py", line 357, in mkdtemp
12/30/2023
10:55:10 AM
    prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
12/30/2023
10:55:10 AM
  File "/usr/local/lib/python3.10/tempfile.py", line 126, in _sanitize_params
12/30/2023
10:55:10 AM
    dir = gettempdir()
12/30/2023
10:55:10 AM
  File "/usr/local/lib/python3.10/tempfile.py", line 299, in gettempdir
12/30/2023
10:55:10 AM
    return _os.fsdecode(_gettempdir())
12/30/2023
10:55:10 AM
  File "/usr/local/lib/python3.10/tempfile.py", line 292, in _gettempdir
12/30/2023
10:55:10 AM
    tempdir = _get_default_tempdir()
12/30/2023
10:55:10 AM
  File "/usr/local/lib/python3.10/tempfile.py", line 223, in _get_default_tempdir
12/30/2023
10:55:10 AM
    raise FileNotFoundError(_errno.ENOENT,
12/30/2023
10:55:10 AM
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/app']
12/30/2023
10:55:10 AM
INFO:     192.168.1.1:0 - "POST /api/admin/backups/mealie_2023.12.30.09.32.38.zip/restore HTTP/1.1" 500 Internal Server Error
12/30/2023
10:55:34 AM
INFO:     127.0.0.1:47018 - "GET /api/app/about HTTP/1.1" 200 OK`

**Comment by Kuchenpirat** [comment]
ok, two things. 
- You said you have no problem passing along the zip. Could you send that over and i can give it a quick try on my system. Either here or on Discord
- Do you have more deployment deployment on your new instance. Do you have the volumes configured correctly?

**Comment by Kuchenpirat** [comment]
i got the zip off platform and could restore it on an postgres deployment. 

Closing for now as i am pretty sure its an deployment error. 

@djmega152 feel free to reopen, if it turn out to be something else.

**Comment by djmega152** [comment]
Confirmed as a config issue on my postgres deployment. I used a different docker compose than the one on the docs site.  Once I defaulted to the one on the site, everything works as expected and the migration is complete.  Thanks @Kuchenpirat for the assist!  I've been toiling with this for months (on and off)

**Comment by boc-the-git** [comment]
@djmega152 can you please share both the bad and good compose files here, for reference?
Could help others see what specific detail is wrong in the config.

Nice one @Kuchenpirat 👍
