### ISSUE TITLE
[BUG] - "Looking for Migrations" Link on create recipe page not working 

### ISSUE THREAD

**Issue by Kuchenpirat** [mealie-recipes/mealie#2928]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

The link on the create recipe page is not working

### Steps to Reproduce

1. Go to create recipe page
2. Klick on "Looking for Migration" Link

### Please provide relevant logs

None

### Mealie Version

Version: nightly
Build: 8ca5a9454e139d4c874cbe50182f61e1f701f811

### Deployment

Docker (Linux), Docker (Windows)

**Comment by michael-genson** [comment]
Should be fixed by https://github.com/mealie-recipes/mealie/pull/2852

**Comment by Kuchenpirat** [comment]
ah damn, i was so proud of me having figured that out within a few seconds 😁

was already writing my pr
