### ISSUE TITLE
[BUG] - Impossible to copy / paste logs

### ISSUE THREAD

**Issue by gravelfreeman** [mealie-recipes/mealie#2932]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

The copy button in the logs page doesn't copy anything to the clipboard.

It's impossible to select the whole text and copy paste it in vscode for example. Only a few hundred of lines will be copied and they'll have 4 breaks between each of them which makes it inconvenient to read the logs.

I'm actually trying to make another ticket but I need to send the logs.

### Steps to Reproduce

1. Go to `/admin/maintenance/logs`
2. Press the copy button or try to select all the lines and copy/paste in notepad

### Please provide relevant logs

```python

            File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute

        


              cursor.execute(statement, parameters)

        


          sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column ingredient_units_1.plural_name does not exist

        


          LINE 1: ...gredient_units_1.name AS ingredient_units_1_name, ingredient...
``` 

### Mealie Version

v1.0.0-RC2

### Deployment

TrueNAS

### Additional Deployment Details

From TrueCharts catalog.

**Comment by boc-the-git** [comment]
What url are you accessing mealie via? I've seen reports of browsers not letting you copy from website over http

**Comment by gravelfreeman** [comment]
> What url are you accessing mealie via? I've seen reports of browsers not letting you copy from website over http

This new test instance is via http, I can setup ingress and come back and report.

**Comment by boc-the-git** [comment]
Please let us know.
It'd seem the likely cause, particularly given you've said it can't be replicated on the demo site.

**Comment by gravelfreeman** [comment]
> Please let us know. It'd seem the likely cause, particularly given you've said it can't be replicated on the demo site.

Thank you, it's working with ingress.
