### ISSUE TITLE
[BUG] - Backups page status notification always reports backup successful even if it's not

### ISSUE THREAD

**Issue by hbh7** [mealie-recipes/mealie#2970]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

The backup page's popup notification always reports success, even if the actual request failed.
![image](https://github.com/mealie-recipes/mealie/assets/5050375/b1602823-856f-46c6-9f58-2a42be2f3228)

Additional context: https://github.com/mealie-recipes/mealie/issues/2904

### Steps to Reproduce

1. Open backup page
2. Shut down server or otherwise make the necessary endpoints return an error
3. Try to create a backup
4. Observe described behavior

### Please provide relevant logs

See screenshot

### Mealie Version

nightly as of a few minutes ago

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
No worries, glad it's otherwise working for you!

**Comment by boc-the-git** [comment]
Confirmed. I navigated to the page (baseurl/admin/backups), stopped my server, then hit "Create a Backup". I witnessed in developer tools a 502 from the server, but on the UI it reported success.
