### ISSUE TITLE
[BUG] - Language Processor works in example but not when creating recipe

### ISSUE THREAD

**Issue by JohnnyPicnic** [mealie-recipes/mealie#3018]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When creating a new recipe the parser finds the "Quantity" and "Food" but does not find the "Unit".
![Screenshot 2024-01-20 at 3 41 53 PM](https://github.com/mealie-recipes/mealie/assets/5553884/87137aa3-7433-4471-9406-a21800d9c4da)

When using the example input at /admin/parser it works as expected.
![Screenshot 2024-01-20 at 3 42 20 PM](https://github.com/mealie-recipes/mealie/assets/5553884/d60aa6a9-1434-4f76-9c88-62378ccdac99)

Tested in the demo site and it works pretty will 

### Steps to Reproduce

Import recipe from url or bulk add ingredients. 
Turn off "Disable Ingredient Amounts".
Select "Parse". (sometime the ingredients are only loaded on the second try?)

### Please provide relevant logs

INFO: 20-Jan-24 15:02:30 	Database connection established.
INFO: 20-Jan-24 15:02:30 	Context impl SQLiteImpl.
INFO: 20-Jan-24 15:02:30 	Will assume non-transactional DDL.
INFO: 20-Jan-24 15:02:30 	Migration needed. Performing migration...
INFO: 20-Jan-24 15:02:31 	Context impl SQLiteImpl.
INFO: 20-Jan-24 15:02:31 	Will assume non-transactional DDL.
INFO: 20-Jan-24 15:02:31 	Running upgrade  -> 6b0f5f32d602, Initial tables
INFO: 20-Jan-24 15:02:31 	Running upgrade 6b0f5f32d602 -> 263dd6707191, convert quantity from integer to float
INFO: 20-Jan-24 15:02:31 	Running upgrade 263dd6707191 -> f1a2dbee5fe9, Add original_text column to recipes_ingredients
INFO: 20-Jan-24 15:02:31 	Running upgrade f1a2dbee5fe9 -> 59eb59135381, add tags to cookbooks
INFO: 20-Jan-24 15:02:31 	Running upgrade 59eb59135381 -> 09dfc897ad62, add require_all for cookbook filters
INFO: 20-Jan-24 15:02:31 	Running upgrade 09dfc897ad62 -> ab0bae02578f, Add use_abbreviation column to ingredients
INFO: 20-Jan-24 15:02:31 	Running upgrade ab0bae02578f -> f30cf048c228, add new webhook fields
INFO: 20-Jan-24 15:02:31 	Running upgrade f30cf048c228 -> 188374910655, add login_attemps and locked_at field to user table
INFO: 20-Jan-24 15:02:31 	Running upgrade 188374910655 -> 089bfa50d0ed, Add is_ocr_recipe column to recipes
INFO: 20-Jan-24 15:02:31 	Running upgrade 089bfa50d0ed -> 44e8d670719d, add extras to shopping lists, list items, and ingredient foods
INFO: 20-Jan-24 15:02:31 	Running upgrade 44e8d670719d -> 2ea7a807915c, add recipe_timeline_events table
INFO: 20-Jan-24 15:02:31 	Running upgrade 2ea7a807915c -> 1923519381ad, added recipe last made timestamp
INFO: 20-Jan-24 15:02:31 	Running upgrade 1923519381ad -> 167eb69066ad, add recipe_scale to shopping list item ref
INFO: 20-Jan-24 15:02:31 	Running upgrade 167eb69066ad -> 165d943c64ee, add related user to mealplan
INFO: 20-Jan-24 15:02:32 	Running upgrade 165d943c64ee -> ff5f73b01a7a, add missing foreign key and order indices
INFO: 20-Jan-24 15:02:32 	Running upgrade ff5f73b01a7a -> 16160bf731a0, add more indices necessary for search
INFO: 20-Jan-24 15:02:32 	Running upgrade 16160bf731a0 -> 5ab195a474eb, add normalized search properties
INFO: 20-Jan-24 15:02:32 	Running upgrade 5ab195a474eb -> b04a08da2108, added shopping list label settings
INFO: 20-Jan-24 15:02:33 	Running upgrade b04a08da2108 -> 38514b39a824, add auth_method to user table
INFO: 20-Jan-24 15:02:33 	Running upgrade 38514b39a824 -> b3dbb554ba53, postgres fuzzy search
INFO: 20-Jan-24 15:02:33 	Running upgrade b3dbb554ba53 -> 04ac51cbe9a4, added group slug
INFO: 20-Jan-24 15:02:33 	Running upgrade 04ac51cbe9a4 -> 1825b5225403, added recipe note to shopping list recipe ref
INFO: 20-Jan-24 15:02:33 	Running upgrade 1825b5225403 -> bcfdad6b7355, remove tool name and slug unique contraints
WARNING: 20-Jan-24 15:02:33 	"get_all" method is deprecated; use "page_all" instead
INFO: 20-Jan-24 15:02:33 	Database contains no users, initializing...
INFO: 20-Jan-24 15:02:33 	Generating Default Group
INFO: 20-Jan-24 15:02:34 	Generating Default User
INFO: 20-Jan-24 15:02:34 	No food found with slug: 'dairy-products-and-dairy-substitutes' skipping fix
INFO: 20-Jan-24 15:03:23 	-----SYSTEM STARTUP----- 

INFO: 20-Jan-24 15:03:23 	------APP SETTINGS------
INFO: 20-Jan-24 15:03:23 	{
    "PRODUCTION": true,
    "BASE_URL": "http://localhost:8080",
    "IS_DEMO": false,
    "API_PORT": 9000,
    "API_DOCS": true,
    "TOKEN_TIME": 48,
    "LOG_LEVEL": "INFO",
    "GIT_COMMIT_HASH": "0a00a6ea0d05d2dd944dd9cc6713156dc767e1ed",
    "ALLOW_SIGNUP": true,
    "SECURITY_MAX_LOGIN_ATTEMPTS": 5,
    "SECURITY_USER_LOCKOUT_TIME": 24,
    "DB_ENGINE": "sqlite",
    "DB_PROVIDER": {
        "data_dir": "/config/addons_config/mealie_data",
        "prefix": ""
    },
    "DEFAULT_GROUP": "Home",
    "DEFAULT_EMAIL": "changeme@email.com",
    "SMTP_HOST": null,
    "SMTP_PORT": "587",
    "SMTP_FROM_NAME": "Mealie",
    "SMTP_FROM_EMAIL": null,
    "SMTP_AUTH_STRATEGY": "TLS",
    "LDAP_AUTH_ENABLED": false,
    "LDAP_SERVER_URL": null,
    "LDAP_TLS_INSECURE": false,
    "LDAP_TLS_CACERTFILE": null,
    "LDAP_ENABLE_STARTTLS": false,
    "LDAP_BASE_DN": null,
    "LDAP_QUERY_BIND": null,
    "LDAP_QUERY_PASSWORD": null,
    "LDAP_USER_FILTER": null,
    "LDAP_ADMIN_FILTER": null,
    "LDAP_ID_ATTRIBUTE": "uid",
    "LDAP_MAIL_ATTRIBUTE": "mail",
    "LDAP_NAME_ATTRIBUTE": "name",
    "TESTING": false
}
INFO: 20-Jan-24 15:03:24 	-----SYSTEM STARTUP----- 

INFO: 20-Jan-24 15:03:24 	------APP SETTINGS------
INFO: 20-Jan-24 15:03:24 	{
    "PRODUCTION": true,
    "BASE_URL": "http://localhost:8080",
    "IS_DEMO": false,
    "API_PORT": 9000,
    "API_DOCS": true,
    "TOKEN_TIME": 48,
    "LOG_LEVEL": "INFO",
    "GIT_COMMIT_HASH": "0a00a6ea0d05d2dd944dd9cc6713156dc767e1ed",
    "ALLOW_SIGNUP": true,
    "SECURITY_MAX_LOGIN_ATTEMPTS": 5,
    "SECURITY_USER_LOCKOUT_TIME": 24,
    "DB_ENGINE": "sqlite",
    "DB_PROVIDER": {
        "data_dir": "/config/addons_config/mealie_data",
        "prefix": ""
    },
    "DEFAULT_GROUP": "Home",
    "DEFAULT_EMAIL": "changeme@email.com",
    "SMTP_HOST": null,
    "SMTP_PORT": "587",
    "SMTP_FROM_NAME": "Mealie",
    "SMTP_FROM_EMAIL": null,
    "SMTP_AUTH_STRATEGY": "TLS",
    "LDAP_AUTH_ENABLED": false,
    "LDAP_SERVER_URL": null,
    "LDAP_TLS_INSECURE": false,
    "LDAP_TLS_CACERTFILE": null,
    "LDAP_ENABLE_STARTTLS": false,
    "LDAP_BASE_DN": null,
    "LDAP_QUERY_BIND": null,
    "LDAP_QUERY_PASSWORD": null,
    "LDAP_USER_FILTER": null,
    "LDAP_ADMIN_FILTER": null,
    "LDAP_ID_ATTRIBUTE": "uid",
    "LDAP_MAIL_ATTRIBUTE": "mail",
    "LDAP_NAME_ATTRIBUTE": "name",
    "TESTING": false
}
INFO: 20-Jan-24 15:07:29 	HTTP Request: GET https://chefjeanpierre.com/recipes/beef-stock/ "HTTP/1.1 200 OK"
ERROR: 20-Jan-24 15:07:30 	Error parsing recipe func_call for 'recipeYield'
INFO: 20-Jan-24 15:07:30 	Image URL: ['https://chefjeanpierre.com/wp-content/uploads/2023/05/Classic-and-Essential-Beef-Stock-_-Chef-Jean-Pierre.jpg', 'https://chefjeanpierre.com/wp-content/uploads/2023/05/Classic-and-Essential-Beef-Stock-_-Chef-Jean-Pierre-500x500.jpg', 'https://chefjeanpierre.com/wp-content/uploads/2023/05/Classic-and-Essential-Beef-Stock-_-Chef-Jean-Pierre-500x375.jpg', 'https://chefjeanpierre.com/wp-content/uploads/2023/05/Classic-and-Essential-Beef-Stock-_-Chef-Jean-Pierre-480x270.jpg']
INFO: 20-Jan-24 15:07:30 	HTTP Request: HEAD https://chefjeanpierre.com/wp-content/uploads/2023/05/Classic-and-Essential-Beef-Stock-_-Chef-Jean-Pierre.jpg "HTTP/1.1 200 OK"
INFO: 20-Jan-24 15:07:30 	HTTP Request: HEAD https://chefjeanpierre.com/wp-content/uploads/2023/05/Classic-and-Essential-Beef-Stock-_-Chef-Jean-Pierre-500x500.jpg "HTTP/1.1 200 OK"
INFO: 20-Jan-24 15:07:30 	HTTP Request: HEAD https://chefjeanpierre.com/wp-content/uploads/2023/05/Classic-and-Essential-Beef-Stock-_-Chef-Jean-Pierre-500x375.jpg "HTTP/1.1 200 OK"
INFO: 20-Jan-24 15:07:30 	HTTP Request: HEAD https://chefjeanpierre.com/wp-content/uploads/2023/05/Classic-and-Essential-Beef-Stock-_-Chef-Jean-Pierre-480x270.jpg "HTTP/1.1 200 OK"
INFO: 20-Jan-24 15:07:31 	HTTP Request: GET https://chefjeanpierre.com/wp-content/uploads/2023/05/Classic-and-Essential-Beef-Stock-_-Chef-Jean-Pierre.jpg "HTTP/1.1 200 OK"
INFO: 20-Jan-24 15:07:32 	original.jpg minified
INFO: 20-Jan-24 15:07:32 	Tiny image saved
INFO: 20-Jan-24 15:23:00 	Recipe Directory Removed: brisket-rub
INFO: 20-Jan-24 15:25:15 	Recipe Directory Removed: brisket-rub-1
INFO: 20-Jan-24 15:28:16 	HTTP Request: GET https://chefjeanpierre.com/recipes/classic-french-onion-soup-recipe/ "HTTP/1.1 200 OK"
INFO: 20-Jan-24 15:28:18 	Image URL: ['https://chefjeanpierre.com/wp-content/uploads/2023/05/Simple-French-Onion-Soup-_-Chef-Jean-Pierre.jpg', 'https://chefjeanpierre.com/wp-content/uploads/2023/05/Simple-French-Onion-Soup-_-Chef-Jean-Pierre-500x500.jpg', 'https://chefjeanpierre.com/wp-content/uploads/2023/05/Simple-French-Onion-Soup-_-Chef-Jean-Pierre-500x375.jpg', 'https://chefjeanpierre.com/wp-content/uploads/2023/05/Simple-French-Onion-Soup-_-Chef-Jean-Pierre-480x270.jpg']
INFO: 20-Jan-24 15:28:19 	HTTP Request: HEAD https://chefjeanpierre.com/wp-content/uploads/2023/05/Simple-French-Onion-Soup-_-Chef-Jean-Pierre.jpg "HTTP/1.1 200 OK"
INFO: 20-Jan-24 15:28:19 	HTTP Request: HEAD https://chefjeanpierre.com/wp-content/uploads/2023/05/Simple-French-Onion-Soup-_-Chef-Jean-Pierre-500x500.jpg "HTTP/1.1 200 OK"
INFO: 20-Jan-24 15:28:19 	HTTP Request: HEAD https://chefjeanpierre.com/wp-content/uploads/2023/05/Simple-French-Onion-Soup-_-Chef-Jean-Pierre-480x270.jpg "HTTP/1.1 200 OK"
INFO: 20-Jan-24 15:28:19 	HTTP Request: HEAD https://chefjeanpierre.com/wp-content/uploads/2023/05/Simple-French-Onion-Soup-_-Chef-Jean-Pierre-500x375.jpg "HTTP/1.1 200 OK"
INFO: 20-Jan-24 15:28:20 	HTTP Request: GET https://chefjeanpierre.com/wp-content/uploads/2023/05/Simple-French-Onion-Soup-_-Chef-Jean-Pierre.jpg "HTTP/1.1 200 OK"
INFO: 20-Jan-24 15:28:21 	original.jpg minified
INFO: 20-Jan-24 15:28:21 	Tiny image saved
ERROR: 20-Jan-24 15:31:53 	Recipe Directory not Found: how-to-make-classic-french-onion-soup
INFO: 20-Jan-24 15:38:35 	HTTP Request: GET https://chefjeanpierre.com/recipes/soups/creamy-cauliflower-bisque/ "HTTP/1.1 200 OK"
ERROR: 20-Jan-24 15:38:36 	Error parsing recipe func_call for 'recipeYield'
INFO: 20-Jan-24 15:38:36 	Image URL: ['https://chefjeanpierre.com/wp-content/uploads/2023/05/Cauliflower-Bisque-Recipe-with-Cheddar-Cheese-_-Chef-Jean-Pierre.jpg', 'https://chefjeanpierre.com/wp-content/uploads/2023/05/Cauliflower-Bisque-Recipe-with-Cheddar-Cheese-_-Chef-Jean-Pierre-500x500.jpg', 'https://chefjeanpierre.com/wp-content/uploads/2023/05/Cauliflower-Bisque-Recipe-with-Cheddar-Cheese-_-Chef-Jean-Pierre-500x375.jpg', 'https://chefjeanpierre.com/wp-content/uploads/2023/05/Cauliflower-Bisque-Recipe-with-Cheddar-Cheese-_-Chef-Jean-Pierre-480x270.jpg']
INFO: 20-Jan-24 15:38:37 	HTTP Request: HEAD https://chefjeanpierre.com/wp-content/uploads/2023/05/Cauliflower-Bisque-Recipe-with-Cheddar-Cheese-_-Chef-Jean-Pierre.jpg "HTTP/1.1 200 OK"
INFO: 20-Jan-24 15:38:37 	HTTP Request: HEAD https://chefjeanpierre.com/wp-content/uploads/2023/05/Cauliflower-Bisque-Recipe-with-Cheddar-Cheese-_-Chef-Jean-Pierre-500x375.jpg "HTTP/1.1 200 OK"
INFO: 20-Jan-24 15:38:37 	HTTP Request: HEAD https://chefjeanpierre.com/wp-content/uploads/2023/05/Cauliflower-Bisque-Recipe-with-Cheddar-Cheese-_-Chef-Jean-Pierre-480x270.jpg "HTTP/1.1 200 OK"
INFO: 20-Jan-24 15:38:37 	HTTP Request: HEAD https://chefjeanpierre.com/wp-content/uploads/2023/05/Cauliflower-Bisque-Recipe-with-Cheddar-Cheese-_-Chef-Jean-Pierre-500x500.jpg "HTTP/1.1 200 OK"
INFO: 20-Jan-24 15:38:38 	HTTP Request: GET https://chefjeanpierre.com/wp-content/uploads/2023/05/Cauliflower-Bisque-Recipe-with-Cheddar-Cheese-_-Chef-Jean-Pierre.jpg "HTTP/1.1 200 OK"
INFO: 20-Jan-24 15:38:39 	original.jpg minified
INFO: 20-Jan-24 15:38:39 	Tiny image saved
INFO: 20-Jan-24 15:47:46 	Database connection established.
INFO: 20-Jan-24 15:47:46 	Context impl SQLiteImpl.
INFO: 20-Jan-24 15:47:46 	Will assume non-transactional DDL.
WARNING: 20-Jan-24 15:47:47 	"get_all" method is deprecated; use "page_all" instead
INFO: 20-Jan-24 15:47:47 	No food found with slug: 'dairy-products-and-dairy-substitutes' skipping fix
INFO: 20-Jan-24 15:48:33 	-----SYSTEM STARTUP----- 

INFO: 20-Jan-24 15:48:33 	------APP SETTINGS------
INFO: 20-Jan-24 15:48:33 	{
    "PRODUCTION": true,
    "BASE_URL": "192.168.1.9",
    "IS_DEMO": false,
    "API_PORT": 9000,
    "API_DOCS": true,
    "TOKEN_TIME": 48,
    "LOG_LEVEL": "INFO",
    "GIT_COMMIT_HASH": "0a00a6ea0d05d2dd944dd9cc6713156dc767e1ed",
    "ALLOW_SIGNUP": true,
    "SECURITY_MAX_LOGIN_ATTEMPTS": 5,
    "SECURITY_USER_LOCKOUT_TIME": 24,
    "DB_ENGINE": "sqlite",
    "DB_PROVIDER": {
        "data_dir": "/config/addons_config/mealie_data",
        "prefix": ""
    },
    "DEFAULT_GROUP": "Home",
    "DEFAULT_EMAIL": "changeme@email.com",
    "SMTP_HOST": null,
    "SMTP_PORT": "587",
    "SMTP_FROM_NAME": "Mealie",
    "SMTP_FROM_EMAIL": null,
    "SMTP_AUTH_STRATEGY": "TLS",
    "LDAP_AUTH_ENABLED": false,
    "LDAP_SERVER_URL": null,
    "LDAP_TLS_INSECURE": false,
    "LDAP_TLS_CACERTFILE": null,
    "LDAP_ENABLE_STARTTLS": false,
    "LDAP_BASE_DN": null,
    "LDAP_QUERY_BIND": null,
    "LDAP_QUERY_PASSWORD": null,
    "LDAP_USER_FILTER": null,
    "LDAP_ADMIN_FILTER": null,
    "LDAP_ID_ATTRIBUTE": "uid",
    "LDAP_MAIL_ATTRIBUTE": "mail",
    "LDAP_NAME_ATTRIBUTE": "name",
    "TESTING": false
}
INFO: 20-Jan-24 15:48:33 	-----SYSTEM STARTUP----- 

INFO: 20-Jan-24 15:48:33 	------APP SETTINGS------
INFO: 20-Jan-24 15:48:33 	{
    "PRODUCTION": true,
    "BASE_URL": "192.168.1.9",
    "IS_DEMO": false,
    "API_PORT": 9000,
    "API_DOCS": true,
    "TOKEN_TIME": 48,
    "LOG_LEVEL": "INFO",
    "GIT_COMMIT_HASH": "0a00a6ea0d05d2dd944dd9cc6713156dc767e1ed",
    "ALLOW_SIGNUP": true,
    "SECURITY_MAX_LOGIN_ATTEMPTS": 5,
    "SECURITY_USER_LOCKOUT_TIME": 24,
    "DB_ENGINE": "sqlite",
    "DB_PROVIDER": {
        "data_dir": "/config/addons_config/mealie_data",
        "prefix": ""
    },
    "DEFAULT_GROUP": "Home",
    "DEFAULT_EMAIL": "changeme@email.com",
    "SMTP_HOST": null,
    "SMTP_PORT": "587",
    "SMTP_FROM_NAME": "Mealie",
    "SMTP_FROM_EMAIL": null,
    "SMTP_AUTH_STRATEGY": "TLS",
    "LDAP_AUTH_ENABLED": false,
    "LDAP_SERVER_URL": null,
    "LDAP_TLS_INSECURE": false,
    "LDAP_TLS_CACERTFILE": null,
    "LDAP_ENABLE_STARTTLS": false,
    "LDAP_BASE_DN": null,
    "LDAP_QUERY_BIND": null,
    "LDAP_QUERY_PASSWORD": null,
    "LDAP_USER_FILTER": null,
    "LDAP_ADMIN_FILTER": null,
    "LDAP_ID_ATTRIBUTE": "uid",
    "LDAP_MAIL_ATTRIBUTE": "mail",
    "LDAP_NAME_ATTRIBUTE": "name",
    "TESTING": false
}
INFO: 20-Jan-24 15:49:07 	HTTP Request: GET https://chefjeanpierre.com/recipes/soups/creamy-cauliflower-bisque/ "HTTP/1.1 200 OK"
ERROR: 20-Jan-24 15:49:07 	Error parsing recipe func_call for 'recipeYield'
INFO: 20-Jan-24 15:49:07 	Image URL: ['https://chefjeanpierre.com/wp-content/uploads/2023/05/Cauliflower-Bisque-Recipe-with-Cheddar-Cheese-_-Chef-Jean-Pierre.jpg', 'https://chefjeanpierre.com/wp-content/uploads/2023/05/Cauliflower-Bisque-Recipe-with-Cheddar-Cheese-_-Chef-Jean-Pierre-500x500.jpg', 'https://chefjeanpierre.com/wp-content/uploads/2023/05/Cauliflower-Bisque-Recipe-with-Cheddar-Cheese-_-Chef-Jean-Pierre-500x375.jpg', 'https://chefjeanpierre.com/wp-content/uploads/2023/05/Cauliflower-Bisque-Recipe-with-Cheddar-Cheese-_-Chef-Jean-Pierre-480x270.jpg']
INFO: 20-Jan-24 15:49:08 	HTTP Request: HEAD https://chefjeanpierre.com/wp-content/uploads/2023/05/Cauliflower-Bisque-Recipe-with-Cheddar-Cheese-_-Chef-Jean-Pierre.jpg "HTTP/1.1 200 OK"
INFO: 20-Jan-24 15:49:08 	HTTP Request: HEAD https://chefjeanpierre.com/wp-content/uploads/2023/05/Cauliflower-Bisque-Recipe-with-Cheddar-Cheese-_-Chef-Jean-Pierre-480x270.jpg "HTTP/1.1 200 OK"
INFO: 20-Jan-24 15:49:08 	HTTP Request: HEAD https://chefjeanpierre.com/wp-content/uploads/2023/05/Cauliflower-Bisque-Recipe-with-Cheddar-Cheese-_-Chef-Jean-Pierre-500x500.jpg "HTTP/1.1 200 OK"
INFO: 20-Jan-24 15:49:08 	HTTP Request: HEAD https://chefjeanpierre.com/wp-content/uploads/2023/05/Cauliflower-Bisque-Recipe-with-Cheddar-Cheese-_-Chef-Jean-Pierre-500x375.jpg "HTTP/1.1 200 OK"
INFO: 20-Jan-24 15:49:08 	HTTP Request: GET https://chefjeanpierre.com/wp-content/uploads/2023/05/Cauliflower-Bisque-Recipe-with-Cheddar-Cheese-_-Chef-Jean-Pierre.jpg "HTTP/1.1 200 OK"
INFO: 20-Jan-24 15:49:09 	original.jpg minified
INFO: 20-Jan-24 15:49:09 	Tiny image saved

### Deployment

Docker (Linux)

### Additional Deployment Details

**Details**
Version: nightly
Build: 0a00a6ea0d05d2dd944dd9cc6713156dc767e1ed
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.42.0

**Checks**
Secure Site: No
Server Side Base URL: No
LDAP Ready: No
Email Configured: No
Docker Volumes: success

**Comment by JohnnyPicnic** [comment]
Does it work by looking whats already created for units or foods in your mealie instance? 
If so could basic measurements come loaded as default?

**Comment by JohnnyPicnic** [comment]
Ok... I misunderstood the seed function.

**Comment by boc-the-git** [comment]
Just FYI @JohnnyPicnic, you appear to be on a fairly old version too, it could be good to update

**Comment by JohnnyPicnic** [comment]
I'm using this Home Assistant add-on [https://github.com/alexbelgium/hassio-addons/tree/master/mealie](url)
Looks like he's using hkotel/mealie:omni-nightly

**Comment by boc-the-git** [comment]
> omni-nightly

That image will never be updated again.

We (the team maintaining Mealie) don't really have anything to do with the HA add-on I'm afraid.
