### ISSUE TITLE
[BUG] - V1 install: "Invalid backup file" error

### ISSUE THREAD

**Issue by jrucker2004** [mealie-recipes/mealie#3024]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I have attempted upgrading to V1 by standing up a brand new docker container from scratch, as the docs recommended.  When trying to restore from my old container's backup file, I get a "invalid backup file" error.

If my backup file is needed for trying to recreate, I will need time to scrape through it to remove any PII

### Steps to Reproduce

1. from a v0.5.6 instance, navigate to settings -> backup and create backup file.
2. Create new docker instance with the latest tag (currently V1.0.0).
3. Log in and navigate to settings -> backups and click upload.
4. Upload the backup file, and click the "Backup Restore" button.
5. Hit the checkbox and then the "Restore Backup" button.

Note that nothing is displayed on this page, no errors, no confirmation that the backup was started or even attempted.

On the confirmation popup at step 5, there's a link sending you to backup/restore instructions.  On that page, is a note about using SQLite:

> If you're using Mealie with SQLite all your data is stored in the /app/data/ folder in the container. You can easily perform entire site backups by stopping the container, and backing up this folder with your chosen tool. This is the best way to backup your data.

I also attempted copying all of the files from the volume from my old container to the new one, and restarting. That didn't work (I didn't really expect it to, based on my other failed attempts at upgrading the container to V1 just following the documentation)

### Please provide relevant logs

Docker container logs:
```
INFO:     192.168.1.80:56438 - "GET /api/admin/about HTTP/1.1" 200 OK
INFO:     192.168.1.80:56436 - "GET /api/admin/about/check HTTP/1.1" 200 OK
INFO:     192.168.1.80:56436 - "GET /api/admin/backups HTTP/1.1" 200 OK
INFO: 21-Jan-24 19:26:40 	initializing backup restore
ERROR: 21-Jan-24 19:26:41 	Invalid backup file. file does not contain required elements (data directory and database.json)
INFO:     127.0.0.1:43552 - "GET /api/app/about HTTP/1.1" 200 OK
ERROR: 21-Jan-24 19:26:41 	Invalid backup file
Traceback (most recent call last):
  File "/app/mealie/routes/admin/admin_backups.py", line 105, in import_one
    backup.restore(file)
  File "/app/mealie/services/backups_v2/backup_v2.py", line 88, in restore
    raise ValueError("Invalid backup file")
ValueError: Invalid backup file
INFO:     192.168.1.80:56436 - "POST /api/admin/backups/mealie-backup-2024-Jan-21.zip/restore HTTP/1.1" 500 Internal Server Error
```

Same error from the /admin/maintenance/logs page:
```
WARNING: 21-Jan-24 19:24:57 	(trapped) error reading bcrypt version
          Traceback (most recent call last):
            File "/opt/pysetup/.venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
              version = _bcrypt.__about__.__version__
          AttributeError: module 'bcrypt' has no attribute '__about__'
          INFO: 21-Jan-24 19:26:03 	initializing backup restore
          ERROR: 21-Jan-24 19:26:03 	Invalid backup file. file does not contain required elements (data directory and database.json)
          ERROR: 21-Jan-24 19:26:03 	Invalid backup file
          Traceback (most recent call last):
            File "/app/mealie/routes/admin/admin_backups.py", line 105, in import_one
              backup.restore(file)
            File "/app/mealie/services/backups_v2/backup_v2.py", line 88, in restore
              raise ValueError("Invalid backup file")
          ValueError: Invalid backup file
          INFO: 21-Jan-24 19:26:40 	initializing backup restore
          ERROR: 21-Jan-24 19:26:41 	Invalid backup file. file does not contain required elements (data directory and database.json)
          ERROR: 21-Jan-24 19:26:41 	Invalid backup file
          Traceback (most recent call last):
            File "/app/mealie/routes/admin/admin_backups.py", line 105, in import_one
              backup.restore(file)
            File "/app/mealie/services/backups_v2/backup_v2.py", line 88, in restore
              raise ValueError("Invalid backup file")
          ValueError: Invalid backup file
```

### Mealie Version

1.0.0

### Deployment

Docker (Linux)

**Comment by ParadingLunatic** [comment]
I was just coming here to write that I'm having the exact same issue with the exact same errors also going from 0.5.6 to 1.0.  I checked the backup files and they indeed don't have a database.json or the data directory in the root of the zip.

**Comment by ZuluForce** [comment]
I had the same problem but had to use the migration tool instead. https://nightly.mealie.io/documentation/getting-started/migrating-to-mealie-v1/#step-3-using-the-migration-tool

This worked and all my recipes are imported.

**Comment by ParadingLunatic** [comment]
Thank you for that!  I completely missed that part in the docs.  Just tried it and it worked for me.

**Comment by Kuchenpirat** [comment]
Great to hear.
Have fun with mealie, I'll go ahead and close this

**Comment by Kuchenpirat** [comment]
Ah my bad, thought @jrucker2004 also confirmed it was working for him. 

If it's not working via the migration feel free to reopen and we'll take another look at the issue.

**Comment by jrucker2004** [comment]
No worries, I just got it working using the instructions above.  I had tried the migration page during my troubleshooting, but completely missed the dropdown.  Thanks!
