### ISSUE TITLE
[BUG] - Warning Message on Password Change Within Docker

### ISSUE THREAD

**Issue by firefly2442** [mealie-recipes/mealie#3040]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When I changed a password per the [instructions in the FAQ](https://nightly.mealie.io/documentation/getting-started/faq/#how-can-i-change-my-password), it was successful but did have a warning message about the `bcrypt` library.

### Steps to Reproduce

```
username@myhost:~/src/mealie$ docker exec -it 1bb bash
root@1bb66895c272:/# python /app/mealie/scripts/change_password.py
Please enter the email of the user you want to reset: admin
INFO: 23-Jan-24 20:38:09 	changing password for admin
Please enter the new password: 
Please enter the new password again: 
WARNING: 23-Jan-24 20:38:13 	(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
INFO: 23-Jan-24 20:38:14 	password change successful
press enter to exit 
```

### Please provide relevant logs

From docker compose logs:

```
mealie  | INFO:     192.168.1.124:57394 - "GET /api/app/about HTTP/1.1" 200 OK
mealie  | INFO:     192.168.1.124:47616 - "GET /api/app/about HTTP/1.1" 200 OK
mealie  | INFO:     192.168.1.124:47618 - "GET /api/app/about/startup-info HTTP/1.1" 200 OK
mealie  | INFO:     172.19.0.1:47098 - "GET / HTTP/1.1" 200 OK
mealie  | WARNING: 23-Jan-24 20:36:32 	(trapped) error reading bcrypt version
mealie  | Traceback (most recent call last):
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
mealie  |     version = _bcrypt.__about__.__version__
mealie  | AttributeError: module 'bcrypt' has no attribute '__about__'
```

### Mealie Version

ghcr.io/mealie-recipes/mealie:latest (v1.0.0 version)

### Deployment

Docker (Linux)

### Additional Deployment Details

Linux pifour 5.15.0-1044-raspi #47-Ubuntu SMP PREEMPT Tue Nov 21 11:33:46 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

Ubuntu 22.04 on Raspberry Pi 4b.

**Comment by michael-genson** [comment]
This is a known issue with bcrypt/passlib. It's harmless, just a warning. We should, however, suppress that log if we can, so I'll leave this issue open

FYI: https://github.com/pyca/bcrypt/issues/684
