### ISSUE TITLE
[BUG] - Any user can Modify group settings

### ISSUE THREAD

**Issue by mazynoah** [mealie-recipes/mealie#3049]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Any user, regardless of their permissions, can access the "Manage Members" page. It makes it pretty hard to, well, manage members as all of them can modify group settings and user permissions (they don't seem to work).

In the logs, when changing the permissions from within a user, a ~~401~~ 403 response is logged. I'd expect the user to not have access to this menu at all.

They can modify the group settings (I don't want users to be able to set the group to public)

### Steps to Reproduce

1) Normal setup
2) Create a group
3) Add users without the Manage, Organize permissions
4) Any user can manage, organize 

### Please provide relevant logs

INFO:     172.18.0.4:38784 - "GET /api/admin/groups?page=1&perPage=-1 HTTP/1.1" 200 OK
INFO:     172.18.0.4:38794 - "GET /api/admin/groups/eed8cacc-0541-49f0-b58d-884787191799 HTTP/1.1" 200 OK
INFO:     172.18.0.4:38808 - "GET /api/admin/groups?page=1&perPage=-1 HTTP/1.1" 200 OK
INFO:     172.18.0.4:38816 - "GET /api/admin/groups/eed8cacc-0541-49f0-b58d-884787191799 HTTP/1.1" 200 OK
INFO:     172.18.0.4:38826 - "GET /api/admin/groups?page=1&perPage=-1 HTTP/1.1" 200 OK
INFO:     172.18.0.4:38842 - "GET /api/users?page=1&perPage=-1 HTTP/1.1" 200 OK
INFO:     172.18.0.4:46428 - "GET /api/admin/users/03e04860-1d7f-4fb1-b1b2-42901f3f80e1 HTTP/1.1" 200 OK
INFO:     172.18.0.4:46438 - "GET /api/admin/groups?page=1&perPage=-1 HTTP/1.1" 200 OK
INFO:     172.18.0.4:46448 - "GET /api/users?page=1&perPage=-1 HTTP/1.1" 200 OK
INFO:     172.18.0.4:46458 - "GET /api/admin/users/32fb0019-9eb5-4a22-9e17-37d85b6d6d3a HTTP/1.1" 200 OK
INFO:     172.18.0.4:46470 - "GET /api/admin/groups?page=1&perPage=-1 HTTP/1.1" 200 OK
INFO:     172.18.0.4:46486 - "PUT /api/admin/users/32fb0019-9eb5-4a22-9e17-37d85b6d6d3a HTTP/1.1" 200 OK
INFO:     172.18.0.4:46488 - "GET /api/admin/groups?page=1&perPage=-1 HTTP/1.1" 200 OK
INFO: 25-Jan-24 22:27:37 	Deleting item with id eed8cacc-0541-49f0-b58d-884787191799
INFO:     172.18.0.4:46496 - "DELETE /api/admin/groups/eed8cacc-0541-49f0-b58d-884787191799 HTTP/1.1" 200 OK
INFO:     172.18.0.4:46512 - "GET /api/admin/groups?page=1&perPage=-1 HTTP/1.1" 200 OK
INFO:     172.18.0.4:56212 - "GET /group/members HTTP/1.1" 307 Temporary Redirect
INFO:     172.18.0.4:56226 - "GET /group/members/ HTTP/1.1" 304 Not Modified
INFO:     172.18.0.4:56240 - "GET /api/users/self HTTP/1.1" 200 OK
INFO:     172.18.0.4:56244 - "GET /api/groups/cookbooks?page=1&perPage=-1&orderBy=position&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.18.0.4:56252 - "GET /api/groups/members HTTP/1.1" 200 OK
INFO:     172.18.0.4:56258 - "PUT /api/groups/permissions HTTP/1.1" 403 Forbidden
INFO:     172.18.0.4:56274 - "PUT /api/groups/permissions HTTP/1.1" 403 Forbidden
INFO:     127.0.0.1:42072 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     172.18.0.4:58868 - "PUT /api/groups/permissions HTTP/1.1" 403 Forbidden
INFO:     172.18.0.4:40356 - "GET /api/admin/about/check HTTP/1.1" 200 OK
INFO:     172.18.0.4:40348 - "GET /api/admin/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:35202 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:33546 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:60508 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     172.18.0.4:60146 - "PUT /api/groups/permissions HTTP/1.1" 403 Forbidden
INFO:     127.0.0.1:47038 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     172.18.0.4:50556 - "PUT /api/groups/permissions HTTP/1.1" 403 Forbidden
INFO:     172.18.0.4:50560 - "PUT /api/groups/permissions HTTP/1.1" 403 Forbidden
INFO:     172.18.0.4:50562 - "GET /api/organizers/categories?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.18.0.4:50596 - "GET /api/organizers/tags?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.18.0.4:50580 - "GET /api/foods?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.18.0.4:50600 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.18.0.4:50578 - "GET /api/recipes?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1706218196202&searchSeed=1706218196202&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
INFO:     172.18.0.4:37176 - "GET /api/groups/statistics HTTP/1.1" 200 OK
INFO:     172.18.0.4:37186 - "GET /api/users/self/group HTTP/1.1" 200 OK
INFO:     172.18.0.4:37194 - "GET /api/groups/members HTTP/1.1" 200 OK
INFO:     172.18.0.4:37202 - "PUT /api/groups/permissions HTTP/1.1" 403 Forbidden
INFO:     172.18.0.4:37206 - "PUT /api/groups/permissions HTTP/1.1" 403 Forbidden
INFO:     172.18.0.4:37208 - "GET /api/organizers/categories?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.18.0.4:37214 - "GET /api/organizers/tags?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.18.0.4:37212 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.18.0.4:37224 - "GET /api/recipes?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1706218206672&searchSeed=1706218206672&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
INFO:     172.18.0.4:52686 - "GET /api/users/self/group HTTP/1.1" 200 OK
INFO:     172.18.0.4:52680 - "GET /api/groups/statistics HTTP/1.1" 200 OK
INFO:     172.18.0.4:52698 - "GET /api/groups/members HTTP/1.1" 200 OK
INFO:     172.18.0.4:52702 - "GET /api/organizers/categories?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.18.0.4:52716 - "GET /api/organizers/tags?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.18.0.4:52704 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.18.0.4:52728 - "GET /api/recipes?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1706218210150&searchSeed=1706218210150&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
INFO:     172.18.0.4:52742 - "GET /api/groups/statistics HTTP/1.1" 200 OK
INFO:     172.18.0.4:52754 - "GET /api/users/self/group HTTP/1.1" 200 OK
INFO:     172.18.0.4:52798 - "GET /api/organizers/tags?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.18.0.4:52762 - "GET /api/organizers/categories?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.18.0.4:52766 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.18.0.4:52782 - "GET /api/recipes?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1706218213025&searchSeed=1706218213025&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
INFO:     172.18.0.4:52812 - "GET /api/users/self/group HTTP/1.1" 200 OK
INFO:     172.18.0.4:52816 - "GET /api/groups/statistics HTTP/1.1" 200 OK
INFO:     172.18.0.4:52824 - "GET /api/groups/self HTTP/1.1" 200 OK
INFO:     127.0.0.1:36434 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     172.18.0.4:50188 - "PUT /api/groups/preferences HTTP/1.1" 200 OK
INFO:     172.18.0.4:50198 - "PUT /api/groups/preferences HTTP/1.1" 200 OK
INFO:     172.18.0.4:50204 - "PUT /api/groups/preferences HTTP/1.1" 200 OK
INFO:     127.0.0.1:44310 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:59104 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     172.18.0.4:51708 - "GET /api/organizers/categories?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.18.0.4:51720 - "GET /api/organizers/tags?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.18.0.4:51706 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.18.0.4:51696 - "GET /api/recipes?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1706218304737&searchSeed=1706218304737&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
INFO:     172.18.0.4:51734 - "GET /api/users/self/group HTTP/1.1" 200 OK
INFO:     172.18.0.4:51726 - "GET /api/groups/statistics HTTP/1.1" 200 OK
INFO:     127.0.0.1:48550 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     172.18.0.4:57436 - "POST /api/recipes HTTP/1.1" 201 Created
INFO:     172.18.0.4:57448 - "GET /api/recipes/utyjt HTTP/1.1" 200 OK
INFO:     172.18.0.4:57460 - "GET /api/media/recipes/65185588-bdb5-42a6-9211-e65de7e78909/images/original.webp?rnd=1&version= HTTP/1.1" 404 Not Found
INFO:     172.18.0.4:57480 - "GET /api/recipes/utyjt/comments HTTP/1.1" 200 OK
INFO:     172.18.0.4:57468 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.18.0.4:57516 - "GET /api/organizers/tags?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.18.0.4:57504 - "GET /api/units?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.18.0.4:57544 - "GET /api/organizers/tags?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.18.0.4:57494 - "GET /api/organizers/categories?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.18.0.4:57556 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.18.0.4:57528 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.18.0.4:57542 - "GET /api/organizers/categories?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.18.0.4:42466 - "PUT /api/recipes/utyjt HTTP/1.1" 200 OK
INFO:     172.18.0.4:42476 - "GET /api/recipes/utyjt/comments HTTP/1.1" 200 OK
INFO:     172.18.0.4:42484 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.18.0.4:42488 - "GET /api/shared/recipes?page=1&perPage=-1&recipe_id=65185588-bdb5-42a6-9211-e65de7e78909 HTTP/1.1" 200 OK
INFO:     172.18.0.4:42504 - "POST /api/shared/recipes HTTP/1.1" 201 Created
INFO:     172.18.0.4:44276 - "GET /g/home/shared/r/3fba6dee-221e-428c-b8af-079dcce1cc60 HTTP/1.1" 200 OK
INFO:     172.18.0.4:44284 - "GET /_nuxt/75f58f5.js HTTP/1.1" 304 Not Modified
INFO:     172.18.0.4:44298 - "GET /api/users/self HTTP/1.1" 200 OK
INFO:     172.18.0.4:44308 - "GET /api/recipes/shared/3fba6dee-221e-428c-b8af-079dcce1cc60 HTTP/1.1" 200 OK
INFO:     172.18.0.4:44322 - "GET /api/recipes/utyjt/comments HTTP/1.1" 200 OK
INFO:     172.18.0.4:44316 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK

### Mealie Version

**Version** v1.0.0
**Build** f0bbe796ce40ef32a4a00eecdfb0efe4eef9da07
**Application Mode** Production 

### Deployment

Docker (Linux)

### Additional Deployment Details

default docker compose file

**Comment by Kuchenpirat** [comment]
Hi, thanks for raising this issue. 
I was able to verify that users without the right permissions are able to change group settings (which will be resolved at least for the frontend by #3100) but i was not able to generate an invite link with a user that has no invite permissions (through the frontend). 

I don't see any requests to the `/api/groups/invites` either in your logs. Can you elaborate on how you generated the invite link?

**Comment by mazynoah** [comment]
Hi, sorry. When I wrote this issue I realized other users could not send invites and updated my text accordingly. I simply forgot to update the tittle.

I changed the title.

**Comment by Kuchenpirat** [comment]
Ok, no worries 👍
