### ISSUE TITLE
[BUG] - SECURITY_MAX_LOGIN_ATTEMPTS not working

### ISSUE THREAD

**Issue by duczz** [mealie-recipes/mealie#3093]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I tried to login multiple times wrong, and hope the i will get blocked via IP, but these not working (Code below)

### Steps to Reproduce

Login many times :)

### Please provide relevant logs

ERROR: 01-Feb-24 07:31:24 	Incorrect username or password from xxxxxxx
ERROR: 01-Feb-24 07:31:26 	Incorrect username or password from xxxxxxx
ERROR: 01-Feb-24 07:31:27 	Incorrect username or password from xxxxxxx
ERROR: 01-Feb-24 07:31:30 	Incorrect username or password from xxxxxxx
ERROR: 01-Feb-24 07:31:33 	Incorrect username or password from xxxxxxx
ERROR: 01-Feb-24 07:31:36 	Incorrect username or password from xxxxxxx
ERROR: 01-Feb-24 07:31:39 	Incorrect username or password from xxxxxxx
ERROR: 01-Feb-24 07:31:42 	Incorrect username or password from xxxxxxx
ERROR: 01-Feb-24 07:31:45 	Incorrect username or password from xxxxxxx
ERROR: 01-Feb-24 07:32:02 	Incorrect username or password from xxxxxxx

### Mealie Version

1.1.0

### Deployment

Other (please specify below)
HomeAssistant Addon [https://github.com/alexbelgium/hassio-addons/tree/master/mealie](url)

### Additional Deployment Details

```
    "PRODUCTION": true,
    "BASE_URL": "https://xxxxxxxx.net:9925",
    "STATIC_FILES": "/spa/static",
    "IS_DEMO": false,
    "API_PORT": 9000,
    "API_DOCS": true,
    "TOKEN_TIME": 48,
    "LOG_LEVEL": "INFO",
    "GIT_COMMIT_HASH": "xxxxxxxxxxxxxxxxxxxxxxxxx",
    "ALLOW_SIGNUP": false,
    "SECURITY_MAX_LOGIN_ATTEMPTS": 3,
    "SECURITY_USER_LOCKOUT_TIME": 24,
    "DB_ENGINE": "sqlite",
    "DEFAULT_GROUP": "Home",
    "SMTP_HOST": null,
    "SMTP_PORT": "587",
    "SMTP_FROM_NAME": "Mealie",
    "SMTP_FROM_EMAIL": null,
    "SMTP_AUTH_STRATEGY": "TLS",
    "LDAP_AUTH_ENABLED": false,
    "LDAP_SERVER_URL": null,
    "LDAP_TLS_INSECURE": false,
    "LDAP_TLS_CACERTFILE": null,
    "LDAP_ENABLE_STARTTLS": false,
    "LDAP_BASE_DN": null,
    "LDAP_QUERY_BIND": null,
    "LDAP_QUERY_PASSWORD": null,
    "LDAP_USER_FILTER": null,
    "LDAP_ADMIN_FILTER": null,
    "LDAP_ID_ATTRIBUTE": "uid",
    "LDAP_MAIL_ATTRIBUTE": "mail",
    "LDAP_NAME_ATTRIBUTE": "name",
    "TESTING": false
```

**Comment by boc-the-git** [comment]
What happens if you enter the correct password? It looks like, based on the following test, that if you enter the correct password you'll get told you're locked out, but if you keep entering the incorrect password, you'll get told it's invalid.
Is that imperfect? Possibly..

https://github.com/mealie-recipes/mealie/blob/a7775ea7ef2995dca8c8dd822fd7a33b70b0265a/tests/integration_tests/user_tests/test_user_login.py#L48-L68
