### ISSUE TITLE
password smtp-config in docker-compose no accept

### ISSUE THREAD

**Issue by birinrw** [mealie-recipes/mealie#3112]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

when the password have a special character (like $! or so) the config in docker-compose.yml work with it, error for use ! the installation doesn't go, the docker don't work. 

### Steps to Reproduce

1. SMTP_PASWORD: 56!$=Klhgofkkm

### Please provide relevant logs

docker-compose.yml

### Mealie Version

1.1.1

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
This is not an issue with mealie, but a feature with docker compose. Please reads their documentation

https://docs.docker.com/compose/compose-file/compose-file-v2/#variable-substitution

Or this 

https://stackoverflow.com/questions/40619582/how-can-i-escape-a-dollar-sign-in-a-docker-compose-file

**Comment by birinrw** [comment]
big thanks, now my password work for the email-config in the docker-compose-file correct.
