### ISSUE TITLE
Deleting ingredient from food data blanks the entry in recipies

### ISSUE THREAD

**Issue by TheHYPO35** [mealie-recipes/mealie#3125]
I'm not 100% certain, but I'm fairly sure my deleting of a food data entry resulted in the name of that food item being blanked from an ingredient entry in a recipe.

It would be nice to either have a validation with a warning pop up if you are deleting an entry that is used in any existing recipes, and/or have any entries that contain the food item add the name of the food item back to the "notes" field. Otherwise, deleting a food item can unintentionally delete important information from a recipe.

**Comment by boc-the-git** [comment]
Please resubmit this following the bug template and providing all relevant information.
https://github.com/mealie-recipes/mealie/issues/new?template=bug-report.yaml
