### ISSUE TITLE
[BUG] - Click-and-drag re-ordering ingredients doesn't work in "parse" screen

### ISSUE THREAD

**Issue by TheHYPO35** [mealie-recipes/mealie#3126]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When you are editing a recipe, there is a little grid of 12 dots next to each ingredient where you can click and drag them into whatever order is needed.

When you go to "parse" an ingredient list, this little grid is still there, but clicking and dragging doesn't do anything. Either the functionality to move ingredients is broken (it would be nice to have this function there), or the function is not intended to exist in the parse screen, and the grid of dots suggesting that it is should be removed.

### Steps to Reproduce

Edit any recipe with multiple ingredients. Ensure that in "settings", that "ingredient amounts" is enabled, then click "parse" under the ingredient list. The click and drag dots make the curse change to a "click and drag" cursor, but clicking and dragging does nothing.

This is in Chrome. I haven't tested in other browsers.

### Please provide relevant logs

I don't believe there are relevant logs for this.

### Mealie Version

v1.1.1 https://github.com/mealie-recipes/mealie/commit/9bf2e3fabd4bb9dce72f472ae13e064b5e9f6b78

Occurs on mealie demo site as well

### Deployment

Docker (Linux)

**Comment by Kuchenpirat** [comment]
Hey, thanks for reporting this. 
Can confirm that the items in the parsing site are not draggable.
