### ISSUE TITLE
[BUG] - Cannot copy to clipboard over HTTP, so no way to access password reset link.

### ISSUE THREAD

**Issue by jozzo402** [mealie-recipes/mealie#3141]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Copy to clipboard buttons don't work when accessing Mealie via HTTP. Browser functionality is blamed for this, however I have no issues copying to clipboard over HTTP on any other web apps I run, such as Gitea and SnippetBox. This seems to only be an issue with Mealie.
This leads to the other issue: on the Admin User Management page the "Generate Password Reset Link" does not provide any visible link to copy, relying on the copy to clipboard button. This means there's no way for me to get the password reset link.

For the first part, Mealie should either support copying over HTTP, or make it clearer in the error message that copying over HTTP is not supported by Mealie rather than blaming the browser.
For the second part, the password reset link should appear somewhere on the page to allow for manual copying.

### Steps to Reproduce

1) Access mealie over a HTTP connection (not HTTPS)
2) Navigate to */admin/manage/users, and click on any user
3) Click the Generate Password Reset Link

### Please provide relevant logs

Browser console logs this:
> Clipboard is currently not supported by your browser. Ensure you're on a secure (https) site.

Mealie container logs this:
> "GET /g/home/admin/manage/users/<user-id>/password-reset HTTP/1.1" 200 OK

### Mealie Version

v1.2.0
Build
0800a8d00a9fa154df40040304d46d4900d42e07 

### Deployment

Docker (Linux)

**Comment by Kuchenpirat** [comment]
Hey, thanks for bringing this to our attention. 

Not being able to copy over http is not a mealie issue, but a security feature of your browser. I have no idea why this is working for your other apps. Just out of curiosity: Are they also using a button to copy, or are you just copiing the text from a text field? 

Non the less i can confirm that it is currently not possible to get the password reset link in the gui via a unsecure http connection.

**Comment by jozzo402** [comment]
Both Snippetbox and Gitea use a copy button like Mealie, I'm not manually copying the text.

**Comment by Kuchenpirat** [comment]
Ah ok, thanks for reporting back. 
I have seen a few workarounds to get this working, but as far as i know, this is not intended behaviour. 

So i think we will stick with this only working for https connections.

**Comment by jozzo402** [comment]
Alright no worries, as a workaround I deleted their account and they made a new one with a password they'll definitely remember this time™

I'm hosting quite a number of apps all accessed over HTTP and the only time I've encountered this clipboard issue is with Mealie.
SnippetBox's copy to clipboard seems to be very straightforward, doesn't look like any workarounds are going on:
https://github.com/pawelmalak/snippet-box/blob/f501941a22ead0fccd196d109098e9b065205d98/client/src/components/Snippets/SnippetCard.tsx
Although it is in typescript, so perhaps just an issue with python?

**Comment by Kuchenpirat** [comment]
i'll take a look at the actual implementation. 
You did not have to go quite that nuclear. There is also a password reset script inside the container: https://nightly.mealie.io/documentation/getting-started/faq/#how-can-i-change-my-password

**Comment by Kuchenpirat** [comment]
Just had a look at the package they are using. They have a fallback to a deprecated command that is still supported by most browsers. 

https://github.com/feross/clipboard-copy/blob/master/index.js
