### ISSUE TITLE
[BUG] - Reoccuring 502 Errors

### ISSUE THREAD

**Issue by malewpro** [mealie-recipes/mealie#3159]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I have two separate containers running Mealie, one for me, and one for my family who live away from me. Mealie has been fantastic, but sometime yesterday afternoon I started getting a load of notifications from Uptime Kuma reporting 502 status code for both Mealie containers. Generally, the container would remain inaccessible for a few minutes, and then come back "online" for 1-2 minutes, and then send 502 errors again. This has continued all night and day today. I've restarted the containers, and ensured they are up to date, and no errors are reported in the logs. 

### Steps to Reproduce

I'm not sure, unfortunately. I was not working on anything in my homelab or network when this started. Mealie has been very stable until this started all of a sudden. Configuration information is available below.

### Please provide relevant logs

Here are the logs from one of my containers  from starting the container through a couple bouts of "502 errors". The second container logs are more or less identical.  

Personal Mealie:
INFO: 11-Feb-24 17:00:24 	Database connection established.

INFO: 11-Feb-24 17:00:24 	Context impl SQLiteImpl.

INFO: 11-Feb-24 17:00:24 	Will assume non-transactional DDL.

INFO: 11-Feb-24 17:00:24 	Checking for migration data fixes

WARNING: 11-Feb-24 17:00:25 	"get_all" method is deprecated; use "page_all" instead

INFO:     Started server process [7]

INFO:     Waiting for application startup.

INFO: 11-Feb-24 17:00:29 	-----SYSTEM STARTUP----- 

INFO: 11-Feb-24 17:00:29 	------APP SETTINGS------

INFO: 11-Feb-24 17:00:29 	{

    "theme": {

        "light_primary": "#E58325",

        "light_accent": "#007A99",

        "light_secondary": "#973542",

        "light_success": "#43A047",

        "light_info": "#1976D2",

        "light_warning": "#FF6D00",

        "light_error": "#EF5350",

        "dark_primary": "#E58325",

        "dark_accent": "#007A99",

        "dark_secondary": "#973542",

        "dark_success": "#43A047",

INFO:     Application startup complete.

        "dark_info": "#1976D2",

        "dark_warning": "#FF6D00",

        "dark_error": "#EF5350"

    },

    "PRODUCTION": true,

    "BASE_URL": "https://mealie.ianmandt.com",

    "STATIC_FILES": "/spa/static",

    "IS_DEMO": false,

    "API_PORT": 9000,

    "API_DOCS": true,

    "TOKEN_TIME": 3000,

    "LOG_LEVEL": "INFO",

    "GIT_COMMIT_HASH": "c9852daf0e213dc4cadf97971c7787cf6fc66dfc",

    "ALLOW_SIGNUP": false,

    "SECURITY_MAX_LOGIN_ATTEMPTS": 5,

    "SECURITY_USER_LOCKOUT_TIME": 1,

    "DB_ENGINE": "sqlite",

    "DEFAULT_GROUP": "Home",

    "SMTP_HOST": "smtp.gmail.com",

    "SMTP_PORT": "465",

    "SMTP_FROM_NAME": "Mealie",

    "SMTP_FROM_EMAIL": "mandtian@gmail.com",

    "SMTP_AUTH_STRATEGY": "SSL",

    "LDAP_AUTH_ENABLED": false,

    "LDAP_SERVER_URL": null,

    "LDAP_TLS_INSECURE": false,

    "LDAP_TLS_CACERTFILE": null,

    "LDAP_ENABLE_STARTTLS": false,

    "LDAP_BASE_DN": null,

    "LDAP_QUERY_BIND": null,

    "LDAP_QUERY_PASSWORD": null,

    "LDAP_USER_FILTER": null,

    "LDAP_ADMIN_FILTER": null,

    "LDAP_ID_ATTRIBUTE": "uid",

    "LDAP_MAIL_ATTRIBUTE": "mail",

    "LDAP_NAME_ATTRIBUTE": "name",

    "TESTING": false

}

INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)

INFO:     127.0.0.1:47226 - "GET /api/app/about HTTP/1.1" 200 OK

INFO:     127.0.0.1:55742 - "GET /api/app/about HTTP/1.1" 200 OK

INFO:     127.0.0.1:39252 - "GET /api/app/about HTTP/1.1" 200 OK

INFO:     172.20.0.6:38404 - "GET / HTTP/1.1" 200 OK

INFO:     127.0.0.1:60548 - "GET /api/app/about HTTP/1.1" 200 OK

INFO:     127.0.0.1:44794 - "GET /api/app/about HTTP/1.1" 200 OK

INFO:     127.0.0.1:53396 - "GET /api/app/about HTTP/1.1" 200 OK

INFO:     127.0.0.1:43526 - "GET /api/app/about HTTP/1.1" 200 OK

INFO:     127.0.0.1:46540 - "GET /api/app/about HTTP/1.1" 200 OK

INFO:     172.20.0.6:59698 - "GET / HTTP/1.1" 200 OK

INFO:     127.0.0.1:58464 - "GET /api/app/about HTTP/1.1" 200 OK

INFO:     127.0.0.1:53828 - "GET /api/app/about HTTP/1.1" 200 OK

INFO:     172.20.0.6:48286 - "GET / HTTP/1.1" 200 OK

INFO:     127.0.0.1:51418 - "GET /api/app/about HTTP/1.1" 200 OK

INFO:     127.0.0.1:40488 - "GET /api/app/about HTTP/1.1" 200 OK

INFO:     172.20.0.6:49918 - "GET / HTTP/1.1" 200 OK

INFO:     127.0.0.1:43824 - "GET /api/app/about HTTP/1.1" 200 OK

INFO:     127.0.0.1:38814 - "GET /api/app/about HTTP/1.1" 200 OK

INFO:     127.0.0.1:42526 - "GET /api/app/about HTTP/1.1" 200 OK

INFO:     127.0.0.1:44124 - "GET /api/app/about HTTP/1.1" 200 OK

INFO:     127.0.0.1:32884 - "GET /api/app/about HTTP/1.1" 200 OK

INFO:     172.20.0.6:55964 - "GET / HTTP/1.1" 200 OK

INFO:     127.0.0.1:44202 - "GET /api/app/about HTTP/1.1" 200 OK

INFO:     127.0.0.1:44186 - "GET /api/app/about HTTP/1.1" 200 OK

INFO:     172.20.0.6:38326 - "GET / HTTP/1.1" 200 OK

INFO:     127.0.0.1:41418 - "GET /api/app/about HTTP/1.1" 200 OK

INFO:     127.0.0.1:43996 - "GET /api/app/about HTTP/1.1" 200 OK

This is what Uptime Kuma reports. I paused monitoring overnight to shutdown the notifications. 
<img width="911" alt="Screenshot 2024-02-11 at 5 14 37 PM" src="https://github.com/mealie-recipes/mealie/assets/33041090/4da5a945-309b-41fa-b681-02935885be6f">

### Mealie Version

v1.2.0 for both containers

### Deployment

Docker (Linux), TrueNAS

### Additional Deployment Details

- Proxy: Cloudflare Tunnel (all other services using cloudflare tunnel are unaffected, only Mealie is reporting issues)
- OS: Ubuntu 22.04 VM running on TrueNAS

**Comment by Kuchenpirat** [comment]
Hey, thanks for submitting this issue, but it seems like this is more likely to do something with your setup. Might be DNS, Firewall or Proxy. 

If the routing would work correct, but mealie would simply be down, you would get an 404 error. 

Additionally your logs show that the mealie health checks are reporting no indication of an outage or similar errors.

**Comment by malewpro** [comment]
Thanks, that's a good point. I assumed it was Mealie related since it's only affecting Mealie containers but your explanation makes sense. I'll poke around some more and see if I can find another cause
