### ISSUE TITLE
[BUG] - Backend configuration docs: Unclear Webworker documentation

### ISSUE THREAD

**Issue by Millio345** [mealie-recipes/mealie#3165]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

On the backend config, located at https://nightly.mealie.io/documentation/getting-started/installation/backend-config/ , there's a few issues:

- WORKERS_PER_CORE, MAX_WORKERS and WEB_CONCURRENCY have text 'More info here' that should be a link but is not, f.e. "More info [here][max_workers]" 
- MAX_WORKERS description says "Default is not set meaning unlimited" , yet right next to it in the default column it says "1"

The main reason I was looking this up is because the example docker compose files include these settings and I was trying to understand what they did and why they needed to be specifically included in the docker environment variables. If "1" is indeed the default for MAX_WORKERS and WEB_CONCURRENCY and it's strongly recommended not to change these settings, then maybe it'd be better to just remove those options from the example docker compose?

### Steps to Reproduce

1. Go to https://nightly.mealie.io/documentation/getting-started/installation/backend-config/
2. Scroll down to Webworker

### Please provide relevant logs

N/A

### Deployment

Docker (Linux)

**Comment by Kuchenpirat** [comment]
Hey thanks for raising this issue. 
Seems like the pages have been moved and some links have not been copied over. 
This should be an easy fix 👍
