### ISSUE TITLE
[BUG] - Nutritional info displays empty values

### ISSUE THREAD

**Issue by BastianLo** [mealie-recipes/mealie#3168]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

The Nurtrition field displays nutritional values with enpty values. The result looks quite confusing.

<img width="390" alt="Bildschirmfoto 2024-02-13 um 14 31 15" src="https://github.com/mealie-recipes/mealie/assets/63297415/d43ef6e2-1bd8-4547-aebf-068db120b008">

I instead expect mealie to only display nutritional values, which have a value assigned. This is what it could look like:
<img width="389" alt="Bildschirmfoto 2024-02-13 um 14 35 19" src="https://github.com/mealie-recipes/mealie/assets/63297415/080f805d-d464-4f55-b291-7240925f5d49">

### Steps to Reproduce

1. Create a recipe
2. add nutritional values, where some values are missing
3. enable displaying the nutritional values

### Please provide relevant logs

no logs

### Mealie Version

I think this applies to all versions

### Deployment

Docker (Linux)

**Comment by boc-the-git** [comment]
Seems like bad UX.
