### ISSUE TITLE
[BUG] - openapi.json `securitySchemes` does not contain bearer auth flow

### ISSUE THREAD

**Issue by jamesanderson9182** [mealie-recipes/mealie#3185]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

The `securitySchemes` of the generated openapi.json file does not contain the bearer token flow and therefore the `${baseUrl]/docs#/` endpoint does now explain how to use the api token that you can generate from the UI.

It was quite hard to figure out how to use the token that is generated from the UI. From looking at the docs of an iOS shortcut I was able to figure this out. It could be made more clear how to use it.

I cloned the repo to look for the openapi.json file but it looks like it's being generated here https://github.com/mealie-recipes/mealie/blob/9ecef4c25f1afdc9f5a767d3fc695cd57b156a35/dev/code-generation/utils/open_api_parser.py#L74 but updating the python code is a bit outside my area of expertise.

### Steps to Reproduce

1. visit https://demo.mealie.io/docs
2. click link at top https://demo.mealie.io/openapi.json 
3. Note that securitySchemes section only explains oauth 2 flow, no mention of bearer token
4. go back to swagger ui page https://demo.mealie.io/docs
5. click authorize
6. Note that there's no bearer token option here 

### Please provide relevant logs

n/a

### Mealie Version

v1.1.0

### Deployment

Docker (Linux)

**Comment by jamesanderson9182** [comment]
I know it's only been 2 minutes since I opened this but on reflection. The OAuth 2 flow does result in a bearer token. So I guess it's being shown. I'm not sure my suggestion is correct maybe it's the MkDocs site that need updated? Something added to the "Getting a Token" section? If you agree, I'd be happy to contribute an explanation

https://github.com/mealie-recipes/mealie/blob/484c60c7ea15c5ae17357ff4194baea836e1ba4e/docs/docs/documentation/getting-started/api-usage.md#L5

**Comment by hay-kot** [comment]
Adding a note about the bearer token and header in the docs is fine with me. As far as the OpenAPI spec, that's generated via FastAPI so I think that anything related to that would be an upstream issue with the library.

**Comment by mrshappy0** [comment]
Has anyone found a workaround for this? I'm been digging myself and would love to be able to use a bearer token in the swagger UI.

**Comment by mrshappy0** [comment]
I'm not skilled in python but this issue seems to show a path forward. Seems like a code change in Mealie for the fastapi stuff?
https://github.com/fastapi/fastapi/issues/142

**Comment by mrshappy0** [comment]
And this documentation might be helpful too. Maybe a possible good first contribution to Mealie? I will save this thread and revisit this week to consider a contribution.
[https://fastapi.tiangolo.com/reference/security/?h=apikeyhe#fastapi.security.APIKeyHeader](https://fastapi.tiangolo.com/reference/security/?h=apikeyhe#fastapi.security.APIKeyHeader)
