### ISSUE TITLE
[BUG] - MQTT broken by upgrade to paho-mqtt 2.0

### ISSUE THREAD

**Issue by boc-the-git** [mealie-recipes/mealie#3190]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I merged an upgrade to paho-mqtt yesterday, https://github.com/mealie-recipes/mealie/pull/3149

That appears to have broken some things, as shown in the logs. I merged that because I have a theory I might be the only person using MQTT notifications in Mealie, so the impact was fairly limited for any potential issue.
as such, I'm also not rushing a fix to downgrade the version back to the previous. Fixing forward will be the way to go.

### Steps to Reproduce

1) Enable a notifier via Apprise, using MQTT
2) It errors

Sorry, these aren't great instructions! What was working ~48 hours ago, now is not.

### Please provide relevant logs

```
mealie    | INFO:     127.0.0.1:40962 - "GET /api/app/about HTTP/1.1" 200 OK
mealie    | INFO: 18-Feb-24 12:45:08    HTTP Request: GET https://www.bestrecipes.com.au/recipes/2-ingredient-nutella-cake-recipe/3pzk6bvf "HTTP/1.1 302 Moved Temporarily"
mealie    | INFO: 18-Feb-24 12:45:09    Image URL: ['https://img.bestrecipes.com.au/9vz3ms-J/br/2016/09/2-ingredient-nutella-cake-recipe-519754-1.jpg']
mealie    | INFO: 18-Feb-24 12:45:10    HTTP Request: HEAD https://img.bestrecipes.com.au/9vz3ms-J/br/2016/09/2-ingredient-nutella-cake-recipe-519754-1.jpg "HTTP/1.1 200 OK"
mealie    | INFO: 18-Feb-24 12:45:10    HTTP Request: GET https://img.bestrecipes.com.au/9vz3ms-J/br/2016/09/2-ingredient-nutella-cake-recipe-519754-1.jpg "HTTP/1.1 200 OK"
mealie    | INFO: 18-Feb-24 12:45:10    original.jpg minified
mealie    | INFO: 18-Feb-24 12:45:10    Tiny image saved
mealie    | INFO:     100.95.152.80:0 - "POST /api/recipes/create-url HTTP/1.1" 201 Created
mealie    | INFO:     100.95.152.80:0 - "GET /api/recipes/2-ingredient-nutella-cake-recipe HTTP/1.1" 200 OK
mealie    | Exception ignored in: <function Client.__del__ at 0x7fd4571b5870>
mealie    | Traceback (most recent call last):
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/paho/mqtt/client.py", line 874, in __del__
mealie    |     self._reset_sockets()
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/paho/mqtt/client.py", line 1133, in _reset_sockets
mealie    |     self._sock_close()
mealie    |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/paho/mqtt/client.py", line 1119, in _sock_close
mealie    |     if not self._sock:
mealie    | AttributeError: 'Client' object has no attribute '_sock'
mealie    | ERROR: 18-Feb-24 12:45:11   Could not load MQTT Notification URL: mqtt://mealie:y...$@1...5:1883/mealie
mealie    | ERROR: 18-Feb-24 12:45:11   There are no service(s) to notify
mealie    | INFO:     100.95.152.80:0 - "GET /api/media/recipes/77ad69d1-d5b0-4964-93a2-398d092ece78/images/original.webp?rnd=1&version=Rjck HTTP/1.1" 200 OK
mealie    | INFO:     192.168.16.1:36286 - "GET / HTTP/1.1" 200 OK
```

### Mealie Version

Nightly, https://github.com/mealie-recipes/mealie/commit/a7775ea7ef2995dca8c8dd822fd7a33b70b0265a

### Deployment

Docker (Linux)

**Comment by boc-the-git** [comment]
Could the answer be that apprise needs to update something on their end? Not sure, haven't looked into it as yet as this isn't a burning issue.

**Comment by Mraedis** [comment]
This is a paho issue, see the release notes for 2.0: https://github.com/eclipse/paho.mqtt.python/blob/v2.0.0/docs/migrations.rst

Specifically the first line:

> Add version to user callbacks (on_publish, on_connect...). tl; dr: add mqtt.CallbackAPIVersion.VERSION1 as first argument to Client()


They added a required field.

**Comment by boc-the-git** [comment]
Thanks @Mraedis !
I did look for release notes the other day but couldn't find any.. it's been a full on week though.

That info is definitely useful!

Are you using the MQTT functionality and would prefer we downgrade to get it working again? (I don't have an ETA on when I'll get around to the fix forward approach (obviously, PRs welcome!))
