### ISSUE TITLE
[BUG] or [QUESTION] How to search on extra fields?

### ISSUE THREAD

**Issue by stephanvierkant** [mealie-recipes/mealie#3192]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [x] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I've added recipes with the API and I'd like to search on the Extra fields. How can I do this? I've tried many different formats but none of them gives the expected results

### Steps to Reproduce

1. Add a recipe with the API with extra fields
2. Use `api/recipes` to search. Use ?search or ?queryFilter to get results

### Please provide relevant logs

n/a

### Mealie Version

1.2.0

### Deployment

Docker (Synology)

**Comment by michael-genson** [comment]
I don't think this is currently possible, though worth a feature request. Extras are mainly to attach additional data to objects, rather than to query them (though I can see why you might want to)
