### ISSUE TITLE
Recipe creation does not fill in the correct fields

### ISSUE THREAD

**Issue by FuXXz** [mealie-recipes/mealie#3199]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When creating recipes, the fields for quantity, unit and food are not filled in.
Instead, everything is written in the Notes line.
This means that the quantities cannot be calculated and I have to manually divide up all the ingredients and fill them in correctly.

![Screenshot 2024-02-20 124937](https://github.com/mealie-recipes/mealie/assets/9010594/1281ae34-f25b-44fb-a39d-0093c7364b17)
![Screenshot 2024-02-20 125011](https://github.com/mealie-recipes/mealie/assets/9010594/28f5202f-93d7-4b28-922f-df320fa8612a)
![Screenshot 2024-02-20 125026](https://github.com/mealie-recipes/mealie/assets/9010594/501bbd3a-1bcb-46fd-9545-d6d784bb0116)

### Steps to Reproduce

Create Recipe

### Please provide relevant logs

No Logs

### Mealie Version

Demo Page and Docker Image with Version v1.2.0 (Recipe Scraper Version
 14.54.0)

### Deployment

Docker (Synology)

**Comment by michael-genson** [comment]
You have to parse the recipe to fill those out. There should be a "parse" button under the ingredients while editing

**Comment by FuXXz** [comment]
Ok thanks.
However, the note in the upper part is to be taken seriously because Mealie only creates garbage when parsing :(
"Experimental Feature
Mealie can use natural language processing to attempt to parse and create units, and foods for your Recipe ingredients. This is experimental and may not work as expected. If you choose to not use the parsed results you can select cancel and your changes will not be saved."

**Comment by michael-genson** [comment]
The NLP parser only works well with English, have you tried switching to the Brute Force parser?

**Comment by FuXXz** [comment]
Yes i have tried.
Now at least I know the possibilities. I can either live with it or not. I just wondered why it wasn't worth mentioning with all the other products. It just works.
Didn't think it would be such a hurdle when scrapping

**Comment by RealFoxie** [comment]
It should work almost perfectly if you have added the units and foods in your database already. Of course it will be a bit more manual to fix at the start.
I got quite a few units and foods and 90% of my recipes get parsed automatically (in Dutch).

**Comment by boc-the-git** [comment]
I'll close this as it looks like the discussion has run its course? Feel free to comment here if an issue is discovered, and Discord is a good place to have discussion too.
