### ISSUE TITLE
[Task] - Fix common backup-restore issues instead of dumping data

### ISSUE THREAD

**Issue by michael-genson** [mealie-recipes/mealie#3219]
### What is the problem this task addresses?

Currently, when restoring a backup, any rows with invalid foreign keys are dropped (see https://github.com/mealie-recipes/mealie/pull/2986). This is a fair "catch-all" solution, but we can do better for more common issues (such as https://github.com/mealie-recipes/mealie/issues/3171)

### Proposed/Possible Solution(s)?

Scan the database JSON before attempting to import and fix some common issues. Specifically, looking at https://github.com/mealie-recipes/mealie/issues/3171, I can think of two:
1. If an invalid `user_id` is found, replace it with a valid one (find any admin user, similar to: #3213)
2. If an invalid `group_id` is found, replace it with a valid one (using an admin user, same as above)

This should fix the most egregious of errors (e.g. deleting recipes that belong to missing users)

Similarly, when users are deleted, their recipes should be re-assigned

**Comment by tba-code** [comment]
It would be kind of nice if there was a placeholder user and group that could be used for orphaned entries. like a group that you cant be added to, and a user that cant be logged in as that are just for placeholders in these situations.
