### ISSUE TITLE
[BUG] - Cannot register new user when using a recently added language 

### ISSUE THREAD

**Issue by gndControl** [mealie-recipes/mealie#3266]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When a recently (after May 6th 2022) added language is used for the UI, confirming the registration returns a status code 422 in the console. Further inspection of the request reveals that the locale is invalid.

### Steps to Reproduce

Select a recently added language for the UI. Go through the "register a new user" process and try to complete it.

### Please provide relevant logs

```json
{
  "detail": [
    {
      "type": "value_error",
      "loc": [
        "body",
        "locale"
      ],
      "msg": "Value error, invalid locale",
      "input": "sl-SI",
      "ctx": {
        "error": {}
      },
      "url": "https://errors.pydantic.dev/2.6/v/value_error"
    }
  ]
}
```

### Mealie Version

1.3.0 and presumably starting with v1.0.0-beta-1

### Deployment

Docker (Windows)

**Comment by hay-kot** [comment]
Fix in 

- https://github.com/mealie-recipes/mealie/pull/3278

with original work in #3267. Thanks for the bug report and the fix! ❤️
