### ISSUE TITLE
[BUG] - 'First day of the week' in group settings has no effect on date pickers

### ISSUE THREAD

**Issue by ghuser238490** [mealie-recipes/mealie#3292]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

As discussed in https://github.com/mealie-recipes/mealie/discussions/3287

Changing the value of 'First day of the week' in group settings has no effect on date pickers. In the calendar view the week always starts on sunday. Tested in different browsers and on the demo site with the default group and newly-created groups.
Maybe related to
https://github.com/mealie-recipes/mealie/issues/1860
https://github.com/mealie-recipes/mealie/pull/1864

![screenshot1](https://github.com/mealie-recipes/mealie/assets/80325288/52a2c609-496a-4b62-9ad1-ff8e6141561a)
![screenshot2](https://github.com/mealie-recipes/mealie/assets/80325288/eb2d977c-dad3-4193-a032-0c9b988ea73d)

### Steps to Reproduce

- Go to `https://my.server/admin/manage/groups`
- click on group in list
- change 'First day of the week' to anything other than Sunday
- open any date picker (e.g. on the meal planner page or use 'add to plan' on a recipe entry)
The first day of the week is always set to Sunday

### Please provide relevant logs

Nothing relevant in the logs.

### Mealie Version

Version
v1.3.2
Build
b54cdf642505bcb63384bddcc21f15d751c2f85b 

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Ahhh I see why I was confused about this. It actually does update exactly _one_ date picker - when editing the meal planner (`.../group/mealplan/planner/edit`).

Set to Tuesday for testing:
![image](https://github.com/mealie-recipes/mealie/assets/71845777/e605be74-17af-4ad5-9f71-40a4e4593284)

Every other date picker ignores the group setting

**Comment by ghuser238490** [comment]
>  It actually does update exactly _one_ date picker

Thanks, @michael-genson for sorting this out! 🎉

**Comment by leahoswald** [comment]
> Ahhh I see why I was confused about this. It actually does update exactly _one_ date picker - when editing the meal planner (`.../group/mealplan/planner/edit`).

Even there it's wrong for me with group setting to Monday.
![Screenshot2024-03-12_17-46-06](https://github.com/mealie-recipes/mealie/assets/1292551/93870d32-49e4-490b-ab73-088f13e1db32)
