### ISSUE TITLE
[BUG]  added a side, using the button. picked a recipe.  cannot delete it

### ISSUE THREAD

**Issue by sdetweil** [mealie-recipes/mealie#3293]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

open meal planner
add a recipe
add a side, click button

leave meal planner
come back into meal planner
delete side.   nothing happens
delete meal.  side remains 

### Steps to Reproduce

open meal planner
add a recipe
add a side, click button

leave meal planner
come back into meal planner
delete side.   nothing happens
delete meal.  side remains 

### Please provide relevant logs

don't have

### Mealie Version

lastest 3/09/24

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
I'm unable to reproduce this on the demo, are you able to share more detailed reproduction steps?
