### ISSUE TITLE
[SCRAPER] - import doesn't get ingredients or steps

### ISSUE THREAD

**Issue by sdetweil** [mealie-recipes/mealie#3304]
### First Check

- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have verified that this issue _is not_ related to the underlying library
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers) by **1)** checking
the [debugger](https://demo.mealie.io/g/home/r/create/debug) and data is returned, **2)**
verifying that there _are_ errors in the log related to application level code, or
**3)** verified that the site provides recipe data, or is otherwise supported by
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers)

- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### Please provide 1-5 example URLs that are having errors

https://recipecs.com/lemon-garlic-roasted-chicken/?fbclid=IwAR3PWLbmbctXfwxZX_U_Pnec2KYbVuxe-h_5EyowaVvVf4mrpcs6oCwrcX4

### Please provide your logs for the Mealie container `docker logs <container-id> > mealie.logs`

INFO: 12-Mar-24 07:35:40        HTTP Request: GET https://recipecs.com/lemon-garlic-roasted-chicken/?fbclid=IwAR3PWLbmbctXfwxZX_U_Pnec2KYbVuxe-h_5Eyo>
ERROR: 12-Mar-24 07:35:40       Recipe Scraper was unable to extract a recipe from https://recipecs.com/lemon-garlic-roasted-chicken/?fbclid=IwAR3PWL>
INFO: 12-Mar-24 07:35:41        HTTP Request: GET https://recipecs.com/lemon-garlic-roasted-chicken/?fbclid=IwAR3PWLbmbctXfwxZX_U_Pnec2KYbVuxe-h_5Eyo>
INFO: 12-Mar-24 07:35:44        Image URL: https://eyyfn4gkkuv.exactdn.com/wp-content/uploads/2021/12/244359557_1486819298371644_7138225809779015385_>
INFO: 12-Mar-24 07:35:44        HTTP Request: GET https://eyyfn4gkkuv.exactdn.com/wp-content/uploads/2021/12/244359557_1486819298371644_7138225809779>
INFO: 12-Mar-24 07:35:45        original.jpg minified
INFO: 12-Mar-24 07:35:45        Tiny image saved

### Deployment

Docker (Linux)

**Comment by Kuchenpirat** [comment]
Hey, does this only happen on recipecs.com? If yes this is not a mealie problem. 

This site is not officially supported by our underliying library [hhursev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers) and since [recipecs.com](https://recipecs.com) also does not use the recipe schema it is not possible to pic up the ingredients etc without support for exactly this website. 

You could open a request to support the page with them.

**Comment by sdetweil** [comment]
opened https://github.com/hhursev/recipe-scrapers/issues/1017

**Comment by Kuchenpirat** [comment]
Ok. I will close this and once support for recipecs.com is added and recipe-scrapers publishes a new version we will include it in mealie.
