### ISSUE TITLE
[BUG] - OIDC Environment Variables not being used

### ISSUE THREAD

**Issue by Wirrkopf76** [mealie-recipes/mealie#3309]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I'm trying to setup Authentik as an identity provider for my home lab and reading [this](https://docs.mealie.io/documentation/getting-started/installation/backend-config/) and [this](https://docs.mealie.io/documentation/getting-started/authentication/oidc/) should be possible to use with Mealie as well.

Unfortunately it seems as if Mealie ignores the OIDC_ environment variables I have in my docker compose file. Mealie just loads as if no OIDC_ stuff is specified

### Steps to Reproduce

1. Create a docker-compose file for Mealie using the OIDC_ environment variable
2. Set up Authentik as described in https://docs.mealie.io/documentation/getting-started/authentication/oidc/
3. Start Mealie

The OIDC environment variables don't show up in the app_settings part of the log file and Mealie does not use Open ID for authentication.

### Please provide relevant logs

``
        "light_error": "#EF5350",
        "dark_primary": "#E58325",
        "dark_accent": "#007A99",
        "dark_secondary": "#973542",
        "dark_success": "#43A047",
        "dark_info": "#1976D2",
        "dark_warning": "#FF6D00",
        "dark_error": "#EF5350"
    },
    "PRODUCTION": true,
    "BASE_URL": "https://mealie.domainname.net",
    "STATIC_FILES": "/spa/static",
    "IS_DEMO": false,
    "API_PORT": 9000,
    "API_DOCS": true,
    "TOKEN_TIME": 48,
    "LOG_LEVEL": "INFO",
    "GIT_COMMIT_HASH": "b54cdf642505bcb63384bddcc21f15d751c2f85b",
    "ALLOW_SIGNUP": true,
    "SECURITY_MAX_LOGIN_ATTEMPTS": 5,
    "SECURITY_USER_LOCKOUT_TIME": 24,
    "DB_ENGINE": "sqlite",
    "DEFAULT_GROUP": "Home",
    "SMTP_HOST": null,
    "SMTP_PORT": "587",
    "SMTP_FROM_NAME": "Mealie",
    "SMTP_FROM_EMAIL": null,
    "SMTP_AUTH_STRATEGY": "TLS",
    "LDAP_AUTH_ENABLED": false,
    "LDAP_SERVER_URL": null,
    "LDAP_TLS_INSECURE": false,
INFO:     Application startup complete.
    "LDAP_TLS_CACERTFILE": null,
    "LDAP_ENABLE_STARTTLS": false,
    "LDAP_BASE_DN": null,
    "LDAP_QUERY_BIND": null,
    "LDAP_QUERY_PASSWORD": null,
    "LDAP_USER_FILTER": null,
    "LDAP_ADMIN_FILTER": null,
    "LDAP_ID_ATTRIBUTE": "uid",
    "LDAP_MAIL_ATTRIBUTE": "mail",
    "LDAP_NAME_ATTRIBUTE": "name",
    "TESTING": false
}
INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
INFO:     127.0.0.1:33570 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:42340 - "GET /api/app/about HTTP/1.1" 200 OK
``

### Mealie Version

Mealie v1.3.2

### Deployment

Docker (Linux)

**Comment by Wirrkopf76** [comment]
I've just seen that there is a [PR](https://github.com/mealie-recipes/mealie/pull/3280) in regard to OIDC which is only 3 days old. Maybe the documentation I see on the website is newer than the version of Mealie I'm using. I will wait for the next Mealie version to hopefully include the use of those environment variables and feature the use of OpenID Connect :-)

I will close this issue for now.

**Comment by hay-kot** [comment]
I think we can do something to clarify this in the docs. I created a new issue

https://github.com/mealie-recipes/mealie/issues/3310.

Thanks for this!

**Comment by Flightkick** [comment]
@hay-kot haha, yeah that might have saved me quite some time. Thanks for the report @Wirrkopf76!
Looking forward to the new release! :)
