### ISSUE TITLE
Github Security Lab Vulnerability Report

### ISSUE THREAD

**Issue by maclarel** [mealie-recipes/mealie#3315]
Hi Mealie maintainers 👋 

I'm working with the GitHub Security Lab and we've identified several vulnerabilities in Mealie. We've shared these with the email specified in https://github.com/mealie-recipes/mealie/blob/mealie-next/SECURITY.md but have not heard back despite several attempts at contact.

We're reached the 90 day disclosure window outlined in our emails to you, but of course our preference is that these issues be addressed before they are disclosed.

Can you please confirm your receipt of those messages and get back to us if you're working on fixes for these issues?

Thank you!

**Comment by hay-kot** [comment]
Hello! Apologies for missing the emails. I was able to find them. Let me try to get a handle on these this weekend. If you wouldn't mind holding your disclosure until next week I would appreciate it. 

For anyone else looking at this, all of these vulnerabilities are only available to authenticated users. So if you've disabled registration, you're likely fine.

**Comment by maclarel** [comment]
Hi @hay-kot ,

>  Let me try to get a handle on these this weekend. If you wouldn't mind holding your disclosure until next week I would appreciate it.

No problem at all. Once you've been able to review these in more depth, if you could send us a note via email with estimates for when you think these can be addressed (or if further discussion is warranted) we're happy to align on a different disclosure date.

**Comment by maclarel** [comment]
Hi @hay-kot , checking in on this. Is there a new date that we could target for disclosure?

**Comment by boc-the-git** [comment]
https://github.com/mealie-recipes/mealie/pull/3368 merged last week.
