### ISSUE TITLE
[BUG] - Mealie is repeatedly calling /api/groups/self on home page when scrolling

### ISSUE THREAD

**Issue by cmintey** [mealie-recipes/mealie#3317]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

On the latest nightly build, scrolling through recipes is making dozens of calls to `/api/groups/self`. I believe this is related to the changes in #3303. 
I fired up a local dev instance and looking at the stack trace in the developer console on Firefox shows the calls emitting from `RecipeContextMenu.vue`. This call should probably be cached and re-used.

### Steps to Reproduce

1. Log in to Mealie on latest nightly build
2. Open developer console and go to Network tab
3. Scroll through your recipes
4. Observe the dozens of calls to `/api/groups/self`. One for each recipe card that gets rendered

### Please provide relevant logs

```
mealie     | INFO:     10.0.2.1:0 - "GET /api/recipes?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1710473439668&searchSeed=1710473439668&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
mealie     | INFO:     10.0.2.1:0 - "GET /api/groups/self HTTP/1.1" 200 OK
mealie     | INFO:     10.0.2.1:0 - "GET /api/groups/self HTTP/1.1" 200 OK
mealie     | INFO:     10.0.2.1:0 - "GET /api/groups/self HTTP/1.1" 200 OK
mealie     | INFO:     10.0.2.1:0 - "GET /api/groups/self HTTP/1.1" 200 OK
mealie     | INFO:     10.0.2.1:0 - "GET /api/groups/self HTTP/1.1" 200 OK
mealie     | INFO:     10.0.2.1:0 - "GET /api/groups/self HTTP/1.1" 200 OK
mealie     | INFO:     10.0.2.1:0 - "GET /api/groups/self HTTP/1.1" 200 OK
mealie     | INFO:     10.0.2.1:0 - "GET /api/groups/self HTTP/1.1" 200 OK
mealie     | INFO:     10.0.2.1:0 - "GET /api/groups/self HTTP/1.1" 200 OK
mealie     | INFO:     10.0.2.1:0 - "GET /api/groups/self HTTP/1.1" 200 OK
mealie     | INFO:     10.0.2.1:0 - "GET /api/groups/self HTTP/1.1" 200 OK
mealie     | INFO:     10.0.2.1:0 - "GET /api/groups/self HTTP/1.1" 200 OK
...
```

### Mealie Version

Nightly
Build: 1af0f426ae7ed19668059929cbe18d4b479f5d75

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Maybe the group is insecure and has to look at itself constantly to feel validated
