### ISSUE TITLE
[BUG] - 1/3rd not recognized as quantity by parser

### ISSUE THREAD

**Issue by JvdMaat** [mealie-recipes/mealie#3318]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Then trying to parse ingredients that contain 1/3rd of something (eg 1/3 cup), the parser lists 0 as quantity

### Steps to Reproduce

From demo site, import recipe from URL: https://www.wellplated.com/slow-cooker-honey-garlic-chicken/#wprm-recipe-container-37253
Save, disable the Disable ingredient amounts, and then parse it.
Both 2nd and 3rd (soy sauce and honey) fail to get a proper quantity
I left https://demo.mealie.io/g/home/r/slow-cooker-honey-garlic-chicken unparsed for ease of reference. (just don't save and can be re-used)

### Please provide relevant logs

![image](https://github.com/mealie-recipes/mealie/assets/90044149/6ecd6009-4945-43db-8638-a5f47c3aa048)

### Mealie Version

1.3.2 & nightly (issue occurs on demo.mealie.io)

### Deployment

Docker (Linux)

**Comment by JvdMaat** [comment]
Just a quick addition. Only fails in NLP (Natural Language Parser). Brute parser catches the 1/3rd no problem.

**Comment by cmintey** [comment]
Can confirm I noticed this as well when importing a recipe the other day

**Comment by camillerimichael** [comment]
Can I add that cup is recognised but not cups. It seems plurals are a blind spot.

**Comment by michael-genson** [comment]
> Can I add that cup is recognised but not cups. It seems plurals are a blind spot.

Have you added plurals to your units? The parser looks at those which usually solves that problem

**Comment by camillerimichael** [comment]
The recipe had plurals to being with. I'll play around more with the parser, I only used the first one.

**Comment by hay-kot** [comment]
FYI, I'm doing work for [Recipinned](https://recipinned.com) in this repo that greatly improved the parsing, but it uses a totally different model/strategy

https://github.com/hay-kot/recipes-api

It would be a pretty big lift to get it integrated into Mealie, but it's totally possible if someone wants to tackle it.

**Comment by JvdMaat** [comment]
Still an issue.

**Comment by GrundleJuice** [comment]
Still an issue.  Does the Open AI parser handle fractions/non integer quantities?
