### ISSUE TITLE
Mealie Web UI is down

### ISSUE THREAD

**Issue by mathgoy** [mealie-recipes/mealie#3327]
Hi guys,

I am running mealie in a docker container in Unraid.

I didnt change anything in my configuration but I can't access my Mealie webUI anymore. It says the site can't be reached.

My log shows the following:

```
INFO: 17-Mar-24 10:51:28        Database connection established.
INFO: 17-Mar-24 10:51:28        Context impl SQLiteImpl.
INFO: 17-Mar-24 10:51:28        Will assume non-transactional DDL.
INFO: 17-Mar-24 10:51:28        Checking for migration data fixes
WARNING: 17-Mar-24 10:51:28     "get_all" method is deprecated; use "page_all" instead
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO: 17-Mar-24 10:51:33        -----SYSTEM STARTUP----- 

INFO: 17-Mar-24 10:51:33        ------APP SETTINGS------
INFO: 17-Mar-24 10:51:33        {
    "theme": {
        "light_primary": "#E58325",
        "light_accent": "#007A99",
        "light_secondary": "#973542",
        "light_success": "#43A047",
        "light_info": "#1976D2",
        "light_warning": "#FF6D00",
        "light_error": "#EF5350",
        "dark_primary": "#E58325",
        "dark_accent": "#007A99",
        "dark_secondary": "#973542",
        "dark_success": "#43A047",
        "dark_info": "#1976D2",INFO:     Application startup complete.

        "dark_warning": "#FF6D00",
        "dark_error": "#EF5350"
    },
    "PRODUCTION": true,
    "BASE_URL": "http://localhost:8080",
    "STATIC_FILES": "/spa/static",
    "IS_DEMO": false,
    "API_PORT": 9000,
    "API_DOCS": true,
    "TOKEN_TIME": 48,
    "LOG_LEVEL": "INFO",
    "GIT_COMMIT_HASH": "b54cdf642505bcb63384bddcc21f15d751c2f85b",
    "ALLOW_SIGNUP": true,
    "SECURITY_MAX_LOGIN_ATTEMPTS": 5,
    "SECURITY_USER_LOCKOUT_TIME": 24,
    "DB_ENGINE": "sqlite",
    "DEFAULT_GROUP": "Home",
    "SMTP_HOST": null,
    "SMTP_PORT": "587",
    "SMTP_FROM_NAME": "Mealie",
    "SMTP_FROM_EMAIL": null,
    "SMTP_AUTH_STRATEGY": "TLS",
    "LDAP_AUTH_ENABLED": false,
    "LDAP_SERVER_URL": null,
    "LDAP_TLS_INSECURE": false,
    "LDAP_TLS_CACERTFILE": null,
    "LDAP_ENABLE_STARTTLS": false,
    "LDAP_BASE_DN": null,
    "LDAP_QUERY_BIND": null,
    "LDAP_QUERY_PASSWORD": null,
    "LDAP_USER_FILTER": null,
    "LDAP_ADMIN_FILTER": null,
    "LDAP_ID_ATTRIBUTE": "uid",
    "LDAP_MAIL_ATTRIBUTE": "mail",
    "LDAP_NAME_ATTRIBUTE": "name",
    "TESTING": false
}
INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
INFO:     127.0.0.1:46372 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:40348 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:45862 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:47282 - "GET /api/app/about HTTP/1.1" 200 OK
```

Note that it will show a new info line every minute or so.

ANy idea what my problem is?

Thanks

**Comment by ovizii** [comment]
Did you try restarting the container?

**Comment by mathgoy** [comment]
> Did you try restarting the container?

Yep I did. 
Several time

**Comment by awfullyterrible** [comment]
Hi all, same issue here. Tried many restarts, repulls and container rebuilds. Here's the logs, same as yours:
`Switching to dedicated user
        User uid:    1000
        User gid:    1000
        
INFO: 19-Mar-24 10:24:32 	Database connection established.
INFO: 19-Mar-24 10:24:32 	Context impl SQLiteImpl.
INFO: 19-Mar-24 10:24:32 	Will assume non-transactional DDL.
INFO: 19-Mar-24 10:24:33 	Checking for migration data fixes
WARNING: 19-Mar-24 10:24:33 	"get_all" method is deprecated; use "page_all" instead
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO: 19-Mar-24 10:24:56 	-----SYSTEM STARTUP----- 
INFO: 19-Mar-24 10:24:56 	------APP SETTINGS------
INFO: 19-Mar-24 10:24:56 	{
    "theme": {
        "light_primary": "#E58325",
        "light_accent": "#007A99",
        "light_secondary": "#973542",
        "light_success": "#43A047",
        "light_info": "#1976D2",
        "light_warning": "#FF6D00",
        "light_error": "#EF5350",
        "dark_primary": "#E58325",
        "dark_accent": "#007A99",
        "dark_secondary": "#973542",
        "dark_success": "#43A047",
        "dark_info": "#1976D2",
        "dark_warning": "#FF6D00",
        "dark_error": "#EF5350"
    },
    "PRODUCTION": true,
    "BASE_URL": "http://localhost:8080",
    "STATIC_FILES": "/spa/static",
    "IS_DEMO": false,
    "API_PORT": 9000,
    "API_DOCS": true,
    "TOKEN_TIME": 48,
    "LOG_LEVEL": "INFO",
    "GIT_COMMIT_HASH": "b54cdf642505bcb63384bddcc21f15d751c2f85b",
    "ALLOW_SIGNUP": true,
    "SECURITY_MAX_LOGIN_ATTEMPTS": 5,
    "SECURITY_USER_LOCKOUT_TIME": 24,
    "DB_ENGINE": "sqlite",
    "DEFAULT_GROUP": "Home",
    "SMTP_HOST": null,
    "SMTP_PORT": "587",
    "SMTP_FROM_NAME": "Mealie",
    "SMTP_FROM_EMAIL": null,
    "SMTP_AUTH_STRATEGY": "TLS",
    "LDAP_AUTH_ENABLED": false,
INFO:     Application startup complete.
    "LDAP_SERVER_URL": null,
    "LDAP_TLS_INSECURE": false,
    "LDAP_TLS_CACERTFILE": null,
    "LDAP_ENABLE_STARTTLS": false,
    "LDAP_BASE_DN": null,
    "LDAP_QUERY_BIND": null,
    "LDAP_QUERY_PASSWORD": null,
    "LDAP_USER_FILTER": null,
    "LDAP_ADMIN_FILTER": null,
    "LDAP_ID_ATTRIBUTE": "uid",
    "LDAP_MAIL_ATTRIBUTE": "mail",
    "LDAP_NAME_ATTRIBUTE": "name",
    "TESTING": false
}
INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
INFO:     127.0.0.1:57400 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:46414 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:44862 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:42900 - "GET /api/app/about HTTP/1.1" 200 OK`

**Comment by boc-the-git** [comment]
Please re-raise your issue using the [correct issue template](https://github.com/mealie-recipes/mealie/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=bug-report.yaml&title=%5BBUG%5D+-+YOUR+DESCRIPTIVE+TITLE+GOES+HERE) and fill in all the fields. Help us to help you.

Include your docker-compose file, redacting only sensitive info.
Include information about your reverse proxy.
