### ISSUE TITLE
[BUG] -  Seeing: ERROR:  operator does not exist in postgresql logs

### ISSUE THREAD

**Issue by ovizii** [mealie-recipes/mealie#3329]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

mealie felt a bit slow today, so I checked the logs and found this in my PostgreSQL logs. Totally unrelated to the slowness but I thought I'd report it here. 

Everything seems to be working fine though.

### Steps to Reproduce

Absolutely no idea how to reproduce.

### Please provide relevant logs

```
2024-03-17 09:09:39.076 UTC [96] ERROR:  operator does not exist: character varying <= timestamp without time zone at character 311                     │
│   2024-03-17 09:09:39.076 UTC [96] HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.               │
│   2024-03-17 09:09:39.076 UTC [96] STATEMENT:  SELECT group_data_exports.id, group_data_exports.group_id, group_data_exports.name, group_data_exports.f   │
│   ilename, group_data_exports.path, group_data_exports.size, group_data_exports.expires, group_data_exports.created_at, group_data_exports.update_at      │
│   FROM group_data_exports                                                                                                                                 │
│   WHERE group_data_exports.expires <= '2024-03-16T10:09:39.074433'::timestamp                                                                            
```

### Mealie Version

image: ghcr.io/mealie-recipes/mealie:v1.3.2

Build
[b54cdf642505bcb63384bddcc21f15d751c2f85b](https://github.com/mealie-recipes/mealie/commit/b54cdf642505bcb63384bddcc21f15d751c2f85b)

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Thanks for the report, but this should be fixed in nightly: https://github.com/mealie-recipes/mealie/pull/3314
