### ISSUE TITLE
[BUG] Too many requests to /api/foods, /api/units slow the page down

### ISSUE THREAD

**Issue by mechanarchy** [mealie-recipes/mealie#3335]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

It looks like many duplicated requests to `/api/foods` and `/api/units` are made from the front end (when ingredient data is loaded) when you click into the recipe edit button on a recipe page. The first couple respond effectively instantly; the rest take 60 seconds/1 minute to either respond with `200 OK` or `500 Internal Server Error`.

However, any other actions (that need the server) on the page are blocked until these replies are received.

### Steps to Reproduce

1. Go to the demo site
2. Make sure food and unit information is already populated
3. Go to a recipe page. eg at time of writing, https://demo.mealie.io/g/home/r/cheesy-beef-creamy-pesto-burger-with-sweet-potato-fries-caramelised-onions
4. F12 to open developer tools and go to the network tab, then Ctrl+F5 to ensure your cache is clean
5. Click the Edit button
6. Observe many many requests. Here is what it looks like on my end, filtered to XHR only:
![image](https://github.com/mealie-recipes/mealie/assets/1166756/6cb8a369-25d8-4565-8085-498778bb3b95)

### Please provide relevant logs

There aren't any relevant logs on my own install, and I don't have access to the logs from the demo site.

### Mealie Version
Self-hosted: v1.3.2 / b54cdf642505bcb63384bddcc21f15d751c2f85b 
Demo site: nightly / e84e5e2910d128911c0c2050a60dfdc205fe277a

### Deployment

Docker (Linux)

### Additional Deployment Details

I thought it may have been my reverse proxy (Caddy), but since it's appearing on the demo site too it's unlikely this is a misconfiguration on my side. Browser Firefox 115.0.2 (64-bit) on Ubuntu.

**Comment by mechanarchy** [comment]
It looks like there's one pair of `/api/units` + `/api/foods` calls made per ingredient in the recipe editor. In the case of the recipe in the steps to reproduce, there's 13 ingredients so a total of 26 API calls. 

Oh. Looks like this might be fixed by #3306.

**Comment by michael-genson** [comment]
> It looks like there's one pair of /api/units + /api/foods calls made per ingredient in the recipe editor

Yup, that's exactly what's going on. But yes, https://github.com/mealie-recipes/mealie/pull/3306 fixed it.

FYI there's a [similar bug](https://github.com/mealie-recipes/mealie/issues/3317) (currently only in nightly) on the home page with `/group/self` and there is an open PR to fix that: https://github.com/mealie-recipes/mealie/pull/3321

**Comment by mechanarchy** [comment]
Thanks. I'll close this issue given it's fixed in master, (presumably) pending next release.
