### ISSUE TITLE
[BUG] - Query text typed in the tag field is not deleted after matching tag is clicked

### ISSUE THREAD

**Issue by simgunz** [mealie-recipes/mealie#3359]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I edit a recipe and type text in the tag field to search for a tag. A list of matches appear and I click on one tag (can also be a the tag that fully match my query). The tag is added but the query text is not deleted and I have to delete it manually.

I expect that after making a selection from the tag list that match the query, the query text is deleted from the input field.

### Steps to Reproduce

1. Edit recipe
2. Type text in the tag field to search for a tag (partial match or full match is the same)
3. Click on the matched tag
4. Tag is added but the query text is still on the field and I have to delete it manually

### Please provide relevant logs

Not relevant

### Mealie Version

v1.3.2
b54cdf642505bcb63384bddcc21f15d751c2f85b  

### Deployment

Docker (Linux)

EDIT: Updated affected version to 1.3.2

EDIT2: This applies to tools and categories field as well

**Comment by Kuchenpirat** [comment]
I just opened a PR that should address this issue. Thanks for bringing this to our attention 👍
