### ISSUE TITLE
[BUG] - v1.3.2 "Keep Screen Awake"-Button missing

### ISSUE THREAD

**Issue by Klausberger** [mealie-recipes/mealie#3367]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

After installing the latest Version of Mealie, no "Keep Screen Awake" Button is visible on any recipe screen:
![image](https://github.com/mealie-recipes/mealie/assets/42064202/b2451680-f30d-4246-bf45-f698b25cb30e)

Deployment:
Latest Docker Container:
![image](https://github.com/mealie-recipes/mealie/assets/42064202/ad93b648-1e81-407b-9072-8a8c0b22e849)

This is reproducible on different devices and browsers, tested on:

Safari iPhone - IOS 16.6.1
Chrome  - Windows 10 (122.0.6261.131)
Fire Tablet 8 Chromium

### Steps to Reproduce

- Clean install of Docker container
- Import Recipie from https://www.chefkoch.de/rezepte/644981165672475/Das-beste-Kartoffelgratin.html?portionen=2
- "Keep Screen Awake" missing at bottom of page

### Please provide relevant logs

No errors in docker compose.

### Mealie Version

v1.3.2

### Deployment

Docker (Linux)

**Comment by Kuchenpirat** [comment]
I could not find a way to reproduce the "Keep Screen awake" not showing up on a device it showed up on before. 

The option will only show up if the browser does allow us to set it up, but seing that you have used multiple devices and browsers it seems unlikely it does not work for all of them. 

Can you say if it worked on earlier version with the same devices?
Can you check if the option is availlable on the demo: [demo.mealie.io](demo.mealie.io)

**Comment by g1bs0nsg** [comment]
I'm having this issue as well, I'm a new user, so just installed a few days ago... but I noticed the the switch is there on demo.mealie.io, but I do not see it on any recipe in my locally hosted instance.

**Comment by Yohanzon** [comment]
It only works over https, not http

**Comment by Klausberger** [comment]
> It only works over https, not http

I tested this, and I can replicate it. Using http there is no button.
