### ISSUE TITLE
[BUG] - Mealie Scraping From Another Mealie Instance Always Grabs Latest Recipe

### ISSUE THREAD

**Issue by sim2kid** [mealie-recipes/mealie#3374]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I am trying to grab exactly one recipe from another mealie instance. To do so, I grabbed the URL from that mealie instance and put it into the scraper of a second mealie instance.
I checked the Scrapper's debugging, and a recipe was returned. I checked the logs, and the only error I received was a failure to load an image.
However, no matter what I try, the same recipe is returned.

Note: On the starting mealie server (where im grabbing the recipe from), I see two GET requests in the log. The first is for the recipe I supplied. The second is then for the media image for the latest recipe (different recipe).

Note 2: It seams if I type in the recipe returned into the search bar of the mealie instance i scraped, every recipe is returned.

### Steps to Reproduce

1. Have two mealie instances. You can use the Demo server as one of them.
2. Use any recipe that is not the most recent. Create two new recipes if needed to test.
3. Copy the link to that recipe. Ensure the recipe is public.
4. On the second mealie instance, Import by link (Create > Link)
5. Past the recipe from the source instance.
6. Scrape it.
7. Note that this is always the same recipe no matter which link you try.

### Please provide relevant logs

On the Destination Mealie Server
```
INFO: 25-Mar-24 09:44:50 	HTTP Request: GET https://other.mealie.example/g/home/r/kfc-original-recipe-chicken "HTTP/1.1 200 OK"
INFO: 25-Mar-24 09:44:50 	Image URL: ['https://other.mealie.example/api/media/recipes/ebd866cc-2933-4286-b49e-bbdbaaab668a/images/original.webp?version=iCPR']
INFO: 25-Mar-24 09:44:50 	HTTP Request: HEAD https://other.mealie.example/api/media/recipes/ebd866cc-2933-4286-b49e-bbdbaaab668a/images/original.webp?version=iCPR "HTTP/1.1 200 OK"
ERROR: 25-Mar-24 09:44:50 	Fatal Image Request Exception
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions

d
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 215, in handle_async_request
    raise UnsupportedProtocol(
httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/mealie/services/recipe/recipe_data_service.py", line 149, in scrape_image
    r = await client.get(image_url, headers={"User-Agent": _FIREFOX_UA})
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1801, in get
    return await self.request(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
INFO:     192.168.50.22:33230 - "POST /api/recipes/create-url HTTP/1.1" 201 Created
INFO:     192.168.50.22:33230 - "GET /api/recipes/egg-drop-soup HTTP/1.1" 200 OK
INFO:     192.168.50.22:33256 - "GET /api/media/recipes/b5ad2373-7fac-4616-a4c8-0960e0fd8124/images/original.webp?rnd=1&version=SdzK HTTP/1.1" 404 Not Found
INFO:     192.168.50.22:33230 - "GET /api/recipes/egg-drop-soup/comments HTTP/1.1" 200 OK
INFO:     192.168.50.22:33242 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
```

On the Source Mealie Server:
```
INFO:     192.168.50.22:45232 - "GET /g/home/r/loaded-baked-potato-soup HTTP/1.1" 200 OK
INFO:     192.168.50.22:45232 - "GET /api/media/recipes/ebd866cc-2933-4286-b49e-bbdbaaab668a/images/original.webp?version=iCPR HTTP/1.1" 200 OK  <-- (Egg Drop Soup Image)
```

### Mealie Version

Source Server:
Nightly branch
Build: [54aef24cafcffc4f867954525e34bcd842ddbd5c](https://github.com/mealie-recipes/mealie/commit/54aef24cafcffc4f867954525e34bcd842ddbd5c)
Recipe Scraper: [14.55.0](https://github.com/hhursev/recipe-scrapers/releases/tag/14.55.0)

Destination Server:
Nightly branch
Build: [b54cdf642505bcb63384bddcc21f15d751c2f85b](https://github.com/mealie-recipes/mealie/commit/b54cdf642505bcb63384bddcc21f15d751c2f85b)
Recipe Scraper: [14.55.0](https://github.com/hhursev/recipe-scrapers/releases/tag/14.55.0)

### Deployment

Docker (Linux)

### Additional Deployment Details

Both servers are deployed the same way (in docker with a bind to the host container). The containers are behind a traefik reverse proxy.

**Comment by boc-the-git** [comment]
It's not definitively the most recently created recipe (as I created one that wasn't what got returned), but I agree that it's returning something other than what you'd expect..

```
INFO: 09-Apr-24 20:45:54 	HTTP Request: GET https://demo.mealie.io/g/home/r/gluten-free-doughnuts-krispy-kreme-copycat "HTTP/1.1 200 OK"
INFO: 09-Apr-24 20:45:54 	Image URL: ['https://demo.mealie.io/api/media/recipes/1bb10cca-315e-4ef3-a359-2564ce939d16/images/original.webp?version=164']
INFO: 09-Apr-24 20:45:55 	HTTP Request: HEAD https://demo.mealie.io/api/media/recipes/1bb10cca-315e-4ef3-a359-2564ce939d16/images/original.webp?version=164 "HTTP/1.1 200 OK"
INFO: 09-Apr-24 20:45:55 	HTTP Request: GET https://demo.mealie.io/api/media/recipes/1bb10cca-315e-4ef3-a359-2564ce939d16/images/original.webp?version=164 "HTTP/1.1 404 Not Found"
INFO:     redactedIP1:0 - "POST /api/recipes/create-url HTTP/1.1" 201 Created
INFO: 09-Apr-24 20:45:56 	Sent MQTT notification
INFO:     redactedIP2:0 - "POST /api/auth/token HTTP/1.1" 200 OK
INFO:     redactedIP1:0 - "GET /api/recipes/issue-3434 HTTP/1.1" 200 OK
```

Cloning a doughnut recipe from the demo server is ending up as `issue-3434` in my local instance

A pure guesstimate with no evidence to support it.. this could possibly relate to public vs private recipes/groups, or something like that..

**Comment by michael-genson** [comment]
I would bet $50 it's related to this: https://github.com/mealie-recipes/mealie/pull/2770
