### ISSUE TITLE
how do i select the recipes shown when not logged in

### ISSUE THREAD

**Issue by sdetweil** [mealie-recipes/mealie#3385]
my userid is the default group
my sisters are in their own groups

when they are logged out, they can see sll my recipes, not theirs.

**Comment by Kuchenpirat** [comment]
Please use the provided templates when creating an issue. 

Logged out, if the user does access the instance directly and not a subpage, you get redirected to the default group.
They would have to navigate to the subpage `/g/<their_group_slug>`

**Comment by sdetweil** [comment]
none of the templates applied  do i used the link to empty
