### ISSUE TITLE
[BUG] - Access groups without logging in

### ISSUE THREAD

**Issue by Wolve1** [mealie-recipes/mealie#3388]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

One of my groups is called "Home". When I open Mealie without being logged in, I am not getting redirected to the login page, but to "mymealieip:9000/g/home?orderBy=created_at" and I can see and access all recipes.

By changing the group name to something else, I get redirected to the login page, just as expected.

Connected error:
If several groups are available and I happen to know those group names, I am able to access them by entering the name in the URL, e.g.:
Group is called "mommy"
visit "mymealieip:9000/g/mommy?orderBy=created_a" without being logged in
than I can see and access all recipes of that group

Expected behaviour would be to either get redirected to the login page if not logged in or to get redirected to a restricted page

### Steps to Reproduce

1) rename one group to "Home"
2) log out
3) visit "mealieip:9000"

Connected error:
1) visit "mealieip:9000" --> you get redirected to mealieip:9000/g/home?orderBy=created_a
2) change the URL to another available group name like: mymealieip:9000/g/mommy?orderBy=created_a

### Please provide relevant logs

not available 

### Mealie Version

Version: v1.3.2
Build: b54cdf642505bcb63384bddcc21f15d751c2f85b

### Deployment

Other (please specify below)

### Additional Deployment Details

Docker (QNAP) via Docker Compose file

**Comment by Kuchenpirat** [comment]
This would happen because your groups are set to public.

If the default group is public, a user that is not logged in will get redirected to the explore page of the default group.
You can change that in the group settings.
