### ISSUE TITLE
[BUG] - Docker infinite loading script tags returning html

### ISSUE THREAD

**Issue by odama626** [mealie-recipes/mealie#3398]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

when not logged in script tags return html and cause an error that the page doesn't recover from, causing infinite loading

### Steps to Reproduce

logout -> reload page

### Please provide relevant logs

```The script from “https://mealie.lilbyte.dev/_nuxt/239cd4e.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
[mealie.lilbyte.dev](https://mealie.lilbyte.dev/)
The script from “https://mealie.lilbyte.dev/_nuxt/9a1b582.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
[mealie.lilbyte.dev](https://mealie.lilbyte.dev/)
Uncaught SyntaxError: expected expression, got '<'
[239cd4e.js:1:1](https://mealie.lilbyte.dev/_nuxt/239cd4e.js)
Uncaught SyntaxError: expected expression, got '<'
[9a1b582.js:1:1](https://mealie.lilbyte.dev/_nuxt/9a1b582.js)

​```

### Mealie Version

1.3.2

### Deployment

Docker (Linux)

### Additional Deployment Details

```version: '3'

networks:
  traefik_net:
    external: true

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.3.2
    restart: unless-stopped
    networks:
      traefik_net:
    volumes:
      - /data/mealie:/app/data
    environment:
      - ALLOW_SIGNUP=false
      - PUID=1000
      - PGID=1000
      - TZ=America/Anchorage
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.mealie.entrypoints=websecure"

      - "traefik.http.services.mealie.loadbalancer.server.port=9000"
      - "traefik.http.routers.mealie.tls.certresolver=mytlschallenge"```

**Comment by tba-code** [comment]
I am unable to replicate the bug with a fresh container.

Here are some things you could try:
1) Testing with an incognito/private browser window
2) Trying a separate browser

Also, I suspect you omitted two traefik tags there:
```yml
 traefik.http.routers.mealie.rule: Host(`mealie.lilbyte.dev`)
 traefik.http.routers.mealie.service: mealie
 ```
 
 If the issue still persists, could your try replicating this in a fresh container or adding relevant docker compose logs?

**Comment by odama626** [comment]
I had deleted that line from the config,  I did start this container on a previous version v1.0 I believe.  It worked on the devices I had logged into before upgrading, then I logged out of one of them and ran into the issue.. On my phone I'm still logged on so it works, but using incognito on my phone hits the error

**Comment by tba-code** [comment]
> I had deleted that line from the config, I did start this container on a previous version v1.0 I believe. It worked on the devices I had logged into before upgrading, then I logged out of one of them and ran into the issue.. On my phone I'm still logged on so it works, but using incognito on my phone hits the error

We need more information to help you. Please provide your docker compose logs from Mealie. What was the last known good version?

**Comment by odama626** [comment]
looks like I went from v1.1.0 to latest
```
ghcr.io/mealie-recipes/mealie                          latest                       038b8cd29c1a   3 weeks ago     410MB
ghcr.io/mealie-recipes/mealie                          v1.1.0                       ebcaab3ee436   2 months ago    410MB
```

the logs don't seem to have any strange output

[mealie_mealie_logs.txt](https://github.com/mealie-recipes/mealie/files/14826222/mealie_mealie_logs.txt)

I'm not sure what it is, I originally thought it was a service worker issue, but removing that in the browser didn't resolve the problem either

do you have the same issue if you navigate to it?

https://mealie.lilbyte.dev/

**Comment by tba-code** [comment]
Yes, I have the same issue. Can you try force recreating the container?

**Comment by odama626** [comment]
I have removed and redeployed the stack a couple times -- I think that is equivalent to what you were asking?

I just ran these commands on the server, (commands on $ lines)

```
$ docker stack rm mealie
Removing service mealie_mealie
$ docker stack deploy -c mealie.yml mealie
Ignoring unsupported options: restart

Since --detach=false was not specified, tasks will be created in the background.
In a future release, --detach=false will become the default.
Creating service mealie_mealie
```

the issue still persists, would a sqlite dump help?

**Comment by tba-code** [comment]
Try rolling back to v1.1.0 first, and if that works, move up to 1.2.0. It would help to narrow down the version where this is occurring a bit more.

**Comment by odama626** [comment]
I went back to v1.1.0 and it worked.  moved to 1.2.0 and it stopped working again... but then I went to 1.3.0 and it works on all 3 versions now?

I guess jumping from 1.1 to 1.3 without running 1.2 in between broke something?

when I went back to 1.3.2 I briefly saw the issue again?

but then I went from 1.3.0 -> 1.3.1 -> 1.3.2 and it resolved the issue again.

My wife's device is logged out and tried it again after I had finished changing versions and it is still broken for her.  I think it has to be something to do with the service worker.

I rolled it back to 1.1.0 and she had to wipe her browser storage for it to start working again.


without thinking I had my web inspector open with disable cache checked... could be why I didn't have problems with the service worker when I tried

**Comment by odama626** [comment]
I started having issues again on 1.3.2 so ultimately rolled back to 1.1.. think it just took time for the service worker to update to start causing problems again?

**Comment by odama626** [comment]
it has been working for several days on v 1.2.0 as well

**Comment by tba-code** [comment]
Hey, sorry for the late reply here. Could you try the current nightly? I'm wondering if it will fix your issue.
