### ISSUE TITLE
[BUG] - OAuth Infinite redirects

### ISSUE THREAD

**Issue by Aurel004** [mealie-recipes/mealie#3399]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Hi,

I've seen a "bug" on mealie using OAuth (via Authentik). When OIDC_AUTO_REDIRECT is set to true and the login is invalid, I am redirected back to mealie login page but as OIDC_AUTO_REDIRECT is selected it tries again to connect and again and again.

I've seen that it is a login issue on logs, "username or password incorrect" (I might have a look on why it is incorrect). I think if the login is incorrect, it might disable temporaly auto redirect.

### Steps to Reproduce

1) Enable OIDC with OIDC_SIGNUP_ENABLED set to true
2) Try to login with an non-existant login in mealie (with OIDC_SIGNUP_ENABLED set to false)

### Please provide relevant logs

mealie  | ERROR: 31-Mar-24 23:01:13     Incorrect username or password from xx
mealie  | ERROR: 31-Mar-24 23:01:14     Incorrect username or password from xx
mealie  | INFO:     172.20.0.2:38972 - "POST /api/auth/token HTTP/1.1" 401 Unauthorized
mealie  | INFO:     172.20.0.2:38972 - "GET /api/app/about HTTP/1.1" 200 OK
mealie  | INFO:     172.20.0.2:38972 - "GET /api/app/about HTTP/1.1" 200 OK
mealie  | INFO:     172.20.0.2:38972 - "GET /sw.js HTTP/1.1" 304 Not Modified
mealie  | INFO:     127.0.0.1:51656 - "GET /api/app/about HTTP/1.1" 200 OK
mealie  | ERROR: 31-Mar-24 23:02:04     Incorrect username or password from xx
mealie  | INFO:     172.20.0.2:39216 - "POST /api/auth/token HTTP/1.1" 401 Unauthorized
mealie  | INFO:     172.20.0.2:39216 - "GET /api/app/about HTTP/1.1" 200 OK
mealie  | INFO:     172.20.0.2:39216 - "GET /api/app/about HTTP/1.1" 200 OK

### Mealie Version

nightly

### Deployment

Docker (Linux)

**Comment by Aurel004** [comment]
Plus, it seems like it "unadmin"ed me (once logged with correct credidentials). I can't check the server settings as if I was a normal user. How can I get it back ?

Thank you

**Comment by cmintey** [comment]
> Plus, it seems like it "unadmin"ed me (once logged with correct credidentials). I can't check the server settings as if I was a normal user. How can I get it back ?
> 
> 
> 
> Thank you

If you want to be an admin, you'll need to set an environment variable which is explained [here](https://docs.mealie.io/documentation/getting-started/authentication/oidc/#groups)

**Comment by Aurel004** [comment]
> > Plus, it seems like it "unadmin"ed me (once logged with correct credidentials). I can't check the server settings as if I was a normal user. How can I get it back ?
> > Thank you
> 
> If you want to be an admin, you'll need to set an environment variable which is explained [here](https://docs.mealie.io/documentation/getting-started/authentication/oidc/#groups)

Thanks
