### ISSUE TITLE
[SCRAPER] - holisticfoodie

### ISSUE THREAD

**Issue by Symbiot78** [mealie-recipes/mealie#3403]
### First Check

- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have verified that this issue _is not_ related to the underlying library [hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers) by **1)** checking
the [debugger](https://demo.mealie.io/g/home/r/create/debug) and data is returned, **2)**
verifying that there _are_ errors in the log related to application level code, or
**3)** verified that the site provides recipe data, or is otherwise supported by
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers)
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### Please provide 1-5 example URLs that are having errors

https://www.holisticfoodie.com/recipes/air-fryer-kfc-chicken#recipe-card
https://www.holisticfoodie.com/recipes/air-fryer-kfc-chicken

### Please provide your logs for the Mealie container `docker logs <container-id> > mealie.logs`

it just says 'could not detect instructions' and 'could not detect ingredients'.

```
O:     192.168.1.243:51573 - "GET /api/recipes?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1711976376561&searchSeed=1711976376561&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
INFO:     192.168.1.243:51573 - "GET /api/media/recipes/02a9eeb4-e5f3-42dd-b160-01bd39c76426/images/min-original.webp?rnd=1&version=XXtQ HTTP/1.1" 200 OK
INFO:     192.168.1.243:51574 - "GET /api/media/recipes/0f7bbbf7-ce98-4ccf-929b-2a42c9c49821/images/min-original.webp?rnd=1&version=tUz7 HTTP/1.1" 200 OK
INFO:     192.168.1.243:51571 - "GET /api/recipes?page=3&perPage=32&orderBy=created_at&orderDirection=desc&paginationSeed=1711976376561&searchSeed=1711976376561&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
INFO: 01-Apr-24 14:59:43 	HTTP Request: GET https://www.holisticfoodie.com/recipes/air-fryer-kfc-chicken#recipe-card "HTTP/1.1 200 OK"
INFO: 01-Apr-24 14:59:43 	HTTP Request: GET https://www.holisticfoodie.com/recipes/air-fryer-kfc-chicken#recipe-card "HTTP/1.1 200 OK"
INFO: 01-Apr-24 14:59:43 	Image URL: https://assets-global.website-files.com/60da4419d98adf0a36dc660e/6410bd66159ed29c9a8f62c5_AirFryerChickenThighs-6.jpg
INFO: 01-Apr-24 14:59:43 	HTTP Request: GET https://assets-global.website-files.com/60da4419d98adf0a36dc660e/6410bd66159ed29c9a8f62c5_AirFryerChickenThighs-6.jpg "HTTP/1.1 200 OK"
INFO: 01-Apr-24 14:59:44 	original.jpg minified
INFO: 01-Apr-24 14:59:44 	Tiny image saved
INFO:     192.168.1.243:51574 - "POST /api/recipes/create-url HTTP/1.1" 201 Created
INFO:     192.168.1.243:51574 - "GET /api/recipes/air-fryer-kfc-chicken HTTP/1.1" 200 OK
INFO:     192.168.1.243:51574 - "GET /api/media/recipes/ff5e319a-f27f-4b20-b66d-ba0ec50c36b8/images/original.webp?rnd=1&version=3MH9 HTTP/1.1" 200 OK
INFO:     192.168.1.243:51576 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     127.0.0.1:56934 - "GET /api/app/about HTTP/1.1" 200 OK
```

### Deployment

Docker (Linux)

**Comment by tba-code** [comment]
> ### First Check
> 
>     * [x]  I used the GitHub search to find a similar issue and didn't find it.
> 
>     * [x]  I have verified that this issue _is not_ related to the underlying library
>       [hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers) by **1)** checking
>       the [debugger](https://demo.mealie.io/g/home/r/create/debug) and data is returned, **2)**
>       verifying that there _are_ errors in the log related to application level code, or
>       **3)** verified that the site provides recipe data, or is otherwise supported by
>       [hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers)

This site is unsupported by the underlying library and returns no data for either ingredients or instructions via my local testing.

**Comment by hay-kot** [comment]
I looked at the website and it provided minimal JSON data 

![CleanShot 2024-04-01 at 09 19 04@2x](https://github.com/mealie-recipes/mealie/assets/64056131/b0ccdedd-db20-415d-a1eb-3723a7e8e866)

Doesn't look like an issue with us.
