### ISSUE TITLE
[SCRAPER] - Cannot create any recipes from thekitchn.com

### ISSUE THREAD

**Issue by sovereignalmida** [mealie-recipes/mealie#3404]
### First Check

- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have verified that this issue _is not_ related to the underlying library
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers) by **1)** checking
the [debugger](https://demo.mealie.io/g/home/r/create/debug) and data is returned, **2)**
verifying that there _are_ errors in the log related to application level code, or
**3)** verified that the site provides recipe data, or is otherwise supported by
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers)

- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### Please provide 1-5 example URLs that are having errors

https://www.thekitchn.com/hot-cross-buns-recipe-23649883
https://www.thekitchn.com/sweet-potato-curry-recipe-review-23649428

### Please provide your logs for the Mealie container `docker logs <container-id> > mealie.logs`

Docker via Umbrel
[mealie.log](https://github.com/mealie-recipes/mealie/files/14825730/mealie.log)

### Deployment

Other

**Comment by tba-code** [comment]
Not a Mealie problem. This is an issue with the underlying library. Support for this site is broken on their end. Please open an issue with them: https://github.com/hhursev/recipe-scrapers

**Comment by Kuchenpirat** [comment]
As @tba-code said, this is an issue with the scraper library we are using. 

There is currently an influx of websites that want to be less scrapable to not end up as data on every LLM, and the scraper library is catching some of that as well. 

To get this resolved please open an issue with: https://github.com/hhursev/recipe-scrapers and stick to their issue template. When this is fixed and they publish a new version the fixes will be included in mealie. 

Bellow the returned data directly from the scraper library for reference: 
```
{
  'canonical_url': 'https://www.thekitchn.com/hot-cross-buns-recipe-23649883', 
  'host': 'thekitchn.com', 
  'image': None, 
  'ingredient_groups': [{'ingredients': [], 'purpose': None}], 
  'ingredients': [], 'instructions': '', 
  'instructions_list': [], 
  'language': 'en', '
  site_name': None
}
```

I'll go ahead and close this as this is not an issue with mealie.
