### ISSUE TITLE
[BUG] - Cannot log in with OIDC when a user with the same username already exists

### ISSUE THREAD

**Issue by bramvdzee** [mealie-recipes/mealie#3412]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When trying to implement OIDC I'm getting an error log that says 'incorrect username or password'. There's already an account with the given username (which gives a different error when OIDC_SIGNUP_ENABLED is true, a unique key error). I'd expect it to log in to the account with the given username, regardless if there's already an account with this username.

### Steps to Reproduce

1). Implement OIDC according to the docs
2). Try to login with OIDC

### Please provide relevant logs

03/04/2024 13:09:41 ERROR: 03-Apr-24 13:09:41 	Incorrect username or password from <IP>
03/04/2024 13:09:41 INFO:     172.22.0.19:47124 - "POST /api/auth/token HTTP/1.1" 401 Unauthorized
03/04/2024 13:09:41 INFO:     172.22.0.19:47124 - "GET /login?direct=1 HTTP/1.1" 307 Temporary Redirect

### Mealie Version

v1.4.0

### Deployment

Docker (Linux)

**Comment by bramvdzee** [comment]
I've seen the post in discussions that mention the usergroups, but I don't have any groups specified.

**Comment by cmintey** [comment]
Does your existing user in Mealie have the same email address as the user in your IdP?

**Comment by bramvdzee** [comment]
Not sure why, but that fixed the login issue. From a user experience perspective I would expect either a different error message, or for the e-mail to either update or stay the same without any errors.

**Comment by cmintey** [comment]
For OIDC login, we currently use the email from the IdP to link accounts, not the username, so that's why it worked when you made your emails the same
