### ISSUE TITLE
[BUG] - Please make "Organizers" in sidebar menu translatable

### ISSUE THREAD

**Issue by ghuser238490** [mealie-recipes/mealie#3413]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

This issue lies in between a bug and a feature request: 
Could you please make "Organizers" in the sidebar menu from https://github.com/mealie-recipes/mealie/pull/3390 translatable?  
Thanks a lot!

### Steps to Reproduce

Locate the item "Organizers" in the sidebar menu and change the language settings from English to another language.

### Please provide relevant logs

-

### Mealie Version

Version
v1.4.0
Build
[f709d11952ca8552214e4b9e8c2a189bc11bfb2a](https://github.com/mealie-recipes/mealie/commit/f709d11952ca8552214e4b9e8c2a189bc11bfb2a)

### Deployment

Docker (Linux)

**Comment by Kuchenpirat** [comment]
Thanks for noticing my mistake! 
This will be translatable soon and will be actually translated once our wonderful crowdin crowd adds translations
