### ISSUE TITLE
Oidc login failure. 

### ISSUE THREAD

**Issue by jimski427** [mealie-recipes/mealie#3414]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

After a few minutes I am no longer able to access mealie after authentication with oidc. I have also double checked my Authentik settings and they haven't changed since setting it up.

### Steps to Reproduce

1. Clear browser cache, login with oidc.
2. Close mealie website.
3. Wait 5-10 minutes
4. Attempt to open mealie again. 
5. Get redirected to mealie login page where it refreshes over and over again and generates the log file above. 

### Please provide relevant logs

07:28:23 AM
DEBUG: 03-Apr-24 07:28:23 	[OIDC] expired_token: The token is expired
07:28:23 AM
ERROR: 03-Apr-24 07:28:23 	Incorrect username or password from [Client IP]

### Mealie Version

Docker image: ghcr.io/mealie-recipes/mealie:latest
Mealie version: 1.4.0

### Deployment

Unraid

### Additional Deployment Details

Authentik version: 2024.2.2

**Comment by indykoning** [comment]
I'm experiencing the same issue, and in fact it's exactly after 5 minutes
<img width="512" alt="image" src="https://github.com/mealie-recipes/mealie/assets/15870933/e1a0fc68-52e0-4c14-bab4-064641a4965f">
As you can see in the screenshot access token validity is only 5 minutes.
Which matches our experience, and makes sense as access tokens should be short lived and be checked and updated every time it expires using the refresh token.

My guess is that it is either not implemented in the code, or implemented somewhere in the code where it does not get triggered.

a TEMPORARY workaround would be to set this access token validity to 24 hours as that is also when the cookie it gets saved in expires.
However not recommended long term as anyone with this access token can impersonate you

**Comment by cmintey** [comment]
I was able to replicate. Still trying to figure out why the infinite reload happens. We are actually only using the id_token for identity verification, not the access_token

**Comment by indykoning** [comment]
I think i may know the direction. This is where we use the id token
https://github.com/mealie-recipes/mealie/blob/9e23ed1a07eed83d54385f240a0ca85b8bd3af2a/mealie/core/security/security.py#L27

which is used in the mealie token validation & reauthorisation 
https://github.com/mealie-recipes/mealie/blob/9e23ed1a07eed83d54385f240a0ca85b8bd3af2a/mealie/routes/auth/auth.py#L49

However throwing my id token into a jwt decoder shows me that this is an access token.


I think this is where we're causing the failing authentication 
https://github.com/mealie-recipes/mealie/blob/9e23ed1a07eed83d54385f240a0ca85b8bd3af2a/mealie/core/security/providers/openid_provider.py#L97
Are we saving the refresh token anywhere? If so i think this is where we should use it to request a new access token and use that to authenticate instead.

Reason for the infinite redirect is probably that we're not deleting the oidc cookies on failed authentication

**Comment by jimski427** [comment]
Well im glad to see it wasn't something on my end! I don't know which specific version broke it. I was using nightly up until today as I saw 1.4 was was released. I don't log in every single day and I know it was working consistently like a week ago.

**Comment by bpbradley** [comment]
I'm not sure if this is related, but I'm getting the exact same behavior when trying to login a new user using OAuth. I have allowed signups, so my understanding is that it should work. But when I try to login with another user I get the infinite redirect bug.

**Comment by mobiledude** [comment]
> Well im glad to see it wasn't something on my end! I don't know which specific version broke it. I was using nightly up until today as I saw 1.4 was was released. I don't log in every single day and I know it was working consistently like a week ago.

I think 2 or 3 releases ago.
