### ISSUE TITLE
Migration needed. Performing migration...

### ISSUE THREAD

**Issue by BenSanborn** [mealie-recipes/mealie#3418]
Using Mealie on unRAID. Mealer was working perfecftly fine last week, now I'm seeing:

ValueError: invalid interpolation syntax in 'postgresql://me:password@192.168.1.174:5432/postgres' at position 22

ERROR:    Application startup failed. Exiting.
Switching to dedicated user

  User uid:    99
     User gid:    100

INFO: 03-Apr-24 20:25:54        start: database initialization
INFO: 03-Apr-24 20:25:54        Database connection established.
INFO: 03-Apr-24 20:25:54        Context impl PostgresqlImpl.
INFO: 03-Apr-24 20:25:54        Will assume transactional DDL
INFO: 03-Apr-24 20:25:54        Migration needed. Performing migration...

and it does not perform a migration or do anything further. Mealie does not load and container is auto-stopped.

**Comment by michael-genson** [comment]
Does your postgres password have a percent sign in it? If yes, you need to escape it with a double percent (e.g. `abc%123` --> `abc%%123`)

**Comment by BenSanborn** [comment]
Is this something that recently changed? Yes mine does have several % in it.

**Comment by michael-genson** [comment]
It was a few months ago in nightly but I believe the first time it hit release was 1.4.0 which was earlier today: https://github.com/mealie-recipes/mealie/pull/3163

**Comment by MrLyallCSIT** [comment]
Mine does not have a % but a * in the password. Does this need to be escaped too?

**Comment by michael-genson** [comment]
I don't think you need to do anything special with most characters, it should just be % signs. However generally URL encoding your postgres password is a good idea

**Comment by BenSanborn** [comment]
Changing password worked, thank you much!

FYI, I also had !! in my postgres password and it was showing as another character that possibly needed to be doubled. It was much easier to just make a super basic password with no special characters.
