### ISSUE TITLE
[BUG] - UX: Re-ordering labels on shopping list

### ISSUE THREAD

**Issue by boc-the-git** [mealie-recipes/mealie#3426]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

The UX for re-ordering shopping lists is bad.
There is only a "cancel" button, though its effect is "close". Updates to the order appear to be saved in real time when you drag and drop; though I didn't look into it extensively.

Hitting "cancel" certainly does not "undo" the changes you'd made.

There's probably 2 solutions here.. either reword "cancel" to "close" (easier), or implement actual "cancel" and "save" functionality. The former is fine.

![image](https://github.com/mealie-recipes/mealie/assets/3479092/fd94fda9-27e6-416d-809e-363a38b3c4a7)

### Steps to Reproduce

On a shopping list, toggle label sorting, then re-order the labels.

### Please provide relevant logs

N/A

### Mealie Version

Assume this is applicable to all versions.

Version
nightly
Build
[de142c47df8486ee8dad17ad9947bcc4d5b8a6b2](https://github.com/mealie-recipes/mealie/commit/de142c47df8486ee8dad17ad9947bcc4d5b8a6b2)

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
As the one who implemented it I agree it's awful. I vote for the latter - making it a proper save/cancel.
