### ISSUE TITLE
[SCRAPER] - foodnetwork.com recipe scraping returns 403 Forbidden

### ISSUE THREAD

**Issue by HerbCSO** [mealie-recipes/mealie#3432]
### First Check

- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have verified that this issue _is not_ related to the underlying library
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers) by **1)** checking
the [debugger](https://demo.mealie.io/g/home/r/create/debug) and data is returned, **2)**
verifying that there _are_ errors in the log related to application level code, or
**3)** verified that the site provides recipe data, or is otherwise supported by
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers)

- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### Please provide 1-5 example URLs that are having errors

https://www.foodnetwork.com/recipes/ree-drummond/tater-tot-breakfast-casserole-4607655

### Please provide your logs for the Mealie container `docker logs <container-id> > mealie.logs`

INFO: 06-Apr-24 12:30:12        HTTP Request: GET https://www.foodnetwork.com/recipes/ree-drummond/tater-tot-breakfast-casserole-4607655 "HTTP/1.1 403 Forbidden"
ERROR: 06-Apr-24 12:30:12       Recipe Scraper was unable to extract a recipe from https://www.foodnetwork.com/recipes/ree-drummond/tater-tot-breakfast-casserole-4607655
INFO: 06-Apr-24 12:30:12        HTTP Request: GET https://www.foodnetwork.com/recipes/ree-drummond/tater-tot-breakfast-casserole-4607655 "HTTP/1.1 403 Forbidden"

### Deployment

Docker (Linux)

**Comment by HerbCSO** [comment]
I'm honestly not sure if this is a `recipe-scraper` issue or a `mealie` issue, so I'm starting here. ;]

I have a sneaking suspicion it might be due to the user agent string, maybe? So possibly because it can identify `mealie` and they're blocking it? Regular requests for the recipe from the same IP certainly don't have issues, and a `curl` from the docker host where I'm running `mealie` also works fine.

**Comment by HerbCSO** [comment]
I also tried running a local nginx container and using it as a target to scrape from in an attempt to see what the actual user agent string is, but for some reason none of the requests I sent from mealie showed up in my nginx logs (curl and browser worked fine) - I must be doing a dumb there, no idea why that's not working.

**Comment by Mraedis** [comment]
This is fixed in the newest version of the scraper, but hasn't been pulled into a mealie release. https://github.com/hhursev/recipe-scrapers/pull/1026

**Comment by HerbCSO** [comment]
Dangit, didn't search their issue, sorry! But it looks like my suspicion was correct. ;]

Feel free to close this, or leave it open to track when the new version is in a release, either way, sorry for the noise and thank you!

**Comment by boc-the-git** [comment]
Per comments, will be fixed in the next recipe-scrapers release.

**Comment by williamkray** [comment]
sorry to necrobump, this is marked as completed, but i'm running mealie v1.11.0 in docker and i'm getting 403s for foodnetwork.com recipes... exec-ing into the container seems to show the pyproject.toml  includes the following info:

```
pyproject.toml
::::::::::::::
[tool.poetry]
authors = ["Hayden <hay-kot@pm.me>"]
description = "A Recipe Manager"
license = "AGPL"
name = "mealie"
version = "1.10.1"

```

and under poetry dependencies:

```
recipe-scrapers = "^15.0.0"
```

not sure what's going wrong here or how to troubleshoot this further, but definitely the same issue... 403 responses from foodnetwork.com using latest mealie which supposedly has the latest fixed version of recipe-scrapers included.

**Comment by williamkray** [comment]
seems like it's a user-agent issue, if i put in a user-agent that i get from my firefox browser, i get a 200 when running the python `requests` get. if i have something else in the user agent, i get a 403. i assume mealie is sending this user-agent string with its requests, so this is probably a mealie problem. i'll open a new issue for it.
