### ISSUE TITLE
[BUG] - Images do not upload when manually creating a recipe

### ISSUE THREAD

**Issue by helmerzNL** [mealie-recipes/mealie#3434]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When I'm trying to add an image to a manual created recipe, the image is not uploaded.

### Steps to Reproduce

1) create a recipe manually
2) Enter recipe name
3) click create
4) click Image
5) click upload
6) browse to jpg file of recipe and select it
7) click Open

### Please provide relevant logs

```
INFO:     192.168.117.56:57240 - "GET /api/recipes?page=3&perPage=32&orderBy=created_at&orderDirection=desc&paginationSeed=1712485749549&searchSeed=1712485749549&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
INFO:     192.168.117.56:57249 - "GET /api/media/recipes/35d9387b-d5d1-47bb-8740-fd381b4d65b0/images/min-original.webp?rnd=1&version=148 HTTP/1.1" 200 OK
INFO:     192.168.117.56:57250 - "GET /api/media/recipes/9840e76f-0dc4-4a15-a963-e997af855c8e/images/min-original.webp?rnd=1&version=247 HTTP/1.1" 200 OK
INFO:     192.168.117.56:57240 - "GET /api/media/recipes/3fa247b6-c253-4ddf-aaa9-69363d839901/images/min-original.webp?rnd=1&version=127 HTTP/1.1" 200 OK
INFO:     127.0.0.1:33042 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     192.168.117.56:57250 - "GET /api/media/recipes/b9e700ea-d9c8-4535-a09c-6e255d297ac8/images/min-original.webp?rnd=1&version=132 HTTP/1.1" 200 OK
INFO:     192.168.117.56:57240 - "GET /api/media/recipes/64d0cff3-77ca-405c-9ebc-d32cbc2a42e6/images/min-original.webp?rnd=1&version=j4RH HTTP/1.1" 200 OK
INFO:     192.168.117.56:57249 - "GET /api/media/recipes/1e3429a5-65ba-451f-8ae1-afa06a098486/images/min-original.webp?rnd=1&version=104 HTTP/1.1" 200 OK
INFO:     192.168.117.56:57249 - "GET /api/recipes/honing-soja-kipspiesjes-met-rijst-en-wokgroenten HTTP/1.1" 200 OK
INFO:     192.168.117.56:57249 - "GET /api/media/recipes/c464d1a2-27c6-42f7-a6cd-9b95bc316195/images/original.webp?rnd=1&version= HTTP/1.1" 404 Not Found
INFO:     192.168.117.56:57249 - "GET /api/media/recipes/c464d1a2-27c6-42f7-a6cd-9b95bc316195/images/original.webp?rnd=1&version= HTTP/1.1" 404 Not Found
INFO:     192.168.117.56:57250 - "GET /api/recipes/honing-soja-kipspiesjes-met-rijst-en-wokgroenten/comments HTTP/1.1" 200 OK
INFO:     192.168.117.56:57250 - "GET /api/units?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     192.168.100.27:51966 - "GET /api/groups/mealplans?page=1&perPage=4&start_date=2024-04-07&end_date=2024-04-09&orderDirection=asc HTTP/1.1" 401 Unauthorized
INFO:     127.0.0.1:55086 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     192.168.100.27:60452 - "GET /api/groups/mealplans?page=1&perPage=4&start_date=2024-04-07&end_date=2024-04-09&orderDirection=asc HTTP/1.1" 401 Unauthorized
INFO:     192.168.117.56:57272 - "GET /api/media/recipes/c464d1a2-27c6-42f7-a6cd-9b95bc316195/images/original.webp?rnd=2&version= HTTP/1.1" 404 Not Found
INFO:     192.168.117.56:57272 - "GET /api/media/recipes/c464d1a2-27c6-42f7-a6cd-9b95bc316195/images/original.webp?rnd=2&version= HTTP/1.1" 404 Not Found
INFO:     192.168.117.56:57281 - "GET /_nuxt/fonts/Roboto-400-latin-ext20.861b791.woff2 HTTP/1.1" 200 OK
INFO:     192.168.117.56:57280 - "GET /_nuxt/fonts/Roboto-400-cyrillic16.71a33b6.woff2 HTTP/1.1" 200 OK
INFO:     192.168.117.56:57280 - "GET /_nuxt/fonts/Roboto-400-vietnamese19.3230f9b.woff2 HTTP/1.1" 200 OK
INFO:     127.0.0.1:59792 - "GET /api/app/about HTTP/1.1" 200 OK
```

### Mealie Version

version 1.4.0
repository: ghcr.io/mealie-recipes/mealie:latest
Build tag: [f709d11952ca8552214e4b9e8c2a189bc11bfb2a](https://github.com/mealie-recipes/mealie/commit/f709d11952ca8552214e4b9e8c2a189bc11bfb2a)

### Deployment

Unraid

**Comment by GeorgRamer** [comment]
I was just searching through the issues to find if someone is experiencing this same issue. It happened to me on v1.0.0-RC1 and now on v1.4.0 Has been going on since about a week, at least? Happy to supply any kind of info I can in addition to what @helmerzNL  already has posted.

I also tried uploading webps directly, this did also not work.

**Comment by helmerzNL** [comment]
> I was just searching through the issues to find if someone is experiencing this same issue. It happened to me on v1.0.0-RC1 and now on v1.4.0 Has been going on since about a week, at least? Happy to supply any kind of info I can in addition to what @helmerzNL already has posted.
> 
> I also tried uploading webps directly, this did also not work.

I have the issues since a couple of weeks. Strangely it does not happen when I import a recipe from a website ;-( But not all websites are supported by the scraper.

**Comment by GeorgRamer** [comment]
This is reproduced on the demo instance as well. Image upload works for recipes created via scraper there but not for recipes created manually.

edit: weird, now it seems to work on the demo instance... Maybe I was mistaken before?

**Comment by GeorgRamer** [comment]
Sorry for the stream of consciousness approach: 

When I look into /app/data/recipes/<GUID> of one of the non-working recipes I only see and /assets subfolder but no /images subfolder. For working recipes /assets and /images are present. My suspicion is that  the image upload does not create this folder if it doesn't exist already. I tried to find the corresponding part of code but that turned out to be beyond my capabilities.

**Comment by tba-code** [comment]
This is likely a local bug and not a bug with Mealie. Please try this in a separate browser first, as I am unable to replicate this locally or on the demo.

**Comment by Mraedis** [comment]
Are you perchance using an iPhone to upload images? The default image format for iPhone is not (yet) supported in mealie. See also https://github.com/mealie-recipes/mealie/issues/3393

**Comment by GeorgRamer** [comment]
> Are you perchance using an iPhone to upload images? The default image format for iPhone is not (yet) supported in mealie. See also #3393

No, I used android (Firefox) and Ubuntu (Chrome, Firefox). I have narrowed it down to a file size dependent issue now. Small files work fine, larger files (~ 3MB) don't. Since the same files are working on the demo instance but not on mine I guess the server this my Mealie instance running on is just slower, leading to some time out? 

Or I set a file upload limit somewhere. The cutoff for working/non-working is suspiciously close to 1 MB.

**Comment by helmerzNL** [comment]
I'm trying it to do in in Microsoft Edge on Windows 11 btw. The image I"m trying to upload is < 250 Kbyte. It also does not work in Safari on iOS (even when I selected a downloaded jpg as the image, so no HEIC image).

**Comment by GeorgRamer** [comment]
> I'm trying it to do in in Microsoft Edge on Windows 11 btw. The image I"m trying to upload is < 250 Kbyte.

I am sorry I have hijacked your issue. I have narrowed my issue down to a local nginx config problem, probably.

**Comment by helmerzNL** [comment]
> > I'm trying it to do in in Microsoft Edge on Windows 11 btw. The image I"m trying to upload is < 250 Kbyte.
> 
> 
> 
> I am sorry I have hijacked your issue. I have narrowed my issue down to a local nginx config problem, probably. 


Not a problem. Btw, on my side it also occurs when using the local up with port number, no reverse proxy being part of the process.

**Comment by Mraedis** [comment]
As for @helmerzNL you post logs of images not being found, but the most relevant log would be the POST action of uploading the image, any chance you can share those?

**Comment by helmerzNL** [comment]
> As for @helmerzNL you post logs of images not being found, but the most relevant log would be the POST action of uploading the image, any chance you can share those?

Yeah, the strang thing is (I tried it twice), it's not showing a real POST 

INFO:     192.168.100.27:44596 - "GET /api/organizers/tags?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     192.168.100.27:44628 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     192.168.100.27:44610 - "GET /api/groups/cookbooks?page=1&perPage=-1&orderBy=position&orderDirection=asc HTTP/1.1" 200 OK
INFO:     192.168.100.27:44622 - "GET /api/organizers/categories?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     192.168.100.27:44598 - "GET /api/recipes?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1712612048850&searchSeed=1712612048850&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
INFO:     192.168.100.27:44638 - "GET /api/media/users/569d1def-e8ed-4140-bc5c-b6dd21fb2405/profile.webp?cacheKey=Wo9m HTTP/1.1" 200 OK
INFO:     192.168.100.27:44592 - "GET /api/foods?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     192.168.100.27:44652 - "GET /api/groups/self HTTP/1.1" 200 OK
INFO:     192.168.100.27:44654 - "GET /api/media/recipes/c464d1a2-27c6-42f7-a6cd-9b95bc316195/images/min-original.webp?rnd=1&version= HTTP/1.1" 404 Not Found
INFO:     192.168.100.27:44694 - "GET /api/media/recipes/bf32b218-f56a-474d-8abb-aaf9b4c3882b/images/min-original.webp?rnd=1&version= HTTP/1.1" 404 Not Found
INFO:     192.168.100.27:44700 - "GET /api/media/recipes/c8aa753c-f977-4a57-a3cd-be721293df41/images/min-original.webp?rnd=1&version= HTTP/1.1" 404 Not Found
INFO:     192.168.100.27:44682 - "GET /api/media/recipes/c6adb33e-712c-42be-9962-6907a0e8db18/images/min-original.webp?rnd=1&version= HTTP/1.1" 200 OK
INFO:     192.168.100.27:44666 - "GET /api/media/recipes/4edcbc7c-3671-44db-9577-34ef747e1f84/images/min-original.webp?rnd=1&version=86 HTTP/1.1" 200 OK
INFO:     192.168.100.27:44724 - "GET /api/media/recipes/417f5109-38b3-4123-ac9d-21ace67b8344/images/min-original.webp?rnd=1&version=0Soh HTTP/1.1" 200 OK
INFO:     192.168.100.27:44716 - "GET /api/recipes?page=3&perPage=32&orderBy=created_at&orderDirection=desc&paginationSeed=1712612048850&searchSeed=1712612048850&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200 OK
INFO:     192.168.100.27:44738 - "GET /sw.js HTTP/1.1" 200 OK
INFO:     192.168.100.27:44748 - "GET /api/recipes/honing-soja-kipspiesjes-met-rijst-en-wokgroenten HTTP/1.1" 200 OK
INFO:     192.168.100.27:44764 - "GET /api/media/recipes/c464d1a2-27c6-42f7-a6cd-9b95bc316195/images/original.webp?rnd=1&version= HTTP/1.1" 404 Not Found
INFO:     192.168.100.27:44778 - "GET /api/recipes/honing-soja-kipspiesjes-met-rijst-en-wokgroenten/comments HTTP/1.1" 200 OK
INFO:     127.0.0.1:59338 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:50344 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     192.168.100.27:47452 - "GET /api/units?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     127.0.0.1:41760 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     192.168.100.27:47934 - "PUT /api/recipes/honing-soja-kipspiesjes-met-rijst-en-wokgroenten HTTP/1.1" 200 OK
INFO:     127.0.0.1:40968 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     192.168.100.27:35750 - "GET /api/recipes/honing-soja-kipspiesjes-met-rijst-en-wokgroenten/comments HTTP/1.1" 200 OK
INFO:     192.168.100.27:35754 - "GET /api/media/recipes/c464d1a2-27c6-42f7-a6cd-9b95bc316195/images/original.webp?rnd=2&version= HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:52022 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     192.168.100.27:37434 - "PUT /api/recipes/honing-soja-kipspiesjes-met-rijst-en-wokgroenten HTTP/1.1" 200 OK


**And I tried it again, this time while uploading an image from a URL** 

INFO:     192.168.100.27:44778 - "GET /api/recipes/honing-soja-kipspiesjes-met-rijst-en-wokgroenten/comments HTTP/1.1" 200 OK
INFO:     127.0.0.1:59338 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:50344 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     192.168.100.27:47452 - "GET /api/units?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200 OK
INFO:     127.0.0.1:41760 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     192.168.100.27:47934 - "PUT /api/recipes/honing-soja-kipspiesjes-met-rijst-en-wokgroenten HTTP/1.1" 200 OK
INFO:     127.0.0.1:40968 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     192.168.100.27:35750 - "GET /api/recipes/honing-soja-kipspiesjes-met-rijst-en-wokgroenten/comments HTTP/1.1" 200 OK
INFO:     192.168.100.27:35754 - "GET /api/media/recipes/c464d1a2-27c6-42f7-a6cd-9b95bc316195/images/original.webp?rnd=2&version= HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:52022 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     192.168.100.27:37434 - "PUT /api/recipes/honing-soja-kipspiesjes-met-rijst-en-wokgroenten HTTP/1.1" 200 OK
INFO:     192.168.100.27:41094 - "GET /api/recipes/honing-soja-kipspiesjes-met-rijst-en-wokgroenten/comments HTTP/1.1" 200 OK
INFO:     127.0.0.1:46086 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:38488 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:49856 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     127.0.0.1:39430 - "GET /api/app/about HTTP/1.1" 200 OK
INFO: 08-Apr-24 23:38:58        Image URL: https://bettyskitchen.nl/wp-content/uploads/2022/09/indonesische_kip_sate_ajam_%C2%A9-bettyskitchen_-289x385.jpg
INFO: 08-Apr-24 23:38:59        HTTP Request: GET https://bettyskitchen.nl/wp-content/uploads/2022/09/indonesische_kip_sate_ajam_%C2%A9-bettyskitchen_-289x385.jpg "HTTP/1.1 200 OK"
INFO: 08-Apr-24 23:38:59        original.jpg minified
INFO: 08-Apr-24 23:38:59        Tiny image saved
INFO:     192.168.100.27:37772 - "POST /api/recipes/honing-soja-kipspiesjes-met-rijst-en-wokgroenten/image HTTP/1.1" 200 OK
INFO:     127.0.0.1:59364 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     192.168.100.27:52556 - "PUT /api/recipes/honing-soja-kipspiesjes-met-rijst-en-wokgroenten HTTP/1.1" 200 OK
INFO:     192.168.100.27:52566 - "GET /api/recipes/honing-soja-kipspiesjes-met-rijst-en-wokgroenten/comments HTTP/1.1" 200 OK

**Comment by aposchde** [comment]
Still same behavior on nighty (2025-10-15, build [ca9d5677b82e58ba77d2179e969a0f40e4e5853c](https://github.com/mealie-recipes/mealie/commit/ca9d5677b82e58ba77d2179e969a0f40e4e5853c)): unable to upload picture on manually added recipe. Tried with FF and Vivaldi (Chrome).

**Comment by JackThursby252** [comment]
Bug still exists, lol. 

Auto Close Bots are so stupid. 

/Edit: Auto close bots are not stupid, but I am. Nginx didnt tell me that the request was too large and i used my global var of 5mb, setting it to 50m fixed it immediately.

**Comment by coastlee** [comment]
I'm having the same issue. Tried firefox and safari. Tried .png, .jpg, .heic files. Logs show a 404 Not Found when I try to upload a photo. I can link it to a URL just fine, but cannot upload my own local photos.

**Comment by maisatanel** [comment]
To anyone encountering this issue: please make sure that the reverse proxy your Mealie instance is behind of allows you to upload large media. For nginx it's
```
client_max_body_size 20M;
```
in your `server` directive.

**Comment by Xadrian-89** [comment]
> To anyone encountering this issue: please make sure that the reverse proxy your Mealie instance is behind of allows you to upload large media. For nginx it's
> 
> ```
> client_max_body_size 20M;
> ```
> 
> in your `server` directive.

That fixed it for me. Thank you very much!
