### ISSUE TITLE
[BUG] - Recipe timeline event is not created automatically after recipe was added to the meal planner

### ISSUE THREAD

**Issue by ghuser238490** [mealie-recipes/mealie#3454]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

According to https://github.com/mealie-recipes/mealie/pull/2050 a recipe timeline event will be created automatically on a daily basis after a recipe was added to the meal planner. 

On my instance that never happened, both the 'last made' date and the recipe timeline doesn't change.
I found this older related issue https://github.com/mealie-recipes/mealie/issues/2344  

I checked with v1.4.0, the latest nightly and the demo site. 
Maybe I'm missing something? Thanks for your help 🙏

### Steps to Reproduce

- Add a recipe to the meal planner as mentioned in https://github.com/mealie-recipes/mealie/issues/2344
> Added recipe for today from Meal Plan page
> Added recipe for today to Meal Plan from the Recipe
> Added recipe for today to Meal Plan from the recipe overview

- Wait for at least one day or longer.

- The 'last made' date of the recipe does not change, no recipe timeline event was added.

### Please provide relevant logs

I could not find anything related to this issue or any errors.
The only scheduled task I can see the logs is the hourly reset of locked users, but no hint of timeline events.
`INFO: 11-Apr-24 23:02:51 	locked users reset`

### Mealie Version

Version
v1.4.0
Build
[f709d11952ca8552214e4b9e8c2a189bc11bfb2a](https://github.com/mealie-recipes/mealie/commit/f709d11952ca8552214e4b9e8c2a189bc11bfb2a)

Version
nightly
Build
[94678fe6e0a4831b3cbc24b366dba1009d360f23](https://github.com/mealie-recipes/mealie/commit/94678fe6e0a4831b3cbc24b366dba1009d360f23)

### Deployment

Docker (Linux)

**Comment by boc-the-git** [comment]
This is an issue. I've noticed an interesting quirk though.. in my instance there is a timeline event created about 10 days ago, for a recipe that maybe my partner added to the mealplan. But for the most part I do the mealplan, and no events have been created for most things..

So maybe there's some differences in how we are creating those entries.
Haven't explored that any deeper yet.

This is probably the relevant code: https://github.com/mealie-recipes/mealie/blob/mealie-next/mealie/services/scheduler/tasks/create_timeline_events.py
