### ISSUE TITLE
scraping ingredients/units in dutch not working well

### ISSUE THREAD

**Issue by remb0** [mealie-recipes/mealie#3460]
I have added multiple recepts from different sites but in Dutch it is not working well. In tandoor it's working fine.
But I prefer mealie, expect for the ingredient parser. Can I do something to choose another model or import ingredients and units so it works better, or is that not an option?

**Comment by RealFoxie** [comment]
If you add Dutch units (and foods maybe), the brute parser should work quite well.
default the nlp parser is selected, but this is focused on English.

Im not sure if there is a Dutch list to import.

**Comment by Kuchenpirat** [comment]
Hey, as RealFoxie said, the brute parser should work fine if you have foods and units seeded. 

Im will go ahead and close this. For the future, please use our issue templates.
