### ISSUE TITLE
[BUG] - Redirect /login?=code... to /login/?=code... making OIDC fail

### ISSUE THREAD

**Issue by seppeel** [mealie-recipes/mealie#3473]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I configured OIDC with authelia like described in the authelia documentation for mealie. Mealie is running behind nginx reverse proxy. (config provided below)
The Login flow seems to work correctly but the login to mealie fails. It seems like the reason is a 307 temporary redirect from /login to /login/ which breaks redirect url.

I tried to mess around with my nginx settings but was not able to fix it there. So i decided to open up this issue.

### Steps to Reproduce

1. Configure OIDC (config details below)
2. Go to mealie login page
3. choose "Anmelden mit OAuth" (i have german locale)
4. login with my testuser
5. confirm the authelia request that mealie may use identity, mail, name and group
6. now the redirect back to the mealie login page should log me in. That does not work. A look at the browser adress bar shows me the following:

`https://mealie.<myhostname>.com/login/?code=authelia_ac_<token>`

this should be without the slash after /login i guess.
The container log shows me a 307 redirect.

### Please provide relevant logs

```
mealie     | INFO     2024-04-16T19:27:51 - [xxxx] 200 OK "GET /api/app/about/oidc HTTP/1.1"
mealie     | INFO     2024-04-16T19:28:03 - [xxxx] 307 Temporary Redirect "GET /login?code=authelia_ac_<token>&iss=https%3A%2F%2Fauth.<myhostname>.com&scope=openid+profile+email+groups&state=u2jZbGd7Be HTTP/1.1"
mealie     | INFO     2024-04-16T19:28:03 - [xxxx] 200 OK "GET /login/?code=authelia_ac_<token>&iss=https%3A%2F%2Fauth.<myhostname>.com&scope=openid+profile+email+groups&state=u2jZbGd7Be HTTP/1.1"
mealie     | INFO     2024-04-16T19:28:03 - [xxxx] 200 OK "GET /api/app/about/startup-info HTTP/1.1"
```

### Mealie Version

1.5.0

### Deployment

Docker (Linux)

### Additional Deployment Details

My OIDC Environment settings:
```
      - OIDC_AUTH_ENABLED=true
      - OIDC_SIGNUP_ENABLED=true
      - OIDC_CONFIGURATION_URL=https://auth.<myhostname>.com/.well-known/openid-configuration
      - OIDC_CLIENT_ID=mealie
      - OIDC_AUTO_REDIRECT=false
      - OIDC_ADMIN_GROUP=mealie_admin
      - OIDC_USER_GROUP=mealie
```
My authelia oidc client config:

```
    clients:
      - client_id: 'mealie'
        client_name: 'Mealie'
        public: true
        authorization_policy: 'one_factor'
        require_pkce: true
        pkce_challenge_method: 'S256'
        redirect_uris:
          - 'https://mealie.<myhostname>.com/login'
        scopes:
          - 'openid'
          - 'email'
          - 'profile'
          - 'groups'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'none'
```
My nginx config for mealie:

```
server {
    listen 443 ssl;
    server_name mealie.<myhostname>.com;
    resolver 127.0.0.11 valid=30s;
    ssl_certificate /etc/letsencrypt/live/<myhostname>.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/<myhostname>.com/privkey.pem;
    ssl_prefer_server_ciphers on;

    location / {
        set $upstream mealie:9000;
        proxy_pass http://$upstream;
        include /etc/nginx/snippets/proxy.conf;
    }
}
```

proxy.conf (the one authelia provides)
```
## Headers
proxy_set_header Host $host;
proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $http_host;
proxy_set_header X-Forwarded-URI $request_uri;
proxy_set_header X-Forwarded-Ssl on;
proxy_set_header X-Forwarded-For $remote_addr;
proxy_set_header X-Real-IP $remote_addr;

## Basic Proxy Configuration
client_body_buffer_size 128k;
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503; ## Timeout if the real server is dead.
proxy_redirect http:// $scheme://;
proxy_http_version 1.1;
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 64 256k;

## Trusted Proxies Configuration
## Please read the following documentation before configuring this:
##     https://www.authelia.com/integration/proxies/nginx/#trusted-proxies
# set_real_ip_from 10.0.0.0/8;
# set_real_ip_from 172.16.0.0/12;
# set_real_ip_from 192.168.0.0/16;
# set_real_ip_from fc00::/7;
real_ip_header X-Forwarded-For;
real_ip_recursive on;

## Advanced Proxy Configuration
send_timeout 5m;
proxy_read_timeout 360;
proxy_send_timeout 360;
proxy_connect_timeout 360;
```

**Comment by p2bauer** [comment]
I'm getting the same issue, also with authelia - but without nginx (it's hosted in Kubernetes w/ a cloudflare tunnel pointing directly to the load balancer port 9000)

**Comment by cmintey** [comment]
Are there any logs in Authelia? Do you have Authelia also set up as forward with proxy for Mealie? Someone else encountered a similar issue that was unrelated to Mealie (https://github.com/mealie-recipes/mealie/issues/3461#issuecomment-2053625133)

**Comment by tba-code** [comment]
This is a confirmed bug. The issue is Mealie is unable to get the access token because of a CORS error when fetching the token.
You are correct that it is because of the /login/? error in the URL.

As a workaround, in your Authelia config, please set ```allowed_origins_from_client_redirect_uris: true``` in the indentity_providers.oidc section.

I have confirmed being able to sign up and log in after changing that setting.

**Comment by seppeel** [comment]
Thanks.

A short test with this authelia setting
```
identity_providers:
  oidc:
    cors:
      allowed_origins_from_client_redirect_uris: true
```

shows me the same behaviour. Tomorrow i will have a closer look at it.

**Comment by cmintey** [comment]
> This is a confirmed bug. The issue is Mealie is unable to get the access token because of a CORS error when fetching the token.

If CORS is the reason for the error then this is not a bug but CORS working properly. It is documented that you should add the mealie domain as an allowed origin in [step 3 of the setup](https://docs.mealie.io/documentation/getting-started/authentication/oidc/#provider-setup)

**Comment by tba-code** [comment]
> > This is a confirmed bug. The issue is Mealie is unable to get the access token because of a CORS error when fetching the token.
> 
> If CORS is the reason for the error then this is not a bug but CORS working properly. It is documented that you should add the mealie domain as an allowed origin in [step 3 of the setup](https://docs.mealie.io/documentation/getting-started/authentication/oidc/#provider-setup)

I don't think you understand the issue here. The issue is that Mealie is redirecting requests to /login -> /login/

The check happens after the redirect occurs.

Authelia is setup correctly. The correct redirect_uri is present. but the request fails the check because it checks the redirected (messed up) url.

**Comment by cmintey** [comment]
> > > This is a confirmed bug. The issue is Mealie is unable to get the access token because of a CORS error when fetching the token.
> > 
> > 
> > If CORS is the reason for the error then this is not a bug but CORS working properly. It is documented that you should add the mealie domain as an allowed origin in [step 3 of the setup](https://docs.mealie.io/documentation/getting-started/authentication/oidc/#provider-setup)
> 
> I don't think you understand the issue here. The issue is that Mealie is redirecting requests to /login -> /login/
> 
> The check happens after the redirect occurs.
> 
> Authelia is setup correctly. The correct redirect_uri is present. but the request fails the check because it checks the redirected (messed up) url.

I see that same redirect happen in the logs of my Mealie. I don't think that is the issue. Have you enabled Debug logs in Mealie? Are there any errors in the browser console?

```
mealie     | INFO     2024-04-16T21:07:57 - [127.0.0.1:37468] 200 OK "GET /api/app/about HTTP/1.1"
mealie     | INFO     2024-04-16T21:08:02 - [10.0.2.1:0] 307 Temporary Redirect "GET /login?code=xxx&iss=https%3A%2F%2Fauth.example.com&scope=openid+profile+email+groups&state=xxx HTTP/1.1"
mealie     | INFO     2024-04-16T21:08:02 - [10.0.2.1:0] 200 OK "GET /login/?code=xxx&iss=https%3A%2F%2Fauth.example.com&scope=openid+profile+email+groups&state=xxx HTTP/1.1"
mealie     | DEBUG    2024-04-16T21:08:03 - Starting new HTTPS connection (1): auth.example.com:443
mealie     | DEBUG    2024-04-16T21:08:03 - https://auth.example.com:443 "GET /.well-known/openid-configuration HTTP/1.1" 200 2507
mealie     | DEBUG    2024-04-16T21:08:03 - Starting new HTTPS connection (1): auth.example.com:443
mealie     | DEBUG    2024-04-16T21:08:03 - https://auth.example.com:443 "GET /jwks.json HTTP/1.1" 200 773
mealie     | INFO     2024-04-16T21:08:03 - [10.0.2.1:0] 304 Not Modified "GET /sw.js HTTP/1.1"
mealie     | INFO     2024-04-16T21:08:04 - [10.0.2.1:0] 200 OK "POST /api/auth/token HTTP/1.1"
mealie     | INFO     2024-04-16T21:08:04 - [10.0.2.1:0] 200 OK "GET /api/users/self HTTP/1.1"

```

**Comment by seppeel** [comment]
You were right, i was missing proper CORS configuration in authelia.

```
identity_providers:
  oidc:
    cors:
      endpoints:
        - 'authorization'
        - 'token'
        - 'revocation'
        - 'introspection'
```
Is the configuration which works now. So i was missing a proper endpoint configuration.

It is not necessary to add CORS origins manually or set `allowed_origins_from_client_redirect_uris` to true to make mealie work as the default setting for authelia is to allow all https origins. This is the explanation out of the authelia default config:

```
## List of allowed origins.
## Any origin with https is permitted unless this option is configured or the
## allowed_origins_from_client_redirect_uris option is enabled.
```

I think `allowed_origins_from_client_redirect_uris` should ne enabled for security reasons, but the reason for my setup not working was the missing endpoint config.

Surprisingly i was running into another bug which is a new redirect loop.
I forgot to add my testuser back to the mealie and meale_admin group which leads to an infinite redirect loop.

Thanks for your help.

I think i keep this open until the authelia documentation for mealie got updated.
Does someone know which endpoint configs are at least neccessary to make mealie work? Then a short update to the authelia docs shouldnt be a problem.

**Comment by seppeel** [comment]
Closed because cors endpoints configuration in authelia is a general prerequisite for many integrations to work. no documentation in authelia needed.
