### ISSUE TITLE
[BUG] - Some English text is hardcoded in the app and not translatable

### ISSUE THREAD

**Issue by Yuni1988** [mealie-recipes/mealie#3490]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

There are a few bits of text that are not translatable:
- default note for ingredients (1 cup flour)
- default text for instructions steps
- days of the week in mealplanner
![image](https://github.com/mealie-recipes/mealie/assets/69676522/8f2a5ca3-529e-410f-82e4-818e0abb55cc)
![image](https://github.com/mealie-recipes/mealie/assets/69676522/140e72c6-2395-434e-a7aa-282e9b435b4e)

### Steps to Reproduce

1) Switch language something other than English
2) Create a new recipe, observe English text
3) Open mealplanner, observe English text

### Please provide relevant logs

/

### Mealie Version

Tested on v1.4.0. I was unable to test on demo, as it appears to be down.

### Deployment

Docker (Linux)

**Comment by ghuser238490** [comment]
I cannot confirm that the weekdays on the meal planner page are not translatable. @Yuni1988 , is your language Slovenian? Anyways, I checked Crowdin and the weekdays strings are already translated in every single supported language (except a few languages which clearly are not yours).
But when switching the language to Slovenian or Croatian the weekdays are still presented in english.

**Comment by Yuni1988** [comment]
My language is Slovenian, correct. Weekdays are already translated in Crowdin, but as you can see from the screenshot, they are not translated in the app. So it appears that these translations are not used in this part of the code.

As you can see from this screenshot, only one "Monday" string is found. And since this one is translated and the app still doesn't show the translation, it means this translation is not used in that part of the app, right?
![image](https://github.com/mealie-recipes/mealie/assets/69676522/70d722db-ddca-4081-83b4-aa73750764b3)

The translation is, however, used in other parts of the code just fine:
![image](https://github.com/mealie-recipes/mealie/assets/69676522/c739408e-aef4-432b-985c-a929db5b4a17)

**Comment by ghuser238490** [comment]
Yes, that's weird. I can reproduce it on v.1.5.1 and on today's nightly Build
[360b8e21d9ca81785574f6777c02cb9eee81ee9b](https://github.com/mealie-recipes/mealie/commit/360b8e21d9ca81785574f6777c02cb9eee81ee9b)

The same bug on the meal planner page seems to occur in Croatian and Lithuanian language as well, but many other languages like Dutch, Polish or Romanian are fine.
Unfortunately this is where my skills end.

**Comment by michael-genson** [comment]
@Yuni1988 can you confirm this looks correct? We were missing some translation files
![image](https://github.com/mealie-recipes/mealie/assets/71845777/b25099c5-58b5-4bf6-aa79-2bd04339e47c)

**Comment by Yuni1988** [comment]
Yes, this looks correct. :)
