### ISSUE TITLE
[SCRAPER] - www.colruyt.be/nl/lekker-koken recipe scraping returns failed to scrape url

### ISSUE THREAD

**Issue by melsenm** [mealie-recipes/mealie#3524]
### First Check

- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have verified that this issue _is not_ related to the underlying library
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers) by **1)** checking
the [debugger](https://demo.mealie.io/g/home/r/create/debug) and data is returned, **2)**
verifying that there _are_ errors in the log related to application level code, or
**3)** verified that the site provides recipe data, or is otherwise supported by
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers)

- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### Please provide 1-5 example URLs that are having errors

https://www.colruyt.be/nl/lekker-koken/recept/scampi-torpedo-met-chimichurri
https://www.colruyt.be/nl/lekker-koken/recept/one-pot-pasta-met-4-groenten

### Please provide your logs for the Mealie container `docker logs <container-id> > mealie.logs`

INFO     2024-04-27T12:29:09 - HTTP Request: GET https://www.colruyt.be/nl/lekker-koken/recept/scampi-torpedo-met-chimichurri "HTTP/1.1 456 "
ERROR    2024-04-27T12:29:09 - Recipe Scraper was unable to extract a recipe from https://www.colruyt.be/nl/lekker-koken/recept/scampi-torpedo-met-chimichurri
ERROR    2024-04-27T12:29:09 - failed to scrape url during bulk url import https://www.colruyt.be/nl/lekker-koken/recept/scampi-torpedo-met-chimichurri
Traceback (most recent call last):
ERROR    2024-04-27T12:29:09 - 400: {'details': 'BAD_RECIPE_DATA'}
fastapi.exceptions.HTTPException: 400: {'details': 'BAD_RECIPE_DATA'}
    raise HTTPException(status.HTTP_400_BAD_REQUEST, {"details": ParserErrors.BAD_RECIPE_DATA.value})
  File "/app/mealie/services/scraper/scraper.py", line 37, in create_from_url
    recipe, _ = await create_from_url(url, self.translator)
  File "/app/mealie/services/scraper/recipe_bulk_scraper.py", line 88, in _do

### Deployment

Docker (Synology)

**Comment by melsenm** [comment]
2 weeks ago it worked adding recipes from this website

**Comment by ndragon798** [comment]
I think my PR #3526 will fix this. My mealie instance pulled the recipe just fine with the change in place.

**Comment by melsenm** [comment]
The same problem with pages from this website to scrape, example: https://www.colruyt.be/nl/lekker-koken/recept/ovenpannetje-van-kabeljauw

**Comment by EvaBurghoorn** [comment]
![Image](https://github.com/user-attachments/assets/f497101f-72bb-4d6b-8c77-ce6560e5e085)

The problem still occurs
https://www.colruyt.be/nl/recepten/lentepasta-met-veggie-stukjes-en-geroosterde-kerstomaatjes
