### ISSUE TITLE
[BUG] - Startup loop/high CPU usage in Docker with 1.5.1

### ISSUE THREAD

**Issue by runbgp** [mealie-recipes/mealie#3528]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I spun up a new instance of Mealie today to test out Mealie 1.5.1 with Postgres 16.

I had it working for a moment, so I'm not sure if this is a race condition or something else. I cannot get it to work again even if I remove all persistent data.

I start up Mealie & Postgres using Docker Compose, CPU usage skyrockets and from the logs it appears that Mealie is boot looping after attempting to change user, it appears.

### Steps to Reproduce

1. Start up Mealie on a brand new Ubuntu 24.04 VM using Docker Compose. No folders for the volumes exist, this is a fresh startup.

### Please provide relevant logs

`docker-compose logs` after running for 30s~: https://paste.ix0.io/XrZzf4
`docker-compose.yml`: https://paste.ix0.io/xNN6SK

### Mealie Version

1.5.1

### Deployment

Docker (Linux)

### Additional Deployment Details

Ubuntu 24.04 LTS

**Comment by hay-kot** [comment]
I believe you need to add the Postgres database name to the Postgres container so that it’s created on startup. I think it’s ‘POSTGRES_DATABASE’ but you’d have to double check the Postgres docs.

**Comment by boc-the-git** [comment]
You've also got fatal errors in your postgres logs, by the looks:
`FATAL:  role "root" does not exist`

**Comment by runbgp** [comment]
I ended up migrating to using SQLite to remove complexity for now, plus I'm not using local storage. Going to close this out. Thanks!
