### ISSUE TITLE
Unable to delete meal planner item

### ISSUE THREAD

**Issue by pecbeck** [mealie-recipes/mealie#3547]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Added item to meal planner. Can drag drop to another day, however hitting bin icon does not delete item. Tried to replicate on demo, but unable to get side menu, just white space

### Steps to Reproduce

1. Add recipe to Monday
2. Hit bin to delete
3. Nothing happens, just greys out bin

### Please provide relevant logs

None

### Mealie Version

Latest

### Deployment

Docker (Linux)

### Additional Deployment Details

Raspberrypi 4, bookworm

**Comment by pecbeck** [comment]
Further info : works fine using Edge browser on windows 11, however unable to delete using edge on android 14, galaxy tab s9

**Comment by pecbeck** [comment]
Further investigation: appears to work if browser set to mobile site, fails set to desktop site. However, when edge "installs" mealie, and goes full screen, it fails again. Sorry if this is confusing,  but I just don't understand why it works sometimes and not others

**Comment by boc-the-git** [comment]
Anything in the logs? Please be more specific in terms of version, copy the info from 'bug report' at URL/admin/site-settings

**Comment by pecbeck** [comment]
**Details**
Version: v1.5.1
Build: faf716cb7e60b9e31451bdc1caec88e8a78f4db7
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: postgres
Recipe Scraper Version: 14.55.0

**Checks**
Secure Site: No
Server Side Base URL: Yes
LDAP Ready: No
OIDC Ready: No
Email Configured: No

Can you point me at the location for logs please, can find them

![Screenshot_20240506_134328_Edge.jpg](https://github.com/mealie-recipes/mealie/assets/5849839/85b40c69-f9e4-4819-b73c-40feafdec04c)

Here's screenshot from my edge browser on android galaxy tab s9. Hopefully you can see where I clicked the bin, it turns grey and then hangs if I go back to meal planner tab. Works fine on edge on windows 11

**Comment by pecbeck** [comment]
Just tried Demo.mealie.io, same problem from edge on android
![Screenshot_20240506_140329_Edge.jpg](https://github.com/mealie-recipes/mealie/assets/5849839/461e9d6c-4d04-4a8a-b963-c66b485a7166)

**Comment by pecbeck** [comment]
Just successfully deleted meal planner item on android phone using edge, but strangely will not delete using any browser on galaxy tab s9. Latest mealie 1.6.0

**Comment by pecbeck** [comment]
Update: works fine on android Firefox. Edge, chrome and Opera just hang on delete icon

**Comment by pecbeck** [comment]
Seems fixed after last update

**Comment by Kuchenpirat** [comment]
Hey nice to hear. Thanks for coming back to this.

Will close this then
