### ISSUE TITLE
Update mealie to HA documentation example code. 

### ISSUE THREAD

**Issue by Shredder5262** [mealie-recipes/mealie#3556]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

in the documentation page https://docs.mealie.io/documentation/community-guide/home-assistant/ for the example rest api calls listed in home assistant, the existing lines...
value_template: "{{ value_json[0].recipe.name }}" 
value_template: "{{ value_json[0].recipe.id }}" 

work, but produce an error in the home assistant logs. On my own setup, I changed the lines to 

value_template: "{{ value_json[0]['recipe']['name']}}"
value_template: "{{ value_json[0]['recipe']['id']}}"

and so far i get the same result, but no error message in the logs. 

### Steps to Reproduce

1. Create a home assistant rest sensor in Configuration.yaml file 
2. paste the mealie rest api call for todays meal
`#Mealie API Calls
- platform: rest
  resource: "https://[mealieinstance]/api/groups/mealplans/today"
  method: GET
  name: Mealie todays meal
  headers:
    Authorization: Bearer [token]
  value_template: "{{ value_json[0]['recipe']['name']}}"
  force_update: true
  scan_interval: 30
`
`
- platform: rest
  resource: "https://[mealieinstance]/api/groups/mealplans/today"
  method: GET
  name: Mealie todays meal ID
  headers:
    Authorization: Bearer  [token]
  value_template: "{{ value_json[0]['recipe']['id']}}"
  force_update: true
  scan_interval: 30
`
3. Validate the yaml configuration and update/restart
4. you should see the new sensors on the 'states' page that continue to pull in today's meal data
5. Check logs for errors, there should no longer be an error when the rest api command runs. 

### Please provide relevant logs

not applicable.

### Mealie Version

not applicable.

### Deployment

Docker (Windows)

### Additional Deployment Details

not applicable.

**Comment by boc-the-git** [comment]
@Shredder5262 can you please share the error message you're getting in HA, and what version of HA you're running? (I didn't see the actual error message here or in Discord)
I'm running 2024.4.3, and using the syntax you're saying gives errors, but I haven't seen any in my logs.
