### ISSUE TITLE
[BUG] - Fractions of ingredient quantities less than 1 aren't displayed when no unit is selected

### ISSUE THREAD

**Issue by Dalarialus** [mealie-recipes/mealie#3582]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When a recipe contains a fraction of an ingredient that doesn't include a unit (for example, half a red onion), the recipe summary displays "0.5 red onion", rather than the expected "½ red onion"

### Steps to Reproduce

1) Create a recipe
2) Enter as an ingredient "0.5 (no unit) red onion"
3) Save the recipe
4) View the recipe

### Please provide relevant logs

No relevant logs as far as I can tell.

### Mealie Version

Image: ghcr.io/mealie-recipes/mealie
Tag: nightly
Build: efbb571bc2b94ae79c78eb5b083b04914afe5a81

### Deployment

Unraid

**Comment by michael-genson** [comment]
This isn't really a bug, though I agree we should probably default to fractions when we don't have a unit. Whether to show decimals or fractions is decided by the unit, and when there is no unit, we need to pick a default

**Comment by Dalarialus** [comment]
I was torn between reporting it as a bug or a feature request, to be honest!
