### ISSUE TITLE
Cant access after installing docker

### ISSUE THREAD

**Issue by Jagsi1981** [mealie-recipes/mealie#3597]
Hello, 

Iam pretty sure it is my fault bit after hours of googeling I could not find the solution 
I installed docker on a raspberry pi 4 - then the portainer visualization 
and then  I installed mealie - everything looks fine 
![grafik](https://github.com/mealie-recipes/mealie/assets/67981122/85aa7018-6a47-40dd-98c1-2f03603da175)
But I have no idea how to access the mealie site 

I hope someone give me a hint what to do. 

thanks

**Comment by boc-the-git** [comment]
The fact that "published ports" is blank is almost certainly your problem.

Have you created this via docker-compose? What does your compose file look like?
You should be using the one from our docs exactly as is, as a starting point.

You will get the best help for this on Discord (chat is better for this problem), and I'm going to close this now as it doesn't appear to be a bug/issue with Mealie.
