### ISSUE TITLE
[BUG] - Recipe image from another mealie instance

### ISSUE THREAD

**Issue by BhasherBEL** [mealie-recipes/mealie#3599]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

While importing a recipe from another mealie instance, the image of the recipe is the mealie's icon rather than the recipe image.

### Steps to Reproduce

1) copy a public url of a mealie recipe
2) import it on another instance
3) the image isn't the right one

### Please provide relevant logs

-

### Mealie Version

1.6.0

### Deployment

Docker (Linux)

**Comment by boc-the-git** [comment]
This isn't just an issue with the image, it doesn't pull the rest of the info correctly either (description, ingredients, etc). I vaguely recall there is an issue for this already.. 🤔

**Comment by boc-the-git** [comment]
Can't find the existing one.. @michael-genson your thoughts on this? I reckon I've seen your name on the related issue in the past..
Possibly if this is recently fixed it could be that the demo instance is running a version ~3 weeks old?
(I tried importing from the demo into my Prod)

**Comment by michael-genson** [comment]
This PR should have fixed any of those issues: https://github.com/mealie-recipes/mealie/pull/3444

But the demo has this change. Is the information incorrect, or just missing? If it's missing it could just be a public access issue
