### ISSUE TITLE
[BUG] - Improve Random Dinner Selection Feature in Meal Planner

### ISSUE THREAD

**Issue by dandud100** [mealie-recipes/mealie#3647]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I believe this is not a feature request but rather an issue with an essential feature. When I use the Meal Planner to plan a random dinner, it sometimes selects the exact same dish I had yesterday. If I press the button multiple times, it can insert the same dish twice or more in a row. Additionally, I find it inconvenient that it's possible to plan more than one dinner for a day using the random button. It would be better if the button provided a suggestion in a separate box, allowing the user to either regenerate or accept the suggestion. As it stands now, I have to press the button, delete the recipe, and then press the button again, which is not user-friendly.

### Steps to Reproduce

1. Use the random dinner planning feature in the Meal Planner.
2. Observe that sometimes the same dish from the previous day is selected.
3. Press the random button on a few days multiple times and notice that the same dish can be inserted consecutively.

![image](https://github.com/mealie-recipes/mealie/assets/43549788/cda12116-fd8e-42e3-8022-17be8d1a53f6)

### Please provide relevant logs

-

### Mealie Version

nightly
55b91bf84741083d600bb369012fc29f742ba849

### Deployment

Unraid

**Comment by boc-the-git** [comment]
I'm going to close this and suggest this is best as a feature request that will require a fair bit of discussion to get to a robust feature idea. e.g. maybe some people are happy to be told to do the same thing 2 days in a row? This is a big topic I feel, and definitely is not a "bug" that has a relatively clear/quick fix.
(not suggesting this shouldn't be improved, just that it needs proper discussion)
