### ISSUE TITLE
[SCRAPER] - Aldi (Australia)

### ISSUE THREAD

**Issue by RavHilton** [mealie-recipes/mealie#3686]
### First Check

- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have verified that this issue _is not_ related to the underlying library
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers) by **1)** checking
the [debugger](https://demo.mealie.io/g/home/r/create/debug) and data is returned, **2)**
verifying that there _are_ errors in the log related to application level code, or
**3)** verified that the site provides recipe data, or is otherwise supported by
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers)

- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### Please provide 1-5 example URLs that are having errors

https://www.aldi.com.au/recipes/main-meals-recipes/spinach-soup-recipe/
https://www.aldi.com.au/recipes/main-meals-recipes/sausage-and-zucchini-skewers-with-rice-salad-recipe/
https://www.aldi.com.au/recipes/main-meals-recipes/oregano-and-orange-roast-chicken-recipe/
https://www.aldi.com.au/baked-brie-honey-and-walnut-pita-recipe/
https://www.aldi.com.au/recipes/breakfast-recipes/cheesy-oats-with-brussels-sprouts-and-sweet-potato-recipe/

### Please provide your logs for the Mealie container `docker logs <container-id> > mealie.logs`

ERROR    2024-06-03T15:23:41 - Recipe Scraper was unable to extract a recipe from https://www.aldi.com.au/recipes/main-meals-recipes/spinach-soup-recipe/
ERROR    2024-06-03T15:36:43 - Recipe Scraper was unable to extract a recipe from https://www.aldi.com.au/recipes/breakfast-recipes/cheesy-oats-with-brussels-sprouts-and-sweet-potato-recipe/

### Deployment

Docker (Synology)

**Comment by Mraedis** [comment]
hhursev/recipe-scrapers does not scrape any aldi recipes.

**Comment by Kuchenpirat** [comment]
Hey,
Our underlying library (linked on top) does need either a recipe schema to be present or the site has to be manually added. Neither is the case for aldi.com.au. 

So there is not much to be done on the mealie side of things. 

You can open a feature request over at [hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers) but please stick to their template. 

I'll close this as this is not a mealie issue.
