### ISSUE TITLE
Shopping list goes blank as soon as internet connection is lost on iPhone

### ISSUE THREAD

**Issue by bartkummel** [mealie-recipes/mealie#3718]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When I have a shopping list open on my iPhone, it goes blank as soon as the iPhone loses it's internet connection.

### Steps to Reproduce

1. Create a shopping list
2. Open the list on iPhone
3. Set iPhone to airplane mode, be sure to also turn off WiFi
4. Shopping list goes blank

### Please provide relevant logs

```
INFO     2024-06-08T19:33:28 - [172.30.0.1:55372] 200 OK "GET /api/groups/shopping/lists/92893449-4706-4999-bacb-9c74c5b58d85 HTTP/1.1"
INFO     2024-06-08T19:33:23 - [172.30.0.1:55372] 200 OK "GET /api/groups/shopping/lists/92893449-4706-4999-bacb-9c74c5b58d85 HTTP/1.1"
INFO     2024-06-08T19:33:18 - [172.30.0.1:55372] 200 OK "GET /api/groups/shopping/lists/92893449-4706-4999-bacb-9c74c5b58d85 HTTP/1.1"
INFO     2024-06-08T19:33:18 - [172.30.0.1:55374] 200 OK "GET /api/groups/labels?page=1&perPage=-1 HTTP/1.1"
INFO     2024-06-08T19:33:17 - [172.30.0.1:55372] 200 OK "GET /api/groups/shopping/lists?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1"
```
At 19:33 I put my phone on airplane mode. After that, the server just didn't get any requests anymore. There's nothing special to be seen in the server logs as far as I can see.

### Mealie Version

- Docker: `ghcr.io/mealie-recipes/mealie:latest` which comes down to 1.8.0 at the time I write this image.
- Build: [583bd742fb7bbeee0191a6e6601677df57d86a11](https://github.com/mealie-recipes/mealie/commit/583bd742fb7bbeee0191a6e6601677df57d86a11)

### Deployment

Docker (Synology)

### Additional Deployment Details

I used the Postgres Docker compose file.

**Comment by michael-genson** [comment]
The shopping list only works online currently since it constantly polls the server for changes and can't store updates to send when online (it either updates the list or fails). We should probably at least keep the shopping list locally consistent if a refresh fails (instead of disappearing). You wouldn't be able to send any updates to the server, but you could at least see it.

Getting it to work offline (by caching/queueing requests in the browser) is more of a lift, though also reasonable. I know it's been discussed a few times.

**Comment by boc-the-git** [comment]
@michael-genson Should we transition this to (or merge into) a feature request, rather than having here as a bug?

**Comment by michael-genson** [comment]
I'm on the fence, I think it's fair to call the behavior of it going blank a bug
