### ISSUE TITLE
[BUG] - Cannot remove empty ingredient

### ISSUE THREAD

**Issue by AndreiGavriliu** [mealie-recipes/mealie#3746]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Hi,

first of all, thanks for developing this project. It's a lifesaver!

While adding a new step, I accidentally dragged it too far up (into the ingredients list). Now I cannot remove it and there is an empty checkbox in the ingredients list which does not appear when editing.

Cheers,
Andrei

### Steps to Reproduce

1. Create new step (empty)
2. Drag it over to the ingredients
3. Save (empty checkbox should be there)
4. Edit (checkbox is not available to be deleted)

### Please provide relevant logs

Logs do not show any information relevant to this

### Mealie Version

**Details**
Version: v1.8.0
Build: 583bd742fb7bbeee0191a6e6601677df57d86a11
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.56.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
OIDC Ready: No
OpenAI Ready: No
Email Configured: No

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Wow I have no idea why you can drag a step into an ingredient, what a weird bug. FYI in the meantime: if you save the recipe, then refresh the page, you can then remove the empty ingredient.
