### ISSUE TITLE
Comments lost after editing recipe

### ISSUE THREAD

**Issue by cdcastlerock** [mealie-recipes/mealie#3766]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

After editing a recipe comments are lost for that  recipe.

### Steps to Reproduce

1) comment on a recipe
2) edit the recipe and hit save
3) comment is gone

### Please provide relevant logs

[INFO|httptools_impl|L466] 2024-06-21T11:16:24: 10.27.27.43:56042 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-06-21T11:16:24: 10.27.27.43:56042 - "GET /api/recipes?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1718986584408&searchSeed=1718986584408&search=pork&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-06-21T11:16:24: 10.27.27.43:56042 - "GET /api/users/self/ratings HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-06-21T11:16:28: 10.27.27.43:56042 - "GET /api/recipes/pulled-pork HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-06-21T11:16:28: 10.27.27.43:56042 - "GET /api/media/recipes/5b288114-4b5d-461d-b381-4c8570f347a4/images/original.webp?rnd=1&version=https://southernladymagazine.com/wp-content/uploads/2014/08/BBQ429MBS-1024x1024.jpg HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-06-21T11:16:28: 10.27.27.43:56042 - "GET /api/users/self/ratings HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-06-21T11:16:28: 10.27.27.43:56044 - "GET /api/recipes/pulled-pork/comments HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-06-21T11:16:28: 10.27.27.43:56043 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-06-21T11:16:40: 10.27.27.43:56045 - "POST /api/comments HTTP/1.1" 201
[INFO|httptools_impl|L466] 2024-06-21T11:16:46: 10.27.27.43:56046 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-06-21T11:16:50: 127.0.0.1:39372 - "GET /api/app/about HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-06-21T11:16:58: 10.27.27.43:56047 - "PUT /api/recipes/pulled-pork HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-06-21T11:16:58: 10.27.27.43:56047 - "GET /api/recipes/pulled-pork/comments HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-06-21T11:16:58: 10.27.27.43:56049 - "GET /api/users/self/ratings HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-06-21T11:16:58: 10.27.27.43:56048 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200

### Mealie Version

Version: v1.9.0 (also happened with v1.8.0)
Build: d96c36333b9cb9461c5dee96ae28b60d912b38fd

### Deployment

Docker (Linux)

### Additional Deployment Details

my docker compose file:
version: "3.1"
services:
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    restart: always
    ports:
      - 9925:9000
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
      THEME_LIGHT_PRIMARY: 8652C9
      THEME_LIGHT_ACCENT: FF00619
      THEME_DARK_PRIMARY: 8642C9
      THEME_DARK_ACCENT: FF0061
    volumes:
      - /home/curtis/docker/mealie:/app/data

**Comment by Kuchenpirat** [comment]
Hey thanks for raising this too us!

Can confirm that comments seem to disappear after editing a recipe.

Some side note: after adding a comment then editing the comment disappeared. When I did the same again the comment stayed.

**Comment by michael-genson** [comment]
Seems to be a state issue. If you add the comment, then refresh the page, it works fine. But, if you add the comment, then make an edit, the frontend sends an empty list of comments.
