### ISSUE TITLE
[BUG][UX] The name Search for the Recipes tab is misleading

### ISSUE THREAD

**Issue by simgunz** [mealie-recipes/mealie#3815]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

In the left sidebar the most important tab of the application, that is the one containing the recipes, is named "Search". I think that for improving the usability it should be named "Recipes".

I would also remote the string "Results" and the magnifier icon or replace it with the string "Recipes"
Rationale:
- All the other tabs have a name that reflects what they contain: Meal planner, Shopping lists, Timeline
- Search is a functionality of the page, but not the main focus. It would be like calling the mail inbox "Search" because we can search emails
- It always takes me that bit of extra cognitive effort to remember that "Search" is the page containing the recipes

### Steps to Reproduce

---

### Please provide relevant logs

---

### Mealie Version

v1.9.0, d96c36333b9cb9461c5dee96ae28b60d912b38fd

### Deployment

Docker (Linux)

**Comment by boc-the-git** [comment]
These changes make sense to me, though are a bit vague in terms of what exactly you'd change. 
 Would you like to raise the PR @simgunz?

**Comment by simgunz** [comment]
Proposed changes:
- Replace the label "Search" with "Recipes" on the left sidebar
- Replace the icon "Magnifier" with an icon representing recipes
![Screenshot_20240629_111241](https://github.com/mealie-recipes/mealie/assets/466270/edb4a071-b513-4844-a29c-5f990059934a)
- Replace the label "Results" with "Recipes" (or just remove it)
- Replace the icon "Magnifier" with an icon representing recipes (or just remove it)
![Screenshot_20240629_111259](https://github.com/mealie-recipes/mealie/assets/466270/7156196b-8ee8-48e4-98b7-28119e9088f8)


I still need to explore the codebase of mealie, so for now I can't open a PR.

**Comment by boc-the-git** [comment]
Top 2 dot points, agree. 
What the icon would be, I'm not sure (not sure what's available).

Bottom 2 dot points. I think they're of lesser significance. But maybe just changing in the same way as the left sidebar makes sense?

**Comment by boc-the-git** [comment]
I don't expect anyone else will rush to raise a PR for this btw, it's a good candidate for a first contribution.

**Comment by Kuchenpirat** [comment]
I think this is quite a good idea.
With the search symbol in the top right people will also be finding a search if they are looking for one.

@simgunz if you need any help with that feel free to ask around especially in the discord. The actual changes should be pretty trivial.

I feel this is not an outright issue with mealie but more of an improvement, so we might want to convert this into a discussion

**Comment by simgunz** [comment]
I will try to make a PR requests soonish

**Comment by michael-genson** [comment]
For reference, we used to have a different homepage, and the "search" link brought you to what's now the homepage, hence why it is the way it is. Fully agree that it doesn't make sense anymore, though.
