### ISSUE TITLE
[BUG] - Offline shopping list: Offline state not detected

### ISSUE THREAD

**Issue by ghuser238490** [mealie-recipes/mealie#3834]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When turning the device offline after opening a shopping list, the banner 'You are offline - Not all features are available..." is not shown and ticking or editing an item does nothing.
I guess Mealie does not recognize that the device is offline. Tested with different devices and browsers.
I'm aware of the caveats mentioned in https://github.com/mealie-recipes/mealie/pull/3760

It works on all devices on the Mealie demo instance, so it might be an deployment issue.

### Steps to Reproduce

- Device is online
- Open a shopping list
- Turn the device offline
- Tick an item or edit it

### Please provide relevant logs

No errors, only the expected API requests for the shopping list while being online.

### Mealie Version

Version
nightly
Build
[4d6fc9a4c93bb32a3619fe03bc6f8a4b8c01ac2a](https://github.com/mealie-recipes/mealie/commit/4d6fc9a4c93bb32a3619fe03bc6f8a4b8c01ac2a)

### Deployment

Docker (Linux)

### Additional Deployment Details

Running behind Nginx Proxy Manager

**Comment by michael-genson** [comment]
1.10 was bugged, try again in 1.10.1 and see if it works for you

**Comment by ghuser238490** [comment]
Because oft https://github.com/mealie-recipes/mealie/issues/3842 this issue is obsolete, I'll close it.
