### ISSUE TITLE
[BUG] - Creating Shopping List makes Shopping List page unaccessible

### ISSUE THREAD

**Issue by dhc25** [mealie-recipes/mealie#3841]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

[Just installed Mealie - apologies if this is user error.]

Creating a Shopping List causes the Shopping List page to go blank.

When trying to access the Shopping Lists, the page is blank with no content.

It appears that the list that was created is in the database, as Recipes can be added to the Shopping List.

Referring to other similar previous posts, there is 1 user in 1 group (Home).

### Steps to Reproduce

1. Go to Shopping Lists
2. Create new list.

### Please provide relevant logs

Cannot find any error logs

### Mealie Version

**Details**
Version: v1.10.0
Build: 7931e383b2fbeef37d0850607a84e755f949570c
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.57.0

**Checks**
Secure Site: No
Server Side Base URL: No
LDAP Ready: No
OIDC Ready: No
OpenAI Ready: No
Email Configured: No

### Deployment

Docker (Synology)

### Additional Deployment Details

Please advise what further details would help.

**Comment by michael-genson** [comment]
We can't really do anything to help without logs. You should be able to grab them from within Synology

**Comment by michael-genson** [comment]
I just noticed you said you're on version 1.10.0: try upgrading to 1.10.1, there was a bug in 1.10.0 that broke shopping lists

**Comment by michael-genson** [comment]
Going to close this for now. If you haven't already: try updating to the latest version and see if that solves your issue. If not, feel free to re-open
