### ISSUE TITLE
[BUG] - Changes to shopping list items immediately overwritten 

### ISSUE THREAD

**Issue by ollywelch** [mealie-recipes/mealie#3842]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When editing a shopping list, any changes to the items get immediately overwritten. Having checked the server logs no requests are being made other than a periodic GET of the shopping list by ID, i.e. no POST or PUT to update the items. Weirdly I was able to add the first item, but nothing worked after that. Not sure if this is always the case.

https://github.com/mealie-recipes/mealie/assets/56311963/abc2d142-9025-4e24-8234-4359ad7f1a97

### Steps to Reproduce

Create a shopping list, and try and add or update some items.

### Please provide relevant logs

See screen recording :)

### Mealie Version

v1.10.1

### Deployment

Docker (Linux)

### Additional Deployment Details

Docker compose behind nginx proxy manager for reverse proxy

**Comment by michael-genson** [comment]
Can you check your browser logs and see if anything is throwing an error there? (F12 on Chrome)

It's probably related to this: https://github.com/mealie-recipes/mealie/pull/3823

That PR was in the 1.10 release, but it broke shopping lists completely so it was reverted in 1.10.1. https://github.com/mealie-recipes/mealie/pull/3837 _should_ fix any issues related to this, but I haven't gotten browser logs from any user experiencing this issue, so I don't actually know what's causing it.

Alternatively, if you're able, you can try pulling https://github.com/mealie-recipes/mealie/pull/3837 locally and seeing if your issue is resolved.

**Comment by ollywelch** [comment]
I think I've located the issue at these lines in `use-shopping-list-item-actions.ts`:
```
const cutoffDate = new Date(queue.lastUpdate + queueTimeout).toISOString();
if (data.updateAt && data.updateAt > cutoffDate) {
    // If the queue is too far behind the shopping list to reliably do updates, we clear the queue
    clearQueueItems("all");
  } else {
    // We send each bulk request one at a time, since the backend may merge items
    await processQueueItems((items) => api.shopping.items.deleteMany(items), "delete");
    await processQueueItems((items) => api.shopping.items.updateMany(items), "update");
    await processQueueItems((items) => api.shopping.items.createMany(items), "create");
  }
```

My server locale is UTC+1, so updateAt is getting returned in that timezone, but the cutoffDate will always be an hour behind because we're formatting it as an ISO string. I tested my theory and I could make one update after 55 minutes of my last update (accounting for queueTimeout). After that, it was back to the same issue again.

I feel like the solution here is for the API to return timezone-aware responses, or to return everything in UTC. Probably the latter would be more straightforward to implement?

**Comment by ollywelch** [comment]
Just to confirm, changing the TZ env variable of the mealie container to Etc/UTC solved the issue

**Comment by michael-genson** [comment]
Ah hah! Good catch, that must be it. I _thought_ the API always returned UTC (actually I'm pretty sure other parts of the app assume it does) so I'll need to look into that

**Comment by Thoroslives** [comment]
Its odd as this seems to be fixed as above but i am having this exact issue and im on v1.11.0

As per the above i see no POST or PUT in my db only GET

when i look at the console in my browser it just says _Out of sync with server; clearing queue_ regardless of browser used cache cleared or not

I have tried to set my container to Etc/UTC (didnt work) but that wouldnt make sense as my postgres db is in my local timezone. I have ensured both containers are running the same TZ still not working.

**Comment by michael-genson** [comment]
Try deleting that shopping list and using a different one, and/or clearing all of your browser's app data for Mealie.

**Comment by Thoroslives** [comment]
> Try deleting that shopping list and using a different one, and/or clearing all of your browser's app data for Mealie.

Ive done that on multiple devices and browsers. Exact same behaviour

**Comment by michael-genson** [comment]
If you're using the PWA you may need to force it to update. Exactly how depends on what you installed it through

**Comment by Thoroslives** [comment]
> If you're using the PWA you may need to force it to update. Exactly how depends on what you installed it through

This behaviour is on desktop and mobile browser and PWA

**Comment by Thoroslives** [comment]
Ive ended up switching the the sqlite db until i can work this out as it works as it should when using sqlite
