### ISSUE TITLE
[BUG] - Search for Foods does not find chosen ingredient

### ISSUE THREAD

**Issue by PAS-BC** [mealie-recipes/mealie#3845]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I loaded a sample recipe like 'Tuna Mornay', which has 'Tuna' in the list of ingredients. 
Using the 'Food' search function and ticking 'any of - tuna' doesn't show the loaded Tuna Mornay recipe.

### Steps to Reproduce

Open a loaded recipe
Identify a sample food ingredient
Open Search/Food
Choose 'Any-of'
Type the sample ingredient in the Search field
Check if any Recipe is shown with the chosen sample ingredient where that Recipe ingredient list includes the sample ingredient

Result is blank, despite the ingredient being included in a recipe

### Please provide relevant logs

INFO     2024-07-04T23:56:55 - [127.0.0.1:45832] 200 OK "GET /api/app/about HTTP/1.1"

      
      
    

### Mealie Version

**Details**
Version: v1.10.1
Build: d639d168fa7c39ffb802d46ba05e4ec4de33faf9
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: postgres
Recipe Scraper Version: 14.57.0

**Checks**
Secure Site: No
Server Side Base URL: Yes
LDAP Ready: No
OIDC Ready: No
OpenAI Ready: No
Email Configured: Yes

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Did you parse the recipe?

https://docs.mealie.io/documentation/getting-started/faq/#how-do-i-enable-smart-ingredient-handling

**Comment by PAS-BC** [comment]
Thank you, Michael,

That was indeed the problem.

 

I had read the FAQ section about ‘smart ingredient handling’ but did not realise it was a prerequisite to using the ‘Foods’ button under Search.

**Comment by michael-genson** [comment]
Glad to hear you got it sorted!
