### ISSUE TITLE
[BUG] - Importing CopyMeThat does not add image to recipe

### ISSUE THREAD

**Issue by arkansas-coder** [mealie-recipes/mealie#3849]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Importing a CopyMeThat zip file recreates the recipes correctly but does not add the images to them. The 'Images' folder has all the needed images.

### Steps to Reproduce

1) Create html zip file in CopyMeThat
2) Choose Copy Me That Recipe Manager
3) Upload file created in step 1
4) Submit
5) Wait until migration completes
6) View recipe list and note that there are no images displayed

### Please provide relevant logs

Docker log (showing only one recipe, but it is the same for all)

INFO     2024-07-04T16:16:16 - [192.168.0.2:57875] 200 OK "POST /api/groups/migrations HTTP/1.1"
INFO     2024-07-04T16:16:28 - [127.0.0.1:54438] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-04T16:16:31 - [192.168.0.2:57924] 200 OK "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1"
INFO     2024-07-04T16:16:31 - [192.168.0.2:57923] 200 OK "GET /api/organizers/categories?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1"
INFO     2024-07-04T16:16:31 - [192.168.0.2:57922] 200 OK "GET /api/recipes?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1720127790663&searchSeed=1720127790663&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1"
INFO     2024-07-04T16:16:31 - [192.168.0.2:57922] 200 OK "GET /api/users/self/ratings HTTP/1.1"
INFO     2024-07-04T16:16:32 - [192.168.0.2:57922] 404 Not Found "GET /api/media/recipes/4e9768cd-b51c-4870-9bf4-5db351bd37db/images/min-original.webp?rnd=1&version=/tmp/tmpaofnih1j/images/grilled_merguez_patties_with_cabbage_sal_arv1h.jpg HTTP/1.1"

### Mealie Version

**Details**
Version: v1.10.1
Build: d639d168fa7c39ffb802d46ba05e4ec4de33faf9
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: postgres
Recipe Scraper Version: 14.57.0

**Checks**
Secure Site: No
Server Side Base URL: Yes
LDAP Ready: No
OIDC Ready: No
OpenAI Ready: No
Email Configured: No

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Can you provide your CopyMeThat file?

Also, have you checked now? The recipes appear in your instance _before_ the images do, so if you looked at the recipes quickly it may have just not been done yet. Usually takes a minute or two

**Comment by arkansas-coder** [comment]
Attached is a copy of the Copy Me That file.
Thanks for your help
[Copy_Me_That_20240703_694010yvd6g843to.zip](https://github.com/user-attachments/files/16113714/Copy_Me_That_20240703_694010yvd6g843to.zip)

**Comment by michael-genson** [comment]
I imported it into my dev instance and the pictures loaded as expected. Can you try deleting the recipes that were previously created, then re-running the migration? Also be sure that you select the Copy Me That migration (though based on your initial report it sounds like you did).

Also, if you could provide your logs during/after migration that would help.

FYI, you can bulk delete recipes at `https://your-mealie-url/group/data/recipes`

**Comment by arkansas-coder** [comment]
After deleting everything, it loaded without problems. I think that I loaded them twice, and I assumed that deleting the first migration would delete the recipes associated with it as well. 
Thanks for your help

**Comment by michael-genson** [comment]
Glad to hear!
