### ISSUE TITLE
[BUG] - Offline detection of shopping list is broken

### ISSUE THREAD

**Issue by MoritzWeber0** [mealie-recipes/mealie#3859]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When accessing the Shopping list on a Android device (in my case Xiaomi 13t) and then switch to offline mode (turn off Wifi and mobile data), it doesn't recognize it properly. The offline message is only displayed for an short time after a request was initiated. It resets directly to the previous value before the change. I can reproduce it on Firefox and Chrome for Android.

Screen recording: 

https://github.com/mealie-recipes/mealie/assets/23395732/5b0c2def-3bd9-46e8-b2ba-a8efef3828c4

I can not reproduce it when using the desktop version (Linux). If I set the throttling to "Offline", then it all works fine.

### Steps to Reproduce

1. Open the Shopping List
2. Turn off Wifi and mobile data or turn on flight mode
3. It's not possible to modify list items as described above.

### Please provide relevant logs

Console log: [demo.mealie.io-1720262329786.log](https://github.com/user-attachments/files/16115701/demo.mealie.io-1720262329786.log)

Looks like the service worker caches the requests. In offline mode the requests still return 200 OK (from service worker). Screenshot from Network tab:

![image](https://github.com/mealie-recipes/mealie/assets/23395732/df4f3316-1543-4b40-b81f-26f20da3f4ff)

Zipped HAR file (you can extract it and then import the HAR file in the network tab of Chrome): 
[demo.mealie.io.zip](https://github.com/user-attachments/files/16115716/demo.mealie.io.zip)

Might be related to https://github.com/mealie-recipes/mealie/issues/3842.

### Mealie Version

v1.10.2, can also be reproduced with the demo version. 

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Should be fixed by https://github.com/mealie-recipes/mealie/pull/3837

**Comment by boc-the-git** [comment]
Marking as confirmed, based on Michael's comment
