### ISSUE TITLE
[BUG] - PWA manifest file does not load when behind Cloudflare Access, requires crossorigin="use-credentials"

### ISSUE THREAD

**Issue by btoconnor** [mealie-recipes/mealie#3935]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I have my Mealie instance protected by Cloudflare Access.  Because of this, the manifest.json file does not load - I get this error:
```
The FetchEvent for "https://<mydomain>/_nuxt/manifest.900ee46d.json" resulted in a network error response: a redirected response was used for a request whose redirect mode is not "follow".
```
Because of this, I am unable to install the PWA or use any of the features that accompany it.  I confirmed that accessing the site locally (with SSL) does *not* have this issue.

### Steps to Reproduce

1. Host mealie behind Cloudflare Access
2. Load mealie
3. Attempt to load the manifest file.
4. Observe inability to install PWA on Android device.

Hard refreshes seem to work, but loading the page regularly does not.  I was never able to install the PWA on my Android phone.

I was able to fix the issue by specifying `crossorigin: "use-credentials"` in the nuxtjs configuration:

```diff
diff --git a/frontend/nuxt.config.js b/frontend/nuxt.config.js
index 8317ade3..d5fad8ed 100644
--- a/frontend/nuxt.config.js
+++ b/frontend/nuxt.config.js
@@ -356,6 +356,7 @@ export default {
       dir: "auto",
       name: "Mealie",
       short_name: "Mealie",
+      crossorigin: "use-credentials",
       id: "mealie",
       description: "Mealie is a recipe management and meal planning app",
       theme_color: process.env.THEME_LIGHT_PRIMARY || "#E58325",
```

I found this referenced in the code for [nuxt js](https://github.com/nuxt-community/pwa-module/blob/main/src/manifest.ts#L54-L56)

This change attaches `crossorigin="use-credentials"`  to the `<link>` tag that loads the manifest file and resolves my issue.  I am not 1000% sure on what byproducts this would have, if any.

The `use-credentials` option is documented at [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin#use-credentials)

### Please provide relevant logs

From Chrome console:

```
The FetchEvent for "https://<mydomain>/_nuxt/manifest.900ee46d.json" resulted in a network error response: a redirected response was used for a request whose redirect mode is not "follow".
```

### Deployment

Docker (Linux)

### Additional Deployment Details

Mealie latest, docker-compose, protected by Cloudflare Access

**Comment by ekcom** [comment]
I am experiencing the same issue.

**Workaround:**
1. Find latest manifest URL
    1. In the Sources tab of Inspect Element, search for `manifest`
        - The element should look like `<link rel="manifest" href="[...]">`
    3. Copy the href URL that looks like `https://<your-domain>/_nuxt/manifest.<hash>.json`
2. Navigate to the manifest URL

This loads the page through any third-party content blocking. After that, refreshing the page allows the manifest to be accessed, and the PWA can be installed.
