### ISSUE TITLE
[BUG] -  "No recipes match your rules" if you create rule with more than one category of food.

### ISSUE THREAD

**Issue by mpetcuRO** [mealie-recipes/mealie#3945]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Hello, just installed Mealie and looks verry promising for my Home Assistant setup.
I will rely on the random picker for every day so rules are a must.

bug:
If I create a rule in the meal planner with more than one category of meal then the random picker has the error "No recipes match your rules"
This issue can be replicated on the demo mealie website.

feature request:
Add toggle button on rule creation for "allow" or "do not allow" repetitive meals that week/month. (do not repeat the meal until all meals in the selected category/categories where offered)

### Steps to Reproduce

1. go to "Meal Planner" -> "Settings" and create a rule that has more than one category of meal for "dinner" for all days.
2. go to "Meal Planner" -> "Edit" push random on dinner meal.
![Screenshot 2024-07-26 161814](https://github.com/user-attachments/assets/1c83a693-3639-4477-8cab-08fb2448b86b)
![Screenshot 2024-07-26 161855](https://github.com/user-attachments/assets/ef707496-9dcd-4ecf-9072-d145760da6ae)

### Please provide relevant logs

INFO     2024-07-26T16:08:24 - [172.17.0.1:37560] 200 OK "GET /api/recipes?search=&page=1&orderBy=name&orderDirection=asc&perPage=20&_searchSeed=1721999304807 HTTP/1.1"
INFO     2024-07-26T16:08:26 - [172.17.0.1:37560] 200 OK "GET /api/groups/mealplans/rules?page=1&perPage=-1 HTTP/1.1"
INFO     2024-07-26T16:08:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:08:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:08:40 - [127.0.0.1:39894] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:08:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:08:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:09:12 - [127.0.0.1:40035] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:09:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:09:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:09:44 - [127.0.0.1:40176] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:09:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:09:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:10:15 - [127.0.0.1:40317] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:10:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:10:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:10:47 - [127.0.0.1:40455] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:10:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:10:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:11:19 - [127.0.0.1:40588] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:11:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:11:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:11:51 - [127.0.0.1:40746] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:11:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:11:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:12:23 - [127.0.0.1:40884] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:12:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:12:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:12:55 - [127.0.0.1:41029] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:12:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:12:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:13:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:13:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:13:28 - [127.0.0.1:41187] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:13:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:13:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:14:00 - [127.0.0.1:41326] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:14:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:14:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:14:32 - [127.0.0.1:41481] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:14:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:14:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:15:04 - [127.0.0.1:41632] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:15:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:15:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:15:36 - [127.0.0.1:41764] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:15:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:15:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:16:08 - [127.0.0.1:41912] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:16:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:16:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:16:40 - [127.0.0.1:42064] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:16:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:16:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:17:11 - [127.0.0.1:42206] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:17:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:17:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:17:43 - [127.0.0.1:42343] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:17:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:17:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:18:15 - [127.0.0.1:42482] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:18:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:18:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:18:47 - [127.0.0.1:42613] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:18:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:18:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:19:19 - [127.0.0.1:42753] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:19:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:19:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:19:51 - [127.0.0.1:42896] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:19:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:19:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:20:22 - [127.0.0.1:43031] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:20:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:20:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:20:54 - [127.0.0.1:43176] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:20:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:20:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:21:26 - [127.0.0.1:43326] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:21:28 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:21:28 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:21:46 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans?start_date=2024-07-26&end_date=2024-08-02&perPage=-1 HTTP/1.1"
INFO     2024-07-26T16:21:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:21:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:21:58 - [127.0.0.1:43475] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:22:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:22:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:22:30 - [127.0.0.1:43684] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:22:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:22:57 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:23:02 - [127.0.0.1:43923] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-07-26T16:23:04 - [172.17.0.1:41666] 201 Created "POST /api/groups/mealplans/rules HTTP/1.1"
INFO     2024-07-26T16:23:04 - [172.17.0.1:41666] 200 OK "GET /api/groups/mealplans/rules?page=1&perPage=-1 HTTP/1.1"
INFO     2024-07-26T16:23:07 - [172.17.0.1:41666] 200 OK "GET /api/groups/mealplans?page=1&perPage=-1&start_date=2024-07-26&end_date=2024-08-01 HTTP/1.1"
INFO     2024-07-26T16:23:09 - [172.17.0.1:41666] 200 OK "GET /api/recipes?search=&page=1&orderBy=name&orderDirection=asc&perPage=20&_searchSeed=1722000189132 HTTP/1.1"
INFO     2024-07-26T16:23:12 - [172.17.0.1:41666] 404 Not Found "POST /api/groups/mealplans/random HTTP/1.1"
INFO     2024-07-26T16:23:15 - [172.17.0.1:41666] 404 Not Found "POST /api/groups/mealplans/random HTTP/1.1"
INFO     2024-07-26T16:23:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:23:27 - [192.168.9.33:0] 200 OK "GET /api/groups/mealplans/today HTTP/1.1"
INFO     2024-07-26T16:23:34 - [127.0.0.1:44105] 200 OK "GET /api/app/about HTTP/1.1"

### Mealie Version

Mealie Version v1.10.2

### Deployment

Docker (Synology)

**Comment by mpetcuRO** [comment]
No feedback on this issue ?

**Comment by eniyiweb** [comment]
I have the same problem too

**Comment by eniyiweb** [comment]
Any feedback on this issue ?

**Comment by mpetcuRO** [comment]
Apparently now one is using this feature the request did not even pass the triage phase :)
I have somehow bodged it by only adding one category on just one day, creating rules for every day, but this is limiting on the random meals as it only can be one category/day.
With automations HA is recommending a random meal if is not already programed manually in advanced, works but is limiting as my categories are fish, eggs, beef, pork,  etc. so we already know that we will get an eggs recipes on Monday :)

**Comment by hay-kot** [comment]
Pretty sure this is working as designed. These rules require all tags and categories to be present, not just one of them. So in the OPs example I’m guessing they don’t have a recipe that’s tagged with Dinner, Chicken and Fish, which would make sense to me. 

Sorry about the slow responses. Sometimes stuff slips through the cracks.

**Comment by mpetcuRO** [comment]
I do not understand your expression "These rules require all tags and categories to be present"
Do you mean that rules must include all the categories and all the tags ? - in this situation what is the point of them ?
Here is a video on my setup I show that the category and tags are present and can be filtered in search but when you create the rule it just fails to give a random meal.  [VIDEO](https://go.screenpal.com/watch/cZQqIZVSbUe?_gl=1*1cq7h08*_ga*OTk2MTMxNzkyLjE3MjY3NTEzMzU.*_ga_J7G603GGVL*MTcyNjc1MTMzNS4xLjEuMTcyNjc1MjI3NC4wLjAuMA..)

**Comment by hay-kot** [comment]
Every tag or category you select in the rule needs to be present on the recipe if it’s going to match. So with that rule, only recipes that have all 3 categories will match.

**Comment by mpetcuRO** [comment]
ok, got it pretty sure this is not the way any average human will understand the rules matching. Rules only compare what you add there (tags, category) with the recipe.
In this situation you can't do much with them as it defats the purpose of tags and category's, if you want one day to get random meals from different category's you can't (even if you make another rule for same day/meal but different category you get the same error)

**Comment by eniyiweb** [comment]
> ok, got it pretty sure this is not the way any average human will understand the rules matching. Rules only compare what you add there (tags, category) with the recipe. In this situation you can't do much with them as it defats the purpose of tags and category's, if you want one day to get random meals from different category's you can't (even if you make another rule for same day/meal but different category you get the same error)

It doesn't seem very useful in this case.

**Comment by mpetcuRO** [comment]
yes, instead of managing the randomness with rules we have to manage it with labels on every recipe (I'm sure they have a reason for this but is still hard to understand for average users)

I have added a new tag to every meal named "Random" based on that you can make a rule that will check only that tag and get the recipes from multiple categories. You can do other combinations but for every combination you have to add new tag to the recipes, is really not the solution  but I'm sure  the developers will not change the way the rules work for now.

**Comment by eniyiweb** [comment]
> yes, instead of managing the randomness with rules we have to manage it with labels on every recipe (I'm sure they have a reason for this but is still hard to understand for average users)
> 
> I have added a new tag to every meal named "Random" based on that you can make a rule that will check only that tag and get the recipes from multiple categories. You can do other combinations but for every combination you have to add new tag to the recipes, is really not the solution but I'm sure the developers will not change the way the rules work for now.

Thank you, I will try it the way you mentioned until the developers come up with a more understandable solution.

**Comment by eniyiweb** [comment]
> recipes from multiple categories.

I added the "Random" tag to all the recipes as you mentioned, but I still get the error.

![Screenshot_1](https://github.com/user-attachments/assets/da7beda7-0ec8-404b-898c-5632686ef933)

**Comment by mpetcuRO** [comment]
remove the category from the rule, only use the tag.

**Comment by eniyiweb** [comment]
> remove the category from the rule, only use the tag.

Oh, ok. Thank you.

**Comment by michael-genson** [comment]
FYI this behavior is addressed in: https://github.com/mealie-recipes/mealie/pull/4346

While the existing behavior isn't a bug, the new query filter editor will let you control the logic more granularly.
