### ISSUE TITLE
[SCRAPER] - Ingredients not being parsed properly

### ISSUE THREAD

**Issue by msubodh** [mealie-recipes/mealie#3951]
### First Check

- [X] I used the GitHub search to find a similar issue and didn't find it.
- [ ] I have verified that this issue _is not_ related to the underlying library
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers) by **1)** checking
the [debugger](https://demo.mealie.io/g/home/r/create/debug) and data is returned, **2)**
verifying that there _are_ errors in the log related to application level code, or
**3)** verified that the site provides recipe data, or is otherwise supported by
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers)

- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/)

### Please provide 1-5 example URLs that are having errors

https://www.eatingwell.com/recipe/252887/matcha-green-tea-latte/
https://www.eatingwell.com/recipe/267223/walnut-rosemary-crusted-salmon/
Anything on this list: https://www.eatingwell.com/gallery/12952/anti-inflammatory-recipes/

I just installed it but every site I have tried does not work in paring the ingredients. I tried the parser in the settings with the exact text from the site and it parses fine there.

![image](https://github.com/user-attachments/assets/d094f511-2b17-47dc-8029-af5ccd9b8ae9)

### Please provide your logs for the Mealie container `docker logs <container-id> > mealie.logs`

[INFO|_client|L1773] 2024-07-28T14:03:35: HTTP Request: GET https://www.eatingwell.com/thmb/jW0FtLVFBiWRl-lXpqDUUG7Uqqw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/3759276-c1c832eedf454c4493c0b4e28044e3bd.jpg "HTTP/1.1 200 OK"
[INFO|minify|L116] 2024-07-28T14:03:35: original.jpg minified
[INFO|minify|L126] 2024-07-28T14:03:35: Tiny image saved
[INFO|httptools_impl|L466] 2024-07-28T14:03:35: 82.154.163.121:0 - "POST /api/recipes/create-url HTTP/1.1" 201
[INFO|httptools_impl|L466] 2024-07-28T14:03:36: 82.154.163.121:0 - "GET /api/recipes/matcha-green-tea-latte HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-07-28T14:03:36: 82.154.163.121:0 - "GET /api/media/recipes/bbca82b2-0a1f-4fa9-a08a-dd41b42fe4bb/images/original.webp?rnd=1&version=ChWB HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-07-28T14:03:36: 82.154.163.121:0 - "GET /api/users/self/ratings HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-07-28T14:03:36: 82.154.163.121:0 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-07-28T14:03:42: 82.154.163.121:0 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-07-28T14:04:01: 127.0.0.1:51906 - "GET /api/app/about HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-07-28T14:04:13: 82.154.163.121:0 - "GET /api/admin/about/check HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-07-28T14:04:13: 82.154.163.121:0 - "GET /api/admin/about HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-07-28T14:04:32: 127.0.0.1:54622 - "GET /api/app/about HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-07-28T14:05:02: 127.0.0.1:51752 - "GET /api/app/about HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-07-28T14:05:33: 127.0.0.1:49944 - "GET /api/app/about HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-07-28T14:05:39: 82.154.163.121:0 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-07-28T14:05:39: 82.154.163.121:0 - "GET /api/recipes?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1722171938413&searchSeed=1722171938413&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-07-28T14:05:39: 82.154.163.121:0 - "GET /api/users/self/ratings HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-07-28T14:05:39: 82.154.163.121:0 - "GET /api/media/recipes/d9d434de-0a60-4bc1-a778-6f305269bc77/images/min-original.webp?rnd=1&version=x3Bf HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-07-28T14:05:39: 82.154.163.121:0 - "GET /api/media/recipes/bbca82b2-0a1f-4fa9-a08a-dd41b42fe4bb/images/min-original.webp?rnd=1&version=ChWB HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-07-28T14:05:41: 82.154.163.121:0 - "GET /api/recipes/matcha-green-tea-latte HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-07-28T14:05:41: 82.154.163.121:0 - "GET /api/users/self/ratings HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-07-28T14:05:41: 82.154.163.121:0 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-07-28T14:05:46: 82.154.163.121:0 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-07-28T14:06:03: 127.0.0.1:47582 - "GET /api/app/about HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-07-28T14:06:34: 127.0.0.1:40896 - "GET /api/app/about HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-07-28T14:07:04: 127.0.0.1:54020 - "GET /api/app/about HTTP/1.1" 200
[INFO|httptools_impl|L466] 2024-07-28T14:07:35: 127.0.0.1:60122 - "GET /api/app/about HTTP/1.1" 200

### Deployment

Docker (Linux)

**Comment by markhaehnel** [comment]
I see the exact same issue.

Deployment: Docker (Compose, Linux)
Version: 1.11.0 *(same issue on 1.10.1)*
Additional Info: **OpenAI configured**

This issue can be replicated on the demo site (https://demo.mealie.io/, see: https://demo.mealie.io/g/home/r/das-beste-kartoffelgratin)

Import URL: [https://www.chefkoch.de/rezepte/644981165672475/Das-beste-Kartoffelgratin.html](https://www.chefkoch.de/rezepte/644981165672475/Das-beste-Kartoffelgratin.html)

<details>
  <summary>Resulting recipe JSON</summary>

  ```json
  {
    "id": "37ad2dd6-e0aa-44b9-9bce-e09ffd77812e",
    "userId": "195f9f0c-c222-4e68-9b10-037d58efc5c4",
    "groupId": "8f3a7257-f8e0-43c9-b065-6da0171ff4cf",
    "name": "Das beste Kartoffelgratin (1)",
    "slug": "das-beste-kartoffelgratin-1",
    "image": "D8TD",
    "recipeYield": "4 servings",
    "totalTime": "1 Stunde 30 Minuten",
    "prepTime": "30 Minuten",
    "cookTime": null,
    "performTime": "1 Stunde",
    "description": "Entdecke das beste Kartoffelgratin Rezept: Unglaublich cremig, köstlich knusprig und einfach zubereitet. Dieses unwiderstehliche Gericht wird Dich und Deine Gäste begeistern",
    "recipeCategory": [],
    "tags": [],
    "tools": [],
    "rating": null,
    "orgURL": "https://www.chefkoch.de/rezepte/644981165672475/Das-beste-Kartoffelgratin.html",
    "dateAdded": "2024-07-31",
    "dateUpdated": "2024-07-31T14:15:40.096009Z",
    "createdAt": "2024-07-31T14:15:40.100725Z",
    "updateAt": "2024-07-31T14:15:40.100727Z",
    "lastMade": null,
    "recipeIngredient": [
      {
        "quantity": 1,
        "unit": null,
        "food": null,
        "note": "Butter für die Form",
        "isFood": false,
        "disableAmount": true,
        "display": "Butter für die Form",
        "title": null,
        "originalText": null,
        "referenceId": "74bd56f0-5567-4f93-93b4-a97e83982576"
      },
      {
        "quantity": 1,
        "unit": null,
        "food": null,
        "note": "1 Knoblauchzehe(n)",
        "isFood": false,
        "disableAmount": true,
        "display": "1 Knoblauchzehe(n)",
        "title": null,
        "originalText": null,
        "referenceId": "14c8b1bb-2973-4685-8042-d8e5881a0522"
      },
      {
        "quantity": 1,
        "unit": null,
        "food": null,
        "note": "800 g Kartoffeln, festkochende",
        "isFood": false,
        "disableAmount": true,
        "display": "800 g Kartoffeln, festkochende",
        "title": null,
        "originalText": null,
        "referenceId": "3fde9a4f-2ece-426f-84b6-2fddd67d5b41"
      },
      {
        "quantity": 1,
        "unit": null,
        "food": null,
        "note": "250 ml Sahne",
        "isFood": false,
        "disableAmount": true,
        "display": "250 ml Sahne",
        "title": null,
        "originalText": null,
        "referenceId": "771063d4-90e6-45c5-9ec6-c5962c0e4f38"
      },
      {
        "quantity": 1,
        "unit": null,
        "food": null,
        "note": "250 ml Vollmilch",
        "isFood": false,
        "disableAmount": true,
        "display": "250 ml Vollmilch",
        "title": null,
        "originalText": null,
        "referenceId": "db649638-bde9-47aa-b076-1225400cb483"
      },
      {
        "quantity": 1,
        "unit": null,
        "food": null,
        "note": "Kräutersalz und Pfeffer , frisch gemahlen",
        "isFood": false,
        "disableAmount": true,
        "display": "Kräutersalz und Pfeffer , frisch gemahlen",
        "title": null,
        "originalText": null,
        "referenceId": "461d2652-b0b3-4a54-8f19-9c6e69f16d2c"
      },
      {
        "quantity": 1,
        "unit": null,
        "food": null,
        "note": "Muskat , frisch gerieben",
        "isFood": false,
        "disableAmount": true,
        "display": "Muskat , frisch gerieben",
        "title": null,
        "originalText": null,
        "referenceId": "7d7e5a80-f44d-4083-927f-648b6f87fe20"
      },
      {
        "quantity": 1,
        "unit": null,
        "food": null,
        "note": "1 EL Gemüsebrühepulver",
        "isFood": false,
        "disableAmount": true,
        "display": "1 EL Gemüsebrühepulver",
        "title": null,
        "originalText": null,
        "referenceId": "05d1ec4e-7be8-4fd0-90f4-b31cef2d9a55"
      },
      {
        "quantity": 1,
        "unit": null,
        "food": null,
        "note": "n. B. Butterflöckchen",
        "isFood": false,
        "disableAmount": true,
        "display": "n. B. Butterflöckchen",
        "title": null,
        "originalText": null,
        "referenceId": "5468eccc-95c0-482d-9ee3-d9ebaa2eb9d2"
      }
    ],
    "recipeInstructions": [
      {
        "id": "6ca61bbd-7898-4b6c-aa7a-860ba8f4d292",
        "title": "",
        "text": "Eine flache Gratinform mit Butter einfetten. Den Knoblauch schälen. Entweder fein würfeln und in der Form verteilen oder direkt in die Form pressen. Die Kartoffeln schälen und in feine Scheiben schneiden (ich nehme dafür einen Gurkenhobel, das geht am schnellsten).",
        "ingredientReferences": []
      },
      {
        "id": "96ca8106-d7c6-4ea2-9129-9a8b113f1478",
        "title": "",
        "text": "Die Hälfte der Kartoffelscheiben in die Form schichten. Mit Kräutersalz und frisch geriebenem Muskat leicht würzen, anschließend die restlichen Kartoffeln darauf schichten.",
        "ingredientReferences": []
      },
      {
        "id": "5300c3f9-6b6f-4e67-8b35-6d48977023d5",
        "title": "",
        "text": "Die Sahne und die Milch mischen. Mit dem Gemüsebrühepulver, Kräutersalz, Muskat und Pfeffer kräftig würzen. Diese Mischung über die Kartoffeln geben. Butterflöckchen auf dem Gratin verteilen.",
        "ingredientReferences": []
      },
      {
        "id": "67c6b85e-66c7-4633-9b1a-05de798a7767",
        "title": "",
        "text": "Im vorgeheizten Backofen bei 180 °C Ober-/Unterhitze ca. 1 Stunde backen. Heiß servieren.",
        "ingredientReferences": []
      }
    ],
    "nutrition": {
      "calories": "287",
      "fatContent": "14.84",
      "proteinContent": "6.96",
      "carbohydrateContent": "30.50",
      "fiberContent": null,
      "sodiumContent": null,
      "sugarContent": null
    },
    "settings": {
      "public": false,
      "showNutrition": false,
      "showAssets": false,
      "landscapeView": false,
      "disableComments": true,
      "disableAmount": true,
      "locked": false
    },
    "assets": [],
    "notes": [],
    "extras": {},
    "comments": []
  }
  ```
</details>

<details>
  <summary>Logs</summary>

  ```
  INFO     2024-07-31T16:15:38 - HTTP Request: GET https://www.chefkoch.de/rezepte/644981165672475/Das-beste-Kartoffelgratin.html "HTTP/1.1 200 OK"
  INFO     2024-07-31T16:15:39 - Image URL: ['https://img.chefkoch-cdn.de/rezepte/644981165672475/bilder/1501982/crop-960x540/das-beste-kartoffelgratin.jpg']
  INFO     2024-07-31T16:15:39 - HTTP Request: HEAD https://img.chefkoch-cdn.de/rezepte/644981165672475/bilder/1501982/crop-960x540/das-beste-kartoffelgratin.jpg "HTTP/1.1 200 OK"
  INFO     2024-07-31T16:15:39 - HTTP Request: GET https://img.chefkoch-cdn.de/rezepte/644981165672475/bilder/1501982/crop-960x540/das-beste-kartoffelgratin.jpg "HTTP/1.1 200 OK"
  INFO     2024-07-31T16:15:40 - original.jpg minified
  INFO     2024-07-31T16:15:40 - Tiny image saved
  INFO     2024-07-31T16:15:41 - [IP_REDACTED] 201 Created "POST /api/recipes/create-url HTTP/1.1"
  INFO     2024-07-31T16:15:41 - [IP_REDACTED] 200 OK "GET /api/recipes/das-beste-kartoffelgratin-1 HTTP/1.1"
  INFO     2024-07-31T16:15:41 - [IP_REDACTED] 200 OK "GET /api/media/recipes/37ad2dd6-e0aa-44b9-9bce-e09ffd77812e/images/original.webp?rnd=1&version=D8TD HTTP/1.1"
  INFO     2024-07-31T16:15:41 - [IP_REDACTED] 200 OK "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1"
  INFO     2024-07-31T16:15:41 - [IP_REDACTED] 200 OK "GET /api/users/self/ratings HTTP/1.1"
  ```
</details>

**Comment by michael-genson** [comment]
Ingredients are not parsed automatically, you have to click "parse" which is just outside of your screenshot:

![image](https://github.com/user-attachments/assets/4bcdac79-eb12-4841-8733-34083f6d3c32)

**Comment by msubodh** [comment]
Got it. Thanks for pointing that out.
