### ISSUE TITLE
[BUG] - Bulk Import via URL from AllRecipies fails to bring in ingredients

### ISSUE THREAD

**Issue by NP00111** [mealie-recipes/mealie#3952]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I am importing the following list of URLs in bulk and the ingredients are coming as 1 Cup Flour for all.  I updated to the latest release today and same issue.

https://www.allrecipes.com/recipe/23600/worlds-best-lasagna/
https://www.allrecipes.com/recipe/21014/good-old-fashioned-pancakes/
https://www.allrecipes.com/recipe/16895/fluffy-french-toast/
https://www.allrecipes.com/recipe/68532/curried-coconut-chicken/
https://www.allrecipes.com/recipe/25309/seans-falafel-and-cucumber-sauce/
https://www.allrecipes.com/recipe/143809/best-steak-marinade-in-existence/
https://www.allrecipes.com/recipe/22220/creamy-caramel-flan/
https://www.allrecipes.com/recipe/17338/tasty-bbq-corn-on-the-cob/
https://www.allrecipes.com/recipe/12999/spicy-black-bean-vegetable-soup/
https://www.allrecipes.com/recipe/142892/slow-cooker-spicy-black-eyed-peas/
https://www.allrecipes.com/recipe/17066/janets-rich-banana-bread/
https://www.allrecipes.com/recipe/141371/watermelon-cooler-slushy/
https://www.allrecipes.com/recipe/15821/aunt-teens-creamy-chocolate-fudge/
https://www.allrecipes.com/recipe/85452/homemade-black-bean-veggie-burgers/
https://www.allrecipes.com/recipe/19368/chucks-favorite-mac-and-cheese/
https://www.allrecipes.com/recipe/32501/margaritas-on-the-rocks/
https://www.allrecipes.com/recipe/25586/glazed-almond-bundt-cake/
https://www.allrecipes.com/recipe/219109/buffalo-chicken-wing-sauce/
https://www.allrecipes.com/recipe/20669/double-tomato-bruschetta/
https://www.allrecipes.com/recipe/9330/molasses-sugar-cookies/
https://www.allrecipes.com/recipe/228293/curry-stand-chicken-tikka-masala-sauce/
https://www.allrecipes.com/recipe/147103/delicious-egg-salad-for-sandwiches/
https://www.allrecipes.com/recipe/12974/butternut-squash-soup/
https://www.allrecipes.com/recipe/77493/brendas-apple-and-pomegranate-crisp/
https://www.allrecipes.com/recipe/25321/eggplant-parmesan-ii/
https://www.allrecipes.com/recipe/93286/peruvian-aji-sauce/
https://www.allrecipes.com/recipe/138090/aji-de-gallina/
https://www.allrecipes.com/recipe/8372/black-magic-cake/
https://www.allrecipes.com/recipe/17379/coffee-butter-frosting/
https://www.allrecipes.com/recipe/26019/creamy-chocolate-frosting/
https://www.allrecipes.com/recipe/7479/kentucky-butter-cake/
https://www.allrecipes.com/recipe/148793/mrs-baxtons-long-island-iced-tea/
https://www.allrecipes.com/recipe/8887/chicken-marsala/
https://www.allrecipes.com/recipe/46653/taco-seasoning-i/
https://www.allrecipes.com/recipe/12720/grilled-salmon-i/
https://www.allrecipes.com/recipe/64513/rosemary-ranch-chicken-kabobs/
https://www.allrecipes.com/recipe/46822/indian-chicken-curry-ii/
https://www.allrecipes.com/recipe/21353/italian-spaghetti-sauce-with-meatballs/
https://www.allrecipes.com/recipe/213742/meatball-nirvana/
https://www.allrecipes.com/recipe/165987/cosmopolitan-with-grand-marnier/
https://www.allrecipes.com/recipe/231353/grand-marnier-souffle/
https://www.allrecipes.com/recipe/15184/mouth-watering-stuffed-mushrooms/
https://www.allrecipes.com/recipe/214617/baked-beer-can-chicken/
https://www.allrecipes.com/recipe/79470/simple-scones/
https://www.allrecipes.com/recipe/8333/banana-cake-vi/
http://home.xtrodinary.net/g/home/r/chocolate-cupcakes
https://www.allrecipes.com/recipe/157877/vanilla-cupcake/
https://www.allrecipes.com/recipe/98579/barbies-tuna-salad/
https://www.allrecipes.com/recipe/12775/spicy-grilled-shrimp/
https://www.allrecipes.com/recipe/77493/brendas-apple-and-pomegranate-crisp/
https://www.allrecipes.com/recipe/19934/chili-lime-chicken-kabobs/
https://www.allrecipes.com/recipe/24087/restaurant-style-buffalo-chicken-wings/
https://www.allrecipes.com/recipe/14231/guacamole/
https://www.allrecipes.com/recipe/14825/seafood-stuffed-mushrooms/
https://www.allrecipes.com/recipe/143069/super-delicious-zuppa-toscana/
https://www.allrecipes.com/recipe/8669/chicken-cordon-bleu-ii/
https://www.allrecipes.com/recipe/21694/marinated-grilled-shrimp/
https://www.allrecipes.com/recipe/58112/mushrooms-with-a-soy-sauce-glaze/
https://www.allrecipes.com/recipe/12906/chicken-and-corn-chili/
https://www.allrecipes.com/recipe/29704/easy-chinese-corn-soup/
https://www.allrecipes.com/recipe/15747/best-ever-banana-bread/
https://www.allrecipes.com/recipe/219936/spicy-chicken-thai-soup/
https://www.allrecipes.com/recipe/23913/spicy-potatoes-and-scrambled-eggs/
https://www.allrecipes.com/recipe/20144/banana-banana-bread/
https://www.allrecipes.com/recipe/239788/chef-johns-chicken-lettuce-wraps/
https://www.allrecipes.com/recipe/22230/slow-cooker-barbecue-ribs/
https://www.allrecipes.com/recipe/41116/parmesan-broccoli-balls/
https://www.allrecipes.com/recipe/19897/old-fashioned-peach-cobbler/
https://www.allrecipes.com/recipe/45954/roast-sticky-chicken-rotisserie-style/
https://www.allrecipes.com/recipe/10813/best-chocolate-chip-cookies/
https://www.allrecipes.com/recipe/7565/too-much-chocolate-cake/
https://www.allrecipes.com/recipe/143083/fresh-fruit-flan/
https://www.allrecipes.com/recipe/20979/spanish-flan/
https://www.allrecipes.com/recipe/254310/vodka-gimlet/
https://www.allrecipes.com/recipe/25241/vickis-hush-puppies/
https://www.allrecipes.com/recipe/45736/chicken-tikka-masala/
https://www.allrecipes.com/recipe/141017/cilantro-serrano-cream-sauce/
https://www.allrecipes.com/recipe/162839/rigatoni-pasta-with-chorizo/
https://www.allrecipes.com/recipe/78299/boilermaker-tailgate-chili/
https://www.allrecipes.com/recipe/13218/absolutely-ultimate-potato-soup/
https://www.allrecipes.com/recipe/169305/sopapilla-cheesecake-pie/
https://www.allrecipes.com/recipe/7399/tres-leches-milk-cake/
https://www.allrecipes.com/recipe/220126/chef-johns-sausage-shrimp-jambalaya/
https://www.allrecipes.com/recipe/214931/oven-roasted-asparagus/
https://www.allrecipes.com/recipe/237928/chef-johns-chicken-marsala/
https://www.allrecipes.com/recipe/21181/marias-broccoli-rabe/
https://www.allrecipes.com/recipe/191156/restaurant-style-beef-and-broccoli/
https://www.allrecipes.com/recipe/8938/cornish-game-hens-with-garlic-and-rosemary/
https://www.allrecipes.com/recipe/13571/slow-cooker-stuffing/
https://www.allrecipes.com/recipe/25469/asian-barbequed-steak/
https://www.allrecipes.com/recipe/10402/the-best-rolled-sugar-cookies/
https://www.allrecipes.com/recipe/17456/golden-rum-cake/
https://www.allrecipes.com/recipe/221265/chef-johns-homemade-chicken-stock/
https://www.allrecipes.com/recipe/8072/five-flavor-pound-cake-i/
https://www.allrecipes.com/recipe/245056/lobster-risotto/
https://www.allrecipes.com/recipe/19163/luscious-slush-punch/
https://www.allrecipes.com/recipe/162760/fluffy-pancakes/
https://www.allrecipes.com/recipe/24082/easy-vodka-sauce/
https://www.allrecipes.com/recipe/38107/barlows-blackened-catfish/
https://www.allrecipes.com/recipe/39455/marinated-tuna-steak/
https://www.allrecipes.com/recipe/11587/sugar-cookie-icing/
https://www.allrecipes.com/recipe/7542/special-buttercream-frosting/
https://www.allrecipes.com/recipe/10264/oatmeal-raisin-cookies-i/
https://www.allrecipes.com/recipe/8991/curry-kabobs/
https://tastesbetterfromscratch.com/panang-curry/
https://www.homechef.com/meals/roasted-salmon-with-green-onion-ginger-sauce
https://www.allrecipes.com/recipe/219091/chef-johns-mushroom-gravy/
https://www.allrecipes.com/recipe/33252/indian-style-sheekh-kabab/

### Steps to Reproduce

Bulk Import URL - Bulk Add URL - Paste all URLs.   Submit.

### Please provide relevant logs

Latest

### Mealie Version

Version - v1.10.2
Recipe Scraper Version - [14.57.0](https://github.com/hhursev/recipe-scrapers/releases/tag/14.57.0)

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
This was an issue with recipe scrapers, fixed in [14.57.1](https://github.com/hhursev/recipe-scrapers/releases/tag/14.57.1). You'll want to upgrade to nightly or wait for the next release.

FYI: https://github.com/hhursev/recipe-scrapers/pull/1155

**Comment by NP00111** [comment]
Thank you.  I updated to nightly, and all is good.
