### ISSUE TITLE
[BUG] - Umlauts in OpenAPI parser are not handled correctly

### ISSUE THREAD

**Issue by markhaehnel** [mealie-recipes/mealie#3972]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

If you have ingredients containing Umlauts like ä, ö, ü (have not tested with other special characters) the string encoding of the output is wrong. Looks like Unicode.

This happens in the ingredient parser on a recipe and also on the `/admin/parser` page.

![image](https://github.com/user-attachments/assets/af969971-5182-429d-9b48-0866b172e227)

### Steps to Reproduce

1. Use the `OpenAI` parser on `/admin/parser`
2. Put `Kräutersalz` in the input
3. Send it
4. Output is `Kr\u00e4utersalz` but should be `Kräutersalz`

### Please provide relevant logs

Irrelevant but anyway:

```log
INFO     2024-08-01T09:30:43 - [REDACTED_IP] 200 OK "POST /api/parser/ingredient HTTP/1.1"
INFO     2024-08-01T09:30:47 - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
```

### Mealie Version

Mealie: v1.11.0
Docker Image: v1.11.0 (`sha256:8c5ab50c4c7579603982f0428d70dd17302ada358bdc10d41f9fc954d6be96ab`)

### Deployment

Docker (Linux)

**Comment by markhaehnel** [comment]
By the way, I would be happy to fix this myself but i need some directions on where to look.

**Comment by michael-genson** [comment]
Oh yeah I've seen a few unicode-related issues too. I'm not 100% sure where the fix will be, but here's a few places to look at if you want to take a crack at it:

This is where the prompts are; if the OpenAI output is the problem, we might need to add something to the prompts. I doubt it's this though: https://github.com/mealie-recipes/mealie/tree/mealie-next/mealie/services/openai/prompts/recipes

This is where we actually receive the response from OpenAI; we might be decoding it wrong (e.g. decoding in ASCII instead of unicode). We return `response.choices[0].message.content` which is already a string: https://github.com/mealie-recipes/mealie/blob/mealie-next/mealie/services/openai/openai.py#L101-L130

**Comment by markhaehnel** [comment]
Thanks for the directions. I will try take a look at this in the next days!

**Comment by michael-genson** [comment]
No problem. Here's the dev getting started guide if you need it: https://docs.mealie.io/contributors/developers-guide/starting-dev-server/

**Comment by markhaehnel** [comment]
It seems that it's a problem with the OpenAI API responses. They are not consistent. Sometimes there are invisible characters, sometimes encoded wrong or not even valid.

Some people are facing the same issue here:
 - https://community.openai.com/t/api-response-encoding-bug-utf-8-utf-16/622103
 - https://community.openai.com/t/api-does-not-support-utf-8-encoding/98400

I tried changing the model to `gpt-4-turbo` which seems to work correctly with umlauts and other special characters.
`gpt-3.5-turbo` and `gpt-4` seem to be working fine too.

It seems that all GPT4o models including the mini variant have this issue.

**Comment by markhaehnel** [comment]
OpenAI just released [Structured Outputs in the API](https://openai.com/index/introducing-structured-outputs-in-the-api/).

I'm currently on vacation but will try it out next week. Maybe it changes how the output is encoded.

**Comment by michael-genson** [comment]
I'm going to close this since it's not a Mealie issue. I've seen less and less of this as well as OpenAI has improved. Feel free to re-open if you're still seeing it

**Comment by jojo141185** [comment]
Problem still exists on my site (mealie v3.1.2). Tested with GPT-5-mini over openrouter.ai.
Perhaps explicitly .decode('utf-8') the output would resolve the problem.
