### ISSUE TITLE
How to get rid of the warning sign?

### ISSUE THREAD

**Issue by WeT-Klb** [mealie-recipes/mealie#4013]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I use Mealie V1.11.0 on a QNAP-NAS (192.168.1.241) with SQLite. The Mealie setup is done through Container Station - not by Docker compose.
I just can´t find how to deal with the warning sign for secure webpage.
What exactly can I do to avoid that warning? There it is written to deliver the site by localhost.
Where can I define that?
For BASE_URL i use http://xxxxxxxx.dyn-dns.org:9093 - is this correct?
I also can´t use the clipboard - I am always told the browser wouldn´t support the clipboar function (Microsoft Edge on Windows 10).

### Steps to Reproduce

1. Go to settings
2. Watch configuration

### Please provide relevant logs

[mealie.log](https://github.com/user-attachments/files/16568855/mealie.log)

### Mealie Version

**Details**
Version: v1.11.0
Build: a41ad8c6ed968b43e5674ce77785dbdf76f77f57
Anwendungsmodus: Produktivumgebung
Demostatus: Keine Demo
API-Port: 9000
API Dokumentation: Aktiviert
Datenbanktyp: sqlite
Rezept Scraper Version: 15.0.0

**Checks**
Sichere Website: Nein
Serverseitige Basis-URL: Ja
LDAP bereit: Nein
OIDC bereit: Nein
OpenAI bereit: Nein
E-Mail konfiguriert: Ja

### Deployment

Other (please specify below)

### Additional Deployment Details

QNAP-NAS TS 251 with Container Station (Docker handling). Should be similar with Synology.

**Comment by boc-the-git** [comment]
There is nothing in Mealie that can solve this for you.
The solution is to use a reverse proxy to redirect your connection. If you're new to self hosting, I'd suggest doing research on reverse proxies. Commonly used ones are Caddy, Nginx Proxy Manager and Traefik.
