### ISSUE TITLE
[BUG] - Google OIDC not working

### ISSUE THREAD

**Issue by Inervo** [mealie-recipes/mealie#4021]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Hi,
Just tried to integrate mealie with Google OIDC. Configured everything.
When trying to connect through google, i'm sent to google oidc to select my account (expected), I select the account, give consent, i'm sent back to Mealie login page... and nothing append! 
Am I missing something, or is Google OIDC not compatible (I don't find any example or discussion regarding Google OIDC)

### Steps to Reproduce

1) Configure Mealie with Google OIDC parameters
2) Try to connect with your google account to Mealie
3) Connection to google okay, you're being sent back to Mealie login page, and nothing happens

### Please provide relevant logs

INFO     2024-08-12T10:09:43 - [192.168.13.254:0] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-08-12T10:09:49 - [192.168.13.254:0] 307 Temporary Redirect "GET /login?state=vUB9LfQ1wn&code=4%2F0AcvDMrA4_eOeiXXXXXXXCBV6A8tnRoGV9zSSTubG88yMhTUh77aqeynMVO8aJ3HyPm8w&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+openid&authuser=0&prompt=none HTTP/1.1"
INFO     2024-08-12T10:09:49 - [192.168.13.254:0] 200 OK "GET /login/?state=vUB9LfQ1wn&code=4%2F0AcvDMrA4_eOeiO4IXXXXXT2CBV6A8tnRoGV9zSSTubG88yMhTUh77aqeynMVO8aJ3HyPm8w&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+openid&authuser=0&prompt=none HTTP/1.1"
INFO     2024-08-12T10:09:49 - [192.168.13.254:0] 200 OK "GET /api/app/about/startup-info HTTP/1.1"
INFO     2024-08-12T10:09:49 - [192.168.13.254:0] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-08-12T10:09:49 - [192.168.13.254:0] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-08-12T10:09:51 - [192.168.13.254:0] 304 Not Modified "GET /sw.js HTTP/1.1"

### Mealie Version

Latest

### Deployment

Docker (Synology)

**Comment by cmintey** [comment]
Historically, it has not been possible to use Google OIDC due to a limitation. See https://github.com/mealie-recipes/mealie/discussions/3477 and https://github.com/mealie-recipes/mealie/discussions/3805.

However, you seem to have gotten past the consent page so maybe it is possible again. Can you please share your environment variables (with sensitive info redacted).

Also, can you add `LOG_LEVEL=DEBUG` to your environment variables and try again and show the output to help diagnose?

**Comment by Inervo** [comment]
Thanks for getting back to me :)

Just tried again today: I can't get to the consent page anymore.. After selecting the google account, I go straight back to Mealie login page..

**Comment by mcmasterp** [comment]
I setup google as oidc and I have the described results. As near as I can tell as long as the login page is in the list of redirects in the google api settings it will get to the consent screen. but as stated it then just redirects to the login page on confirmation.  would love to see this work
