### ISSUE TITLE
[BUG] - docker image pyproject.toml shows wrong version of mealie?

### ISSUE THREAD

**Issue by williamkray** [mealie-recipes/mealie#4026]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

unsure what the impact of this is, but the pyproject.toml file inside the docker container image for v1.11.0 shows the wrong version of mealie despite the file having been updated in git.

### Steps to Reproduce

confirm mealie version with `docker compose ps | grep mealie`, then compare that to the version string in the container with `docker compose exec mealie head /app/pyproject.toml`

### Please provide relevant logs

```
$ docker compose ps | grep mealie
apps-mealie-1                   ghcr.io/mealie-recipes/mealie:v1.11.0                                                                                  "/app/run.sh"            mealie                   3 days ago          Up 3 days (healthy)    9000/tcp
apps-mealiepsql-1               postgres:15                                                                                                            "docker-entrypoint.s…"   mealiepsql               3 days ago          Up 3 days (healthy)    5432/tcp
```

```
$ docker compose exec mealie head /app/pyproject.toml
[tool.poetry]
authors = ["Hayden <hay-kot@pm.me>"]
description = "A Recipe Manager"
license = "AGPL"
name = "mealie"
version = "1.10.1"

[tool.poetry.scripts]
start = "mealie.app:main"

```

### Mealie Version

docker: ghcr.io/mealie-recipes/mealie:v1.11.0

![image](https://github.com/user-attachments/assets/40fe3402-26c3-45db-bbe6-b1c347c0c6f3)

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Yeah that checks out. This actually [used to be totally broken](https://github.com/mealie-recipes/mealie/pull/3840) (it was set to 1.0.0b and never updated). Due to how we do releases it will always be slightly behind. Nightly will be correct, though

> unsure what the impact of this is

Technically none, though kind of annoying. @boc-the-git not sure if you have any fancy ideas on how to bump the version in the release workflow

**Comment by michael-genson** [comment]
Also an issue in `frontend\package.json`

**Comment by michael-genson** [comment]
Oh wait just kidding it's[ supposed to be doing this in our release workflow](https://github.com/mealie-recipes/mealie/blob/mealie-next/.github/workflows/release.yml). Well now I'm mildly confused

**Comment by boc-the-git** [comment]
> Oh wait just kidding it's[ supposed to be doing this in our release workflow](https://github.com/mealie-recipes/mealie/blob/mealie-next/.github/workflows/release.yml). Well now I'm mildly confused

If you're referring to this https://github.com/mealie-recipes/mealie/blob/mealie-next/.github/workflows/release.yml#L71, that's raising the pull request to update it in the repo, not actually updating it for the image that gets built.

In theory [this](https://github.com/mealie-recipes/mealie/blob/mealie-next/.github/workflows/partial-builder.yml#L38-L40) should be updating it for the built image, in init.py.. I haven't verified if that's working.
We could do much the same in pyproject.toml

**Comment by michael-genson** [comment]
Not sure when, but this was fixed
