### ISSUE TITLE
[BUG] - Profile image from iPhone is rotated incorrectly

### ISSUE THREAD

**Issue by pjbosco** [mealie-recipes/mealie#4035]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Adding a profile picture from an iPhone results in a 90 degree rotated profile picture. This does not match what is displayed in the iPhone. It is not clear how or why the rotation is being introduced.

### Steps to Reproduce

1) Go to profile
2) Under picture, click upload
3) Browse pictures on iPhone and choose one
4) Submit

### Please provide relevant logs

N/A

### Mealie Version

**Details**
Version: v1.11.0
Build: a41ad8c6ed968b43e5674ce77785dbdf76f77f57
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 15.0.0

**Checks**
Secure Site: No
Server Side Base URL: No
LDAP Ready: No
OIDC Ready: No
OpenAI Ready: No
Email Configured: No

### Deployment

Docker (Linux)

### Additional Deployment Details

N/A

**Comment by JonathanPitre** [comment]
Same issue on iPad OS.
