### ISSUE TITLE
[BUG] - Gmail Not Working [ERROR|admin_email|L32]

### ISSUE THREAD

**Issue by broyuken** [mealie-recipes/mealie#4040]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I am using the home assistant addon by alexbelgium for this, and have most things working. I have defined my email variables in config.yaml and have themes, LDAP and most of email working. For some reason, it doesn't look like the SMTP_USER and SMTP_PASSWORD fields are getting imported into my config. 

```
# Email Configuration
SMTP_HOST: smtp.gmail.com
SMTP_PORT: 465
SMTP_FROM_NAME: xxxxxxx@gmail.com
SMTP_AUTH_STRATEGY: TLS
SMTP_FROM_EMAIL: xxxxxxx@gmail.com
SMTP_USER: xxxxxxx@gmail.com
SMTP_PASSWORD: secret gmail app password
```

### Steps to Reproduce

Configure SMTP settings as per above
Go to site settings, test email
See failed message

### Please provide relevant logs

This is the only thing that shows in my logs when I tail the mealie.log file while I test the email.

[ERROR|admin_email|L32] 2024-08-15T14:49:47: Connection unexpectedly closed
[INFO|httptools_impl|L466] 2024-08-15T14:49:47: 10.0.86.92:0 - "POST /api/admin/email HTTP/1.1" 200

When I go in and look at my mealie.log file while it's starting up, I see the following. It looks like it loads up all the variables from my config.yaml directory except for the SMTP_USER and SMTP_PASSWORD variables. 

[INFO|app|L62] 2024-08-15T14:49:03: {
    "theme": {
        "light_primary": "a569bd",
        "light_accent": "#007A99",
        "light_secondary": "#973542",
        "light_success": "#43A047",
        "light_info": "#1976D2",
        "light_warning": "#FF6D00",
        "light_error": "#EF5350",
        "dark_primary": "a569bd",
        "dark_accent": "#007A99",
        "dark_secondary": "#973542",
        "dark_success": "#43A047",
        "dark_info": "#1976D2",
        "dark_warning": "#FF6D00",
        "dark_error": "#EF5350"
    },
    "PRODUCTION": true,
    "BASE_URL": "mealie.yyyyyyyyyy.com",
    "STATIC_FILES": "/spa/static",
    "IS_DEMO": false,
    "HOST_IP": "*",
    "API_HOST": "0.0.0.0",
    "API_PORT": 9000,
    "API_DOCS": true,
    "TOKEN_TIME": 48,
    "LOG_CONFIG_OVERRIDE": null,
    "LOG_LEVEL": "debug",
    "GIT_COMMIT_HASH": "7820ddc8f72e559b5c9b03e9be3567251f6b5b0c",
    "ALLOW_SIGNUP": false,
    "DAILY_SCHEDULE_TIME": "23:45",
    "SECURITY_MAX_LOGIN_ATTEMPTS": 5,
    "SECURITY_USER_LOCKOUT_TIME": 24,
    "DB_ENGINE": "sqlite",
    "DEFAULT_GROUP": "Home",
    "SMTP_HOST": "smtp.gmail.com",
    "SMTP_PORT": "465",
    "SMTP_FROM_NAME": "xxxxxxxxxx@gmail.com",
    "SMTP_FROM_EMAIL": "xxxxxxxxxx@gmail.com",
    "SMTP_AUTH_STRATEGY": "TLS",
    "LDAP_AUTH_ENABLED": true,

### Mealie Version

nightly

7820ddc8f72e559b5c9b03e9be3567251f6b5b0c

### Deployment

Other (please specify below)

### Additional Deployment Details

Home Assistant Addon
https://github.com/alexbelgium/hassio-addons/tree/master/mealie

**Comment by michael-genson** [comment]
Can you confirm your SMTP credentials are working outside of Mealie? Gmail has locked down SMTP a lot in recent years, you have to adjust some account settings to get it to work.

> It looks like it loads up all the variables from my config.yaml directory except for the SMTP_USER and SMTP_PASSWORD variables

They're not logged for security reasons

**Comment by broyuken** [comment]
But LDAP bind credentials are?

**Comment by broyuken** [comment]
Also I use the same account with a number of different SMTP providers with the same settings, ports, etc, just a different app password.

**Comment by broyuken** [comment]
I just figured it out. I had to set it to SSL, not TLS and now it works.

**Comment by ameuret** [comment]
> I just figured it out. I had to set it to SSL, not TLS and now it works.

Huh sorry to follow up on this but I'm facing the same situation and I'm wondering why I don't see the Exception message in the log (`LOG_LEVEL: "debug"`).

And most of all, why would SSL work with gmail and not TLS?

**Comment by nguyenhu95** [comment]
> > I just figured it out. I had to set it to SSL, not TLS and now it works.
> 
> Huh sorry to follow up on this but I'm facing the same situation and I'm wondering why I don't see the Exception message in the log (`LOG_LEVEL: "debug"`).
> 
> And most of all, why would SSL work with gmail and not TLS?

It’s because STMP port was set to 465 by OP, I think. If it’s port 587, it’s TLS
https://postmarkapp.com/blog/choosing-the-right-smtp-port#smtp-port-465-a-deprecated-port-you-should-no-longer-use

**Comment by ameuret** [comment]
> It’s because STMP port was set to 465 by OP, I think. If it’s port 587, it’s TLS

Thx ! True, I realized he was trying TLS on 465. Which is not my issue. Still haven't found why I don't get any error message in the logs...
