### ISSUE TITLE
[BUG] - translation has no effect at import for number of servings

### ISSUE THREAD

**Issue by cameo77** [mealie-recipes/mealie#4046]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I use my Mealie UI in German language and I usually import German recipes. At a recipe import from a website, Mealie imports also the number of servings. In the field, where this number is placed in, there is automatically added a "unit". So if I would use an English UI, the text field should contain, e.g. "6 servings". But in German, there should be written "6 Portionen" (in this example). But although my Mealie UI and the recipe is in German, there is still written "6 servings". Here you can see a screenshot:
![image](https://github.com/user-attachments/assets/55a9b07d-b9ac-48f0-9c81-2154481c7fb5)
The yellow marked "servings" should be named "Portionen".
I had a similiar issue with the cooking time units, but I was able to fix this with Crowdin. But in this case, there is no translation error in Crowdin. It seems to be an error in Mealie, because if I use the recipe import debugger, only the number can be found in the json, so looks like Mealie adds this "unit" automatically. Maybe this "servings" word is hard coded and not related to the translation files.

### Steps to Reproduce

Just import a German recipe, in a German Mealie UI (maybe it's the same for other non-English languages). 
For example, use [this](https://www.gutekueche.at/moussaka-rezept-347) recipe.

### Please provide relevant logs

--

### Mealie Version

v1.11.0
Build: a41ad8c6ed968b43e5674ce77785dbdf76f77f57

### Deployment

Docker (Linux)

**Comment by mhoenes** [comment]
This was already reported in https://github.com/mealie-recipes/mealie/issues/2807, but couldn't be fixed.

"servings" is added by the underlying scraper library automatically to the yield when a recipe doesn't specify a serving unit text.
It's done here in the recipe scraper code: https://github.com/hhursev/recipe-scrapers/blob/ad7377dcea6ffd1272f3fafbe3e396a3c55529cc/recipe_scrapers/_utils.py#L227
