### ISSUE TITLE
[BUG] - Themeing not picking up defined environments for hex colors

### ISSUE THREAD

**Issue by samschultzponsys** [mealie-recipes/mealie#4107]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Defined hex color for theming not applying

### Steps to Reproduce

Entering these lines in my env config with my other working environment variables does not allow the color to change:

 THEME_LIGHT_PRIMARY: "#60249c"
 THEME_DARK_PRIMARY: "#60249c"

### Please provide relevant logs

No relevant logs.

### Mealie Version

Docker   image: ghcr.io/mealie-recipes/mealie:latest 1.7 I believe it has the OpenAI integration setup and working.

### Deployment

Docker (Linux), Unraid

### Additional Deployment Details

Utilizing docker compose on Unraid.

**Comment by boc-the-git** [comment]
Please share your docker logs @samschultzponsys, only redacting sensitive info.
Also your docker-compose file.

**Comment by death2all110** [comment]
@samschultzponsys 

Can you verify the version of Mealie you're running? I am on 1.12(the latest) running through unraid docker and cannot reproduce. Maybe its a cache issue?

**Comment by samschultzponsys** [comment]
I will update my compose file and logs shortly but here is my config pages for version info etc.

**Comment by samschultzponsys** [comment]
![Screenshot_20240828_203413_Chrome](https://github.com/user-attachments/assets/596ba15a-f360-480d-9c2b-6248b1d5e825)
![Screenshot_20240828_203424_Chrome](https://github.com/user-attachments/assets/11144c9a-6f3d-45e3-bd72-05387e2982b3)

**Comment by samschultzponsys** [comment]
So weird twist, I pulled up mealie on a new device and it's purple...
![20240828_204638](https://github.com/user-attachments/assets/28409ac8-dc03-4d22-ac71-4d05e30682d1)

**Comment by samschultzponsys** [comment]
Confirmed this seems to be a cookie issue or something as private browsing is picking up the theme change. I am closing this case sorry to have wasted your time.
