### ISSUE TITLE
[BUG] - Error sending email, no logs

### ISSUE THREAD

**Issue by atxbyea** [mealie-recipes/mealie#4109]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Added email settings as environment variables in docker compose file, see those same variables populated on startup, however no email is ever tried sent, running protonmail bridge locally, other services (nextcloud, cron,bacula etc) sending emails fine.
errors out with "Error Sending Email" the second you press "send" in the webui, but no error log in mealie docker logs, and can't see any attempted authentication in protonmail bridge.

### Steps to Reproduce

add variables to compose
try to send email
cry a lot

### Please provide relevant logs

docker logs on startup
`    "SMTP_HOST": "192.168.1.11",
    "SMTP_PORT": "1025",
    "SMTP_FROM_NAME": "services@domain.com",
    "SMTP_FROM_EMAIL": "services@domain.com",
    "SMTP_AUTH_STRATEGY": "TLS",
`

docker logs when sending
`INFO     2024-08-27T13:36:10 - [2a01:7] 201 Created "POST /api/groups/invitations HTTP/1.1"
INFO     2024-08-27T13:36:15 - [2a01:7] 200 OK "POST /api/groups/invitations/email HTTP/1.1"
`

protonmail bridge logs

``

### Mealie Version

/admin/site-settings just sends me to the recipies, is this an old URL scheme ?

running :latest which is 1.12 currently

### Deployment

Docker (Linux)

**Comment by boc-the-git** [comment]
> /admin/site-settings just sends me to the recipies, is this an old URL scheme ?

No, you must not be an admin.

**Comment by atxbyea** [comment]
Interesting, I've tried logging in with the `changeme@email.com` and `changeme@example.org` to no avail, and I can only see my own user and my wifes user in the members context, is there any way to verify the admin users \ change password of it ?

**Comment by boc-the-git** [comment]
The defaults are:

```
Username: changeme@example.com

Password: MyPassword
```

Modifying the database would be the way to change it if nothing else works.

**Comment by atxbyea** [comment]
Yeah. no go with any password I can think of, this is an old installation that was setup originally with the omni-image, which is why I also tried the `@email.com` domain

**Comment by atxbyea** [comment]
reset the password with the python script, and got in with the admin user

just says 

`
Email Configuration Status
Not Ready - Check Environmental Variables 
`

**Comment by atxbyea** [comment]
just noticed that I had `SMTP_PASS` instead of `SMTP_PASSWORD` but no change in behavior, interesting when an application accept bogus variables :-D

**Comment by atxbyea** [comment]
SMTP_HOST: 192.168.1.11
        SMTP_PORT: 1025
        SMTP_FROM_NAME: services@domain.com
        SMTP_FROM_EMAIL: services@domain.com
        SMTP_AUTH_STRATEGY: TLS
        SMTP_USER: user@protonmail.com
        SMTP_PASSWORD: lOngStrngPassword

**Comment by atxbyea** [comment]
> just noticed that I had `SMTP_PASS` instead of `SMTP_PASSWORD` but no change in behavior, interesting when an application accept bogus variables :-D

Never mind, it did fix it, forgot to recreate the container, just did a restart.

**Comment by atxbyea** [comment]
All working :-)
