### ISSUE TITLE
Mealie Azure OpenAI bad connection url

### ISSUE THREAD

**Issue by AntoineBriseboisRoy** [mealie-recipes/mealie#4119]
I would like to use this feature, but I want to use Azure openAI resource since I have credits with work. I tried to use it, however, for it to work in azure, we need to specify the api version as a query params:
https://domainname.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2023-03-15-preview

However, when I look at your code, you take the full given url and append /chat/completions at the end. This ends up with a call to:
https://domainname.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2023-03-15-preview/chat/completions which for obvious reasons, doesn't work.

Would there be a way to specify, in environment variables, the api-version used? so that you can append it at the end without us having to go play in py files (we're not all software developers ;) )

_Originally posted by @AntoineBriseboisRoy in https://github.com/mealie-recipes/mealie/discussions/1588#discussioncomment-10474879_

**Comment by AntoineBriseboisRoy** [comment]
Do we have any status on this?

**Comment by AntoineBriseboisRoy** [comment]
I reviewed what you did and it is exactly what we needed! Also, the debug tab is very very useful. (Nice code btw ;) )

Thank you!

**Comment by TyzzyT** [comment]
@AntoineBriseboisRoy I'm sorry for bothering you, but I'm having issues setting up the Azure OpenAI integration in Mealie. 
I'm not sure what I'm doing wrong here or what is missing. I added a gpt-4o deployment in Azure OpenAI Studio in the resource group Mealie and copied the Target URI + Key from the Deployments page.

Config is as follows:

```
- OPENAI_BASE_URL=https://mealie.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2024-08-01-preview
- OPENAI_API_KEY=REDACTED
- OPENAI_WORKERS=1
```
But it's not working and when using the OpenAI debug page I get:
`OpenAI request failed. Full error has been logged. Exception: "OpenAI Request Failed. NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}"`

When testing this URL & API-key in Postman, it is working. Can you please help me?

**Comment by AntoineBriseboisRoy** [comment]
Your base URL should only be `https://mealie.openai.azure.com/openai/deployments/gpt-4o/`. Also, you need to include headers and params. See my config:

```
      OPENAI_BASE_URL: https://mealie-openai.openai.azure.com/openai/deployments/gpt-4o-mealie/
      OPENAI_CUSTOM_PARAMS: '{"api-version":"2023-03-15-preview"}'
      OPENAI_CUSTOM_HEADERS: '{"api-key":"YOU_API_KEY"}'
      OPENAI_API_KEY: YOUR_API_KEY
```


It is probably not necessary to put both api keys, but I do it because why not ;)

**Comment by TyzzyT** [comment]
It is working, thank you very much! 🎉
