### ISSUE TITLE
Lost my user credentials, can't access database

### ISSUE THREAD

**Issue by amca01** [mealie-recipes/mealie#4123]
Hello,

I recently had some issues with my VPS, which required a reboot; also I've been tinkering with my caddy setup (for reverse proxy).

When I try to log in to mealie now, it claims that this appears to be a first login, and gives me the standard "changeme@example.com/MyPassword" credentials.

As far as I can see, the database is still there, and I've moved it to a local directory with a docker bind mount.

Can I import the database into a new user?  I don't want to have to recreate all my recipes from scratch - there are too many of them.  I'm no database expert (I'm no database anything really), but I don't mind using sqlite command line tools to manage the database, if that's a possibility.

Anyway, I'd like to have my old user credentials again, and with the current database.  Happy to take advice!

(I hope all this makes sense.)

Thank you very much,
Alasdair

**Comment by michael-genson** [comment]
You can change your password from the command line: https://docs.mealie.io/documentation/getting-started/faq/#how-can-i-change-my-password

**Comment by amca01** [comment]
Many thanks for pointing that out.  However, I can't extract any recipes from the database.  Exploring it seems to indicate that it consists entirely of tables and schemas, but no data.

Maybe I will have to create all my recipes from scratch again, and this time be cleverer about backups - actually do them!
