### ISSUE TITLE
[BUG] - PWA: screen changes orientation although the phone screen is locked to portrait mode

### ISSUE THREAD

**Issue by tomgehrmann** [mealie-recipes/mealie#4136]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

The screen orientation of the PWA changes although the screen is locked.

**Proposed solution** (untested):
Change [orientation in manifest](https://github.com/mealie-recipes/mealie/blob/9acf9ec27c5595baed197c35900cd83f1375cdbd/frontend/nuxt.config.js#L495) to default (by removing the field).

**Reference**:
- [W3C Web Application Manifest](https://w3c.github.io/manifest/#orientation-member)
- [W3C Screen Orientation](https://www.w3.org/TR/screen-orientation/#dfn-default-screen-orientation)

### Steps to Reproduce

**App**: Brave Android 1.69.153, Chromium 128.0.6613.85
**OS**: Android 12

1. Set phone to Portrait/Locked Mode
2. Open Mealie Website (e.g. [Mealie Demo](https://demo.mealie.io))
3. Add to Start Menu
4. Install
5. Open Mealie PWA
6. Rotate phone

### Please provide relevant logs

_None_

### Mealie Version

mealie:v1.11.0, Build [a41ad8c6ed968b43e5674ce77785dbdf76f77f57](https://github.com/mealie-recipes/mealie/commit/a41ad8c6ed968b43e5674ce77785dbdf76f77f57)
Also current demo version

### Deployment

Docker (Linux)

**Comment by boc-the-git** [comment]
@Choromanski do you have any view on this?

**Comment by Choromanski** [comment]
> @Choromanski do you have any view on this?

I will work on a solution and test it.

**Comment by Choromanski** [comment]
Bug is addressed in #4143
