### ISSUE TITLE
[BUG] - Shopping list item transfer button does nothing

### ISSUE THREAD

**Issue by BlackHoleFox** [mealie-recipes/mealie#4152]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When trying to transfer an item from one shopping list to another, the transfer action/button in the UI doesn't do anything.

### Steps to Reproduce

1. Create two shopping lists in your mealie example instance
2. Add `foobar` item to the first list
3. Click the tile on the right of this new shopping list item
4. Click `Transfer`
5. No model, popup, etc appears and the item is not transferred despite other list candidates existing. 

### Please provide relevant logs

I checked the Docker logs but I don't see any errors or warnings. There are no browser console logs either after trying to use the `Transfer` button.

I don't see any network requests being made when I click this button either so I think its a frontend problem that wouldn't be logged.
```
INFO     2024-09-04T01:49:19 - [192.168.65.1:43082] 200 OK "GET /api/groups/shopping/lists/e33cd1e3-8aac-4bc9-88fb-4d4ab4a0f01d HTTP/1.1"
INFO     2024-09-04T01:49:24 - [192.168.65.1:23024] 200 OK "GET /api/groups/shopping/lists/e33cd1e3-8aac-4bc9-88fb-4d4ab4a0f01d HTTP/1.1"
INFO     2024-09-04T01:49:29 - [192.168.65.1:23024] 200 OK "GET /api/groups/shopping/lists/e33cd1e3-8aac-4bc9-88fb-4d4ab4a0f01d HTTP/1.1"
INFO     2024-09-04T01:49:34 - [192.168.65.1:23024] 200 OK "GET /api/groups/shopping/lists/e33cd1e3-8aac-4bc9-88fb-4d4ab4a0f01d HTTP/1.1"
INFO     2024-09-04T01:49:39 - [192.168.65.1:23024] 200 OK "GET /api/groups/shopping/lists/e33cd1e3-8aac-4bc9-88fb-4d4ab4a0f01d HTTP/1.1"
INFO     2024-09-04T01:49:42 - [127.0.0.1:56454] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-09-04T01:49:44 - [192.168.65.1:23024] 200 OK "GET /api/groups/shopping/lists/e33cd1e3-8aac-4bc9-88fb-4d4ab4a0f01d HTTP/1.1"
```

### Mealie Version

- Docker image: `ghcr.io/mealie-recipes/mealie:v1.12.0`
- Build tag: `0d06494bbfc62fc8a1771a85fd308190891d6167 `

### Deployment

Docker (Linux), Docker (Windows)

### Additional Deployment Details

I'm able to reproduce this in a fresh docker image volume alongside my production Mealie installation. It also reproduces in both Chrome and Firefox.

**Comment by michael-genson** [comment]
The "Transfer" button on the shopping list is part of the drag and drop plugin we use; it's an alternative to actually dragging and dropping. I agree this is confusing, we should probably just get rid of the option

**Comment by BlackHoleFox** [comment]
Is there any effort (or interest) to add either an API or frontend component for transferring items between lists? seems like a common operation.

**Comment by michael-genson** [comment]
Worth a feature request for sure!

**Comment by BlackHoleFox** [comment]
Appreciate the confirmation, I opened https://github.com/mealie-recipes/mealie/discussions/5596 to track the idea.
