### ISSUE TITLE
[SCRAPER] - YOUR TITLE

### ISSUE THREAD

**Issue by giannis371** [mealie-recipes/mealie#4166]
### First Check

- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have verified that this issue _is not_ related to the underlying library
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers) by **1)** checking
the [debugger](https://demo.mealie.io/g/home/r/create/debug) and data is returned, **2)**
verifying that there _are_ errors in the log related to application level code, or
**3)** verified that the site provides recipe data, or is otherwise supported by
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers)

- [x] This issue can be replicated on the demo site (https://demo.mealie.io/)

### Please provide 1-5 example URLs that are having errors

All recipes from this domain https://akispetretzikis.com/en

"Only websites containing ld+json or microdata can be imported by Mealie. Most major recipe websites support this data structure. If your site cannot be imported but there is json data in the log, please submit a github issue with the URL and data."

I checked the website and it contains Id+json.

Also a contributor from [hhyrsev/recipe-scrapers] tested the recipe on his system 

"Thanks [@giannis371](https://github.com/giannis371)

I was able to scrape the same recipe URL successfully using a standalone checkout of recipe-scrapers v15.0.0.

Note: recipe-scrapers doesn't contain any asynchronous request code, as far as I'm aware."

https://akispetretzikis.com/en/recipe/8459/lazania-me-kima-kotopoulou
https://akispetretzikis.com/en/recipe/8445/gyros-choirinos-sto-air-fryer
https://akispetretzikis.com/en/recipe/8461/peinirli-ths-pareas
https://akispetretzikis.com/en/recipe/8459/lazania-me-kima-kotopoulou
https://akispetretzikis.com/en/recipe/8450/sokolatenies-mpares-prwteinhs-xwris-prosthiki-krystallikhs-zaxarhs

### Please provide your logs for the Mealie container `docker logs <container-id> > mealie.logs`

ERROR    2024-09-05T09:09:44 - Recipe Scraper was unable to extract a recipe from https://akispetretzikis.com/recipe/6927/kotopoylo-lemonato-me-riganh-ston-foyrno

### Deployment

Docker (Linux)

**Comment by PeterJT** [comment]
I believe this issue (like many others) is caused by anti-bot protection on the website, and it looking for javascript support on the client.

**Comment by PeterJT** [comment]
Hmm... an interesting possible workaround is to prefix the url by https://cooked.wiki so rather than using https://akispetretzikis.com/en/recipe/8459/lazania-me-kima-kotopoulou try https://cooked.wiki/https://akispetretzikis.com/en/recipe/8459/lazania-me-kima-kotopoulou

**Comment by giannis371** [comment]
Thank you for your fast reply and your time. I tried this workaround by adding the link https://cooked.wiki/https://akispetretzikis.com/en/recipe/8459/lazania-me-kima-kotopoulou in mealie but sadly it didn't work. I get the same error. Did it work when you tried it?

**Comment by PeterJT** [comment]
Yes and I just tried again. No issue. You do have to open the page on cooking wiki. It will parse the recipe and give you a new url; mine was https://cooked.wiki/new/recent/f44c77ae-9cc3-4a09-aee2-26c09c6fd502 which I was then able to save to mealie

**Comment by giannis371** [comment]
I tried your link. I don't get an error now it adds the recipes picture but on instructions and ingredients it's says could not detect ingredients/instructions. I also tried to create a new link and tested on mealie test website. Both the same, no ingredients/instructions. That's confusing

**Comment by PeterJT** [comment]
Only thing I  can think is that I'm doing it to my own Mealie instance with
OpenAI enabled.

BINGO

It's the OpenAI solving it for me. Just tried it on demo; same issue

**Comment by giannis371** [comment]
That worked for me also! Thanks!

**Comment by giannis371** [comment]
What I don't understand is why can't the AI scrape the recipe directly and it has to be through cooked.wiki. Did they a sort of blocker/protection in their website?

**Comment by PeterJT** [comment]
I believe that OpenAI is not able to access web data
