### ISSUE TITLE
[BUG] - Authelia OIDC not working

### ISSUE THREAD

**Issue by shomilsaini** [mealie-recipes/mealie#4172]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

In the past I Configured Mealie and Authelia. Had been working in the past. Didn't use it for a while.
Tried today after 2 months or so. Since there were a few big updates.
Now the Authelia integration is not working.

### Steps to Reproduce

1. go to mealie.example.com
2. auto-redirect to Authelia
3. sign in to Authelia and 2FA
4. redirect back to Mealie
5. Mealie redirects to for manual login -  https://recipes.example.com/login/?direct=1

### Please provide relevant logs

Logs from Mealie
```
INFO     2024-09-07T13:43:23 - [xxx.xxx.xxx.xxx:0] 307 Temporary Redirect "GET /login?code=authelia_ac_XXXXXXXXX&iss=https%3A%2F%2Fauth.example.com&scope=openid+profile+email+groups&state=ZknZEbag26 HTTP/1.1"
INFO     2024-09-07T13:43:23 - [xxx.xxx.xxx.xxx:0] 200 OK "GET /login/?code=authelia_ac_XXXXXXXXX&iss=https%3A%2F%2Fauth.example.com&scope=openid+profile+email+groups&state=ZknZEbag26 HTTP/1.1"
ERROR    2024-09-07T13:43:24 - Incorrect username or password from xxx.xxx.xxx.xxx
INFO     2024-09-07T13:43:24 - [xxx.xxx.xxx.xxx:0] 401 Unauthorized "POST /api/auth/token HTTP/1.1"
ERROR    2024-09-07T13:43:25 - Incorrect username or password from xxx.xxx.xxx.xxx
INFO     2024-09-07T13:43:25 - [xxx.xxx.xxx.xxx:0] 401 Unauthorized "POST /api/auth/token HTTP/1.1"
INFO     2024-09-07T13:43:25 - [xxx.xxx.xxx.xxx:0] 307 Temporary Redirect "GET /login?direct=1 HTTP/1.1"
```

Logs from Authelia
```
time="2024-09-07T13:43:23-04:00" level=debug msg="Authorization Request with id 'ca2e55ea-6922-45ef-8c38-b31323fbacff' on client with id '<<client_id>>' is being processed" method=GET path=/api/oidc/authorization remote_ip=xxx.xxx.xxx.xxx
time="2024-09-07T13:43:23-04:00" level=debug msg="Authorization Request with id 'ca2e55ea-6922-45ef-8c38-b31323fbacff' on client with id '<<client_id>>' was successfully processed, proceeding to build Authorization Response" method=GET path=/api/oidc/authorization remote_ip=xxx.xxx.xxx.xxx
time="2024-09-07T13:43:24-04:00" level=debug msg="Access Request with id 'ca2e55ea-6922-45ef-8c38-b31323fbacff' on client with id '<<client_id>>' is being processed" method=POST path=/api/oidc/token remote_ip=xxx.xxx.xxx.xxx
time="2024-09-07T13:43:24-04:00" level=debug msg="Access Request with id 'ca2e55ea-6922-45ef-8c38-b31323fbacff' on client with id '<<client_id>>' has successfully been processed" method=POST path=/api/oidc/token remote_ip=xxx.xxx.xxx.xxx
```

### Mealie Version

Version
v1.12.0
Build
[0d06494bbfc62fc8a1771a85fd308190891d6167](https://github.com/mealie-recipes/mealie/commit/0d06494bbfc62fc8a1771a85fd308190891d6167)

### Deployment

Unraid

**Comment by cmintey** [comment]
Enable debug mode by setting `LOG_LEVEL=DEBUG` in your environment variables and post the logs please

**Comment by shomilsaini** [comment]
> Enable debug mode by setting `LOG_LEVEL=DEBUG` in your environment variables and post the logs please

Thanks for pointing me in the right direction.
I got this log which made me fix the issue.
`DEBUG    2024-09-10T18:07:52 - [OIDC] User does not have the required group. Found: ['admins'] - Required: usersERROR    2024-09-10T18:07:52 - Incorrect username or password from XXX.XXX.XXX.XXX`
Although it is weird that the admins still need to be in the users group, doesn't make any sense to me.
I have temporarily added user to the users group, and it works now.

Thanks

**Comment by shomilsaini** [comment]
Also, on a side note -
going to https://mealie.YOURWEBSITE.com/g/users
goes straight to page and shows the recipes, unless it is intended to be public it should not show that and redirect to OIDC/Login Page

Thanks

**Comment by cmintey** [comment]
> Although it is weird that the admins still need to be in the users group, doesn't make any sense to me.

I've gotten this feedback a lot. I'm open to changing it for v2 if you want to voice that concern [here](https://github.com/mealie-recipes/mealie/discussions/4182).

As for the comment about public listings, that can be toggled in the group settings. Related docs: https://docs.mealie.io/documentation/getting-started/usage/permissions-and-public-access/
