### ISSUE TITLE
[BUG] - Data gone after update 

### ISSUE THREAD

**Issue by jkosick** [mealie-recipes/mealie#4178]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

After updating the container all data was gone like it was a fresh install. 

### Steps to Reproduce

Updating container via container manager after selecting upgrade image. 

### Please provide relevant logs

2024/09/08 19:47:45 | stdout | ERROR    2024-09-08T19:47:45 - Incorrect username or password from 192.168.1.1
2024/09/08 19:47:45 | stdout | ERROR    2024-09-08T19:47:45 - Incorrect username or password from 192.168.1.1
2024/09/08 19:47:41 | stdout | INFO     2024-09-08T19:47:41 - [192.168.1.1:0] [32m200 OK[0m "[1mGET /sw.js HTTP/1.1[0m"
2024/09/08 19:47:41 | stdout | INFO     2024-09-08T19:47:41 - [192.168.1.1:0] [32m200 OK[0m "[1mGET /icons/apple-touch-icon.png HTTP/1.1[0m"
2024/09/08 19:47:41 | stdout | INFO     2024-09-08T19:47:41 - [192.168.1.1:0] [32m200 OK[0m "[1mGET /api/app/about/startup-info HTTP/1.1[0m"
2024/09/08 19:47:41 | stdout | INFO     2024-09-08T19:47:41 - [192.168.1.1:0] [32m200 OK[0m "[1mGET /api/app/about HTTP/1.1[0m"
2024/09/08 19:47:41 | stdout | INFO     2024-09-08T19:47:41 - [192.168.1.1:0] [32m200 OK[0m "[1mGET /_nuxt/0e3bc77.js HTTP/1.1[0m"
2024/09/08 19:47:41 | stdout | INFO     2024-09-08T19:47:41 - [192.168.1.1:0] [32m200 OK[0m "[1mGET /api/app/about HTTP/1.1[0m"
2024/09/08 19:47:41 | stdout | INFO     2024-09-08T19:47:41 - [192.168.1.1:0] [32m200 OK[0m "[1mGET /api/app/about HTTP/1.1[0m"
2024/09/08 19:47:41 | stdout | INFO     2024-09-08T19:47:41 - [192.168.1.1:0] [32m200 OK[0m "[1mGET /api/app/about/theme HTTP/1.1[0m"
2024/09/08 19:47:41 | stdout | INFO     2024-09-08T19:47:41 - [192.168.1.1:0] [32m200 OK[0m "[1mGET /favicon.ico HTTP/1.1[0m"
2024/09/08 19:47:41 | stdout | INFO     2024-09-08T19:47:41 - [192.168.1.1:0] [32m200 OK[0m "[1mGET /_nuxt/f0a85d5.js HTTP/1.1[0m"
2024/09/08 19:47:41 | stdout | INFO     2024-09-08T19:47:41 - [192.168.1.1:0] [32m200 OK[0m "[1mGET /icons/android-chrome-maskable-512x512.png HTTP/1.1[0m"
2024/09/08 19:47:40 | stdout | INFO     2024-09-08T19:47:40 - [192.168.1.1:0] [32m200 OK[0m "[1mGET /_nuxt/ffbda59.js HTTP/1.1[0m"
2024/09/08 19:47:40 | stdout | INFO     2024-09-08T19:47:40 - [192.168.1.1:0] [32m200 OK[0m "[1mGET /_nuxt/1666741.js HTTP/1.1[0m"
2024/09/08 19:47:40 | stdout | INFO     2024-09-08T19:47:40 - [192.168.1.1:0] [32m200 OK[0m "[1mGET /_nuxt/f6e2c87.js HTTP/1.1[0m"
2024/09/08 19:47:40 | stdout | INFO     2024-09-08T19:47:40 - [192.168.1.1:0] [32m200 OK[0m "[1mGET /_nuxt/4f93031.js HTTP/1.1[0m"
2024/09/08 19:47:40 | stdout | INFO     2024-09-08T19:47:40 - [192.168.1.1:0] [32m200 OK[0m "[1mGET /_nuxt/43cddb8.js HTTP/1.1[0m"
2024/09/08 19:47:40 | stdout | INFO     2024-09-08T19:47:40 - [192.168.1.1:0] [32m200 OK[0m "[1mGET / HTTP/1.1[0m"
2024/09/08 19:47:16 | stdout | INFO     2024-09-08T19:47:16 - [127.0.0.1:47512] [32m200 OK[0m "[1mGET /api/app/about HTTP/1.1[0m"
2024/09/08 19:46:45 | stdout | INFO     2024-09-08T19:46:45 - [127.0.0.1:47466] [32m200 OK[0m "[1mGET /api/app/about HTTP/1.1[0m"
2024/09/08 19:46:14 | stdout | INFO     2024-09-08T19:46:14 - [127.0.0.1:47308] [32m200 OK[0m "[1mGET /api/app/about HTTP/1.1[0m"
2024/09/08 19:45:43 | stdout | INFO     2024-09-08T19:45:43 - [127.0.0.1:47222] [32m200 OK[0m "[1mGET /api/app/about HTTP/1.1[0m"
2024/09/08 19:45:12 | stdout | INFO     2024-09-08T19:45:12 - [127.0.0.1:47154] [32m200 OK[0m "[1mGET /api/app/about HTTP/1.1[0m"
2024/09/08 19:44:40 | stdout | INFO     2024-09-08T19:44:40 - [127.0.0.1:47142] [32m200 OK[0m "[1mGET /api/app/about HTTP/1.1[0m"
2024/09/08 19:44:09 | stdout | INFO     2024-09-08T19:44:09 - [127.0.0.1:47010] [32m200 OK[0m "[1mGET /api/app/about HTTP/1.1[0m"
2024/09/08 19:43:39 | stdout | INFO     2024-09-08T19:43:39 - [127.0.0.1:46966] [32m200 OK[0m "[1mGET /api/app/about HTTP/1.1[0m"
2024/09/08 19:43:08 | stdout | INFO     2024-09-08T19:43:08 - [127.0.0.1:46928] [32m200 OK[0m "[1mGET /api/app/about HTTP/1.1[0m"
2024/09/08 19:42:37 | stdout | INFO     2024-09-08T19:42:37 - [127.0.0.1:46832] [32m200 OK[0m "[1mGET /api/app/about HTTP/1.1[0m"
2024/09/08 19:42:06 | stdout | INFO     2024-09-08T19:42:06 - [127.0.0.1:46538] [32m200 OK[0m "[1mGET /api/app/about HTTP/1.1[0m"
2024/09/08 19:41:36 | stdout | INFO     2024-09-08T19:41:36 - [127.0.0.1:46290] [32m200 OK[0m "[1mGET /api/app/about HTTP/1.1[0m"
2024/09/08 19:41:05 | stdout | INFO     2024-09-08T19:41:05 - [127.0.0.1:46246] [32m200 OK[0m "[1mGET /api/app/about HTTP/1.1[0m"
2024/09/08 19:40:34 | stdout | INFO     2024-09-08T19:40:34 - [127.0.0.1:46192] [32m200 OK[0m "[1mGET /api/app/about HTTP/1.1[0m"
2024/09/08 19:40:10 | stdout | INFO     2024-09-08T19:40:10 - Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
2024/09/08 19:40:10 | stdout | INFO     2024-09-08T19:40:10 - Application startup complete.
2024/09/08 19:40:10 | stdout | INFO     2024-09-08T19:40:10 - Daily tasks scheduled for 2024-09-09 06:45:00+00:00
2024/09/08 19:40:10 | stdout | }
2024/09/08 19:40:10 | stdout | "UVICORN_WORKERS": 1
2024/09/08 19:40:10 | stdout | "WORKER_PER_CORE": 1,
2024/09/08 19:40:10 | stdout | "OPENAI_REQUEST_TIMEOUT": 60,
2024/09/08 19:40:10 | stdout | "OPENAI_SEND_DATABASE_DATA": true,
2024/09/08 19:40:10 | stdout | "OPENAI_WORKERS": 2,
2024/09/08 19:40:10 | stdout | "OPENAI_ENABLE_IMAGE_SERVICES": true,
2024/09/08 19:40:10 | stdout | "OPENAI_MODEL": "gpt-4o",
2024/09/08 19:40:10 | stdout | "OPENAI_API_KEY": null,
2024/09/08 19:40:10 | stdout | "OPENAI_BASE_URL": null,
2024/09/08 19:40:10 | stdout | "OIDC_TLS_CACERTFILE": null,
2024/09/08 19:40:10 | stdout | "OIDC_GROUPS_CLAIM": "groups",
2024/09/08 19:40:10 | stdout | "OIDC_USER_CLAIM": "email",
2024/09/08 19:40:10 | stdout | "OIDC_SIGNING_ALGORITHM": "RS256",
2024/09/08 19:40:10 | stdout | "OIDC_REMEMBER_ME": false,
2024/09/08 19:40:10 | stdout | "OIDC_PROVIDER_NAME": "OAuth",
2024/09/08 19:40:10 | stdout | "OIDC_AUTO_REDIRECT": false,
2024/09/08 19:40:10 | stdout | "OIDC_ADMIN_GROUP": null,
2024/09/08 19:40:10 | stdout | "OIDC_USER_GROUP": null,
2024/09/08 19:40:10 | stdout | "OIDC_SIGNUP_ENABLED": true,
2024/09/08 19:40:10 | stdout | "OIDC_CONFIGURATION_URL": null,
2024/09/08 19:40:10 | stdout | "OIDC_CLIENT_ID": null,
2024/09/08 19:40:10 | stdout | "OIDC_AUTH_ENABLED": false,
2024/09/08 19:40:10 | stdout | "LDAP_NAME_ATTRIBUTE": "name",
2024/09/08 19:40:10 | stdout | "LDAP_MAIL_ATTRIBUTE": "mail",
2024/09/08 19:40:10 | stdout | "LDAP_ID_ATTRIBUTE": "uid",
2024/09/08 19:40:10 | stdout | "LDAP_ADMIN_FILTER": null,
2024/09/08 19:40:10 | stdout | "LDAP_USER_FILTER": null,
2024/09/08 19:40:10 | stdout | "LDAP_QUERY_PASSWORD": null,
2024/09/08 19:40:10 | stdout | "LDAP_QUERY_BIND": null,
2024/09/08 19:40:10 | stdout | "LDAP_BASE_DN": null,
2024/09/08 19:40:10 | stdout | "LDAP_ENABLE_STARTTLS": false,
2024/09/08 19:40:10 | stdout | "LDAP_TLS_CACERTFILE": null,
2024/09/08 19:40:10 | stdout | "LDAP_TLS_INSECURE": false,
2024/09/08 19:40:10 | stdout | "LDAP_SERVER_URL": null,
2024/09/08 19:40:10 | stdout | "LDAP_AUTH_ENABLED": false,
2024/09/08 19:40:10 | stdout | "SMTP_AUTH_STRATEGY": "SSL",
2024/09/08 19:40:10 | stdout | "SMTP_FROM_EMAIL": "removed",
2024/09/08 19:40:10 | stdout | "SMTP_FROM_NAME": "removed",
2024/09/08 19:40:10 | stdout | "SMTP_PORT": "465",
2024/09/08 19:40:10 | stdout | "SMTP_HOST": "removed",
2024/09/08 19:40:10 | stdout | "DEFAULT_GROUP": "Home",
2024/09/08 19:40:10 | stdout | "DB_ENGINE": "sqlite",
2024/09/08 19:40:10 | stdout | "SECURITY_USER_LOCKOUT_TIME": 24,
2024/09/08 19:40:10 | stdout | "SECURITY_MAX_LOGIN_ATTEMPTS": 5,
2024/09/08 19:40:10 | stdout | "DAILY_SCHEDULE_TIME": "23:45",
2024/09/08 19:40:10 | stdout | "ALLOW_SIGNUP": true,
2024/09/08 19:40:10 | stdout | "GIT_COMMIT_HASH": "e344f3f1e6672d673f6e0899a5cef28aa8beb2f0",
2024/09/08 19:40:10 | stdout | "TOKEN_TIME": 48,
2024/09/08 19:40:10 | stdout | "API_DOCS": false,
2024/09/08 19:40:10 | stdout | "API_PORT": 9000,
2024/09/08 19:40:10 | stdout | "API_HOST": "0.0.0.0",
2024/09/08 19:40:10 | stdout | "HOST_IP": "*",
2024/09/08 19:40:10 | stdout | "IS_DEMO": false,
2024/09/08 19:40:10 | stdout | "STATIC_FILES": "/spa/static",
2024/09/08 19:40:10 | stdout | "BASE_URL": "removed",
2024/09/08 19:40:10 | stdout | },
2024/09/08 19:40:10 | stdout | "dark_error": "#EF5350"
2024/09/08 19:40:10 | stdout | "dark_warning": "#FF6D00",
2024/09/08 19:40:10 | stdout | "dark_info": "#1976D2",
2024/09/08 19:40:10 | stdout | "dark_success": "#43A047",
2024/09/08 19:40:10 | stdout | "dark_secondary": "#973542",
2024/09/08 19:40:10 | stdout | "dark_accent": "#007A99",
2024/09/08 19:40:10 | stdout | "dark_primary": "#E58325",
2024/09/08 19:40:10 | stdout | "light_error": "#EF5350",
2024/09/08 19:40:10 | stdout | "light_warning": "#FF6D00",
2024/09/08 19:40:10 | stdout | "light_info": "#1976D2",
2024/09/08 19:40:10 | stdout | "light_success": "#43A047",
2024/09/08 19:40:10 | stdout | "light_secondary": "#973542",
2024/09/08 19:40:10 | stdout | "light_accent": "#007A99",
2024/09/08 19:40:10 | stdout | "light_primary": "#E58325",
2024/09/08 19:40:10 | stdout | "theme": {
2024/09/08 19:40:10 | stdout | "LOG_LEVEL": "info",
2024/09/08 19:40:10 | stdout | "LOG_CONFIG_OVERRIDE": null,
2024/09/08 19:40:10 | stdout | "PRODUCTION": true,
2024/09/08 19:40:10 | stdout | "TESTING": false,
2024/09/08 19:40:10 | stdout | INFO     2024-09-08T19:40:10 - {
2024/09/08 19:40:10 | stdout | INFO     2024-09-08T19:40:10 - ------APP SETTINGS------
2024/09/08 19:40:10 | stdout | INFO     2024-09-08T19:40:10 - -----SYSTEM STARTUP-----
2024/09/08 19:40:10 | stdout | INFO     2024-09-08T19:40:10 - end: database initialization
2024/09/08 19:40:10 | stdout | INFO     2024-09-08T19:40:10 - Generating Default User
2024/09/08 19:40:10 | stdout | INFO     2024-09-08T19:40:10 - Generating Default Group
2024/09/08 19:40:10 | stdout | INFO     2024-09-08T19:40:10 - Database contains no users, initializing...
2024/09/08 19:40:09 | stdout | INFO     2024-09-08T19:40:09 - Checking for migration data fixes
2024/09/08 19:40:09 | stdout | INFO     2024-09-08T19:40:09 - Running upgrade 7788478a0338 -> 32d69327997b, Add staple flag to foods
2024/09/08 19:40:09 | stdout | INFO     2024-09-08T19:40:09 - Running upgrade d7c6efd2de42 -> 7788478a0338, add group recipe actions
2024/09/08 19:40:09 | stdout | INFO     2024-09-08T19:40:09 - Running upgrade 09aba125b57a -> d7c6efd2de42, migrate favorites and ratings to user_ratings
2024/09/08 19:40:09 | stdout | INFO     2024-09-08T19:40:09 - Running upgrade 2298bb460ffd -> 09aba125b57a, add OIDC auth method
2024/09/08 19:40:09 | stdout | INFO     2024-09-08T19:40:09 - Running upgrade ba1e4a6cfe99 -> 2298bb460ffd, added user to shopping list
2024/09/08 19:40:08 | stdout | INFO     2024-09-08T19:40:08 - Running upgrade dded3119c1fe -> ba1e4a6cfe99, added plural names and alias tables for foods and units
2024/09/08 19:40:08 | stdout | INFO     2024-09-08T19:40:08 - Running upgrade 0341b154f79a -> dded3119c1fe, added unique constraints
2024/09/08 19:40:07 | stdout | INFO     2024-09-08T19:40:07 - Running upgrade bcfdad6b7355 -> 0341b154f79a, added normalized unit and food names
2024/09/08 19:40:07 | stdout | INFO     2024-09-08T19:40:07 - Running upgrade 1825b5225403 -> bcfdad6b7355, remove tool name and slug unique contraints
2024/09/08 19:40:07 | stdout | INFO     2024-09-08T19:40:07 - Running upgrade 04ac51cbe9a4 -> 1825b5225403, added recipe note to shopping list recipe ref
2024/09/08 19:40:07 | stdout | INFO     2024-09-08T19:40:07 - Running upgrade b3dbb554ba53 -> 04ac51cbe9a4, added group slug
2024/09/08 19:40:07 | stdout | INFO     2024-09-08T19:40:07 - Running upgrade 38514b39a824 -> b3dbb554ba53, postgres fuzzy search
2024/09/08 19:40:07 | stdout | INFO     2024-09-08T19:40:07 - Running upgrade b04a08da2108 -> 38514b39a824, add auth_method to user table
2024/09/08 19:40:06 | stdout | INFO     2024-09-08T19:40:06 - Running upgrade 5ab195a474eb -> b04a08da2108, added shopping list label settings
2024/09/08 19:40:06 | stdout | INFO     2024-09-08T19:40:06 - Running upgrade 16160bf731a0 -> 5ab195a474eb, add normalized search properties
2024/09/08 19:40:06 | stdout | INFO     2024-09-08T19:40:06 - Running upgrade ff5f73b01a7a -> 16160bf731a0, add more indices necessary for search
2024/09/08 19:40:02 | stdout | INFO     2024-09-08T19:40:02 - Running upgrade 165d943c64ee -> ff5f73b01a7a, add missing foreign key and order indices
2024/09/08 19:40:01 | stdout | INFO     2024-09-08T19:40:01 - Running upgrade 167eb69066ad -> 165d943c64ee, add related user to mealplan
2024/09/08 19:40:01 | stdout | INFO     2024-09-08T19:40:01 - Running upgrade 1923519381ad -> 167eb69066ad, add recipe_scale to shopping list item ref
2024/09/08 19:40:01 | stdout | INFO     2024-09-08T19:40:01 - Running upgrade 2ea7a807915c -> 1923519381ad, added recipe last made timestamp
2024/09/08 19:40:01 | stdout | INFO     2024-09-08T19:40:01 - Running upgrade 44e8d670719d -> 2ea7a807915c, add recipe_timeline_events table
2024/09/08 19:40:01 | stdout | INFO     2024-09-08T19:40:01 - Running upgrade 089bfa50d0ed -> 44e8d670719d, add extras to shopping lists, list items, and ingredient foods
2024/09/08 19:40:01 | stdout | INFO     2024-09-08T19:40:01 - Running upgrade 188374910655 -> 089bfa50d0ed, Add is_ocr_recipe column to recipes
2024/09/08 19:40:01 | stdout | INFO     2024-09-08T19:40:01 - Running upgrade f30cf048c228 -> 188374910655, add login_attemps and locked_at field to user table
2024/09/08 19:40:01 | stdout | INFO     2024-09-08T19:40:01 - Running upgrade ab0bae02578f -> f30cf048c228, add new webhook fields
2024/09/08 19:40:01 | stdout | INFO     2024-09-08T19:40:01 - Running upgrade 09dfc897ad62 -> ab0bae02578f, Add use_abbreviation column to ingredients
2024/09/08 19:40:01 | stdout | INFO     2024-09-08T19:40:01 - Running upgrade 59eb59135381 -> 09dfc897ad62, add require_all for cookbook filters
2024/09/08 19:40:00 | stdout | INFO     2024-09-08T19:40:00 - Running upgrade f1a2dbee5fe9 -> 59eb59135381, add tags to cookbooks
2024/09/08 19:40:00 | stdout | INFO     2024-09-08T19:40:00 - Running upgrade 263dd6707191 -> f1a2dbee5fe9, Add original_text column to recipes_ingredients
2024/09/08 19:40:00 | stdout | INFO     2024-09-08T19:40:00 - Running upgrade 6b0f5f32d602 -> 263dd6707191, convert quantity from integer to float
2024/09/08 19:39:58 | stdout | INFO     2024-09-08T19:39:58 - Running upgrade  -> 6b0f5f32d602, Initial tables
2024/09/08 19:39:58 | stdout | INFO     2024-09-08T19:39:58 - Will assume non-transactional DDL.
2024/09/08 19:39:58 | stdout | INFO     2024-09-08T19:39:58 - Context impl SQLiteImpl.
2024/09/08 19:39:58 | stdout | INFO     2024-09-08T19:39:58 - Migration needed. Performing migration...
2024/09/08 19:39:58 | stdout | INFO     2024-09-08T19:39:58 - Will assume non-transactional DDL.
2024/09/08 19:39:58 | stdout | INFO     2024-09-08T19:39:58 - Context impl SQLiteImpl.
2024/09/08 19:39:58 | stdout | INFO     2024-09-08T19:39:58 - Database connection established.
2024/09/08 19:39:58 | stdout | INFO     2024-09-08T19:39:58 - start: database initialization
2024/09/08 19:39:58 | stdout | INFO     2024-09-08T19:39:58 - Waiting for application startup.
2024/09/08 19:39:58 | stdout | INFO     2024-09-08T19:39:58 - Started server process [1]
2024/09/08 19:39:33 | stdout |  
2024/09/08 19:39:33 | stdout | User gid:    911
2024/09/08 19:39:33 | stdout | User uid:    1026
2024/09/08 19:39:33 | stdout |  
2024/09/08 19:39:33 | stdout | Switching to dedicated user

### Mealie Version

**Details**
Version: v1.12.0
Build: e344f3f1e6672d673f6e0899a5cef28aa8beb2f0
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Disabled
Database Type: sqlite
Recipe Scraper Version: 15.0.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
OIDC Ready: No
OpenAI Ready: No
Email Configured: Yes

### Deployment

Docker (Synology)

**Comment by michael-genson** [comment]
What version did you update from? Per the logs, it looks like there were no users in the database when it started up:

> Database contains no users, initializing...

**Comment by jkosick** [comment]
I am not exactly sure, my log doesn't show the versions in the container manager. It should have been the prior release to this one. Container Manager showed that an update was available, and I clicked update.  I had one user, and roughly 30 recipes. I am using Synology. All of my other containers keep my data even if I delete the container, so I am assuming that all data was stored inside the container and that's why I lost all of my data when it updated. What is the best way to set up the mapping so that it stores the data outside of the container? I didn't see any reference to that in the documentation.

**Comment by Kuchenpirat** [comment]
You need to have a volume mapped to `/app/data` to have persistent storage. 
If you are using sqlite that is all.

Our docker compose is a good template to start from: https://docs.mealie.io/documentation/getting-started/installation/sqlite/

**Comment by jkosick** [comment]
Thank you. I was using the hkotel-mealie image. I mapped the data folder and tried a reset and my data was still there on resetting the container, so I should be good now, thank you for mapping info.

**Comment by Kuchenpirat** [comment]
We publish to both dockerhub (hkotel image) and ghcr so that should not be an issue. 

But yeah, without mapping, the data cannot be persistent. 
Glad to hear you are sorted for the future will close this  as completed.
