### ISSUE TITLE
[BUG] - Mealie exposes sensitive information in log files

### ISSUE THREAD

**Issue by bigcat2014** [mealie-recipes/mealie#4217]
I noticed that Mealie excludes some of the sensitive informatin from the logs, but it does not exclude everything; mainly, it's missing LDAP_QUERY_PASSWORD, OIDC_CLIENT_ID, and OPENAI_API_KEY.

I will open a PR to _hopefully_ fix this issue, although this is my first time contributing to Mealie, so if I miss some spots in the code where this info may be leaked, please let me know and I will correct it.

**Comment by michael-genson** [comment]
You should be able to just add those fields here:

https://github.com/mealie-recipes/mealie/blob/8778559a208d3cdd0332229f4fde6acd4c12f7d4/mealie/app.py#L60-L75

**Comment by michael-genson** [comment]
Also, please use the bug template next time: https://github.com/mealie-recipes/mealie/issues/new/choose
