### ISSUE TITLE
[BUG] - Shortcut image import results in recipe which fails validation

### ISSUE THREAD

**Issue by gordonbazeley** [mealie-recipes/mealie#4222]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I'm just getting started with Mealie. Before I realised the latest version includes OpenAI image import I tried out the old Mac Shortcut using Gemini. For one of the recipes I tried to load in this way something went wrong and when I try to edit that recipe I get shown Unknown error - in developer tools this is shown as a Validation Error.

Is there any way for me to delete this invalid recipe please?

### Steps to Reproduce

Not wholly sure - something errored when using the iOS Shortcut Gemini image import

I tried to delete from the bulk edit page (group/data/recipes/) and that doesn't error but neither did it delete the recipe

### Please provide relevant logs

Can provide logs but not sure which section is relevant and pasting the whole log fails on size

### Mealie Version

Version
nightly
Build
[cff33cb15c9c0faa9f8a7698076bc54a833dfd32](https://github.com/mealie-recipes/mealie/commit/cff33cb15c9c0faa9f8a7698076bc54a833dfd32)

### Deployment

Docker (Linux)

### Additional Deployment Details

Docker on Mac OS X

**Comment by michael-genson** [comment]
Please post your logs with the entire error

**Comment by gordonbazeley** [comment]
Hi there - I *think* this is the right section ...

mealie  | ERROR    2024-09-17T07:06:32 - Unknown Error on recipe controller action
mealie  | ERROR    2024-09-17T07:06:32 - Unknown Error on recipe controller action
mealie  | ERROR    2024-09-17T07:06:32 - 14 validation errors for Recipe
mealie  | recipe_ingredient.0.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.1.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.2.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.3.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.4.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.5.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.6.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.7.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.8.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.9.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.10.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.11.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.12.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.13.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | Traceback (most recent call last):
mealie  |   File "/app/mealie/routes/recipe/recipe_crud_routes.py", line 371, in get_one
mealie  |     recipe = self.service.get_one(slug)
mealie  |   File "/app/mealie/services/recipe/recipe_service.py", line 149, in get_one
mealie  |     return self._get_recipe(slug_or_id, "slug")
mealie  |   File "/app/mealie/services/recipe/recipe_service.py", line 61, in _get_recipe
mealie  |     recipe = self.group_recipes.get_one(data, key)
mealie  |   File "/app/mealie/repos/repository_generic.py", line 158, in get_one
mealie  |     return eff_schema.model_validate(result)
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/pydantic/main.py", line 593, in model_validate
mealie  |     return cls.__pydantic_validator__.validate_python(
mealie  | pydantic_core._pydantic_core.ValidationError: 14 validation errors for Recipe
mealie  | recipe_ingredient.0.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.1.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.2.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.3.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.4.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.5.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.6.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.7.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.8.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.9.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.10.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.11.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.12.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.13.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | ERROR    2024-09-17T07:06:32 - 14 validation errors for Recipe
mealie  | recipe_ingredient.0.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.1.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.2.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.3.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.4.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.5.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.6.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.7.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.8.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.9.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.10.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.11.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.12.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.13.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | Traceback (most recent call last):
mealie  |   File "/app/mealie/routes/recipe/recipe_crud_routes.py", line 371, in get_one
mealie  |     recipe = self.service.get_one(slug)
mealie  |   File "/app/mealie/services/recipe/recipe_service.py", line 149, in get_one
mealie  |     return self._get_recipe(slug_or_id, "slug")
mealie  |   File "/app/mealie/services/recipe/recipe_service.py", line 61, in _get_recipe
mealie  |     recipe = self.group_recipes.get_one(data, key)
mealie  |   File "/app/mealie/repos/repository_generic.py", line 158, in get_one
mealie  |     return eff_schema.model_validate(result)
mealie  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/pydantic/main.py", line 593, in model_validate
mealie  |     return cls.__pydantic_validator__.validate_python(
mealie  | pydantic_core._pydantic_core.ValidationError: 14 validation errors for Recipe
mealie  | recipe_ingredient.0.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.1.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.2.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.3.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.4.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.5.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.6.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.7.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.8.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.9.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.10.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.11.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.12.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | recipe_ingredient.13.reference_id
mealie  |   UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=None, input_type=NoneType]
mealie  |     For further information visit https://errors.pydantic.dev/2.9/v/uuid_type
mealie  | INFO     2024-09-17T07:06:32 - [192.168.65.1:17051] 500 Internal Server Error "GET /api/recipes/roasted-parsnip-puy-lentil-and-watercress-salad HTTP/1.1"
mealie  | INFO     2024-09-17T07:06:56 - [127.0.0.1:38428] 200 OK "GET /api/app/about HTTP/1.1"

**Comment by michael-genson** [comment]
Can you go into more detail on how you created this recipe? You said you used an old shortcut? Can you supply that?

To delete the recipe, have you tried doing it from the data management page?
`https://your-url.com/group/data/recipes`

**Comment by gordonbazeley** [comment]
Hi @michael-genson - I created the recipe using the shortcut [detailed here](https://docs.mealie.io/documentation/community-guide/ios/). I used that shortcut on my Mac about three times - I think it reliably created a recipe once, failed outright once and created this "zombie" recipe once.

Trying to delete the recipe from the data management page returns the following in console ... but doesn't delete the recipe

{data: null, status: 200, statusText: 'OK', headers: {…}, config: {…}, …}
config
: 
{url: '/api/recipes/bulk-actions/delete', method: 'post', data: '{"recipes":["roasted-parsnip-puy-lentil-and-watercress-salad"]}', headers: {…}, baseURL: '/', …}
data
: 
null
headers
: 
{content-length: '4', content-type: 'application/json', date: 'Wed, 18 Sep 2024 13:29:11 GMT', server: 'uvicorn'}
request
: 
XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: true, upload: XMLHttpRequestUpload, …}
status
: 
200
statusText
: 
"OK"
[[Prototype]]
: 
Object

**Comment by michael-genson** [comment]
I think your best bet is to delete it straight from the database. No clue how a recipe could be created without an id, but the API is going to fail on it.

**Comment by gordonbazeley** [comment]
Thanks @michael-genson - my install is using SQLite and Docker. Whereabouts is the database file to open in DB Browser please?

**Comment by michael-genson** [comment]
SQLite is pretty easy, it's just a single file on disc ("mealie.db"). If you go into the Docker container it should be in `/app/data`. To browse the Docker filesystem:

`docker exec -it containerid sh`
(to get your container id you can list all containers with `docker ps`)

**Comment by gordonbazeley** [comment]
Got it - thanks so much for your help @michael-genson

**Comment by gordonbazeley** [comment]
Sorted
