### ISSUE TITLE
[BUG] - OpenAI request fails with 413

### ISSUE THREAD

**Issue by mahen57** [mealie-recipes/mealie#4262]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I have setup an OpenAI account and funded it, i.e. not using a free account.  When loading a recipe from an image, I receive a quick pop-up saying "Something went wrong" at the top center of the screen.

I have tried multiple recipe images scanned at various DPI. 

### Steps to Reproduce

Click Create + -> Create from Image
Click Upload Image
Select file from local drive
Use crop widget to resize as necessary
Click +Create

### Please provide relevant logs

[mealie.log](https://github.com/user-attachments/files/17103419/mealie.log)

### Mealie Version

Version
v1.12.0
Build
[0d06494bbfc62fc8a1771a85fd308190891d6167](https://github.com/mealie-recipes/mealie/commit/0d06494bbfc62fc8a1771a85fd308190891d6167)

### Deployment

Other (please specify below)

### Additional Deployment Details

QNAP Container station

$ docker -v
Docker version 20.10.27-qnap1, build 662936b

**Comment by michael-genson** [comment]
How big is the image? Can you provide it here?

> Client error '413 Payload Too Large'

**Comment by mahen57** [comment]
It's a little over 3MB.  Attached.
![oyster-stuffing](https://github.com/user-attachments/assets/bd144154-3f81-4dde-9e3d-30b849759881)

**Comment by mahen57** [comment]
Found it.  Typo on my part.

**Comment by boc-the-git** [comment]
Can you give more specific info pls @mahen57

**Comment by mahen57** [comment]
It was a matter of having OPENIA vs OPENAI in one of my ENV variables.  I looked at the yaml a dozen times before seeing that.
