### ISSUE TITLE
Failure of Migration and Backup Restore

### ISSUE THREAD

**Issue by jrichey25** [mealie-recipes/mealie#4276]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I needed to recreate a Mealie docker container on the same machine. I downloaded a backup of my previous Mealie instance, thinking I could spin up a new Mealie instance and simply import the backup. Mealie sees my backup, I can see it in the GUI. However, when I attempt to Backup Restore, I get the logs below and my Mealie instance breaks. 

I've also tried to simply Migrate the recipes. I've organzied my recipes in the structure that is shown in the GUI, however, I get a failure every time and nothing appears to show in the logs. 

I've tried to simply copy the recipe folders from my backup into the new installation, which did not work.

### Steps to Reproduce

Restore attempt:
1) download Mealie backup from previously working and populated instance
2) Backup and Restore

Migration attempt:
1) format .zip file to match structure shown in GUI
2) Submit

### Please provide relevant logs

    self.dialect.do_execute(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: groups
[SQL: SELECT groups.id, groups.name, groups.slug, groups.created_at, groups.update_at 


### Mealie Version

Full docker-compose

version: '3.8'
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.6.0  
    container_name: mealie                      
    restart: always                             
    ports:
      - "9925:9000"                             
    deploy:
      resources:
        limits:
          memory: 1000M                        
    volumes:
      - /home/NAME/docker/mealie/mealie-data:/app/data/                  
    environment:
      - ALLOW_SIGNUP=true                      
      - PUID=1000                              
      - PGID=1000                              
      - TZ=America/New_York                   
      - MAX_WORKERS=1                           
      - WEB_CONCURRENCY=1                       
      - BASE_URL=http://192.168.1.166  

volumes:
  mealie-data:                                  

### Deployment

Docker (Linux)

### Additional Deployment Details

Deployed via docker-compose in Portainer

**Comment by jrichey25** [comment]
I guess I can't paste my full log. I'm new to most of this, so I apologize for my ignorance in advance.

    self.dialect.do_execute(
  File "/opt/pysetup/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: groups
[SQL: SELECT groups.id, groups.name, groups.slug, groups.created_at, groups.update_at 


**Comment by michael-genson** [comment]
> no such table: groups

This tells me something is wrong with your database/backup. Which version of Mealie did your backup come from? Can you share it here?

Unrelated, though worth mentioning, it looks like you're trying to restore to v1.6.0. You may as well upgrade to the most recent stable version (`ghcr.io/mealie-recipes/mealie:v1.12.0`)

**Comment by jrichey25** [comment]
Thanks for taking the time to look into my issue. It looks like my backup is too large to attach here. It's 33 MB, and it looks like the max attachment size is 25 MB. Is there another way to send you the backup? I took the backup from version 1.6.

**Comment by jrichey25** [comment]
Well, I redeployed Mealie with the latest version (1.12) instead of v1.6, and the backup restored with no issues. Looks like everything restored perfectly

**Comment by michael-genson** [comment]
Great! Some previous versions had some weird migration issues so it's possible it was one of those. Glad you got it sorted!
