### ISSUE TITLE
OIDC login problem, results in a 404 error...

### ISSUE THREAD

**Issue by Aesgarth** [mealie-recipes/mealie#4304]
Hello.

I'm trying to configure a Meallie instance to run along side a small forum that I host for friends and family. Ideally I'd like to use OIDC so that my users can log in to mealie using the forum login.

The forum is running on Discourse and my OIDC provider is Distrust.
https://github.com/Parkour-Vienna/distrust

I have succesfully set up Distrust and can use it as a login for Grist - so i believe it's working correctly. It also works correctly when tested with the OIDC playground. When I try to log in to Mealie with OIDC i get the Mealie 404 page.

Distrust Logs:
7:40PM TRC request finished duration=0.309959 from=192.168.0.38:60538 method=GET path=/oauth2/.well-known/openid-configuration status=200
It seems there are no further requests after the discovery document.

Mealie Logs (LOG_LEVEL=DEBUG already set)
`INFO 2024-10-01T20:40:49 - [45.150.143.12:0] 200 OK "GET /api/app/about HTTP/1.1"

INFO 2024-10-01T20:40:49 - [45.150.143.12:0] 200 OK "GET /api/app/about HTTP/1.1"

INFO 2024-10-01T20:40:51 - [45.150.143.12:0] 200 OK "GET /null?protocol=oauth2&response_type=code&access_type&client_id=mealie&redirect_uri=https%3A%2F%2Frecipe.mysite.com%2Flogin&scope=openid%20profile%20email%20groups&state=CGoGfJyx66&code_challenge_method=S256&code_challenge=FBlOfJAumMd09sewEEgQjQn53LIAiwLltmB3fYEdWcE HTTP/1.1"

INFO 2024-10-01T20:40:53 - [45.150.143.12:0] 304 Not Modified "GET /sw.js HTTP/1.1"`

Any suggestions?

**Comment by Aesgarth** [comment]
An addition:

I realised it looks like I haven't even tried to search for solutions but I have. I've read through the following;

https://github.com/mealie-recipes/mealie/issues/4172
github.com/mealie-recipes/mealie/discussions/3450
github.com/authelia/authelia/discussions/7419
reddit.com/r/selfhosted/comments/1c2u4s3/mealie_support_cloudflare_oauth_help/

and some other stuff, and I've spent literally hours changing things to try to make this work.

It appears that mealie is not redirecting to the login page - I get the exact same result in an incognito window... Straight to Mealie 404 Page not found message.

When using this OIDC provider for other services I get redirected to the forum login page on a new incognito browsing session.
Same thing when using Chrome or Edge.
I do get a little red "something went wrong" message when I click log in with OIDC the first time but then the 404 on every subsequent click. Nothing seems to be showing in the logs.

**Comment by cmintey** [comment]
Any logs in the browser console when you click the button the first time and get the "something went wrong" pop up? I suspect this has something to do with CORS

**Comment by Aesgarth** [comment]
Thank you! I had looked at the CORS post on the Authelia github but didn't know how to diagnose it. 

`/login:1 Access to XMLHttpRequest at 'https://auth.mysite.com/oauth2/.well-known/openid-configuration' from origin 'https://recipe.ctwtf.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I now have no idea how to fix it but at least I know what's wrong.  Thanks!

**Comment by cmintey** [comment]
Yeah I can't help specifically with your IdP. However I will say that the OIDC implementation in the upcoming Mealie v2 release has been completely rewritten to be all done in the backend, so CORS is no longer an issue.

https://github.com/mealie-recipes/mealie/issues/4254

**Comment by Aesgarth** [comment]
Just wanted to add that I switched to the nightly build and the problem is resolved. Thank you.
