### ISSUE TITLE
[BUG] Logged-out users can view recipes, but not landing page

### ISSUE THREAD

**Issue by atomicthumbs** [mealie-recipes/mealie#4334]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I have enabled OIDC login for my organization and set my first recipe and the only group to public visibility. I have disabled the OIDC auto redirect in the settings. Logged-out users visiting the base subdomain of the site cannot see the recipes on it, as it redirects to the login page, but they can see individual recipes if given a link. This does not seem like intended behavior.

### Steps to Reproduce

1. log out when configured as stated above
2. attempt to view site.

### Please provide relevant logs

there is no relevant info in the logs.

### Mealie Version

build: [0d06494bbfc62fc8a1771a85fd308190891d6167](https://github.com/mealie-recipes/mealie/commit/0d06494bbfc62fc8a1771a85fd308190891d6167)
docker image: the official one.

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Have you checked out the FAQ? https://docs.mealie.io/documentation/getting-started/usage/permissions-and-public-access/

You'll want to make sure your group is configured correctly to enable public recipe browsing. Users will also be redirected to the login page if the default group slug in your env vars doesn't match your actual group's slug

**Comment by atomicthumbs** [comment]
The group is not private and there are no "household settings" present in the application, as far as I can find.

However, setting the "default group" environment variable to what I'd named it during the installation fixed it. Mentioning this in the docs would be helpful.

**Comment by michael-genson** [comment]
Yup, that should probably be in the docs. Glad that solved it!
