### ISSUE TITLE
[BUG] - Can not import from culy.nl

### ISSUE THREAD

**Issue by pgrond** [mealie-recipes/mealie#4348]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Example URL: https://www.culy.nl/recepten/cacio-e-pepe-aardappeltjes/
The source contains a script tag with ld+json:
	`<script type="application/ld+json" class="yoast-schema-graph">{"@context":"https://schema.org","@graph":[{"@type":"Article","@id":"https://www.culy.nl/recepten/cacio-e-pepe-aardappeltjes/#article","isPartOf":{"@id":"https://www.culy.nl/recepten/cacio-e-pepe-aardappeltjes/"},"author":{"name":"Nancy van Batenburg","@id":"https://www.culy.nl/#/schema/person/437fea7d6375d11b759d2e07f6051aa8"},"headline":"Culy Homemade: cacio e pepe aardappeltjes (een snel &#038; makkelijk bijgerecht)","datePublished":"2020-12-22T15:00:06+00:00","dateModified":"2020-12-18T11:45:27+00:00","mainEntityOfPage":{"@id":"https://www.culy.nl/recepten/cacio-e-pepe-aardappeltjes/"},"wordCount":240,"publisher":{"@id":"https://www.culy.nl/#organization"},"image":{"@id":"https://www.culy.nl/recepten/cacio-e-pepe-aardappeltjes/#primaryimage"},"thumbnailUrl":"https://www.culy.nl/wp-content/uploads/2020/12/4_cacio-e-pepe-aardappeltjes.jpg","keywords":["Aardappels","Bijgerecht","Culy Homemade","Feest","Kerstrecepten","Snelle recepten"],"articleSection":["Diner","Recepten","Snelle recepten","Soort","Vegetarische recepten","Wat eten we vandaag?"],"inLanguage":"nl-NL"},{"@type":"WebPage","@id":"https://www.culy.nl/recepten/cacio-e-pepe-aardappeltjes/","url":"https://www.culy.nl/recepten/cacio-e-pepe-aardappeltjes/","name":"Cacio e pepe aardappeltjes (makkelijk & snel bijgerecht) - Culy.nl","isPartOf":{"@id":"https://www.culy.nl/#website"},"primaryImageOfPage":{"@id":"https://www.culy.nl/recepten/cacio-e-pepe-aardappeltjes/#primaryimage"},"image":{"@id":"https://www.culy.nl/recepten/cacio-e-pepe-aardappeltjes/#primaryimage"},"thumbnailUrl":"https://www.culy.nl/wp-content/uploads/2020/12/4_cacio-e-pepe-aardappeltjes.jpg","datePublished":"2020-12-22T15:00:06+00:00","dateModified":"2020-12-18T11:45:27+00:00","description":"Een simpel en snel bijgerecht met stevige smaken: dat zijn deze cacio e pepe aardappeltjes. Maak ze voor kerst!","breadcrumb":{"@id":"https://www.culy.nl/recepten/cacio-e-pepe-aardappeltjes/#breadcrumb"},"inLanguage":"nl-NL","potentialAction":[{"@type":"ReadAction","target":["https://www.culy.nl/recepten/cacio-e-pepe-aardappeltjes/"]}]},{"@type":"ImageObject","inLanguage":"nl-NL","@id":"https://www.culy.nl/recepten/cacio-e-pepe-aardappeltjes/#primaryimage","url":"https://www.culy.nl/wp-content/uploads/2020/12/4_cacio-e-pepe-aardappeltjes.jpg","contentUrl":"https://www.culy.nl/wp-content/uploads/2020/12/4_cacio-e-pepe-aardappeltjes.jpg","width":6000,"height":4000,"caption":"Bron:"},{"@type":"BreadcrumbList","@id":"https://www.culy.nl/recepten/cacio-e-pepe-aardappeltjes/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://www.culy.nl/"},{"@type":"ListItem","position":2,"name":"Recepten","item":"https://www.culy.nl/recepten/"},{"@type":"ListItem","position":3,"name":"Culy Homemade: cacio e pepe aardappeltjes (een snel &#038; makkelijk bijgerecht)"}]},{"@type":"WebSite","@id":"https://www.culy.nl/#website","url":"https://www.culy.nl/","name":"Culy","description":"Dagelijks genieten","publisher":{"@id":"https://www.culy.nl/#organization"},"potentialAction":[{"@type":"SearchAction","target":{"@type":"EntryPoint","urlTemplate":"https://www.culy.nl/?s={search_term_string}"},"query-input":"required name=search_term_string"}],"inLanguage":"nl-NL"},{"@type":"Organization","@id":"https://www.culy.nl/#organization","name":"Culy","url":"https://www.culy.nl/","logo":{"@type":"ImageObject","inLanguage":"nl-NL","@id":"https://www.culy.nl/#/schema/logo/image/","url":"https://www.culy.nl/wp-content/uploads/2018/05/culy_logo.gif","contentUrl":"https://www.culy.nl/wp-content/uploads/2018/05/culy_logo.gif","width":143,"height":141,"caption":"Culy"},"image":{"@id":"https://www.culy.nl/#/schema/logo/image/"},"sameAs":["https://www.facebook.com/CulyNL","https://x.com/CulyNL","https://www.instagram.com/culynl/","https://nl.pinterest.com/culy/","https://www.youtube.com/user/CulyNL"]},{"@type":"Person","@id":"https://www.culy.nl/#/schema/person/437fea7d6375d11b759d2e07f6051aa8","name":"Nancy van Batenburg","image":{"@type":"ImageObject","url":"https://img.culy.nl/images/Vp24KP-SmCEXEEwrtItIdw0nVMw=/150x150/filters:quality(80):format(jpeg):background_color(fff)/https%3A%2F%2Fwww.culy.nl%2Fwp-content%2Fuploads%2F2020%2F03%2FDSC04534.jpg","caption":"Nancy van Batenburg"},"description":"Bedenkt elke week recepten voor Culy en bezoekt de beste restaurants om recensies over neer te pennen. Is voorstander van nose-to-tail-eating (zoals Fergus Henderson zegt: “It’s the polite thing to do”) en is dol op alles met venkel en (ster)anijs. De beste maaltijd ooit at ze bij Restaurant Blanca in New York. Van het pizzadeeg met boter raakte ze tot tranen geroerd.","sameAs":["http://www.instagram.com/nenznenz","https://www.linkedin.com/in/nancyvanbatenburg/"],"url":"https://www.culy.nl/author/nancy/"}]}</script>`

### Steps to Reproduce

- Import recipe with "Import from URL"
- Use https://www.culy.nl/recepten/cacio-e-pepe-aardappeltjes/ as URL
- Looks Like We Couldn't Find Anything

### Please provide relevant logs

ERROR    2024-10-11T13:45:55 - Recipe Scraper was unable to extract a recipe from https://www.culy.nl/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.culy.nl%2Frecepten%2Fcacio-e-pepe-aardappeltjes%2F

### Mealie Version

v1.12.0 
0d06494bbfc62fc8a1771a85fd308190891d6167 

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Can you share more logs? It imported fine on the demo: https://demo.mealie.io/g/home/r/cacio-e-pepe-aardappeltjes-makkelijk-snel-bijgerecht-culy-nl?edit=false

**Comment by pgrond** [comment]
Hmm, strange. Now it's working. Maybe some rate limiting on the site. Not a Mealie issue.
