### ISSUE TITLE
[BUG] - translation of units not working when plural is used

### ISSUE THREAD

**Issue by Jarod2801** [mealie-recipes/mealie#4380]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When I change the portions (e.g. from 1 to 2), the unit isn't anymore in my language (german).
The singular is fine but when using the plural it gets messed up.

### Steps to Reproduce

Check http://MEALIE_URL:PORT/group/data/units for the units.

I suggest the values are imported from the json file [https://github.com/mealie-recipes/mealie/blob/mealie-next/mealie/repos/seed/resources/units/locales/de-DE.json](url)

But the plurals are all in english although the german plurals are written in the file

![image](https://github.com/user-attachments/assets/d9562fa7-fc71-4907-a286-af1c94a7ad17)

`...
    "can": {
        "name": "Dose",
        "plural_name": "Dosen",
        "description": "",
        "abbreviation": ""
    },
...`

### Please provide relevant logs

---

### Mealie Version

Version v1.12.0

Build [0d06494bbfc62fc8a1771a85fd308190891d6167](https://github.com/mealie-recipes/mealie/commit/0d06494bbfc62fc8a1771a85fd308190891d6167)

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
We don't do any translations with food/units/labels. You have to add those yourself. Our seed data only has the singular version so you'll have to add plurals yourself (although in nightly we added support for plurals)

**Comment by Jarod2801** [comment]
OK, I edited it by myself.

But still curious why it initially mixes german end english and where the information came from.

EDIT: Looks to me like I have some translation issues.  In the timeline it says "Recipe Created", so also in english and not in german. But the german translation exists!

Have I done something terrible wrong when installing? Haven't read anything about it. 
I just noted the TZ environment variable in the docker compose.

**Comment by michael-genson** [comment]
> curious why it initially mixes german end english and where the information came from

Do you have any other users? Until nightly we don't auto-populate those fields, we only populate the name field when seeding

> In the timeline it says "Recipe Created", so also in english and not in german

I believe that only happens if you were using English when the recipe was created, but it could otherwise be a bug

**Comment by Jarod2801** [comment]
> Do you have any other users? Until nightly we don't auto-populate those fields, we only populate the name field when seeding

No, I am the only user as I installed it yesterday. Maybe I used some demo receipes when setting up. Cound be the cause. But I am not sure.

> I believe that only happens if you were using English when the recipe was created, but it could otherwise be a bug

When importing or creating receipes manually, the Ui was set to german as well.

I will make another test-install tomorrow and  have a look again.
