### ISSUE TITLE
[BUG] - No "login with Oauth" button

### ISSUE THREAD

**Issue by jmadden91** [mealie-recipes/mealie#4386]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Hi, currently running the nightly build and on a recent update I have lost the "login with Oauth" button, despite having it configured in my environment settings. 

If I spin up a new blank container it shows up and works as expected, but my backup fails to load into the new instance so I am stuck trying to fix my current instance.
![no button](https://github.com/user-attachments/assets/7ec73a8f-71df-486d-b63d-cb7b4683a1dd)
![button](https://github.com/user-attachments/assets/5296ef25-0d92-46aa-9798-55e0a8f9f266)

### Steps to Reproduce

As above

### Please provide relevant logs

INFO     2024-10-18T11:36:23 - Shutting down
INFO     2024-10-18T11:36:23 - Waiting for application shutdown.
INFO     2024-10-18T11:36:23 - -----SYSTEM SHUTDOWN----- 

INFO     2024-10-18T11:36:23 - Application shutdown complete.
INFO     2024-10-18T11:36:23 - Finished server process [1]

        User uid:    0
        User gid:    0
        
DEBUG    2024-10-18T11:36:26 - Language set to en
INFO     2024-10-18T11:36:32 - Started server process [1]
INFO     2024-10-18T11:36:32 - Waiting for application startup.
INFO     2024-10-18T11:36:32 - start: database initialization
INFO     2024-10-18T11:36:32 - Database connection established.
INFO     2024-10-18T11:36:32 - Context impl SQLiteImpl.
INFO     2024-10-18T11:36:32 - Will assume non-transactional DDL.
DEBUG    2024-10-18T11:36:32 - Migration not needed.
INFO     2024-10-18T11:36:32 - Checking for migration data fixes
DEBUG    2024-10-18T11:36:33 - No food found with slug: 'dairy-products-and-dairy-substitutes' skipping fix
DEBUG    2024-10-18T11:36:33 - No group found with an empty name; skipping fix
DEBUG    2024-10-18T11:36:33 - Database exists
INFO     2024-10-18T11:36:33 - end: database initialization
DEBUG    2024-10-18T11:36:33 - Registering daily callback: purge_group_registration
DEBUG    2024-10-18T11:36:33 - Registering daily callback: purge_password_reset_tokens
DEBUG    2024-10-18T11:36:33 - Registering daily callback: purge_group_data_exports
DEBUG    2024-10-18T11:36:33 - Registering daily callback: create_mealplan_timeline_events
DEBUG    2024-10-18T11:36:33 - Registering daily callback: delete_old_checked_list_items
DEBUG    2024-10-18T11:36:33 - Registering minutely callback: post_group_webhooks
DEBUG    2024-10-18T11:36:33 - Registering daily callback: locked_user_reset
DEBUG    2024-10-18T11:36:33 - Daily job: purge_group_registration
DEBUG    2024-10-18T11:36:33 - Daily job: purge_password_reset_tokens
DEBUG    2024-10-18T11:36:33 - Daily job: purge_group_data_exports
DEBUG    2024-10-18T11:36:33 - Daily job: create_mealplan_timeline_events
DEBUG    2024-10-18T11:36:33 - Daily job: delete_old_checked_list_items
DEBUG    2024-10-18T11:36:33 - Hourly job: locked_user_reset
DEBUG    2024-10-18T11:36:33 - Minutely job: post_group_webhooks
INFO     2024-10-18T11:36:33 - -----SYSTEM STARTUP-----
INFO     2024-10-18T11:36:33 - ------APP SETTINGS------
INFO     2024-10-18T11:36:33 - {
    "TESTING": false,
    "PRODUCTION": true,
    "LOG_CONFIG_OVERRIDE": null,
    "LOG_LEVEL": "debug",
    "theme": {
        "light_primary": "#E58325",
        "light_accent": "#007A99",
        "light_secondary": "#973542",
        "light_success": "#43A047",
        "light_info": "#1976D2",
        "light_warning": "#FF6D00",
        "light_error": "#EF5350",
        "dark_primary": "#E58325",
        "dark_accent": "#007A99",
        "dark_secondary": "#973542",
        "dark_success": "#43A047",
        "dark_info": "#1976D2",
        "dark_warning": "#FF6D00",
        "dark_error": "#EF5350"
    },
    "BASE_URL": "https://mealie.domain.com",
    "STATIC_FILES": "/spa/static",
    "IS_DEMO": false,
    "HOST_IP": "*",
    "API_HOST": "0.0.0.0",
    "API_PORT": 9000,
    "API_DOCS": true,
    "TOKEN_TIME": 48,
    "GIT_COMMIT_HASH": "292ff8313fgsfdgc8ca7f7133ff2c29702795",
    "ALLOW_SIGNUP": true,
    "DAILY_SCHEDULE_TIME": "23:45",
    "SECURITY_MAX_LOGIN_ATTEMPTS": 5,
    "SECURITY_USER_LOCKOUT_TIME": 24,
    "DB_ENGINE": "sqlite",
    "DEFAULT_GROUP": "Home",
    "DEFAULT_HOUSEHOLD": "Family",
    "SMTP_HOST": "smtp.gmail.com",
    "SMTP_PORT": "587",
    "SMTP_FROM_NAME": "mealie@domain.com",
    "SMTP_FROM_EMAIL": "mealie@domain.com",
    "SMTP_AUTH_STRATEGY": "TLS",
    "LDAP_AUTH_ENABLED": false,
    "LDAP_SERVER_URL": null,
    "LDAP_TLS_INSECURE": false,
    "LDAP_TLS_CACERTFILE": null,
    "LDAP_ENABLE_STARTTLS": false,
    "LDAP_BASE_DN": null,
    "LDAP_QUERY_BIND": null,
    "LDAP_USER_FILTER": null,
    "LDAP_ADMIN_FILTER": null,
    "LDAP_ID_ATTRIBUTE": "uid",
    "LDAP_MAIL_ATTRIBUTE": "mail",
    "LDAP_NAME_ATTRIBUTE": "name",
    "OIDC_AUTH_ENABLED": true,
    "OIDC_CLIENT_ID": "2w55ZM9hqpcBadsklfjh;sldkhj4398579hPhxWxl7mP9nL5av2",
    "OIDC_CONFIGURATION_URL": "https://auth.domain.com/application/o/mealie/.well-known/openid-configuration",
    "OIDC_SIGNUP_ENABLED": true,
    "OIDC_USER_GROUP": "public",
    "OIDC_ADMIN_GROUP": "administrators",
    "OIDC_AUTO_REDIRECT": false,
    "OIDC_PROVIDER_NAME": "OAuth",
    "OIDC_REMEMBER_ME": false,
    "OIDC_USER_CLAIM": "email",
    "OIDC_GROUPS_CLAIM": "groups",
    "OIDC_TLS_CACERTFILE": null,
    "OPENAI_BASE_URL": null,
    "OPENAI_MODEL": "gpt-4o",
    "OPENAI_CUSTOM_HEADERS": {},
    "OPENAI_CUSTOM_PARAMS": {},
    "OPENAI_ENABLE_IMAGE_SERVICES": true,
    "OPENAI_WORKERS": 2,
    "OPENAI_SEND_DATABASE_DATA": true,
    "OPENAI_REQUEST_TIMEOUT": 60,
    "WORKER_PER_CORE": 1,
    "UVICORN_WORKERS": 1
}
DEBUG    2024-10-18T11:36:33 - Local time: 23:45 | UTC time: 13:45
DEBUG    2024-10-18T11:36:33 - Current time is 2024-10-18 01:36:33.036562+00:00 and DAILY_SCHEDULE_TIME (in UTC) is ScheduleTime(hour=13, minute=45)
DEBUG    2024-10-18T11:36:33 - Time left: 12:08:27
INFO     2024-10-18T11:36:33 - Daily tasks scheduled for 2024-10-18 13:45:00+00:00
INFO     2024-10-18T11:36:33 - Application startup complete.
INFO     2024-10-18T11:36:33 - Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
INFO     2024-10-18T11:36:42 - [203.30.100.1:0] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-10-18T11:36:42 - [203.30.100.1:0] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-10-18T11:36:43 - [203.30.100.1:0] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-10-18T11:36:43 - [203.30.100.1:0] 200 OK "GET /api/explore/recipes/home?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1729215403119&searchSeed=1729215403119&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1"
INFO     2024-10-18T11:36:45 - [203.30.100.1:0] 304 Not Modified "GET /sw.js HTTP/1.1"
INFO     2024-10-18T11:36:46 - [203.30.100.1:0] 304 Not Modified "GET /g/home HTTP/1.1"
INFO     2024-10-18T11:36:49 - [203.30.100.1:0] 200 OK "GET /api/explore/groups/home/cookbooks?page=1&perPage=-1&orderBy=position&orderDirection=asc HTTP/1.1"
INFO     2024-10-18T11:36:49 - [203.30.100.1:0] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-10-18T11:36:49 - [203.30.100.1:0] 200 OK "GET /api/explore/groups/home/organizers/categories?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1"
INFO     2024-10-18T11:36:49 - [203.30.100.1:0] 200 OK "GET /api/explore/groups/home/foods?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1"
INFO     2024-10-18T11:36:49 - [203.30.100.1:0] 200 OK "GET /api/explore/groups/home/households?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1"
INFO     2024-10-18T11:36:49 - [203.30.100.1:0] 200 OK "GET /api/explore/groups/home/recipes?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1729215408816&searchSeed=1729215408816&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1"
INFO     2024-10-18T11:36:50 - [203.30.100.1:0] 200 OK "GET /api/explore/groups/home/organizers/tags?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1"
INFO     2024-10-18T11:36:50 - [203.30.100.1:0] 200 OK "GET /api/explore/groups/home/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1"
INFO     2024-10-18T11:36:53 - [203.30.100.1:0] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-10-18T11:36:53 - [203.30.100.1:0] 200 OK "GET /api/app/about/startup-info HTTP/1.1"
INFO     2024-10-18T11:36:54 - [203.30.100.1:0] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-10-18T11:36:54 - [203.30.100.1:0] 304 Not Modified "GET /sw.js HTTP/1.1"
INFO     2024-10-18T11:36:55 - [127.0.0.1:60870] 200 OK "GET /api/app/about HTTP/1.1"

### Mealie Version

nightly

### Deployment

Docker (Linux)

**Comment by cmintey** [comment]
OIDC implementation is getting updated for v2. If you're running nightly, then you'll need to go through the migration: https://docs.mealie.io/documentation/getting-started/authentication/oidc-v2/#migration-from-mealie-v1x

**Comment by jmadden91** [comment]
> OIDC implementation is getting updated for v2. If you're running nightly, then you'll need to go through the migration: https://docs.mealie.io/documentation/getting-started/authentication/oidc-v2/#migration-from-mealie-v1x

Ugh, sorry I should have read the docs more carefully. That has fixed it. Thank you very much!
