### ISSUE TITLE
[BUG] - Unable to delete groups

### ISSUE THREAD

**Issue by psybers** [mealie-recipes/mealie#4411]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Although there is a trash icon indicating groups should be able to be deleted, clicking it only goes to the edit page.  That page has no delete option.

Thus there is no way to delete a group (that I can find).

### Steps to Reproduce

1) create a new group
2) go to the groups page in settings
3) try clicking the trash

### Please provide relevant logs

none

### Mealie Version

2.0

### Deployment

Docker (Linux)

**Comment by Kuchenpirat** [comment]
This is a bit of a rabit hole but pretty easy to solve. 

- To delete a group you must first delete all households within that group. 
- To delete a household you must first delete all users within that household. 


I think we could communicate the requirements more clearly.

**Comment by psybers** [comment]
I see.  That definitely is not clear.  A note on the page might clarify that.

**Comment by Kuchenpirat** [comment]
#4414 adds a tooltip to the disabled delete icon describing why it might not be possible to delete a certain group / household.

**Comment by psybers** [comment]
Nice!

One other suggestion: is it possible to stop the click from going to the edit page?  Since the delete button is still drawn (but disabled) it is somewhat unexpected to click on it and go to the edit page.  That might also prevent people from seeing the new tooltip as they might just try to click it and then be confused as to why there is no delete option on the next page.
