### ISSUE TITLE
[BUG] - Error in scheduled task func='locked_user_reset'

### ISSUE THREAD

**Issue by andrewdunndev** [mealie-recipes/mealie#4426]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

In the logs, periodic:
```
Error in scheduled task func='locked_user_reset': exception='AllRepositories.__init__() got an unexpected keyword argument 'user_id''
```

Discussed [in discord](https://discord.com/channels/795445547577770014/795489645227671584/1298684000268845098).

/cc @michael-genson 

### Steps to Reproduce

1) Operating mealie `v2` container
2) Observe logs

My instance has been around for a while so potentially this is an older schemata issue

### Please provide relevant logs

When it manifests in logs it appears twice:
```
54a2cfa9c213 ERROR    2024-10-23T12:51:45 - Error in scheduled task func='locked_user_reset': exception='AllRepositories.__init__() got an unexpected keyword argument 'user_id''
54a2cfa9c213 ERROR    2024-10-23T12:51:45 - Error in scheduled task func='locked_user_reset': exception='AllRepositories.__init__() got an unexpected keyword argument 'user_id''
```

### Mealie Version

 - podman version 5.2.3
 - mealie `latest` `v2.0.0` container `b5e65f1389f6`

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Nope this is just me being dumb: https://github.com/mealie-recipes/mealie/pull/4342

That should be `household_id` not `user_id`. I even put `household_id` in the PR description.
