### ISSUE TITLE
[BUG] - Grossly excessive precission with decimal unit scaling

### ISSUE THREAD

**Issue by tecosaur** [mealie-recipes/mealie#4465]
##### I think this falls somewhere between a bug and a feature request, hope you don't mind this as an issue.

I've just started using Mealie with v2, and have noticed that scaling a recipe can result in absurd numbers. For instance, take this:

![image](https://github.com/user-attachments/assets/d042a231-2af9-44c4-a3b0-44ef15e02f94)

Scaling from 6 to 7, with the `gram` and `millilitre` units configured *not* to use fractions, I see:

![image](https://github.com/user-attachments/assets/ebaf27b9-1234-458b-9a79-e03cf28d5638)

Just for fun, I counted the number of decimal places. It goes down to tenths of a pico-gram! :joy: 

The main reason why I'd consider this a UI-bug type of thing is that it makes it harder to read the measurement at a glance while cooking. I'd recommend that a significant-figures type approach is used instead.

**Comment by Kuchenpirat** [comment]
Next time please fill out our bug report form correctly. 

What version are you on, i can't replicate this on nightly. 
This is what i get when scaling a recipe with some of the values from 6 to 7
```
466 2/3 g mascarpone
186 2/3 g sugar
```

**Comment by tecosaur** [comment]
I'm using v2.0.0.

Did you follow this step in my description? 

> with the gram and millilitre units configured not to use fractions

**Comment by Kuchenpirat** [comment]
Ah, sorry i didn't see the text between the images. 
Can replicate this with fractions off
We probably should round that to something like 3 digits. 

This wont make sense alot of sense for grams, milliliters and other small units, but as currently units are just strings we have no way of differentiating between big and small units in a meaningfull way.

**Comment by tecosaur** [comment]
Right, I think this can probably be handled decently in a unit-agnostic way though: I can't think of any instance where I've actually used more than 3 significant figures of measurement in a recipe, most of the time 2 is enough (particularly when scaling, since there are usually slight scaling effects). In this example, I'd think that `117` and `120` would both be a reasonable scaling of `100`ml increased by 1/6.

**Comment by Kuchenpirat** [comment]
This will be fixed by #4470

**Comment by tecosaur** [comment]
Brilliant, thanks for taking care of this!
