### ISSUE TITLE
[BUG] - Home Assistant Camera Entity broken?

### ISSUE THREAD

**Issue by mschut** [mealie-recipes/mealie#4499]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I was using the Home Assistant option to display the recipe of the day (https://docs.mealie.io/documentation/community-guide/home-assistant/). 

However, I notice it is not working anymore. If I cross check the description of the image url (.../api/media/recipes/...) to the API documentation (e.g.: https://demo.mealie.io/docs#/) I would assume that the api url has changed?

Is the documentation mentioned in https://docs.mealie.io/documentation/community-guide/home-assistant/ still correct, or am I missing something?

### Steps to Reproduce

1. Used the same setup as before, now got the error "Kan geen geldige afbeelding via de foto URL laden: de URL werd niet gevonden op de server." 
2. Trying to correct setup by following instructions at https://docs.mealie.io/documentation/community-guide/home-assistant/
3. Setup still correct, issue continues. 

### Please provide relevant logs

Cant think of relevant logs at the moment. 

### Mealie Version

Docker image and Mealie version Latest
Mealie: v2.1.0, build [b1278b45e24c0beaef2591519dfce8f260f692b9]

### Deployment

Docker (Synology)

**Comment by smrichards** [comment]
I recently had to fix this as well. The API endpoint has changed. Per this migration page: https://docs.mealie.io/contributors/developers-guide/migration-guide/ it has changed like this:

/groups/mealplans -> /households/mealplans

Update the url in your config and it should work again. I did it recently and its working again for me

**Comment by mschut** [comment]
Thanks, I already changed that. The name of the meals of today are visible, however the image is not working. Probably the url of the image (in the image entity) should be changed as well, I cant figure out what the change in this url should be. 

In the migration guide is states the url: 
http://mealie:9000/api/media/recipes/{{states('sensor.mealie_todays_meal_id')}}/images/min-original.webp 

This is in my setup unchanged, is seems like is needs no change (migration guide) but still it cant find any images anymore.

**Comment by mschut** [comment]
Feel stupid, had changed this in 1 place, but missed the second. ....
