### ISSUE TITLE
[BUG] - Account Locked and Can't unlock it with command

### ISSUE THREAD

**Issue by almulder** [mealie-recipes/mealie#4505]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I tried logging in to my hosted mealie and I get an Account Locked, found the documentation on the command to unlock it, but when I try I get an error

`# python /app/mealie/scripts/reset_locked_users.py
Are you sure you want to reset all locked users? (y/n) y
Traceback (most recent call last):
  File "/app/mealie/scripts/reset_locked_users.py", line 34, in <module>
    main()
  File "/app/mealie/scripts/reset_locked_users.py", line 20, in main
    locked_users = user_service.get_locked_users()
  File "/app/mealie/services/user_services/user_service.py", line 14, in get_locked_users
    return self.repos.users.get_locked_users()
  File "/usr/local/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/app/mealie/repos/repository_factory.py", line 173, in users
    return RepositoryUsers(self.session, PK_ID, User, PrivateUser, group_id=self.group_id)
  File "/app/mealie/repos/repository_generic.py", line 470, in __init__
    raise ValueError("group_id must be set")
ValueError: group_id must be set`

### Steps to Reproduce

lock a user and try using code to unlock it

### Please provide relevant logs

.

### Deployment

Unraid

**Comment by almulder** [comment]
Note: I was able to use adminer to unlock the user

**Comment by Art-of-Budi** [comment]
> Note: I was able to use adminer to unlock the user

How did you unlock your account?

**Comment by Kuchenpirat** [comment]
You should be able to use this script to unlock a user. 
https://docs.mealie.io/documentation/getting-started/faq/#how-can-i-unlock-my-account

**Comment by Art-of-Budi** [comment]
Thanks!

**Comment by onedayfishsale** [comment]
Just ran into this bug here as well, seems to still be an issue in the current version.
