### ISSUE TITLE
[BUG] - Toggling out of JSON view in the recipe editing interface the instruction section becomes read-only

### ISSUE THREAD

**Issue by chrispatin** [mealie-recipes/mealie#4509]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When a user toggles out of JSON view while editing a recipe, the instruction section becomes read-only and cannot be modified. This issue prevents users from making necessary updates to the recipe instructions after reviewing them in JSON format.

    

### Steps to Reproduce

Navigate to the recipe editing page.
Enter edit mode.
Toggle to JSON view.
Toggle back out of JSON view.
Attempt to edit the instruction section.

### Please provide relevant logs

-

### Mealie Version

Version: nightly
Build: 3e69ea94d5699da7ea1abe2fb77109bd38c8ded0 

### Deployment

Unraid

**Comment by Kuchenpirat** [comment]
Hey, thanks for reporting this issue. 
Can reproduce on demo 👍
