### ISSUE TITLE
[BUG] - Opening No Label section is extremely slow

### ISSUE THREAD

**Issue by andrew-codechimp** [mealie-recipes/mealie#4521]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

With the new collapsible labels, if you have items without a label opening/closing the No Label section takes multiple seconds whilst normal label sections are instant.

Reproducible in both Chrome and Safari
As labelled sections are performant I wonder if a DB call is being made and there is a bad index for null labels?

### Steps to Reproduce

Add multiple items to a shopping list, some with labels, some without
Enable Label Sorting
Try expanding/collapsing the No Label section and compare speed with a labelled section

### Please provide relevant logs

N/A

### Mealie Version

2.1.0
The demo site is running a nightly, but due to lack of semantic versioning on nightlies can't tell which one, but it doesn't have collapsible label sections.

### Deployment

Docker (Linux)

### Additional Deployment Details

Running on a Core i5 with under 10% average load so not a pc performance issue.

**Comment by michael-genson** [comment]
This should be fixed in nightly: https://github.com/mealie-recipes/mealie/pull/4513

**Comment by daniel-k** [comment]
I was experiencing the exact same issue (Docker image `latest`, so `v2.1`) and can confirm that the current nightly Docker image (8ce6f90) fixes it :tada: Thank you so much for building such an awesome tool!

**Comment by andrew-codechimp** [comment]
Thanks, I just updated my test instance with the latest nightly and that fixed it.
