### ISSUE TITLE
[BUG] - Unsecure Site - TLS_CERTIFICATE_PATH - ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by neooblaster** [mealie-recipes/mealie#4526]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

# Introducing Issue

Hello team,

I'm trying to secure with SSL my website to validate the following control : 

(Translation purpose: Unsecure website):
<img width="641" alt="image" src="https://github.com/user-attachments/assets/bfab8ab6-7e56-4b9b-9753-6cabe99426c9">

To achieve that, I tried to setup the following environment variables as indicated in the Documentation:

- TLS_CERTIFICATE_PATH
- TLS_PRIVATE_KEY_PATH

<img width="443" alt="image" src="https://github.com/user-attachments/assets/d45a7476-6fd9-41f2-8ecf-c3696eaed25b">

But once these two environment variables are configured, I getting the following error : ERR_SSL_PROTOCOL_ERROR

<img width="893" alt="image" src="https://github.com/user-attachments/assets/77278646-d6b9-463a-a414-3a53601c1af9">

<hr />

# Please find below the setting:

Maybe my paths are invalid, but I'm not able to find example to validate my setup

Environment Variables configuration:
<img width="404" alt="image" src="https://github.com/user-attachments/assets/7612c889-89d0-41fd-9af8-56d7ac521703">

Docker Volume Binding: 
<img width="862" alt="image" src="https://github.com/user-attachments/assets/b8c8afd1-38ec-4c4b-b2ab-484a57ca272c">

Mealie App Folder:
<img width="561" alt="image" src="https://github.com/user-attachments/assets/8e5d0ce0-5418-4ae2-878b-319d4b03041a">

SSL Folder created in the Mealie app folder:
<img width="567" alt="image" src="https://github.com/user-attachments/assets/19c664ed-c6c7-4d58-90a4-95f0266463fd">

Proof that certificat is valid for my domain name nicolas-dupre.fr (port should not responsible of the issue)
<img width="547" alt="image" src="https://github.com/user-attachments/assets/7c14d36f-a382-474c-b8ae-1e37b1ef631d">

Mealie is reachable but unsecure without setup of TLS environment variables: 
<img width="480" alt="image" src="https://github.com/user-attachments/assets/09319c4d-7cf0-4444-bed7-1b2520cb635b">

Mealie no longer reachable due to SSL Error when TLS environment variables are setup: 
<img width="833" alt="image" src="https://github.com/user-attachments/assets/7746787c-68b7-4bd4-b35e-ddb7b07ee845">

<hr />

# Support Request

I suppose it's a misconfiguration, but documentation do not provide me sufficient information to solve the issue by myself.

So questions : 

- What are the correct expected values for TLS_CERTIFICATE_PATH and TLS_PRIVATE_KEY_PATH ?
- Is the certificat .crt format is the correct format for Mealie ?
- How is the path ? I try will absolute path `/app/data/ssl/<file>` and relative `ssl/<file>` but none has solve the issue.

Sorry, to request support by raising a bug issue.

Thanks a lot for your help

Best regards,
Nicolas D.

### Steps to Reproduce

Configure container envionment variables : 

- TLS_CERTIFICATE_PATH
- TLS_PRIVATE_KEY_PATH

Start Container and try to reach again the service

Expected Result : Reachable & Secured website + Validation of check in app setting page allowing clipboard.

### Please provide relevant logs

Please find below log when container start with TLS_*_* environment variable (from cleared log file) : 

````ini
[WARNING|httptools_impl|L166] 2024-11-08T18:05:26: Invalid HTTP request received.
[WARNING|httptools_impl|L166] 2024-11-08T18:05:26: Invalid HTTP request received.
[INFO|httptools_impl|L468] 2024-11-08T18:05:30: 127.0.0.1:38690 - "GET /api/app/about HTTP/1.1" 200
[INFO|httptools_impl|L468] 2024-11-08T18:06:01: 127.0.0.1:38740 - "GET /api/app/about HTTP/1.1" 200
[INFO|httptools_impl|L468] 2024-11-08T18:06:32: 127.0.0.1:38786 - "GET /api/app/about HTTP/1.1" 200
[INFO|server|L262] 2024-11-08T18:06:40: Shutting down
[INFO|on|L67] 2024-11-08T18:06:40: Waiting for application shutdown.
[INFO|app|L84] 2024-11-08T18:06:40: -----SYSTEM SHUTDOWN----- 

[INFO|on|L76] 2024-11-08T18:06:40: Application shutdown complete.
[INFO|server|L92] 2024-11-08T18:06:40: Finished server process [1]
````

Please find below log when container start withou TLS_*_* environment variable

````ini
[INFO|server|L82] 2024-11-08T18:34:08: Started server process [1]
[INFO|on|L48] 2024-11-08T18:34:08: Waiting for application startup.
[INFO|app|L53] 2024-11-08T18:34:08: start: database initialization
[INFO|init_db|L93] 2024-11-08T18:34:08: Database connection established.
[INFO|migration|L215] 2024-11-08T18:34:08: Context impl SQLiteImpl.
[INFO|migration|L218] 2024-11-08T18:34:08: Will assume non-transactional DDL.
[INFO|fix_migration_data|L203] 2024-11-08T18:34:08: Checking for migration data fixes
[INFO|app|L57] 2024-11-08T18:34:08: end: database initialization
[INFO|app|L61] 2024-11-08T18:34:08: -----SYSTEM STARTUP-----
[INFO|app|L62] 2024-11-08T18:34:08: ------APP SETTINGS------
[INFO|app|L63] 2024-11-08T18:34:08: {
    "TESTING": false,
    "PRODUCTION": true,
    "LOG_CONFIG_OVERRIDE": null,
    "LOG_LEVEL": "info",
    "theme": {
        "light_primary": "#E58325",
        "light_accent": "#007A99",
        "light_secondary": "#973542",
        "light_success": "#43A047",
        "light_info": "#1976D2",
        "light_warning": "#FF6D00",
        "light_error": "#EF5350",
        "dark_primary": "#E58325",
        "dark_accent": "#007A99",
        "dark_secondary": "#973542",
        "dark_success": "#43A047",
        "dark_info": "#1976D2",
        "dark_warning": "#FF6D00",
        "dark_error": "#EF5350"
    },
    "BASE_URL": "https://nicolas-dupre.fr:9000",
    "STATIC_FILES": "/spa/static",
    "IS_DEMO": false,
    "HOST_IP": "*",
    "API_HOST": "0.0.0.0",
    "API_PORT": 9000,
    "API_DOCS": true,
    "TOKEN_TIME": 48,
    "GIT_COMMIT_HASH": "53a566d08ab5b639671ee8abe1ad5a45dfdccc5a",
    "ALLOW_SIGNUP": false,
    "DAILY_SCHEDULE_TIME": "23:45",
    "SECURITY_MAX_LOGIN_ATTEMPTS": 5,
    "SECURITY_USER_LOCKOUT_TIME": 24,
    "DB_ENGINE": "sqlite",
    "DEFAULT_GROUP": "Home",
    "DEFAULT_HOUSEHOLD": "Family",
    "SMTP_HOST": "neoapps.fr",
    "SMTP_PORT": "587",
    "SMTP_FROM_NAME": "Mealie",
    "SMTP_FROM_EMAIL": "mealie@nicolas-dupre.fr",
    "SMTP_AUTH_STRATEGY": "TLS",
    "LDAP_AUTH_ENABLED": false,
    "LDAP_SERVER_URL": null,
    "LDAP_TLS_INSECURE": false,
    "LDAP_TLS_CACERTFILE": null,
    "LDAP_ENABLE_STARTTLS": false,
    "LDAP_BASE_DN": null,
    "LDAP_QUERY_BIND": null,
    "LDAP_USER_FILTER": null,
    "LDAP_ADMIN_FILTER": null,
    "LDAP_ID_ATTRIBUTE": "uid",
    "LDAP_MAIL_ATTRIBUTE": "mail",
    "LDAP_NAME_ATTRIBUTE": "name",
    "OIDC_AUTH_ENABLED": false,
    "OIDC_CLIENT_ID": null,
    "OIDC_CONFIGURATION_URL": null,
    "OIDC_SIGNUP_ENABLED": true,
    "OIDC_USER_GROUP": null,
    "OIDC_ADMIN_GROUP": null,
    "OIDC_AUTO_REDIRECT": false,
    "OIDC_PROVIDER_NAME": "OAuth",
    "OIDC_REMEMBER_ME": false,
    "OIDC_USER_CLAIM": "email",
    "OIDC_GROUPS_CLAIM": "groups",
    "OIDC_TLS_CACERTFILE": null,
    "OPENAI_BASE_URL": null,
    "OPENAI_MODEL": "gpt-4o",
    "OPENAI_CUSTOM_HEADERS": {},
    "OPENAI_CUSTOM_PARAMS": {},
    "OPENAI_ENABLE_IMAGE_SERVICES": true,
    "OPENAI_WORKERS": 2,
    "OPENAI_SEND_DATABASE_DATA": true,
    "OPENAI_REQUEST_TIMEOUT": 60,
    "WORKER_PER_CORE": 1,
    "UVICORN_WORKERS": 1
}
[INFO|scheduler_service|L49] 2024-11-08T18:34:08: Daily tasks scheduled for 2024-11-08 23:45:00+00:00
[INFO|on|L62] 2024-11-08T18:34:08: Application startup complete.
[INFO|server|L214] 2024-11-08T18:34:08: Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
[WARNING|httptools_impl|L166] 2024-11-08T18:34:08: Invalid HTTP request received.
[WARNING|httptools_impl|L166] 2024-11-08T18:34:08: Invalid HTTP request received.
[WARNING|httptools_impl|L166] 2024-11-08T18:34:17: Invalid HTTP request received.
[WARNING|httptools_impl|L166] 2024-11-08T18:34:17: Invalid HTTP request received.
[INFO|httptools_impl|L468] 2024-11-08T18:34:25: 127.0.0.1:41090 - "GET /api/app/about HTTP/1.1" 200
[WARNING|httptools_impl|L166] 2024-11-08T18:34:33: Invalid HTTP request received.
[WARNING|httptools_impl|L166] 2024-11-08T18:34:33: Invalid HTTP request received.
[INFO|httptools_impl|L468] 2024-11-08T18:34:33: 172.17.0.1:45734 - "GET /api/users/self HTTP/1.1" 200
[INFO|httptools_impl|L468] 2024-11-08T18:34:33: 172.17.0.1:45734 - "GET /api/app/about HTTP/1.1" 200
[INFO|httptools_impl|L468] 2024-11-08T18:34:33: 172.17.0.1:45736 - "GET /api/app/about/startup-info HTTP/1.1" 200
[INFO|httptools_impl|L468] 2024-11-08T18:34:34: 172.17.0.1:45738 - "GET /api/app/about HTTP/1.1" 200
[INFO|httptools_impl|L468] 2024-11-08T18:34:34: 172.17.0.1:45736 - "GET /api/households/self HTTP/1.1" 200
[INFO|httptools_impl|L468] 2024-11-08T18:34:34: 172.17.0.1:45734 - "GET /api/households/cookbooks?page=1&perPage=-1&orderBy=position&orderDirection=asc HTTP/1.1" 200
[INFO|httptools_impl|L468] 2024-11-08T18:34:34: 172.17.0.1:45742 - "GET /api/groups/members?page=1&perPage=-1&orderBy=full_name&orderDirection=asc HTTP/1.1" 200
[INFO|httptools_impl|L468] 2024-11-08T18:34:34: 172.17.0.1:45744 - "GET /api/organizers/categories?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200
[INFO|httptools_impl|L468] 2024-11-08T18:34:34: 172.17.0.1:45738 - "GET /api/organizers/tags?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200
[INFO|httptools_impl|L468] 2024-11-08T18:34:34: 172.17.0.1:45734 - "GET /api/organizers/tools?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200
[INFO|httptools_impl|L468] 2024-11-08T18:34:34: 172.17.0.1:45736 - "GET /api/groups/households?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200
[INFO|httptools_impl|L468] 2024-11-08T18:34:34: 172.17.0.1:45744 - "GET /api/media/users/5dc04023-4a2b-4ca3-b0ba-527441771f9c/profile.webp?cacheKey=1234 HTTP/1.1" 200
[INFO|httptools_impl|L468] 2024-11-08T18:34:34: 172.17.0.1:45742 - "GET /api/recipes?page=1&perPage=64&orderBy=created_at&orderDirection=desc&paginationSeed=1731090875466&searchSeed=1731090875466&search=&requireAllCategories=false&requireAllTags=false&requireAllTools=false&requireAllFoods=false HTTP/1.1" 200
[INFO|httptools_impl|L468] 2024-11-08T18:34:34: 172.17.0.1:45734 - "GET /api/media/recipes/de8f62b1-d178-4a10-8b33-a659185703af/images/min-original.webp?rnd=1&version=GHQv HTTP/1.1" 200
[INFO|httptools_impl|L468] 2024-11-08T18:34:34: 172.17.0.1:45744 - "GET /api/households/recipe-actions?page=1&perPage=-1&orderBy=title&orderDirection=asc HTTP/1.1" 200
[INFO|httptools_impl|L468] 2024-11-08T18:34:34: 172.17.0.1:45742 - "GET /api/users/self/ratings HTTP/1.1" 200
[INFO|httptools_impl|L468] 2024-11-08T18:34:34: 172.17.0.1:45740 - "GET /api/foods?page=1&perPage=-1&orderBy=name&orderDirection=asc HTTP/1.1" 200
[WARNING|httptools_impl|L166] 2024-11-08T18:34:47: Invalid HTTP request received.
[WARNING|httptools_impl|L166] 2024-11-08T18:34:47: Invalid HTTP request received.
[INFO|httptools_impl|L468] 2024-11-08T18:34:56: 127.0.0.1:41154 - "GET /api/app/about HTTP/1.1" 200
[INFO|httptools_impl|L468] 2024-11-08T18:35:27: 127.0.0.1:41196 - "GET /api/app/about HTTP/1.1" 200

````

### Mealie Version

**Details**
Version: v2.1.0
Build: 53a566d08ab5b639671ee8abe1ad5a45dfdccc5a
Mode de l’application: Réalisation
Mode démo: Non
Port de l’API: 9000
Documentation de l’API: Activé
Type de base de données: sqlite
Foyer par défaut: Family
Version du Scraper de recette: 15.2.1

**Checks**
Site sécurisé: Non
URL de base côté serveur: Oui
Prêt pour LDAP: Non
Prêt pour OIDC: Non
Prêt pour OpenAI: Non
E-mail configuré: Oui

### Deployment

Docker (Synology)

### Additional Deployment Details

````json
{
   "CapAdd" : [],
   "CapDrop" : [],
   "cmd" : "",
   "cpu_priority" : 50,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : false,
   "enable_service_portal" : null,
   "enabled" : false,
   "env_variables" : [
      {
         "key" : "PATH",
         "value" : "/opt/poetry/bin:/opt/pysetup/.venv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "LANG",
         "value" : "C.UTF-8"
      },
      {
         "key" : "GPG_KEY",
         "value" : "A035C8C19219BA821ECEA86B64E628F8D684696D"
      },
      {
         "key" : "PYTHON_VERSION",
         "value" : "3.10.15"
      },
      {
         "key" : "PYTHON_SHA256",
         "value" : "aab0950817735172601879872d937c1e4928a57c409ae02369ec3d91dccebe79"
      },
      {
         "key" : "MEALIE_HOME",
         "value" : "/app"
      },
      {
         "key" : "PYTHONUNBUFFERED",
         "value" : "1"
      },
      {
         "key" : "PYTHONDONTWRITEBYTECODE",
         "value" : "1"
      },
      {
         "key" : "PIP_NO_CACHE_DIR",
         "value" : "off"
      },
      {
         "key" : "PIP_DISABLE_PIP_VERSION_CHECK",
         "value" : "on"
      },
      {
         "key" : "PIP_DEFAULT_TIMEOUT",
         "value" : "100"
      },
      {
         "key" : "POETRY_HOME",
         "value" : "/opt/poetry"
      },
      {
         "key" : "POETRY_VIRTUALENVS_IN_PROJECT",
         "value" : "true"
      },
      {
         "key" : "POETRY_NO_INTERACTION",
         "value" : "1"
      },
      {
         "key" : "PYSETUP_PATH",
         "value" : "/opt/pysetup"
      },
      {
         "key" : "VENV_PATH",
         "value" : "/opt/pysetup/.venv"
      },
      {
         "key" : "PRODUCTION",
         "value" : "true"
      },
      {
         "key" : "TESTING",
         "value" : "false"
      },
      {
         "key" : "GIT_COMMIT_HASH",
         "value" : "53a566d08ab5b639671ee8abe1ad5a45dfdccc5a"
      },
      {
         "key" : "LD_LIBRARY_PATH",
         "value" : "/usr/local/lib"
      },
      {
         "key" : "APP_PORT",
         "value" : "9000"
      },
      {
         "key" : "STATIC_FILES",
         "value" : "/spa/static"
      },
      {
         "key" : "HOST",
         "value" : "192.168.1.98"
      },
      {
         "key" : "BASE_URL",
         "value" : "https://nicolas-dupre.fr:9000"
      },
      {
         "key" : "SMTP_HOST",
         "value" : "neoapps.fr"
      },
      {
         "key" : "SMTP_PORT",
         "value" : "587"
      },
      {
         "key" : "SMTP_USER",
         "value" : "***********"
      },
      {
         "key" : "SMTP_PASSWORD",
         "value" : "***********"
      },
      {
         "key" : "SMTP_FROM_EMAIL",
         "value" : "mealie@nicolas-dupre.fr"
      },
      {
         "key" : "TLS_CERTIFICATE_PATH",
         "value" : "ssl/certificate.crt"
      },
      {
         "key" : "TLS_PRIVATE_KEY_PATH",
         "value" : "ssl/private.key"
      }
   ],
   "exporting" : false,
   "id" : "7a2259c7e8e863460a9753111939fd88b7e41b159247717a49c15fbafd50e2f1",
   "image" : "hkotel/mealie:latest",
   "is_ddsm" : false,
   "is_package" : false,
   "labels" : {
      "org.opencontainers.image.source" : "https://github.com/mealie-recipes/mealie"
   },
   "links" : [],
   "memory_limit" : 0,
   "name" : "mealie",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "bridge"
      }
   ],
   "network_mode" : "bridge",
   "port_bindings" : [
      {
         "container_port" : 9000,
         "host_port" : 9000,
         "type" : "tcp"
      }
   ],
   "privileged" : false,
   "service_portals" : [],
   "shortcut" : {
      "enable_shortcut" : false,
      "enable_status_page" : false,
      "enable_web_page" : false,
      "web_page_url" : ""
   },
   "use_host_network" : false,
   "version" : 2,
   "volume_bindings" : [
      {
         "host_volume_file" : "/docker/volumes/mealie",
         "is_directory" : true,
         "mount_point" : "/app/data",
         "type" : "rw"
      }
   ]
}

````

**Comment by hay-kot** [comment]
Hey! We don't handle any of the actual TLS stuff, we just pass those values to Uvicorn (the web server we use) so we might not be able to help much here. Their documentation also doesn't go into much more detail

https://www.uvicorn.org/deployment/#running-with-https

Their example does provide `.pem` files for both variables though, so maybe that can point you in the right direction?

**Comment by neooblaster** [comment]
Hello @hay-kot ,

Oh okay !
I will try to go deeper with the documentation and using the terminal.

Can we keep a while the issue opened while I'm trying to solve the issue ?
Maybe I will be able to provide some feedback.

Thanks for your prompt reply.

Best regards,
Nicolas

**Comment by neooblaster** [comment]
Hello @hay-kot ,

I succeeded to set SSL Certificate and get security check set as Secure Website : 

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/7712542c-13df-41ef-8200-3bb1c775cb7b">

<hr />

# Procedure to set SSL Certificate

Please find below change I made to achive that : 

## 1. Use Symbolinc link to manipulate safely the container endpoint `run.sh`

In the bound volume folder handling `/app/data`, I created an new folder named `extends`

<img width="620" alt="image" src="https://github.com/user-attachments/assets/5864f08d-5cb5-486c-9e02-9b4557b801d3">

- Then, run a terminal on the container
- Go in the folder `/app` with command `cd /app`
- Make a backup of the file `run.sh` with command `cp run.sh run.sh.bak`
- Make an another copy in the folder `extends` with command `cp run.sh /app/data/extends/run.sh`
- Then remove file `run.sh` to with command `rm run.sh`
- Create the symbolic link with command `ln -s /app/data/extends/run.sh run.sh` (cf.1) 
- Check the link with command `ls -alh` (cf.2) 

<img width="707" alt="image" src="https://github.com/user-attachments/assets/a97417d0-791f-4431-985d-349d03af6f8b">

## 2. Update `run.sh` and adapt `main.py`

- Go in folder `/app/mealie` with command `cd /app/mealie`
- Make a copy of the file `main.py` named `main-ssl.py` in the folder `extends` with command `cp main.py /app/data/extends/main-ssl.py`
- Update `run.sh` file in the folder `/app/data/extends/run.sh` : 

````bash
# Copy main-ssl.py
cp /app/data/extends/main-ssl.py /app/mealie/main-ssl.py

# run app
#exec python /app/mealie/main.py
exec python /app/mealie/main-ssl.py
```` 

<img width="808" alt="image" src="https://github.com/user-attachments/assets/fd6df66c-df67-4023-bcb0-fbfe6f4ae99c">

> By manipulating this `run.sh`, you will be able to revert to original `main.py` if you encounter an error. Indeed, if the
> command `exec python main-ssl.py` failed, you will no longer able to open a terminal in the container (Synology setup).

- In the file `/app/data/extends/main-ssl.py`, add the two following options : 
    - `ssl_certificate`
    - `ssl_keyfile`

<img width="466" alt="image" src="https://github.com/user-attachments/assets/b889b242-8e2d-4618-9fc3-12c97645fcdd">

- restart the container to rerun file `run.sh` : 

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/76d04b16-1b3b-4f5a-8ad6-8c605ae2f437">

Go to the application portal with `https` and check the SSL Certifcate status : 

<img width="584" alt="image" src="https://github.com/user-attachments/assets/000fdf0a-5c75-4fb6-8e4b-ba90aad59208">

You did it !

Thanks a lot @hay-kot for your help.

# Source Links : 

- [Uvicorn - Settings](https://www.uvicorn.org/settings/)
- [Uvicorn - Deployment](https://www.uvicorn.org/deployment/)
- [Enable https using UVICORN](https://stackoverflow.com/questions/69207474/enable-https-using-uvicorn)
