### ISSUE TITLE
[BUG] - No link/button nor sufficient documentation how to get to the `notifiers` screen

### ISSUE THREAD

**Issue by brumik** [mealie-recipes/mealie#4533]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

The documentation does not provide sufficient information how to get to the `create notifier` screen (`/household/notifiers/`).

There is also no UI button (as far as I can see) to get to this page. The way I was only able to figure it out to go to the demo page from `Documentation > Nofifier Demo (button)` and steal the URL from there.

### Steps to Reproduce

N.A.

### Please provide relevant logs

N.A.

### Mealie Version

2.1.0

### Deployment

Docker (Linux)

**Comment by Kuchenpirat** [comment]
Notifiers can be reached by clicking on your profile picture in the Navigation drawer and then on Notifiers.

This is where almost all of non admin settings can be found so I don't think this is too hidden.
