### ISSUE TITLE
[BUG] - images are not correctly imported from gotvach.bg

### ISSUE THREAD

**Issue by npelov** [mealie-recipes/mealie#4564]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

The URL of the recipe(s) that are not being scraped correctly

example recipe urls (fail to import the image):
https://recepti.gotvach.bg/r-4531-%D0%9E%D0%BC%D0%BB%D0%B5%D1%82_%D0%A3%D0%BD%D0%B8%D0%BA%D0%B0%D1%82
https://recepti.gotvach.bg/r-43121-%D0%9E%D0%BC%D0%BB%D0%B5%D1%82_%D1%81_%D0%BA%D0%B0%D1%88%D0%BA%D0%B0%D0%B2%D0%B0%D0%BB

example image urls (fail with import image from url):
https://recepti.gotvach.bg/files/lib/600x350/omlet4.webp
https://recepti.gotvach.bg/files/lib/600x350/omlet-kashkaval5.webp

### Steps to Reproduce

1. import any recipe from https://recepti.gotvach.bg/
2. recipe image not imported.
3. try to import image from url https://recepti.gotvach.bg/files/lib/600x350/omlet4.webp
4. doesn't work
5. download the image and upload from computer - works

### Please provide relevant logs

I don't have any

### Mealie Version

Version: v2.1.0
Build: 53a566d08ab5b639671ee8abe1ad5a45dfdccc5a

### Deployment

Docker (Linux)

**Comment by jhollowe** [comment]
This is likely something that needs to be fixed in [recipe-scrapers](https://github.com/hhursev/recipe-scrapers) instead of Mealie.

**Comment by npelov** [comment]
Well it's either one or the other you can't be both right:
https://github.com/hhursev/recipe-scrapers/issues/1366
