### ISSUE TITLE
[BUG] - Mealie sends Authentik https://127.0.0.1:9925/login as redirect URL

### ISSUE THREAD

**Issue by ryan-mca** [mealie-recipes/mealie#4579]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I am trying to set up OIDC with Authentik as me IdP.
Both my Authentik server and Mealie server are behind Cloudflare proxies, however that hasn't affected other services.

### Steps to Reproduce

1) Setup OIDC in docker-compose.yml
2) Setup Mealie OIDC provider and application in Authentik
3) Successfully log-in to Authentik
4) Authentik either responds with redirect_uri error or redirects to https://127.0.0.1:9925/login

### Please provide relevant logs

mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.2.0 # 
    container_name: mealie
    restart: always
    ports:
        - "9925:9000" # 
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - ./mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
      BASE_URL: "https://mealie.domain.com"

     # OpenID/OAUTH
      OIDC_AUTH_ENABLED: "True"
      OIDC_SIGNUP_ENABLED: "True"
      OIDC_CONFIGURATION_URL: "https://auth.domain.com/application/o/mealie/.well-known/openid-configuration"
      OIDC_CLIENT_ID: "client id"
      OIDC_CLIENT_SECRET: "client secret"
      OIDC_ADMIN_GROUP: "MealieAdmins"
      OIDC_AUTO_REDIRECT: "False"
      OIDC_PROVIDER_NAME: "Authentik"
      OIDC_REMEMBER_ME: "True"

### Mealie Version

ghcr.io/mealie-recipes/mealie:v2.2.0

### Deployment

Docker (Linux)

### Additional Deployment Details

Authentik is currently working as an OIDC provider for a couple other services

**Comment by cmintey** [comment]
Your proxy is likely misconfigured. Make sure it's configured to forward the correct headers. `X-Forwarded-For`, `Host`, and `X-Forwarded-Proto`.

Somewhat related: https://github.com/mealie-recipes/mealie/issues/4482

**Comment by ryan-mca** [comment]
Thanks, I can't believe it was something that simple. It's working perfectly.
