### ISSUE TITLE
[BUG] - Unable to Use Google App Password

### ISSUE THREAD

**Issue by tucker19** [mealie-recipes/mealie#4589]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I am trying to use a Google App Password but these passwords have spaces in them and Docker is not picking it up correctly

### Steps to Reproduce

1) Create an App Password with Gmail account using these steps https://support.google.com/accounts/answer/185833?hl=en
2) Setup email with 
```
     SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 465
      SMTP_FROM_EMAIL: <gmail_email>
      SMTP_USER: <gmail_email>
      SMTP_PASSWORD: <APP_PASSWORD>
```
example App Password `aaaa bbbb cccc dddd`
3) Try to test email 

### Please provide relevant logs

ERROR    2024-11-21T11:20:58 - Connection unexpectedly closed: timed out

### Mealie Version

**Details**
Version: v2.2.0
Build: 65c35adc9d46fe319f9e949353cd02519d0041ae
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: postgres
Default Household: Family
Recipe Scraper Version: 15.2.1

**Checks**
Secure Site: Yes
Server Side Base URL: No
LDAP Ready: No
OIDC Ready: No
OpenAI Ready: No
Email Configured: Yes - Not Working

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Have you confirmed it works outside of Mealie? There are a bunch of different ways that Google prevents SMTP from working, even with app passwords.

As another troubleshooting method, try TLS instead (switch the port to `587` and set `SMTP_AUTH_STRATEGY` to `TLS`)

**Comment by tucker19** [comment]
I have this setup within my Calibre-Web Server and works fine. Granted I am not inputting the values via Docker but within the web ui itself. Will try suggestions too.

**Comment by tucker19** [comment]
New Log message after switching port and adding auth strat `ERROR    2024-11-21T11:39:13 - (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 8926c6da1cb9f-4e1cfe1a0d7sm62697173.23 - gsmtp')`

**Comment by tucker19** [comment]
Well it starting working now so will close. Must have been the Port but thats the same port I use with other Containers
