### ISSUE TITLE
Ability to add LOCAL videos 

### ISSUE THREAD

**Issue by AnnieSixgun** [mealie-recipes/mealie#4597]
### Discussed in https://github.com/mealie-recipes/mealie/discussions/819

<div type='discussions-op-text'>

<sup>Originally posted by **NightMean** November 23, 2021</sup>
**Before submitting this feature request I have**
- [x] Reviewed the documentation and verified that my feature request isn't already a feature.
- [x] Reviewed the existing feature requests and my feature has not been requested.
- [x] Checked the [tasks taged](https://github.com/hay-kot/mealie/issues?q=is%3Aissue+is%3Aopen+label%3Atask+) issues and verified my feature is not covered.

**Please Describe The Problem To Be Solved**
Playing a LOCAL video within a mealie recipe
 
All of my family recipes have preparation videos made by me forinstructing my kids and grand kids  on HOW  to make all the family recipes .. We have even created videos of hand written recipes from our great grandmother.

Right now we look up the recipe on my computer,  watch it. and make the recipe
 
If a local video could be viewed while within its associated mealie recipe that would be great.  
watch the instruction video while creating the recipe.

Yes I know about iframe and importing video from online web sites like youtube, but I only want to import from a local folder.

**Suggestion:**
- Include a way to play a LOCALLY stored recipe video while in a mealie recipe and display the video in the image area at the top of the recipe

**Second suggestion:**
- Include a way to access a LOCALLY stored recipe video into a mealie recipe  within a recipe STEP

Thanks

**Comment by Kuchenpirat** [comment]
Hey,
First of all this is a feature request not an issue, so please use the relevant template in the discussion board. 

Also in the thread you linked this from is a explanation on how to add local video and embedded them into a recipe step. So I would suggest you follow this guide. 
https://github.com/mealie-recipes/mealie/discussions/819#discussioncomment-3024064

I'll go ahead and close this, if there is more needed around this I can convert this into a discussion.
