### ISSUE TITLE
[BUG] - Date format hint is incorrect (and probably irrelevant)

### ISSUE THREAD

**Issue by markalex2209** [mealie-recipes/mealie#4598]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When adding recipe to the meal plan, date field in dialog box shows a hint `MM/DD/YYYY format`, but then date itself is shown in format `2024-11-13`.
I see that hint changes with change in language, but format of the date is not.
Additionally, AFAICT this field is not intended to be manually edited (`readonly="readonly"`) so maybe whole hint should be dropped?

Setup used to reproduce:
Firefox 128.4.0esr on Windows 11. 
System date format dd.mm.yyyy

### Steps to Reproduce

1. Three dots on recipe
2. Add to Plan
3. Select any date

### Please provide relevant logs

UI only, no logs

### Mealie Version

2.2.0

### Deployment

Docker (Synology)

**Comment by BavyaMittal** [comment]
Hello my name is Bavya and I am a software engineering student looking for a good first issue. I would like to try resolving this issue. Can I work on this if no one else is assigned yet?

**Comment by michael-genson** [comment]
Sure thing! We generally don't assign issues, anyone is welcome to open a PR!
