### ISSUE TITLE
[BUG] - First day of the week in date picker

### ISSUE THREAD

**Issue by markalex2209** [mealie-recipes/mealie#4599]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Regardless of the locale date picker uses Sunday a first day of the week.

As far as I can tell, vuetify's datepicker supports change of the first day out of the box with localization, but it might be that it was overwritten somehow.

### Steps to Reproduce

Change locale to non-Sunday-first one (for example any european except Portugal), and see Sunday still being the first day in picker, for example in the meal option > add to Plan.

### Please provide relevant logs

UI only, no logs

### Mealie Version

2.2.0

### Deployment

Docker (Synology)

**Comment by michael-genson** [comment]
You should be able to change this with your household preferences:
![image](https://github.com/user-attachments/assets/2b8848bd-393c-4aff-9f5e-f5c943ec6b46)

Let me know if that works for you. I remember a while back this was broken, but I'm pretty sure we fixed it

**Comment by markalex2209** [comment]
Yep, found it there. And it works.

Still would like to point out that this config being household-wide is a somewhat strange decision. Especially since localization is per-user, and datetime format and first day of the week are (at least in most cases) related to localization.

Also, please correct me if I'm wrong, but it doesn't look like configuration for this is described anywhere in the docs.

**Comment by michael-genson** [comment]
> this config being household-wide is a somewhat strange decision

It's because it gets used for webhooks, which are household-wide. When we send a week's meals via webhook we need to know where the start of the week is. I agree that for the frontend this could probably be tied to language instead, or at least a user-level setting somewhere

> it doesn't look like configuration for this is described anywhere in the docs

I don't think it is, we'd would welcome a PR adding it somewhere!
