### ISSUE TITLE
[BUG] - Multiple GET requests with escalating port numbers

### ISSUE THREAD

**Issue by stusemple** [mealie-recipes/mealie#4613]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I am seeing multiple (every minute) http GET requests all to the same address, each with a different port number.

### Steps to Reproduce

this appears in my logs as soon as i start the mealie container

### Please provide relevant logs

<img width="480" alt="image" src="https://github.com/user-attachments/assets/0b5a6a35-cda8-4012-9192-c2d0a00dfb96">

### Deployment

Docker (Synology)

**Comment by PeterJT** [comment]
This is the docker heartbeat / healthcheck running.

**Comment by hay-kot** [comment]
Like @PeterJT said, it's the health check running I don't see any issue here.
