### ISSUE TITLE
[SCRAPER] - Savory by Stop & Shop

### ISSUE THREAD

**Issue by heartsforbuddha** [mealie-recipes/mealie#4628]
### First Check

- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have verified that this issue _is not_ related to the underlying library
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers) by **1)** checking
the [debugger](https://demo.mealie.io/g/home/r/create/debug) and data is returned, **2)**
verifying that there _are_ errors in the log related to application level code, or
**3)** verified that the site provides recipe data, or is otherwise supported by
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers)

- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### Please provide 1-5 example URLs that are having errors

Here is an example of one, but all of them do not work from this website. https://recipecenter.stopandshop.com/recipes/93823/baked-macaroni-chicken-and-spinach-casserole

Debugger "recipe_scrapers was unable to scrape this URL"

Recipe does work when import from HTML copy

### Please provide your logs for the Mealie container `docker logs <container-id> > mealie.logs`

No relevant logs. Truenas app

### Deployment

Other

**Comment by hay-kot** [comment]
Doesn't look like there's much we can do here. 

Command

```sh
curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" \
"https://recipecenter.stopandshop.com/recipes/93823/baked-macaroni-chicken-and-spinach-casserole"
```

Results in 

```html
<html>
   <head>
      <title>stopandshop.com</title>
      <script src="/cdn-cgi/apps/head/0bBd3eY_gVS3S8csjWXZ86cPyjA.js"></script>
      <style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style>
   </head>
   <body style="margin:0">
      <p id="cmsg">Please enable JS and disable any ad blocker</p>
      <script data-cfasync="false">var dd={'rt':'c','cid':'AHrlqAAAAAMAuzcQVz03xcUAawJUVA==','hsh':'6F06B864D19E80A2E0F4C48238C7FD','t':'bv','s':36030,'e':'116fd1120e32cdffd18aac3f22827d80bf9b07721f8802d58d041fedb17412de','host':'geo.captcha-delivery.com','cookie':'yPSNMdkJybpr_F~tr6HLtVOohFeWTA3KyP3PvUha0kTe87qCUE6maG74lXVDTAY05S1S_hhgObpcroeuQife2LBx7O1P5PwjAiO8kPd2_vuj7dhV737PFtGIPPcOVl_B'}</script><script data-cfasync="false" src="https://ct.captcha-delivery.com/c.js"></script><script>(function(){function c(){var b=a.contentDocument||a.contentWindow.document;if(b){var d=b.createElement('script');d.innerHTML="window.__CF$cv$params={r:'8ecd5db5ee1ca22d',t:'MTczMzMzMTc2Ni4wMDAwMDA='};var a=document.createElement('script');a.nonce='';a.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js';document.getElementsByTagName('head')[0].appendChild(a);";b.getElementsByTagName('head')[0].appendChild(d)}}if(document.body){var a=document.createElement('iframe');a.height=1;a.width=1;a.style.position='absolute';a.style.top=0;a.style.left=0;a.style.border='none';a.style.visibility='hidden';document.body.appendChild(a);if('loading'!==document.readyState)c();else if(window.addEventListener)document.addEventListener('DOMContentLoaded',c);else{var e=document.onreadystatechange||function(){};document.onreadystatechange=function(b){e(b);'loading'!==document.readyState&&(document.onreadystatechange=e,c())}}}})();</script>
   </body>
</html>
```

The relevant part being 

> Please enable JS and disable any ad blocker

which means their using client side rendering and not something we're able to work around at the moment.
