### ISSUE TITLE
[BUG] - Unable to create users / household

### ISSUE THREAD

**Issue by turbofx** [mealie-recipes/mealie#4632]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I've used both the docker-compose's for SQLLITE and Postgresql and I run into the same problem.
I'm able to login as the Changeme user and create myself as an admin user, I'm unable to add any more users.

### Steps to Reproduce

1) Create a basic docker compose file using the instructions on the web. Start with "up" so you can watch the logs.
2) Go into the web app, go to the "households" and try to create a new household, get nowhere, but there is a default.
3) Go to create user and you try to pick group "Family" but the household says "No data found" and goes red.

### Please provide relevant logs

When trying to create a household I see this log emitted from the container:
mealie    | INFO     2024-11-30T09:37:17 - [172.20.0.1:59302] 422 Unprocessable Entity "POST /api/admin/households HTTP/1.1"

### Mealie Version

Version: 2.3.0
Build ID: d6de0d0b3d3ffd63a72ac75eec43c4802c3dcc31

### Deployment

Docker (Linux)

### Additional Deployment Details

I'm using the provided docker-compose yaml for a SQLLITE version.

**Comment by ryancbutler** [comment]
Seems like the GUID isn't being created when checking with browser tools.

## Request
```json
{"groupId":"","name":"test"}
```

## Response
```json
{
    "detail": [
        {
            "type": "uuid_parsing",
            "loc": [
                "body",
                "groupId"
            ],
            "msg": "Input should be a valid UUID, invalid length: expected length 32 for simple format, found 0",
            "input": "",
            "ctx": {
                "error": "invalid length: expected length 32 for simple format, found 0"
            }
        }
    ]
}
```

**Comment by michael-genson** [comment]
Huh, no idea what happened there. I can reproduce this on my instance and on the demo

**Comment by michael-genson** [comment]
Oh I see what it is; the UI wants you to choose a group, but it will let you leave it null, thus it fails when it hits the API. Make sure you select the group before trying to create the user/household.

The UI should prevent you from making this mistake, though

**Comment by wieli99** [comment]
Bug still persists, no User Household can be selected in user creation
`Failed to load resource: the server responded with a status of 422`
Reproducible on demo site

**Comment by Kuchenpirat** [comment]
@wieli99 i dont think this is the same issue, please open a new one. 

I could somewhat reproduce it, but a refresh solved it (temporarily)
I am not sure if this is a cache issue or if there is something weird going on with the auto form. Will investigate more on the new issue.

**Comment by wieli99** [comment]
> @wieli99 i dont think this is the same issue, please open a new one. 
> 
> I could somewhat reproduce it, but a refresh solved it (temporarily)
> I am not sure if this is a cache issue or if there is something weird going on with the auto form. Will investigate more on the new issue. 

Sure, I created #5681 :)
