### ISSUE TITLE
[BUG] - default user/pass credentials not accepted

### ISSUE THREAD

**Issue by ballinger** [mealie-recipes/mealie#4663]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

the initial login screen, where one is supposed to enter  changeme@example.com, MyPassword is not accepted.
debian bookworm, yunohost installation on a vps. docker, mealie installed without errors. i am using yunohosts reverse proxy for the domain stuff. it redirects me to the login screen and prints
`401 Unauthorized "GET /api/users/self HTTP/1.1"`

### Steps to Reproduce

standard mealie install

### Please provide relevant logs

sudo docker compose down
[+] Running 2/2
 ✔ Container mealie        Removed                                                                                                                                                 1.8s 
 ✔ Network mealie_default  Removed                                                                                                                                                 0.3s 
 

sudo docker compose up -d && sudo docker compose logs -f
[+] Running 2/2
 ✔ Network mealie_default  Created                                                                                                                                                 0.2s 
 ✔ Container mealie        Started                                                                                                                                                 0.3s 
mealie  | Switching to dedicated user
mealie  | 
mealie  |         User uid:    1000
mealie  |         User gid:    1000
mealie  |         
mealie  | INFO     2024-12-02T20:05:07 - Started server process [1]
mealie  | INFO     2024-12-02T20:05:07 - Waiting for application startup.
mealie  | INFO     2024-12-02T20:05:07 - start: database initialization
mealie  | INFO     2024-12-02T20:05:07 - Database connection established.
mealie  | INFO     2024-12-02T20:05:07 - Context impl SQLiteImpl.
mealie  | INFO     2024-12-02T20:05:07 - Will assume non-transactional DDL.
mealie  | INFO     2024-12-02T20:05:07 - Checking for migration data fixes
mealie  | INFO     2024-12-02T20:05:07 - end: database initialization
mealie  | INFO     2024-12-02T20:05:07 - -----SYSTEM STARTUP-----
mealie  | INFO     2024-12-02T20:05:07 - ------APP SETTINGS------
mealie  | INFO     2024-12-02T20:05:07 - {
mealie  |     "TESTING": false,
mealie  |     "PRODUCTION": true,
mealie  |     "LOG_CONFIG_OVERRIDE": null,
mealie  |     "LOG_LEVEL": "info",
mealie  |     "theme": {
mealie  |         "light_primary": "#E58325",
mealie  |         "light_accent": "#007A99",
mealie  |         "light_secondary": "#973542",
mealie  |         "light_success": "#43A047",
mealie  |         "light_info": "#1976D2",
mealie  |         "light_warning": "#FF6D00",
mealie  |         "light_error": "#EF5350",
mealie  |         "dark_primary": "#E58325",
mealie  |         "dark_accent": "#007A99",
mealie  |         "dark_secondary": "#973542",
mealie  |         "dark_success": "#43A047",
mealie  |         "dark_info": "#1976D2",
mealie  |         "dark_warning": "#FF6D00",
mealie  |         "dark_error": "#EF5350"
mealie  |     },
mealie  |     "BASE_URL": "https://food.domain.org",
mealie  |     "STATIC_FILES": "/spa/static",
mealie  |     "IS_DEMO": false,
mealie  |     "HOST_IP": "*",
mealie  |     "API_HOST": "0.0.0.0",
mealie  |     "API_PORT": 9000,
mealie  |     "API_DOCS": true,
mealie  |     "TOKEN_TIME": 48,
mealie  |     "GIT_COMMIT_HASH": "d6de0d0b3d3ffd63a72ac75eec43c4802c3dcc31",
mealie  |     "ALLOW_SIGNUP": true,
mealie  |     "DAILY_SCHEDULE_TIME": "23:45",
mealie  |     "SECURITY_MAX_LOGIN_ATTEMPTS": 5,
mealie  |     "SECURITY_USER_LOCKOUT_TIME": 24,
mealie  |     "DB_ENGINE": "sqlite",
mealie  |     "DEFAULT_GROUP": "Home",
mealie  |     "DEFAULT_HOUSEHOLD": "Family",
mealie  |     "SMTP_HOST": null,
mealie  |     "SMTP_PORT": "587",
mealie  |     "SMTP_FROM_NAME": "Mealie",
mealie  |     "SMTP_FROM_EMAIL": null,
mealie  |     "SMTP_USER": null,
mealie  |     "SMTP_PASSWORD": null,
mealie  |     "SMTP_AUTH_STRATEGY": "TLS",
mealie  |     "LDAP_AUTH_ENABLED": false,
mealie  |     "LDAP_SERVER_URL": null,
mealie  |     "LDAP_TLS_INSECURE": false,
mealie  |     "LDAP_TLS_CACERTFILE": null,
mealie  |     "LDAP_ENABLE_STARTTLS": false,
mealie  |     "LDAP_BASE_DN": null,
mealie  |     "LDAP_QUERY_BIND": null,
mealie  |     "LDAP_QUERY_PASSWORD": null,
mealie  |     "LDAP_USER_FILTER": null,
mealie  |     "LDAP_ADMIN_FILTER": null,
mealie  |     "LDAP_ID_ATTRIBUTE": "uid",
mealie  |     "LDAP_MAIL_ATTRIBUTE": "mail",
mealie  |     "LDAP_NAME_ATTRIBUTE": "name",
mealie  |     "OIDC_AUTH_ENABLED": false,
mealie  |     "OIDC_CLIENT_ID": null,
mealie  |     "OIDC_CLIENT_SECRET": null,
mealie  |     "OIDC_CONFIGURATION_URL": null,
mealie  |     "OIDC_SIGNUP_ENABLED": true,
mealie  |     "OIDC_USER_GROUP": null,
mealie  |     "OIDC_ADMIN_GROUP": null,
mealie  |     "OIDC_AUTO_REDIRECT": false,
mealie  |     "OIDC_PROVIDER_NAME": "OAuth",
mealie  |     "OIDC_REMEMBER_ME": false,
mealie  |     "OIDC_USER_CLAIM": "email",
mealie  |     "OIDC_NAME_CLAIM": "name",
mealie  |     "OIDC_GROUPS_CLAIM": "groups",
mealie  |     "OIDC_SCOPES_OVERRIDE": null,
mealie  |     "OIDC_TLS_CACERTFILE": null,
mealie  |     "OPENAI_BASE_URL": null,
mealie  |     "OPENAI_API_KEY": null,
mealie  |     "OPENAI_MODEL": "gpt-4o",
mealie  |     "OPENAI_CUSTOM_HEADERS": {},
mealie  |     "OPENAI_CUSTOM_PARAMS": {},
mealie  |     "OPENAI_ENABLE_IMAGE_SERVICES": true,
mealie  |     "OPENAI_WORKERS": 2,
mealie  |     "OPENAI_SEND_DATABASE_DATA": true,
mealie  |     "OPENAI_REQUEST_TIMEOUT": 60,
mealie  |     "WORKER_PER_CORE": 1,
mealie  |     "UVICORN_WORKERS": 1,
mealie  |     "TLS_CERTIFICATE_PATH": null,
mealie  |     "TLS_PRIVATE_KEY_PATH": null
mealie  | }
mealie  | INFO     2024-12-02T20:05:07 - ------APP FEATURES------
mealie  | INFO     2024-12-02T20:05:07 - --------==SMTP==--------
mealie  | INFO     2024-12-02T20:05:07 - Enabled: False
mealie  | Reason: Missing required values for ['SMTP_HOST', 'SMTP_FROM_EMAIL']
mealie  | INFO     2024-12-02T20:05:07 - --------==LDAP==--------
mealie  | INFO     2024-12-02T20:05:07 - Enabled: False
mealie  | Reason: LDAP_AUTH_ENABLED is false
mealie  | INFO     2024-12-02T20:05:07 - --------==OIDC==--------
mealie  | INFO     2024-12-02T20:05:07 - Enabled: False
mealie  | Reason: OIDC_AUTH_ENABLED is false
mealie  | INFO     2024-12-02T20:05:07 - -------==OPENAI==-------
mealie  | INFO     2024-12-02T20:05:07 - Enabled: False
mealie  | Reason: OPENAI_API_KEY is not set
mealie  | INFO     2024-12-02T20:05:07 - ------------------------
mealie  | INFO     2024-12-02T20:05:07 - Daily tasks scheduled for 2024-12-02 23:45:00+00:00
mealie  | INFO     2024-12-02T20:05:07 - Application startup complete.
mealie  | INFO     2024-12-02T20:05:07 - Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
mealie  | INFO     2024-12-02T20:05:27 - [127.0.0.1:50996] 200 OK "GET /api/app/about HTTP/1.1"
mealie  | INFO     2024-12-02T20:05:58 - [127.0.0.1:44832] 200 OK "GET /api/app/about HTTP/1.1"
mealie  | INFO     2024-12-02T20:06:09 - [`IP:0:0`] 304 Not Modified "GET /login/ HTTP/1.1"
mealie  | INFO     2024-12-02T20:06:09 - [IP:0:0] 401 Unauthorized "GET /api/users/self HTTP/1.1"
mealie  | INFO     2024-12-02T20:06:09 - [IP:0:0] 200 OK "GET /api/app/about/startup-info HTTP/1.1"
mealie  | INFO     2024-12-02T20:06:09 - [IP:0:0] 200 OK "GET /api/app/about HTTP/1.1"
mealie  | INFO     2024-12-02T20:06:09 - [IP:0:0] 200 OK "GET /api/app/about HTTP/1.1"
mealie  | INFO     2024-12-02T20:06:10 - [IP:0:0] 304 Not Modified "GET /sw.js HTTP/1.1"
mealie  | INFO     2024-12-02T20:06:20 - [IP:0:0] 200 OK "POST /api/auth/token HTTP/1.1"
mealie  | INFO     2024-12-02T20:06:20 - [IP:0:0] 401 Unauthorized "GET /api/users/self HTTP/1.1"
mealie  | INFO     2024-12-02T20:06:28 - [127.0.0.1:40510] 200 OK "GET /api/app/about HTTP/1.1"
mealie  | INFO     2024-12-02T20:06:59 - [127.0.0.1:56470] 200 OK "GET /api/app/about HTTP/1.1"

### Mealie Version

stable debian docker repo, latest stable mealie

### Deployment

Docker (Linux)

### Additional Deployment Details

https://github.com/YunoHost-Apps/reverseproxy_ynh

**Comment by ballinger** [comment]
resolved - yunohost app should be redirect not reverse proxy

**Comment by LiloBzH** [comment]
Hi !

i know it's closed but 1 question.

I have a WAF too (Bunkerweb) . It s not possible to use WAF ? 

Same error 401 on login
