### ISSUE TITLE
[BUG] - Writes "ONCES" instead of "CENTILITERS" in the recipes' ingredient list (french version)

### ISSUE THREAD

**Issue by pongomail** [mealie-recipes/mealie#4744]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I think there is a bug in the mapping of the ingredient quantities in the french version of Mealie (haven't tried other languages). 
The system displays "onces" instead of "centiliters" (changing the parameters to set precisely the ingredients quantity).  
I can't replicate the bug on the demo as no ingredient quantity "type" appears. 

### Steps to Reproduce

1. In a french version of Mealie
2. Creating a recipe
3. Changing the parameters to specify ingredient's quantity
4. Adding liquid ingredients (eg. 10 Centiliters of water)
5. When saving and viewing the recipe 10 ONCES of water will be displayed instead of 10 Centiliters

### Please provide relevant logs

No error logs

### Mealie Version

**Details**
Version: v2.3.0
Build: d6de0d0b3d3ffd63a72ac75eec43c4802c3dcc31
Mode de l’application: Réalisation
Mode démo: Non
Port de l’API: 9000
Documentation de l’API: Activé
Type de base de données: postgres
Foyer par défaut: Family
Version du Scraper de recette: 15.2.1

**Checks**
Site sécurisé: Non
URL de base côté serveur: Oui
Prêt pour LDAP: Non
Prêt pour OIDC: Non
Prêt pour OpenAI: Non
E-mail configuré: Non

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Translations are handled through Crowdin: https://crowdin.com/project/mealie
However units are not global, they are configurable in your own instance via the [data management page](https://docs.mealie.io/documentation/getting-started/features/#data-management)

**Comment by pongomail** [comment]
Thank you, within the data management page I've been able to correct several mistakes in the translation. 
Sorry for creating this incorrect bug 
Have a nice day !

**Comment by michael-genson** [comment]
All good! If you're willing/able, would love to have you fix the translations [on Crowdin](https://crowdin.com/project/mealie)!

**Comment by pongomail** [comment]
Did it, hope it helps

**Comment by michael-genson** [comment]
Thank you!!!
