### ISSUE TITLE
[BUG] - Error Starting Docker after PI Upgrade

### ISSUE THREAD

**Issue by NP00111** [mealie-recipes/mealie#4748]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I recently ran a upgrade on my pi and post reboot, I get the following error when trying to start the docker image.   It was running fine prior to upgrade. 

nishalp@raspberrypi:~/mealie $ docker compose up -d
WARN[0000] /home/nishalp/mealie/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 1/1
 ✔ Container postgres  Created                                             0.8s 
 ⠋ Container mealie    Creating                                            0.0s 
Error response from daemon: rename /var/lib/docker/overlay2/777f2523b5654227fe71d055120fee2da67836585c6e084b0ddcfeb7998395c7/.tmp-committed4070078241 /var/lib/docker/overlay2/777f2523b5654227fe71d055120fee2da67836585c6e084b0ddcfeb7998395c7/committed: bad message

### Steps to Reproduce

Running docker compose up -d gives the above error

### Please provide relevant logs

See above

### Mealie Version

image: ghcr.io/mealie-recipes/mealie:nightly

### Deployment

Other (please specify below)

### Additional Deployment Details

Docker Raspberry Pi

**Comment by NP00111** [comment]
I resolved it.  Was a docker upgrade issue.  Running docker system prune -a -f and then running docker compose up -d solved the issue.

**Comment by Kuchenpirat** [comment]
Thanks for reporting back. Will close this issue then.
