### ISSUE TITLE
[BUG] - Same ingredient different translation depending on page

### ISSUE THREAD

**Issue by GerardPolloRebozado** [mealie-recipes/mealie#4755]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

One of the ingredients in a recipe is an egg and when im in the recipe page says 3 servings of eggs, but if I go to edit the recipe it says 3 porciones de huevo. The thing is my instance is in spanish only the eggs are the ones that have this issue

### Steps to Reproduce

Add a recipe that has eggs
Have the language to spanish
Look at the recipe ingredients

### Please provide relevant logs

1.1"
INFO     2024-12-20T20:21:29 - [127.0.0.1:45268] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-12-20T20:22:00 - [127.0.0.1:56216] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-12-20T20:22:31 - [127.0.0.1:54250] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-12-20T20:23:01 - [127.0.0.1:57984] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-12-20T20:23:32 - [127.0.0.1:45364] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-12-20T20:24:03 - [127.0.0.1:50762] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-12-20T20:24:31 - locked users reset
INFO     2024-12-20T20:24:34 - [127.0.0.1:33396] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-12-20T20:25:05 - [127.0.0.1:50712] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-12-20T20:25:35 - [127.0.0.1:59964] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-12-20T20:25:56 - [79.116.49.152:0] 200 OK "GET /_nuxt/5087f04.js HTTP/1.1"
INFO     2024-12-20T20:25:57 - [79.116.49.152:0] 200 OK "GET /api/admin/about HTTP/1.1"
INFO     2024-12-20T20:25:57 - [79.116.49.152:0] 200 OK "GET /api/admin/about/check HTTP/1.1"
INFO     2024-12-20T20:26:06 - [127.0.0.1:48358] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-12-20T20:26:37 - [127.0.0.1:38588] 200 OK "GET /api/app/about HTTP/1.1"
INFO     2024-12-20T20:27:08 - [127.0.0.1:57572] 200 OK "GET /api/app/about HTTP/1.1"

### Mealie Version

**Details**
Versión: v2.4.1
Compilación: 2922782e5ea44e1c5d2690c9aea84134a044a7cc
Modo de Aplicación: Producción
Modo Demo: No Demo
Puerto API: 9000
Documentación API: Habilitado
Tipo de base de datos: postgres
Casa predeterminada: Family
Versión de Analizador de Recetas: 15.3.3

**Checks**
Sitio Seguro: Si
URL base del servidor: Si
LDAP Listo: No
OIDC Listo: No
OpenAI Listo: Si
Email configurado: No

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
This is probably related to singular vs plural foods. Foods are defined per-instance, they're not global to Mealie. How does it look in the data management page?

https://docs.mealie.io/documentation/getting-started/features/#data-management

**Comment by GerardPolloRebozado** [comment]
Yes you are right. For now I only added recipes with the importer using AI so I suppose this plurals are added by the ai?

**Comment by michael-genson** [comment]
It may be useful to read up on how Mealie handles ingredients: https://docs.mealie.io/documentation/getting-started/faq/#how-do-i-enable-smart-ingredient-handling
