### ISSUE TITLE
[BUG] - "Recipe Created by" Translation is off in Timeline Mealie

### ISSUE THREAD

**Issue by bennym85** [mealie-recipes/mealie#4756]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

German Translation issue when a recipe gets added. 
Instead of "<user> created recipe"  it says. recipe.recipe-created

Acoording to Discord channel this might affect other translations as well

### Steps to Reproduce

Click on Timeline - it shows "recipe.recipe-created"
<img width="1228" alt="Bildschirmfoto 2024-12-19 um 20 51 45" src="https://github.com/user-attachments/assets/c4224e48-ab5e-439d-bd29-0424b37f3e81" />

### Please provide relevant logs

n/a

### Mealie Version

latest nightly

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Hey there,

This should be fixed in the latest nightly/release. Can you try updating and see if it works for you? It won't retroactively fix timeline events, but it should be fixed for new ones.

**Comment by bennym85** [comment]
Confirmed, fixed. Thanks 👍

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Michael Genson ***@***.***>
Gesendet: Saturday, December 21, 2024 6:53:45 PM
An: mealie-recipes/mealie ***@***.***>
Cc: bennym85 ***@***.***>; Author ***@***.***>
Betreff: Re: [mealie-recipes/mealie] [BUG] - "Recipe Created by" Translation is off in Timeline Mealie (Issue #4756)


Hey there,

This should be fixed in the latest nightly/release. Can you try updating and see if it works for you? It won't retroactively fix timeline events, but it should be fixed for new ones.
