### ISSUE TITLE
[BUG] - Missing Translation for Recipe Finder

### ISSUE THREAD

**Issue by bennym85** [mealie-recipes/mealie#4758]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

"Recipe Finder" menu item and corresponding section is not being translated however some button labels are.

### Steps to Reproduce

Log into Mealie with a different language then English (in my case German), see Recipe Finder appears in English language. 
Select Recipe finder and find the text is all in English and does not have an equivalent translation.
<img width="1445" alt="Bildschirmfoto 2024-12-21 um 12 53 31" src="https://github.com/user-attachments/assets/02035493-3dff-4b58-ab88-7441ad0cfa31" />

### Please provide relevant logs

n/a

### Mealie Version

latest nightly

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Translations are [done through Crowdin](https://docs.mealie.io/contributors/translating/). Since the recipe finder is so new, community members haven't had much time to contribute translations. If you're interested in contributing, [you can do so here](https://crowdin.com/project/mealie)!

**Comment by bennym85** [comment]
Confirmed, fixed 😃👍

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Michael Genson ***@***.***>
Gesendet: Saturday, December 21, 2024 6:29:12 PM
An: mealie-recipes/mealie ***@***.***>
Cc: bennym85 ***@***.***>; Author ***@***.***>
Betreff: Re: [mealie-recipes/mealie] [BUG] - Missing Translation for Recipe Finder (Issue #4758)


Closed #4758<https://github.com/mealie-recipes/mealie/issues/4758> as completed.
