### ISSUE TITLE
[BUG] - Households permissions ignored 

### ISSUE THREAD

**Issue by MatthieuBalmont** [mealie-recipes/mealie#4763]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I created two households within the same group: one private and one public. However, when I connect as a user in the public household, I can still see recipes from the private household.

According to your 'Permissions and Public Access' documentation, this should normally be impossible.
![Screenshot 2024-12-22 at 14 01 08](https://github.com/user-attachments/assets/62c8b537-318a-4b67-b5b8-a5ae4434a6af)

### Steps to Reproduce

1) Create two households: one private and one public.
2) Create two users, assigning one to each household.
3) Log in as the user in the private household and create a recipe.
4) Log in as the other user and observe that the recipe from the private household is visible.

### Please provide relevant logs

Not relevant 

### Mealie Version

Version
v2.4.1

Build
[2922782e5ea44e1c5d2690c9aea84134a044a7cc](https://github.com/mealie-recipes/mealie/commit/2922782e5ea44e1c5d2690c9aea84134a044a7cc)

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
The guide you're referring to is for public access, not for authenticated users. All users within a group can see all recipes within that group, regardless of settings.

If you want to hide recipes from users, you need to create a separate group.

**Comment by MatthieuBalmont** [comment]
Thank you for your response.

If it’s not possible to manage permissions between households beyond editing, I believe the households abstraction adds no real value; in fact, a household equals a user. However, it might be useful to allow a user to belong to multiple households.

Thank you for your time.
You can close the issue. 👍

**Comment by michael-genson** [comment]
> a household equals a user

It may be helpful to check out the docs on how groups and households work: https://docs.mealie.io/documentation/getting-started/features/#groups-and-households. Households function completely differently than users, since you can share meal plans, shopping lists, etc.
