### ISSUE TITLE
[BUG] - SyntaxWarning in repository_cookbooks.py and query_search.py for mealie >= v2.4.0

### ISSUE THREAD

**Issue by Weizenritter** [mealie-recipes/mealie#4775]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When starting `mealie` in version v2.4.0 or higher two `SyntaxWarning` are being logged.

### Steps to Reproduce

1) Start the application in version >=`v2.4.0`.
2) See the Warnings in the Logs right away.

### Please provide relevant logs

```bash
$ docker run ghcr.io/mealie-recipes/mealie:v2.4.0
usermod: no changes
Switching to dedicated user

        User uid:    911
        User gid:    911

/app/mealie/repos/repository_cookbooks.py:39: SyntaxWarning: invalid escape sequence '\d'
  if not (data.slug and re.match(f"^({new_slug})(-\d+)?$", data.slug)):
/app/mealie/schema/response/query_search.py:19: SyntaxWarning: invalid escape sequence '\#'
  punctuation = "!\#$%&()*+,-./:;<=>?@[\\]^_`{|}~"  # string.punctuation with ' & " removed
…
```

### Mealie Version

Image Tag: ghcr.io/mealie-recipes/mealie:v2.4.0
Build: b3c0661f52c8e843f00a311bf2e335e3f9598fa3 

### Deployment

Docker (Linux)

**Comment by Vertux** [comment]
I can confirm this issue. 

### Mealie Version

Version v2.4.1
Build 2922782e5ea44e1c5d2690c9aea84134a044a7cc

### Deployment

Podman, Version 5.3.1 (Fedora Server,Linux), rootless

```
Dez 29 19:13:39 pool podman[53378]: 31b7a7f75d02ea3ef75b94ffc1dfb13b939c6962001fc147288978b3e3be42db
Dez 29 19:13:39 pool mealie[53414]: Switching to dedicated user
Dez 29 19:13:39 pool mealie[53414]:
Dez 29 19:13:39 pool mealie[53414]:         User uid:    1000
Dez 29 19:13:39 pool mealie[53414]:         User gid:    1000
Dez 29 19:13:39 pool mealie[53414]:
Dez 29 19:13:42 pool mealie[53414]: /app/mealie/repos/repository_cookbooks.py:39: SyntaxWarning: invalid escape sequence '\d'
Dez 29 19:13:42 pool mealie[53414]:   if not (data.slug and re.match(f"^({new_slug})(-\d+)?$", data.slug)):
Dez 29 19:13:42 pool mealie[53414]: /app/mealie/schema/response/query_search.py:19: SyntaxWarning: invalid escape sequence '\#'
Dez 29 19:13:42 pool mealie[53414]:   punctuation = "!\#$%&()*+,-./:;<=>?@[\\]^_`{|}~"  # string.punctuation with ' & " removed

```

**Comment by michael-genson** [comment]
This is just a warning, so other than being annoying it's not harming anything. Agreed that it should be fixed, though
