### ISSUE TITLE
Grouping of duplicate ingredients 

### ISSUE THREAD

**Issue by jkaberg** [mealie-recipes/mealie#691]
**Describe the bug**
Creating an meal plan of lets say spaghetti and meatballs all days for a week, when generating the shopping list for this week plan you end up with lots of duplicates

**Steps To Reproduce**
Please be specific!
1. Add/import the recipe https://www.ica.se/recept/kottbullar-i-tomatsas-med-spaghetti-723256/
2. Create an meal plan for an entire week (monday->sunday) with everyday this recipe
3. Generate an shopping list
4. The shopping list is full of 1 x ingredient x day (so 7 of the same for all ingredients)

**Expected behavior**
Mealie should group the same ingredient (and add up)

**Actual Behavior**
Maelie doesn't group, but creates duplicates

**Screenshots**
![image](https://user-images.githubusercontent.com/613363/134465749-2bca91b6-7dc4-4008-b2ba-c6139a200562.png)

**Device Information (please complete the following information):**
 - Mealie 0.5.2

**Additional behavior**

The generated shopping list (notice all the duplicates)
```
MealPlan Shopping List
1

1 gul lök

1

1 vitlöksklyfta

1

100 g färsk salsiccia

1

2 msk olivolja

1

390 g pastasås tomat & vitlök

1

390 g krossade tomater

1

1 dl vatten

1

1 tsk timjan

1

1 tsk oregano

1

1 grönsaksbuljongtärning

1

1 tsk vitvinsvinäger

1

salt

1

svartpeppar

1

350 g stekta köttbullar

1

4 port spaghetti

1

1/2 kruka persilja

1

riven hårdost (t ex parmesan)

1

1 gul lök

1

1 vitlöksklyfta

1

100 g färsk salsiccia

1

2 msk olivolja

1

390 g pastasås tomat & vitlök

1

390 g krossade tomater

1

1 dl vatten

1

1 tsk timjan

1

1 tsk oregano

1

1 grönsaksbuljongtärning

1

1 tsk vitvinsvinäger

1

salt

1

svartpeppar

1

350 g stekta köttbullar

1

4 port spaghetti

1

1/2 kruka persilja

1

riven hårdost (t ex parmesan)

1

1 gul lök

1

1 vitlöksklyfta

1

100 g färsk salsiccia

1

2 msk olivolja

1

390 g pastasås tomat & vitlök

1

390 g krossade tomater

1

1 dl vatten

1

1 tsk timjan

1

1 tsk oregano

1

1 grönsaksbuljongtärning

1

1 tsk vitvinsvinäger

1

salt

1

svartpeppar

1

350 g stekta köttbullar

1

4 port spaghetti

1

1/2 kruka persilja

1

riven hårdost (t ex parmesan)

1

1 gul lök

1

1 vitlöksklyfta

1

100 g färsk salsiccia

1

2 msk olivolja

1

390 g pastasås tomat & vitlök

1

390 g krossade tomater

1

1 dl vatten

1

1 tsk timjan

1

1 tsk oregano

1

1 grönsaksbuljongtärning

1

1 tsk vitvinsvinäger

1

salt

1

svartpeppar

1

350 g stekta köttbullar

1

4 port spaghetti

1

1/2 kruka persilja

1

riven hårdost (t ex parmesan)

1

1 gul lök

1

1 vitlöksklyfta

1

100 g färsk salsiccia

1

2 msk olivolja

1

390 g pastasås tomat & vitlök

1

390 g krossade tomater

1

1 dl vatten

1

1 tsk timjan

1

1 tsk oregano

1

1 grönsaksbuljongtärning

1

1 tsk vitvinsvinäger

1

salt

1

svartpeppar

1

350 g stekta köttbullar

1

4 port spaghetti

1

1/2 kruka persilja

1

riven hårdost (t ex parmesan)


```

**Comment by jkaberg** [comment]
One would also expect that if you have a bunch of different recipes which shares some (but not all) ingredients, then Mealie should group the shared ingredients aswell when generating a shopping list.

**Comment by hay-kot** [comment]
Edit and save your list and it will consolidate your matching items.

**Comment by jkaberg** [comment]
@hay-kot Nice, that works! I'll leave it up to you if you want to close this.

**Comment by hay-kot** [comment]
> @hay-kot Nice, that works! I'll leave it up to you if you want to close this.

I'm going to close for now. As part of the rewrite, Shopping Lists will operate completely differently and this functionality will be available out of the box so no need to track the issue. Thanks!
