### ISSUE TITLE
Errors importing from Chowdown

### ISSUE THREAD

**Issue by anoncl** [mealie-recipes/mealie#698]
### Description
I have been trying to write a script to convert documents files into chowdown format. Its going well but I am getting lots of errors trying to import. This includes importing data from the chowdown website itself, not just my data. 

### Expected Behavior
Successful import without errors.

### Actual Behavior 
A large number of the recipes (roughly half) say they failed with these errors:
(sqlite3.IntegrityError) UNIQUE constraint failed: recipes.slug [SQL: INSERT INTO recipes (name, description, image, total_time, prep_time, perform_time, cook_time, recipe_yield, "recipeCuisine", slug, rating, org_url, date_added, date_updated, favorited_by_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)] [parameters: ('Crispy Carrots', "This is another recipe we saw on Jamie Oliver's TV show, and we can't stop making it. It's perfect for parties, and pairs well with any rich dip (we' ... (3 characters truncated) ... been doing greek yogurt topped with hot sauce and tahini). We've also rolled things other than carrots, changed the flavors, made news dips— go wild!", 'crispy-carrots.jpg', None, None, None, None, None, None, 'crispy-carrots', None, None, '2021-09-27', '2021-09-27 23:25:47.014256', None)] (Background on this error at: https://sqlalche.me/e/14/gkpj) 

### Troubleshooting Steps
I went and downloaded the chowdown source and uploaded that to see if that would work and I get the same errors. The error above is actually from trying the chowdown data, not my data.

I have also tried  #wiping out the entire Mealie folder and starting the import from a blank install and get the same issues. 

I also tried it on the demo site with the same results.

It looks like its similar to  #653 

Also, it DOES actually import the recipes, but it is filled with errors in the process.

**Comment by hay-kot** [comment]
I wasn't able to replicate your issue. I was able to import all of the recipes in the [chowdown repository](https://github.com/clarklab/chowdown) using the demo site. 

<img width="1675" alt="Screen Shot 2021-10-02 at 5 29 08 PM" src="https://user-images.githubusercontent.com/64056131/135736338-163d5d5b-c425-4e3c-83ba-b2f2111ae4fb.png">

**Comment by anoncl** [comment]
So strange.

I just deleted all the recipes from the demo, uploaded the full zip, and imported.

![01-before](https://user-images.githubusercontent.com/91525238/135739235-a4166aba-2572-4638-a7d0-20203c796edb.png)
 ![02-import](https://user-images.githubusercontent.com/91525238/135739240-2c0a07a7-1258-48ad-9079-1063b67463f3.png)
![03-after](https://user-images.githubusercontent.com/91525238/135739244-199332c2-f434-462b-a4d4-18b3bd033f60.png)

Ive tried Chormium and Firefox. Any thoughts on why I would get this and you would not?

Anything I can do to test?

**Comment by hay-kot** [comment]
I have no idea why this would be different. We appear to be doing the same thing.
