### ISSUE TITLE
Category and Tag dropdowns in Recipe Editor show no entries

### ISSUE THREAD

**Issue by Jonnobrow** [mealie-recipes/mealie#702]
**Describe the bug**
When editing a recipe I see no tags or categories in the dropdown menus. 

**Steps To Reproduce**
1. Log in and edit a recipe
2. Click on the dropdown menu for categories or tags
3. See that no entries are present and the drop down toggle is changing

**Expected behavior**
I would expect the list of tags and categories to be displayed. I can access these through the tags and categories pages and through the API.

**Actual Behavior**
The dropdown lists are empty.

**Screenshots**
![ezgif-4-b1103a4af740](https://user-images.githubusercontent.com/34320158/135298072-4713aff3-4bfb-49b0-bc13-d05669726fdf.gif)

**Device Information (please complete the following information):**
 - OS: Arch Linux  (Kernel 5.10.67-1-lts)
 - Deployment: [k8s-at-home helm chart](https://github.com/k8s-at-home/charts/tree/master/charts/stable/mealie), using docker image tag v0.5.2 (v0.5.1 yields same results)
 - Browser: Firefox 92.0
 - Version: v0.5.2

**Additional context**
This behaviour only happens on desktop for me, on my phone everything works correctly.

**Comment by hay-kot** [comment]
Can you do a hard refresh in the browser and verify that you have the same issue described in #605?

**Comment by Jonnobrow** [comment]
> Can you do a hard refresh in the browser and verify that you have the same issue described in #605?

I tried running a hard refresh (Ctrl + F5 in Firefox) and the issue still appears. I also went into developer settings and cleared the cached data added by the service worker and this also did not resolve this issue either and therefore I am happy to accept my issue is the same as in #605 so I will close this issue. Thanks.
