### ISSUE TITLE
Image upload failed when creating recipe manually

### ISSUE THREAD

**Issue by cwpearson** [mealie-recipes/mealie#704]
This is an awesome project, it was easy to get up and running!

**Describe the bug**
When creating a new recipe, I get the message "image upload failed" when uploading an image.

**Steps To Reproduce**
1. New Recipe
2. Click "Image"
3. Click "Upload"
4. Select an image from your computer (1.5MB jpeg)
5. Receive error message "image upload failed"

**Sample Code**

**Expected behavior**
The image should be added to the recipe.

**Actual Behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - OS: macOS 11.6, iOS 15.0
 - Deployment: docker-compose
 - Browser: Firefox 92.0.1
 - Version: 0.5.2

**Additional context**
```
$ docker logs -f mealie
...
172.21.0.1:0 - "GET /api/debug/statistics HTTP/1.1" 200
172.21.0.1:0 - "GET /api/backups/available HTTP/1.1" 200
172.21.0.1:0 - "GET /api/backups/available HTTP/1.1" 200
172.21.0.1:0 - "GET /api/site-settings/custom-pages HTTP/1.1" 200
172.21.0.1:0 - "GET /api/recipes/summary HTTP/1.1" 200
172.21.0.1:0 - "GET /api/site-settings HTTP/1.1" 200
True True
True True
172.21.0.1:0 - "GET /api/recipes/southwest-stuffed-zucchini-boats HTTP/1.1" 200
172.21.0.1:0 - "GET /api/recipes/southwest-stuffed-zucchini-boats HTTP/1.1" 200
172.21.0.1:0 - "GET /api/categories HTTP/1.1" 200
172.21.0.1:0 - "GET /api/tags HTTP/1.1" 200
```

Dashboard most recent event is:

```
Recipe Created (URL)
'Southwest Stuffed Zucchini Boats' by <me> http://localhost:8080/recipe/southwest-stuffed-zucchini-boats
Thursday, September 30, 2021, 4:20 AM 
```

I'm running this behind an nginx reverse proxy with SSL.

**Comment by cwpearson** [comment]
This is after selecting the image from the file-picker dialogue the computer gives me

<img width="771" alt="Screen Shot 2021-09-30 at 6 40 46 AM" src="https://user-images.githubusercontent.com/6765756/135456917-eca8cab2-9551-46b5-a83e-983672fdc7df.png">

**Comment by hay-kot** [comment]
Can you confirm that this only occurs before the initial save and once the recipe is saved you can edit the images? If that is the case, I've already fixed this in v1. There's a new creation flow to make things a little "safer" and easier to do.

**Comment by cwpearson** [comment]
It happens both at the initial creation and when editing. If you've made substantial changes for v1 it sounds like I should wait and try again then :D. Feel free to close this. Thanks for you work on this.

**Comment by hay-kot** [comment]
> It happens both at the initial creation and when editing. If you've made substantial changes for v1 it sounds like I should wait and try again then :D. Feel free to close this. Thanks for you work on this.

v1 is still a ways away unfortunately, this should work though? Here's what I did on the demo site.

1. Create new Recipe with only name "Test Recipe 123"
2. Saved Recipe
3. Edit Recipe and Upload Image
4. Saved Recipe
5. Image is shown as expected.

https://demo.mealie.io/recipe/test-recipe-123

**Comment by cwpearson** [comment]
It also worked for me on the demo site! It's possible I've messed up my configuration somehow, I'm running 0.5.2 instead of 0.5.0, and I'm using sqlite. Maybe I can try 0.5.0 on my own machine and see what happens.

**Comment by cwpearson** [comment]
Aha I'm a bit out of my depth in webdev but I checked the web developer tools console when I try to upload and I get this:

```
HTTP/1.1 413 Request Entity Too Large
Server: nginx/1.18.0
Date: Fri, 01 Oct 2021 18:18:48 GMT
Content-Type: text/html
Content-Length: 183
Connection: close
```

I fixed it by setting
```
client_max_body_size 2M;
```

In my nginx config that I use for mealie
