### ISSUE TITLE
No matching manifest for linux/arm/v7 in the manifest list entries

### ISSUE THREAD

**Issue by ptizzl** [mealie-recipes/mealie#706]
**Describe the bug**
no matching manifest for linux/arm/v7 in the manifest list entries after running docker-compose

**Steps To Reproduce**
Please be specific!
1. Use the docker-compose file 
2. Run docker-compose up -d
3. Get error

**Sample Code**
Contents of my docker-compose.yml file

version: "3.1"
services:
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    restart: always
    ports:
      - 9925:80
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Anchorage

      # Default Recipe Settings
      RECIPE_PUBLIC: 'true'
      RECIPE_SHOW_NUTRITION: 'true'
      RECIPE_SHOW_ASSETS: 'true'
      RECIPE_LANDSCAPE_VIEW: 'true'
      RECIPE_DISABLE_COMMENTS: 'false'
      RECIPE_DISABLE_AMOUNT: 'false'

      # Gunicorn
      WEB_CONCURRENCY: 2
      # WORKERS_PER_CORE: 0.5
      # MAX_WORKERS: 8

    volumes:
      - /srv/dev-disk-by-label-media/data/appdata/mealie:/app/data            

**Expected behavior**
Install

**Actual Behavior**
Error stating: No matching manifest for linux/arm/v7 in the manifest list entries

**Screenshots**

**Device Information (please complete the following information):**
 - OS: Raspbian Lite
 - Deployment: Docker

**Additional context**

**Comment by hay-kot** [comment]
See [breaking change 'Arm/v7 Support' in v0.5.0 release notes](https://hay-kot.github.io/mealie/changelog/v0.5.0/)

**Comment by ptizzl** [comment]
ah ok bummer. All of that is greek to me, I have no idea how to compile that myself.

**Comment by hay-kot** [comment]
> ah ok bummer. All of that is greek to me, I have no idea how to compile that myself.

It sort of a crap-shoot if it will compile anyways. You're better off finding a 64bit machine to run it on or If you're using modern Pi, there is likely a 64 bit OS available.

**Comment by ptizzl** [comment]
Good to know. This is on a Raspberry Pi 4, I must have installed the wrong OS back when I set this up initially.

**Comment by hay-kot** [comment]
Yeah, I believe the default installer for Pi's is still 32bit so It's a common issue.
