### ISSUE TITLE
[v1.0.0b] - Hamburger menu not working as supposed, needs double tick to close

### ISSUE THREAD

**Issue by zierbeek** [mealie-recipes/mealie#722]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

when logging in, the sidebar is exposed. If I want to close it, I need to tick twice on the hamburger menu. It should be working from the fist tick. I think this has to do with a state which is set wrongly or a toggle not in place.

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
Should be fixed, feel free to reopen
