### ISSUE TITLE
Just updated Docke to latest and wont start

### ISSUE THREAD

**Issue by Code-Slave** [mealie-recipes/mealie#723]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Been great wanted to get latest. When I run the docker

/app/mealie/run.sh: line 30: poetry: command not found
Production
usermod: no changes
    User uid:    911
    User gid:    911

Thats a pull from latest. deleted containers and pulled again same issue

### Deployment

Docker (Linux)

### Mealie Version

latest

**Comment by Code-Slave** [comment]
reverted to v.5.0 and works fine. Cant figure out what changed that broke latest for me

**Comment by hay-kot** [comment]
The only thing I can think of is that there a layer that is still cached in docker that is keeping the image from starting properly. Poetry is a key dependency during build and runtime, so it not being there doesn't make any sense. 

You could try pulling the `dev` tag and see if you can run that. It's pretty much ready for the 0.5.3 but I haven't tested the upgrade process, so be sure to backup your data before testing it out.

**Comment by MadWalnut** [comment]
I am experiencing the same issue after updating to 0.5.2 using the `latest` tag. `dev` (and therefore 0.5.3) works. At first glance also no issues with the upgrade process.

For me this occurs on Synology DSM. Resetting the container does not help, so I don't think its a cache issue.

**Comment by hay-kot** [comment]
This should be resolved in v0.5.3. Please reopen if you're still experiencing the issue after upgrading.

**Comment by petergerdes** [comment]
Just pulled v0.5.3 and issue still persists:
`/app/mealie/run.sh: line 30: poetry: command not found`

**Comment by MadWalnut** [comment]
Same for me. `dev` v0.5.3 works, but pulling via `latest` doesn't.

**Comment by hay-kot** [comment]
> Same for me. `dev` v0.5.3 works, but pulling via `latest` doesn't.

They're identical images, so I'm fairly sure that it's a caching issue with your docker host.

**Comment by MadWalnut** [comment]
I had already tried repulling but that didn't work. However Docker DSM had shown be some weird EVs on the `latest` container, that were not present on the `dev` one. For example `POETRY_VERSION=1.1.6`. After completely re-creating the config for `latest`, those EVs are now gone and now the container starts.

**Comment by stevennic22** [comment]
As a follow-up on this, I believe that there was an old version of the PATH ENV that was causing this problem for me. Once I cleared that and re-deployed, a new PATH ENV was set that included the /opt/poetry/bin that was not there before.
