### ISSUE TITLE
categories - Internal Server Error 

### ISSUE THREAD

**Issue by ghost** [mealie-recipes/mealie#748]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When I go to the categories, none are displayed. When I click on a category in a recipe, I get an Internal Server Error. It does not redirect me to the category but to mealie/undefined
![image](https://user-images.githubusercontent.com/44962130/137935713-a8080f4c-7438-4298-b03f-098fcc2852d7.png)

### Deployment

Unraid

### Mealie Version

V0.5.2

**Comment by fabykr** [comment]
Same Version, same problem. I migrated via zip-file-upload from nextcloud cookbook. You too? While importing, i got this error message:

> (sqlite3.IntegrityError) UNIQUE constraint failed: recipes.slug [SQL: INSERT INTO recipes (name, description, image, total_time, prep_time, perform_time, cook_time, recipe_yield, "recipeCuisine", slug, rating, org_url, date_added, date_updated, favorited_by_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)] [parameters: ('Vegane Baked Feta Pasta', 'Eine Ladung obercremige Pasta mit aromatischen, gerösteten Kirschtomaten, gutem Olivenöl, Knobi und veganem Feta – das ganze noch aus dem Ofen und in unter 30 Minuten fertig? Voilà, hier kommt unsere Version vom viral gegangenen TikTok-Rezept „Baked Feta Pasta“ in vegan.', 'https://www.eat-this.org/wp-content/uploads/2021/02/eat_this_vegane_baked_feta_pasta-005.jpg', '30 Minutes', '5 Minutes', None, None, '2', None, 'vegane-baked-feta-pasta', None, 'https://www.eat-this.org/vegane-baked-feta-pasta/', '2021-10-20', '2021-10-20 11:11:15.122093', None)] (Background on this error at: https://sqlalche.me/e/14/gkpj) 

But everything except categories is working. 

If you change or add a category, next time the link .../recipes/category shows the categories. you reload, you lose them. 

Otherwise one of the most beautiful and functional open source projects! :-D

**Comment by ghost** [comment]
> 
> 
> Same Version, same problem. I migrated via zip-file-upload from nextcloud cookbook. You too? While importing, i got this error message:
> 
> > (sqlite3.IntegrityError) UNIQUE constraint failed: recipes.slug [SQL: INSERT INTO recipes (name, description, image, total_time, prep_time, perform_time, cook_time, recipe_yield, "recipeCuisine", slug, rating, org_url, date_added, date_updated, favorited_by_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)] [parameters: ('Vegane Baked Feta Pasta', 'Eine Ladung obercremige Pasta mit aromatischen, gerösteten Kirschtomaten, gutem Olivenöl, Knobi und veganem Feta – das ganze noch aus dem Ofen und in unter 30 Minuten fertig? Voilà, hier kommt unsere Version vom viral gegangenen TikTok-Rezept „Baked Feta Pasta“ in vegan.', 'https://www.eat-this.org/wp-content/uploads/2021/02/eat_this_vegane_baked_feta_pasta-005.jpg', '30 Minutes', '5 Minutes', None, None, '2', None, 'vegane-baked-feta-pasta', None, 'https://www.eat-this.org/vegane-baked-feta-pasta/', '2021-10-20', '2021-10-20 11:11:15.122093', None)] (Background on this error at: https://sqlalche.me/e/14/gkpj)
> 
> But everything except categories is working.
> 
> If you change or add a category, next time the link .../recipes/category shows the categories. you reload, you lose them.
> 
> Otherwise one of the most beautiful and functional open source projects! :-D

I didn't get an error after importing but I import my nextcloud cookbook as well!

**Comment by hay-kot** [comment]
It has to do with the aggressive caching I was doing on the frontend, it should be resolved in the `dev` tag. When I get time this week, I'll do some thorough testing and push a new release (Hopefully).

**Comment by hay-kot** [comment]
Should be fixed in the new release (v0.5.3), please open a new issue if you're still experiencing it after upgrading.
