### ISSUE TITLE
[v1.0.0b] - Natural Language parser misinterpreting units

### ISSUE THREAD

**Issue by EKCJ** [mealie-recipes/mealie#751]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When using natural language to parse an ingredient which uses a long form of a unit, such as "15 grams sesame seeds", the parser creates an incorrect result:
**amount**: 15 **unit**: g **food**: rams sesame seeds

![image](https://user-images.githubusercontent.com/67192679/138326794-96ba9875-7fcc-41fc-8cfd-3e813d92b5c7.png)

### Deployment

Unraid

**Comment by hay-kot** [comment]
Fixed!

<img width="1288" alt="Screen Shot 2021-10-28 at 8 38 39 PM" src="https://user-images.githubusercontent.com/64056131/139376605-8296cab6-0c5d-48d0-aed6-3ad3104829b1.png">
