### ISSUE TITLE
Cannot import from a 1:1 copy of a website which works just fine with import

### ISSUE THREAD

**Issue by dzek69** [mealie-recipes/mealie#752]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

This website: https://aniagotuje.pl/przepis/domowa-cwikla-z-chrzanem imports fine. Not perfect, but fine.
I tested it with scrape_me and it works with wild mode only.

Now, I've made a copy of that website, just copied html and pasted into a file and saved and uploaded. It's accessible here: http://tools.dev.nitra.pl/test.html (now removed)
I tested this with scrape_me and on wild mode it works the same.

However on Mealie the original recipe works and my copy does not.

I tried on several urls (including https support), but nothing worked. I don't know what is the difference between original and a copy that makes the difference.

### Deployment

Docker (Linux)

### Mealie Version

0.5.2

**Comment by cadamswaite** [comment]
Did you delete the original recipe before trying to import from the cloned version? 
When I tried your cloned version it worked ok in both dev and on demo.mealie.io, so I suspect it is an issue with duplicate names (#212) instead of with the cloned site

**Comment by hay-kot** [comment]
What exactly are you trying to accomplish here?

**Comment by dzek69** [comment]
Sorry for late reply.
@cadamswaite was right - it is because of #212.

@hay-kot I wanted to prepare a website that will be readable by Mealie. And to make sure everything works i started with cloning existing website which works just fine and then I wanted to remove all the unneeded stuff and change the content.

As now I know this is caused by another bug I'm closing this as no futher assistance is needed. Thank you!
