### ISSUE TITLE
Admin login change does not take effect

### ISSUE THREAD

**Issue by CollinChidiac** [mealie-recipes/mealie#753]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When first logging in with the default credentials, I am able to reach the admin page to change the email and username. After this I enter in the new password I'd like to use and save it. 

When I log out completely and try to log back in using the new credentials, it fails to log me in. I am able to login using the credentials I made for other users but not for the admin user. I then try to login using the original default credentials and this fails as well. I then do a mixture of the two; same error. 

I am at a loss as to why this is happening. Any information would be appreciated. 

### Deployment

Docker (Linux)

### Deployment Details

Docker container managed by Portainer.

### Mealie Version

v0.5.2

**Comment by hay-kot** [comment]
Can you reset the admin password on your profile page? I think the admin might be soft-locked from being updated on the admin page.

**Comment by CollinChidiac** [comment]
> Can you reset the admin password on your profile page? I think the admin might be soft-locked from being updated on the admin page.

<s>Well, unfortunately even after attempting a clean install it wont allow me to login with the default credentials. I attempted to delete out everything from the home folder that was mealie related but it seems like there are other files that are hanging around elsewhere that the reinstall uses. </s> I lied. Just got it to login using the default credentials. I am able to save my email in the "manage users" then go to the profile page to change the password as a workaround.
