### ISSUE TITLE
Cannot import recipes from Oda anymore

### ISSUE THREAD

**Issue by emilhetty** [mealie-recipes/mealie#754]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When trying to import recipes from Oda it now fails("Looks Like We Couldn't Find Anything")
For example [this ](https://oda.com/no/recipes/2943-silje-og-solvold-satayspyd-med-peanottsaus-og-agurksalat/) I already have imported before, but now I cannot import it again or any other recipe from Oda.

### Deployment

Docker (Linux)

### Mealie Version

0.5.2

**Comment by emilhetty** [comment]
I found the following errors in the log:
ERROR: 22-Oct-21 08:11:14 	Error parsing recipe func_call for 'totalTime'
ERROR: 22-Oct-21 08:11:14 	Error parsing recipe func_call for 'prepTime'
ERROR: 22-Oct-21 08:11:14 	Error parsing recipe func_call for 'performTime'
ERROR: 22-Oct-21 08:11:15 	Error Scraping Image: 'str' object has no attribute 'name'

**Comment by hay-kot** [comment]
Just tried it on the demo site and that URL is working. Are you running the `dev` tag or are you running `latest`?

**Comment by emilhetty** [comment]
I'm running `latest` tag.
I found the problem, it seems like when I try to add a recipe that I already have added before, I get the error("Looks Like We Couldn't Find Anything").
Just deployed a `dev` container and I could replicate this issue by importing the same recipe twice.
It should have been a better description when trying to import a recipe that is already imported.
