### ISSUE TITLE
Mealie Categories Not Displaying Until After Settings Opened 

### ISSUE THREAD

**Issue by Geektasticdad** [mealie-recipes/mealie#755]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When I first open Mealie and click Categories, the page is blank except for the word "Categories". However, when I go into the settings page, back to the main Mealie page, and then click Categories again they open just fine. 

![mealie](https://user-images.githubusercontent.com/73676044/138542943-565ac0ba-c9c1-4f4a-82a3-a4c35dae6317.gif)

### Deployment

Docker (Linux)

### Deployment Details

I'm running Mealie v0.5.2 with a Postgres database in a docker container. I use Nginx Proxy Manager to navigate to the URL and have Let's Encrypt SSL cert through NPM. I've attached my Portainer logs
 

### Mealie Version

0.5.2

**Comment by hay-kot** [comment]
This should be resolved in the `dev` branch if you want to give it a go. I'm doing testing this week, and will push out a release this week that addresses this issue, and the other similar ones.

**Comment by hay-kot** [comment]
Should be fixed in the new release (v0.5.3), please open a new issue if you're still experiencing it after upgrading.
