### ISSUE TITLE
[v1.0.0b] - Bulk Add ingredients not saving (after navigating away from recipe and returning)

### ISSUE THREAD

**Issue by coffee-mage** [mealie-recipes/mealie#766]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

**Steps to Produce**
1) Go to beta.mealie.io
2) Hit '+ Create' button
3) Select Create recipe manually
4) Set recipe name to 'Baked Meatballs2'.   Hit Create.
5) Hit pencil edit button.
6) Hit '+ Bulk Add' for ingredients.
7) Paste in text:
226 g ground beef
226 g ground veal
226 g ground pork
2 garlic
1/3 cup parmesan cheese
1/2 cup panko breadcrumbs
1 eggs
1 teaspoons salt
1/2 tsp fresh ground black pepper
1/2 tsp red pepper flakes
1/2 cup ricotta cheese
1/2 tbsp parsley, chopped
8) Hit Save
9) You can see ingredients seem to be in the recipe.  
<img width="1846" alt="screenshot1" src="https://user-images.githubusercontent.com/14890934/139596985-64b18940-bc68-40cd-b194-b168556758c6.PNG">

10) Save the recipe.
11) Ingredients in the recipe seem to work. 
<img width="1799" alt="screenshot2" src="https://user-images.githubusercontent.com/14890934/139596988-b63252b9-8394-4af9-bbc0-fbdcedd71f70.PNG">

12) Navigate away from recipe,  then search for Baked Meatballs2.
13) Click on recipe, and ingredients are gone. 
<img width="1820" alt="screenshot3" src="https://user-images.githubusercontent.com/14890934/139596991-85432f51-8332-48b0-8c8a-beb39f6a0d3b.PNG">

### Deployment

Other

### Deployment Details

Used https://beta.mealie.io/

**Comment by hay-kot** [comment]
This has been fixed 🎉
