### ISSUE TITLE
[v1.0.0b] - Recipe Creation Bugs

### ISSUE THREAD

**Issue by coffee-mage** [mealie-recipes/mealie#769]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

**Manual**
1) When doing image upload (either url or file).   After you hit Upload or Get, and it successfully completes.  Dialog box doesn't close.
2) When trying to add a new tag or categories (during recipe creation).  I hit the plus button,  it allows me to add the category/tag.  But after I hit create, the new category/tag doesn't get populated into category/tags checkbox list.  Without saving, and editing again.   Also it seems to add an undefined tag/category to the recipe.
3) Hitting Recipe Settings.  I'm not sure Public Recipe, Show Nutrition Values, Show Assets, and Disable Comments checkboxes do anything.
4) When you type in the recipe name, and hit create.  Should it jump you directly to the edit screen?  It currently dumps you into the view screen of the recipe with the name you provided.  I assume user will always hit edit again right after.
5) Should we be able to parse ingredients?  I hit the Parse All button, using the Natural Language Processor selection.   In the network log, I saw Internal Server error.

**Scrape**
6) Tried Scrape Recipe using this URL: 'https://www.allrecipes.com/recipe/282037/nanas-apple-crumble/'  When I clicked out of the textbox, it told me it was an invalid url.  I hit create anyways, and the scrape worked.
7) Tried to scrape the same recipe more than one.   Gave an error saying that the website did not support Id+json or microdata.   But when I looked in the network logs, the REST Api error message was 'Recipe name must be unique'.   Maybe we could test for response and give the user a better error message.
8) When hitting +Create button on sidemenu,  bulk import isn't in the options.    But if you click +Create, Import,  then select the dropdown on that page, you can see bulk import.
9) Bulk importer,  we may want to disable the submit button after user hits it.  I had 4 recipes on the bulk import, and hit the Submit button 5 times.  It seemed to choke the server, and app got very slow for a few minutes.

**Zip**
10) Couldn't test this functionality, as I couldn't get the recipe to export/download a zip file.

Let me know if any of these don't make sense.  Happy to give more detailed information.

### Deployment

Other

### Deployment Details

Linux,  git-hub clone, and development scripts.  SQLite database.

**Comment by hay-kot** [comment]
> Should we be able to parse ingredients? I hit the Parse All button, using the Natural Language Processor selection. In the network log, I saw Internal Server error.

You should, can you provide logs and/or the recipe you were trying to parse? 

---

Somewhat a side note. Huge thanks to you for putting these together. I was able to plow through those things in a few hours instead of days because of your quality bug reports. Seriously, thank you!

**Comment by coffee-mage** [comment]
So for some reason, my setup doesn't seem to be generating a mealie.log file.  I checked ./dev/data/mealie.log, but it wasn't there.  I will investigate more in the future.  Perhaps another bug.   For now I just copied the output of my console into a text file (attached).

I checked the same recipe on beta.mealie.io, and it seemed to work fine.
To simplify the issue on my end, I went to the admin section --> parser.  I tried to parse a single ingredient.  Attached is the console log.  Let me know if you need more.
[mealie_parser_crash.txt](https://github.com/hay-kot/mealie/files/7484239/mealie_parser_crash.txt)

**Comment by coffee-mage** [comment]
For the bulk import, what is the path you expect people to take to get to it?  Currently the only way I can find to get to it is:
1) Hit +Create
2) Import
3) Import with URL dropdown.
4) Bulk URL import.

**Comment by hay-kot** [comment]
> So for some reason, my setup doesn't seem to be generating a mealie.log file.  I checked ./dev/data/mealie.log, but it wasn't there.  I will investigate more in the future.  Perhaps another bug.   For now I just copied the output of my console into a text file (attached).
> 

If you're running in development mode, and not pulling the docker image, you'll need to download the crf model and crf++ installed to get the parser to work. Sound like that's what's going on, granted it isn't documented anywhere.

**Comment by hay-kot** [comment]
> For the bulk import, what is the path you expect people to take to get to it?  Currently the only way I can find to get to it is:
> 1) Hit +Create
> 2) Import
> 3) Import with URL dropdown.
> 4) Bulk URL import.

That's what I had in mind. I'm going to be adding additional things to the create button on the side and didn't want to over crowd it. Once I get closer to. A Release Candidate, I'll take another look at what I can include there without making it a gigantic list.

**Comment by hay-kot** [comment]
I think all these items were addressed... Closing for now, feel free to reopen if I missed something.
