### ISSUE TITLE
[v1.0.0b] - Recipe Page Interaction Bugs

### ISSUE THREAD

**Issue by coffee-mage** [mealie-recipes/mealie#771]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

1) Hitting favourite button on recipe screen doesn't do anything.  Seems to send a REST api request to http://address:3000/api/users/1/favorites/baked-meatballs.   But the request is null.
2) Hitting three dots, print. Doesn't do anything.
3) Hitting three dots, share.  Gives 404.
4) Hitting three dots, download.   Gives screen that says {"detail: "Not authenticated"}
5) If recipe is not in 'landscape mode'  Recipe stars has two places on recipe page to update.   If you update one, the other doesn't update  (until you refresh recipe).  Perhaps you plan to get rid of non-landscape-mode.
6) It is really hard to copy and paste ingredients out of the app into something else (like notepad), because of the checkbox components.  You can't really select the text of the ingredients.   Perhaps we don't want people to be able to do that.
7) If you hit random on the all recipes screen, with no recipes in the database.  It 404's.

Let me know if any of these don't make sense.  Happy to give more detailed information.

### Deployment

Other

### Deployment Details

Linux,  git-hub clone, and development scripts.  SQLite database.

**Comment by hay-kot** [comment]
Was able to get these fixed in 

- #778

**Comment by coffee-mage** [comment]
Testing the fixes.  Two other issues popped up:
1) Hitting three dots, share.  Gives 404.
2) The new copy ingredients button, gives 404.

**Comment by hay-kot** [comment]
> Testing the fixes.  Two other issues popped up:
> 1) Hitting three dots, share.  Gives 404.
> 2) The new copy ingredients button, gives 404.
> 

How are you running Mealie? The share and copy API require either localhost or secure (https) connection. In the admin section under site settings, if the secure site is red, a lot of the copy or share functionality won't work.

**Comment by coffee-mage** [comment]
That is likely it.  My current setup is a little odd.  I have a server in the basement, so running it off that and hosting to 192.168.1.6:3000.  Then connecting from another computer.

I will take a look at my setup, and try to tweak.  Consider this closed.
