### ISSUE TITLE
Add update instructions for manual/"docker-less" hosting to documentation

### ISSUE THREAD

**Issue by menewol** [mealie-recipes/mealie#772]
Hello, 

i was wondering whether theres update guides for mealie-instances that are not being hosted via the docker image but rather by starting the required components manually? 

i would like to update the instance on a regular basis, but feel that its not part of the game to extract the changes from the docker-image that is provided...

lokking forward to your feedback! 

BR

menewol

**Comment by cadamswaite** [comment]
You could follow the [dev setup instructions](https://hay-kot.github.io/mealie/contributors/developers-guide/starting-dev-server/#without-docker) - is that what you were looking for?

**Comment by hay-kot** [comment]
Hey! I added the documentation setup that's linked above as a way for people to install the application without a container, from there you're kind of on your own. 

I don't have any good suggestions on upgrading other than pull the changes from GitHub and restarting everything. _Technically_ I'm not supporting manual installs as I just don't have the time to manage all the edge cases and documentation. I understand that not everyone wants to use Docker, but from a maintainers perspective, I don't want to open the door to maintaining non-container installations.

Thanks!

**Comment by JedMeister** [comment]
FWIW I stumbled onto this thread looking for non docker instructions to install.

I get that as a dev, providing docker builds makes it much easier to support on a diverse range of host systems but OTOH I tend to run low resource systems and try to run them as lean as possible and the resource overhead for docker is completely ridiculous IMO.

Anyway, sorry for bitching. The point of my post wasn't to whinge. My intention was to simply tack on an updated link to the [Mealie dev setup docs](https://nightly.mealie.io/contributors/developers-guide/starting-dev-server/) to save a future docker skeptic from having to find it themselves.
