### ISSUE TITLE
 "POST /api/auth/token HTTP/1.1" 401

### ISSUE THREAD

**Issue by aramis-source** [mealie-recipes/mealie#774]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

getting 401 error trying to login to Mealie. any idea where is the problem ?

INFO: 04-Nov-21 01:50:11 	{
    "PRODUCTION": true,
    "BASE_URL": "http://localhost:8080",
    "IS_DEMO": false,
    "API_PORT": 9000,
    "API_DOCS": true,
    "DB_ENGINE": "postgres",
    "POSTGRES_SERVER": "postgres",
    "POSTGRES_PORT": "5432",
    "POSTGRES_DB": "mealie",
    "DB_URL_PUBLIC": "postgresql://*****:*****@postgres:5432/mealie",
    "DEFAULT_GROUP": "Home",
    "DEFAULT_EMAIL": "changeme@email.com",
    "TOKEN_TIME": 2,
    "RECIPE_PUBLIC": true,
    "RECIPE_SHOW_NUTRITION": true,
    "RECIPE_SHOW_ASSETS": true,
    "RECIPE_LANDSCAPE_VIEW": true,
    "RECIPE_DISABLE_COMMENTS": false,
    "RECIPE_DISABLE_AMOUNT": false,
    "SCHEDULER_DATABASE": "sqlite:////app/data/scheduler.db"
}
None
[2021-11-04 01:50:11 +0000] [41] [INFO] Application startup complete.
192.168.100.15:0 - "GET /api/groups/self HTTP/1.1" 401
192.168.100.15:0 - "GET /api/tags HTTP/1.1" 200
192.168.100.15:0 - "GET /api/debug/version HTTP/1.1" 200
192.168.100.15:0 - "GET /api/categories HTTP/1.1" 200
192.168.100.15:0 - "GET /api/site-settings HTTP/1.1" 200
192.168.100.15:0 - "GET /api/recipes/summary HTTP/1.1" 200
192.168.100.15:0 - "GET /api/categories HTTP/1.1" 200
192.168.100.15:0 - "GET /api/tags HTTP/1.1" 200
192.168.100.15:0 - "POST /api/auth/token HTTP/1.1" 401

### Deployment

Docker (Linux)

### Mealie Version

latest

**Comment by hay-kot** [comment]
That would indicate you're using the wrong password or email. 401 is unauthorized, so it can't find your email/password in the database.

**Comment by aramis-source** [comment]
I'm using the same username/password what I have in docker-compose.yml. Is there any specific format for the password  (have changed mealie to my own one)?

Full log below

> `Production
> usermod: no changes
> 
>     User uid:    911
>     User gid:    911
>     
> Database Doesn't Exists, Initializing...
> INFO: 04-Nov-21 07:19:18 	Generating Default Group
> INFO: 04-Nov-21 07:19:18 	Created Site Settings: 
>  language='en-US' first_day_of_week=0 show_recent=True cards_per_section=9 categories=[]
> INFO: 04-Nov-21 07:19:19 	Generating Default User
> None
> INFO: 04-Nov-21 07:19:21 	Checking for Images to Minify...
> INFO: 04-Nov-21 07:19:21 	Finished Minification Check
> {"level":"info","ts":1636010361.4617682,"msg":"using provided configuration","config_file":"/app/Caddyfile","config_adapter":""}
> {"level":"warn","ts":1636010361.4662397,"logger":"admin","msg":"admin endpoint disabled"}
> {"level":"info","ts":1636010361.4664924,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000438000"}
> {"level":"info","ts":1636010361.4671788,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/root/.local/share/caddy"}
> {"level":"info","ts":1636010361.467285,"logger":"tls","msg":"finished cleaning storage units"}
> {"level":"info","ts":1636010361.4674475,"msg":"autosaved config (load with --resume flag)","file":"/root/.config/caddy/autosave.json"}
> {"level":"info","ts":1636010361.4674654,"msg":"serving initial configuration"}
> Successfully started Caddy (pid=30) - Caddy is running in the background
> ---- Gunicorn Configuration ---- {
>     "loglevel": "info",
>     "workers": 1,
>     "bind": "127.0.0.1:80",
>     "graceful_timeout": 120,
>     "timeout": 120,
>     "keepalive": 5,
>     "errorlog": "-",
>     "accesslog": "-",
>     "workers_per_core": 1.0,
>     "use_max_workers": "1",
>     "host": "127.0.0.1",
>     "port": "80"
> }
> [2021-11-04 07:19:24 +0000] [39] [INFO] Starting gunicorn 20.1.0
> [2021-11-04 07:19:24 +0000] [39] [INFO] Listening at: http://0.0.0.0:9000 (39)
> [2021-11-04 07:19:24 +0000] [39] [INFO] Using worker: uvicorn.workers.UvicornWorker
> [2021-11-04 07:19:24 +0000] [40] [INFO] Booting worker with pid: 40
> [2021-11-04 07:19:24 +0000] [40] [INFO] Started server process [40]
> [2021-11-04 07:19:24 +0000] [40] [INFO] Waiting for application startup.
> INFO: 04-Nov-21 07:19:24 	Adding job tentatively -- it will be properly scheduled when the scheduler starts
> INFO: 04-Nov-21 07:19:24 	Adding job tentatively -- it will be properly scheduled when the scheduler starts
> INFO: 04-Nov-21 07:19:24 	----INIT SCHEDULE OBJECT-----
> INFO: 04-Nov-21 07:19:24 	Adding job tentatively -- it will be properly scheduled when the scheduler starts
> INFO: 04-Nov-21 07:19:24 	Adding job tentatively -- it will be properly scheduled when the scheduler starts
> Pending jobs:
>     purge_events_database (trigger: interval[1 day, 0:00:00], pending)
>     update_webhook_schedule (trigger: interval[0:30:00], pending)
>     backups (trigger: cron[hour='0', minute='0'], pending)
>     Home (trigger: cron[hour='0', minute='0'], pending)
> INFO: 04-Nov-21 07:19:24 	None
> INFO: 04-Nov-21 07:19:24 	Added job "purge_events_database" to job store "default"
> INFO: 04-Nov-21 07:19:24 	Added job "update_webhook_schedule" to job store "default"
> INFO: 04-Nov-21 07:19:24 	Added job "backups" to job store "default"
> INFO: 04-Nov-21 07:19:24 	Added job "Home" to job store "default"
> INFO: 04-Nov-21 07:19:24 	Scheduler started
> INFO: 04-Nov-21 07:19:24 	-----SYSTEM STARTUP----- 
> 
> INFO: 04-Nov-21 07:19:24 	------APP SETTINGS------
> INFO: 04-Nov-21 07:19:24 	{
>     "PRODUCTION": true,
>     "BASE_URL": "http://localhost:8080",
>     "IS_DEMO": false,
>     "API_PORT": 9000,
>     "API_DOCS": true,
>     "DB_ENGINE": "postgres",
>     "POSTGRES_SERVER": "postgres",
>     "POSTGRES_PORT": "5432",
>     "POSTGRES_DB": "mealie",
>     "DB_URL_PUBLIC": "postgresql://*****:*****@postgres:5432/mealie",
>     "DEFAULT_GROUP": "Home",
>     "DEFAULT_EMAIL": "changeme@email.com",
>     "TOKEN_TIME": 2,
>     "RECIPE_PUBLIC": true,
>     "RECIPE_SHOW_NUTRITION": true,
>     "RECIPE_SHOW_ASSETS": true,
>     "RECIPE_LANDSCAPE_VIEW": true,
>     "RECIPE_DISABLE_COMMENTS": false,
>     "RECIPE_DISABLE_AMOUNT": false,
>     "SCHEDULER_DATABASE": "sqlite:////app/data/scheduler.db"
> }
> None
> [2021-11-04 07:19:24 +0000] [40] [INFO] Application startup complete.
> 192.168.100.15:0 - "GET /api/groups/self HTTP/1.1" 401
> 192.168.100.15:0 - "GET /api/debug/version HTTP/1.1" 200
> 192.168.100.15:0 - "GET /api/tags HTTP/1.1" 200
> 192.168.100.15:0 - "GET /api/categories HTTP/1.1" 200
> 192.168.100.15:0 - "GET /api/site-settings HTTP/1.1" 200
> 192.168.100.15:0 - "GET /api/recipes/summary HTTP/1.1" 200
> 192.168.100.15:0 - "GET /api/site-settings HTTP/1.1" 200
> 192.168.100.15:0 - "GET /api/groups/self HTTP/1.1" 401
> 192.168.100.15:0 - "GET /api/debug/version HTTP/1.1" 200
> 192.168.100.15:0 - "GET /api/tags HTTP/1.1" 200
> 192.168.100.15:0 - "GET /api/categories HTTP/1.1" 200
> 192.168.100.15:0 - "GET /api/site-settings HTTP/1.1" 200
> 192.168.100.15:0 - "GET /api/recipes/summary HTTP/1.1" 200
> 192.168.100.15:0 - "GET /api/site-settings HTTP/1.1" 200
> 192.168.100.15:0 - "POST /api/auth/token HTTP/1.1" 401`

**Comment by aramis-source** [comment]
with your default docker-compose.yml seeing the same 401 error


> version: "3.1"
> services:
>   mealie:
>     build:
>       context: ./
>       target: production
>       dockerfile: Dockerfile
>     container_name: mealie
>     restart: always
>     depends_on:
>       - "postgres"
>     ports:
>       - 9090:80
>     environment:
>       DB_ENGINE: postgres # Optional: 'sqlite', 'postgres'
>       POSTGRES_USER: mealie
>       POSTGRES_PASSWORD: mealie
>       POSTGRES_SERVER: postgres
>       POSTGRES_PORT: 5432
>       POSTGRES_DB: mealie
>       # WORKERS_PER_CORE: 0.5
>       # MAX_WORKERS: 8
>       # WEB_CONCURRENCY: 2
>   postgres:
>     container_name: postgres
>     image: postgres
>     restart: always
>     environment:
>       POSTGRES_PASSWORD: mealie
>       POSTGRES_USER: mealie

**Comment by hay-kot** [comment]
1. What username and password are you using?
2. does the same error occur if you use SQLite?

**Comment by aramis-source** [comment]
1. username: mealie  & password: mealie
2. didn't try SQLite

> docker-compose version 1.29.2, build 5becea4c
> docker-py version: 5.0.0
> CPython version: 3.7.10
> OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
>

**Comment by hay-kot** [comment]
> username: mealie & password: mealie

Those are the credentials for the database. [Review the installation guide](https://hay-kot.github.io/mealie/documentation/getting-started/install/) and try the default credentials listed there. Additionally, unless you're planning on 10+ concurrent users, I suggest you use SQLite. It's self-contained, and better tested.

**Comment by aramis-source** [comment]
Thank you for this clarification and sory for misunderstanding. 
Changing the user I should do it in the template.evn before or just from UI ?
