### ISSUE TITLE
[v1.0.0b] - Parser Issues

### ISSUE THREAD

**Issue by coffee-mage** [mealie-recipes/mealie#783]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

1) Took a recipe with these ingredients:
226 g ground beef
226 g ground veal
226 g ground pork
2 garlic
1/3 cup parmesan cheese
1/2 cup panko breadcrumbs
1 eggs
1 teaspoons salt
1/2 tsp fresh ground black pepper
1/2 tsp red pepper flakes
1/2 cup ricotta cheese
1/2 tbsp parsley, chopped

Fed it into the parser.  Parser did a pretty good job of matching it.  I manually fixed the rest.
See screenshot.  Everything is looking good:   
<img width="1377" alt="good_ingredient_parse1" src="https://user-images.githubusercontent.com/14890934/140585445-b94e604f-db2c-4b30-9b55-13bc97d28c01.PNG">

Hit Save all,  and the ingredients end up being nuked in the recipe:
<img width="1372" alt="nuked_ingredients_in_recipe2" src="https://user-images.githubusercontent.com/14890934/140585459-203eb124-b767-4b2c-b46c-9b97803de714.PNG">

2) Parse ingredients seems to work on ingredients in the database, not ingredients input into the frontend.
This creates a confusing situation for the user, they probably don't expect it.  They need to save any ingredient changes before using the parser.

If it isn't possible to read from the front-end/client side.  Could you create a flag that tracks whether the front-end ingredients is out of sync with database.  If so disable the parse button, and let user know they have to save ingredients first.  Also it would be nice to be able to save ingredients without exiting the editor window.

3) Perhaps Parse button should be disabled/invisible while there are no ingredients in the recipe.

4) It takes a lot of clicks to activate the parser.   Parse --> Confirm --> Parse.
Could we put the warning text from the confirm button in the parse page?  This could eliminate the confirm button.  Also I wonder what percentage of people will switch from NLP to Brute?  NLP was working great for me.  Perhaps when the parse page loads, it parses automatically with NLP (or last parser used).  If you don't like the results you can hit a button to switch to the other.

### Deployment

Other

### Deployment Details

beta.mealie.io

**Comment by hay-kot** [comment]
> Hit Save all, and the ingredients end up being nuked in the recipe:

Can you verify that Disable Ingredient Amounts is unchecked?

<img width="570" alt="Screen Shot 2021-11-05 at 2 44 56 PM" src="https://user-images.githubusercontent.com/64056131/140586485-0f10ce06-6e68-4e39-9ac0-aa5addebbfb5.png">


> It takes a lot of clicks to activate the parser. Parse --> Confirm --> Parse.

I think the overall flow needs some improvement, you're correct. Will have to think about this one some more. in relation to the other issues you raised.

> NLP was working great for me.

NLP is going to work great for any recipes that are primarily in English. Anything else get's garbage results. 

---

Will look into a PR for this once I finish up with the one I've got open. Thanks!

**Comment by coffee-mage** [comment]
Yes you were correct disable ingredient amounts was checked.  I unchecked and it showed things properly.    
If you have disable ingredient amounts checked,  it looks like it displays the note, instead of the ingredient.  Hence all the blanks.  It should probably show the concatenation of ingredient and note,  or just ingredient (instead of note).

Take your time on fixing things.  Just trying to get lists of issues on the board for you.

**Comment by hay-kot** [comment]
Note from

- #789 

> Parse ingredients seems to work on ingredients in the database, not ingredients input into the frontend.
This creates a confusing situation for the user, they probably don't expect it. They need to save any ingredient changes before using the parser.

You're now prompted with an alert before navigating from the recipe editor to save your changes. 

> Perhaps Parse button should be disabled/invisible while there are no ingredients in the recipe.

I think I've mitigated this problem with some other improvements. [See my comment here](https://github.com/hay-kot/mealie/issues/788#issuecomment-962517491)

> It takes a lot of clicks to activate the parser. Parse --> Confirm --> Parse.
>
>Could we put the warning text from the confirm button in the parse page? This could eliminate the confirm button. Also I wonder what percentage of people will switch from NLP to Brute? NLP was working great for me. Perhaps when the parse page loads, it parses automatically with NLP (or last parser used). If you don't like the results you can hit a button to switch to the other.

Warning text has been moved to the parser page. On navigation you'll either be prompted to save changes or be navigation automatically, depending on state. Additionally, the parser will automatically run on navigation. We can also set the default parser at a later date.

**Comment by hay-kot** [comment]
I think all these items were addressed... Closing for now, feel free to reopen if I missed something.
