### ISSUE TITLE
[v1.0.0b] - Nov 4-6 Commits

### ISSUE THREAD

**Issue by coffee-mage** [mealie-recipes/mealie#788]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

1) Password change works.   When you hit the update button, it doesn't give the user any visual indication that it worked.  I was expecting the password window to close and go back to the user profile window.  Or something else to give an indicator that password change worked.

2) Cook mode is awesome!  I love it.  Once  you go to cook mode, you seem to get locked into it.  I think we need one more button/hyperlink to easily go back or toggle to recipe page if we want to.   Also when you hit the last step, next button is disabled.  Perhaps it should turn into 'Finish' button, and it goes back to recipe.

3) When you link ingredients to steps, it feels redundant to have the step ingredients and the ingredients sidebar.  I think they are both useful for different reasons.  Could we have some sort of checkbox/slider for swapping between sidebar ingredients and instruction ingredients?

4) When you are linking ingredients (actions -> Link ingredients).  It shows a window with all the ingredients.  It would be nice if that checkbox list was filtered to only unassigned ingredients.

5) On cook mode, you may have steps that don't have any new ingredients.  In that case, let's hide the ingredients box.

6) In the NLP parser, I think all ingredient boxes should be expanded so you can see what the NLP has done without clicking (regardless of match score).  As an example, this morning, I had a 76% match that was minimized, but it hadn't identified the food at all.  I didn't even see the  'Create missing food 'chicken stock' button.

7) In the NLP parser, when you are doing manual overrides.  If you are typing in a new food item to be added.  You must hit the '+ Create' button after typing.  would be nice to add 'Enter' event handler to the input box, so you don't have to reach for the mouse.  Also after you hit the '+ Create' button, the food dropdown remains open.

8) When you NLP parse ingredients, it seems to set 'Disable ingredient amounts' to true by default.  I'm not sure it should do that.  That should be something the user decides to set.  After I parse, I always go and re-enable ingredient amounts.

9) Recipe -- Add to mealplan worked well.

10) I'm not sure I understand the Split by Numbered Line feature.  As far as I can tell, it takes a paragraph filled with numbers, and no breaks.  Then it breaks it out into individual steps.   Does this recipe format occur alot on websites?  I'm not sure I have ever seen this format.   With that being said, I think there is an issue in the parser.  If you have more than 10 steps, it starts adding 1 to the end of any step after 9. 
<img width="680" alt="break paragraph by number" src="https://user-images.githubusercontent.com/14890934/140609283-101152cd-24a1-4d90-a8aa-17151e829324.PNG">

11)  On the ingredient parser, perhaps we should hide Split by Numbered Line button?  I don't think it would get used on that input.

### Deployment

Other

### Deployment Details

Linux,  git-hub clone, and development scripts.  SQLite database.

**Comment by hay-kot** [comment]
Notes from 

- #787

> button/hyperlink to easily go back or toggle to recipe page if we want to. 

Added a "Back to Recipe" button 

>  Perhaps it should turn into 'Finish' button, and it goes back to recipe.

I'm toying around with a few ideas here. I think a finished button might be goo.d Maybe that would ask you to rate it or something else? I'm not sure. 

> When you link ingredients to steps, it feels redundant to have the step ingredients and the ingredients sidebar.

I agree. I removed them from the regular view. They'll not only show when editing, which I think is a useful visual indicator that items have been linked. I think having the ingredients that are linked shown in the "Cook" mode is sufficient for now.  

> It would be nice if that checkbox list was filtered to only unassigned ingredients.

It now shows two sections, one with already linked ingredients, and one without. Incase you want to link two to one step.

> In that case, let's hide the ingredients box

Done.

> As far as I can tell, it takes a paragraph filled with numbers, and no breaks.

That's basically it. It's a helper for when the automatic parser doesn't work. I've had a couple recipes where it's useful. It uses regex matching to find '1: ' '1. ' or '1) ' and splits on those. 

> With that being said, I think there is an issue in the parser. If you have more than 10 steps, it starts adding 1 to the end of any step after 9.

I was not accounting for double digits, but it's now been fixed.

> On the ingredient parser, perhaps we should hide Split by Numbered Line button? I don't think it would get used on that input.

No harm in leaving it. I've had all kinds of weird things come in when copy/pasting.

**Comment by hay-kot** [comment]
Note from

- #789 

> In the NLP parser, I think all ingredient boxes should be expanded so you can see what the NLP has done without clicking (regardless of match score). As an example, this morning, I had a 76% match that was minimized, but it hadn't identified the food at all. I didn't even see the 'Create missing food 'chicken stock' button.

Makes sense to me. Thanks for the feedback! Should not default to open for all items.

> In the NLP parser, when you are doing manual overrides. If you are typing in a new food item to be added. You must hit the '+ Create' button after typing. would be nice to add 'Enter' event handler to the input box, so you don't have to reach for the mouse. Also after you hit the '+ Create' button, the food dropdown remains open.

Took me a bit to get this one figured out. I did get it working, but it's possible there's still some rough edges. 

> When you NLP parse ingredients, it seems to set 'Disable ingredient amounts' to true by default. I'm not sure it should do that. That should be something the user decides to set. After I parse, I always go and re-enable ingredient amounts.

It wasn't changing it, it's just that if it is disabled, it won't enable them. I've added a lock to the parse button so you can't click it unless you have the settings set correctly. It also provides a tooltip to let you know. 

<img width="608" alt="Screen Shot 2021-11-06 at 2 20 50 PM" src="https://user-images.githubusercontent.com/64056131/140625384-1ec33e42-2a0d-41da-9821-ab20f7493240.png">

**Comment by coffee-mage** [comment]
1) When creating a new food in parser,  enter will create the food.  But after the food is created/populated, the drop-down remains open.  I have started to get used to typing the food, hit enter (to create), hit escape (to get rid of select box).

2) If you have ingredients that are already split by amount/unit/food/notes, and you hit parse.  It will only grab the rows that have a note in it.  If you hit save, it will mangle all the ingredients.  See screenshots.  Parse should probably check all the fields amount/unit/food/notes and prepopulate if they exist, instead of overwriting everything.
<img width="1390" alt="parse_mangle1" src="https://user-images.githubusercontent.com/14890934/140646857-cb966ffc-3da7-47c9-9cdb-c512ef0ce043.PNG">
<img width="1413" alt="parse_mangle2" src="https://user-images.githubusercontent.com/14890934/140646861-5cb46004-6ed4-423e-a7be-df7843c910dc.PNG">


3) Instead of disabling parse, until we allow ingredient amounts.  could the parse button just enable ingredient amounts for you?   I think your save dialog warning fixes the user confusion I was talking about before (frontend ingredients vs database ingredients).

4) You can enable ingredient amounts, and hit parse on an empty ingredient list.  Parse should probably be invisible until you have ingredients in the list.

5) The save warning dialog box buttons are slightly confusing.  It says something along the lines of 'You have unsaved changes'.   Then Ok/Cancel.   Okay makes sense to me, you save and proceed.  I would have expected cancel to stop the parse, and remain on the existing page.  Instead it doesn't save and proceeds to parse.

6) Another weird thing I noticed, if that save dialog box appears, and i click to another tab in the browser.  It appears to automatically select cancel, and proceed to the parser with no ingredients.
