### ISSUE TITLE
what does "recipe_scrapers was unable to scrape this URL" mean?

### ISSUE THREAD

**Issue by ovizii** [mealie-recipes/mealie#795]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I am trying to scrape this recipe: https://thehappyfoodie.co.uk/recipes/flamenco-eggs-with-tomato-and-serrano-ham/ 

and am getting "recipe_scrapers was unable to scrape this URL" 

does this simply mean the recipe does not have the required formatting or is there some other error at hand?

### Deployment

Docker (Linux)

### Mealie Version

v0.5.3

**Comment by hay-kot** [comment]
The error message in the UI provides this information, did you not get the error message?

![image](https://user-images.githubusercontent.com/64056131/141189582-675ff44c-fb63-4e7d-a9e7-c713d1e8a9f7.png)

**Comment by ovizii** [comment]
sorry about that, this was a misunderstanding on my side. I actually had to re-read the error message thrice even after you posted it here. The error is on this side of the screen, no idea how I misunderstood what is actually made very clear in your error message :-(
