### ISSUE TITLE
[v1.0.0b] - 2021-11-16 Search Feedback

### ISSUE THREAD

**Issue by coffee-mage** [mealie-recipes/mealie#804]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

1) Search always seems to find stuff, even if it doesn't seem to be a match in the slightest.  On my own instance, I searched for 'soup',  It returned the one soup I had, and 4 copies of meatballs.  lol.   On beta.mealie.io, I searched a garbage string that shouldn't match anything.  Still returned 5 results.
<img width="759" alt="search_find_stuff" src="https://user-images.githubusercontent.com/14890934/142004697-cd3884d7-7235-498e-82e4-13e7575c0f58.PNG">

2) In the small search window (hit / to bring up).   I click advanced search.  It takes me to the regular search window, but not in advanced mode.  Should probably open in advanced mode.

3) Search window, food filter.  I typed in pork.  It gave me a dropdown to select 'ground pork'.  I did, and it properly added the tag.   But it left the pork string in the search box after the tagged food item.  It also leaves the selection box open.  Ideally it would remove the text i just matched, and close the selection box.
<img width="589" alt="ingredient_search" src="https://user-images.githubusercontent.com/14890934/142004727-a1038c13-07e6-4b60-982b-880903c1a1b1.PNG">

4) Food filter only seems to work if you have converted your text ingredients into amount/measurement/food combos.  Should it work on regular text ingredients?   I plan to always map my ingredients, but other people may not?

### Deployment

Other

### Deployment Details

Linux,  git-hub clone, and development scripts.  SQLite database.

**Comment by hay-kot** [comment]
> Search window, food filter. I typed in pork. It gave me a dropdown to select 'ground pork'. I did, and it properly added the tag. But it left the pork string in the search box after the tagged food item. It also leaves the selection box open. Ideally it would remove the text i just matched, and close the selection box.

This is the default behavior of the component we use for selector. Probably going to leave it the way it is for now. 

> Food filter only seems to work if you have converted your text ingredients into amount/measurement/food combos. Should it work on regular text ingredients? I plan to always map my ingredients, but other people may not?

Food filters do only work if you've defined ingredients. I'm not sure there's a non-resource intensive way to do this. You'd have to iterate through every recipe and perform a text search. This would also assume that you'd have your ingredients named exactly as is displayed...and if that's the case I'd assume you'd just set it up anyways? If it becomes an issue after the RC is out, maybe I'll take another look at it. 🤷

**Comment by epheterson** [comment]
> Search always seems to find stuff, even if it doesn't seem to be a match in the slightest. 

Agree this is very odd, search should be able to show zero results or only what matches, but doesn’t seem to be the case and makes parsing the results confusing.

**Comment by anoncl** [comment]
>     1. Search always seems to find stuff, even if it doesn't seem to be a match in the slightest.  On my own instance, I searched for 'soup',  It returned the one soup I had, and 4 copies of meatballs.  lol.   On beta.mealie.io, I searched a garbage string that shouldn't match anything.  Still returned 5 results.

I thought i would add that i have also experienced this. I've also noticed that it does not return results I expect it to. For example I searched "pancakes" on my instance and it left out one named " Gluten-Free Buckwheat Pancakes" until I added a "pancakes" tag. I have noticed this on other recipes also. 
Using  v1.0.0beta-4

**Comment by Orybon** [comment]
Same issue here. I am really enjoying mealie so i put many recipes in our server. But now that i need to search among them it's very hard top find a recipe with the search engine.
