### ISSUE TITLE
[v1.0.0b] - New user form send twice fullName instead of username

### ISSUE THREAD

**Issue by gabt92** [mealie-recipes/mealie#813]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

This issue is not in version 0.5.

When I create a new user and fill all the fields as follow: 
![image](https://user-images.githubusercontent.com/38195308/142959367-22212968-117b-4f19-bb58-510aa4ea1ad2.png)

The information sent to the backend is with the wrong mapping on the field: 
![image](https://user-images.githubusercontent.com/38195308/142959435-b09ff896-2a17-43a5-bc4f-f033ca689a88.png)

And finally, we get this results when looking at the users: 
![image](https://user-images.githubusercontent.com/38195308/142959570-a0856855-6934-49c2-8825-b5d1fdf8a5af.png)
I guess the loading is fine, but sending the wrong information as username is problematic.
 

### Deployment

Other

### Deployment Details

Using the beta on https://beta.mealie.io/

**Comment by hay-kot** [comment]
This has been fixed in v1
