### ISSUE TITLE
[v1.0.0b] - French typos and fr-CA translation

### ISSUE THREAD

**Issue by gabt92** [mealie-recipes/mealie#816]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

~~"Création" and "Mise à jour" are feminine words so the verbs following them need a "e" at the end.~~

Also, if you want a french canadian version in a different file, I would recommand changing "liste de courses" by "liste d'épicerie".

![image](https://user-images.githubusercontent.com/38195308/142967747-13d276ba-cd9c-4114-814c-585e4a2599e9.png)

Solution:
~~Here is the JSON file in txt format.
[fr-FR.json.txt](https://github.com/hay-kot/mealie/files/7585669/fr-FR.json.txt)~~

Possible french canadian version
[fr-CA.json.txt](https://github.com/hay-kot/mealie/files/7585689/fr-CA.json.txt)

 

### Deployment

Other

**Comment by sephrat** [comment]
You can use Crowdin to suggest translations: https://hay-kot.github.io/mealie/contributors/translating/
I'm not sure I understand the feminine issue so I'll let you raise issues on Crowdin if needed. Otherwise please show us an example of where it is wrong.

As for the Canadian variant, this is the first request we received. We can add it to Crowdin if you feel up to the task of contributing to it. What do you think?

**Comment by gabt92** [comment]
Sure why not!

**Comment by sephrat** [comment]
You can now translate Mealie into Canadian French on Crowdin! Get back to us once it's done so we can reference the language in Mealie.

**Comment by gabt92** [comment]
I'm pretty much done with the fr-CA translation. I just have a question about one string limited to 14 characters due to space limitation (I think). If those changes are to be applied to the v1.0, then I think that the limit could be increased to 15 characters to allow "Tableau de bord" instead of "Dashboard" since the sidebar seems a little bit larger...
![image](https://user-images.githubusercontent.com/38195308/143055819-983178af-7269-4452-ad91-183be36608ba.png)

**Comment by sephrat** [comment]
You're right, this restriction was set due to width limitation. I'll look into changing it once we consider working on v1 localization. For now Crowdin is still plugged in to v0.x branch. 

[french digression] Also FYI, I took a look into the feminine form you were talking about based on your work on Crowdin (great job!). The previous form was actually correct: you're not supposed to use feminine form after "avoir" 😉 so it should be "la mise à jour a échou**é**", not "échoué**e**"  .

**Comment by gabt92** [comment]
Also, I reviewed the fr-FR translation because of the mistakes mentionned earlier.

"

> [french digression] Also FYI, I took a look into the feminine form you were talking about based on your work on Crowdin (great job!). The previous form was actually correct: you're not supposed to use feminine form after "avoir" 😉 so it should be "la mise à jour a échou**é**", not "échoué**e**" .

Actually, it's more complex than that. It's French, how could it be simple ? haha Let me try to explain it to you in english...

In French, we have something called "Complément d'objet direct (COD)". By definition, it's something that add details to an object (a word). Normally, this COD is not following the feminine form of word with the verb "avoir" as you mentionned, but the rule is more complex. 

Let me use a simple sentence meaning "The man that I saw" and "The woman that I saw". In french, the good way to write those is:
- L'homme que j'ai vu
- La femme que j'ai vue

The rule is quite simple, we only have to ask ourself a question: "J'ai vu **quoi**", meaning "I saw **what**" and if the answer is after the verb, then the COD is invariable. If the answer is before the verb, then it is variable.
For exemple, in this case, since "homme" and "femme" are **after** the verb, then it is invariable.
- J'ai vu l'homme
- J'ai vu la femme

In our case, we have the words "Création, suppression, mise à jour" which are feminine and the sentences are: 
- La création de {object} a échouée

Following the rule, what _failed_ ? The creation. Is it **before** the verb "a" then "échouée" which is the COD is variable.

https://grammaire.reverso.net/accord-du-participe-passe-avec-avoir/
https://la-conjugaison.nouvelobs.com/regles/orthographe/l-accord-du-participe-passe-employe-avec-l-auxiliaire-avoir-179.php

**Comment by sephrat** [comment]
I'm sorry but I disagree with your interpretation of this grammar rule and won't approve your suggestions. I suggest we continue this conversation on Crowdin where this is more relevant. I'll PM you with my arguments.

Let's keep this issue open to track the request for adding fr-CA to Mealie. I'll probably work on a PR myself when I get to it.

**Comment by gabt92** [comment]
> I'm sorry but I disagree with your interpretation of this grammar rule and won't approve your suggestions.

In fact, writing about it made me doubt myself. I saw it more complex that it was.

**Passé composé**
j'ai échoué
tu as échoué
il/elle a échoué
nous avons échoué
vous avez échoué
ils/elles ont échoué

In our case, we simply change "il/elle" by "La création de {object}" so its invariable. I'll apply the changes to Crowdin, sorry about that!

**Comment by hay-kot** [comment]
Has this been resolved with @sephrat's work in the `dev` branch and with the most recent release?

**Comment by sephrat** [comment]
Still need to add fr-CA to the list of available languages. I'll see to it.
