### ISSUE TITLE
Trying to create a recipe with the name "Peanut Butter Banana Baked Oatmeal" fails

### ISSUE THREAD

**Issue by azuntik** [mealie-recipes/mealie#823]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

This is really strange. At first I thought it was an issue with length or some other validation, but I don't think that's the case. This specific title fails. If I add or remove a single character or change the order of the words, it creates the recipe just fine. But this particular name, in this order, regardless of capitalization or punctuation, gives me an error message that the recipe could not be created.

If I create a recipe with another name and then try to update it to this name, the update fails.

Am I losing my mind or can someone confirm this?

I worked around this issue by naming it something else, but it's strange that it would have this behavior to begin with.

### Deployment

Docker (Linux)

### Mealie Version

0.5.3

**Comment by gabt92** [comment]
Is there one with the same name already?

**Comment by azuntik** [comment]
Okay. I'm an idiot. I have hundreds of recipes and when I searched there is indeed another recipe with the same name.

It might be good to have a slightly more descriptive error message, like "a recipe with the same name already exists in the database" or similar.

Thanks for your help! Sorry for being an idiot!

**Comment by hay-kot** [comment]
> It might be good to have a slightly more descriptive error message, like "a recipe with the same name already exists in the database" or similar.

There's a better error message in v1 that says it's a duplicate. Hopefully we'll have a usable v1 soon! closing this for now. Thanks!
