### ISSUE TITLE
[v1.0.0b] - Problem when restoring a backup

### ISSUE THREAD

**Issue by blueline13** [mealie-recipes/mealie#827]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

The self-created Foods and Units can be restored from the backup.

1) Create a recipe with new foods and/or units that are not yet in the DB
2) Create a backup and save it
3) Delete the Docker container
4) Create a new container with an empty DB
5) Load the backup again and restore it
6) Now the foods and units created before the backup are missing in the DB and in the recipe

### Deployment

Docker (Linux)

### Deployment Details

Tested with the Docker image from today.

**Comment by hay-kot** [comment]
Can you provide your logs?

FYI, this isn't some I'm actively supporting or testing. Migration from v0.5.x will be supported but moving from a v1 beta to the next is not guaranteed. It should really only be used for testing.

**Comment by blueline13** [comment]
I made a mistake with the title and corrected it.

Here are the logs from the container and mealie during the restore and the next line after. But there are no errors during the restore to see . The time of the restore was around 23:39:39.

Container.log
2021-11-24T22:39:03.734451597Z 172.17.0.2:43078 - "GET /api/backups/available HTTP/1.1" 200
2021-11-24T22:39:13.892929060Z 172.17.0.2:43080 - "POST /api/backups/upload HTTP/1.1" 200
2021-11-24T22:39:14.017813984Z 172.17.0.2:43086 - "GET /api/backups/available HTTP/1.1" 200
2021-11-24T22:39:39.509228344Z INFO: 24-Nov-21 22:39:39 	Checking for Images to Minify...
2021-11-24T22:39:39.557338283Z INFO: 24-Nov-21 22:39:39 	Finished Minification Check
2021-11-24T22:39:39.684164699Z 172.17.0.2:43090 - "POST /api/backups/2021-Nov-21.zip/import HTTP/1.1" 200
2021-11-24T22:39:39.731759154Z 172.17.0.2:43092 - "GET /api/backups/available HTTP/1.1" 200
2021-11-24T22:44:00.214704870Z 172.17.0.2:43148 - "GET /api/about/events HTTP/1.1" 200

Mealie.log
INFO: 24-Nov-21 22:39:39        Checking for Images to Minify...
INFO: 24-Nov-21 22:39:39        Finished Minification Check
WARNING: 24-Nov-21 22:51:51     Error getting due jobs from job store 'default': (sqlite3.OperationalError) unable to open database file (Background on this error at: https://sqlalche.me/e/14/e3q8)

For better understanding what should happen. During the restore it seems that new "foods" and "units" that are included in the backup but are not yet present, are not created during the restore.

Here is an excerpt from the backup of a recipe and what can be seen afterwards in mealie.
}
    "title": null,
    "note": "oder Reisessig",
    "unit": {
        "name": "EL",
        "description": "",
        "fraction": true,
        "abbreviation": "",
        "id": 35
    },
    "food": {
        "name": "Sushi Essig",
        "description": "",
        "id": 323
    },
    "disable_amount": true,
    "quantity": 1.0,
    "reference_id": "a4003225-b5d0-423f-a48e-1ef92e77c711"
},

![grafik](https://user-images.githubusercontent.com/56932380/143408696-0134a66a-dd47-412a-ae1e-c163d27ce527.png)

**Comment by hay-kot** [comment]
Hey! Mealie v1 Beta now supports full site import/export via the Admin panel including foods and units.
