### ISSUE TITLE
No vertical scroll bars when using Firefox browser

### ISSUE THREAD

**Issue by freddieFishCake** [mealie-recipes/mealie#828]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

The Mealie UI doesn't show vertical scroll bars in Firefox - but does in e.g. Chromium. Screen shots attached.
Lack of vertical scroll bars means that the user can't scroll down the page to read the rest of the recipe.
A mouse wheel can be used as a workaround, but not all mice (or laptop trackpads) have a wheel.

Screenshot from Firefox:
![Screenshot from 2021-11-24 15-07-48](https://user-images.githubusercontent.com/8157954/143263411-b963885b-5eb9-426c-88c5-6f389f7b94cf.png)

Screenshot from Chromium:
![Screenshot from 2021-11-24 15-09-40](https://user-images.githubusercontent.com/8157954/143263732-4a35586c-13a4-4628-b6fb-d572ec607119.png)

### Deployment

Docker (Synology)

### Mealie Version

v0.5.3

**Comment by cadamswaite** [comment]
So I think the scrollbar is there, just invisible.. (transparent on transparent)

This seems to be caused by [d85e3a4](https://github.com/hay-kot/mealie/pull/406/commits/2a37900aceef0aa6bd8932d6fa1bc2c42d85e3a4) - I'm not sure of the original intention of this commit, so I won't revert it @hay-kot

**Comment by hay-kot** [comment]
> So I think the scrollbar is there, just invisible.. (transparent on transparent)
> 
> This seems to be caused by [d85e3a4](https://github.com/hay-kot/mealie/pull/406/commits/2a37900aceef0aa6bd8932d6fa1bc2c42d85e3a4) - I'm not sure of the original intention of this commit, so I won't revert it @hay-kot

I like the styling of the transparent scroll bar similar to what MacOS does. It does bring up an accessibility concern. You (or anyone else) welcome to update the styling to be more accessible if you'd like, otherwise I can take a look later. 

Perhaps something like this? 

https://mdbootstrap.com/snippets/jquery/mdbootstrap/944182#css-tab-view
