### ISSUE TITLE
[v1.0.0b] [Task] - Async Input Validators

### ISSUE THREAD

**Issue by hay-kot** [mealie-recipes/mealie#832]
### What is the problem this task addresses?

There are several inputs that are restricted by unique values 

- Recipe Names
- User Names
- Group Names
- ?? Probably others

Often times no user feedback is provided until the form is submitted and sometimes not at all. 

### Proposed/Possible Solution(s)?

Several endpoints should be created to do Async validation on input fields throughout the applications. 

Endpoints should follow a pattern as follows `/api/validators/{validator-type}` 

Endpoint should take in a post with a value attributed and return a { valid: bool } payload.

Implementation of async validators on the frontend is still a little unclear. It appears that you would have to manually use a validation on blur to verify that input and manually mark it invalid. This can likely be done in a reusable way by using the composition API and a closure function.

**Comment by m42e** [comment]
@hay-kot With recipe do you mean the `name` or are you referencing to the `slug`?

**Comment by hay-kot** [comment]
> @hay-kot With recipe do you mean the `name` or are you referencing to the `slug`?

Would be slug. Uniqueness is determined by slug and group_id in the database, so the check would need to validate that the recipe could be created.

**Comment by m42e** [comment]
I assumed that.

**Comment by Miroito** [comment]
@hay-kot What's left on this issue other than group names? I can probably take the rest over

**Comment by hay-kot** [comment]
Nothing has been done on the frontend so we need some way to add an async validation for the Vuetify inputs. I haven't looked into how to do that, but I suspect it will require some manual work to get it done and displayed correctly as their validators don't support async functions. I would like to see some additions made to the validation folder using the composition API to make these validations reusable across the application.

**Comment by hay-kot** [comment]
@Miroito, not sure if you're working on this, but I'm working on this as apart of the registration rewrite and will include it in the PR

**Comment by Miroito** [comment]
I hadn't started anything, please go ahead.
