### ISSUE TITLE
[v1.0.0b] [Task] - Food/Unit Bootstrap Values should be Translatable

### ISSUE THREAD

**Issue by hay-kot** [mealie-recipes/mealie#835]
### What is the problem this task addresses?

On Startup, Mealie will bootstrap the database with common units and foods. These should be translatable.

### Proposed/Possible Solution(s)?

See `mealie/db/data_initialization` for details on how bootstrapping is done and where .json files are currently stored.

Code needs to be written to convert the current list implementation in the json file to a key/value based file. The importer needs to be updated according. 

**Before**

```json
[
    {
        "name": "cup",
        "description": "",
        "fraction": true,
        "abbreviation": "cup"
    }
]
```

**After**

```json
{
    "cup":  {
        "name": "cup",
        "description": "",
        "fraction": true,
        "abbreviation": "cup"
    }
}
```

**Before**

```json
[
    {
        "name": "acorn squash",
        "description": ""
    }
]
```

**After**

```json
{
   "acorn-squash": {
        "name": "acorn squash",
        "description": ""
    }
}
```

**Comment by alexbarcelo** [comment]
I was looking into how to translate food & units. Is there a mechanism already in place? I could not find documentation or issues for it, maybe I am looking at the wrong place. I can provide translation for spanish and catalan if they do not exist yet.

**Comment by zierbeek** [comment]
the translation itself would be handled by Crowdin, a community platform for translations. Their needs to be a list for the exiting stuff with the units as a list which is said by hay-kot at the beginning

"See mealie/db/data_initialization for details on how bootstrapping is done and where .json files are currently stored."

**Comment by alexbarcelo** [comment]
> See mealie/db/data_initialization

I have no idea where to look. The db folder has an empty `__init__.py`. There is no data_initialization file there. A `grep` on the codebase yields no result when looking for `data_initialization`. There is no file that starts with that. If I use the github search for that term then I end up on this same issue. The documentation has no apparent "db"/"database" section with this. Am I looking at the wrong branch? At the wrong repository? An actual link would help a lot.

**Comment by hay-kot** [comment]
https://github.com/hay-kot/mealie/tree/mealie-next/mealie%2Frepos%2Fseed%2Fresources

Things have moved around alot sorry for the confusion. There currently isn't any support for setting the language that the seed data will use, and it also isn't setup in the translation software to look at this folder.

I believe the refactoring of the structure of the JSON file has already been done though.

**Comment by alexbarcelo** [comment]
Thanks! Sorry, I didn't want to sound demanding, I was just a bit confused. Then I'll keep an eye in order to help with the translation or the process :smiley:
