### ISSUE TITLE
Reference/Addendum Pages

### ISSUE THREAD

**Issue by shimizurei** [mealie-recipes/mealie#840]
### Discussed in https://github.com/hay-kot/mealie/discussions/802

<div type='discussions-op-text'>

<sup>Originally posted by **shimizurei** November 15, 2021</sup>
**Before submitting this feature request I have**

- [x] Reviewed the documentation and verified that my feature request isn't already a feature.
- [x] Reviewed the existing feature requests and my feature has not been requested.
- [x] Checked the [tasks tagged](https://github.com/hay-kot/mealie/issues?q=is%3Aissue+is%3Aopen+label%3Atask+) issues and verified my feature is not covered

**Please Describe The Problem To Be Solved**

Reference pages. Since there is already a custom page option, what if you could create a blank page and for example, make a note of common substitutions? For example, when I run out of eggs, I like to substitute applesauce in for my eggs. There are a ton of possible substitutes for many ingredient parts and it would be nice to collect them in one place.

**Suggest A Solution**

The page function doesn't have to be that detailed. Just create a blank, custom page and using Markdown, add your info. Then have a "References" or "Addendum" page that collects all these little note/reference pages into one. Then the page can be added to the sidebar.</div>

**Comment by hay-kot** [comment]
There's no need to create an additional issue. Feature requests should be submitted in the discussions page as you have already done.
