### ISSUE TITLE
Setting RECIPE_PUBLIC to "False" does nothing

### ISSUE THREAD

**Issue by SteveDinn** [mealie-recipes/mealie#890]
Even though my mealie instance is publicly accessible, I don't want to share my recipes with the world. I tried setting
```
environment:
  RECIPE_PUBLIC: "False"
```
in my docker-compose.yml, but it appears to have no effect.

I'm running on Ubuntu 20.04 under docker (obviously) on an x64 processor. Testing by accessing the instance via an incognito Chrome Window - both from Android and Linux.

**Comment by tyrrminal** [comment]
The environment variable sets the default value for the recipe-specific public flag, which means that it only applies to new recipes created after it was changed. Each recipe you already made has a public/private switch in its settings, which you can toggle to hide it from public view.

**Comment by SteveDinn** [comment]
I totally missed this whole menu somehow. Thanks!
