### ISSUE TITLE
Error starting Mealie after updating the Mealie-container

### ISSUE THREAD

**Issue by NightFalcon650** [mealie-recipes/mealie#896]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Error starting the Mealie container after updating.

Steps i took according to update manual:
- stopping the old container (`sudo docker-compose down`)
- updating containter (`sudo docker-compose pull`)
- starting container (`sudo docker-compose up`)

Error message is:
![image](https://user-images.githubusercontent.com/7109209/147848332-aa7b7b11-585c-42aa-b173-ab649599b639.png)

### Deployment

Docker (Linux)

### Deployment Details

![image](https://user-images.githubusercontent.com/7109209/147848416-362715c7-6ead-4c86-8a49-0cb71d06e846.png)

### Mealie Version

0.53 (Latest docker-compose pull)

**Comment by hay-kot** [comment]
You could try moving or renaming the /app/data/recipes/ folder while the container is down and then starting it back up. It's running into issues because the directory already exists but it shouldn't. Maybe it failed half-way through the migration for some reason?

**Comment by NightFalcon650** [comment]
> You could try moving or renaming the /app/data/recipes/ folder while the container is down and then starting it back up. It's running into issues because the directory already exists but it shouldn't. Maybe it failed half-way through the migration for some reason?

Yep i noticed that it went wrong with the migration. I tried several things, but in the end  i just deleted everything and did a new docker-compose up to build Mealie up from scratch. After this i restored everything through a backup.
Now it work again but a new point came up. 

It did a pull for the new container, the latest and this is 0.5.3 and not the latest 0.5.4. How is this possible, normaly you would think that it pulls the latest version?

**Comment by hay-kot** [comment]
The most recent release has the wrong version listed somewhere. So it's likely the right container, I just missed the version somewhere.

**Comment by NightFalcon650** [comment]
> The most recent release has the wrong version listed somewhere. So it's likely the right container, I just missed the version somewhere.

Ah oke. In that case i'll wait for the next version :-D

Thanks

**Comment by hay-kot** [comment]
Closing since the original issues has been solved, thanks!
