### ISSUE TITLE
Trim whitespace from URL when importing

### ISSUE THREAD

**Issue by tjjunior** [mealie-recipes/mealie#901]
Describe the bug
When importing a recipe by URL, extra whitepaces at the end of the URL will cause the import to fail with a Must be a Valid URL error

Steps To Reproduce
    Click Plus -> Import a recipe
    Type in "http://allrecipes.com/recipe/6925/monkey-bread-v/ " (without quotes, note extra space after the final slash)
    Mealie will give an Invalid URL error message
    Try again without the extra space and it will succeed

Expected behavior
Trim the whitespace from entries so extra spaces at the end will be ignored

Actual Behavior
User can not import with trailing whitespace

Note, this is the same issue as bug #475 but on the Import function instead of the login function.

**Comment by apoorvkh** [comment]
On this note, might as well strip the parameters from original URLs before saving.

For example:
`https://cooking.nytimes.com/recipes/1022828-skillet-poached-eggs?action=click&region=Sam%20Sifton%27s%20Suggestions&rank=2`
could instead be saved as
`https://cooking.nytimes.com/recipes/1022828-skillet-poached-eggs`

**Comment by tjjunior** [comment]
I didn't specifically mention it, but it also fails when there are extraneous spaces at the start of the URL.

**Comment by MidnightRising** [comment]
> On this note, might as well strip the parameters from original URLs before saving.
> 
> For example: `https://cooking.nytimes.com/recipes/1022828-skillet-poached-eggs?action=click&region=Sam%20Sifton%27s%20Suggestions&rank=2` could instead be saved as `https://cooking.nytimes.com/recipes/1022828-skillet-poached-eggs`

This actually isn't the case with Javascript:

`let testStr = ' foo bar biz'
 testStr.trim()
 -> 'foo bar biz'`

I'll look into it.

**Comment by MidnightRising** [comment]
Pull request #907 should address this.
