### ISSUE TITLE
[v1.0.0b] [Task] - Intelligent/Automated Meal Planning

### ISSUE THREAD

**Issue by hay-kot** [mealie-recipes/mealie#913]
### What is the problem this task addresses?

Having to cook for the family every week and taking under consideration the schedules for all children can be "complex". Let's say you want to eat salat two days a week. Two days the meal must be prepared, since the kids are coming home late. Creating a meal plan simplifies this process a lot. However, in my experience, eventually you forget to create one for the next week, and at some point you stop creating one at all. Having a meal plan that is creating itself and takes some rules under consideration, would let you come back to using the meal plan at any point in time, even if you have stopped for some days/weeks/months.

### Proposed/Possible Solution(s)?

It would be great to be able to define auto assignment rules for meal planning. These rules could be based on categories (like now), plus certain categories/tags for each day of the week. Meals could then be tagged with "preparable", "salad", "casserole", "soup", ... and a meal plan could be created automatically some time in advance (i.e. always one week in advance, or a configurable amount of days in advance). The rules could then maybe read:

```
Only use recipes from the category "Main dish"

* Monday: must be tagged with "casserole"
* Tuesday: anything (no further rules)
* Wednesday: must be tagged with "soup"
* Thursday: must be tagged with "salad"
* Friday: must be tagged with "salad"
```

**Comment by zierbeek** [comment]
a small addition to receive a notification when it's time to set up your mealplan rules?

**Comment by hay-kot** [comment]
> a small addition to receive a notification when it's time to set up your mealplan rules?

I'm not sure what you mean? Wouldn't you just need to set the meal plan rules one time, what do you need a notification for?

**Comment by spieker** [comment]
I think, it would be more interesting to receive a notification once a new meal plan is available (i.e. to connect it with Home Assistant or so).
