### ISSUE TITLE
Docker image for 0.5.4 says its 0.5.3 and needs update

### ISSUE THREAD

**Issue by TheSander562** [mealie-recipes/mealie#926]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Using the docker version 0.5.4, when you go to the /admin/about page it says it is using 0.5.3 and not mealie 0.5,4 so it says i need to update but i am using the latest docker image from https://hub.docker.com/r/hkotel/mealie.
![Schermafbeelding 2022-01-13 143940](https://user-images.githubusercontent.com/14059770/149340863-6d00265a-9df7-47b0-942b-25a4c1229a40.png)

### Deployment

Docker (Synology)

### Mealie Version

0.5.3

**Comment by zierbeek** [comment]
Hi, doesn't matter, @hay-kot did screw up somewhere in the code and didn't change the version number. nothing to worry about :)

**Comment by TheSander562** [comment]
Ah alright, so i am using 0.5.4? 😮🤔
How can i check this?

**Comment by zierbeek** [comment]
Yes! ;)
