### ISSUE TITLE
No built-in back to search functionality

### ISSUE THREAD

**Issue by nkringle** [mealie-recipes/mealie#931]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

[Reference Discussion](https://github.com/hay-kot/mealie/discussions/929#discussioncomment-1972120)

When using mealie in a browser that doesn't have a back button (ex: if installing the app as a "bookmark" in ios or potentially as a PWA), when you go to search or navigate through categories/tags/etc. and then go into a specific recipe there is no back functionality. 

### Deployment

Docker (Linux), Other

### Deployment Details

Docker on Mac, proxied by trafik with a let's encrypt certificate.

### Mealie Version

v0.5.4

**Comment by epheterson** [comment]
This is actually a pretty significant issue, because even with the back button the search is discarded when using browser back button. There should either be a back button, or search should be remembered when using browser back button (not sure how tricky that is).

**Comment by ViperJPB** [comment]
100%. Makes browsing and searching very difficult. Especially if browsing through a long list of recipes. Click on one…decide that’s not the one…hit back to continue browsing just to have your last location while browsing reset to the top. Major thing for my wife.

**Comment by michael-genson** [comment]
FYI: with https://github.com/mealie-recipes/mealie/pull/3332 this is resolved. This fixes both the back button issue (your last search is remembered when hitting back) and the initial issue. Clicking on the Mealie logo in the upper left is now a "back to search" button, so it works even in PWAs
