### ISSUE TITLE
[v1.0.0b] [Task] - In App Help Template

### ISSUE THREAD

**Issue by hay-kot** [mealie-recipes/mealie#932]
### What is the problem this task addresses?

There is little to no documentation within the application itself.

### Proposed/Possible Solution(s)?

Mealie should provide some sort of "Help Button" available on certain pages that will pop-up a dialog with a summary of common questions or a How To Guide based on the page they're on. It may also be beneficial to list external sources for better documentation.

**Comment by zierbeek** [comment]
Or just a button which links to the docs page? Or would it also needed to be self-hosted?

**Comment by hay-kot** [comment]
> Or just a button which links to the docs page? Or would it also needed to be self-hosted?

My goal here would be to keep the user in the app. You shouldn't really need to read the documentation to _use_ the app. So if there tricky parts to using something, I want that information to be front and center in the app itself or inside of a help dialog. 

That way the documentation is only about deployment and management. Hopefully thay will improve usability.

Of course, we could always have links to the docs included in that.

**Comment by zierbeek** [comment]
yeah makes sense indeed! would be a tooltip then? 
https://vuetifyjs.com/en/components/tooltips/

**Comment by hay-kot** [comment]
I think there's two approaches.

- Tooltips for button that have a short descriptor text. For longer descriptors, using a v-menu may also be an option. 
- Dialogs for larger "documentation-like" references. For example, we could include a markdown reference dialog for quick access to some examples of how to embed images, videos, and the like.

**Comment by zierbeek** [comment]
Hmm yeah, well if you could give it a start, I'm more than willing to work further on it!

**Comment by hay-kot** [comment]
Great! I'll post an update here with some additional requirements once I layout a framework 👍

**Comment by hay-kot** [comment]
Going to close this since it's more or less complete at this point. I've decided to go with a simple help icon that can be used to help provide context around actions. This is both minimal and easily added to the UI through a global import

![CleanShot 2022-04-10 at 13 08 46](https://user-images.githubusercontent.com/64056131/162639974-8a35fe59-d882-47ac-ba2c-6e3694c5e79f.png)

Component at `frontend/components/global/HelpIcon.vue`

**Comment by zierbeek** [comment]
Good man! Will give it a try. What do you want explained?
