### ISSUE TITLE
Demo site was displayed in German despite me only having en_GB and en_US as browser languages.

### ISSUE THREAD

**Issue by doctorjames** [mealie-recipes/mealie#933]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When I tried the demo site today it was set to a German locale, and not speaking German, I found it very hard to test, or even find the admin settings.

I searched the help and found how to change the site to English. It might be a good idea to make the demo reset to English automatically, as many people are likely to just leave at that point. Even better would be to pick up the browser language settings for the demo.

### Deployment

Other

### Deployment Details

Author provided demo.

### Mealie Version

0.5.3

**Comment by doctorjames** [comment]
Another minor bug: after changing the locale in the admin settings and saving, the various action buttons (update/create) remain in the previous language until the page is refreshed.

**Comment by hay-kot** [comment]
This has been something we've discussed a few different times. I think with v1 the framework we're using for the frontend offers ALOT more support on managing locales, so most of these issues should be addressed. Additionally, there's a PR open that resolves a few of these issues.

- #925 

I don't think I'm going to put in any work to resolve this is the v0.5.x branch as we're pretty close to a beta release (I hope)
