### ISSUE TITLE
"Close" button in recipe editor saves changes

### ISSUE THREAD

**Issue by MichlF** [mealie-recipes/mealie#943]
### What is the issue you are experiencing?

When editing recipes, the close function/button saves changes. Thereby it behaves just like the save button. The log shows no errors/issues.

### Deployment

Docker (Synology)

### Mealie Version

v0.5.4

**Comment by hay-kot** [comment]
If you refresh the page are those changes still present?

I believe the issue here is the it doesn't save the initial state and when you hit close, it doesn't refetch the server state to get the actual contents, it just uses whatever is in the browser.

**Comment by MichlF** [comment]
Should have checked that more throroughly. It disappears, like you say, with a refresh.
Nonetheless, for my non-tech-savy grandma this may not immediately be apparent and should, if possible, be fixed even if it's more of a visual bug.

**Comment by hay-kot** [comment]
Agreed. Just wanted to clarify I understood the issue 👍

**Comment by PFischbeck** [comment]
I think this is already fixed in `mealie-next`, so look forward to version 1.0 😄 

https://github.com/hay-kot/mealie/blob/40d1f586cd73a13b873b5eec70a3a0dc656ec9e4/frontend/pages/recipe/_slug/index.vue#L610-L614
