### ISSUE TITLE
Unable to update recipe image using the URL functionality

### ISSUE THREAD

**Issue by humantree** [mealie-recipes/mealie#949]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When I edit a recipe and try to select a new image URL, the image never gets updated.

The logs show that the image appears to be minified, but no change ever takes place:

```
INFO: 23-Jan-22 10:29:31 Image URL: https://hips.hearstapps.com/ame-prod-redonline-assets.s3.amazonaws.com/main/thumbs/293/1289899045-duck-breasts-with-a-port-and-berry-sauce.jpg
INFO: 23-Jan-22 10:29:31 File Name Suffix .jpg
INFO: 23-Jan-22 10:29:32 original.jpg Minified: 57.51 kB -> 38.51 kB -> 10.97 kB
```

I tested this with multiple URLs and multiple recipes and had the same result.

If I use the image upload functionality the image is successfully updated.

### Deployment

Docker (Linux)

### Mealie Version

v0.5.3

**Comment by jrcatoe** [comment]
@hay-kot this isn't tagged as a 'beta' bug, but I have the same issue on the beta site. I was able to change the image via an upload, but was not able to use the URL grab method.
