### ISSUE TITLE
[v1.0.0b] - Ingredient Parser (unable to add new foods)

### ISSUE THREAD

**Issue by coffee-mage** [mealie-recipes/mealie#955]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When parsing ingredients of a new recipe (using the Natural Language Processor).  I have unmatched foods.  I can pick from the existing food list, and it works.  But if I try to add a new food (from parser interface), it fails.   

I have tried two approaches:
1) '+ Create missing food 'parmesan cheese'?  button
2) Click choose food dropdown box, type the new food name, and hit enter.
3) Click choose food dropdown box, type the new food name, and hit green Create button.

All three approaches have the same result.   In the chrome inspect window, I see a REST request to https://beta.mealie.io/api/foods,  with the following payloads.
{id: 0, name: "parmesan cheese", description: "", labelId: ""}

I get a 422 response code with this:
{"detail":[{"loc":["body","labelId"],"msg":"value is not a valid uuid","type":"type_error.uuid"}]}

I tried to manually add a food in the Manage Foods UI, and it worked but the REST call was slightly different.  LabelID was populated.  My attempts above did not have labelid.  
{id: 0, name: "parmy cheese", description: "", labelId: "20b308d2-668c-4de6-bbee-f3cd27d258be"}

### Deployment

Other

### Deployment Details

beta.mealie.io

**Comment by coffee-mage** [comment]
It looks like the food api is expecting labelId = null, if there is no food label.  I think we are passing "" (from the input form) instead of null.

This appears to be a problem in both ingredient-parser.vue, and foods.vue.

**Comment by hay-kot** [comment]
Fixed! Thanks for the heads up.
