### ISSUE TITLE
Images no longer cropped down in v0.5.5

### ISSUE THREAD

**Issue by CorneliousJD** [mealie-recipes/mealie#961]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

After the v0.5.5 update, images are no longer cropped down when viewing i recipe on the desktop (it still seems to work fine on mobile)

This means full images are now shown pushing the recipe very far down on the page.

Here is an example image of what I mean.
It used to crop the image to give everything a nice uniform height.

![image](https://user-images.githubusercontent.com/724777/152545247-1e4e922b-9fad-4d6d-8f89-7d203b7a7d63.png)

### Deployment

Docker (Linux)

### Mealie Version

0.5.5

**Comment by hay-kot** [comment]
Yikes, will roll out a fix today thanks for reporting!

**Comment by hay-kot** [comment]
Build in progress 👍 

https://github.com/hay-kot/mealie/actions/runs/1796210589

**Comment by hay-kot** [comment]
Confirmed that this is no longer an issue in the latest version, thanks!
