### ISSUE TITLE
API example creates un-editable recipe.

### ISSUE THREAD

**Issue by zzqzzqzzq** [mealie-recipes/mealie#966]
Something about the "Chicken and Rice With Leeks and Salsa Verde" "Create From JSON" example recipe in the Swagger UI creates an uneditable recipe if you use it.     The UI displays a "Recipe update failed" when trying something as simple as editing the description.

If one removes: 

  "extras": {
    "message": "Don't forget to defrost the chicken!"
  }

From the sample JSON, this does not occur.

Tested with v0.5.6

**Comment by m42e** [comment]
I can reproduce it, having the `extra` field also prohibits asset uploading. 
For now I put my extra into notes.
