### ISSUE TITLE
[v1.0.0b] - Form creation of users misstores the password in the database (non-hashed)

### ISSUE THREAD

**Issue by alexbarcelo** [mealie-recipes/mealie#967]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

If a user is created through the "register" mechanism, everything seems to work as expected.

However, if one creates a user through the admin interface (i.e. at /admin/manage/users by following the form), that user is created in  the database but the password field is not hashed. This causes an error and that user cannot login to mealie.

That means that user creation through the admin interface results in users that cannot login.

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
Big yikes, thanks for reporting. Will catch it in the next round of updates. Thanks for the detailed issue!

**Comment by hay-kot** [comment]
Fixed with tests, thanks!
