### ISSUE TITLE
Can't log in to demo site

### ISSUE THREAD

**Issue by jtatum** [mealie-recipes/mealie#975]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

The username and password in the banner of the demo site don't work. I get this error: 
```
Could Not Validate Credentials
```

### Deployment

Other

### Mealie Version

0.5.7

**Comment by hay-kot** [comment]
Thanks for the heads up, I reset the container. Should be good to go now 👍
