### ISSUE TITLE
error? in the logs - mealie.db.models.mealplan.MealPlan

### ISSUE THREAD

**Issue by Symbiot78** [mealie-recipes/mealie#981]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

something I haven't noticed before has started popping up in the logs.

[<mealie.db.models.mealplan.MealPlan object at 0x7f098b572b20>, <mealie.db.models.mealplan.MealPlan object at 0x7f098b57b250>],

this may be normal but it's something I haven't noticed before - so I just wanna check.

### Deployment

Docker (Linux)

### Mealie Version

0.5.6

**Comment by hay-kot** [comment]
This is what it looks like when you log or print a python object to the stdout. Nothing to worry about, just forgot to cleanup some debugging text when I pushed the last release.
