### ISSUE TITLE
Frontend density - more than 3 recipes across

### ISSUE THREAD

**Issue by woobenjamin** [mealie-recipes/mealie#982]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I think I have searched through the docs, etc. but I can't seem to figure out how to get more recipes to show per screen. Right now it is 3 across. I'd love to have smaller recipes but more across. So not sure if this is a bug or a feature request. 

Thanks.

### Deployment

Docker (Linux)

### Mealie Version

0.5.6

**Comment by hay-kot** [comment]
This isn't something that's currently supported, you can submit a feature request if you'd like. See the process below

- https://github.com/hay-kot/mealie/issues/317
