### ISSUE TITLE
[v1.0.0b] - Ingredient Parser doesn't seem to save ingredients properly

### ISSUE THREAD

**Issue by coffee-mage** [mealie-recipes/mealie#986]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Trying to add Asparagus Salad recipe to mealie.   I bulk add ingredients:
***
1 teaspoon salt
300 g asparagus, ends trimmed; stalks peeled
1/4 cup slivered almonds, toasted
1 shallot
1 pinch black pepper
2 tablespoons vinaigrette
50 g feta cheese
***

The add food feature from parser seems to work now.  The parser identifies the ingredients correctly:
![parse_view](https://user-images.githubusercontent.com/14890934/154954287-f4aa2fb0-1091-487a-a855-a937c7f93425.JPG)

After I hit save, the parsed ingredients don't seem to be saved properly.  It only seems to grab amount and notes.  Units and foods are blank.
![ingredients_after_parse](https://user-images.githubusercontent.com/14890934/154954408-dc4fff5d-3293-47b8-ba97-662d7800a1ee.JPG)

### Deployment

Other

### Deployment Details

beta.mealie.io

**Comment by hay-kot** [comment]
Hmm. Doesn't look like any ingredients are being saved properly, thanks for reporting.
