### ISSUE TITLE
[v1.0.0b] - Created recipes missing from All Recipes

### ISSUE THREAD

**Issue by coffee-mage** [mealie-recipes/mealie#988]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I may be doing something incorrectly, but when I create a recipe.  I am unable to find it in the 'All Recipes' section.   I am able to find it in the meal planner tool.

Steps to reproduce
---------------------
+ Create button.
Fill in ingredients (tried both parsed and regular text).  
Fill in directions.
Hit Save
Click on All Recipes sidebar.
Search for recipe just created.

### Deployment

Other

### Deployment Details

beta.mealie.io

**Comment by hay-kot** [comment]
I think the issue here is that the "All Recipes" is returning there recipes in reverse order, so Oldest first. It should default to Newest first

**Comment by coffee-mage** [comment]
I think it is something with the cache not being refreshed on create?   I was searching for my recipes (using search function).  I couldn't find anything.  Then I logged out,  logged back in, and everything appeared.

**Comment by hay-kot** [comment]
I think this is now fixed in beta. Can you confirm?

**Comment by coffee-mage** [comment]
Fixed.
