### ISSUE TITLE
[v1.0.0b] - Can't rate recipes

### ISSUE THREAD

**Issue by coffee-mage** [mealie-recipes/mealie#992]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When I try to rate a recipe (in view page, or in all recipe page).  I get an error message 'recipe already exists'.

### Deployment

Other

### Deployment Details

beta.mealie.io

**Comment by hay-kot** [comment]
Fixed! Thanks!
