### ISSUE TITLE
[v1.0.0b] - Enter not working for creating an ingredient in safari 

### ISSUE THREAD

**Issue by zierbeek** [mealie-recipes/mealie#994]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When my ingredients are parsed, I'm unable to go to a box of an ingredient an tap enter to create the ingredient. This is working when clicking the button '+create'

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
This is working on my Macbook Pro. What version of Safari are you using?

**Comment by zierbeek** [comment]
using version 15.3 (17612.4.9.1.5). Tried it again but no luck. 
Also tried in chrome and also did not function. Can I help you troubleshoot this further?

**Comment by hay-kot** [comment]
Can you record and video and/or provide the browser console logs when you performed the action?

**Comment by Sennevds** [comment]
I have the same problem in MS Edge (Version 98.0.1108.62 (Official build) (64-bit))
For the unit enter works but not for a ingredient.
When using enter I get the following in my console:
```
{__ob__: Nt} 
```
Which expands to:
```json
{
    "name": "0 verse tijm",
    "description": "",
    "labelId": null
}
```
When clicking on the create button I get a post to /api/foods.
If you need more info let me know

**Comment by Sennevds** [comment]
I tried it locally and there it's working so it's a bit harder to debug then I hoped

**Comment by zierbeek** [comment]
locally I didn't have succes

**Comment by zierbeek** [comment]
> Can you record and video and/or provide the browser console logs when you performed the action?

https://we.tl/t-zj0pXBDFwm

**Comment by zierbeek** [comment]
https://user-images.githubusercontent.com/58994651/156152577-788d2b6a-2166-49ec-95bb-36d10a941342.mov
