### ISSUE TITLE
[v1.0.0b] - Favourite button displays TypeError

### ISSUE THREAD

**Issue by coffee-mage** [mealie-recipes/mealie#999]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When clicking favourite button (on allrecipes or recipe page), console displays type error.

<img width="595" alt="favourite" src="https://user-images.githubusercontent.com/14890934/155295856-6655fbcb-69a6-4335-aa4c-b4f1c4a9d5a5.png">
Even though it shows type error, the favouriting seems to work.

Also what can we do with favourites?  I think I can set it and unset it, but I don't seem to be able to search by favorites?

### Deployment

Other

### Deployment Details

beta.mealie.io

**Comment by hay-kot** [comment]
Fixed the type error. Currently favorites don't do anything, but there will be a page to view them eventually...
